- web/concrete/src/Page/Controller/PageController.php
I changed this if statement to check if theme is null. This allows for `$this->theme = false` to be used in an action to disable the theme for just that action instead of having to override `getTheme()` and disable it for the entire controller.
> Allow theme to be set to false

- web/concrete/elements/page_controls_header.php
- web/concrete/js/build/core/app/edit-mode/blocktype.js
- web/concrete/js/build/core/app/edit-mode/editmode.js
- web/concrete/js/build/core/app/panels.js
- web/concrete/js/build/core/app/toolbar.js
Regarding issue #1688
- Clicking on the add block button opens it (but does not lock it)
- Clicking a second times locks it down.
- Clicking a third time closes it
If the panel is not locked (pinned) then no change from previous behavior.
If the panel is pinned, it is reopened after a block had been added (or its add form closed/cancel).
Tell me how you guys feel about it.
> allowed the add block panel to be pinned down

- web/concrete/src/Routing/Redirect.php
When pretty URLs were enabled, "index.php" was preserved in the redirect URLs.
You can see this e.g. if you set a language section to the site and enable root redirection to the default language.
> Fixed page redirects with pretty URLs

- web/concrete/src/Localization/Localization.php
- web/concrete/src/Multilingual/Service/Detector.php
- web/concrete/src/Package/Package.php
I think that I finally managed to fix the localization stuff.
Now everything should be fine: callink Localization::changeLocale loads the core + package + site language files.
BTW, we've got some breaking change here. IMHO they're quite minor, but a feedback from the core team is needed:
1. I removed Localization::addSiteInterfaceLanguage: it's useless since changeLocale does everything that's needed
2. Package::setupPackageLocalization had an unused `$key` parameter. I replaced it with the `$translate` parameter that's needed by Localization::changeLocale.
> Fix localization

- web/concrete/blocks/image_slider/view.php
If a user is not placing a title for each slide, the h2 tag of the title is empty. This causes a warning with w3c-validation.
If a user is not placing a title for each slide, there is no alt-tag inside img-tag. This causes validation-error with w3c-validation.
In my fix the h2-tag is not shown, when the title of the image is empty. Same for the alt-tag.
> Remove empty h2-tag, add placeholder alt tag

- web/concrete/src/Page/Type/Composer/Control/Control.php
- web/concrete/src/Page/Type/Composer/Control/Type/BlockType.php
* The name of Block Types are not localized
* The name of Core Page Properties and Collection Attribute Types are localized twice
> Fix to get localized Page Type Composer Control Name

- web/concrete/views/panels/details/page/attributes.php
When the page attributes panel is open and an attribute is added to the
active list, there is no visual feedback that something has been added.
The newly added attribute is added to the bottom of the page, but this
is normally beyond the viewport, requiring a scroll to see it.
This line automatically scrolls the viewport to the bottom, showing the
newly added attribute.
> Scroll to bottom of page when adding an attribute

- web/concrete/src/Permission/Assignment/BlockAssignment.php
If an Area overrides the master collection permissions, the instances of the Area should overrides each collections.
> Double check whether the Area overrides the collection permission

- web/concrete/css/build/core/app/panels/add-block.less
This dropdown menu is hard to recognize as the clickable area.
> Add hover style to add block header accordion

- web/concrete/src/Area/CustomStyle.php
When using more than one custom classes in an area, the inline CSS was like this: ".ccm-custom-style-area.first-class second-class"
(Only the first space was replaced with a dot)
I've fixed this by using the same code as in /src/Block/CustomStyle.php
Thanks,
Jordi
> Fix inline CSS when having several custom classes

- web/concrete/blocks/autonav/form_setup_html.php
- web/concrete/blocks/page_list/page_list_form.php
- web/concrete/css/build/vendor/bootstrap/bootstrap.less
- The fieldset tags in the autonav and page list blocks weren’t nested
correctly, this change corrects the nesting
- Adds some padding to bottom of fieldset to correct spacing between
fieldsets
> Updates to autonav and pagelist fieldset tag nesting

- web/concrete/blocks/social_links/controller.php
When a theme without Font Awesome as a required asset was used, the social link icons were not displayed correctly.
> Add Font Awesome as required asset

- web/concrete/src/Sharing/ShareThisPage/Service.php
we're wanting to have a 'share this' on each instance of a page
in a page list template and thought it would be nice to use the code
that is in core already, but this would only share the page the user
is currently viewing. This PR would allow for a custom page to
optionally be passed in to override this behaviour.
> allow a page to be passed to getServiceLink

- web/concrete/bootstrap/helpers.php
Let's assume that ZF2 loaded from a .po file a plural translation string, for instance the one used in:
```php
t2('You have one message', 'You have %s messages', $n);
```
If we call `t` against its singular form, like for instance
```php
t('You have one message');
```
ZF2 will return an array.
Let's be sure we result in a string.
> Fix t problem for some special case

- web/concrete/config/concrete.php
- web/concrete/src/Session/Session.php
NativeSessionStorage need prefix “cookie_” in parameters.
see: 
http://api.symfony.com/2.6/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.html#method_setOptions
http://php.net/session.configuration
> Fix cookie config

- build/README.md
Add Composer Note to Asset Build Readme
`npm install` fails with error in `generate-constants.php` if third
party PHP dependencies have not been install via Composer.
> Add Composer Note to Asset Build Readme

- web/concrete/src/Authentication/AuthenticationType.php
Fixed a bug only rendering a authentication type once (usefull when adding then to a page).
http://www.concrete5.org/developers/bugs/5-7-3-1/authentication-type-renders-only-once/
> Authentication type only renders once

- web/concrete/bootstrap/configure.php
- web/concrete/src/Foundation/Environment.php
- web/concrete/src/Page/View/PageView.php
- Addition of new DIRNAME_PAGE_TEMPLATES define
- Addition of DIRNAME_PAGE_TEMPLATES to Environment overrides list
(removal of DIRNAME_PAGE_TYPES)
- Adjustment of PageView to look at page_templates and package when applicable
- New page_templates empty dir in /application
- Removal of defunct page_types folder from /application
> Fix to for page templates to be found in packages

- web/concrete/composer.json
- web/concrete/composer.lock
- web/concrete/controllers/single_page/dashboard/system/multilingual/translate_interface.php
- web/concrete/single_pages/dashboard/system/multilingual/translate_interface.php
- web/concrete/src/Multilingual/Page/Section/Section.php
- web/concrete/src/Multilingual/Page/Section/Translation.php
- web/concrete/src/Multilingual/Service/Extractor.php
- Upgrade gettext/gettext to v3.1
- Rename \Concrete\Core\Multilingual\Page\Section\Translation::getID to getRecordID since \Gettext\Translation introduced getID itself in 3.1
- Save multilingual sections accordingly to the section plural rules
- Fix extracting translations from not-existing folders (before we had an Exception)
> Localization improvements and fixes

- web/concrete/blocks/core_scrapbook_display/controller.php
The uninstall of blocks sometimes leaves the clipboard in a state
where getInstance() calls on non-objects breaks pages (with no way
to resolve it via the interface).
This adds some extra checking to check if block objects are in fact real
objects.
> More defensive clipboard block loading

- web/concrete/src/Multilingual/Service/Detector.php
Currently we use a wrong config key and we pass accept-language quality value instead of locale to Section::getByLocaleOrLanguage
> fix multilingual browser detection redirection

- web/concrete/blocks/form/controller.php
When the form is successfully submitted, redirect to the correct anchor position.
> Fixed form submit anchor position

- web/concrete/src/Legacy/ImageHelper.php
The legacy Image helper has everything needed to set a default compression level, but it doesn't use it at all. Setting the compression level will have absolutely no effect when an image is saved.
This small change fixes that.
> Add compression level to Image helper

- web/concrete/src/Application/Application.php
- web/concrete/src/Localization/Localization.php
- Store package load state in config, don't rely on cache (it may be disabled)
- Make sure we reload the localization files when we clear the localization cache
> Localization fixes about package load state and cache handling

- web/concrete/controllers/single_page/dashboard/system/multilingual/translate_interface.php
- web/concrete/src/Multilingual/Page/Section/Section.php
In #1841 I changed the order of the loaded translations, since in the generated .po files it's better to keep the original order.
BTW, IMHO it's better to keep the untranslated strings at top in the concrete5 UI (at last until *someone* - like me - implements a more complete translators interface :wink:)
> Restore the previous ordering of translations when translating

- web/concrete/src/User/Group/Group.php
The function getUserIDs() is called getResultIDs() in the UserList class.
> Fix the call to undefined function

- web/concrete/src/Legacy/ImageHelper.php
Cached performance can be improved significantly by moving where the
$image variable is set to the conditional statement where the variable
is used.
> Cached Thumbnails (Issue #1945)

- web/concrete/src/Permission/IPService.php
Some proxy servers send unknown instead of the right IP address in the HTTP headers. It is also possible that they send it as a part of a list of IP addresses and the other addresses are valid in the list. When a proxy server send such a request, an error appears in concrete5 saying that there is an error with inet_pton(). This fix skips all entries with the text unknown.
> Some proxies send unknown instead of IP address in headers.

- web/concrete/src/Block/BlockType/BlockType.php
- web/concrete/src/Foundation/Environment.php
I need to override the autonav block controller for a multisite package we're building. In 5.6 you could do that by calling `Environment::overrideCoreByPackage()` from for example the package controller on_start method, however in 5.7 that doesn't work anymore, at least for block controllers. 
So this fixes that, unless you guys have a better solution for me?
> Allow overriding core block controllers from package

- tests/tests/Core/Permission/DurationTest.php
Use consistent values not `time()` since it is pretty difficult to
troubleshoot previous failed tests when the values being tested are not
known after the fact.
> Use Consistent Values for Repetition Tests

- web/concrete/config/install/base/permissions.xml
Fix Add Conversation Message Permission Install
- Add custom class declaration on installation of the
`add_conversation_message` installation
> Fix Add Conversation Message Permission Install

- web/concrete/controllers/dialog/block/aliasing.php
I was setting up a new page type, and I made some pages with the new page type. Then, I added a conversation block on a master collection of the page type. The pages that I already added has no conversation block. So, I added it on child pages from master collection. Finally, I posted some messages on conversation block. Strangely, same messages were appearing on each child page.
I found `$btCopyWhenPropagate` property on the controller of core conversation. So, we should duplicate a block instance of core conversation, instead of aliasing when copying it...Right? If so, I think there are additional issues related on this.
1. I think we should duplicate a conversation block when pasting from clipboard. How could we duplicate a block in the proxy block?
2. Should we duplicate a …
> Fix problems with aliasing Conversation blocks (work in progress)

- web/concrete/src/Permission/Key/Key.php
Remove extra `pkCategoryHandle` from select statment in `Key::loadAll()`
> Remove Extra pkCategoryHandle from Select loadAll

- web/concrete/config/database.php
- web/concrete/src/Database/DatabaseManagerORM.php
Adds exclusion of the core support directory from the Doctrine ORM annotation driver
Fixes #1975 and adds support for adding other exclusions as seen fit.
> Adds Exclusion of Support directory from Doctrine ORM AnnotationDriver

- tests/tests/Core/Foundation/ClassloaderTest.php
- web/concrete/src/Foundation/ClassLoader.php
Fix autoload for attributes that have additional classes defined in the
attribute `controller.php` file.
- Add class map for select `Option` class
- Add class map for address `Value` class
Note: This does not address autoloading in the /application directory
> Fix autoloader attributes

- web/concrete/src/Routing/DispatcherRouteCallback.php
Adds a forbidden page's cID to Session as 'rcID' to allow login controller to automatically forward to the page after a successful login. This functionality was available pre-5.7.
> Login forwarding for protected pages

- web/concrete/single_pages/dashboard/files/sets.php
To fix one of the requests from #1740 (that part was pretty much independent of all the rest) I did the following:
- Refactored the fileset page
- Change list to a table (using the same formatting than the file manager)
- Added more info to the list (file name, title, date)
- Added a little tweak to the sortable
- Added the ability to sort ability on titles
For information, the date is converted to a timestamp (int) for the sorting in order to avoid possible localization issues.
Also, the sort is not saved unless you hit the save button, and you can still move around the files after any sort. This should make working with large filesets a lot easier.
BTW, it now looks like this:
> [feature] Make fileset sortable by filename/title/date in dashboard

- web/concrete/config/concrete.php
- web/concrete/config/db.xml
- web/concrete/src/Multilingual/Page/Section/Section.php
- web/concrete/src/Updater/Migrations/Migrations/Version5732.php
Let's add the name of the plural cases.
Until now we have that, for instance, Russian has 3 plural cases, identified by `0`, `1` and `2`.
That's not a great help when translators have to translate plurals.
It's much better to identify plurals by `one`, `few` and `others` (the CLDR identifiers) and have some sample numeric range to explain when we have `one`, `few` and `others`.
For some sample plural data see http://mlocati.github.io/cldr-to-gettext-plural-rules/
I'm trying to find some time to improve the user interface to translate the site ( http://website/dashboard/system/multilingual/translate_interface/translate_po/... ) adding support for comments, plurals, location, filters, contexts... but it's better to start collecting the info about the plurals before the next 5.7 release.
> Add plural cases info

- web/concrete/src/Error/Error.php
Concrete\Core\Error\Error uses `\Exception` but calls it `Exception`...
> Add missing 'use Exception'

- web/concrete/blocks/html/form_setup_html.php
If the HTML block is saved without any changes (thus not triggering the on change event), the textarea remains empty and the content is lost.
This fix copies the editor contents into the textarea upon loading the block for editing, ensuring the content isn't emptied if nothing has changed.
> Prevent empty textarea overriding HTML block content

- .gitignore
- build/Gruntfile.js
- web/concrete/config/app.php
- web/concrete/controllers/single_page/dashboard/system/multilingual/translate_interface.php
- web/concrete/css/build/core/translator.less
- web/concrete/js/build/core/translator.js
- web/concrete/single_pages/dashboard/system/multilingual/translate_interface.php
- web/concrete/src/Multilingual/Service/Extractor.php
Here's a new interface to translate for the *Translate Site Interface* page.
Highlights:
- search function (in source language and/or in destination language and/or in contexts)
- show only translated and/or untranslated strings
- support for plural strings
- single-line translations for single-line source strings
- show comments, contexts and references
- saving via ajax
=====
Before:
=====
After:
> Better translator interface

- web/concrete/css/build/vendor/jquery-ui/jquery-ui.less
Changing overflow to visible on .ui-dialog prevents the tooltip from being cut off (see #845).
Chrome/Webkit has a bug where translate3d() on a position: fixed element causes it to behave as if it were position: absolute (also visible in the #845 screenshot, the tooltip isn't connected to the cursor).
> Fixes #845, HTML block tooltip getting cut off

- web/concrete/src/File/FileList.php
If a FileSet is paginated (e.g. in a block like List Files From Set,
or in somewhere like the File Manager), it uses ccm_paging_p as the
URL parameter to control which ‘page’ of results to display.
This parameter is the same used for the pagination of Page List blocks,
which means that if both are on the same page the blocks effectively
have linked pagination (incorrect behaviour).
By overriding in the FileList class the default parameter with
something unique, this problem is removed.
(there may be other classes that extend ItemList where this would be
worthwhile too)
> Unique pagination page parameter for FileList

- web/concrete/config/db.xml
We have this block of code duplicated for the BlockFeatureAssignments  table:
```xml
<index name="faID">
<col>faID</col>
<col>cID</col>
<col>cvID</col>
</index>
```
...it's not always true that [repetita iuvant](http://en.wikipedia.org/wiki/List_of_Latin_phrases_(R)#repetita_iuvant)... ;)
> Remove duplicated index in BlockFeatureAssignments table

- web/concrete/composer.json
- web/concrete/composer.lock
See https://github.com/mlocati/concrete5-translation-library/releases/tag/1.3.2
> Upgrade Translation Library to v1.3.2

- web/concrete/src/Asset/Asset.php
- web/concrete/src/Asset/CssAsset.php
- web/concrete/src/Asset/JavascriptAsset.php
minify() and combine() don't use any instance method/variabies, and they are called as static by `View->postProcessAssets()` (see https://github.com/concrete5/concrete5-5.7.0/blob/develop/web/concrete/src/View/View.php#L253 and https://github.com/concrete5/concrete5-5.7.0/blob/develop/web/concrete/src/View/View.php#L256)
> Mark minify and combine as static

- web/concrete/src/Mail/Service.php
- PSR-2
- allow send html-only emails (`$body === false` and `$bodyHTML !== false`)
- fix #2030
I tested this helper in the following cases:
- text-only email
- html-only email
- text + html email
- text-only email + attachment
- html-only email + attachment
- text + html email + attachment
- attachment only
- no body and no attachment
> Improve mail helper

- web/concrete/elements/files/search.php
- web/concrete/js/build/core/file-manager/search.js
- web/concrete/tools/i18n_js.php
Added 'Choose' back to the bulk options menu within the file managers 'choose' mode as per #1799.
There is a new switch `multipleSelection` that is supplied as part of the dialog call, an example:
ConcreteFileManager.launchDialog(function (data) {
for(var i = 0; i < data.fID.length; i++) {
ConcreteFileManager.getFileDetails(data.fID[i], function(r) {
// Do your stuff
});
}
}, { 'multipleSelection' : true });
If the switch is set to `true` an array of file IDs will be passed back, if the switch is not present or set to false you will get the standard object back, this preserves compatibility.
As per the last comment by @ahukkanen, I've disabled the auto selection only when a checkbox is clicked, you can click anywhere else on a row and get the selection functionality. The 'choose' bulk …
> File manager multi select

- web/concrete/css/build/core/app/toolbar.less
It is the 1px line between 'Add' and 'Powered', hard to see I know.
> Remove the border on the 'Powered by concrete5.' white label message

- web/concrete/elements/page_controls_footer.php
> Only display 'Powered by Concrete5' message when there is room for it

- web/concrete/controllers/single_page/dashboard/system/optimization/jobs.php
If we upload custom jobs in application directory, we will get ReflectionException.
> Avoid "Class does not exist" exception on Automated Jobs page

- web/concrete/blocks/feature/form.php
Changed the icon select in the Feature block to be fluid width instead of fixed, but still allowing that little space for the preview icon.
> Changed the icon select in the Feature block to be fluid width

- web/concrete/src/Database/Schema/Parser/ArrayParser.php
I'm trying to create an attribute category in 5.7 but always received a message `illegal offset 'columns'`. It took me a few minutes to track it down as my package is pretty big. I'd recommend to improve the error reporting as shown in this PR.
You can reproduce it if you create an attribute category with this in it:
```php
protected $searchIndexFieldDefinition = 'lID I(11) UNSIGNED NOTNULL DEFAULT 0 PRIMARY';
```
> check for proper column definition

- web/concrete/blocks/page_attribute_display/templates/date_time.php
Makes use of correct locale on multilingual websites.
> Use date helper in date time template of page_attribute_display block

- web/concrete/src/Support/Symbol/MetadataGenerator.php
This is similar to what I wrote to allow PhpStorm / IntelliJ to type detect \Core::make(), but now for \Package::getByHandle()
> Phpstorm metadata for packages

- web/concrete/src/Database/DatabaseManager.php
\Concrete\Core\Database\Connection\Connection extends \Doctrine\DBAL\Connection so nothing breaks
But this allows fancy entity autocompletion! (don't forget to regenerate symbols!
> Correct the docblocks so autocompletion works

- web/concrete/src/Application/Application.php
- web/concrete/src/Url/Resolver/PathUrlResolver.php
The detection of non standard ports doesn't work (bug introduced in https://github.com/concrete5/concrete5-5.7.0/commit/3b077519b0a7a31f8633f4b9a93a94ce24855166).
> Correct handling of requests on non-standard port

- web/concrete/blocks/autonav/controller.php
- web/concrete/js/build/core/sitemap/search.js
- web/concrete/src/Page/Page.php
- web/concrete/src/Permission/Response/PageResponse.php
I came across a [thread](http://www.concrete5.org/community/forums/customizing_c5/setting-permissions-on-external-page-links-in-autonav/) trying to figure out adding permissions and attributes for external links.
Adds 'Attributes' and 'Permissions' to the dropdown for External Links in the Sitemap.
Adds default permissions (Guest view, Admin edit) to an external link upon creation.
Removed code which was overridding the permissions checks, now they behave the same as normal pages.
> Edit attributes and permissions for external links

- web/concrete/src/Support/Symbol/MetadataGenerator.php
Legacy but still used so much in the core that this should be helpful.
> PhpStorm metadata generator for Loader::helper()

- web/concrete/src/Area/SubArea.php
When you set a custom template for an area (in code), then that custom template should also be applied when the user adds a gridlayout to that area.
This is a fix for the same issue as https://github.com/concrete5/concrete5-5.7.0/pull/2133, but the code is in SubArea instead of in BlockView. I think it's probably cleaner this way.
> Apply custom templates also to SubAreas

- web/concrete/composer.json
- web/concrete/composer.lock
- web/concrete/src/Authentication/Type/Facebook/ServiceProvider.php
- web/concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
Fixes #1694
There were a couple of problems preventing Facebook auth from working:
* Email scope permission wasn't being requested
* Username was being used, which Facebook removed support for
* The fallback username code resulted in a username of `_`
> Facebook Authentication

- web/concrete/src/Html/Object/HeadLink.php
> Avoid warnings in HeadLink::__constructor

- web/concrete/js/build/vendor/redactor/redactor.js
Related to #2153: that text should be added in redactor.js, just in case if someone doesn't include the redactor localization
> Add missing text in redactor.js

- web/concrete/src/Permission/Assignment/PageAssignment.php
We tried to use an undefined variable if there's no record in PagePermissionAssignments table
> Avoid warnings in PageAssignment::getPermissionAccessObject

- web/concrete/src/Backup/ContentImporter.php
This commit doesn't work for me:
https://github.com/concrete5/concrete5-5.7.0/commit/80935590a040912bf71bde30e908a67f9ce52bdd
Got an XML like this:
```
<?xml version="1.0"?>
<concrete5-cif version="1.0">
<attributekeys>
<attributekey handle="exclude_subpages_from_nav" name="Exclude Subpages from Nav" package="webwende_theme"
searchable="1" indexed="1" type="boolean" category="collection" attributeset="navigation"/>
</attributekeys>
</concrete5-cif>
```
Produces an error like this:
```
call_user_func() expects parameter 1 to be a valid callback, class '\Concrete\Package\MyPackage\Src\Attribute\Key\CollectionKey' not found
```
This is because you're checking the package of the attribute, but that's incorrect. You need to check the package of the attribute key category like I did in my pull …
> use package handle of attribute key category

- web/concrete/elements/page_controls_footer.php
- web/concrete/themes/dashboard/elements/header.php
This is a suggestion for more meaningful labels for the main toolbar buttons, more inline with their tooltips and purpose.
‘Add Page’ change to ‘Pages’  - This panel also has a very handy sitemap in it, so it’s not just about adding pages, it’s about navigating the pages of your site.
‘Settings’ change to ‘Page Settings’ - this button is referring specifically to the current page, whereas the word Settings seems too broad and could be interpreted to mean site settings.
‘Add’ to ‘Add Content’ - this button is always about adding blocks (or stacks) to a page, but the word add by itself could imply other things. Adding the word Content gives more context.
I’m sorry to be pedantic about these labels, but since these labels are about improving accessibility they should be as meaningful as …
> Suggested tweaks to toolbar button labels

- web/concrete/single_pages/dashboard/pages/themes/view.php
- web/concrete/src/Application/Service/UserInterface.php
UserInterface::button_js() wasn't using the provided parameters which was causing the remove button to display incorrectly on the themes page.
> Fixed UserInterface::button_js()

- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
I was trying to run the generate constants via grunt (cli) but league/url kept throwing a runtime exception that the port must be greater than 0 there really is no reason to try and set the port if its not set to anything.
> Only set the port if we have one

- web/concrete/src/Permission/IPService.php
A user can set any of the HTTP headers in the $serverVars array in their request and concrete5 will use that IP. Conversations, surveys, ip ban checks, session fixation checks and registration/login ip records are all using this.
> Prevent user from setting request IP

- web/concrete/controllers/single_page/login.php
Currently, if the configuration key `concrete.i18n.choose_language_login` is set, in the login page we ask the user's preferred language.
BTW, we don't do anything with that language: let's set the user's language to what he/she specify...
> Make language selection on login work

- web/concrete/src/Asset/CssAsset.php
Without this fix the code translates from
```css
background-image:url(data:image/png;base64,...);
```
to
```css
background-image:url(some/relative/path/data:image/png;base64,...);
```
> Don't change paths of urls that start with data: in CSS

- web/concrete/src/Block/CacheSettings.php
And use `isset` (much faster than `is_object`).
> Avoid accessing an undefined variable in Block/CacheSettings

- web/concrete/src/File/File.php
For some reason in the getID function we were returning the object... and not the ID which broke some stuff so now it actually returns the ID of the storage location
> Return the ID for storage locations

- web/concrete/src/Package/Package.php
Fixes part of #2169.
When https://github.com/concrete5/concrete5-5.7.0/commit/9ffea260d06bab58f85cc21c8703d2f248e44630#diff-870da868c5b9a1d629e57609bae3758eR84 was removed packages may not install right if they try to load any classes in the package because package autoloaders are only registered for those installed at the start of the request. That line was hiding this bug.
> Register package autoloader on install

- web/concrete/js/build/core/app/edit-mode/editmode.js
This seemed to fix up issue #1668 for me. Tested it in chrome and firefox and both work well for me.
> Fixes add block panel scrolling speed

- web/application/files/.gitignore
Is there a reason why this was removed? It is needed to install concrete5.
> Include empty files directory

- web/concrete/src/Error/Handler/ErrorHandler.php
I ran into some autoloading issues during which the translations weren't loaded yet.
I'd recommend to avoid using the t-function for internal / low-level exception.
If you really want to have them, at least make sure you don't use string concatenation as the order of the words can change depending on the language.
> no translations in emergy exception

- web/concrete/controllers/frontend/assets_localization.php
- web/concrete/js/build/core/redactor/inline.js
- web/concrete/js/build/core/redactor/magic.js
- web/concrete/js/build/core/redactor/specialcharacters.js
- web/concrete/js/build/core/redactor/underline.js
- web/concrete/js/build/core/redactor/undoredo.js
- web/concrete/js/build/vendor/redactor/redactor.js
- Get rid of `ccmi18n_redactor` global JS var and use Redactor `lang.get` method
- Synchronize vendor's `redactor.js` and `assets_localization.php`
- Translate `specialcharacters` plugin
- Translate `underline` plugin
- Translate `undoredo` plugin
> Complete Redactor translations and use standard translation approach

- web/concrete/css/build/vendor/select2/select2.less
- web/concrete/elements/files/search.php
The `wordwrap()` function is not multibyte friendly. Let's remove it and use css instead.
> Remove wordwrap

- web/concrete/elements/block_area_footer_view.php
- web/concrete/elements/block_area_header_view.php
Let's be sure to define `$class` before using it.
Furthermore: `getAreaCustomStyle()` returns `null` or an object, so let's use `isset` instead of `is_object` (much faster).
> Avoid accessing an undefined variable in block_area_header/footer_view

- web/concrete/src/Package/StartingPointPackage.php
- web/concrete/src/Page/Page.php
Draft pages inherits their permissions from their parent page (usually it is Home page). When we want to create a limited user account that will be allowed to create some types of page, we have to change the permissions of Draft (/!drafts) page. If not, the limited user will get weird "Not Found" page when creating a new draft page, because the user can't access to editing permissions of "Home" page. It is not intuitive. This change helps people who wants to setup Advanced Permission mode.
1. `/!drafts` page should have own permissions, not inherit from Home page
2. Assign "Page Owner" to some permissions that are required to access to Composer interface
3. A new draft page inherits its permissions from `/!drafts` page.
> Improve default permissions of Drafts page

- web/concrete/src/Block/BlockController.php
`BlockController`s often access to `$btTable`, but for blocks that don't define it we access an undefined property: let's define it.
Furthermore I marked as `public` these methods that didn't have an accessibility mark:
- `install`
- `render`
> Define $btTable property in BlockController

- web/concrete/src/User/User.php
It's called statically and doesn't contain any reference to `$this`, so it's safe to mark it as static
> Make User::verifyAuthTypeCookie static

- web/concrete/css/build/core/app/page-areas.less
This pull takes firefox from looking like:
To more like one would expect:
> Make firefox empty area borders size appropriately

- web/concrete/elements/page_controls_footer.php
URL is not a static method of View: let's switch to the brand new URL class.
Notice: I used `URL::to` instead of `Url::to` since in other places of this file we have the upper-case version. BTW, shouldn't it be [`Url`](https://github.com/concrete5/concrete5-5.7.0/blob/develop/web/concrete/src/Support/Facade/Url.php#L4)?
> Fix warnings in page_controls_footer: use URL::to instead of View::URL

- web/concrete/src/Asset/AssetList.php
When a theme controller calls something like `$this->providesAsset('css', 'bootstrap/*')` we try to access an asset that's not in the list.
> Fix warning in AssetList::getAsset:

- web/concrete/blocks/google_map/controller.php
- web/concrete/blocks/google_map/view.php
I was having issues with maps blocks not having a unique id and hence duplicate blocks failing to render. I started by using proxy block id's, but that continued to give duplicate id's if a map was in a stack pulled more than once.
This solution just makes sure the id's really are unique. It could still fail if the view of a stack is cached and used in more than one place on a page.
A better solution would be a complete refactoring of the way maps blocks create and interact with their JavaScript to avoid dependence on a block ID.
> Ensure maps blocks have a unique identity

- web/concrete/attributes/address/form.php
- web/concrete/attributes/address/type_form.php
- web/concrete/attributes/boolean/controller.php
- web/concrete/attributes/date_time/type_form.php
- web/concrete/attributes/image_file/controller.php
- web/concrete/attributes/rating/service.php
- web/concrete/attributes/select/form.php
- web/concrete/attributes/select/type_form.php
Added classes "ccm-attribute" and "ccm-attribute-address" to the <fieldset> in order to enable targetting by CSS and jQuery. These two classes have been added preceding the already existing ID-based class which is (generally) unique unless there are multiple instances of the given attribute. Thus the classes are ordered by level of precision. 
See the related issue: https://github.com/concrete5/concrete5-5.7.0/issues/2262
> Add classes to fieldset to enable targetting

- web/concrete/src/Page/Collection/Collection.php
With this PR we'll have 561 less warnings during concrete5 installation with full sample content.
> Fix warnings in addCollection

- web/concrete/src/Legacy/UserList.php
Not sure why, but during the CLI install I have this error:
```
5%: Starting installation and creating directories.
10%: Creating database tables.
Whoops\Exception\ErrorException: Cannot use Loader as Loader because the name is already in use
in file concrete/src/Legacy/UserList.php on line 6
Stack trace:
1. () concrete/src/Legacy/UserList.php:6
| array(0) {
| }
```
I managed to get rid of this error by switching from `Loader::helper('...')` to `Core:make('helper/...')` and `Loader::db()` to `Database::connection()`
> Get rid of Loader in UserList

- web/concrete/src/Attribute/Value/Value.php
Another 415 less warnings during install with sample contents.
IMHO these warnings were caused by two calls to Value destructor: by child classes and by php.
> Avoid warnings in attribute value destructor

- web/concrete/controllers/single_page/dashboard/system/multilingual/translate_interface.php
- web/concrete/single_pages/dashboard/system/multilingual/translate_interface.php
Removed this option which allowed unescaped slashes which allowed input to be evaluated.
@mlocati Any reason this was added? it only affected PHP 5.4+ and I don't see why it was needed.
> Fix XSS in Translating site interface

- web/concrete/src/Block/BlockType/Set.php
- web/concrete/views/panels/add.php
A better implementation of
https://github.com/concrete5/concrete5-5.7.0/pull/2256
Added a displayOrder method to Set class and used that in a usort within the Add panel
> Sort block types by displayOrder in add panel 

- web/concrete/src/Tree/Node/Type/Group.php
- web/concrete/src/User/Group/Group.php
This pull request improves (and supersedes) #2288 by translating group names
> Show localized names in Groups tree, without parents path

- web/concrete/controllers/single_page/dashboard/system/multilingual/translate_interface.php
- web/concrete/single_pages/dashboard/system/multilingual/translate_interface.php
The `Export to .PO` function of the multilingual dashboard section does a lot more that exporting to .po files: it generates the .mo files that are used to actually translate the site.
So: I changed the button text from `Export to .PO` to `Save to file` and I changed the message from `Translations exported to PO File and Reloaded` to `The translations have been exported to file and will be used by the website`. Furthermore, I added a call to `\Localization::clearCache()`.
Finally: this function is handy while translating the strings in the Translator, so I added a `Save to file` button in the translator page too. To keep the editing interface untouched (current editing locale, search filter, UI state), this button does an ajax call.
> Export and activate translations

- web/concrete/src/Http/ResponseAssetGroup.php
If the code requires an invalid asset group, the site breaks.
We have two alternatives: we can ignore this error (like in this PR) or we can throw an Exception with a description of the problem. Since both have downsides I'll leave this choice to the core team :wink:
Furthermore, the class-level static variable `$group` was just defined as `static $group = null;`, without any accessibility specifications: I marked it as `protected`.
> Avoid problems in ResponseAssetGroup::requireAsset

- web/concrete/css/build/core/app/dialog.less
> Fix guide background color

- web/concrete/src/Url/Url.php
I initially wrote this as
```php
if (
$port
&&
(!(
($this->getScheme()->get() == 'http' && $port == '80')
||
($this->getScheme()->get() == 'https' && $port == '443')
))
} (
$this->getPort()->set($port);
}
```
But since `!(A || B) === (!A && !B)` and `!(A && B) === (!A || !B)` ([basic boolean rules](http://en.wikipedia.org/wiki/De_Morgan%27s_laws)), I wrote this as
```php
if (
$port
&&
($this->getScheme()->get() != 'http' || $port != '80')
&&
($this->getScheme()->get() != 'https' || $port != '443')
) {
$this->getPort()->set($port);
}
```
> Url::setPortIfNecessary always return $this

- build/libraries/generate-symbols.php
- web/concrete/src/Support/Symbol/ClassSymbol/ClassSymbol.php
- web/concrete/src/Support/Symbol/ClassSymbol/MethodSymbol/MethodSymbol.php
- web/concrete/src/Support/Symbol/SymbolGenerator.php
After some discussion in #114, here's a new pull request that simplifies and improves `__IDE_SYMBOLS__.php`:
-  Exclude unnecessary methods
- Fix definition of facade methods
- Simplify indentation
> Improve IDE symbols file

- web/concrete/src/Search/Pagination/Pagination.php
- web/concrete/src/Search/Pagination/View/ViewRenderer.php
* `renderDefaultView()` does not pass arguments to `renderView()`
* `ViewRenderer` does not use arguments
Related: #2304
> Fix to use pagination arguments

- web/concrete/src/Error/Handler/ErrorHandler.php
> Better view of concrete5 configuration on error

- web/concrete/tools/files/importers/thumbnail.php
Fixes #2341.
Borrowed the same fix from #2142:
`str_replace('data:image/png;base64,', '', $imgData)`
became
`preg_replace('/data:image\/(png|jpeg);base64,/', '', $imgData, 1)`
> Fixed non-PNG decoding in thumbnail save (Fixes #2341)

- .travis.yml
- tests/tests/bootstrap.php
For local tests, it's handy to (re)create the test DB in the bootstrap.php
> (Re)Create test database in bootstrap.php

- web/concrete/src/File/Version.php
Fixes the thumbnail options parameter being skipped
RE: https://github.com/concrete5/concrete5-5.7.0/commit/58aaa02003706ef7a63fb2a4497b006b8cae403a#commitcomment-10978536
> Fixing jpeg quality being ignored

- web/concrete/blocks/form/auto.js
- web/concrete/blocks/form/controller.php
- web/concrete/blocks/form/db.xml
- web/concrete/blocks/form/form_setup_html.php
- web/concrete/blocks/form/mini_survey.php
Implements #2283
This implements setting a default date to blank or current date/time. It also fixes a bug in the datetime type where when you submit it, if validation fails, it reverts to the submitted value instead of the default value.
It looked like the form block was already being refreshed so I think we should be good to go for upgrade on the database side of things
> Implements 2283

- web/concrete/src/File/Set/File.php
I have a Press Photo block that pulls a specific File Set. I made a change to the sort order of the files within the File Set using the File Manager > File Sets > Files in Set dashboard. However, my block wasn't reflecting the update to the sort order.
I added the ORDER BY clause to the query so that the result set would honor the fsDisplayOrder values.
> Add fsDisplayOrder sort to getFileSetFiles

- web/concrete/src/Page/Type/Type.php
To keep composer interface works properly, even if an add-on adds new page type manually.
Related #2337
> Set default publish target to each page type

- web/concrete/tools/dashboard/get_image_data.php
- The constant `DASHBOARD_BACKGROUND_INFO` was moved to `concrete.urls.background_info` config key
- Support cases when `concrete.urls.background_info` already contains a question mark
- print out `$imageData` only if it's defined
> Fix get_image_data

- web/concrete/config/concrete.php
- web/concrete/src/Application/Service/UserInterface/Help.php
In some scenarios we want to hide the help system. This PR adds a config setting to disable the help system (front-end & dashboard).
> Add config setting to enable / disable help system

- web/concrete/composer.json
- web/concrete/composer.lock
Formatting English ordinal suffix for the day of the month was not correct in #2417 (well, it was rendered as an empty string).
This PR fixes this.
> Upgrade Punic to 1.6.1

- tests/tests/Core/Form/Service/FormTest.php
- web/concrete/src/Form/Service/Form.php
Here's a pull request that I've wanted to do since the first time I met concrete5 :wink:
Novice users that take a look at the FormHelper code get confused very fast (it's still happening to me).
So, I simplified almost everything, and added correct phpDoc comments. Furthermore I gave a more meaningful name to some parameters (for instance: `$valueOrMiscFields` instead of `$valueOrArray`).
I also added a lot of tests to check the new code. Everything's working as expected.
As an extra check, I ran all the tests included in this pull request against the old code, and here's the few differences between the old and the new code:
1. in [a textarea test](https://github.com/concrete5/concrete5-5.7.0/commit/fe24c8d14bc0600bf2600f9d52264f6950005ec6#diff-71fea021526964db059d893ddb68f000R407) the …
> Beautify form helper

- web/concrete/src/Page/Type/Composer/Control/Control.php
In ComposerControl::addToPageTypeComposerFormLayoutSet we try to access an undefined class property called `isPageTypeComposerControlRequiredByDefault`.
If I'm not wrong, it should access the `ptComposerControlRequiredByDefault` property instead (and I wrapped it in a `isPageTypeComposerControlRequiredByDefault()` method).
> Fix composer control required by default

- web/concrete/blocks/core_page_type_composer_control_output/controller.php
In the `getImportData` method we have `$b = $this->getBlockObject();`.
BTW, `$b` is never used; furthermore we're importing a new block, so it's quite useless to try to load it, IMHO.
> Avoid trying to load non-existing block

- web/concrete/src/StyleCustomizer/Inline/StyleSet.php
It's called statically, and it doesn't contain an reference to $this
> Mark StyleSet::import as static

- web/concrete/controllers/single_page/dashboard/extend/install.php
`The package type has been uninstalled`: what's a `package type`? I guess it should be just `package`
> 'Package type' should be 'Package'

- web/concrete/controllers/single_page/register.php
- web/concrete/mail/user_register_approval_required_to_user.php
When a new user register and needs approval, no email to the user.
He/she may consider that registration failed and try again.
When a new user register and needs approval, email to the user that he/she has registered but needs approval by admin.
> When a new user register and needs approval, email the user

- web/concrete/src/Page/Theme/Theme.php
- web/concrete/themes/elemental/description.txt
- web/concrete/themes/elemental/page_theme.php
- Elemental: move theme name and description to theme controller.
Strings in theme controllers can be translated and developers that are inspired from Elemental will use this better approach
- When installing themes, we need to save in the DB the English name/description: they'll be translated in views
> Fix themes

- README.md
Congrats on pulling the bandaid off and all the new success and growth with 5.7. :beers: 
Noticed a bit of a typo in the new readme.
> Fix concrete5 legacy link in README

- web/concrete/css/build/core/redactor/redactor.less
Make the table cells easier to select and add content to.
> #2433 - added min-width: 55px; to .redactor-editor table

- web/concrete/blocks/feature/controller.php
Please note that the `getLinkURL` method didn't have the accessibility defined: I marked it as `public`.
> Cleanup Feature block controller

- web/concrete/composer.json
- web/concrete/composer.lock
- Upgrade ZF2 from 2.2.9 to to 2.2.10
- Re-apply patch for plural translations not working with languages that don't have plural
Please remark that the ZF2 repos have changed their file structure, and some "require" have changed (we now have two extra ZF2 packages: zend-json and zend-serializer).
> Upgrade and fix ZF2

- web/concrete/config/db.xml
- web/concrete/src/Attribute/Key/Category.php
- web/concrete/src/Attribute/Set.php
Allows Attribute Sets to have handles that are not unique.
Adds a non-invasive way to get an Attribute Set when the ID of an
Attribute Key Category is known.
Issue #2432
> Attribute Set Handle Non-Uniquity

- web/concrete/src/Asset/Asset.php
Abstract static methods throw an E_STRICT warning
> Mark Asset::process as not abstract

- tests/tests/Core/Logging/LogTest.php
Sometimes I get an access denied error because the log file is still open...
> Close logger before deleting log file

- web/concrete/src/Updater/Archive.php
This PR *could* fix http://www.concrete5.org/developers/bugs/5-7-3-1/cant-update-or-download-add-ons/
> Normalize directory before splitting it

- web/concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php
Fixes being unable to publish a page which has a valid file attribute that is marked as required (the validation test returns null when it passes, but null matches false in a loose comparison).
It would let you publish the page through the Composer interface, but not through the exit Edit Mode panel.
> Strict check for false

- web/concrete/src/User/UserInfo.php
Currently, no events are fired when the user updates their avatar unlike any of the other properties which do properly fire the event.
> Updates UserInfo::updateUserAvatar to fire event

- web/concrete/controllers/single_page/dashboard/reports/forms.php
- web/concrete/single_pages/dashboard/reports/forms.php
The Form Results pagination is broken as a side effect of the recent [BASE_URL and DIR_REL deprecation](https://github.com/concrete5/concrete5/commit/b6e5a7c3ca54bec27bb0d5e0ed731960d0e0b6a8#diff-c8650f428a9ccd91451f25949b50081fL121)
The initial query string `?cID=` was removed which invalidated the other parameters, causing it to redirect.
> Fixes the Form Results pagination

- web/concrete/src/Cache/Page/PageCache.php
Currently, page cache adapters will be loaded from concrete directory only. This change enables to add another adapters for developers.
Here is an example to use APC cache adapter.
application/config/concrete.php
```php
<?php
return array(
'cache' => array(
'page' => array(
'adapter' => 'apc',
'ttl' => 3600,
'namespace' => 'concrete5fullpagecache'
)
)
);
```
application/src/Cache/Page/ApcPageCache.php
```php
<?php
namespace Application\Src\Cache\Page;
use Concrete\Core\Cache\Page\PageCache;
use Concrete\Core\Cache\Page\PageCacheRecord;
use Stash\Driver\Apc;
use Stash\Pool;
use Page as ConcretePage;
use Config;
class ApcPageCache extends PageCache
{
static $pool;
public function __construct()
{
$driver = new Apc();
$options = array(
'ttl'       => Config::get('concrete.cache.page.ttl'), …
```
> Enables to override page cache adapters

- web/concrete/src/Application/Application.php
`DIR_FILES_CACHE` is no more defined.
I replaced this old code with new code that completely deletes and re-create the cache directory.
In most cases this is superfluous since the cache directory should already be emptied by `Core::make('cache/expensive')->flush()`, but let's be sure to delete the cache directory anyway (since it's configurable).
> Remove undefined constant DIR_FILES_CACHE

- web/concrete/src/Backup/ContentImporter.php
importing fails for block types because the check for existing blocks is missing. Used to be there https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/core/libraries/content/importer.php#L307
> check existing blocks before import

- web/concrete/config/concrete.php
The used configuration key is [`conversations.attachments_enabled`](https://github.com/concrete5/concrete5/blob/cb2808c368b143585a8e91b2d9b9b68c161dd70d/web/concrete/config/conversations.php#L13) and not `concrete.conversations.attachments_enabled`
> Remove concrete.conversations.attachments_enabled

- web/concrete/src/Mail/Service.php
The configuration key for the default sender name is `concrete.email.name` and not `concrete.email.default.name`: see the [concrete/config/concrete.php file](https://github.com/concrete5/concrete5/blob/cb2808c368b143585a8e91b2d9b9b68c161dd70d/web/concrete/config/concrete.php#L328-L330)
> Fix config key for default email sender name

- web/concrete/tools/pages/delete.php
I may be wrong, but here we should use `'concrete.limits.delete_pages'` instead of `'concrete.limits.sitemap_pages'` (see [`concrete/config/concrete.php`](https://github.com/concrete5/concrete5/blob/cb2808c368b143585a8e91b2d9b9b68c161dd70d/web/concrete/config/concrete.php#L848))
> Use correct config value for the page size when deleting pages

- web/concrete/src/Job/QueueableJob.php
See [`concrete/config/concrete.php`](https://github.com/concrete5/concrete5/blob/cb2808c368b143585a8e91b2d9b9b68c161dd70d/web/concrete/config/concrete.php#L851)
> Use correct config value for the page size for queueable jobs

- web/concrete/src/StyleCustomizer/Style/TypeStyle.php
Throws an error when saving a type with underline option unchecked in theme customization.
`Call to undefined method Concrete\Core\StyleCustomizer\Style\Value\TypeValue::setDecoration()`
> Fix method name

- web/concrete/js/build/core/style-customizer/typography.js
Typography selector fails on save if it is used without font selection.
`Uncaught TypeError: Cannot read property 'css' of undefined`
e.g. I don't want end-user to be able to choose font on links:
**styles.xml**
```
<style name="Link" variable="link" type="type" />
```
**defaults.less**
```
@link-type-color: #222;
@link-type-text-decoration: none;
```
> Fix uncaught error on ConcreteTypographySelector

- web/concrete/src/Html/Object/Picture.php
[IE9 doesn't recognise `<source>` elements inside `<picture>`](http://scottjehl.github.io/picturefill/#ie9).
Adding this conditional tag for IE9 gets it working (as explained in the link above)
> Added conditional IE9 tag for Picturefill

- web/concrete/blocks/file/add.php
- web/concrete/blocks/file/controller.php
- web/concrete/blocks/file/db.xml
- web/concrete/blocks/file/edit.php
- web/concrete/blocks/file/view.php
This change:
- Adds the option to force a linked file to download
- Uses the newer ->getDownloadURL() call
- Increases the height of the form block interface to fit the new checkbox
> Addition of option to force download in File block

- web/concrete/controllers/single_page/dashboard/workflow.php
When you click the "Workflow" of right side dashboard menu, it will redirect to the "Workflow List" page.
But we would want to direct to "Waiting for Me" page instead.
This is because there may be a user who has a permission to approve the page, but not the Workflow List page.
Once you finish setting up the Workflow, you will visit Waiting For Me page more often.
> Change default workflow page to Me

- web/concrete/src/Workflow/BasicWorkflow.php
Users can not use multiple basic workflow now, because basic workflow permission assignment class is not used.
> Fix basic workflow assignment

- web/concrete/controllers/single_page/register.php
Very long username shows "A username may only contain letters or numbers".
This message is unnecessary.
> Fix: username validation

- web/concrete/src/Console/Command/InstallCommand.php
Even if we define any options from config file, these values will be overwrited by default value.
http://php.net/manual/en/language.operators.array.php
> Fix: can't override install options by config file

- web/concrete/elements/group/search.php
If you does not have access to group search, you'll get the error message:
```
An unexpected error occurred.
Call to a member function getJSONObject() on null
```
> Check access group search permission on dashboard

- web/concrete/src/Legacy/PageList.php
We might have to move away from legacy pagelist, but we should fix the error first.
> Fix class alias issue in legacy page list

- web/concrete/src/Foundation/EnvironmentDetector.php
This adds the possibility to define the current environment through an environment variable named CONCRETE5_ENV. This allows us to control the environment on the server-level (or even in .htaccess).
We find this much convenient way than sniffing the hostname because we all basically use the same environment configs on our development machines.
I know we could already pass a closure to the method but it would be easier if we didn't have to add the same code manually for each and every project.
> Possibility to define the environment through an environment variable

- web/concrete/controllers/single_page/dashboard/users/add.php
- web/concrete/controllers/single_page/register.php
Username characters
[A-Za-z0-9] ... allowed everywhere
if  concrete.user.username.allow_spaces :
[A-Za-z0-9_. ] ... disallowed in start and end
else :
[A-Za-z0-9_.] ... disallowed in start and end
see src\Application\Service\Validation.php L63-88
> Fix: Message for notifing the allowed chars in username

- web/concrete/src/Console/Command/GenerateIDESymbolsCommand.php
Followup of https://github.com/concrete5/concrete5/pull/2527/files#r32346805 : the `c5:ide-symbols` cli command has swapped function names: let's fix this.
> Swap IDESymbols functions

- web/concrete/controllers/frontend/page_forbidden.php
- web/concrete/controllers/single_page/page_forbidden.php
when a user doesn't have a permission to view that page and `concrete.permissions.forward_to_login` config value is `false`.
> Show forbidden page intead of login form

- web/concrete/blocks/core_conversation_message/controller.php
- web/concrete/controllers/single_page/dashboard/system/conversations/bannedwords.php
- web/concrete/src/Updater/Migrations/Migrations/Version20150610000000.php
- web/concrete/tools/conversations/add_message.php
All the other conversations-related configuration keys use `conversations.*`, not `conversation.*`
> From conversation.banned_words to conversations.banned_words

- web/concrete/js/build/core/app/edit-mode/stack.js
- web/concrete/views/panels/add.php
This code makes the stacks block type javascript behave the same way as the javascript for a normal block type. On a custom editing page this code causes problems because:
+ CCM_ID is the ID of the current page, which is ok when editing a normal page but not when editing a collection from another page. A normal block type uses data-cid to store the destination collection ID, which for stacks was changed to the stack collection ID. Instead, I added a new attribute to store the stack collection ID and kept the same behavior for the collection ID.
+ ConcretePanelManager.exitPanelMode() is not needed here when editing a normal page because the panel will already have been closed. When used on a dashboard page it actually closes the side navigation page. In addition, a normal block type will …
> Stack block type javascript

- web/concrete/src/Page/Page.php
Composer the great tool to manufacture the same type of content such as news page.
Sometime, you want to copy an existing page to a new page ( such as a new press release page) to re-use some of the content.
However, when you make a copy, the composer blocks became uneditable on composer.
I think we should make it available to edit on composer on duplicated page
I've added the query on Page::duplicate() function.
Cheers
> Keep composer editable blocks status even after the page is duplicated

- web/concrete/src/Multilingual/Service/UserInterface/Flag.php
This PR allows us to add flag images in our theme folder as well.
It also fixes a bug because the old code looks in /images/countries/ for images. Although this worked for C56, it doesn't for C57. We use the DIR_APPLICATION constant to look for flag images in /application/images/countries/region.png
In sum, the script looks for these paths:
1. /application/themes/theme/images/countries/region.png
2. /application/images/countries/region.png
3. /concrete/images/countries/region.png
> Add theme folder as flag source. Fix old c56 image path.

- web/concrete/src/Cache/OpCache.php
- web/concrete/src/Config/FileSaver.php
When opcache is enabled, we often have problems in dashboard pages: the newly configured options are not immediately visible because of the cache.
So, let's try to clear the cache after saving the config files.
> Clear the opcache after saving a configuration file

- web/concrete/src/Session/Session.php
- web/concrete/src/Session/Storage/Handler/NativeFileSessionHandler.php
Hit the same snag with open_basedir restrictions as described in issue #2579. The trouble is with the Symfony session file storage handler checking the existence of the session path.
This is useful when a website has its own session path, but in many distributions the default session path is shared over the entire server (e.g. /var/lib/php5 in Debian, which also has its own garbage collection implementation tied in with that).
Complementing open_basedir restrictions make sure that runtime code is unable to read session data, as it has no business there from a security perspective. Turning off open_basedir restrictions on such a path will make any session data unnecessary vulnerable to things like remote file inclusion.
Also, in such a situation it is safe to assume the session path always …
> Modify NativeFileSessionHandler to avoid open_basedir issue with default session path

- tests/tests/Block/ContentFileTranslateTest.php
- tests/tests/Core/File/FileListTest.php
- web/concrete/blocks/autonav/nav_item.php
- web/concrete/config/concrete.php
- web/concrete/single_pages/dashboard/system/basics/multilingual/view.php
- web/concrete/single_pages/dashboard/system/files/filetypes.php
- web/concrete/single_pages/dashboard/system/mail/method/test.php
- web/concrete/single_pages/dashboard/system/seo/statistics.php
- web/concrete/single_pages/login_oauth.php
- web/concrete/src/Activity/Newsflow.php
- web/concrete/src/File/ValidationService.php
- web/concrete/src/User/User.php
New configuration option introduced: `concrete.user.password.legacy_salt`
> Remove old constants - Part 2

- web/concrete/src/Area/Area.php
- web/concrete/src/Area/GlobalArea.php
This fixes two E_STRICT warnings:
- Declaration of Concrete\Core\Area\GlobalArea::getTotalBlocksInArea() should be compatible with Concrete\Core\Area\Area::getTotalBlocksInArea($c = false)
- Declaration of Concrete\Core\Area\GlobalArea::display() should be compatible with Concrete\Core\Area\Area::display($c, $alternateBlockArray = NULL)
> Fix warnings in GlobalArea

- web/concrete/bootstrap/start.php
I think its safe to move the page cache check to happen before the assets and install check. Not a huge benefit but the loading times appeared to go down 10% when I tested it.
Just not sure about routes. The page cache does not apply to routes right?
> Check page cache before assets & install check

- web/concrete/src/Support/Symbol/MetadataGenerator.php
Adds some additional missing classes to the phpstorm metadata file like `Core::make('app')`
> More phpstorm metadata

- web/concrete/src/File/File.php
If you call 'getRelativePathFromID' for a non-existing fID, the file would evaluate to NULL, and you can't get a relative path from NULL -> this would result in a fatal error. I've added code to return 'false' in such cases instead. This kind of behavior could happen if you've transferred the database but not the files itself. The previous behavior would make the whole page inoperable/inaccessible, the new behavior doesn't.
> getRelativePathFromID: 'false' instead of error

- web/concrete/config/app.php
- web/concrete/controllers/dialog/area/layout/presets/manage.php
Two errors fixed here (one per commit):
1. The route `/ccm/system/dialogs/area/layout/presets/manage` should be defined before `/ccm/system/dialogs/area/layout/presets/{arLayoutID}`, otherwise the latter gets executed before the former
2. **not sure about this** `Concrete\Core\Area\Layout\Preset` does not exist. Maybe it could be `Concrete\Core\Area\Layout\Preset\UserPreset`
> Fix presets managing

- tests/tests/ConcreteDatabaseTestCase.php
Let's avoid to open and close the database connection at every test.
This makes the whole test suite running 6x faster (from 9 minutes to 1 minute and half on my development machine).
> Faster tests

- web/concrete/controllers/single_page/login.php
- web/concrete/single_pages/login.php
If you fail to authenticate with an authentication type that is not the default the default authentication form is displayed when the page is reloaded. This makes the authentication type last used display instead.
> Display last used authentication type if authentication fails

- web/concrete/src/Tree/Node/Node.php
- web/concrete/src/Tree/Node/Type/Category.php
- web/concrete/src/Tree/Node/Type/Topic.php
`importNode` is called statically, it does not contain any reference to `$this` (and the method name is not the same as the class name :wink:).
I marked the first argument of `Topic::add` as optional to avoid strict warnings: see http://3v4l.org/AVeOk (like the previous code) and http://3v4l.org/Tvjqu (like the code in this PR).
The need to have static methods with compatible signatures is quite odd IMHO, BTW.
> Fix warnings in tree nodes

- web/concrete/src/Permission/Response/GroupTreeNodeResponse.php
I'd like to give the permission to access to group tree to my user, but I have to change "Access Group Search" permission and the view permission of "User Groups" page. This is annoying. I believe concrete5 should check only "Access Group Search" permission.
> Check task permission if the user can view group tree

- web/concrete/authentication/concrete/controller.php
If /dev/urandom is not available (eg. in a chroot), we'll have to use MCRYPT_RAND.
Closes #2635
> Allow mcrypt_create_iv to fall back

- web/concrete/src/Application/Service/Avatar.php
The aspect ratio was only applied to avatars uploaded directly to concrete5, but should also be applied to avatars loaded via Gravatar.
> Fix scaling of avatars fetched from Gravatar

- tests/tests/Core/Permission/DurationTest.php
- web/concrete/src/Foundation/Repetition/AbstractRepetition.php
A few fixes here:
- [1st commit](https://github.com/concrete5/concrete5/commit/5be058ae8532d12bec8974b44c58add684f710cc): some installations don't support timestamps with more that 32 bits (so the max timestamp allowed is `Tue, 19 Jan 2038 03:14:07 UTC`), So, let's limit the "future" year in those systems while testing
- [2nd commit](https://github.com/concrete5/concrete5/commit/f55e2e63d3137aa7b202ffdea2039b6a52fd1c98): on the systems with timestamps limited to 32bits, we sometimes have `double` timestamps instead of `int` timestamps, so we have to compare timestamps with `==`/`!=` instead of `===`/`!==` (because with the strict operators comparing `double` with `int` always fails)
- [3rd commit](https://github.com/concrete5/concrete5/commit/928e7c940b86b52ed90f68b2cfe583c4fde3be59): the …
> Fix duration repetition and tests

- web/concrete/src/Block/Block.php
This PR fixes this problem that occurs while saving the layout design:
```
An exception occurred while executing 'UPDATE CollectionVersionBlocks SET cbOverrideBlockTypeContainerSettings = ?, cbEnableBlockContainer = ? WHERE cID = ? AND cvID = ? AND arHandle = ? AND bID = ?' with params [0, false, "182", "1", "Main", "163"]:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'cbEnableBlockContainer' at row 1
```
> Fix saving layout design

- web/concrete/src/Tree/Node/NodeType.php
NodeType::add is called statically: let's mark it as static.
Fixes an E_STRICT warning in PHP < 7, and an E_DEPRECATED warning in PHP 7
> Fix warnings in NodeType

- web/concrete/src/Tree/TreeType.php
TreeType::add is called statically: let's mark it as static.
Fixes an E_STRICT warning in PHP < 7, and an E_DEPRECATED warning in PHP 7
> Fix warnings in TreeType

- web/concrete/blocks/autonav/controller.php
- web/concrete/src/Html/Service/Seo.php
- web/concrete/src/Http/ResponseAssetGroup.php
When rendering multiple pages programmatically(e.g. export to html), some items are duplicated because these items are shared in memory. If this request merged, we can reset these shared items.
> Some improvements for rendering pages manually

- web/concrete/composer.json
- web/concrete/composer.lock
- Workaround for HHVM bug while handling timezone names
- Fix sorting of list with non-US-ASCII chars
- Speed improvements
> Upgrade Punic from 1.6.1 to 1.6.3

- web/concrete/elements/block_header_view.php
Prevents blocks from overflowing out of an area with arGridMaximumColumns set.
> Use getAreaGridMaximumColumns to determine block container classes

- web/concrete/elements/files/add_to_sets.php
Make the checkbox determining if the fileset we're adding is public checked by default. 
@aembler mentioned this in #2597.
> Make new filesets public by default

- web/concrete/src/Attribute/Key/UserKey.php
This PR fixes two E_STRICT warnings in PHP < 7 (two E_WARNING in PHP 7).
BTW, there are two more declarations that should be fixed:
- [`UserKey::getList`](https://github.com/concrete5/concrete5/blob/c478b84576740cc262a36e65010147e403d427e6/web/concrete/src/Attribute/Key/UserKey.php#L158) vs [`Key::getList`](https://github.com/concrete5/concrete5/blob/c478b84576740cc262a36e65010147e403d427e6/web/concrete/src/Attribute/Key/Key.php#L216)
- [`UserKey::add`](https://github.com/concrete5/concrete5/blob/c478b84576740cc262a36e65010147e403d427e6/web/concrete/src/Attribute/Key/UserKey.php#L188) vs [`Key::add`](https://github.com/concrete5/concrete5/blob/c478b84576740cc262a36e65010147e403d427e6/web/concrete/src/Attribute/Key/Key.php#L360)
I can't see a way to make them compatible...
> Fix warnings in UserKey

- web/concrete/controllers/search/files.php
- web/concrete/controllers/search/groups.php
- web/concrete/controllers/search/pages.php
- web/concrete/controllers/search/users.php
Added a getListObject function to each of the search controllers to
noninvasively facilitate abstraction. This is useful for packages that
need apply extra qualifiers to a DatabaseItemList after a search has
been performed.
> Search Controller Abstraction

- tests/tests/Core/Routing/URLTest.php
- web/concrete/src/Routing/Router.php
- web/concrete/src/Url/Resolver/RouteUrlResolver.php
- web/concrete/src/Url/Url.php
- web/concrete/src/Url/UrlServiceProvider.php
Here's a sample:
```php
\Route::register('/path/to/{some_var}/', function() {}, 'some_route_handle');
$url = (string) \URL::to('some_route_handle', array('some_var' => 'test')); 
// string 'http://c57.com/path/to/test' (length=27)
```
@aembler I went back and forth with adding a prefix to this. Searching the route list every time we generate a url if it matches a form factor certainly will impact performance. To fix that we can make it something like `\URL::to('route/some_route_handle')` and only search when the string starts with `route/`
> Add named route url resolver

- web/concrete/src/File/Service/File.php
In my environment, PHP5.5 Apache2.4 mod_fastcgi PHP_FPM, open_basedir set to sensible values I am seeing open_basedir warnings when error_reporting includes E_WARNING. This causes the sitemap to fail to load, and the file manager won't show an image if you "view" it. I logged a bug here:
https://www.concrete5.org/developers/bugs/5-7-4-2/open_basedir-issue-php-5.5-apache-2.4
The fix is very simple - just suppress errors with "@"
> Suppress open_basedir warnings in Concrete\Core\File\Service::isSamePath

- web/concrete/bin/concrete5.php
- web/concrete/src/Console/Application.php
This PR makes console command extendable from a Package, without adding the method directly to the Package class. This is an alternative plan of #2651 
An example of package controller:
```php
<?php 
namespace Concrete\Package\CommandPackageExample;
use Concrete\Package\CommandPackageExample\Console\Command\ExampleCommand;
use Core;
class Controller extends \Concrete\Core\Package\Package
{
protected $pkgHandle = 'command_package_example';
protected $appVersionRequired = '5.7.4.3';
protected $pkgVersion = '0.1';
protected $pkgAutoloaderMapCoreExtensions = true;
public function getPackageName()
{
return t('Command Package Example');
}
public function getPackageDescription()
{
return t('An example package to add console commands.');
}
public function on_start()
{
if …
```
> Re: Make console command extendable from packages

- web/concrete/src/Permission/Assignment/AreaAssignment.php
- web/concrete/src/Permission/Assignment/BlockAssignment.php
- web/concrete/src/Permission/Assignment/ConversationAssignment.php
- web/concrete/src/Permission/Assignment/FileAssignment.php
- web/concrete/src/Permission/Assignment/FileSetAssignment.php
- web/concrete/src/Permission/Assignment/TopicTreeNodeAssignment.php
Since `setPermissionObject` should have the same signature for all the derived classes, let's remove the forced type from the sub-classes declarations (sigh).
> Fix warnings in Permission\Assignment\...::setPermissionObject

- web/concrete/blocks/share_this_page/controller.php
We can also keep getImportData as public ( see http://3v4l.org/1tC68 ), but there shouldn't be any problem in marking it as protected since it's called only by the parent class `BlockController` (`import` method)
> Fix warnings in ShareThisPage controller

- web/concrete/blocks/core_area_layout/controller.php
Make `CoreAreaLayoutController::getImportData` compatible with the parent declaration
Marking this method as static is safe since it's being called only by the parent class `BlockController` (`import` method)
EDIT: BTW there's no problem in keeping getImportData as public, no warnings is raised if the parameters are the same (see http://3v4l.org/1tC68 )
> Fix warnings in CoreAreaLayoutController

- tests/tests/ConcreteDatabaseTestCase.php
- tests/tests/Core/User/GroupTest.php
- tests/tests/UserTestCase.php
- web/concrete/src/User/Group/Group.php
- Set `gPath` on group object after rescan
- Add addtional test for rescan group path
- Add test for `Group::updateGroup()`
- Run `parent::setUp()` as DBUnit has a setUp method that does not get
run if this is not included
- Clear `CacheLocal` on tear down for clean state between tests
> Fix failing UserPoint test

- web/concrete/src/Config/Renderer.php
Example: previous output
```php
array(
'detail' => 'debug',
'display_errors' => true
)
```
new output:
```php
array(
'detail' => 'debug',
'display_errors' => true,
)
```
This simplifies changes (eg git)
> Normalize formatted array when saving configuration items

- web/concrete/src/Form/Service/Widget/DateTime.php
This fixes #2755, basically when the overlay is closed it will check if the field is blank and if it is the value will be set to empty.
This was the solution posted at bugs.jqueryui.com/ticket/5734. Since they decided they weren't going to do anything with it I think we're going to have to handle it ourselves in concrete5.
> clear out altField in datepicker when field is empty

- web/concrete/blocks/autonav/auto.js
Calling the `.val()` function on a checkbox always returns the value it would submit if checked, but is not influenced by its current state. In order to actually check the value of a checkbox, `is(':checked')` can be used. To prevent having to deal with `true` and `false` as strings throughout the code, it makes sense to immediately translate this into the integers `1` and `0` respectively.
> Autonav: properly read checkbox value for preview

- web/concrete/src/Database/Connection/Connection.php
While converting a 5.6 site to 5.7 I came across an old ADODB method that hadn't been aliased yet.
Doctrine's fetchAssoc() returns
```
array(
[0] => array(
[id] => 1
[name] => 'John'
),
[1] => array(
[id] => 2
[name] => 'Bob'
)
)
```
whereas ADODB's GetAssoc() returned
```
array(
1 => John,
2 => Bob
)
```
> Alias for ADODB GetAssoc() method which returns a key/value array.

- web/concrete/single_pages/dashboard/view.php
exclude_nav causes dashboard pages to no longer show up in dashboard panel which implements the suggestion from #2444
> fixes 2444

- web/concrete/src/Area/Area.php
This fixes #2741 in such a way that it treats `Area` and `GlobalArea` as 2 different areas with different blocks. This does nothing to copy the blocks from the stack to the area or vice versa, it simply allows the area name to be converted back and fourth as needed.
> Allows areas to be changed to global areas and vice versa

- web/concrete/src/Logging/Logger.php
Right now the logger always logs everything to the database logger. This modification might allow us to add a minimum log level configuration setting so that we're not needlessly logging granular information. Additionally, it allows people who are defining their own loggers based off the core one to specify their own default logging level. This could be extremely useful for package developers who might only want to log package warnings and higher by default, but have more granular tracing / debug information available for their package if someone wanted to turn it on.
> Allow the minimum log level to be set

- web/concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php
Fixes composer attribute controls to show the proper label after being updated. Fixes #2766
> Fix composer attribute control label

- web/concrete/bin/concrete5.php
- web/concrete/src/Console/Application.php
With the latest version of the CLI stuff, the c5:install command doesn't work since we're trying to use database-dependent stuff (but the db is not initialized before the installation).
So, let's reduce the set of available commands to those that don't require a fully installed instance.
> Fix install via CLI

- web/concrete/src/Page/View/PageView.php
Example class to set the scene: https://gist.github.com/mitchray/70f0a6fc3b88c2f249d7
* You can request to render a Single Page using `$this->render('path/go/here')`.
* It has an optional parameter for a package handle, like so: `$this->render('path/go/here', 'PACKAGE_HANDLE')`.
* THEME_HANDLE is a part of the View class and is not controlled through render(). 
* After requesting to render a Single Page, the system decides how to wrap it. This is different from setting a theme: `$this->setTheme('THEME_HANDLE')`, I just wanted to make the distinction clear as we aren't trying to explicitly give a page a certain theme.
1. If the exact template `themes/THEME_HANDLE/fruit.php` or `packages/PACKAGE_HANDLE/themes/THEME_HANDLE/fruit.php` exists, use that as the outer wrapper and don't do an …
> Single page render improvements

- web/concrete/blocks/page_list/view.php
Make page_list output external links just like autonav does. So the href will render as http://externalsite.com instead of /?cID=1234
> Output external links in page list blocks

- web/concrete/css/build/core/app/inline-toolbar.less
* Change scope of the Customize Theme color picker to .ccm-panel-left, which ensures other uses throughout the Dashboard are not affected (see http://bgrins.github.io/spectrum/ for how it looks).
* Restore the before/after comparison (showInitial = true but the CSS was hiding it).
* Restore the checkered background in the alpha slider.
* Lighten the color value text to match the Cancal/Choose text.
* Fix alignment of the Choose text.
> Spectrum color picker tweaks.

- web/concrete/elements/account/menu.php
In rare cases where the menu contains children, but all of them have the `exclude_nav` attribute set, this code would crash on the `foreach` loop and render the entire website unusable. By initialising the `$categories` array to an empty array instead of relying on at least one appended child, the foreach is guaranteed to execute without throwing `Exception: Invalid argument supplied for foreach()`
> Prevents a non-existent array in the foreach loop

- web/concrete/controllers/single_page/dashboard/system/basics/accessibility.php
Closes https://www.concrete5.org/developers/bugs/5-7-5rc1/re-enabling-help-after-turning-it-off-in-accessibility-menu/
> Fix enabling/disabling display_help_system

- web/concrete/src/Routing/DispatcherRouteCallback.php
It is not necessary to send RedirectResponse in the dispatcher, the bootstrap handles that. It fired an exception ("concrete\bootstrap\start.php:290 Call to a member function send() on a non-object") since the response was already sent by the dispatcher and the bootstrap had nothing to send.
> Remove excess send() call

- web/concrete/src/Asset/AssetGroup.php
- web/concrete/src/Asset/AssetPointer.php
Created a function which returns a unique key to identify an asset pointer so that we can use it as an array index. Cuts down on thousands of iterations of the asset pointers per page load since `contains()` was being run for every asset that was added this was starting to add up
> asset group performance improvement

- web/concrete/src/Block/Block.php
This fixes the exception thrown at install time when MySQL is configured with STRICT_TRANS_TABLES:
```
[Doctrine\DBAL\Exception\DriverException]
'insert into CollectionVersionBlocks (cID, cvID, bID, arHandle, cbDisplayOrder, isOriginal, cbOverrideAreaPermissions, cbOverrideBlockTypeCacheSettings, cbOverrideBlockTypeContainerSettings, cbEnableBlockContainer) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
with params ["155", "1", "40", "Main", 0, 0, 0, 0, 0, false]:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'cbEnableBlockContainer' at row 1
```
> Fix saving CollectionVersionBlocks.cbEnableBlockContainer with strict MySQL

- web/concrete/src/Cache/Page/PageCache.php
Looks like the intent was to grab global blocks and merge with local, but we didn't save the resulting merged array.
Resolves #1903
> Fixes bug where global blocks cache settings were ignored.

- web/concrete/elements/page_types/composer/form/layout_set/control.php
- web/concrete/single_pages/dashboard/pages/types/form.php
- web/concrete/src/File/Version.php
- web/concrete/tools/page_types/composer/form/add_control.php
- web/concrete/tools/page_types/composer/form/edit_control.php
The culmination of discussion from PR #2316.
The columns across the different sets are now aligned.
> Add composer type names to composer form

- web/concrete/blocks/page_list/controller.php
Just a side note: @TimDix in the next pull requests, could you format the php-only files with php-cs-fixer?
It's as easy as typing
```
php-cs-fixer --config-file=<concrete5-root>/.php_cs fix <php-file-name>
```
I usually do it in a separate commit, so that relevant changes are more visible in the other commits (like in this pull request).
> Avoid accessing undefined index in PageList controller

- web/concrete/src/Area/Layout/Column.php
This fixes the following error:
```
Static function Concrete\Core\Area\Layout\Column::getByID() should not be abstract
```
> Avoid static abstract function: Area\Layout\Column::getByID()

- web/concrete/src/File/File.php
- web/concrete/src/Updater/Migrations/Migrations/Version20150731000000.php
Supersedes #2871
Assuming I'm still good to add these database deletes to the latest migration?
> Fix orphaning records on file delete

- web/concrete/blocks/search/controller.php
Inconsistent results between setting page, or setting the results URL. See http://screencast.com/t/FWrwd4kwJd for demonstration.
> Fixes Bug with Search Block when resultsURL specified instead of page

- web/concrete/blocks/autonav/controller.php
- web/concrete/blocks/content/controller.php
- web/concrete/blocks/core_area_layout/controller.php
- web/concrete/blocks/core_conversation/controller.php
- web/concrete/blocks/core_gathering/controller.php
- web/concrete/blocks/core_gathering_display/controller.php
- web/concrete/blocks/discussion/controller.php
- web/concrete/blocks/feature/controller.php
- web/concrete/blocks/google_map/controller.php
- web/concrete/blocks/image/controller.php
- web/concrete/blocks/image_slider/controller.php
- web/concrete/blocks/share_this_page/controller.php
- web/concrete/blocks/social_links/controller.php
- web/concrete/blocks/video/controller.php
- web/concrete/blocks/youtube/controller.php
- web/concrete/src/Block/BlockController.php
This fixes this warning:
```
Declaration of Concrete\Block\Content\Controller::registerViewAssets()
should be compatible with Concrete\Core\Block\BlockController::registerViewAssets()
```
The problem here is that `registerViewAssets` for the Content block needs the `$outputContent` parameter, but all the other blocks (and the base class) don't have that parameter.
We should change all these methods to
```php
public function registerViewAssets($outputContent)
```
but that would break existing 3rd party blocks.
The only solution I can see is the one implemented in this PR:
```php
public function registerViewAssets($outputContent = '')
```
> Normalize registerViewAssets for blocks

- web/concrete/src/User/Point/Action/Action.php
- web/concrete/src/User/Point/Action/WonBadgeAction.php
[`User\Point\Action::addDetailedEntry`](https://github.com/concrete5/concrete5/blob/a1cd4262f88badeb4e35fc231236f2aa82ece8d3/web/concrete/src/User/Point/Action/Action.php#L233) is just an alias of [`User\Point\Action::addEntry`](https://github.com/concrete5/concrete5/blob/a1cd4262f88badeb4e35fc231236f2aa82ece8d3/web/concrete/src/User/Point/Action/Action.php#L238), it's not called anywhere from the core (the only call to a `addDetailedEntry` method is [here](https://github.com/concrete5/concrete5/blob/a1cd4262f88badeb4e35fc231236f2aa82ece8d3/web/concrete/src/User/User.php#L513)), and it clashes with the definition of [`User\Point\Action\WonBadgeAction::addDetailedEntry`](https://github.com/concrete5/concrete5/blob/a1cd4262f88badeb4e35fc231236f2aa82ece8d3/web/concrete/src/User/Point/Action/W …
> Remove User\Point\Action::addDetailedEntry

- web/concrete/src/Job/QueueableJob.php
The value '999999999999' caused errors in 'vendor/zend-queue/library/ZendQueue/Queue.php' on some systems as it was typed as 'double' instead of integer. Changed it to be the max integer value for the current version and platform that the system is running on.
> Change maxMessages value

- tests/tests/ConcreteDatabaseTestCase.php
- tests/tests/Core/Database/DatabaseTest.php
- tests/tests/bootstrap.php
- web/concrete/blocks/autonav/controller.php
- web/concrete/blocks/content/controller.php
- web/concrete/blocks/form/controller.php
- web/concrete/blocks/form/view.php
- web/concrete/src/Attribute/Type.php
- web/concrete/src/Block/Block.php
- web/concrete/src/File/FileList.php
- web/concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php
- web/concrete/src/Form/Service/Form.php
- web/concrete/src/Foundation/Repetition/AbstractRepetition.php
- web/concrete/src/Http/RequestBase.php
- web/concrete/src/Logging/Handler/DatabaseHandler.php
- web/concrete/src/Mail/Service.php
- web/concrete/src/Page/Collection/Collection.php
- web/concrete/src/Page/Theme/Theme.php
- web/concrete/src/Page/Type/PublishTarget/Type/Type.php
- web/concrete/src/StyleCustomizer/Style/ColorStyle.php
- web/concrete/src/StyleCustomizer/Style/ImageStyle.php
- web/concrete/src/StyleCustomizer/Style/SizeStyle.php
- web/concrete/src/StyleCustomizer/Style/TypeStyle.php
- web/concrete/src/StyleCustomizer/Style/ValueList.php
- web/concrete/src/User/User.php
- web/concrete/src/User/UserInfo.php
This fixes all notice errors presented by the phpunit tests. There are quite a few files touched but most touches are very minor so I left them in only a couple commits. If this needs split up in some way say the word and I'll make it so.
Additionally....
- Fixes an Error, which if it wasn't an error would pose a SQL injection vulnerability, which is also fixed.
- Will most likely conflict with PR #2884 in regard to web/concrete/src/Page/Type/PublishTarget/Type/Type.php. PR #2884 changes will superscede the isset change presented in this PR, it's only there to prevent unit test failures.
-  tests/tests/bootstrap.php has been modified so that unit tests going forward will show `E_NOTICE` messages.
> Notice error fixes

- web/concrete/js/build/core/app/search/base.js
- web/concrete/js/build/core/file-manager/search.js
This was a fun one.
The file upload progress bar is in a dialog class. That prevented the pre-dialog close function from ever running the last dialog closing code, which removes the overflow hidden on the body element. So, if you uploaded a file the scroll bar would never come back.
That change caused the browser the redirect to the search results' json page anytime you selected the uploaded file from the success dialog. Eventually discovered this is because refresh was triggering submit on an element no longer in the document.
> Fixed scrollbar not reappearing after file upload

- web/concrete/src/Page/Collection/Version/EditResponse.php
- web/concrete/views/panels/page/versions.php
A several clients who are using workflow mentioned that Version list doesn't show who approved the version like 5.6.x.
So although there is some design issue. I've added the `Approved by` to the list.
What do you guys think?
We may want to adjust the design and CSS a bit.
Here are the screenshot
> Add ApproverUserName to Version list

- web/concrete/src/Marketplace/RemoteItemList.php
This PR fixes this warning:
```
Declaration of Concrete\Core\Marketplace\RemoteItemList::sortBy()
should be compatible with Concrete\Core\Legacy\ItemList::sortBy($column, $direction = 'asc')
```
> Make RemoteItemList::sortBy compatible with parent class

- web/concrete/src/Search/ItemList/ItemList.php
When the ccm_paging_p query parameter is not a number, such as 'a', an error is thrown. Instead, this assumes that it should show page 1.
This works similar to when the OutOfRangeCurrentPageException is thrown.
> Error when the ccm_paging_p query parameter is not a number

- tests/tests/Core/Area/AreaLayoutPresetTest.php
- web/concrete/src/Area/Layout/CustomColumn.php
Column ids are missing since 5.7.5.
Columns with a custom width don't work without this.
> Add column ids

- web/concrete/src/Form/Service/Widget/DateTime.php
Fix for #2922
Let's use the 'app' timezone (it's the default for PHP - it' set in [concrete/bootstrap/start.php](https://github.com/concrete5/concrete5/blob/5.7.5.1/web/concrete/bootstrap/start.php#L119))
> Fix localization of AM/PM

- web/concrete/config/app.php
- web/concrete/src/File/Service/File.php
Allow connection timeout to be configured with a global default for use when it is called without a second parameter from core files, Refs issue #2934
> Add config option for cURL timeout, #2934

- web/concrete/views/panels/page/devices.php
Add Device Screen Pixels, Screen Pixel Ratio, and Displayed Screen Pixels information to Mobile Device Preview items.
This pull request was based on a discussion in the forum.
"Also, although the iPhone 6 plus and Galaxy s5 are marked with the same screen size of 1920x1080 they don't actually have the same size so it might be better to also mention what size we're actually getting on screen. I think it's something like 340x640 for the samsung. That would be useful when trying to set breakpoints."
http://www.concrete5.org/community/forums/customizing_c5/5.7.5-release-candidate-1-now-available/#755709
**Current**
**Pull Request Changes**
> add additional screen information to Mobile Device Preview

- web/concrete/elements/block_header_view.php
The height is now high enough that you don't have to scroll.
> Make the height of some dialogs a little higher to prevent scrolling

- web/concrete/controllers/single_page/dashboard/system/seo/urls.php
Having a canonical URL not starting with http:// breaks everything. This modification throws an error in that case. Same with SSL canonical URL and https://
Franz suggested a pull request for this problem: http://www.concrete5.org/developers/pro-accounts/community-leaders-area/community-leaders-discussion/help-canonical-url-without-http-broke-complete-site-even-backend/
Here's Franz comment: http://www.concrete5.org/developers/pro-accounts/community-leaders-area/community-leaders-discussion/help-canonical-url-without-http-broke-complete-site-even-backend/#766489
> no http:// in canonical URL bug

- web/concrete/src/Foundation/Environment.php
We can add view.js/view.css to menu items, but `Environment` class doesn't check menu items directories.
> Check overrides on menu items directories

- web/concrete/config/install/base/attributes.xml
- web/concrete/controllers/single_page/dashboard/system/seo/bulk.php
- web/concrete/single_pages/dashboard/system/seo/bulk.php
This addresses #2951 
It doesn't remove the meta_keywords attribute (as it's used for dashboard page searching), but it simply removes it from the SEO attribute group and from the Bulk SEO Update dashboard page
If someone did still want to use the attribute for some reason (intranet, custom search engine), they can still add the attribute back to the group and use it as normal.
> Removal of meta_keywords from SEO attribute group and Bulk SEO Updater

- web/concrete/blocks/form/view.php
these string replacement broke as the commentor predicted at some point.
The lables now come from within the question['input'] which makes this code unnecessary and just leads to a stray ```</label>``` tag being output with every radio field in a form Block.
> removed hacky string replacement in form view

- web/concrete/single_pages/dashboard/blocks/stacks/view.php
dashboard/blocks/stacks
EditModeBlockMove event handler seems to be missing.
With this, the Approve button will show when blocks were moved.
> Handle EditModeBlockMove event, show Approval Button

- web/concrete/single_pages/account/messages/inbox.php
Current
----------
links to the members/profile all the time.
Desirable
------------
links to the members/profile when User Profile enabled.
Description
---------------
When User Profile is disabled, links to the members/profile page is useless.
Clicking these links will lead you to "PAGE NOT FOUND."
> Bug Fix: minor: members/profile page assumes User Profile enabled.

- web/concrete/controllers/panel/detail/page/permissions.php
- web/concrete/controllers/single_page/dashboard/system/permissions/site.php
- web/concrete/src/Package/StartingPointPackage.php
- web/concrete/src/Page/Page.php
When I don't use the advanced permission mode I can only see the language switch in the toolbar when I use the admin group created by the starting point. When I create my own group I simply can't use it.
I had to add the permission keys listed in this PR. I'm not sure it's supposed to be like that, but having a way to see the language switch is pretty helpful.
> add multilingual permissions to edit permissions

- web/concrete/js/build/core/layouts.js
in case the parent container width was not an integer, the free-form
layout broke the columns into two separate rows because the width was
set too large.
> fixed layout breaking on sub-pixel width of container

- web/concrete/attributes/date_time/controller.php
I've alredy posted the Issue here:
http://www.concrete5.org/developers/bugs/5-7-5-2/date-attributes-search-method-doesnt-work/
Since it's a minor code change i took the liberty of creating a PR.
> activate inline datepicker parameter in attributes search method

- web/concrete/single_pages/dashboard/system/basics/editor.php
The Editor Plugins phrase should be generic so that if someone overrides the editor it's not incorrect
> Redactor Plugins Rephrase

- web/concrete/src/Page/Theme/Theme.php
By extracting this part of the method we can easily override the result of ValueList in our page theme controller. This would offer the possibility to add custom values from our PHP code.
Creating a variable `my-color` would work with this:
```php
public function getThemeCustomStyleObjectValues()
{
$valueList = parent::getThemeCustomStyleObjectValues();
$myColor = new \Concrete\Core\StyleCustomizer\Style\Value\ColorValue('my');
$myColor->setAlpha(0.5);
$myColor->setRed(111);
$myColor->setBlue(222);
$myColor->setGreen(33);
$valueList->addValue($myColor);
return $valueList;
}
```
> return ValueList from separate method to be able to inject custom values

- tests/README.md
Instead of suggesting running the whole tests folder (with the `old` tests), only suggest to run the defined test suites.
> Modified the tests readme

- web/concrete/src/File/Version.php
- web/concrete/src/Http/FlysystemFileResponse.php
Downloading a file that exceeds the available memory today causes an out of memory issue. This pull request resolves that issue by implementing and sending a `FlysystemFileResponse` object that outputs a file from any file storage location.
> Resolve file download memory issue

- web/concrete/controllers/single_page/register.php
Prevent registration failures from causing a ban and remove undefined variable that wasn't used in mail template. For example, if you try and register and can't get your password to match or meet requirements a few times, this shouldn't be cause for a ban.
> Remove banning on failed registrations

- web/concrete/attributes/select/controller.php
Fix for 
http://www.concrete5.org/developers/bugs/5-7-5-2/can-not-filter-by-more-then-one-attribute
Your contribution guidelines don't say anything about which branch I should base my fix off, or which branch to create the pull request into, so this fix was pulled from master, and my pull request is into develop. Hope that's OK - if not, let me know and I can easily create a new pull request using different branches.
> Allow PageLists to be filtered by multiple select attributes

- web/concrete/src/Updater/Update.php
Avoids error on upgrade from 5.7.5.2 -> 5.7.5.3.
> Core::make() parameters must be array

- web/concrete/controllers/single_page/dashboard/system/files/thumbnails.php
Width and Height are not properly validated when creating thumbnail types as explained here: https://github.com/concrete5/concrete5/issues/3073
This fixes it
> Update thumbnails.php to validate input more thoroughly

- web/concrete/js/build/core/groups.js
When checkboxes are enabled, allow more than one group node to be selected in the tree.
-Steve
> Allow multiple node selection in group tree

- web/concrete/blocks/survey/controller.php
Fix was very easy... which makes me wonder why it was built this way in the first place? Is there something I'm missing, or just an oversight?
https://drive.google.com/open?id=0BxDKN4uzSheoUzlfeXgxczlHWEU
> Fixes #3061 by moving __construct logic to on_start

- build/tasks/translations.js
Transifex has a wrong plural forms count for these languages: Belarusian, Polish, Russian, Ukrainian.
This causes problems like https://www.concrete5.org/community/forums/internationalization/error/
Let's fix the translations downloaded from Transifex when building a new concrete5 release.
The remaining problem is that when people will upgrade their concrete5, the /application/languages folder is not updated.
> Fix wrong plural forms count for some languages

- web/concrete/elements/block_header_view.php
We define [`$canEditName`](https://github.com/concrete5/concrete5/blob/ae482f7b19f17409feeb02b96d932cfd9a067929/web/concrete/elements/block_header_view.php#L80) but we use `$canEditBlockName`: let's use `$canEditName`
PS: now that we have very few logged warnings, such errors can be detected much much easier.
> Fix misnamed $canEditName/$canEditBlockName

- web/concrete/attributes/date_time/controller.php
an alternative approach for https://github.com/concrete5/concrete5/pull/3119
> display no date in date widget for `null` - alternative

- web/concrete/src/Sharing/ShareThisPage/Service.php
- web/concrete/src/Sharing/ShareThisPage/ServiceList.php
Even though `print` is not an actual service it seems logical to have it as an option in `Share This Page` -block.
> Add print as a new service

- web/concrete/src/Editor/LinkAbstractor.php
Reimplements #3067, minus the import function and moved the dom manipulation to the end of export to prevent it interfering with the regex replacements
> fixes 3063 take2

- web/concrete/single_pages/dashboard/system/seo/codes.php
Textarea for tracking codes is so small that I always resize it. Let's make it a little bigger by default.
> Enlarge textarea for tracking code

- web/concrete/src/Attribute/Controller.php
some attributes return an array when you call `getValue`. This ensures that the export process doesn't process. It will most likely not work when importing, but that's a problem of the attribute..
> encode array when exporting attribute

- web/concrete/blocks/google_map/auto.js
- web/concrete/blocks/google_map/controller.php
An update to use the latest google maps api url, adding defer and sticking to https. This is really just to keep it up to date.
(I'm still getting errors/warnings in the console about the api being loaded twice when editing a block, couldn't work out how to resolve that, but it doesn't actually cause issues.)
> Update google map api urls

- CHANGELOG.md
- web/concrete/src/Console/Application.php
- web/concrete/src/Console/Command/InstallPackageCommand.php
- web/concrete/src/Console/Command/UninstallPackageCommand.php
- web/concrete/src/Console/Command/UpdatePackageCommand.php
- web/concrete/src/Package/Package.php
Supersedes #3153
Three new commands here:
`c5:package-install [--full-content-swap] <packageHandle> [packageOption1=value1 [packageOption2=value2...]]`
Where:
- `--full-content-swap` enables full contents swap (if package supports it)
- `packageHandle` is the handle of the package to install
- `[packageOption1=value1 [packageOption2=value2...]]` to pass options to the package install routine
`c5:package-uninstall [--trash] <packageHandle>`
Where:
- `--trash` moves the package directory to the trash
- `packageHandle` is the handle of the package to uninstall
`c5:package-update <--all|packageHandle>`
Where:
- `--all` to update al the updatable packages
- `packageHandle` the handle of a package to be updated
> Packages handling via CLI - reloaded

- web/concrete/src/User/UserInfo.php
this causes some fun problems if you want to re-use the already bound oauth id
> delete row in OauthUserMap when user is removed

- web/concrete/src/Config/DirectFileSaver.php
- web/concrete/src/Config/FileSaver.php
- web/concrete/src/Console/Command/ConfigCommand.php
Add an option to the c5:config command to control if saving to the `generated_overrides` folder:
Current (and default) behavior of
`concrete5 c5:config set concrete.external.news_overlay false`
is to save to `application/config/concrete.php`
Let's add a new option (`--generated-overrides` or simply `-g`):
`concrete5 c5:config -g set concrete.external.news_overlay false`
will to save to `application/config/generated_overrides/concrete.php`
> Allow saving options to the generated_overrides folder

- CHANGELOG.md
- web/concrete/src/Console/Application.php
- web/concrete/src/Console/Command/TranslatePackageCommand.php
Let's add a CLI command that generates/updates translation files...
This PR supersedes the `i18n` command of my [concrete5-build](https://github.com/mlocati/concrete5-build/tree/master/bin) repository
> Add c5:package-translate CLI command

- web/concrete/src/Console/Command/ConfigCommand.php
The correct name for the newly introduced option is `generated-overrides` and not `generated-override`
So, `$input->hasOption('generated-override')` always returns false.
It should be `$input->getOption('generated-overrides')`
My fault
> Fix detecting generated-overrides option in CLI config command

- web/concrete/tools/pages/delete.php
Bugtracker: https://www.concrete5.org/developers/bugs/5-7-5-3/properly-escape-javascript-strings/
> Correctly escape string from PHP to Javascript

- web/concrete/src/Block/View/BlockView.php
I found an instance of "Share this page" block which link is draft url. concrete5 should not create block output cache when that block is in draft page.
> Should not cache block when the page is in draft

- web/concrete/src/Console/Command/UpdatePackageCommand.php
When developing a package, it's handy to call the update process without having to update the controller `$pkgVersion` property or the `Packages`.`pkgVersion` table field.
So, what about adding a `--force` option to the `c5:package-update` cli command?
> Allow forcing package update

- web/concrete/config/concrete.php
- web/concrete/elements/page_controls_footer.php
- web/concrete/src/Application/Service/UserInterface.php
- web/concrete/src/Console/Command/InstallCommand.php
There's no way to globally hide the introductive help overlay.
Maybe once there was the `concrete.misc.seen_introduction` option, but now it does not affect anything.
What about adding a new `concrete.misc.help_overlay` option?
> Config option to hide introduction

- build/Gruntfile.js
- web/concrete/config/install/base/dashboard.xml
- web/concrete/controllers/single_page/dashboard/system/files/image_uploading.php
- web/concrete/elements/files/search.php
- web/concrete/js/build/core/file-manager/search.js
- web/concrete/js/build/vendor/jquery-fileupload/javascript-canvas-to-blob.js
- web/concrete/js/build/vendor/jquery-fileupload/jquery-fileupload-image.js
- web/concrete/js/build/vendor/jquery-fileupload/jquery-fileupload-process.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image-exif-map.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image-exif.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image-ios.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image-meta.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image-orientation.js
- web/concrete/js/build/vendor/jquery-fileupload/load-image.js
- web/concrete/single_pages/dashboard/files/search.php
- web/concrete/single_pages/dashboard/system/files/image_uploading.php
Works on modern browsers, IE10+.
In older browsers (such as IE9), the file upload still completes but simply doesn't do the client size resize.
> Client side image resize on upload, dashboard page for configuration

- web/concrete/attributes/number/controller.php
if a browser doesn't support an input type it will fallback to the default type text. This shouldn't cause any problems and make it impossible to enter text in a number field..
> use number input for number attribute

- web/concrete/views/panels/sitemap.php
When making a page draft, the name of the page draft (or "(Untitled)" if there is no name) is displayed in the Pages panel. You could potentially have page drafts with the same name in different locations, but not know which one was which. This pull request adds the date added to the draft name.
**Current**
**Pull Request**
> add date added to page drafts in Pages panel

- web/concrete/src/Block/View/BlockView.php
I noticed that when including another file from the template of a block of external_form type, the `file` variable is being overwritten by `extract($this->getScopeItems());`.
One possible solution could be to pass `EXTR_SKIP` as the second parameter in the `extract` function, but renaming the variable might just do it.
Steps to reproduce the issue:
* Create a new block of type `External Forms`
* Assign to the block a custom template
* Inside the template, make sure you write `<?php $this->inc( 'some/path/some_file.php' ); ?>`
* You should get the error `Object of class Concrete\Core\File\Service\File could not be converted to string`
Let me know what you guys think.
Have a good one!
> [BlockView] renaming file in inc method to avoid variables extraction conflict

- web/concrete/src/Application/Application.php
We need to apply urldecode before comparing URLs since
the URLs may be urldecoded when we use mod_rewrite.
See. "6.2.2.2.  Percent-Encoding Normalization" at https://www.ietf.org/rfc/rfc3986.txt
> Apply urldecode before comparing two URLs

- web/concrete/src/Form/Service/Form.php
The `id` attribute of `<input type="radio">` elements is build starting from `radioIndex`, btw the value of `radioIndex` may not be known.
What about adding the ability to manually specify it via
```php
$form->radio('name', 'value, '', array('id' => 'id'));
```
?
> Allow manually setting radio id

- web/concrete/blocks/feature/controller.php
- web/concrete/blocks/feature/form.php
Currently if you add a picture to a feature paragraph area (or other abstracted string) and go to edit it it doesn't get translated back
> Fixes feature paragraph edit

- CHANGELOG.md
- web/concrete/src/Console/Application.php
- web/concrete/src/Console/Command/PackPackageCommand.php
This is a quite flexible command that allows (mainly) to create a zip files containing a package.
It offers the following features:
- compile .po translations to .mo files
- generate .png icons from .svg files (requires Inkscape)
- expand php short tags (`<?` and `<?=`, or `<?` only)
- create a zip package with or without the .po/icon.svg files
- create a zip package with or without the .dot files
- update the source package directory (useful to automatically expand short tags/compile translations or icons)
- support pre-5.7 packages (just specify the package directory instead of the package handle)
> Add new c5:package-pack command

- web/concrete/blocks/dashboard_app_status/view.php
The URL was old 5.6 link to Update page resulted on 404.
Bug report from Endo from concrete5 Japan.
http://concrete5-japan.org/community/forums/bug/post-12302/
> Fix newsflow url to Dashboard's update page

- web/concrete/controllers/frontend/assets_localization.php
- web/concrete/js/build/core/file-manager/search.js
Thumbnail editing is hidden away within the properties dialog. This simply adds the option to the file menu in the file manager, so you can directly edit thumbnails.
Thumbnail defining is such an underrated and under-discussed feature of 5.7!
> Add thumbnail option to file manager menu

- web/concrete/controllers/install.php
- web/concrete/views/frontend/install.php
Let's use `var_export` when saving the variables to `site_install_user.php` to avoid problems.
For instance, emails may contain apostrophes: in this case the concrete5 installation breaks.
> Fix install apostrophes

- web/concrete/config/concrete.php
- web/concrete/src/File/File.php
This table can bloat, for people who don't need it it would be good to have an option to disable it.
> Add configuration to disable download statistics tracking

- web/concrete/composer.json
- web/concrete/composer.lock
- web/concrete/src/Application/Application.php
This allows us to make full use of the new DI features in laravel 5.2. Check out https://laravel.com/docs/5.2/container for more info (We support all of that!)
> Update illuminate/container dependency and deprecate bindShared method

- web/concrete/authentication/concrete/password_changed.php
The class `.alert-sucess` should be `.alert-success`
> Fix typo in password_changed.php

- web/concrete/src/Editor/LinkAbstractor.php
Allows images that might have something like <img style="width: 200px; height: 200px;"...> to leverage the responsive picture elements. Previously these would have been detected as having a style attribute and thus would not be placed within the <picture> element
> Better support for <picture> elements in content blocks

- web/concrete/blocks/image_slider/add.php
- web/concrete/blocks/image_slider/controller.php
- web/concrete/blocks/image_slider/db.xml
- web/concrete/blocks/image_slider/form_setup_html.php
- web/concrete/blocks/image_slider/view.php
This pull request adds the following ResponsiveSlides.js features to the Image Slider block form.
auto: true,             // Boolean: Animate automatically, true or false
speed: 500,            // Integer: Speed of the transition, in milliseconds
timeout: 4000,          // Integer: Time between slide transitions, in milliseconds
pause: false,           // Boolean: Pause on hover, true or false
The navigation and options have been placed together in a new tab. By default the slider will use the speed and timeout defaults included in ResponsiveSlides.js.
An extra validation check is required due to a bug in ResponsiveSlides.js. 
"The 'timeout' (amount of time spent on one slide) has to be at least 100 bigger than 'speed', otherwise the function simply returns." …
> add ResponsiveSlides.js options to Image Slider block form

- web/concrete/src/View/DialogView.php
Put Inline Javascript with `ccm_addHeaderItem()` causes 404 error.
> Put Javascript Inline Asset directly into edit block dialog

- web/concrete/src/Application/Application.php
Before we were comparing a parsed url with the request URL which would attempt to normalize FAR too many things. Now we only care whether or not there's a trailing space depending on the configuration.
This should resolve #3258 if it is indeed still an issue.
> refactor: Update Application::handleUrlSlashes so that it ONLY handles url slashes.

- web/concrete/js/image-editor/controls/position.js
- web/concrete/views/image-editor/controls/position.php
When editing a thumbnail, it can be challenging to use the scale slider and mouse to restore the thumbnail's original position and size. 
The Fit Image button resets the thumbnail to its original size and position.
**Reset Thumbnail Size**
**Reset Thumbnail Position**
> add Fit Image button to Image Editor

- tests/tests/Core/Controller/ControllerResolverTest.php
- web/concrete/src/Controller/ApplicationAwareControllerResolver.php
When the old controller resolver was loaded before the new one, a namespace collision would occur. resolves #3279
> fix: new ControllerResolver namespace collision

- web/concrete/controllers/install.php
- web/concrete/src/Console/Command/InstallCommand.php
- web/concrete/src/Package/Routine/AttachModeCompatibleRoutineInterface.php
- web/concrete/src/Package/Routine/AttachModeInstallRoutine.php
- web/concrete/src/Package/StartingPointPackage.php
When the `--attach` flag is supplied with a `concrete5 c5:install` call, if the supplied database already has rows we will attach to it rather than failing.
This change adds an interface that lets you mark your own `StartingPointInstallRoutine` steps as required to run in attach mode, just implement the `\Concrete\Core\Package\Routine\AttachModeCompatibleRoutineInterface` interface.
This should resolve #3298
> Feature: Attach mode for CLI installer

- web/concrete/elements/page_controls_footer.php
- web/concrete/single_pages/dashboard/pages/types/output.php
**Current**
- when on the Defaults and Output page, clicking on an Edit Defaults link opens a new tab
- the new Edit Defaults tab looks very similar to editing a regular page, with the only difference being the arrow/back button in the toolbar
- the arrow/back button in the toolbar is a link back to the Page Types page
**Changes**
- Edit Defaults links open in the same window
- the arrow/back button in the toolbar has a text label "Exit Edit Defaults" to help differentiate it from editing a regular page
- the arrow/back button links to the Defaults and Output page for that page type for faster editing of multiple page template defaults
http://www.concrete5.org/community/forums/documentation_efforts/really-hard-user-expirence-for-editing-master-page-pagetype/
> Edit Defaults - open in the same window, add label, and change back arrow link

- web/concrete/authentication/concrete/controller.php
Predictable random number generators could result in session takeover, since the auth cookies could be guessed.
`mcrypt_create_iv` will fall-back to insecure RNG if there's no `/dev/urandom` available.
(It would actually be better if this function would crash instead of falling back...)
> Prevent predictable tokens in certain setups

- tests/tests/Core/Session/SessionFactoryTest.php
- tests/tests/Core/Session/SessionValidatorTest.php
- web/concrete/src/Session/Session.php
- web/concrete/src/Session/SessionFactory.php
- web/concrete/src/Session/SessionFactoryInterface.php
- web/concrete/src/Session/SessionServiceProvider.php
- web/concrete/src/Session/SessionValidator.php
- web/concrete/src/Session/SessionValidatorInterface.php
- web/concrete/src/User/User.php
This allows us to use session with the DI container, and makes it a bit easier to work with session generation in a middleware request initialization flow.
> Refactor: Clean up session management

- web/concrete/blocks/autonav/auto.js
- web/concrete/blocks/autonav/controller.php
- web/concrete/blocks/autonav/db.xml
- web/concrete/blocks/autonav/form_setup_html.php
- web/concrete/blocks/autonav/tools/preview_pane.php
There has been a static attribute to configure the availability of system pages in the auto-nav block, but it was not configurable from the UI. This pull request adds a checkbox to the UI to enable showing of system pages (and a database field to store this value).
EDIT: as it turns out, this feature appears to have been available in 5.6. Was it removed for a specific reason, or just never fully ported?
> Add support for system pages to autonav block

- web/concrete/css/build/core/app/toolbar.less
When toolbar titles are turned on the little blue pulsing spinner doesn't sit on top of the icon correctly.
This is a fix for that. After:
> Fix position of blue spinner on toolbar when titles turned on

- web/concrete/src/Page/PageList.php
I was noticing on our large site that the fulltext search results did not appear accurate. Upon investigation using the SQL logs, I observed that the cIndexScore column had no ORDER BY directive. This would render the results pseudo randomly. By adding a ORDER BY with DESC, the best scored results display first.
> fix: fulltext was not sorting by cIndexScore

- web/concrete/themes/concrete/background_image.php
If concrete5 has been updated and is running from `updates/`, `DIR_REL` always points to the original concrete5 core, `ASSETS_URL_IMAGES` points to the right update.
> Use ASSETS_URL_IMAGES instead of DIR_REL

- web/concrete/blocks/image_slider/controller.php
- web/concrete/blocks/image_slider/form_setup_html.php
This pull request makes the individual slide entries collapsible and draggable. When adding a new slide, all other slides collapse, significantly reducing the amount of scrolling to reach the Add Slide button to create another slide. When dragging, there is a blue placeholder showing where the slide will be dropped
The Slide Duration and Slide Transition Speed inputs were changed from text to number.
**Closed Slides**
**Open Slide**
**Drag Placeholder**
I believe there is an existing upgrade script for the Image Slider block:
https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Updater/Migrations/Migrations/Version20151221000000.php#L27-L30
> make slide entries collapsible and draggable

- web/concrete/src/Block/Block.php
Feature Request: Block::getByName() shouldn't be limited to Stacks #3115
> getByName() returns global and non-global blocks

- web/concrete/src/Authentication/Type/OAuth/ServiceProvider.php
The following change broke the generic OAuth login in 5.7.5.4: https://github.com/concrete5/concrete5/commit/8eaac83641686eb43f81f72027c412d264e02ca1#diff-ced5220248e4a9d14defe88b7d4e7836
Error message: `Argument 1 passed to OAuth\UserData\ExtractorFactory::get() must implement interface OAuth\Common\Service\ServiceInterface, array given, called in […]/concrete/src/Authentication/Type/OAuth/ServiceProvider.php on line 38 and defined`
I'm not too familiar with Laravel IoC and [the documentation](https://laravel.com/docs/4.2/ioc) about it rather sparse, but from what I gathered by looking at the source and usage on GitHub it seems the second parameter of the bind closure should be `$params = array()`.
This proposed fix keeps the type `oauth_extractor` backward compatible.
@KorvinSzanto Can …
> Fix oauth_extractor bind parameters

- web/concrete/views/panels/sitemap.php
Prevent default behaviour (#) when clicking a link to show more page types
> Prevent default behaviour when showing all available page types

- web/concrete/composer.json
- web/concrete/composer.lock
All this does is add PSR-4 namespacing to the tests when composer is installed in development mode. 
#3356
> Add PSR4 namespacing to tests

- web/concrete/blocks/form/form_setup_html.php
Form block's questions are ordered incorrectly after ordering some of them and creating a new question.
- Add form block to a page
- Write `Q1` to Question and click `Add Question`
- Write `Q2` to Question and click `Add Question`
- Click `Edit` tab
- Change order of the question, move `Q2` to first position
- Click `Add` to save the block
- Questions are now in correct order
```
Q2
Q1
```
- Edit the block you just created
- Write `Q3` to Question and click `Add Question`
- Click `Save` to save your changes
- Questions are now in wrong order
```
Q2
Q3
Q1
```
The reason is that the position value was always passed on as undefined to save method while adding a new question. Easiest way to prevent this is to add a similar position field to add template that edit template has.
> Fix questions' order in form block

- web/concrete/src/User/UserInfo.php
An error was thrown e.g. when trying to change user's password in dashboard while MYSQL is used in STRICT_TRANS_TABLES mode
```
'update Users set uName = ?, uEmail = ?, uPassword = ?, uHasAvatar = ?, uTimezone = ?, uDefaultLanguage = ?, uLastPasswordChange = ? where uID = ?' with params ["username", "test@example.com", "hash", false, null, "fi_FI", "2016-01-19 09:20:00", "1"]
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'uHasAvatar' at row 1
```
> Fix user update in strict mysql

- web/concrete/src/Localization/Localization.php
We call `unset($this->translate)`: this leads to warnings when we try to access `$this->translate`
> Avoid accessing undefined $translate property in Localization

- .gitignore
Eclipse just created a `.externalToolBuilders` folder in my local concrete5 directory. I don't know neither why nor what's it. Let's just ignore it...
> Ignore Eclipse folder: .externalToolBuilders

- web/concrete/blocks/core_scrapbook_display/controller.php
- web/concrete/src/Block/Block.php
Test:
Install full elemental
Copy HR block on the homepage
Paste HR block on the homepage
Before this commit, the pasted HR does not span full width. After, it does.
Supersedes #3397
> Fix: Make copy/pasted blocks retain full width setting

- web/concrete/themes/elemental/elements/header_top.php
this line https://github.com/concrete5/concrete5/blob/develop/web/concrete/elements/header_required.php#L39 is currently useless as we can't set `pageDescription` from a controller.
> forward page description to  header_required

- web/concrete/single_pages/dashboard/extend/install.php
- web/concrete/src/Package/Package.php
Currently when a package is uninstalled, we always try to load an uninstall element, even if it does not exist.
Let's add a `hasUninstallNotes` method that checks if this element exists or not (like we already have for the pre-install and post-install phases - see `hasInstallNotes` and `hasInstallPostScreen` respectively).
> Add Package::hasUninstallNotes()

- web/concrete/css/build/core/file-manager.less
- web/concrete/single_pages/dashboard/files/sets.php
We can change the thumbnail size for the filemanager list, but what's the point of that if there's a max height? A customer of mine wants bigger thumbnails (actually a bigger thumbnail on hover), but that didn't work without thix change.
> remove max height from filemanager thumbnail

- web/concrete/controllers/single_page/dashboard/system/backup/update.php
WIth PHP 7.0.2 visiting /index.php/dashboard/system/backup/update results in an exception:
Declaration of Concrete\Controller\SinglePage\Dashboard\System\Backup\UpdateArchive::install($file)
should be compatible with Concrete\Core\Updater\Archive::install($file, $inplace = false) 
http://www.concrete5.org/developers/bugs/5-7-5-5/php7-concrete5-dashboard-update-throws-exception/
> PHP7 Fix incompatible declaration of UpdateArchive::install

- web/concrete/controllers/install.php
- web/concrete/src/Console/Command/InstallCommand.php
- web/concrete/src/Package/StartingPointPackage.php
Calling `StartingPointPackage::getClass` with an invalid class caused the execution flow to abort since the code tried to instantiate a non-existing class.
> Fix StartingPointPackage::getClass

- web/concrete/js/build/core/editable-field/container.js
These links' default behaviour (#) should be prevented, but their click functions were returning an object instead of false.
These functions are called when clearing user's attribute or avatar in 
Dashboard -> Members -> Search Users -> Edit User
> Prevent default behaviour when clearing user's attribute or avatar

- web/concrete/js/build/core/editable-field/container.js
Dashboard -> Members -> Search Users -> Edit User -> Change Profile Picture
User's avatar's url doesn't change when you change the image. Because of that the image doesn't reload after a change until you reload the page. That can cause users to think that it is not working. 
Let's force the image to reload by adding unique parameter to it's url after a change.
> Force user avatar to reload after a change

- web/concrete/single_pages/dashboard/pages/single.php
Base path is displayed incorrectly if url rewriting is disabled
> Fix displayed base path in single pages

- web/concrete/controllers/single_page/dashboard/pages/feeds.php
Add default value for page type filter.
An error was thrown while adding a new feed without page type filtration when using mysql in strict mode.
```
An exception occurred while executing 'INSERT INTO PageFeeds (customTopicAttributeKeyHandle, customTopicTreeNodeID, iconFID, pfDescription, pfHandle, pfTitle, cParentID, ptID, pfIncludeAllDescendents, pfDisplayAliases, pfContentToDisplay, pfAreaHandleToDisplay, pfDisplayFeaturedOnly) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["", 0, "0", "Description", "lorem", "Lorem", 154, "", "1", "0", "S", null, "0"]: 
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'ptID' at row 1
```
> Prevent error while adding a new feed without a page type filter

- web/concrete/controllers/single_page/dashboard/blocks/stacks.php
Steps to reproduce:
- Go to: Dashboard -> Stacks & Blocks
- Add a new stack `A`
- Click rename
- Change name to `B`
You will now get a message "No stacks have been added." as a result of an incorrect action.
> Fix incorrect action after renaming a stack

- web/concrete/src/Page/Collection/Version/EditResponse.php
- web/concrete/views/panels/page/versions.php
Dashboard -> Stacks & Blocks -> View stacks details -> Version history -> Hover over a version and click the arrow link next to it
Remove redundant `New Page` link from stacks version history item's menu
> Remove New Page link from stacks version history

- web/concrete/composer.json
- web/concrete/composer.lock
There's a problem with 5.7.5.4/5 - it's impossible to register as a new user because a perfectly valid email address is rejected as incorrect. This is due to the recent addition of the strict argument in the Strings.php helper which exposes the bug. The underlying vendor library fixed the bug over a year ago. This pull just updates composer.json and composer.lock to pull in the fixed version. Not sure if this is entirely the right way to proceed or whether a more recent version of the library (current is 1.2.11) is appropriate, but it needs some quick attention since this is something of a show stopper for a lot of people.
More info:
https://www.concrete5.org/community/forums/5-7-discussion/email-validation-issues-on-5.7.5.4
https://www.concrete5.org/developers/bugs/5-7-5-5/registration-do …
> Upgrade egulias/email-validator to 1.24

- web/concrete/blocks/core_area_layout/templates/parallax/view.css
- web/concrete/blocks/core_area_layout/templates/parallax/view.js
- web/concrete/js/build/core/frontend/parallax-image.js
Resolves issue #3413. The issue was that the container had `overflow:hidden` on it. Instead I give the parallaxic image it's own full width full height `overflow:hidden` container.
> Fix: Show area tab in parallaxic layout view

- web/concrete/single_pages/dashboard/reports/logs.php
Dashboard -> Reports -> Logs
Change the clear button to red to indicate that it actually deletes something
**before**
**after**
> Adjust clear log button to indicate dangerousness of the action

- web/concrete/src/Multilingual/Service/UserInterface/Flag.php
A small bug was introduced in #3362 (#3309). It fixed a typo in a class name. When the correct class is applied to a flag image it gets displayed as a block, which causes layout to break if toolbar titles are enabled.
That class seems to be redundant, so let's just remove it.
> Fix flag image layout

- web/concrete/blocks/next_previous/controller.php
`Exclude system pages` is actually always true
Steps to reproduce
- *Ensure that block cache is disabled*
- Add `Next & Previous Nav` -block to a page with `Exclude system pages` *unchecked*
- Save block
- Edit the block again
- `Exclude system pages` is *checked*
With block cache it *seems* to work, but `excludeSystemPages` was always saved as 1
> Fix save in next_previous block

- web/concrete/src/Page/Type/Composer/Control/BlockControl.php
#2787 Composer Page Template Block Default Styles
To reproduce issue on a current build, find any page type that has a composer form defined. Edit it's default output and set a custom style on any block that is generated via a composer control. If you then go and create a page of this type via composer, the custom styles are not applied to that block.
> Fix: Page Type Default Block Styles

- web/concrete/css/build/core/file-manager.less
- web/concrete/src/File/Image/Thumbnail/Type/Version.php
- web/concrete/views/dialogs/file/thumbnails.php
Bootstrap style cards for faster browsing of large numbers of thumbnails.
I tested this by creating a mix of very wide and very tall thumbnails and also long thumbnail names.
**Current**
**Changes**
_standard and wide thumbnail sizes_
_standard and tall thumbnail sizes_
_responsive_
_long thumbnail names_
> allow for faster browsing of thumbnails

- web/concrete/css/build/themes/dashboard/main.less
The alerts that get shown in the dashboard don't align on the right hand side with the rest of the page content \*twitch\*, due to an unnecessary right margin. This PR simply removes this. I couldn't find a reason for this margin to be there.
before
after
> Removal of unnecessary margins on dashboard result message

- web/concrete/controllers/feed.php
The \Concrete\Core\Controller\Controller::get method has a signature of get($identifier=null, $defaultValue=null). This signature was causing issues on PHP7.
> Add default parameter values to   method

- web/concrete/elements/page_controls_footer.php
This appends the label 'Composer' to the Page Settings button, if the current page is configured for the composer.
A current concern is that the composer is sort of hidden away in the Page Settings panel, and it's not really obvious that you can click the Page Settings button to get to it. So this is a small suggestion as to how the feature can be made a bit clearer (at least when the labels are turned on).
For 5.6, Hissy and myself both released 'Edit In Composer' toolbar buttons - I had _many_ requests to add this button to sites, and I know personally it made a huge difference. 5.7 fortunately has the _feature_ of being able to directly edit a page in Composer, but it's just not clear that it's there.
> Addition of Composer label to Page Settings button (if applicable)

- web/INSTALL.md
`tools/upgrade` doesn't work anymore, taken text from http://documentation.concrete5.org/developers/installation/upgrading-concrete5
> fix upgrade path

- web/concrete/src/User/User.php
This would allow us to still use getByUserID if the User class has been extended.
> User late static binding

- web/concrete/blocks/page_list/view.php
Use correct target when `Use Different Link than Page Name` option is enabled in page list
> Use correct target in page list links

- web/concrete/blocks/page_attribute_display/controller.php
We can select file type attribute, but if we set both sizes empty, it causes an error:
```
Imagine\Exception\InvalidArgumentException thrown with message "Length of either side cannot be 0 or negative, current size is 0x0"
```
> Avoid InvalidArgumentException with Page Attribute Display block

- web/concrete/elements/header_required.php
- web/concrete/themes/elemental/elements/header_top.php
I know that I feel I'm wasting my time.
But, one of my clients asked me if they can override meta keyword.
I've told them that Google no longer uses Meta Keyword. They knew, but they still want to set the Meta Keyword pattern.
So, I had to implement the meta keyword override.
But header_required.php doesn't allow override. So I would like to suggest to include the override.
> Adding Meta Keyword Override

- web/concrete/elements/storage_location_types/local.php
> Fix translated placeholders on storage location paths

- web/concrete/src/Attribute/Value/Value.php
The `getAttributeTypeObject()` method relies on the instance variable `atID` which might not have been set up if the attribute value doesn't exist.
> Fix error when attribute value not found

- web/concrete/attributes/select/controller.php
Currently select attributes ignore the comparison operator. Some operators often won't make sense, but != or <> can be translated into NOT LIKE and will work every time. This commit checks for the two operators mentioned, using NOT LIKE, otherwise defaulting to LIKE.
> Allow filter select attribute using NOT LIKE through comparison

- web/concrete/controllers/single_page/dashboard/users/search.php
Any reason why we disabled username change from the dashboard when the email address was used to log in? The username validation is there so in case someone decides to switch back to usernames they don't have duplicates.
> Enable username change from the dashboard

- web/concrete/src/Page/Type/Composer/Control/CorePageProperty/DescriptionCorePageProperty.php
- web/concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
- web/concrete/src/Page/Type/Composer/Control/CorePageProperty/UrlSlugCorePageProperty.php
Our page property validator checks the value is true or false. Let's validate it is empty string or not.
> Fix: we are not able to create a "0" page

- web/concrete/bin/concrete5.php
- Let's assume you symlinked the CLI entrypoint (eg with `ln -s /path/to/website1/concrete/bin/concrete5 /usr/local/bin/c5`) for website 1
- Let's assume you want to run the CLI commands for website 2 using the symlinked `c5` entrypoint
Currently this is not possible.
Let's allow this simply by `cd /path/to/website2`, so that `c5` will use it.
> Detect CLI environment from current working directory

- web/concrete/blocks/html/form_setup_html.php
Entity of html block become invalid
Steps to Reproduce
1.add html block input entitized "&lt;h1&gt;aaaa&lt;/h1&gt;"
2.save
3.edit html block. show "&lt;h1&gt;aaaa&lt;/h1&gt;"
4.Save without doing anything.
5.entity of html block become invalid.
> fix html block entity

- web/concrete/single_pages/dashboard/reports/forms.php
File URL was not working when using a private file location.
> Fix file url in form results

- web/concrete/bin/concrete5.php
Currently the CLI entrypoint that gets executed is the one in the /concrete/bin directory.
Let's detect if there's an updated core, and if so let's run the new CLI entrypoint.
> Detect updated core in CLI commands

- web/concrete/src/Editor/RedactorEditor.php
Entity of content block become invalid.
Steps to Reproduce
1.add content block "html mode " input entitized "&lt;h1&gt;aaaa&lt;/h1&gt;"
2.save
3.edit content block. show "&lt;h1&gt;aaaa&lt;/h1&gt;"
4.Save without doing anything.
5.entity of content block become invalid.
> fix content block entity

- web/concrete/src/Session/SessionFactory.php
The PHP setting `gc_maxlifetime` is named incorrectly and as such, settings in `/application/config/concrete.php` are not applied to the session correctly.
See also http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime
> Bugfix: gc_max_lifetime should be gc_maxlifetime

- web/concrete/src/User/User.php
I tested the community authentication, and I had a strange error in `getByUserID`: `$nu` didn't have the `setPropertiesFromArray` method.
This PR fixes this problem.
> Make User::loginByUserID static

- tests/tests/Core/Form/Service/FormTest.php
- web/concrete/src/Form/Service/Form.php
- web/concrete/src/Form/Service/Widget/DateTime.php
This seems like the last function in the Form.php file that was using $_REQUEST. 
Did the same thing in the DateTime widget.
The fix allow to use id with brackets. Eg.:  myRadio[1][foo]
> use getRequestValue instead of $_REQUEST 

- web/concrete/src/Authentication/Type/Facebook/ServiceProvider.php
The problem was that we had
```php
$factory = $app->make('oauth/factory/service', array(CURLOPT_SSL_VERIFYPEER => Config::get('app.curl.verifyPeer')));
```
but no `use Config;` was present.
> Fix Facebook authentication

- web/concrete/src/Console/Application.php
- web/concrete/src/Console/Command/ExecCommand.php
I often have to run one-time scripts from the console.
Every time I need this, I have to initialize the concrete5 environment, then write the script itself.
What about adding a wrapper command?
Here's an example:
1) create a `test.php` file like this:
```php
<?php
$dh = Core::make('helper/date');
echo $dh->formatDateTime('now', true);
```
2) execute `test.php` simply with `concrete/bin/concrete5 c5:exec test.php`
> Add c5:exec CLI command

- tests/phpunit.xml
- tests/tests/Localization/LocalizationTest.php
- tests/tests/bootstrap.php
This would detect wrong translatable strings.
For instance, if the PHP code contains something like this:
```php
echo t2('One %s', 'Two %d', $n);
```
The tests would fail with this message:
```
/application/languages/messages.po:19: format specifications in 'msgid_plural' and 'msgstr[0]'
for argument 1 are not the same
msgfmt: found 1 fatal error
4284 translated messages.
```
(we've had this problem in an old version of 5.6)
> Re-enable tests on translatable strings

- web/concrete/controllers/single_page/login.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
Let's preserve the requested URI when we access a page that requires user access but no user is logged in, so that we can forward to a page specific action after users log in.
> Preserve original URL when login is needed

- web/concrete/jobs/generate_sitemap.php
Issue detail:
1. Empty self-closing changefreq element is not allowed on Search Console
2. There is a possibility that $changefreq is a object if the attribute type is select
> Avoid sitemap.xml error on Search Console

- web/concrete/src/Package/Package.php
Fixes backwards comaptibility for the modified package methods, as discussed here:
https://github.com/concrete5/concrete5/commit/8a5b34dde8d81f98517f18ece8cd7da104689732#diff-b2c917c0f9a391f0bd443dd9ae1af539L590
> Backwards compatibility

- web/concrete/src/Page/Type/Composer/Control/Control.php
As I was creating documentation for adding Page Type's Composer forms programmatically, I noticed that you can only set the custom label after the fact. While this makes sense with the web ui, it doesn't make sense for people programmatically creating these items with packages.
This adds setting, getting, and adding the custom label to the initial creation of the object.
UPDATE: the 3rd commit also adds support for presetting the description, since there is no reason that shouldn't be allowed as well.
> Add Set Page Type Control Label Setting/Getting during Creation

- web/concrete/js/build/core/app/panels.js
- web/concrete/views/panels/details/page/attributes.php
- web/concrete/views/panels/details/page/seo.php
This is a suggested change to improve the user experience when updating page attributes (or attributes via the SEO panel). 
At the moment when you go into these panels and do a save, there's no prompt to suggest you need to actually publish the page.
<del>This tweak triggers the page publishing panel on the save of these two panels. </del>
Updated to a refresh instead
Overly descriptive video demo here!  - https://www.youtube.com/watch?v=PfHyYQ3d8Js
> Trigger refresh on save of attributes and SEO

- web/concrete/config/app.php
- web/concrete/controllers/feed.php
- web/concrete/src/Page/Feed.php
This is a few updated fixes for #3485
> Update page feed controller to not collide with Controller::get

- web/concrete/themes/elemental/css/build/content.less
Images added using the Content block will not resize correctly if they are wider than their parent container. Adding height auto corrects this.
Example:
The top image was added to the page using the Image block. By default this image will get the img-responsive class. The bottom image was added using the Content block. 
**Current**
**Changes**
https://www.concrete5.org/community/forums/usage/squashed-images-mobile-view/
> add height auto to div.ccm-page img

- web/concrete/blocks/image_slider/form_setup_html.php
Makes for far less scrolling and annoyance when adding multiple slides.
I was just trying to add 15 slides to a slideshow, and kept having to scroll back up to add. It makes more sense for the ADD button to be below the entries. 
(pre-emptive comment: Yes, if there are already entries, they will have to scroll down. But it can be assumed that people editing slideshows will have added images before, and the scroll bar in general makes it pretty obvious. The decrease in annoyance for all users vs a very low chance of confusion for one or two users weighs towards the former for me).
> Move ADD button for image slider to below the slides

- tests/tests/Localization/LocalizationTest.php
The extraction of translatable strings may throw an exception if the structure of the xml files changes.
Since it a problem of the Translation Library and not of the core, let's just ignore such errors.
> Ignore extraction of translatable strings

- web/concrete/authentication/concrete/forgot_password.php
there was an extra closing div in the forgot password action of the default concrete5 authentication. This pr removes it.
This may have an impact on people who have styled their pages based off the previous HTML
> remove extra div from forgot password

- build/tasks/build-release/clean.js
Now that we have a CLI interface, some package could require them (for instance https://github.com/concrete5/addon_community_translation/issues/7)
> Keep binary/executable files in releases

- web/concrete/controllers/frontend/assets_localization.php
- web/concrete/js/build/core/translator.js
The [Community Translation](https://github.com/concrete5/addon_community_translation) add-on requires to intercept some functions/events of the Translator javascript object.
I'll add to this pull request the required changes, so that people that want to try the add-on can have a functional concrete5 installation.
Please wait before accepting/refusing this pull request until I'm sure that every required edit is done.
> Allow extending translator.js functions

- web/concrete/blocks/image_slider/controller.php
- web/concrete/blocks/image_slider/db.xml
- web/concrete/blocks/image_slider/form_setup_html.php
- web/concrete/blocks/image_slider/view.php
This will allow the image slider to be narrower if needed in wide situations
As I was adding in some 4:3 images to the slider, the lower responsive breakpoints were fine, but the 1170 one was making the images crop in an insanely ugly way. This option will allow more control in those types of situations
> Add Max Width to Image Slider

- web/concrete/css/build/vendor/jquery-magnific-popup/jquery-magnific-popup.less
- web/concrete/js/build/vendor/jquery-magnific-popup/jquery-magnific-popup.js
**Changes from the current 1.0.0 version**
https://github.com/dimsemenov/Magnific-Popup/releases
"1.1.0
dimsemenov released this 18 days ago
Dropped built-in fast-click support in favor of modern touch-action property. If you still need it in browsers that have 300ms delay, use FastClick by FT Labs.
Dropped basic IE7 support (if you still need to support old IE, keep using the previous version).
Sanitized attributes with jQuery when replacing img element (#770 via @makkaq).
Added 'style' property to package.json (#816 via @jonscottclark).
Removed vendor prefixes for box-sizing and box-shadow (via @chicagoing).
1.0.1
dimsemenov released this on Dec 30, 2015 · 15 commits to master since this release
New option autoFocusLast to on/off autofocusing after popup close (via @resetko).
Shift- and …
> update Magnific Popup to version 1.1.0

- web/concrete/elements/page_controls_header.php
This padding top value for div.ccm-page should be 48px there is an extra pixel showing at 49px.  The actual set height of the .ccm-toolbar-item-list and div#ccm-toolbar in toolbar.less (see attached)
> Fix height of padding to match actual height of ccm-toolbar

- web/concrete/src/Package/Package.php
Without the id we'll run into an issue when running `c5:package-update --all`. This method calls this line at some point https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Package/Package.php#L805
If that happens we'll need the package id to get the list of block types in that package..
> set package id in upgradeable packages

- web/concrete/attributes/select/type_form.php
This fixes a bug in webkit browsers when editing the options of a select attribute.
There currently is a handler in place to respond to an enter keypress to save, as well as up and down keypresses to quickly navigate between editing the options.  
The problem is that if you type Shift+9  (for a left parenthesis), in webkit browsers onkeypress returns the wrong keycode, it returns the keycode for a down keypress for some reason. So you can't type in a ( character, it jumps to the next field. Pressing up and down on the keywork also doesn't work.
By changing it to onkeydown, the correct keycodes are returned again and it works as designed.
> Change to onkeypress - fixes bug with webkit browsers

- web/concrete/themes/dashboard/default.php
I was doing some testing, and realized that it was impossible to add regular pages (as opposed to single pages) under the dashboard node in the site map. Almost every project I've done in 5.6 in the last three years has used page types in the dashboard instead of single pages. But it would be just a blank white page in 5.7 because the system couldn't find /web/concrete/themes/dashboard/default.php
Hopefully this can be merged in, so I can port my page management tools from 5.6 to 5.7. It doesn't really change anything major...
> Add default.php to dashboard theme

- web/concrete/blocks/google_map/view.php
I believe "Enable Scroll Wheel" option is useful when we'd like to use the full width Google Map, because it hijacks user's scrolling. However, with a mobile browser, this problem is still remaining. We should also stop dragging.
> Disable scrolling also on mobile

- web/concrete/composer.json
- web/concrete/composer.lock
See
- https://github.com/oscarotero/Gettext/releases/tag/v3.5.9
- https://github.com/mlocati/concrete5-translation-library/releases/tag/1.4.3
- https://github.com/mlocati/concrete5-translation-library/releases/tag/1.4.4
> Upgrade concrete5 Translation Library to v1.4.4

- tests/tests/Core/File/Service/ZipTest.php
- web/concrete/src/File/FileServiceProvider.php
- web/concrete/src/File/Service/Zip.php
(supersedes #3632)
I'm quite tired of writing the same code over and over again :wink:, so, what about adding a new helper to handle zip files?
```php
$zh = \Core::make('helper/zip');
// Compress a directory
$zh->zip('/directory/to/compress', 'file.zip');
// Decompress a zip file to a directory
$zh->unzip('file.zip', '/destination/directory');
```
For faster execution, this helper uses the native `zip`/`unzip` commands (if they are available), otherwise it uses the `ZipArchive` native PHP class.
This behavior can be controlled with two methods:
```php
// Never use native zip/unzip commands
$zh->disableNativeCommands();
// Re-enable native commands:
$zh->enableNativeCommands();
```
> Add ZIP helper

- .php_cs
If we run php-cs-fixer against this code:
```php
<?php
namespace X;
```
The result currently is:
```php
<?php
namespace X;
```
But it should remain untouched:
```php
<?php
namespace X;
```
> Don't add a blank line after PHP opening tag

- web/concrete/themes/elemental/elements/footer.php
I've been told that these links are negatively effecting concrete5.org's SEP :-1:
> Update footer to include `rel="nofollow"` for c5.org link

- web/concrete/blocks/rss_displayer/controller.php
- web/concrete/src/Cache/Adapter/ZendCacheDriver.php
- web/concrete/src/Cache/Cache.php
- web/concrete/src/Feed/FeedService.php
I've noticed that when using the RSS Feed block that the feed gets cached almost indefinitely, regardless of what your page/block caching settings are, this appears to be because the `FeedService` class enables an additional caching layer and there seems to be no expiry time set on the cache.
Here is my quick initial attempt at fixing it, but not fully tested as yet. Would like someone with a better core knowledge to review and provide any feedback.
Simon.
> Bugfix: RSS feeds get cached indefinitely

- web/concrete/src/Workflow/BasicWorkflow.php
- web/concrete/src/Workflow/Workflow.php
> PHP Fatal error:  Call to a member function getRequesterUserID() on null in /path/to/concrete5/web/concrete/src/Workflow/BasicWorkflow.php on line 70
1. Turn advanced permissions on.
2. Add 2 or more workflows. You have to attach "Approve or Deny" permission to you.
3. Apply these workflows to "Approve Changes" permission on a same page.
4. Edit the page and publish.
> Bug fix: multiple workflow on same page causes errors

- web/concrete/src/Entity/Attribute/Key/Type/ImageFileType.php
Fix the following install error:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'akFileManagerMode' cannot be null
```
> Fix ImageFileType constructor

- web/concrete/blocks/image_slider/form_setup_html.php
I misunderstood how the form checkbox widget worked and was using it incorrectly. This pull request fixes the checkbox use and moves the checkbox to the left of the label.
> fix incorrect checkbox use

- web/concrete/src/Cache/Adapter/ZendCacheDriver.php
Andrew recently merged my PR #3636 (thank you!), but upon closer review I think it was missing a line. (Otherwise the function parameter does nothing.)
Couldn't work out how to amend the previous PR after it was merged (is that possible?), so just submitting this small amendment.
> Bugfix: Previous PR was missing a line in ZendCacheDriver

- web/concrete/single_pages/dashboard/blocks/types/view.php
Fixing the wrong URL link where is says "More Add-ons" from Dashboard/Block/Types/index.html which is supposed to link to
/index.php/dashboard/blocks/types
> Fixing the wrong link in dashboard/blocks/types to marketetplace listing page

- web/concrete/controllers/install.php
- web/concrete/views/frontend/install.php
Install fails if the DOM extension is not loaded.
{"error":{"message":"Class 'DOMDocument' not found"},"errors":["Class 'DOMDocument' not found"]}
> DOM extension is required

- web/concrete/blocks/form/controller.php
You're not able to set Home page as redirect page of form submission.
Error message:
```
InvalidArgumentException: Cannot redirect to an empty URL.
```
> Fix: unable to redirect to home on submit form block

- web/concrete/controllers/dialog/block/design.php
- web/concrete/src/StyleCustomizer/Inline/StyleSet.php
Fix for https://www.concrete5.org/developers/bugs/5-7-5-6/applying-border-radius-requires-non-zero-border-width/#814380
> Allow setting border radius without border width

- web/concrete/src/Multilingual/Service/Detector.php
This will be used when accessing pages not under multilingual sections, like /login
> [8.0] Save to session the locale of the page being visited

- tests/tests/Core/File/ImporterTest.php
- web/concrete/config/concrete.php
- web/concrete/config/db.xml
- web/concrete/src/Application/Application.php
- web/concrete/src/File/Image/Thumbnail/Path/Resolver.php
- web/concrete/src/File/Image/Thumbnail/Type/Version.php
- web/concrete/src/File/StorageLocation/Configuration/DeferredConfigurationInterface.php
- web/concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php
- web/concrete/src/File/Version.php
- web/concrete/src/Updater/Migrations/Migrations/Version20160412000000.php
Resolves #3590
Some interesting tidbits:
* To avoid caching the base url of the site, we added an interface that is used as a flag. Any storage location that wants to cache the "file path" instead of the public url should implement this interface.
* To clear this table, you must clear site cache. There is talk of moving this to storage locations interface.
To get the path for a file version:
```php
<?php
$path_resolver = $app->make('Concrete\Core\File\Image\Thumbnail\Path\Resolver');
$path = $path_resolver->getPath($file_version, $thumbnail_type_version);
```
> Cache file thumbnail paths

- web/concrete/src/Application/Application.php
If a package, in its `on_start method`, calls `t()`, the localization files are loaded and cached.
Once these localization files are loaded, translations of subsequent packages are not loaded anymore since the translation cache is already built.
So, let's first initialize the localization of all the packages, and only after let's call the packages `on_start` methods.
> Fix package localization

- web/concrete/blocks/feature/controller.php
- web/concrete/blocks/feature/form.php
I was noticing that when a Feature block linked to a document using the file manager, it would continually append the cID on every block save.
Edit the block.
Then click save, click edit the block again, click save, do this several times and the URL grows.
I looked through the Content block controller because that block wasn't suffering the same bug and realized that it contained a method called getContentEditMode() so I duplicated this functionality for the Feature block.
I tested this on both Linux and OSX using apache 2.2, php 5.5, and php 5.6. 
Thanks,
Jared
> fix: feature block wasn't pulling paragraph correctly in editmode

- web/concrete/src/Localization/Service/StatesProvincesList.php
Quite unbelievably: this typo has been there since [2009-09-08](https://github.com/concrete5/concrete5-legacy/commit/ec45c6bbcfa3ae6ea8062fb54cd2ef7bc89e6fa4#diff-4e657b13dc28140874bf76211deff574R231) :wink:
> Fix Brazilian state name Tocatins -> Tocantins

- web/concrete/authentication/concrete/change_password.php
Currently no error messages are displayed when attempting to change passwords. This fixes that with the exact same code used in /concrete/themes/dashboard/view.php
> Display error messages on Concrete password change

- web/concrete/src/Asset/CssLocalizedAsset.php
- web/concrete/src/Asset/JavascriptLocalizedAsset.php
Bug tracker: https://www.concrete5.org/developers/bugs/5-7-5-6/javascriptlocalizedasset-loads-asset-with-base_url-resulting-in-/
> Remove protocol and domain from localized asset URLs

- web/concrete/bootstrap/start.php
https://www.concrete5.org/developers/bugs/5-7-5-6/setup-of-security.trustedproxies.ips-done-too-late-in-concretebo/
> The position of setting trusted proxies is too late

- web/concrete/config/concrete.php
- web/concrete/controllers/panel/page/check_in.php
- web/concrete/views/panels/page/check_in.php
If the new configuration option `concrete.misc.require_version_comments` is set to true, version comments are required
> Add configuration option to require version comments

- web/concrete/src/Page/Type/Type.php
When working with adding page types programmatically for packages, it would be much easier to be able to pass a list of page template handles instead of the full object. This pull request would allow for either the objects (as is done currently), or the list of handles.
> Allow the passing of Page Template handles for Page Type adding/updating

- web/concrete/blocks/autonav/controller.php
The `getNavigationArray` method is responsible for populating the array of navigation items. Later, in `getNavItems` method, the controller goes through each navigation item and excludes the pages based on certain conditions. This approach is not good as it fetches all the pages and for each page separate database queries are made (i.e for fetching page object using `Page::getByID`). Hence, there is a possibility that the menu on front end displays only 10 items, but in the back end more than 2000 queries are being made just for that instance of Auto-Nav block. For e.g., there is a page called Projects under Home which is set to exclude all the sub-pages from nav having 2000 pages under it of page type Project.
This commit adds additional checks in the beginning of `getNavigationArray` to …
> Updated Auto-Nav block controller to minimize database queries

- web/concrete/blocks/video/view.php
Video closing tag was placed outside if.
> Don't print closing video tag when there is no video selected

- web/concrete/src/User/User.php
Due to LSB and some extremely bizarre PHP behavior, `\User::loginByUserID()` previously did not work from within a class method.
To replicate open up /application/bootstrap/app.php and replace the contents with:
```php
<?php
class Foo {
public function bar() {
\Concrete\Core\User\User::loginByUserID(1);
}
}
$f = new Foo;
$f->bar();
```
The error you see will make you very confused. This pull requests resolves that issue and makes this behave in a sane way.
> Fix: Resolve BIZARRE issue with using ::loginByUserID() from within a class method

- web/concrete/controllers/dialog/file/advanced_search.php
- web/concrete/src/Tree/Node/Type/SearchPreset.php
This PR fixes this problem (that prevents installing on PHP 7):
```
Declaration of
Concrete\Core\Tree\Node\Type\SearchPreset::add()
should be compatible with
Concrete\Core\Tree\Node\Node::add($parent = false)
```
> Fix Tree\Node\Type\SearchPreset::add should be compatible with Tree\Node\Node::add

- web/concrete/blocks/page_title/controller.php
- web/concrete/blocks/page_title/db.xml
- web/concrete/blocks/page_title/form_add_edit.php
- web/concrete/blocks/page_title/view.php
- web/concrete/blocks/tags/controller.php
This pull request adds topic, tag, and date "filtering" to the Page Title block. Allowing the text of the Page Title block to be updated to reflect the current topic, tag, or date. It includes basic text case formatting of default (no formatting change), capitalize the first letter of each word, lowercase, and uppercase.
**Topic text formatting:**
- Default (no formatting change)
- Capitalize the first letter of each word
- Lowercase
- Uppercase
**Tag text formatting:**
- Capitalize the first letter of each word
- Lowercase
- Uppercase   
_Tag text has no default formatting_
**Date text formatting:**
- Default (no formatting change)
- Capitalize the first letter of each word
- Lowercase
- Uppercase
**Examples of text used to test:**
サンドイッチポテト
Сэндвич Картофеля
תפוח אדמה כריך
土豆三明治 …
> Add topic, tag, and date filtering to the Page Title block

- tests/tests/Core/Express/ObjectAssociationBuilderTest.php
- tests/tests/Core/Statistics/UsageTracker/AggregateTrackerTest.php
- tests/tests/Core/Statistics/UsageTracker/ServiceProviderTest.php
- web/concrete/blocks/core_stack_display/controller.php
- web/concrete/config/app.php
- web/concrete/config/statistics.php
- web/concrete/controllers/single_page/dashboard/blocks/stacks.php
- web/concrete/single_pages/dashboard/blocks/stacks/view.php
- web/concrete/src/Block/Block.php
- web/concrete/src/Block/BlockType/BlockType.php
- web/concrete/src/Entity/Statistics/UsageTracker/StackUsageRecord.php
- web/concrete/src/Page/Stack/UsageTracker.php
- web/concrete/src/Statistics/UsageTracker/AggregateTracker.php
- web/concrete/src/Statistics/UsageTracker/ServiceProvider.php
- web/concrete/src/Statistics/UsageTracker/TrackableInterface.php
- web/concrete/src/Statistics/UsageTracker/TrackerInterface.php
- web/concrete/src/Statistics/UsageTracker/TrackerManagerInterface.php
- web/concrete/views/dialogs/stack/usage.php
This is an complete example of the Statistics/UsageTracker as discussed in #3240. 
5ffae98 is the core `\Concrete\Statistics\UsageTracker` package
84ee3a8 is a convenience method I added so that I wouldn't have to access `$controller->stID`
8d94dbe is a Tracker that tracks stacks given a trackable core stack view block controller or a page or a page controller
> An implementation of the tracker service and a stack tracker

- web/concrete/composer.json
- web/concrete/composer.lock
Some localization-related stuff still remained at old versions (https://github.com/concrete5/concrete5/pull/3567 seems to have been lost).
I just run `composer require mlocati/concrete5-translation-library:1.4.5`, but composer updated also other stuff:
- `illuminate/contracts` from 5.2.7 to 5.2.31 (I don't see any breaking change... The differences are the first 6 commits [here](https://github.com/illuminate/contracts/commits/v5.2.31))
- `symfony/console` from 3.0.2 to 3.0.6 (I don't see any breaking change [here](https://github.com/symfony/console/compare/v3.0.2...v3.0.6)).
- `symfony/debug` from 3.0.2 to 3.0.6 (I don't see any breaking change [here](https://github.com/symfony/debug/compare/v3.0.2...v3.0.6)).
- `symfony/polyfill-mbstring` from 1.1.0 to 1.1.1 (they are exactly the same: …
> Update localization stuff... and other composer packages

- web/concrete/blocks/form/controller.php
(concerning jozzeh-patch-2)
When a form is submitted an error would occur (Events class not found).
This patch fixes that error and it also uses the new Events dispatch method instead of the old fire method. **Fully tested**
Added Events class at top of the file
+
Changed deprecated event fire method to current dispatch method
This is a bugfix and should be merged asap.
> Bugfix : error on form submission (events class not found)

- web/concrete/elements/attribute/key/list.php
We are not adding an attribute type, so it's better to split `Add Attribute Type` into `Add Attribute` and `Type`:
Before:
After:
> Better text when adding a new attribute to a data object

- web/concrete/elements/dashboard/express/detail_navigation.php
`View %s Entries` may mean two different things (so it can have two different translations):
1. `View X entries` where X is a number
2. `View entries of X` where X is a container
So, let's use a translation context to be sure that this translatable string won't clash with other translatable strings.
> Better translatable text for 'View %s Entries'

- web/concrete/src/Page/Stack/Stack.php
It's called statically and it does not contain any reference to `$this`
> Make Stack::getMultilingualSectionFromType static

- web/concrete/elements/page_controls_footer.php
- Give translators a hint about what `%1$s` and `%2$s` are in `published on %1$s at %2$s`
- Fix a couple of html errors (an unclosed `<div>` and a misplaced `>`)
- Use `$app->make` instead of `Core::make`
- Use `$app->make('config')` instead of `Config::`
- Simplify the logic (avoid useless nested `if`s, define variables only if they are used)
- Remove unused variables
- Avoid calling duplicated `$app->make` calls
> Fix page_controls_footer.php

- web/concrete/elements/permission/duration.php
The text `On` is translatable in two places:
- [here](https://github.com/concrete5/concrete5/blob/426b1f409e4dad3ce6e53e898d1713ec7f3e3f4b/web/concrete/elements/permission/duration.php#L378) it's used as a prefix for dates
- [here](https://github.com/concrete5/concrete5/blob/426b1f409e4dad3ce6e53e898d1713ec7f3e3f4b/web/concrete/single_pages/dashboard/system/registration/open.php#L35) it's used to set a value of an option (as in `On`/`Off`)
Since they have a totally different meaning, we need to distinguish them with a translation context, so that they can have different translations.
> Add translation context to 'On' used for dates

- web/concrete/views/image-editor/controls/position.php
If input alphabet on width, it's going to be "NaN" value. It looks bad for about UX view.
> Prevent input non-numeric character on width, height input

- web/concrete/src/Page/Collection/Version/Version.php
Some tiny performance improvements, achieved by:
- Avoid deprecated methods
- Defining all the instance methods
- Removing an `accessing an undefined array index` warning loading the collection version
> Collection Version fixes

- tests/tests/Core/Statistics/UsageTracker/ServiceProviderTest.php
- web/concrete/src/Statistics/UsageTracker/ServiceProvider.php
This provides a mock repository object in order to allow the tests to complete.
> Fix: Provide config mock for usage tracker test

- tests/tests/Core/Statistics/UsageTracker/ServiceProviderTest.php
See #3779 
We can isolate this a little further by using a mock object or a fixture for the repository object. Probably doesn't matter at all for now.
> Update usage statistics tracker to make sure that config trackers work

- web/concrete/src/Page/Collection/Version/Version.php
I really don't know what this method is meant to do... I can't find any call to this method in the core, and the cvCanWrite field is never set...
> Remove useless CollectionVersion::canWrite

- tests/README.md
Close #3785 
I also removed the step about `Install concrete5` since tests don't require that concrete5 is installed.
> Fix the tests readme

- web/concrete/elements/dashboard/welcome.php
Showing the changes in the Italian welcome page:
- before:  
- after:
> Translate nav menu in welcome page

- web/concrete/src/Database/EntityManagerConfigFactory.php
- web/concrete/src/Package/Package.php
- web/concrete/src/Package/PackageService.php
Additional package namespaces are now registered automatically into the driver chain. Now the c5 migration tool works.
There are still two open questions. 
1. `$pkgAutoloaderMapCoreExtensions` is set in the migration tool to `true`. If I handle the mapping information the same as the ClassLoader does, say `Concrete\\Package\\MigrationTool` maps to `/packages/migration_tool/src/Concrete` the package isn't installed properly. Are there other packages out there, which use `$pkgAutoloaderMapCoreExtensions=true`?
2. The mapping paths are stored as absolute paths in `config/database.php`. This can generate problem if the web page is moved. Shall I change the absolute paths to relative paths? (If so, every mapping path has to be prepended during bootstrap.) Any preferences?
> v8: Fix - Add additional package namespaces to the driver chain.

- web/concrete/blocks/autonav/controller.php
Children where still excluded when using `$ignore_exclude_nav`.  
In a page template we now also can set the option to ingnore exluded nav items. There is no need to adjust the autonav template.  
```
$nav = BlockType::getByHandle('autonav');  
$nav->controller->ingnoreExludeNav = true;
```
> fix for ignore excluded nav items still being excluded.

- web/concrete/src/Editor/CkeditorEditor.php
I think originally this was put in to get rid of the grey colors from the ckeditor theme because they didn't mesh well with concrete5. However, it seems to have had a very bad side effect of completely removing the styling from icons when they are "on".
Before Change:
After Change:
> can't set uicolor without messing up editor theme

- web/concrete/blocks/page_attribute_display/controller.php
I just wanted to throw a small idea.
This is very minor suggestion to add nl2br to Page Displayer Block when displaying the collection description.
I kinda wanted to support nl2br to text area attribute. But if it's Rich Text, it should not add the line break to it. So I hold on to it.
At first, I would like to open a discussion if anyone is interested in embracing my idea.
Thanks.
> Suggestion to support line break to Page Attribute Display

- web/concrete/src/Search/Pagination/View/ViewRenderer.php
Legacy URL helper uses raw `$_SERVER` global variables. It is not best for url manipulation.
Let's replace it with league URL component.
> Avoid to use url helper on pagination view renderer

- web/concrete/src/Package/Package.php
If `$pkgAutoloaderMapCoreExtensions = true` add additional source path to the package default namespace. This is the last open issue according to my knowledge. 
I'll provide some UnitTest in the next few days, and make a pull request to develop.
> v8: Fix - missing support for packages with pkgAutoloaderMapCoreExtensions = true

- web/concrete/src/Cache/Page/FilePageCache.php
- web/concrete/src/Cache/Page/PageCache.php
In the core use statements are mixed (full namespace and alias). This can give problems when instance of is checked. We would like to know what the advice approach is. Using the full namespace gives us some advantages in our IDE.
```
use Concrete\Core\Page\Page;
use \Page;
```
We use `Concrete\Core\Page\Page` . When making a copy of a page we get the following error. 
```
Argument 1 passed to Concrete\Core\Cache\Page\FilePageCache::purge() must be an instance of Page, instance of Concrete\Core\Page\Page given
```
> use full namespace

- concrete/blocks/html/add.php
- concrete/blocks/html/composer.php
- concrete/blocks/html/edit.php
- concrete/blocks/html/form_setup_html.php
- concrete/blocks/html/scrapbook.php
- concrete/blocks/html/view.php
- Use h helper instead of htmlspecialchars, **please confirm this is ok**
- bID is always an integer, no need for intval
- Use form helper for labels
- Remove unnecessary vars like $controllerObj
- PSR fixer
I've tested the block with composer and the layout remains the same.
> Cleanup html block

- build/tasks/build-release/download.js
Running `cd build & grunt build-release-download` results in an extracted folders readable only by root.
Let's fix this
> [grunt-build-release] Fix permissions extracting downloaded ZIP

- build/tasks/build-release/build.js
- composer.json
This was already so in core releases, let's do the same in every case
> Prefer Composer dist packages instead of source ones

- concrete/blocks/next_previous/form_setup_html.php
See commit messages.
If it's OK I'd gladly add to this PR:
- Placeholders should start with capital letter: "Leave blank to hide".
- Remove the dot after "Exclude system pages.". But this would affect translations.
> Cleanup next_previous edit dialog

- build/tasks/build-release/download.js
The Download NPM package is able to extract downloaded archives, but it has some problems regarding file permissions and empty directories.
So, let's use the system `unzip` command
> Use system unzip to extract release archive

- concrete/blocks/html/composer.php
It's about that blue line underneath and the additional padding add margin.
Before:
After:
> Fix html block layout in composer

- concrete/controllers/single_page/dashboard/users/points/assign.php
Prevents an SQL error if an action doesn't exist (anymore).
> Check if action exists before assigning points

- concrete/src/Permission/Access/Entity/UserEntity.php
This is a very tiny fix that fixes a typo which produced invalid HTML.
> Remove duplicate quote in UserEntity HTML render

- concrete/blocks/next_previous/add.php
- concrete/blocks/next_previous/controller.php
- concrete/blocks/next_previous/edit.php
- concrete/blocks/next_previous/form_setup_html.php
- concrete/blocks/next_previous/view.php
Commit:
- Overall cleanup en PSR
- Remove empty getJavaScriptStrings method
- Move default values from add.php to controller add method
- Move logic from view to controller
- Remove showArrows (save) because it's not used
- get[Next|Previous)Collection should only return Page or false
Notes:
1. Controller still uses Facade, because if the block is set up via page types, $this->app currently returns null.
2. It's possible to use HTML in the label fields. Do we want to use h() in the view.php or do we want to keep it as it stands?
3. The methods getNextCollection and getPreviousCollection should probably be merged some day.
> Cleanup next_previous controller

- concrete/src/Http/ResponseAssetGroup.php
This should fix bug https://www.concrete5.org/developers/bugs/5-7-5-8/file-manager-edit-image-doesnt-work-when-jscss-cache-is-on-becau/
> Avoid adding duplicated assets to output

- web/concrete/src/Session/SessionFactory.php
Adds cookie_lifetime option to the session storage, this allows us to retrieve the time remaining on the currently active session when a limit is set.
> Cookie lifetime for session

- concrete/controllers/single_page/dashboard/system/seo/codes.php
- concrete/elements/footer_required.php
- concrete/elements/header_required.php
- concrete/single_pages/dashboard/system/seo/codes.php
- concrete/src/Updater/Migrations/Migrations/Version20160420000000.php
https://github.com/concrete5/concrete5/issues/3711
> add separate header and footer tracking code inputs

- concrete/blocks/image/add.php
- concrete/blocks/image/composer.php
- concrete/blocks/image/controller.php
- concrete/blocks/image/edit.php
- concrete/blocks/image/form.php
- concrete/blocks/image/view.php
See commit messages for details.
Two things:
1. The Error class is deprecated, what should be used instead?
2. The hover state doesn't work. This is not because of this PR, but because of PictureFill. I've tested the image hover in the develop branch, it had the same problem.
I've tested all the fields, including setting it up via composer. I may have made a mistake, so please review before merge. Hopefully this PR eventually gets through though, because the image block is often copied and modified.
> Cleanup image block

- concrete/src/Html/Object/Picture.php
The source element when used with the picture element does not support class, title, and alt attributes.
https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element
**Current**
```
<picture>
<source srcset="http://localhost/concrete5_sandbox/application/files/thumbnails/large/5514/6430/4370/sunset.jpg" media="(min-width: 900px)" class="ccm-image-block img-responsive bID-168" alt="hot crossed buns" title="milk toast">
<source srcset="http://localhost/concrete5_sandbox/application/files/thumbnails/medium/5514/6430/4370/sunset.jpg" media="(min-width: 768px)" class="ccm-image-block img-responsive bID-168" alt="hot crossed buns" title="milk toast">
<source srcset="http://localhost/concrete5_sandbox/application/files/thumbnails/small/5514/6430/4370/sunset.jpg" …
```
> remove unsupported attributes from source

- concrete/bin/concrete5.php
- concrete/bootstrap/configure.php
- concrete/bootstrap/paths.php
With version 5.7, [`concrete/bootstrap/paths.php`](https://github.com/concrete5/concrete5/blob/5.7.5.8/web/concrete/bootstrap/paths.php) was directly included by [`concrete/bootstrap/start.php`](https://github.com/concrete5/concrete5/blob/5.7.5.8/web/concrete/bootstrap/start.php#L39), which was directly included by [`concrete/dispatcher.php`](https://github.com/concrete5/concrete5/blob/5.7.5.8/web/concrete/dispatcher.php#L36), which was directly included by [`index.php`](https://github.com/concrete5/concrete5/blob/5.7.5.8/web/index.php#L2).
That means that before `concrete/bootstrap/paths.php` could access the global variables directly (since that file was included directly and not from functions).
concrete5 version 8 introduced the runtime booters and runners, and now …
> Fix working with updated core versions

- web/concrete/elements/header_required.php
This will cleanup the header_required.php file. Changes:
- Code has been shortened;
- Code will be used consistent, instead of sometimes outputting straight JavaScript and in between echo'ing JavaScript in PHP;
- Variables have been removed, if they hadn't got to be in a variable but could be used straight away;
- Grouped meta tags into an array;
- Grouped shortcut links in an array;
- Description (meta) will only show when not empty (after trimming);
- Removed deprecated code (Loader::helper('concrete/ui'));
After this cleanup, we can think of firing an event or something, for Add-Ons to be able to add/edit some meta tags. For now, this cleanup only has parts it already had, but organized, clean, no deprecated code and will make it easier to add something in for Add-Ons at a later stage …
> header_required cleanup

- concrete/src/Marketplace/Marketplace.php
When installing ExchangeCore Dev Tools on 8.0.0a5, I got:
Fatal error: Undefined class constant 'E_PACKAGE_INVALID_APP_VERSION'
E_PACKAGE_INVALID_APP_VERSION is a member of \Package, not Concrete\Core\Support\Facade\Package (Concrete\Core\Package\PackageService)
> Marketplace.php - undefined constant

- concrete/src/StyleCustomizer/Preset.php
The theme customizer in the develop branch is currently broken due to https://github.com/oyejorge/less.php/pull/324.
However the wrapper class added in https://github.com/concrete5/concrete5/pull/3825 by @KorvinSzanto offers a workaround.
> Use TreeCallColor wrapper in StyleCustomizer Preset

- concrete/src/Localization/Service/StatesProvincesList.php
This option would never be used as a billing or shipping address and shouldn't be included in the list of states and territories of Australia. (Antartica is listed as a country option anyway).
> Removal of Australian Antarctic Territory from list of Australian States

- concrete/elements/conversation/display.php
The conversation form is retrieved with AJAX and that request seems to not "honor" the language of the page that the block is on, but rather uses the default language.
> Add multilingual support to Conversation block form

- web/concrete/blocks/autonav/controller.php
Fix the autonav bug which breaks breadcrumbs in the 5.7 branch.
Backport of #3769.
> Fix autonav exclude

- concrete/blocks/page_title/view.php
Wrong output before:
`<h1>Title<h1>`
Correct After:
`<h1>Title</h1>`
This **tiny** issue could break the whole design of the site (Convert other element to h1).
> Tiny issue: Add missing  "/" in $title end tag

- web/concrete/src/Page/View/PageView.php
When using theme customizations on a concrete5 site I noticed an increased load time. After some investigation it seems that with theme customizations the CSS cache is actually not used.
The problem was introduced with this commit: https://github.com/concrete5/concrete5/commit/6bd27450c552c642b12ba68e9d3a206ce64527be#diff-7a93e2465b45c5883e9e24fa04035a3f
I'm not entirely sure which bug exactly this is supposed to fix, but it effectively disables all caching for pages with theme customizations. Before it would only use the "handler script" for previewing unapproved changes, after the "handler script" is used as soon as there are theme customizations.
I think the call `$this->cp->canViewPageVersions()` was removed by accident.
> Fix theme customizations caching

- web/concrete/blocks/share_this_page/view.php
The default view of the Share This Page block creates empty hyperlinks (they contain only the Bootstrap ```<i></i>``` elements that display the service icons). In order to make WCAG AA happy, hyperlinks need to have some kind of text content. I opted to add aria-label attributes to each anchor tag and popular the attribute with the getDisplayName() service call. This results in markup like this:
```
<li>
<a href="https://www.facebook.com/sharer/sharer.php?u=path/to/page" aria-label="Facebook"><i class="fa fa-facebook"></i></a>
</li>
```
> Add WCAG label to Share This Page default view

- concrete/blocks/share_this_page/view.php
The default view of the Share This Page block creates empty hyperlinks (they contain only the Bootstrap `<i></i>` elements that display the service icons). In order to make WCAG AA happy, hyperlinks need to have some kind of text content. I opted to add aria-label attributes to each anchor tag and popular the attribute with the getDisplayName() service call. This results in markup like this:
```
<li>
<a href="https://www.facebook.com/sharer/sharer.php?u=path/to/page" aria-label="Facebook"><i class="fa fa-facebook"></i></a>
</li>
```
> Same accessibility fix as the one merged into 5.7.x

- concrete/src/Page/Theme/Theme.php
CSS files are currently cached on two sides; both by Concrete5 and by the client's browser. That's very effective, but when something changes in such a file, both caches need to be invalidated.
Concrete5's cache appears to function just fine, but when a CSS file in a theme is edited, the browser still retains its old version for a while. By adding the last-modified date, the browser is informed that the current version is outdated.
This is particularly relevant for CSS files that are the result of compiled LESS files, which greatly benefit from aggressive caching.
> Invalidate browser cache when CSS files are edited

- concrete/authentication/google/type_form.php
The regex example in this file was off, instead of `~^concrete5\.org$i~` it should be something that works like `~^concrete5\.org$~i`.
> Update google type form to have correct regex

- concrete/blocks/tags/controller.php
- concrete/blocks/tags/view.php
Proposed fix for #3992.
Replaces `OptionList` with an `array`. Also added required `getSelectedOptions()` call for the page attribute.
> Fix attribute option list in Tags block

- concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Fix for #3869.
Same as in the [Application facade]( https://github.com/concrete5/concrete5/blob/develop/concrete/src/Support/Facade/Application.php#L25).
Assuming it's not wise to call `\Core::getApplicationURL()` here as that would use the static facade app instead of `$this->app`.
Shouldn't this actually be `$app->make('url/canonical')` (parameter) instead of `$this->app->make('url/canonical')` (protected field)?
> Use rtrim for BASE_URL

- concrete/src/Application/Application.php
By denying any requests with two periods we prevent potential path traversal on some systems completely. Is there ever a case where a valid concrete5 URL has a ".." in it's path?
Another option that will have the same effect is replacing ".." with "", but that would duplicate content for example "/blogs" will be accessible from "/..blo..gs.." or "/b..l..o........g..s"
> Protect against path traversal more thoroughly

- concrete/src/Application/Application.php
Change to check for `false` to raise exception when first two
characters are '..'.
> Fix Exception on '../'

- concrete/config/concrete.php
Japanese users and I was also wondering why the page title order default has been
SITE NAME :: PAGE NAME
I would like to propose to switch to PAGE NAME :: SITE NAME order by default.
By changing the /concrete/config/concrete.php
Request from Japanese users
http://concrete5-japan.org/community/forums/feature-requests/post-13251/
They want to comply the site to meet WCAG standard
https://www.w3.org/TR/WCAG20-TECHS/G88.html
https://www.w3.org/WAI/WCAG20/quickref/#qr-navigation-mechanisms-title
Thanks.
> Switch Site name and page title on default

- concrete/src/Application/Application.php
- concrete/src/Job/Set.php
In the application shutdown we retrieve scheduled jobs.
We also retrieve job sets, but they're not filtered on whether they're scheduled or not.
This PR also gives a slight performance advantage because shutdown is basically called in each request.
> Add parameter to only retrieve scheduled job sets

- concrete/views/panels/details/page/permissions/advanced.php
When I was testing the advanced page permission, I realized that I was getting non-object error, and found out about shorttag leftover on the line 7.
I just ran PHP CS Fixer for the file to fix the entire file.
> Shorttag Left-over on Advanced Permission Page Panels

- concrete/src/File/Type/Type.php
Calling a non-static method from a static method is conceptually wrong and throws an `E_DEPRECATED` warning: let's do the vice-versa.
> Get generic type text: call static method from non-static, not the vice-versa

- concrete/src/Multilingual/Service/UserInterface/Flag.php
Sitemap dashboard page is broken for me when I have multilingual sections.
That's because `Flag::getSectionFlagIcon` calls `Section::getBySectionOfSite` with a collection ID and not with a `Page` instance.
Furthermore, `Flag::getSectionFlagIcon` and `Flag::getFlagIcon` are called statically, but they are defined as not static: let's set them as static.
> Fix multilingual sitemap

- concrete/elements/navigation/menu.php
$c maybe not defined (I found some "Undefined variable: c" warnings in my logs).
Furthermore $walk accepts only one parameter, the $view is just *use*d
> Avoid accessing undefined (and unused) variable in menu navigation element

- concrete/src/Multilingual/Page/Section/Section.php
I've seen that sometimes `Section::getByLocale` is called with an empty $locale, and this throws a warning. Let's avoid those warnings.
> Avoid looking for multilingual section if $locale is empty

- concrete/single_pages/dashboard/blocks/stacks/view.php
Fixes #3708.
Removed the duplicate call to `new Concrete.EditMode()` and replaced with calls to `Concrete.getEditMode()`.
> Fix stacks duplicate edit mode

- concrete/controllers/single_page/dashboard/system/seo/urls.php
Fixed typo (unsecognized -> unrecognized) that was causing the .htaccess file contents not to be shown on a server whose type could not be determined.
> Fix typo when setting pretty URLs

- concrete/src/Page/View/PageView.php
Fixes #4010.
Removes the `isActive()` check when setting the previous frontend page. 
This doesn't appear to break anything else, but does also seem to fix #4014.
> Allow returning to a draft

- concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
- tests/tests/bootstrap.php
When concrete5 is installed, the core determines the value of the legacy constant `BASE_URL`.
Since that happens before the tests bootstrap, the connection is used is the one relative to the installed instance.
That implies that the default connection is already defined before the `/tests/tests/bootstrap.php` file defines the default connection, breaking many tests.
So, let's manually define `BASE_URL` when running tests.
> Fix tests for installed concrete5 instances

- concrete/blocks/image_slider/view.php
Image_slider block Disable in edit mode - so i added more **"Visual"** "edit mode" - "i am a slider" design (Better UI).
- Like "**wireframe**" design of slider (image icon and dots). 
- Also in this code you can know **"how much"** sliders you have also in edit mode (In the image below - 4 sliders = 4 dots - the first is "active"). Mabye this code - array_slice (i want to start from the second item of the array) - cause "travis CI" error - i dont know about "travis" so well.
> Add font-aswome icons to slider in "edit mode"

- concrete/blocks/image_slider/form_setup_html.php
The extra form group wrapping the radio buttons added an extra fieldless form line.
> remove extra form group from the Image Slider form

- concrete/css/build/core/app/forms.less
This pull request matches the radio button background color with the checkbox background color.
**Current**
**Changes**
> radio button background color

- concrete/attributes/select/form.php
- concrete/elements/page_types/form/base.php
- concrete/js/build/core/app/search/base.js
- concrete/single_pages/dashboard/reports/logs.php
Currently items selected with Selectize cannot be removed with a mouse or by touch. This pull request enables the "remove_button" Selectize plugin, which allows for items to be removed by mouse and touch and provides a visual indicator that a selection can be removed.
The "remove_button" plugin appears to behave like Select2 does in 5.7.
**Example: Select2 in 5.7**
**Current**
**Changes**
**Current**
**Changes**
**Current**
**Changes**
**Current**
**Changes**
> add remove button to Selectize selections

- web/concrete/controllers/search/users.php
The permission key object was missing in the users search controller causing filtering by a Group Set to fail.
> Fix missing permission key

- tests/tests/CodingStyle/NoShortTagsTest.php
- tests/tests/CodingStyleTestCase.php
Let's add a test to verify that all the PHP files (except the ones under `/concrete/vendor`) don't have PHP short open tags (`<?`).
> Add test to verify short PHP tags

- concrete/src/Page/Type/Composer/Control/Control.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/DateTimeCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/DescriptionCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/PageTemplateCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/PublishTargetCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UrlSlugCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UserCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/Type/CollectionAttributeType.php
- concrete/tools/page_types/composer/form/add_control.php
Fixes #4151.
Adds the ability to specify a FontAwesome icon formatter instead of an image src and selects the right one to render - block types are using image icons so both are still needed.
Gets the correct icon from the type of custom attributes, and replaces the image srcs for core properties with the appropriate icons for the type.
> Fix form control icons

- concrete/src/User/Group/GroupSearchColumnSet.php
If you use hierarchical Group path, Group#getGroupDisplayName may includes span element, so we should avoid it in `data-group-name` attribute value.
> Do not include html on ajax group search

- concrete/blocks/date_navigation/controller.php
Bug report: https://www.concrete5.org/developers/bugs/5-7-5-8/mysql-5.7.5-sql-mode-only_full_group_by-causing-blog-to-fail-c57/
> Fix DateNavigation controller when ONLY_FULL_GROUP_BY enabled in MySQL

- tests/tests/CodingStyleTestCase.php
This change is needed because of https://github.com/concrete5/concrete5/commit/7dddbc5512218c21e012589f108bca62bbe68a48
> Fix skipping of vendor files analysis

- web/concrete/controllers/single_page/dashboard/pages/themes.php
- web/concrete/controllers/single_page/dashboard/system/attributes/types.php
- web/concrete/controllers/single_page/dashboard/system/basics/accessibility.php
- web/concrete/controllers/single_page/dashboard/system/conversations/points.php
- web/concrete/controllers/single_page/dashboard/system/optimization/jobs.php
- web/concrete/controllers/single_page/dashboard/system/seo/bulk.php
- web/concrete/single_pages/dashboard/pages/themes/view.php
- web/concrete/single_pages/dashboard/system/attributes/types.php
- web/concrete/single_pages/dashboard/system/basics/accessibility.php
- web/concrete/single_pages/dashboard/system/conversations/points.php
- web/concrete/single_pages/dashboard/system/optimization/jobs.php
- web/concrete/single_pages/dashboard/system/seo/bulk.php
- web/concrete/tools/files/permissions.php
A bunch of separate CSRF additions. I'll work on opening a PR for v8 too.
> Various CSRF fixes

- concrete/blocks/youtube/view.php
The variable for the loop setting in the controller is $loopEnd (instead of $loop).
> loop Setting not working in youtube block

- tests/tests/Core/Statistics/UsageTracker/AggregateTrackerTest.php
- tests/tests/Core/Statistics/UsageTracker/ServiceProviderTest.php
- tests/tests/Core/Url/Resolver/CanonicalUrlResolverTest.php
- tests/tests/Core/Url/Resolver/Manager/ResolverManagerTest.php
- tests/tests/Core/Url/Resolver/PageUrlResolverTest.php
- tests/tests/Core/Validator/ValidatorManagerTest.php
- tests/tests/CreateClassMockTrait.php
Newer versions of PHPUnit raise these warnings when calling `getMock`:
```
PHPUnit_Framework_TestCase::getMock() is deprecated,
use PHPUnit_Framework_TestCase::createMock()
or PHPUnit_Framework_TestCase::getMockBuilder() instead
```
Since the PHPUnit version that supports PHP 5.5 does not implements the ` PHPUnit_Framework_TestCase::createMock()` method, let's introduce a trait that calls `getMock` for older PHPUnit versions and `createMock` for newer versions.
> Fix phpunit warnings about mocks

- concrete/elements/conversation/message.php
- concrete/elements/gathering/templates/detail/image_conversation/view.php
- concrete/elements/gathering/templates/tile/tweet/view.php
- concrete/src/Gathering/Item/Twitter.php
- concrete/src/Sharing/ShareThisPage/Service.php
- concrete/src/Utility/Service/Text.php
I was installing the `share_this_page` block on a page when I noticed that Twitter links were not formatted correctly. It was using the `www.` version of the domain.
I had a look at the source code of the block but didn't find the link. I did a full-text search on my Concrete5 install and found the link along with other incorrect links in the core code.
I fixed each of them to use the Apex version along with the HTTPS protocol.
I also found a link to `search.twitter.com`. A quick try <https://search.twitter.com/search?q=%23laravel> told me it was no longer active. I migrated it to the new syntax (and HTTPS): <https://dev.twitter.com/rest/public/search>. Another link was using an incorrect syntax of the same search API.
Except for the `search.twitter.com` case, nothing is critical. Twitter …
> Fix Twitter links

- concrete/src/Attribute/Category/ExpressCategory.php
Fix for this error:
```
Declaration of
Concrete\Core\Attribute\Category\ExpressCategory::import(
Concrete\Core\Entity\Attribute\Type $type,
SimpleXMLElement $element,
Concrete\Core\Package\Package $package = NULL
)
should be compatible with
Concrete\Core\Attribute\Category\AbstractCategory::import(
Concrete\Core\Entity\Attribute\Type $type,
SimpleXMLElement $element,
Concrete\Core\Entity\Package $package = NULL
)
```
I start hating this class ambiguity... :unamused:
> Fix ExpressCategory attribute -> import

- concrete/src/Config/Repository/Repository.php
- concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php
- concrete/src/Url/Resolver/CanonicalUrlResolver.php
- concrete/src/Url/Url.php
- concrete/src/Url/UrlImmutable.php
- tests/config/concrete.php
- tests/tests/Core/Routing/URLTest.php
- tests/tests/Core/Url/Resolver/CallableUrlResolverTest.php
- tests/tests/Core/Url/Resolver/PageUrlResolverTest.php
- tests/tests/Core/Url/Resolver/PathUrlResolverTest.php
- tests/tests/Core/Url/Resolver/ResolverTestCase.php
- tests/tests/Core/Url/Resolver/RouteUrlResolverTest.php
If `concrete.seo.canonical_url` is not set, we'll now output the relative url when someone requests the canonical url.
> Relative urls when canonical url is not set

- concrete/single_pages/dashboard/system/conversations/settings.php
The note text size was 11px and challenging to read. The "small" class was removed.
**Current**
**Changes**
> increase Conversation Settings note text size

- README.md
This adds a counter for items ready to start in the issue list. Clicking on it takes you to the things that are ready to be worked on in the issues list
> Add a counter and a link to issues that are ready to start

- concrete/config/install/packages/elemental_full/content.xml
If MySQL runs with `STRICT_TRANS_TABLES` mode enabled, installation fails with this error:
```
'INSERT INTO btExpressForm (
bID,
exFormID,
submitLabel,
thankyouMsg,
notifyMeOnSubmission,
recipientEmail,
displayCaptcha,
redirectCID,
replyToEmailControlID,
addFilesToSet
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
with params [
"120",
"881b6bde-220f-4482-b8f9-ace40b5d169b",
"Submit",
"Thanks!",
"0",
"",
"",
"0",
"02181ae2-634d-11e6-a245-62e65b165d8e",
"0"
]:
SQLSTATE[HY000]: General error: 1366
Incorrect integer value: '' for column 'displayCaptcha' at row 1
```
> Fix installation when strict mode is enabled

- concrete/src/Page/Type/Composer/Control/CorePageProperty/CorePageProperty.php
It's called statically and does not contain any reference to $this
> Make CorePageProperty::clearComposerRequestProcessControls static

- concrete/src/Attribute/View.php
Those two function bodies are quite useless, since `$view` is not defined.
Should they do something? Since they've been so [for years](https://github.com/concrete5/concrete5/commit/02c446de54fe3c59ad08551f1323cce3e5d21c4f#diff-4d3f5ee2dfcd041eb508179c2564d134R92) I don't think so...
Otherwise, should `$view` be replaced with `$this->viewToRender`?
> Remove useless function code in Attribute\View on[Before|After]GetContents

- concrete/controllers/panel/page/versions.php
- concrete/views/panels/page/versions.php
This change does two things:
1. Prevents you from deleting all versions in the controller
2. Prevents you from deleting all versions from the front end
Resolves #4214
> Prevent all collection version from being deleted

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
Pull #4226 disabled the canonical url resolver when c5 is not installed, lets revert that.
> Update the canonical url resolver to work before the app is installed

- concrete/elements/permission/access/list.php
Increasing the modal width by 10px prevents the date selector from wrapping.
**Current**
**Changes**
> increase Access Entity modal width

- tests/tests/Core/Statistics/UsageTracker/FileUsageTrackerTest.php
Newer PHPUnit versions show this warning:
```
Trying to configure method "getCollectionObject" which cannot be configured
because it does not exist, has not been specified, is final, or is static
```
Let's fix this warning
> Fix FileUsageTrackerTest::testTrackingCollection test

- concrete/src/Session/SessionFactory.php
Pretty self explanatory. When I made this change previously I didn't realize that `cookie_lifetime` was settable through config.
Resolves #3995 (as long as you don't have cookie_lifetime configured)
> Remove cookie_lifetime override

- concrete/src/Url/Resolver/PageUrlResolver.php
fd58e88d145ec0c11222050e5290fbf3a5e13315 introduced the ability for the `PageUrlResolver` to return an external link if the page has one, however the change returns a string instead of what [`UrlResolverInterface` requires](https://github.com/concrete5/concrete5/blob/7b039747ab761de682d06a473441db08911f4988/concrete/src/Url/Resolver/UrlResolverInterface.php#L15-L15) which is an instance of `\League\URL\URLInterface`
> Return proper type from PageUrlResolver

- concrete/controllers/single_page/page_not_found.php
- concrete/controllers/single_page/register.php
- concrete/src/Page/Controller/PageController.php
- concrete/src/Routing/DispatcherRouteCallback.php
This change does two things:
1. Makes `$controller->replace` replace in a way that works with the dispatcher instead of just outputting and exiting.
2. Makes the 404 controller a little smarter so that it will apply the 404 response code in all cases.
> Better $controller->replace() functionality

- concrete/src/StyleCustomizer/Style/ColorStyle.php
- concrete/src/StyleCustomizer/Style/ImageStyle.php
- concrete/src/StyleCustomizer/Style/SizeStyle.php
- concrete/src/StyleCustomizer/Style/Style.php
- concrete/src/StyleCustomizer/Style/TypeStyle.php
It's called statically and it does not contain any references to `$this`.
BTW, if the base abstract class defines an abstract static methods,
PHP raises a "strict standards" warnings, so let's remove it from the base abstract class (`Style`)
PS: newer PHP versions (>= 7.0) don't throw the "strict standards" warning, and it could be interesting to know why. That's why I submitted https://bugs.php.net/bug.php?id=72993
> Make StyleCustomizer\Style\Style::getValuesFromVariables static

- concrete/src/Http/DefaultDispatcher.php
- concrete/src/Http/HttpServiceProvider.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Http/ResponseFactoryInterface.php
- concrete/src/Page/Collection/Response/CollectionResponseFactory.php
- concrete/src/Page/Collection/Response/ServiceProvider.php
- concrete/src/Routing/DispatcherRouteCallback.php
- concrete/src/Routing/RouteCallback.php
This moves all of the response creation stuff from the dispatcher and adds some extra helpful functions to a new ResponseFactory class.
One can get an instance of it by doing `$app->make(ResponseFactoryInterface::class)`
> Move dispatcher response creation to a new ResponseFactory

- concrete/src/Permission/Access/AddSubpagePageAccess.php
**WARNING: behaviour changed**: I *think* there was a bug, since the `$permission` variable could be reused from a previous `foreach` cycle if it's not set in the current cycle.
It wasn't meant to work like this, was it?
> Avoid accessing undefined var in AddSubpagePageAccess::getAccessListItems

- concrete/controllers/single_page/page_not_found.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Page/Controller/PageController.php
The important things in here are:
1. Replacement handling is lower
2. 404 page always validates the request
3. ResponseFactory->controller now handles PageControllers properly
Fixes issue with 404's being redirected to `/page_not_found`
> Fix 404 page rendering

- .travis.yml
- phpunit.xml
- tests/tests/CodingStyle/NoShortTagsTest.php
- tests/travis.hhvm.ini
- tests/travis.php.ini
Let's include in the test suite the tests introduced in #4157
> Enable tests in CodingStyle directory

- concrete/controllers/search/groups.php
- concrete/controllers/single_page/dashboard/users/groups.php
- concrete/src/User/Group/GroupList.php
If MySQL runs with the `ONLY_FULL_GROUP_BY` flag turned on (default on MySQL 5.7), visiting `dashboard/users/groups` causes this exception:
```
'SELECT count(g.gID) FROM Groups g ORDER BY gID asc LIMIT 1
SQLSTATE[42000]: Syntax error or access violation:
1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...)
with no GROUP columns is illegal if there is no GROUP BY clause
```
> Fix GroupList count

- concrete/src/Http/ResponseFactory.php
This resolves #4376 
The issue was caused by the fact that we handle the 404 page in a way that prevents an redirect loop. Because [`->collection()` send the page controller over to `->controller()` if it's a page_not_found collection](https://github.com/concrete5/concrete5/blob/50165a9ef5f3b178aec4af9978ad203451007450/concrete/src/Http/ResponseFactory.php#L231-L234) the request was never properly updated with the current page. To resolve this, we just run `$request->setCurrentPage($collection)` before we pass the controller to `->controller()`.
This change also includes a fix for a special case where someone doesn't have access to view the page not found page.
> Update the request with the current page if we get a 404 page

- concrete/controllers/single_page/dashboard/users.php
Base constructor needs a `Page` parameter: let's use `validateRequest` instead
> Avoid using constructor to redirect from dashboard/users

- concrete/controllers/backend/tree.php
- concrete/controllers/single_page/dashboard/users/groups/bulkupdate.php
- concrete/src/Tree/Node/Exception/MoveException.php
- concrete/src/Tree/Node/Node.php
If you try to move a user group under one of its child groups (logically incorrect), the site may become unavailable.
Let's avoid this.
> Avoid invalid node moves

- concrete/src/Http/ResponseFactory.php
Originally we just deferred to rendering the controller straight if we were given page_not_found in `ResponseFactory::collection()`, this was put there to prevent us being redirected back to "/page_not_found" any time we navigated to a path that didn't exist. That way worked, but it prevented the /bootstrap/process.php from being pulled in so we were unable to edit the page_not_found page through edit mode.
This change simply wraps the canonical url redirect conditional to only redirect if the page is not the page_not_found page.
> Remove old page_not_found fix and fix the original problem more directly

- build/Gruntfile.js
- build/package.json
JavaScript SourceMaps finally work on Windows
> Upgrade grunt-contrib-uglify

- concrete/blocks/switch_language/controller.php
For instance, if the current language is Chinese (that sadly I really can't read), I'd really wouldn't understand anything...
> SwitchLanguage block: show language names in their native language

- concrete/controllers/element/dashboard/express/control.php
- concrete/controllers/element/dashboard/express/menu.php
I checked all the classes derived from `Concrete\Core\Controller\AbstractController`, and I found two classes that didn't initialize themselves correctly.
> Add missing parent constructors to controllers

- concrete/src/View/View.php
- try to load file with $viewPkgHandle in addition to $themePkgHandle
- reduce variable name clashing (now we only use a variable named `$__data__`)
- throws an exception in case of variable name clashes
> Fix View::inc

- concrete/controllers/panel/detail/page/composer.php
Let's assume that:
1. we are creating a page via Composer
2. the page type has `Publish Method` set to `Choose from all pages when publishing`
3. we set the page handle in the `Page Settings` -> `SEO` panel
4. we set the parent page in the `Page Settings` -> `Location` panel
Currently, when we try to publish the page, the parent page ID is only retrieved from the page type or from a `cParentID` post field, but not from the currently saved data. This causes the inability to publish the page since the parent ID set in the `Location` panel is not retrieved: let's retrieve it.
> Composer save: fallback to use saved parent page ID

- web/concrete/blocks/switch_language/controller.php
- web/concrete/src/Multilingual/Service/Detector.php
Let's assume this example:
1. a visitor visit a page in Italian
2. then the visitor visit a page not under any locale root
Currently, concrete5 falls back the default site locale.
Let's add a new configuration option (`concrete.multilingual.use_previous_locale`) that, if set to true, set the current locale to the last used one.
> [5.7] Add configuration option to fallback to previous locale

- concrete/src/Page/Stack/Stack.php
I had this error during installation (PHP7): Declaration of Concrete\Core\Page\Stack\Stack::duplicate() must be compatible with Concrete\Core\Page\Page::duplicate()
> Fix declaration error on install

- concrete/blocks/switch_language/controller.php
This a of https://github.com/concrete5/concrete5/pull/4388, limited to the switch_language block part.
The part related to the page languages seems to be already working fine: @aembler where/when do you see [problems](https://github.com/concrete5/concrete5/pull/4388#issuecomment-248980330)?
> Ensure current locale selected in switch_language

- concrete/src/StyleCustomizer/Preset.php
I have this warning in my logs:
`Accessing undefined Less_Tree_Comment->name property`
Let's avoid this.
> Avoid accessing an undefined property in StyleCustomizer\Preset::getFromFile

- concrete/src/Database/EntityManagerConfigFactory.php
Removed hard reference to the vendor directory to allow loading the cms as a composer dependancy, all files in the vendor directory are already within the include path as specified here: https://github.com/concrete5/concrete5/blob/develop/concrete/bootstrap/configure.php#L363
> Doctrine annotation registration path fix.

- concrete/src/Package/PackageService.php
It's called statically by Entity\Package::getClass and it does not contain any reference to $this
> Make PackageService::getClass static

- concrete/src/Http/ResponseFactory.php
This is a condition that was missed in the dispatcher changes. [Originally we only sent notFound if validaterequest was not true](https://github.com/concrete5/concrete5/blob/5.7.x/web/concrete/src/Routing/DispatcherRouteCallback.php#L205-L207). With the new setup, that means we need to pass the home controller to `$factory->controller()` and return the result of that.
Resolves #4396
> Add back special handling for block passthrough

- concrete/controllers/single_page/register.php
- concrete/src/Editor/LinkAbstractor.php
- concrete/src/Job/Set.php
- concrete/src/Legacy/PageList.php
- concrete/src/Permission/Access/ListItem/ListItem.php
- concrete/src/Permission/Response/FileSetResponse.php
- concrete/src/Updater/Archive.php
- concrete/src/User/Event/AddUser.php
- concrete/src/User/Group/GroupSet.php
- concrete/src/User/PrivateMessage/Limit.php
- concrete/src/Workflow/Request/ApprovePageRequest.php
This just replaces tabs with spaces in controllers and src. This allows us to test against spaces/tabs spacing and catch the issue automatically without review.
If you have any doubts about whether this has functional implications, [add ?w=1 to the url and you'll see that nothing really changes other than spacing](https://github.com/concrete5/concrete5/pull/4419/files?w=1).
> Clean up old tab spacing in src and controllers

- concrete/src/Entity/Package.php
This should be the only place where PackageService->getClass is called statically
> Avoid calling PackageService->getClass statically

- concrete/authentication/google/controller.php
- concrete/authentication/twitter/controller.php
- concrete/controllers/single_page/login.php
- concrete/src/Authentication/AuthenticationTypeController.php
- concrete/src/Authentication/Type/OAuth/OAuth1a/GenericOauth1aTypeController.php
- concrete/src/Authentication/Type/OAuth/OAuth2/GenericOauth2TypeController.php
- concrete/src/Cookie/CookieServiceProvider.php
- concrete/src/Http/DefaultDispatcher.php
We weren't returning responses here, instead we were sending em which was causing the cookie middleware we have to not get a chance to deal with cookies. In addition to that, the cookie service provider was setting the singleton on "cookie" instead of on the class name making typehint DI not work properly.
> Fix forever authentication and make cookie middleware work

- concrete/src/Block/BlockType/BlockTypeList.php
When a site has a lot of block types only the first 100 will be shown because this is the default in BlockTypeList->get(). All blocks more then the first 100 cannot be edited, refreshed, removed or assigned permissions. Removing this limit solves that. Code that wants to add pagination can still do so.
> Show all blocktypes by default instead of only the first 100

- web/concrete/src/Application/Application.php
There's a quite hard problem to be solved, and here's the cause:
1. concrete5 starts and we initially setup the locale to the default one (user's one or, if no user is logged in, the site default)
2. we setup the packages (including their on-start events)
3. we load the site-level language files
4. localization system is ready
When the first call to t() is done, the Zend-i18n component gets initialized, i.e.:
a. it checks if its cache is ready
b. if not, it loads the configured language files, and stores them in its cache
c. it uses the translations in its cache file
So, if a call to t() is done somewhere between 1. and 4, the Zend-i18n cache is only partially populated, thus leading to some translation file not loaded.
A way to mitigate this problem is by calling package startup …
> [5.7] Mitigate problems about loading translation files

- concrete/src/Entity/File/Version.php
- concrete/src/File/Search/ColumnSet/FolderSet.php
- concrete/src/File/Type/Type.php
- concrete/src/File/Type/TypeList.php
Currently the File\Type class initialized itself with texts that are translated when the class is instantiated.
This causes problems when setting/changing the locale (file types are initialized very early during the boot process).
So, let's introduce the getDisplay* methods.
While we're at this, let's add getters/setters and deprecate the access to the class properties, add some phpdoc and get rid of other deprecated methods
> Add DisplayName / DisplayType to file types

- concrete/src/Routing/RoutingServiceProvider.php
These registrations are kinda difficult to get right in your head...
So here's what I want to be true:
```php
// Rebinding the interface clears the singleton
$app->bind(RouterInterface::class, NewRouter::class);
$app->make(NewRouter::class) === $app->make(RouterInterface::class); 
// Same type AND same instance
$app->make(Router::class) === $app->make(RouterInterface::class); 
```
The issue currently is that this won't work since NewRouter is not setup as a singleton, so overrides need to take care to set their override object as a singleton for the override to work. The hope with the broken code was that the singleton would be bound to the interface instead of the implementation.
> Fix router service provider registration

- tests/tests/Core/Foundation/ClassloaderTest.php
This should fix [these tests warnings](https://travis-ci.org/concrete5/concrete5/jobs/166360018#L535-L557) caused by [this change](https://github.com/concrete5/concrete5/pull/4453/files#diff-2fdc1f2cb748756db77f4cbcfe01a3d9L125).
> Fix tests warnings

- concrete/src/Entity/Attribute/Value/UserValue.php
- concrete/src/Entity/Notification/NotificationAlert.php
- concrete/src/Entity/User/User.php
- concrete/src/User/UserInfo.php
There was a minor issue with issue with a null target user id being passed to the delete workflow request, I'm guessing that the reference just got missed during the doctrine entity implementation.
Once I'd patched the above, errors were being thrown due to foreign key constraints failing on the UserAttributeValues table. There was no relationship definition from the User entity to the UserValue and thus a users attributes weren't being flushed on deletion.
Also, the User entity was trying to reference the Notification entity directly. I've updated it to reference the intermediate NotificationAlert entity. I've then implemented cascading deletes for User to NotificationAlert and then the NotificationAlert to the various Notification entities which keeps things clean on user deletion.
> [8.0.0b6] Delete user fixes (#4395)

- concrete/blocks/image/controller.php
- concrete/src/File/Tracker/UsageTracker.php
Previously the file usage tracker would convert block controllers to blocks then back to block controllers. This caused data to be lost, instead we just handle blocks and block controllers in the tracker object filter.
> Fix file usage tracker

- concrete/config/concrete.php
- concrete/src/Conversation/Message/Message.php
Some defined properties with a new more restrictive visibility was the cause of this javascript error. 
An additional issue I ran into was the fact that my webserver always has SERVER_NAME set, but it might not always be filled. Because of that it was breaking submission. This could be a security risk because someone could potentially use hosts entry to send legit looking mail from a separate domain.
This resolves #4392
> Resolve issue with adding replies to conversations

- concrete/blocks/image_slider/form_setup_html.php
If the last Image Slider slide is removed, the block will error when saved.
Steps to reproduce:
1. remove the last Image Slider slide
2. save
3. console error
VM939:324 Uncaught The editor instance "description[]" is already attached to the provided element.
To remove the slide, the CKEditor instance for that slide needs to be destroyed before the slide is removed from the DOM. This requires each slide to have a unique ID.
> Image slider remove fix

- concrete/src/Search/Field/AttributeKeyField.php
`$this->attributeKey` can be a null on wakeup context.
Steps to reproduce the error
+ Add new attribute to page/user/file
+ Select that attribute on page/user/file advanced search on dashboard
+ Delete that attribute
+ Back to advanced search
> [v8] [SearchField] Avoid accesing class methods on null

- concrete/css/build/core/app/panels/add-block.less
This is a small adjustment to the way block labels are handled in the add block panel, without changing the overall appearance.
Currently some of the labels for the built in blocks are being truncated when there is room to display them in full. Even two word block names that really wouldn't be considered 'long' are being unnecessarily truncated. This just makes understanding the purpose of each block more difficult.
This change removes this ellipsis truncation and subtly adjusts the padding to allow more text to fit.
In one screen shot above I changed the text of one block to show a much longer block title.
Although this isn't suitable as a block name, it shows that it at least will continue to fit the text.
An option could be to reduce the font size further down by 1px, then it fits even …
> Adjustment of block panel block labels

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
- concrete/src/Url/Resolver/PageUrlResolver.php
- concrete/src/Url/Resolver/PathUrlResolver.php
With this change, the PageUrlResolver will pass the Page used to the PathUrlResolver, which will also pass the page used to the CanonicalUrlResolver. If a page is passed to the CanonicalUrlResolver, it will ignore its internal cache and resolve the url based on the page specific site config.
> Add support for resolving canonical url based on passed page

- web/concrete/src/Page/CustomStyle.php
> [5.7] Corrected page custom style property / variable name.

- concrete/src/User/Workflow/Progress/ProgressList.php
When MySQL 5.7 runs in strict mode (that's the default), visiting `/dashboard/welcome` leads to this error:
```
Doctrine\DBAL\Exception\DriverException thrown with message
"An exception occurred while executing
'SELECT DISTINCT u.uID, u.uName, wp.wpID
FROM Users u
INNER JOIN UserWorkflowProgress uwp ON uwp.uID = u.uID
INNER JOIN WorkflowProgress wp ON wp.wpID = uwp.wpID 
where
1=1
and wpIsCompleted = '0'
and wpApproved = '0'
order by wpDateLastAction desc
':
SQLSTATE[HY000]: General error: 3065
Expression #1 of ORDER BY clause is not in SELECT list, references column
'wp.wpDateLastAction'
which is not in SELECT list; this is incompatible with DISTINCT"
```
...let's fix this
> Fix welcome page when MySQL runs in strict mode

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
@KorvinSzanto What about installing [Warnings Log](https://github.com/mlocati/warnings_log) ? :wink:
> Avoid accessing undefined vars in CanonicalUrlResolver::resolve

- concrete/elements/dashboard/welcome.php
usually the (great) Image Of The Day pictures have their best part in the middle: let's show it in the dashboard welcome page (and avoid repeating it).
===
Turns this:
Into this:
> Center welcome picture and don't repeat it

- web/concrete/elements/page_controls_header.php
As the title says, added class to HTML tag while pages are in edit mode. Fixes #4381.
> [v5.7] Added 'ccm-edit-mode' class to HTML tag.

- concrete/elements/page_controls_header.php
As the title says, added class to HTML tag while pages are in edit mode. Fixes #4381.
> [v8] Added 'ccm-edit-mode' class to HTML tag.

- concrete/config/app.php
Fix the error `Class "\Concrete\Controller\Backend\Multilingual" does not exist`
> Fix routes to Multilingual backend controller

- web/concrete/src/File/Image/BasicThumbnailer.php
`file_exists` returns true for a directory too, should probably check for `is_file`, otherwise `getimagesize` will throw an exception if things went wrong on the disk. I'd rather have no picture but still see the page.
> [5.7] don't try to create thumbnails of a directory

- phpunit.xml
phpunit fails to run tests, [saying that](https://travis-ci.org/concrete5/concrete5/jobs/169290215#L501)
```
https://travis-ci.org/concrete5/concrete5/jobs/169290215#L501
```
> Remove MyBuilder\PhpunitAccelerator\TestListener from phpunit

- concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Assets localization is required because we now include the core/app asset group in the install page
> Allow /ccm/assets/localization/* URLs in install page

- concrete/controllers/install.php
- concrete/views/frontend/install.php
The result of `Core::make('helper/number')->formatSize` already contains the size unit.
Turn this:
Into this:
> Fix shown memory sizes

- concrete/js/build/vendor/bootstrap/collapse.js
It seems that in in https://github.com/concrete5/concrete5/commit/e1b80f684316445bd2a764028a1687e9f7002a6a we missed to add collapse.js required by https://github.com/concrete5/concrete5/commit/80e0c47559e3ccd0aa60c79d03c2ecb5241746bd
> Add bootstrap/collapse.js

- tests/tests/Core/Routing/URLTest.php
- tests/tests/Core/Url/Resolver/PageUrlResolverTest.php
Due to recent edits in the way cID variables were added, these tests needed revising.
> Make tests conform to cID changes

- concrete/src/Entity/Attribute/Value/Value/SelectValueOption.php
I was trying to figure out if that bug https://github.com/concrete5/concrete5/pull/4573 can be found in 5.8 too and saw this parameter which I think isn't necessary.
> [v8] remove unused parameter

- web/concrete/attributes/select/option.php
having a value like `R&D` causes the PO file to get messed up. It will be saved as `R&amp;D` and is thus not translatable.
> [5.7] use original value in select value translations

- concrete/css/build/core/app/flatten.less
This updates the select2 appearance to have border radius, font size and padding/height matching other form elements.
(previous work wasn't compiling bootstrap)
> Fix to match select2 padding, font sizes to other form elements

- concrete/src/Foundation/EnvironmentDetector.php
This fixes installation in case CONCRETE5_ENV has been defined. Currently the installation screen throws an exception in this case.
I also refactored the detection code a little bit to make it more easily understandable (check the commit).
> Fix installation and CONCRETE5_ENV

- concrete/blocks/share_this_page/controller.php
The share_this_page block used to push the services multiple times to the local "cache" array in case `getSelectedServices()` was called multiple times.
This fixes the issue by setting the local cache empty every time the `getSelectedServices()` method gets called.
To reproduce:
```php
$bc->export($xmlNode);
$bc->export($otherXmlNode);
```
After these calls, the social links appear twice in the XML generated from `$otherXmlNode`.
> Fix local cache issue with share_this_page block

- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Validator/ValidatorManagerInterface.php
I threw this together this morning and in my down time today. I think if we're following #4295 this would fall under:
* **Controversial > Feature improvements**
* **Controversial > Usability improvements**
This I think is an important change. It adds the ability to install concrete5 via the command line interactively.
Today the best way to install over CLI is to:
A. Already know the required options
B. Look at the InstallCommand class to determine the options via code
C. Try over and over until the errors stop and c5 gets installed
If you're like me, you do C every single time. This is a super painful time waste, so instead lets do a wizardy interactive install:
To test install in interactive mode:
`$ concrete5 c5:install -i`
I'm personally going to use this every time I install concrete5 …
> Add interactive install flag

- concrete/js/build/core/sitemap/sitemap.js
This fixes that annoying sitemap jump. Turns out it's caused by jquery ui. https://github.com/mar10/fancytree/issues/577
> Make it so that the sitemap doesnt jump on first click

- concrete/tools/dashboard/sitemap_data.php
This allows the flat sitemap view to render and resolves #4612. @aembler I'm not sure if we can populate 'locales' properly when `?displaySingleLevel=1` so I'll leave that to you.
> Fix flat sitemap view

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
See discussion in #4564 
Before I forget to do this, I am adding back request based urls to the canonical url resolver so that we don't set an example of returning just paths from the url resolver stack. 
I want to go on the record here and say that I don't really think we should actually merge this since the release candidate has been released now but I think it's important enough that we can make the decision in this pull request.
I'd like to revisit this stuff in 8.1 and make it so that we have actually stacked resolver stack. Today the Page and Path url resolvers require references to other url resolvers which is cool and all but it's super confusing. Instead they should be stacked so that the path url resolver only handles passed paths while the page url resolver only handles passed …
> Add back request based urls to the canonical url resolver

- concrete/config/app.php
- concrete/jobs/index_search.php
- concrete/jobs/index_search_all.php
- concrete/src/Page/Collection/Collection.php
- concrete/src/Page/Search/Index/PageIndex.php
- concrete/src/Page/Search/Index/PageIndexer.php
- concrete/src/Page/Search/IndexedSearch.php
- concrete/src/Search/Index/AbstractIndex.php
- concrete/src/Search/Index/DefaultManager.php
- concrete/src/Search/Index/Driver/IndexingDriverInterface.php
- concrete/src/Search/Index/IndexInterface.php
- concrete/src/Search/Index/IndexManagerInterface.php
- concrete/src/Search/SearchServiceProvider.php
Sorry about this single mega commit, I think you'll find the changes are rather straight forward if you take a minute or two to look at them.
I'm working on implementing a secondary search index for a client and I'm finding it extremely difficult. Without this change, you have to essentially replace the entire stack top to bottom. 
If this change lands, you can add your own custom index to the stack with the following code:
```php
$customDriver = new \My\Package\IndexDriver();
$manager = $app->make(IndexManagerInterface::class);
// Add an index for pages
$manager->addIndex(Page::class, new Index($customDriver));
```
and a custom driver would look like this:
```php
class IndexDriver implements IndexingDriverInterface {
function index($object) { ... }
function forget($object) { ... }
}
``` …
> Update search indexing stack to be easily extendable

- concrete/config/app.php
- concrete/config/db.xml
- concrete/src/File/Image/BasicThumbnailer.php
- concrete/src/File/Image/Thumbnail/Path/Resolver.php
- concrete/src/File/Image/Thumbnail/ThumbnailerInterface.php
- concrete/src/File/Image/Thumbnail/Type/CustomThumbnail.php
- concrete/src/File/StorageLocation/StorageLocation.php
- concrete/src/File/StorageLocation/StorageLocationFactory.php
- concrete/src/Foundation/Runtime/DefaultRuntime.php
- concrete/src/Foundation/Runtime/Run/DefaultRunner.php
- concrete/src/Http/Middleware/ThumbnailMiddleware.php
- concrete/src/Updater/Migrations/Migrations/Version20161108113202.php
We are in RC now so if we are adhering to what I set forth in the pull request that wasn't merged here: https://github.com/KorvinSzanto/concrete5/blob/d81ff1a4ea72436f70639013104fbc8d785503d2/README.md
This change falls under:
* **Controversial > Feature improvements**: Improves the FileImageThumbnailPath stack allowing it to track the built status of cached thumbnails
* **Accepted > Known bug fixes**: There is a known bug out there that if a user cancels a request prematurely or a request dies that is building the cache for a page (Read generating thumbnails) the pages thumbnails might be broken. If they are broken there's no way for them to currently get rebuilt leaving a users site broken. And to boot, if the issue happens every time they will never get their site displaying properly! …
> Fix for failed cached thumbnails

- concrete/css/build/core/app/panels/add-block.less
It's not perfect, but if we don't have more space we at least don't have an overflow.
Before:
After:
I didn't recreate the CSS files, not sure if you do that, but I don't with my own projects to avoid merge conflicts.
> [V8]RC1 fix text overflow in add block panel

- concrete/controllers/single_page/dashboard/users/search.php
- concrete/single_pages/dashboard/users/search.php
Fixes #4084
Change the "select2" field to a "select" field.
I also had to update the get_timezones source to change the "id" property to "value", in order to work properly with x-editable as documented here - https://vitalets.github.io/x-editable/docs.html#select
> Fix #4084 user select timezone

- concrete/src/Session/SessionFactory.php
This fixes the `There is already an active transaction` error people have been seeing.
> Use database sessions without transactions to prevent mysql errors

- concrete/attributes/number/controller.php
The width of a number field should be at least as wide as to accomodate 4 digits for years, for example
> Make number field a bit wider

- concrete/attributes/select/controller.php
- concrete/elements/express/form/form/attribute_key.php
- concrete/src/Attribute/AttributeKeyInterface.php
- concrete/src/Attribute/Controller.php
Following #4295 this is a known bug fix so good to accept. This makes it so that the express form block outputs its label elements with proper `for=""` attributes.
> Add method to attribute controllers to return label ID

- concrete/bin/concrete5.php
- concrete/bootstrap/configure.php
- concrete/bootstrap/paths.php
This changes the `APP_UPDATED_PASSTHRU` constant back to a `boolean` and adds a new constant `DIRNAME_APP_UPDATED`. As we work to get rid of these remaining procedural files we can find a better way to rework this stuff if there is one.
> Fix updating from 5.7.x

- concrete/blocks/image_slider/view.php
#In sliders a lot of times you want arrow & bullets **together** for better **user experience**. I only made small change inside <script> tag (will work fine in future updates from 5.X to 5.8).
I also made small change in "`form_setup_html.php`" to complete this task.
#4689 
- This is "how" the result should look like (demo of the slider in conrete5 site deafult theme):
http://www.siton-systems.co.il/slider
- Example of this pattern in swiper.js plugin:
-http://idangero.us/swiper/demos/14-nav-arrows.html
> Image slider view.php:: add option For arrow + bullets

- concrete/src/Database/EntityManager/Driver/Driver.php
- concrete/src/Database/EntityManager/Provider/DefaultPackageProvider.php
- tests/tests/Core/Database/EntityManager/Driver/DriverTest.php
- tests/tests/Core/Database/EntityManager/Provider/DefaultPackageProviderTest.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerBlank.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerDefault.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerDefaultWithAdditionalNamespaces.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerLegacy.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerWithNotSupportedMappingDriver.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerWithgetPackageEntityPath.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerXml.php
- tests/tests/Core/Database/EntityManager/Provider/Fixtures/PackageControllerYaml.php
- tests/tests/Core/Database/EntityManager/Provider/PackageProviderFactoryTest.php
- tests/tests/Core/Database/Traits/DirectoryHelpers.php
Added more unit tests:
- DriverTest
- PackageProviderFactoryTest
- DefaultPackageProviderTest
**In the Concrete\Core\Database\EntityManger\Provider\DefaultPackageProvider is still a bug**. [See here](https://github.com/concrete5/concrete5/blob/dc762a1f2920ddca8584e23b9780eb5717e4fd5f/concrete/src/Database/EntityManager/Provider/DefaultPackageProvider.php#L28-L30)  
If a package still has the method "getPackageEntityPath" it, will throw a exception because a Doctrine MappingDriver is returned instaed of a ....\EntityManger\Driver\DriverInterface which is required in the [EntityManagerConfigUpdater class ](https://github.com/concrete5/concrete5/blob/dc762a1f2920ddca8584e23b9780eb5717e4fd5f/concrete/src/Database/EntityManagerConfigUpdater.php#L34).
What should be the behaviour in this case? …
> [v8] More Test for ...Database\EntityManager\ 

- concrete/attributes/image_file/form.php
This makes it so that the <label> element works properly.
> Add id to image/file attribute element

- concrete/src/Express/EntryList.php
- concrete/src/File/FileList.php
- concrete/src/File/FolderItemList.php
- concrete/src/Logging/Query/LogList.php
- concrete/src/Page/PageList.php
- concrete/src/User/Group/GroupList.php
- concrete/src/User/UserList.php
This is needed when MySQL runs in strict mode (`sql-mode` contains ONLY_FULL_GROUP_BY and/or STRICT_TRANS_TABLES)
> Fix getTotalResults and createPaginationObject of DatabaseItemList

- concrete/src/Localization/Service/CountryList.php
`CountryList::getCountriesForLanguage` may return a couple of country codes that we explicitly removed from the recognized countries (see [CountryList::loadCountries](https://github.com/mlocati/concrete5/blob/08a696b1fc67978c46a7c3389e81ba6b7bc2bf9e/concrete/src/Localization/Service/CountryList.php#L19-L23)).
> Remove fake countries from CountryList::getCountriesForLanguage

- concrete/src/Page/Page.php
The static method `Page::addStatic` should call the static [`Collection::createCollection`](https://github.com/concrete5/concrete5/blob/d44febcd8ff84c93cd7f97761c7b7451d0898d54/concrete/src/Page/Collection/Collection.php#L98) method instead of the not-static [`Collection->addCollection`](https://github.com/concrete5/concrete5/blob/d44febcd8ff84c93cd7f97761c7b7451d0898d54/concrete/src/Page/Collection/Collection.php#L88), otherwise we have this `E_DEPRECATED` warning:
```
Non-static method
Concrete\Core\Page\Collection\Collection::addCollection()
should not be called statically
```
> Let's call the static method to create a collection from a static method

- concrete/js/build/core/dashboard.js
The click event handler is being fired too many times (all the old ones too). Resulting in multiple unnecessary ajax calls.
Before setting up a new event handler, remove the old one.
Other solution would be: setup both handlers, don't recall setupFavorites()
> Update dashboard.js add_favorite event firing too many times

- concrete/controllers/single_page/login.php
This makes it so that the redirect after login never uses cache. This fixes the issue where if you are redirected to the homepage or any other full page cached page after login you don't see the toolbar until hard refreshing.
> Disable cache for login redirect

- concrete/js/ckeditor4/core/ckeditor.css
- concrete/src/Editor/CkeditorEditor.php
- breaks up the default button groups into the smallest groups allowed
- removes the toolbar line breaks, which allows the buttons to wrap onto a new line depending on the width of the toolbar
- adds a 600px toolbar max-width to the inline editor, preventing the toolbar from being one long row
> CKEditor toolbarGroups

- concrete/src/Asset/JavascriptAsset.php
This should always work, you can test by opening you browser console and running `();;;();;;;;();;()` javascript is super lenient with extra semicolons.
That said, omitting a semicolon is also allowed by javascript so the issue I was running into was this:
Script 1:
```javascript
$().click(function() {
})
```
Script 2:
```javascript
(function() {
}())
```
Due to the way we we concat, we end up with the following:
```javascript
$().click(function() {
})
(function() {
}())
```
A keen eye will notice that that essentially boils down to: `$().click()()` which IS valid javascript, but certainly isn't what was intended. Not just that but `$().click()` doesn't return a function so this will always error.
This is a known issue with IIFE's in JS which is why it's always recommended to start your …
> Add a semi colon to separate JS scripts in cache

- concrete/src/Http/ResponseFactory.php
The problem was that $factory->collection() was calling $factory->forbidden which was then calling $factory->collection() again.
This change just renders via the controller instead which seems to work.
> Avoid cycle in ResponseFactory->forbidden

- concrete/src/Editor/CkeditorEditor.php
This resolves one of the bugs in this issue:
https://github.com/concrete5/concrete5/issues/4801#issuecomment-266115370
> Rich Text Editor - prevent array_merge() error when saving with all checkboxes unchecked

- concrete/src/Attribute/StandardValidator.php
- concrete/src/Attribute/ValidatorInterface.php
> Argument 2 passed to Concrete\Core\Attribute\StandardValidator::validateCurrentAttributeValue() must be an instance of Concrete\Core\Entity\Attribute\Value\Value, instance of Concrete\Core\Entity\Attribute\Value\PageValue given, called in C:\www\concrete\src\Page\Type\Composer\Control\CollectionAttributeControl.php on line 191
I change Concrete\Core\Entity\Attribute\Value\Value to Concrete\Core\Attribute\AttributeValueInterface for fix it
> [v8] Fix declaration error

- concrete/css/build/themes/dashboard/form-and-set-builder.less
- concrete/elements/page_types/composer/form/layout_set/control.php
- concrete/elements/page_types/composer/output/control.php
- concrete/single_pages/dashboard/pages/types/form.php
- concrete/tools/page_types/composer/form/add_control.php
- matches the Compose Form form control display with the current Form Details form control display
- removes the inline Compose Form form control CSS and merges it with the Form Details form control CSS (they use the same CSS)
After watching the latest Express videos, I saw that the Form Details form controls were always shown while the Compose Form form controls were hidden until hovered. Always displaying the form controls looks to be a much better approach and more intuitive.
**Form Details**
**Compose Form**
**Compose Form**
> Form Control Display

- concrete/src/Form/Service/Widget/DateTime.php
This pull request changes the default jQuery UI date picker behavior so that the year drop-down displays the last 100 years instead of 10.
Some users may not know that the year can be entered manually into the date text input. For entering dates like birthdays, having more years may reduce possible confusion.
https://github.com/concrete5/concrete5/issues/4862
The jQuery UI datepicker default for yearRange is `c-10:c+10`. This means that the year select drop-down displays 10 years in the past and 10 years in the future (relative to the current year). To select a year outside of that 10 year range, you must select the last available year in the past or future, which adds an additional 10 years to the year select drop-down.
http://api.jqueryui.com/datepicker/#option-yearRange
Example: select …
> DateTime widget - change default displayed past years from 10 to 100

- concrete/blocks/file/add.php
- concrete/blocks/file/controller.php
- concrete/blocks/file/edit.php
This pull request makes the File block label and validation text match what the input does.
> File Block - change label and validation text to reduce confusion

- concrete/config/app.php
- concrete/config/concrete.php
- concrete/src/Http/Middleware/CSRFMiddleware.php
This is the middleware to enable checking for CSRF tokens automatically by POST or header.
This is **disabled** by default for now but can easily be enabled. Currently this will break basically everything when enabled.
> Create the CSRF Middleware (off by deafult for now)

- concrete/single_pages/dashboard/users/search.php
- concrete/src/User/UserInfo.php
Main changes:
1. Show the language name, not its code
2. When clicking on a language, preselect the current value
I think that the style of the select needs some love from @MrKarlDilkington: as you can see from the screenshots:
- The style for `.ccm-ui select.input-sm` has a `line-height: 35px;` that forces the selected item to have an offset (it's cutted) (se both screenshots)
- If the item initially selected is quite long, and if the window is quite narrow, the popup is too narrow (see second screenshot). It seems that the popup width is somehow related to the width of the container of the attribute ([see this video](https://youtu.be/NDPzKbMRKtw))
> Fix the view of the users/search dashboard page

- concrete/bin/concrete5.php
Let's avoid short array syntax in CLI entrypoint.
For instance, if run with 5.3, before we had:
```
Parse error: syntax error, unexpected '[' in concrete/bin/concrete5.php on line 28
```
now we have:
```
concrete5 requires PHP 5.5.9+ to run.
```
> Avoid using short-array-syntax in CLI entrypoint

- concrete/single_pages/dashboard/extend/install.php
- concrete/single_pages/dashboard/extend/update.php
One the "Install" page, the button floated to the right, where on "Update", it did not. Also on the "Update" page, it hadn't got the "btn-primary" class added to it (but a non-available "success" class instead).
> Connect to community buttons standardized

- concrete/single_pages/dashboard/users/points/actions.php
Makes no real sense if other paging doesn't have a div wrapping it, so delete it on the "Actions" page (Members - Community Points - Actions) too. Shorter **and** cleaner! :)
> Wrapped div paging not needed ("Actions" page)

- concrete/views/panels/details/page/location.php
Make sure everything that comes after the "Add URL" is not floating next to the button and wrap the help-text in a paragraph instead.
Not sure if we should actually float the button to the right still? But hey, not up to me. For now, this code is more valid and will work fine if we decide to change some CSS here or there! - who uses br's anyways these days haha
> Page "Location" dialog update

- concrete/controllers/single_page/dashboard/system/basics/timezone.php
- concrete/single_pages/dashboard/system/basics/timezone.php
Add a function to suggest time zones compatible with the database one.
Users will pick a time zone, that will set the `app.server_timezone` concrete5 configuration key.
To test this, you can change the `date.timezone` PHP.ini configuration key to something different from the MySQL timezone.
> Add functions to autofix PHP time zone

- concrete/single_pages/dashboard/users/points/actions.php
- concrete/single_pages/dashboard/users/points/view.php
- wraps the results tables in div.table-responsive
- switches to the ccm-search-results-table.compact-results class from the table-striped class
- adds missing span, thead, and tbody tags
- add the btn-primary class to the Search button and positions it to the right
The "ccm-search-results-table" class adds the ascending/descending sorting column arrows.
This pull request uses the new "compact-results" class and depends on https://github.com/concrete5/concrete5/pull/4912 being accepted.
**Current:**
**Changes:**
> Community Points

- concrete/views/panels/add.php
When adding a stack block (drag a stack onto an area), you will see stack icon.
That Stack icon message was not properly wrap with t().
Here is the fix.
This bug is reported by @hayaka26
> Fixing Adding Stack message (reported by @hayaka26)

- concrete/blocks/page_attribute_display/controller.php
Currently, delimiters are not applied to topics. They are displayed with comma space separation.
This pull request "normalizes" them so that a delimiter can be applied.
> Page Attribute Display block - add delimiter option to topics

- concrete/single_pages/dashboard/system/seo/urls.php
Some languages, like Dutch, contain apostrophes in the translations: "Pretty URLs" becomes "Mooie URL's". This breaks Javascript strings contained in single quotes, because often single quote and apostrophe are used interchangeably.
`php-cs-fixer --config-file==<webroot>/.php_cs fix <filename>`
> Escape translations to prevent JavaScript errors because of containing apostrophes

- concrete/src/Entity/File/File.php
- concrete/src/Entity/File/Version.php
When moving a file to a new storage location, the thumbnails would be left behind in the previous storage location, but all links in the front end (and file manager) would point to the new storage location which would 404.
I also updated the move code to use flysystem's actual move functionality (which should reduce memory use as it will stream the files)
Before:
Move file to new storage location
All thumbnails 404
After:
All thumbnails work!
Testing:
1. Selected a file in the file manager
2. Permissions->Storage Location->S3
3. Refresh page
-Thumbnail shows in file list
5. Click on Thumbnails
-Thumbnails populated
> Move file thumbnails when moving the original file

- concrete/src/Page/PageList.php
Add a condition in case filterByPath used. Otherwise filterByPath returns no rows
> filterByPath fix

- concrete/src/Workflow/BasicWorkflow.php
- concrete/src/Workflow/HistoryEntry/BasicHistoryEntry.php
- concrete/src/Workflow/Progress/History.php
When the user who made a workflow request was deleted, display '(Deleted User)' instead of trying to retrieve the user's username causing an exception being thrown because of calling getUserName() on a non-object.
> Fix exception being thrown when the workflow requester was deleted

- concrete/src/Localization/Localization.php
This fixes and issue where Punic's locale was set incorrectly in case the active context was reverted back using the `popActiveContext()` method. In this situation, the Punic's locale was left to the previous locale set when `pushActiveContext()` got called. This caused the Punic translated site context's translations to be incorrect.
A visible occurrence of this issue was e.g. the `date_navigation` block where the month names should be translated according to the site's context.
> Fix localization issue with Punic

- concrete/controllers/install.php
- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Package/StartingPointPackage.php
Installing concrete5 with a language that's not `en_US` fails.
Let's be sure that the active locale is `en_US` in the install routines.
- Fix #4933 (it's still valid)
- Supersedes #4955
I also removed the `install_page_templates` method of the `StartingPointPackage` class, since it's not used anywhere (and the referenced file `/config/install/base/page_templates.xml` does not exist)
> Fix localized installation process

- concrete/src/Routing/ClosureRouteCallback.php
Redirects (after oauth) were not redirecting properly as the class we were checking against wasn't low enough in the inheritance chain.
> Fix redirect responses

- concrete/controllers/single_page/page_forbidden.php
Verified that setting `concrete.permissions.forward_to_login` to false does not show the login page (defaults to true)
> Fix an issue where concrete.permissions.forward_to_login didn't work

- concrete/attributes/image_file/type_form.php
Just changed the title of image file attribute, from "Text area options" to "Image/File Options".
> [Fix] Image file options text

- concrete/src/Editor/CkeditorEditor.php
Fix https://www.concrete5.org/developers/bugs/8-1-0/feature-block-ckeditor-source-view-empty-if-no-resized/#866545
> Fix CKEditor problem with view HTML source in IE11

- concrete/attributes/select/type_form.php
Bug tracker: https://www.concrete5.org/developers/bugs/5-7-5-8/changing-tags-settings-results-in-deleted-tags
> Inhibit saving tags if the max_input_vars PHP.ini value is reached
