concretecms/concretecms

- web/concrete/src/Html/Service/Navigation.php
- PSR-2 code styling
- Fixed some incomplete comments
- Changed $appendBaseURL to $prependBaseURL to better describe what it does
> PSR-2 and comment updates for the Navigation helper

- web/concrete/src/Cache/Adapter/ZendCacheDriver.php
Fix #1745 
Credits to @EC-Chris :wink:
> Fix localization clearcache

- web/concrete/elements/files/search.php
One more on the list of #1740 adding a simple select to control the pagination of the file manager.
This should be no big deal.
> [trivial] adding pagination control to the file manager

- web/concrete/css/build/core/style-customizer.less
- web/concrete/elements/custom_style.php
- web/concrete/js/build/core/style-customizer/inline-toolbar.js
> Issue #1670 style customizer slider improvement

- web/concrete/blocks/google_map/controller.php
- web/concrete/blocks/google_map/form_setup_html.php
- web/concrete/blocks/google_map/view.php
Option to enable/disable Scrollwheel. Implemented as done and tested in a live setup, not tested in this version.
> feature/Google Maps Scrollwheel

- web/concrete/src/Utility/IPAddress.php
Can't install when a port number in $ipAddress.
> Check included port number

- web/concrete/blocks/form/view.php
When the form is submitted, the page was not automatically scrolled to the form's position.
> Fixed form block's action URL's anchor

- web/concrete/src/Package/Package.php
when updating a package version the db.xml file does not seem to be refreshed for a package. Blocks within the package have their db.xml parsed just fine so I copied the logic from their refresh method and dropped it in for the packages. I have tested with both an install and an update and it seems to work in both cases.
> allow updates to db.xml file for packages

- web/concrete/elements/permission/lists/area.php
I'm sorry, this is my mistake.
> Fix a method name on a permission element

- web/concrete/elements/files/search.php
See https://github.com/concrete5/concrete5-5.7.0/commit/bf63724fd488e99de9cd5a379e986ebd2682614b#commitcomment-9145773
> Switch key/values in select for pagesize in search files element

- web/concrete/src/Routing/DispatcherRouteCallback.php
If redirect_home_to_default_locale is true and the home page of the default locale is the root page, we may have an infinite redirection.
It's a good idea to avoid it :wink:
> Avoid infinite multilingual redirection

- web/concrete/src/Form/Service/Widget/Color.php
> Fix for color picker textbox not being selectable

- web/concrete/blocks/autonav/templates/breadcrumb.php
> Add an accessible breadcrumbs template using ARIA

- web/concrete/blocks/image/controller.php
filter and sanitize eternal links which are displayed through the image block.
> filter external links in the image block

- web/concrete/src/Application/Service/Avatar.php
- web/concrete/src/Application/Service/Composer.php
- web/concrete/src/Application/Service/Dashboard.php
- web/concrete/src/Application/Service/Dashboard/Sitemap.php
- web/concrete/src/Application/Service/FileManager.php
- web/concrete/src/Application/Service/Urls.php
- web/concrete/src/Application/Service/User.php
- web/concrete/src/Application/Service/UserInterface.php
- web/concrete/src/Application/Service/UserInterface/Help.php
- web/concrete/src/Application/Service/UserInterface/Menu.php
- web/concrete/src/Application/Service/Validation.php
PSR all the things
There were 2 functions whose signatures did not hold up with PSR standards so I renamed them and created new functions with the old signatures marked as `@deprecated` 
I also added the `@deprecated` to functions that get tools urls from blocks and packages
> PSR /src/Application directory

- web/concrete/blocks/page_title/controller.php
- web/concrete/blocks/page_title/templates/archive.php
- web/concrete/config/install/packages/elemental_full/content.xml
Refs http://www.concrete5.org/community/forums/5-7-discussion/what-is-the-right-way-to-get-a-current-topic/
> Show the current topic name on page title block

- web/concrete/src/Area/Area.php
- web/concrete/src/Area/CustomStyle.php
- web/concrete/src/Area/GlobalArea.php
- web/concrete/src/Area/Layout/Column.php
- web/concrete/src/Area/Layout/CustomColumn.php
- web/concrete/src/Area/Layout/CustomLayout.php
- web/concrete/src/Area/Layout/Layout.php
- web/concrete/src/Area/Layout/Preset.php
- web/concrete/src/Area/Layout/ThemeGridColumn.php
- web/concrete/src/Area/Layout/ThemeGridLayout.php
- web/concrete/src/Area/SubArea.php
PSR and comments
also a few Loader::element() -> View::element() cause why not
> PSR-2 For /src/Area

- web/concrete/src/Area/Layout/Column.php
> fix missing ;

- web/concrete/config/app.php
- web/concrete/css/jquery-visualize.css
- web/concrete/js/jquery-visualize.js
> update jquery visualize and add the jquery/visualize asset

- tests/tests/Core/Html/Service/SeoTest.php
- web/concrete/blocks/page_list/controller.php
- web/concrete/config/concrete.php
- web/concrete/elements/header_required.php
- web/concrete/src/Html/HtmlServiceProvider.php
- web/concrete/src/Html/Service/Seo.php
Let's change the title in the `<head>` section of the page list archive, for better SEO!
Fixes #1716
> Introduce SEO helper

- web/concrete/single_pages/dashboard/extend/install.php
> fix install page trying to conect to marketplace

- web/concrete/src/Database/DatabaseManagerORM.php
Now that this is decided, these comments are unnecessary.
> Removed unnecessary comments.

- web/concrete/blocks/feature/form.php
I noticed that the preview icon is not showing in the feature block. I use this fix for my sites.
> Preview Icon now showing - Tiny Javascript change

- web/concrete/src/Page/Page.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
Because of the problem in #1863, this is a second try fixing #1862.
> Fix #1862 (second try)

- web/concrete/controllers/single_page/account/messages/inbox.php
> Escape user supplied parameters

- web/concrete/composer.json
- web/concrete/composer.lock
- Punic: see https://github.com/punic/punic/releases for the changelog from v1.2.3 to v1.4.1
- Translation Library: see https://github.com/mlocati/concrete5-translation-library/releases for the changelog from v1.0.0 to v1.0.1
> Update Punic + Translation Library

- web/concrete/src/Form/Service/Widget/Color.php
Perhaps it has a reason to doesn't allow this ?
> Allow to choose color with alpha chanel

- web/concrete/blocks/core_conversation/controller.php
Implement `getSearchableContent()` for Conversations block
- Add subject to searchable content
- Add body to searchable content
Fix to PSR4
> Add Searchable Content to Conversations Block

- web/concrete/src/Html/Service/Navigation.php
- web/concrete/themes/elemental/elements/footer.php
a shorthand for designers (not familiar with PHP namespaces)
> Add a shorthand method to get logout link

- web/concrete/mail/user_register.php
fix typo
reported by Takashi Ando @andotake3
> Fix typo in user_register.php

- web/concrete/src/Package/Package.php
Workflow progress categories are not uninstalled when unintalling a
package.
- Add workflow progress categories to uninstall items
> Fix Workflow Progress Category uninstall

- web/concrete/css/build/core/app/hud.less
- web/concrete/css/build/core/app/search.less
- web/concrete/css/build/core/app/toolbar.less
- web/concrete/elements/page_controls_footer.php
- web/concrete/js/build/core/app/edit-mode/editmode.js
- web/concrete/js/build/core/app/panels.js
- web/concrete/views/panels/details/page/composer.php
* Enables to use composer dialog
* Fix some interfaces to more mobile friendly
* Change mobile menu button to active in edit mode
> Improve mobile editing

- web/concrete/controllers/single_page/dashboard/users/search.php
> Fixes trailing slash issue on click in search users dashboard page

- web/concrete/src/Page/Page.php
I'm not 100% sure on this one, but I know that the function is definitely broken as there is no `$this->vObj->ptID`. 
Working on getting stuff working with E_NOTICE turned on so prepare for the barrage of PRs....
> Fixes Page isGeneratedCollection function

- web/concrete/jobs/check_automated_groups.php
- web/concrete/jobs/generate_sitemap.php
- web/concrete/jobs/index_search.php
- web/concrete/jobs/index_search_all.php
- web/concrete/jobs/process_email.php
- web/concrete/jobs/update_gatherings.php
- web/concrete/src/Mail/Importer/MailImporter.php
Just cleanup and code review here... nothing special... Left the remove_old_page_versions job for another time as it needed some real work done to it.
> Automated jobs psr2 / code cleanup

- web/concrete/blocks/survey/survey_list.php
> Fixes survey result and optimized query

- web/concrete/blocks/search/templates/tag_cloud/view.php
> Fixes url encoding on tag cloud

- web/concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- web/concrete/single_pages/dashboard/system/multilingual/setup.php
- web/concrete/src/Multilingual/Service/Detector.php
> Add an option to keep logged-in user's language

- web/concrete/controllers/dialog/file/search/customize.php
- web/concrete/controllers/dialog/page/search/customize.php
- web/concrete/controllers/dialog/user/search/customize.php
- web/concrete/controllers/search/files.php
- web/concrete/controllers/search/pages.php
- web/concrete/controllers/search/users.php
- web/concrete/src/Search/ItemList/Database/AttributedItemList.php
- web/concrete/src/Search/ItemList/Database/ItemList.php
- web/concrete/src/Search/ItemList/ItemList.php
Attempts to allow the existing sortBy to do less restrictive query building for developers and adds a new sanitizedSortBy function to accommodate user input in the Database ItemList
This is in response to the previous pull request #1771.
I didn't to a ton of extensive testing on this. Mostly it should be ok but i'm not sure if the 'rand()' string is actually being passed as user input or if that's parsed out somewhere else. Notice that I removed that exception to the rule with the thought that if someone wanted to leverage that they would use the `sortBy` instead of the `sanitizedSortBy` function. Obviously if that's user input though we'll need to add it back into the sanitizedSortBy checks.
Give it a good read through and let me know if there's any feedback.
> More options for ItemList sorting

- web/concrete/jobs/remove_old_page_versions.php
Resolves #1979 - Thanks @aembler for doing the heavy lifting, just needed the array reverse removed and figured I'd PSR2 it while i'm at it.
> Remove old page versions fix

- web/concrete/config/concrete.php
- web/concrete/elements/custom_style.php
> Added slider limit customization to concrete configuration

- web/concrete/composer.json
- web/concrete/composer.lock
- Fix handling dynamic translations of group sets
- Fix handling dynamic translations of select attribute values
> Upgrade Translation Library

- web/concrete/blocks/form/controller.php
- web/concrete/blocks/form/db.xml
- web/concrete/blocks/form/form_setup_html.php
- web/concrete/blocks/form/mini_survey.php
- web/concrete/blocks/form/view.php
- web/concrete/src/Updater/Migrations/Migrations/Version5732.php
Implementation for issue #2018 
I didn't test upgrading from a previous version of 5.7.3.1 but on a raw install everything worked as I would have expected and In my mind the programming should work for an upgrade.
> Implements submit button text changing for Form block

- web/concrete/blocks/form/mini_survey.php
$suvey to $survey, fixes form preview submit button.
> Fixed typo in form block (submit text)

- web/concrete/blocks/form/view.php
- web/concrete/blocks/page_list/templates/thumbnail_grid/view.php
- web/concrete/blocks/page_list/view.php
- web/concrete/blocks/page_title/templates/archive.php
- web/concrete/blocks/page_title/templates/byline.php
- web/concrete/blocks/page_title/view.php
- web/concrete/blocks/search/templates/tag_cloud/view.php
- web/concrete/blocks/search/view.php
- web/concrete/controllers/dialog/area/design.php
- web/concrete/controllers/single_page/dashboard/reports/logs.php
- web/concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- web/concrete/single_pages/dashboard/extend/connect.php
- web/concrete/single_pages/dashboard/pages/single.php
- web/concrete/single_pages/dashboard/system/optimization/jobs.php
- web/concrete/single_pages/dashboard/system/registration/open.php
- web/concrete/single_pages/dashboard/system/seo/searchindex.php
- web/concrete/src/Form/Service/Form.php
- web/concrete/src/Multilingual/Service/UserInterface/Flag.php
- web/concrete/tools/files/importers/remote.php
- web/concrete/tools/permissions/access_entity.php
These are a collection of fixes that Korvin asked me to take a look at, along with other things I found while poking the core with a large fish.
> Misc Escaping fixes

- web/concrete/src/Page/Search/IndexedSearch.php
> Escape area names when using it in regular expressions

- web/concrete/authentication/community/type_form.php
- web/concrete/authentication/concrete/change_password.php
- web/concrete/authentication/facebook/type_form.php
- web/concrete/authentication/google/type_form.php
- web/concrete/single_pages/account/edit_profile.php
- web/concrete/single_pages/dashboard/system/mail/method.php
- web/concrete/single_pages/dashboard/users/add.php
- web/concrete/single_pages/dashboard/users/search.php
- web/concrete/single_pages/register.php
- web/concrete/views/frontend/install.php
> autocomplete=off for passwords.... trying again

- web/concrete/blocks/date_navigation/view.php
- web/concrete/blocks/feature/templates/hover_description/view.php
- web/concrete/blocks/feature/view.php
- web/concrete/blocks/image/view.php
- web/concrete/blocks/image_slider/form_setup_html.php
- web/concrete/blocks/page_list/templates/thumbnail_grid/view.php
- web/concrete/blocks/page_list/view.php
- web/concrete/blocks/testimonial/view.php
- web/concrete/blocks/topic_list/view.php
Korvin didn't make me do this one :P
> Misc XSS fixes

- web/concrete/composer.lock
> Sync composer.lock

- web/concrete/config/concrete.php
- web/concrete/controllers/single_page/dashboard/system/seo/urls.php
- web/concrete/single_pages/dashboard/system/seo/urls.php
- web/concrete/src/Application/Application.php
- web/concrete/src/Url/Resolver/PathUrlResolver.php
Fixes #2069
Added this like and ports showed up everywhere so I guess it works, definitely works better than it did before :P
> Make running c5 on a non-standard port work

- web/concrete/composer.json
- web/concrete/composer.lock
> Upgrade Doctrine DBAL to 2.5.1

- web/concrete/src/Attribute/Controller.php
- web/concrete/src/Controller/AbstractController.php
- web/concrete/src/View/AbstractView.php
we used to be able to specify a default value in the post method, this should bring them back..
> bring back default value to post methods

- web/concrete/src/Attribute/Key/Key.php
we can have two attributes with the same handle as long as they are in different categories. That's also how the table is defined..
> an attribute key with the same handle can exist in two categories

- README.md
Currently reporting status for master.
> Use develop branch in build status badge

- web/concrete/config/install/base/permissions.xml
- web/concrete/src/Application/Service/UserInterface.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
> Allow admins to access site in maintenance mode

- web/concrete/controllers/frontend/assets_localization.php
Twas missing, causing the select option to be blank
> Added "in_lightbox" string to assets_localization.php for Redactor

- web/concrete/src/Asset/Asset.php
- web/concrete/src/Asset/CssAsset.php
- web/concrete/src/Asset/JavascriptAsset.php
- web/concrete/src/View/View.php
> Improve merging assets

- web/concrete/src/Editor/LinkAbstractor.php
> LinkAbstractor should only replace app url if there is an app url

- web/concrete/src/View/View.php
> fix setViewTheme (should delete cached objects and reload them)

- web/concrete/views/dialogs/file/thumbnails/edit.php
> Fix thumbnail saving

- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
Also need to make sure that the port is not 0 here
> Port check

- web/concrete/css/build/vendor/redactor/redactor.less
> Fix tooltip display when redactor is fixed on top

- web/concrete/src/Attribute/Key/Category.php
PHPDocs
Refactored Attribute Category to no longer use deprecated classes/functions
Set Attribute Category properties to be protected (previously they had no declaration), forcing the use of the get functions. Not sure if we should flip these to public or not, there aren't any usages of them in the core, but I suppose it's possible that some packages might?
> PHPDoc/Refactor Attribute Category

- web/concrete/single_pages/dashboard/system/permissions/antispam.php
- web/concrete/src/Antispam/Library.php
The antispam checks currently do not work because Concrete is used instead of Core. Also improved the settings page.
> Antispam fixes

- web/concrete/elements/block_footer_edit.php
- web/concrete/elements/page_types/composer/form/output/buttons.php
- web/concrete/single_pages/dashboard/system/basics/editor.php
- web/concrete/single_pages/dashboard/system/basics/name.php
- web/concrete/single_pages/dashboard/system/files/filetypes.php
- web/concrete/single_pages/dashboard/system/optimization/cache.php
- web/concrete/single_pages/dashboard/system/permissions/maintenance.php
- web/concrete/single_pages/dashboard/system/permissions/site.php
- web/concrete/single_pages/dashboard/system/registration/postlogin.php
- web/concrete/single_pages/dashboard/system/registration/profiles.php
Changed all the green save buttons to be blue for consistency
> Blue save buttons

- web/concrete/single_pages/dashboard/files/sets.php
- web/concrete/single_pages/dashboard/system/backup/backup.php
- web/concrete/single_pages/dashboard/system/permissions/site.php
> Checkbox alignment

- web/concrete/composer.json
- web/concrete/composer.lock
- web/concrete/src/Tree/Node/Node.php
- web/concrete/src/Tree/Node/Type/Category.php
- web/concrete/src/Tree/Node/Type/Topic.php
- web/concrete/src/Tree/Node/Type/TopicCategory.php
- web/concrete/src/Tree/Tree.php
> Tree localization fixes

- web/concrete/controllers/search/files.php
- web/concrete/js/build/core/file-manager/search.js
- web/concrete/src/File/Version.php
* "Search File in File Manager" permission is ignored
* View, Download and Edit menu items are not hidden even if these permissions are false
> Check proper permissions in file manager

- web/concrete/src/User/User.php
Fixes user ccmAuthUserHash clearing on logout, this was a bug. since if you checked the "Remember me for 2 weeks" on login and then logged out, closed the browser, then visited the site again you would be logged back in as the user
Fixes E_NOTICE error previously caused by trying to set uLastLogin from database array that didn't have that set, let's use setPropertiesFromArray() instead to avoid these issues in the future.
Cleaned up unused Zend DateTime use statement which was replaced by the date helper at some point.
> User fixes

- web/concrete/src/Attribute/Value/CollectionValue.php
- web/concrete/src/Attribute/Value/FileValue.php
- web/concrete/src/Attribute/Value/UserValue.php
- web/concrete/src/Captcha/Library.php
- web/concrete/src/Config/ConfigStore.php
- web/concrete/src/Editor/Snippet.php
- web/concrete/src/File/Set/SavedSearch.php
- web/concrete/src/Filesystem/TemplateFile.php
- web/concrete/src/Gathering/Item/Page.php
- web/concrete/src/Gathering/Item/Template/Type.php
- web/concrete/src/Html/Service/Lightbox.php
- web/concrete/src/Http/Service/Ajax.php
- web/concrete/src/Legacy/Loader.php
- web/concrete/src/Localization/Service/Date.php
- web/concrete/src/Page/Statistics.php
- web/concrete/src/User/Point/Action/Action.php
- web/concrete/src/User/PrivateMessage/Limit.php
- web/concrete/src/User/User.php
- web/concrete/src/User/UserInfo.php
- web/concrete/src/User/UserList.php
- web/concrete/src/View/View.php
- web/concrete/src/Workflow/HistoryEntry/BasicHistoryEntry.php
Lots of missing use statements and phpdocs needing a \ in them for proper return/param classes
> Use statements & PHPDoc tweaks

- web/concrete/single_pages/dashboard/blocks/stacks/view.php
> Back to Global Areas

- web/concrete/src/Page/Controller/PageController.php
> Fix warnings in PageController

- web/concrete/src/Legacy/UserList.php
> add missing imports

- tests/tests/Core/Update/UpdateTest.php
Sometimes (but not always) the UpdateTest fails.
This PR could fix this.
> Fix UpdateTest

- web/concrete/src/Updater/Migrations/Migrations/Version20140919000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20140930000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20141017000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20141024000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20141113000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20141219000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20150109000000.php
- web/concrete/src/Updater/Migrations/Migrations/Version20150413000000.php
> Rename the migration classes

- web/concrete/blocks/page_title/controller.php
77 less warnings installing sample content
> Avoid warnings in page title block

- cli/install-concrete5.php
While installing via CLI it's very useful to tell the caller if the installation failed or all is good.
> Set install script return code

- web/concrete/src/Page/Page.php
Same problem as concrete5/concrete5#1832
> Fix display order issue of aliased pages

- tests/tests/Block/BlockStyleTest.php
- web/concrete/blocks/core_stack_display/controller.php
- web/concrete/controllers/dialog/area/design.php
- web/concrete/controllers/dialog/block/design.php
- web/concrete/js/build/core/style-customizer/inline-toolbar.js
- web/concrete/src/Area/CustomStyle.php
- web/concrete/src/Block/CustomStyle.php
- web/concrete/src/Page/Collection/Collection.php
> Generate custom style tags only if there's some style

- web/concrete/single_pages/dashboard/system/multilingual/translate_interface.php
Already fixed in https://github.com/concrete5/concrete5-5.7.0/commit/382bb529b94a56c678b519918bf3479b070ec509 but reverted in recent commit
> Redo fix for approval support of Translator

- web/concrete/src/File/Version.php
> Don't generate thumbnails if image could not be loaded

- web/concrete/src/Application/EditResponse.php
AjaxHelper already supports \Exceptions: let's get `EditResponse` support them too...
> Allow EditResponse to handle \Exceptions

- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
> Correct handling of canonical URL in CLI enviro

- web/concrete/single_pages/dashboard/system/files/permissions.php
- web/concrete/single_pages/dashboard/system/permissions/tasks.php
- web/concrete/single_pages/dashboard/system/permissions/users.php
* Fix the path of cancel button on file permissions page
* Add cancel button on task & user permissions page
* Blue save button
Refs: #2305 , #2227
> Fix buttons on pages of permission

- tests/tests/Core/File/Service/FileTest.php
- web/concrete/src/File/Service/File.php
> Better file extension resolver

- web/concrete/src/Asset/Asset.php
- web/concrete/src/Asset/CssLocalizedAsset.php
- web/concrete/src/Asset/JavascriptLocalizedAsset.php
> Detect changes in assets

- web/concrete/src/File/Importer.php
Storage->copy returns false in case of failure, it doesn't raise an exception
> Fix importer from incoming

- web/concrete/blocks/form/form_setup_html.php
Fixes "reply to this email address" when field type is changed in edit mode
Fixes #2327
> Fixes 2327

- web/concrete/src/File/Version.php
> Generate thumbnails based on the original filetype

- web/concrete/src/Page/Type/Type.php
Need some documentation on this function really badly
> page type add phpdoc

- web/concrete/composer.json
- web/concrete/composer.lock
> Update gettext stuff

- web/concrete/src/File/Service/File.php
Bug tracker: http://www.concrete5.org/developers/bugs/5-7-3-1/concretecorefileserviceunfilename/
> Fix FileHelper::unfilename

- web/concrete/jobs/generate_sitemap.php
If the site has multilingual sections, let's add the links to the mapped pages.
> Multilingual sitemap

- web/concrete/src/View/View.php
> Fix assets combination condition

- web/concrete/src/File/Version.php
> Avoid error on getting thumbnail with unregistered handle

- web/concrete/blocks/page_list/controller.php
68 less warnings during installation with full sample content
> Avoid warnings saving PageList block

- web/concrete/src/Tree/Node/Type/Group.php
50 less warnings during installation with full sample content
> Avoid warnings accessing undefined gID in group node type

- web/concrete/src/Permission/Access/Access.php
44 less warnings during installation with full sample content
> Avoid warnings in Permission\Access::getByID

- web/concrete/attributes/select/controller.php
37 less warnings during installation with full sample content
> Avoid warnings in SelectAttribute controller

- web/concrete/src/Legacy/DatabaseItemList.php
> Fix warnings in DatabaseItemList

- web/concrete/src/Permission/Category.php
> Cleanup PermissionCategory

- web/concrete/attributes/boolean/controller.php
> Cleanup BooleanAttribute

- web/concrete/bootstrap/start.php
> Die with an error message if the host is invalid

- web/concrete/src/User/UserInfo.php
> Cleanup UserInfo

- web/concrete/single_pages/dashboard/view.php
When there were no children pages the list was not properly started.
> Fix missing list element

- web/concrete/tools/files/import.php
> Incoming files checkbox

- web/concrete/src/Http/Request.php
- web/concrete/src/Http/RequestBase.php
> Request: fix warnings and code cleanup

- tests/tests/BlockTypeTestCase.php
- tests/tests/ConcreteDatabaseTestCase.php
- tests/tests/Core/Update/UpdateTest.php
- web/concrete/src/Block/BlockType/BlockType.php
- web/concrete/src/Updater/Migrations/Migrations/Version20150413000000.php
> Fixes 2320

- web/concrete/src/Page/Collection/Collection.php
- web/concrete/src/Page/Page.php
- web/concrete/src/Page/Type/Type.php
> Avoid calling Collection::addCollection statically

- web/concrete/controllers/single_page/register.php
This is a fix for PR2440 filename
https://github.com/concrete5/concrete5/pull/2440/files
> Fix filename 

- web/concrete/src/Attribute/DefaultController.php
> Cleanup Attribute DefaultController

- web/concrete/src/Asset/CssAsset.php
> Don't change paths of absolute @import

- web/concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
Let's make GenericOauthTypeController (and derived clases) handle correctly the current AuthenticationType
> GenericOauthTypeController constructor with same signature as AuthenticationTypeController constructor

- web/concrete/single_pages/dashboard/system/multilingual/setup.php
I guess that the 5.7 series is always greather than 5.6.0.3 :wink:
> Remove useless version check in multilingual setup

- web/concrete/single_pages/dashboard/pages/types/form.php
> Updated Bootstrap styles on the Add Control Set dialog

- web/concrete/src/Package/StartingPointPackage.php
See each commit message (in particular the second one)
> Cleanup StartingPointPackage

- web/concrete/blocks/form/form_setup_html.php
Add maxlength to the Question field in the form block #2498
> Add maxlength to form question field #2498

- web/concrete/attributes/topics/controller.php
> Fix warnings & cleanup Topics controller

- web/concrete/composer.json
- web/concrete/composer.lock
> Switch from innogames/cssmin to natxet/cssmin

- web/concrete/controllers/single_page/dashboard/users/group_sets.php
We can already add multibyte group set name. Let's save the same name.
> Allow to save multibyte group set name

- web/concrete/src/Page/Page.php
> Fix warnings & cleanup Page

- web/concrete/blocks/image_slider/controller.php
> Fix warnings in ImageSlider controller

- web/concrete/src/Localization/Service/Date.php
Removed these constants:
- ENABLE_USER_TIMEZONES
- C5_ENVIRONMENT_ONLY
> Remove old constants from date helper

- web/concrete/src/Backup/ContentImporter.php
used be there in 5.6 https://github.com/concrete5/concrete5-legacy/blob/master/web/concrete/core/libraries/content/importer.php#L548
> check existing attribute keys before import

- web/concrete/src/Backup/ContentImporter.php
> Cleanup ContentImporter v2

- web/concrete/config/concrete.php
- web/concrete/src/Asset/Asset.php
> Allow assets cache key calculated on contents

- web/concrete/blocks/form/controller.php
> Cleanup form block controller

- web/concrete/attributes/textarea/controller.php
> Cleanup Textarea attribute controller

- web/concrete/src/Page/DeletePageEvent.php
- web/concrete/src/Page/Page.php
> Cleanup Page v2

- tests/tests/Core/Utility/IPAddressTest.php
- web/concrete/src/Utility/IPAddress.php
I haven't actually been able to get an IPv4 to 6 address setup to test with yet, but based on the unit tests I added this should take care of the issues.
> Fixing ipv4 to ipv6 address bugs

- web/concrete/config/concrete.php
- web/concrete/config/database.php
- web/concrete/controllers/single_page/dashboard/system/basics/multilingual.php
- web/concrete/controllers/single_page/dashboard/system/registration/open.php
- web/concrete/controllers/single_page/dashboard/system/registration/postlogin.php
- web/concrete/src/Page/Page.php
- web/concrete/src/User/User.php
Please let me know if you prefer multiple pull requests instead of this single pull request.
> Cleanup config-related stuff

- web/concrete/elements/page_types/composer/form/output/buttons.php
> Check proper permissions for buttons on composer form

- web/concrete/controllers/backend/page.php
> Show error messages on sitemap widget ui

- web/concrete/config/concrete.php
- web/concrete/src/Session/Session.php
May help in case we have problems like #2579 or https://www.concrete5.org/developers/bugs/5-7-4-2/installing-with-open_basedir-still-fails/
> Allow customizing session save path

- web/concrete/config/concrete.php
- web/concrete/src/Multilingual/Service/Detector.php
- web/concrete/src/Page/Stack/Stack.php
The (**great**) latest changes break the installation. Let's make it work again :wink:
> Make installation work again & multilingual stack fixes

- web/concrete/authentication/concrete/controller.php
- web/concrete/config/concrete.php
- web/concrete/controllers/single_page/register.php
- web/concrete/src/File/Service/File.php
- web/concrete/src/Package/Package.php
> Remove old constants - Part 1

- web/concrete/src/Validation/BannedWord/Service.php
Those constants are not defined.
This pull request introduce class constants instead of those undefined global constants.
> Remove STRING_UTILS_... legacy constants

- web/concrete/tools/conversations/view_ajax.php
https://hackerone.com/reports/70946
> Sanitize some ints

- web/concrete/src/Application/Application.php
Let's clear the op-cache too when we call `Application::clearCaches`
> Clear opcache on cache clear

- web/concrete/blocks/next_previous/controller.php
- web/concrete/blocks/next_previous/form_setup_html.php
add "Reverse Sitemap" option
add "Reverse Chronological" option
fixes #2616
> Add reverse options to next_previous block

- web/concrete/controllers/backend/file.php
> Better dialog message when the user can not select files

- web/concrete/composer.json
- web/concrete/composer.lock
Fix problems reported in #2628
> Update league/url to latest 3.x series

- web/concrete/single_pages/login.php
Support for auth type icons that aren't embedded SVGs or font awesome icons.
> Added an icon class to the auth type

- web/concrete/src/Application/Application.php
Supersedes #2628 and fixes #2626
> Fix handle url slashes

- web/concrete/src/Permission/Key/Key.php
> Cleanup PermissionKey

- web/concrete/src/Tree/Tree.php
- web/concrete/src/Tree/Type/Group.php
- web/concrete/src/Tree/Type/Topic.php
> Fix warnings in Tree

- web/concrete/src/Permission/Access/Access.php
This fixes 9 E_STRICT warnings (E_WARNING in PHP 7)
> Fix warnings in Permission\Access

- web/concrete/src/User/Group/Group.php
> Fix warnings in User\Group

- web/concrete/src/Workflow/Progress/Category.php
> Fix warnings in Workflow\Progress\Category

- web/concrete/js/build/core/conversations/conversations.js
> MaxFileSize to maxFileSize in conversations

- web/concrete/src/Page/Stack/Stack.php
Let's make that method compatible with the parent class method
> Fix warnings in Stack::export

- web/concrete/src/Conversation/Editor/Editor.php
> Fix warnings in Conversation\Editor

- web/concrete/controllers/install.php
> Fix warnings in install controller

- web/concrete/blocks/topic_list/controller.php
> Fix warnings in TopicList controller

- web/concrete/blocks/survey/controller.php
> Fix warnings in Survey controller

- web/concrete/blocks/search/controller.php
> Fix warnings in Search controller

- web/concrete/src/Permission/Access/EditPagePropertiesPageAccess.php
> Fix warnings (and maybe a bugfix?) in EditPagePropertiesPageAccess

- web/concrete/blocks/next_previous/controller.php
> Fix warnings in NextPrevious controller

- web/concrete/blocks/google_map/controller.php
> Fix warnings in GoogleMap controller

- web/concrete/blocks/faq/controller.php
> Fix warnings in Faq controller

- web/concrete/src/Console/Command/ResetCommand.php
#2722 
Asks the user to confirm that they really want to reset
> Confirm reset

- web/concrete/css/build/core/app/panels/devices.less
Fixed device preview image paths (relative to CSS file instead of server root)
> Fixed device preview image paths

- tests/tests/ConcreteDatabaseTestCase.php
- tests/tests/Core/User/GroupTest.php
- tests/tests/UserTestCase.php
- web/concrete/src/User/Group/Group.php
Reverts concrete5/concrete5#2729 
I think I jumped the gun merging this, lets get some feedback from andy first.
> Revert "Fix failing UserPoint test"

- web/concrete/composer.json
- web/concrete/composer.lock
https://github.com/thephpleague/url bumped to 3.3.5 https://github.com/thephpleague/url/pull/81 so we shouldn't need to track dev
> Track patch for league/url

- web/concrete/blocks/core_scrapbook_display/controller.php
This allows concrete5 to install again
> Fix installer

- web/concrete/css/build/themes/dashboard/main.less
- web/concrete/single_pages/dashboard/extend/install.php
Adds hover highlighting to the install packages #2340
> Adds hover highlighting to the install packages part 2 (see #2340)

- web/concrete/single_pages/dashboard/reports/forms.php
Added 'delete-response' class on Delete button to fire up confirmation
dialog
> Fix confirmation dialog

- web/concrete/controllers/single_page/dashboard/pages/types/attributes.php
- web/concrete/elements/attribute/editable_attribute.php
- web/concrete/elements/attribute/editable_list.php
- web/concrete/elements/attribute/editable_set_list.php
- web/concrete/single_pages/dashboard/pages/types/attributes.php
Clearly not the DRYest code, nor necessarily the prettiest, but it's a start towards #2740 
Mostly borrowed the element code from https://github.com/concrete5/concrete5/blob/develop/web/concrete/elements/attribute/editable_list.php
> stab at adding sets to the page type attributes

- web/concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php
- web/concrete/src/Page/Type/Composer/Control/Control.php
- web/concrete/src/Page/Type/Composer/FormLayoutSetControl.php
> delete composer control when attribute doesn't exist anymore

- web/concrete/elements/header_required.php
This allows favicons for to work with file storage providers.
> Change favicons to call getURL instead of getRelativePath.

- web/concrete/src/Mail/Service.php
> Adds support to add additional headers to mail.

- web/concrete/bootstrap/start.php
Example config settings:
'security' => array(
'trusted_proxies' => array(
'ips' => array(
'1.2.3.4',
),
'headers' => array(
'client_ip' => 'HTTP_X_FORWARDED_FOR',
),
),
),
> Adds support to adjust trusted proxy ips and settings.

- web/concrete/js/build/vendor/jquery-magnific-popup/jquery-magnific-popup.js
Replaces 0.8.8 from May 24, 2013.
This old version was throwing errors for popups using the [data-mfp-src method](http://dimsemenov.com/plugins/magnific-popup/documentation.html#content-types) during a 5.6-to-5.7 conversion.
Tested all its usages in the core and everything looks ok.
> Update Magnific Popup to version 1.0.0

- web/concrete/controllers/single_page/dashboard/reports/logs.php
- web/concrete/single_pages/dashboard/reports/logs.php
> Add Logs Export to CSV option

- web/concrete/controllers/single_page/dashboard/reports/logs.php
This changes it from exporting the log results you're currently looking at (paged), to exporting all.
> Changes the CSV to export all log entries.

- web/concrete/blocks/page_list/page_list_form.php
> Fixes UI Bug #2789

- web/concrete/src/Feature/Assignment/Assignment.php
> Fix warnings in Feature\Assignment

- web/concrete/src/Area/Area.php
- web/concrete/src/File/Image/Thumbnail/Type/Type.php
> Fix install with STRICT_TRANS_TABLES

- tests/tests/Core/User/UserPointTest.php
> Fix test so we don't actually send emails when we don't want to

- web/concrete/elements/page_types/composer/controls/core_page_property/name.php
- web/concrete/elements/page_types/composer/controls/core_page_property/url_slug.php
- web/concrete/tools/pages/url_slug.php
Fix for https://www.concrete5.org/developers/bugs/5-7-5rc1/german-umlauts-arent-converted-right-in-urls/
> Fix url slug generation

- web/concrete/src/Form/Service/Form.php
Minor fix for the change of https://github.com/mlocati/concrete5/commit/6aac14efeac0e1dc884160dfd658904d50f02358#diff-8415a178e4e8660939f613db906d4564L489
> Initialize $str in Form helper

- web/concrete/blocks/page_attribute_display/controller.php
Uses same settings as Page Title.
> Adds Page Attribute Display block caching.

- web/concrete/blocks/testimonial/view.php
Fix for forum issue:
https://www.concrete5.org/community/forums/5-7-discussion/testimonial-urls-not-working/
> Fix for Testimonial block URL's not working

- web/concrete/config/concrete.php
- web/concrete/config/db.xml
- web/concrete/src/Updater/Migrations/Migrations/Version20150731000000.php
I put this into a new migration since I wasn't sure how else to make sure those already running RC2 would get the update. Feel free to just yank whatever's appropriate and build your own commit if this isn't correct.
> add primary key to query log table

- web/concrete/src/Page/Page.php
> Fixed on_page_get_icon event

- web/concrete/blocks/page_list/auto.js
- web/concrete/blocks/page_list/controller.php
- web/concrete/blocks/page_list/db.xml
- web/concrete/blocks/page_list/page_list_form.php
- web/concrete/blocks/page_list/tools/preview_pane.php
Allows filtering by:
Show All
Today
Past
Future
Between Dates
This adds feature requested in #2415
> Adds Date Filtering feature to PageList

- web/concrete/src/Multilingual/Page/Section/Section.php
- web/concrete/src/Page/Page.php
- web/concrete/src/Page/Stack/Stack.php
> LSP for Page::getByID()

- web/concrete/src/Sharing/SocialNetwork/Service.php
- web/concrete/src/Sharing/SocialNetwork/ServiceList.php
Adds feature #2420 
Example Config:
```
'social' => array(
'additional_services' => array(
array(
'mail',
'Mail',
'envelope-o',
),
array(
'hello_world',
'Hello World',
'hi',
'<b class="hi">Hi</b>',
),
),
),
```
> Adds ability to add Social Icons via config.

- web/concrete/blocks/file/composer.php
- web/concrete/blocks/file/controller.php
- web/concrete/blocks/file/view.php
> Adds support for the File Block in Composer

- web/concrete/src/Permission/IPService.php
remove deprecated function calls
fix `logSignupRequest()` to honour parameter to ignore config
> ipservice cleanup

- web/concrete/src/Page/Collection/Version/Version.php
- web/concrete/src/Page/Page.php
> fixes collection version cache bug

- web/concrete/src/StyleCustomizer/Stylesheet.php
> Add source maps when generating uncompressed CSS from LESS

- web/concrete/src/Gathering/Item/Item.php
> Avoid static abstract function: Gathering\Item\Item::getListByItem

- web/concrete/config/concrete.php
- web/concrete/controllers/single_page/dashboard/system/optimization/cache.php
- web/concrete/single_pages/dashboard/system/optimization/cache.php
- web/concrete/src/StyleCustomizer/Stylesheet.php
Improve #2863 as discussed in #2862
> Add specific option to control CSS source map

- web/concrete/src/Permission/Access/Entity/Entity.php
> Avoid static abstract function: Permission\Access\Entity::getAccessEntitiesForUser

- web/concrete/blocks/core_scrapbook_display/controller.php
Adds support for caching by checking original block settings.
> Feature scrapbook cache improvements

- web/concrete/blocks/search/controller.php
Adds ability to cache Search Block if the block doesn't display results - useful for when placed in header/footer.
> Feature search cache improvements

- web/concrete/blocks/testimonial/controller.php
> Include Testimonial Position content to search index

- web/concrete/views/dialogs/block/aliasing.php
Cancel button on block aliasing dialog is not works.
> Fix Cancel button action on block aliasing dialog

- web/concrete/src/Page/Page.php
- web/concrete/src/Page/View/PageView.php
> Fixes DesignPreview Bug where wrong wrapper classes were applied

- web/concrete/src/Page/Collection/Collection.php
This seems to solve issue https://github.com/concrete5/concrete5/issues/2909.
-Steve
> Allow indexing of attributes for external links

- web/concrete/src/Permission/Access/Access.php
- web/concrete/src/Permission/Access/AddBlockBlockTypeAccess.php
- web/concrete/src/Permission/Access/AddBlockToAreaAreaAccess.php
- web/concrete/src/Permission/Access/AddConversationMessageConversationAccess.php
- web/concrete/src/Permission/Access/AddFileFileSetAccess.php
- web/concrete/src/Permission/Access/AddSubpagePageAccess.php
- web/concrete/src/Permission/Access/EditPagePropertiesPageAccess.php
- web/concrete/src/Permission/Access/EditPageThemePageAccess.php
- web/concrete/src/Permission/Access/EditUserPropertiesUserAccess.php
- web/concrete/src/Permission/Access/ViewUserAttributesUserAccess.php
Supersedes #2678 (reverted in https://github.com/concrete5/concrete5/commit/d560ab24ac84ddda6dc3185b32340c589c95e9c2 )
> Fix warnings in Permission\Access v2

- web/concrete/blocks/core_stack_display/controller.php
Stack loops through all blocks contained within and sets cache settings for the stack appropriately.
> Feature stack cache improvements

- web/concrete/blocks/core_area_layout/controller.php
- web/concrete/src/Area/Layout/Column.php
Works by iterating through child blocks and checking combining all their cache settings together for the Area Layout.
> Feature area layout caching improvements

- web/concrete/src/Page/Type/PublishTarget/Type/Type.php
Mainly fixes a couple `E_Notice` errors
> Page type publish target cleanup

- web/concrete/src/Gathering/Item/Template/Template.php
- web/concrete/src/Gathering/Item/Template/Tile/TitleDateCommentsTemplate.php
Two bug fixes here: see the commit messages
> Fix GatheringItemTemplate::getGatheringItemTemplateData

- web/concrete/controllers/dialog/file/bulk/sets.php
On behalf @jeffharris23
https://github.com/concrete5/concrete5/issues/2830#issuecomment-131234044
> Fixes performance issue with file sets, Resolves #2830

- web/concrete/src/Area/Layout/Column.php
- web/concrete/src/Area/Layout/PresetLayout.php
Due to the intermittent nature of the bug, I'm not 100% about this fix... maybe someone who knows layouts better than I can look it over?
> Fixes bug with Core Area Layout - Fixes #2923

- web/concrete/views/panels/details/page/composer.php
- web/concrete/views/panels/page/check_in.php
Accidentally I've deleted my drafts which was almost publishable. This button causes destruction.
> Show confirm dialog before discarding draft

- web/concrete/src/Page/Type/Type.php
> Fix second part of #2952

- web/concrete/controllers/single_page/dashboard/pages/templates.php
- web/concrete/src/Page/Type/Type.php
> Fix first part of #2952

- web/concrete/bin/concrete5.php
jobs stuff doesn't work without it if you have a package job
> packages need autoloaded for the cli 

- web/concrete/src/Application/Application.php
Fixes issue where when visiting any page (other than home page) on an idn domain you go to a 301 loop. Example Domain: совокна58.рф
> IDN Redirect Fix

- web/concrete/controllers/single_page/dashboard/reports/forms.php
Adds escape character to answers which start with either -, = or + to prevent macros from being run.
Note: This fixes an issue with Excel, but adds extra ' to office libre.
Fixes: h1 #91282
> Adds escape character to prevent Excel Macros

- web/concrete/blocks/image_slider/controller.php
Image Slider uses Redactor editor for descriptions, but there are no translation in controller. Let's translate Image Slider descriptions with LinkAbstractor.
> Links in Image Slider descriptions are currently "index.php?cID=" style

- web/concrete/controllers/backend/file.php
> Ignore post_max_size when it's disabled

- web/concrete/blocks/faq/form_setup_html.php
minHeight wasn't working because it was passed as a string
> Pass minHeight as a integer to Redactor

- web/concrete/blocks/core_area_layout/controller.php
This addition import styles into subareas.
> Take care of styles into a columns

- web/concrete/views/dialogs/page/add_block_list.php
If you added a BlockTypeSet but didn't add anything to them it would cause the foreach to error on a null value.
> Fix problem with BlockTypeSet's not having any blocks attached to them

- web/concrete/attributes/textarea/controller.php
it's handled by Core::make('editor') when it's really needed
> don't include redactor asset

- web/concrete/src/File/Importer.php
> fix large imports

- web/concrete/src/Application/Service/UserInterface.php
- web/concrete/src/Attribute/DefaultController.php
- web/concrete/src/Attribute/View.php
- web/concrete/src/Conversation/Discussion/Discussion.php
- web/concrete/src/Form/Service/Widget/Attribute.php
- web/concrete/src/Form/Service/Widget/UserSelector.php
- web/concrete/src/Gathering/Item/Template/Template.php
- web/concrete/src/Legacy/ItemList.php
- web/concrete/src/Legacy/Pagination.php
- web/concrete/src/Mail/Importer/MailImporter.php
- web/concrete/src/Page/Type/Composer/Control/Type/CorePagePropertyType.php
- web/concrete/src/Permission/Access/EditPageThemePageAccess.php
- web/concrete/src/Permission/Access/Entity/FileUploaderEntity.php
- web/concrete/src/Permission/Assignment/AreaAssignment.php
- web/concrete/src/Permission/Assignment/BlockAssignment.php
- web/concrete/src/Permission/Assignment/FileAssignment.php
- web/concrete/src/Permission/Key/AddFileFileSetKey.php
- web/concrete/src/StyleCustomizer/Inline/StyleSet.php
- web/concrete/src/User/Point/Action/Action.php
- web/concrete/src/User/PrivateMessage/PrivateMessageList.php
- web/concrete/src/Utility/Service/Identifier.php
- web/concrete/src/Workflow/Request/PageRequest.php
Lots of code with NOTICEs from undefined variable access, a few bits of code using the wrong variable names, and workflow progress function that didn't extend with correct parameters
> fix many things

- web/concrete/views/dialogs/block/design.php
Closes #2987 
Example on how to use in your page_theme:
```
public function getThemeBlockClasses()
{
return array(
'*' => array (
'alternate',
'highlighted',
'special'
)
);
}
```
> Adds ability to specify wildcard page theme classes

- tests/tests/Block/ContentTranslateTest.php
- web/concrete/src/Editor/LinkAbstractor.php
> fixes CCM:BASE_URL translation in edit mode

- web/concrete/bootstrap/start.php
Define application fully qualified class names to support automatic dependency resolution. See #3054
> Define fully qualified class names for application

- web/concrete/src/Page/Page.php
just a quick'n'dirty fix for https://github.com/concrete5/concrete5/issues/3064
not well tested as I'm on my laptop
> fix block reordering

- web/concrete/src/Editor/LinkAbstractor.php
Make the LinkAbstractor less aggressive with it's dom parsing / reformatting
Fixes #3063
> Less Aggressive Link Abstractor

- web/concrete/src/Job/QueueableJob.php
- web/concrete/src/Job/Set.php
> Fix JobSet::getListByPackage function

- web/concrete/src/File/File.php
> Fixes file-exists bug on duplicate

- web/concrete/controllers/single_page/dashboard/system/conversations/settings.php
- web/concrete/single_pages/dashboard/system/conversations/settings.php
> Fix formatting and remove Loader from conversations/settings page

- web/concrete/src/Application/Service/FileManager.php
Allows the use of custom label text for file selectors. Not very elegant but it works
> Fixes #3083

- web/concrete/src/Page/Stack/Stack.php
> Page\Stack::addStackToCategory should be static

- web/concrete/js/build/core/app/in-context-menu.js
- web/concrete/js/build/core/app/toolbar.js
Adds isEnabled() method to toolbar, and checks against it using existing
logic. We might need to consider a more robust solution moving forward,
but this adheres to the current code logic / structure.
> Fixes Inline Block Editing Bug #3039

- web/concrete/src/Attribute/Key/Key.php
- web/concrete/src/Attribute/Type.php
- web/concrete/src/File/Set/SavedSearch.php
- web/concrete/src/File/Set/Set.php
- web/concrete/src/Gathering/Item/FlickrFeed.php
- web/concrete/src/Gathering/Item/Item.php
- web/concrete/src/Gathering/Item/Page.php
- web/concrete/src/Gathering/Item/RssFeed.php
- web/concrete/src/Gathering/Item/Twitter.php
- web/concrete/src/Http/FlysystemFileResponse.php
- web/concrete/src/Page/Type/Composer/Control/CorePageProperty/UserCorePageProperty.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
- web/concrete/src/Workflow/Progress/PageProgress.php
- web/concrete/src/Workflow/Progress/Progress.php
> Fix #2714 - aka concrete5 on PHP 7 !!

- web/concrete/src/StyleCustomizer/Inline/StyleSet.php
> Take care of background image into a Area

- web/concrete/src/Html/Image.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
* Elements are loaded from default theme instead of mobile theme
* Responsive image settings of mobile theme does not respected
> Fix mobile theme issues

- web/concrete/src/Attribute/PendingType.php
> Loader to Core::make

- web/concrete/src/Page/Type/Composer/Control/Type/CollectionAttributeType.php
> Fixes bug with adding attributes to attribute sets

- .php_cs
> Don't force empty lines before namespace declaration

- web/concrete/single_pages/dashboard/extend/install.php
> Fix loading translations of new packages

- web/concrete/blocks/image/controller.php
- web/concrete/blocks/image/view.php
- web/concrete/blocks/page_list/controller.php
- web/concrete/blocks/page_list/templates/thumbnail_grid/view.php
- web/concrete/blocks/page_list/view.php
- web/concrete/blocks/page_title/controller.php
- web/concrete/blocks/topic_list/templates/flat_filter.php
- web/concrete/controllers/install.php
- web/concrete/src/Attribute/Key/CollectionKey.php
- web/concrete/src/Attribute/Key/FileKey.php
- web/concrete/src/Attribute/Key/Key.php
- web/concrete/src/Attribute/Key/UserKey.php
- web/concrete/src/Routing/ControllerRouteCallback.php
- web/concrete/src/Sharing/SocialNetwork/ServiceList.php
- web/concrete/themes/concrete/elements/footer.php
- web/concrete/themes/concrete/elements/header.php
- web/concrete/themes/concrete/view.php
Just a few php warnings remains to be fixed... Let's fix them.
I'll add fixes to this pull request as soon as I find them, feel free to merge this PR when you want :wink:
> Fix a few PHP warnings

- web/concrete/js/build/vendor/tourist/tourist.js
For example to use in a conditional like so:
```javascript
onChange: function (tour) {
if ($('#input').val() === '1') {
tour.showStep(0);
return false; 
}
tour.next();
return false;
}
```
I did a pull request too on the original repo: https://github.com/easelinc/tourist
> Added the showStep(show_index) method.

- web/concrete/blocks/autonav/templates/responsive_header_navigation/view.css
- web/concrete/blocks/google_map/view.css
- web/concrete/blocks/page_list/view.css
- web/concrete/blocks/rss_displayer/view.css
- web/concrete/blocks/search/templates/tag_cloud/view.css
- web/concrete/blocks/search/view.css
- web/concrete/blocks/share_this_page/view.css
- web/concrete/blocks/social_links/view.css
- web/concrete/blocks/switch_language/templates/flags/view.css
- web/concrete/blocks/topic_list/view.css
> Cleanup/properly namespace block core CSS files

- web/concrete/src/Page/Single.php
> single page add fix

- web/concrete/src/StyleCustomizer/Style/ColorStyle.php
- web/concrete/src/StyleCustomizer/Style/Value/ColorValue.php
> Accepts a value of 0 for color alpha

- .php_cs
> Remove blank lines before namespace declarations

- web/concrete/src/Legacy/Loader.php
> Don't use deprecated methods in deprecated Loader

- web/concrete/blocks/file/controller.php
- web/concrete/controllers/single_page/download_file.php
Bugtracker: https://www.concrete5.org/developers/bugs/5-7-5-3/zip-file-download/
> Fix download of binary files

- web/concrete/blocks/image_slider/controller.php
"internalLinkCID" is not copied during replication.
> fix image slider duplicate

- web/concrete/config/db.xml
- web/concrete/elements/custom_style.php
- web/concrete/src/Area/CustomStyle.php
- web/concrete/src/Block/CustomStyle.php
- web/concrete/src/StyleCustomizer/Inline/StyleSet.php
> add background-size and background-position options to Background design menu

- web/concrete/bin/concrete5.php
> Fix CLI run with symlinked core directory

- tests/tests/Core/Url/Resolver/CanonicalUrlResolverTest.php
- web/concrete/config/app.php
- web/concrete/src/Http/HttpServiceProvider.php
- web/concrete/src/Routing/Router.php
- web/concrete/src/Routing/RouterInterface.php
- web/concrete/src/Routing/RoutingServiceProvider.php
- web/concrete/src/Support/Facade/Route.php
- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
- web/concrete/src/Url/Resolver/Manager/ResolverManager.php
- web/concrete/src/Url/Resolver/PageUrlResolver.php
- web/concrete/src/Url/Resolver/PathUrlResolver.php
- web/concrete/src/Url/Resolver/RouterUrlResolver.php
- web/concrete/src/Url/UrlServiceProvider.php
I'm going to merge this if the tests pass, the fix for #3208 is all contained in https://github.com/concrete5/concrete5/commit/759dc7a451dcf887beba7be97a35828e491ccdbd
> Add better https support plus a bunch of DI improvements along the way

- web/concrete/blocks/page_list/controller.php
Adds support for Page List blocks to be cached.
If there's no pagination or external filtering, Page List block will be cached same length as autonavs.
> Feature page list block cache improvements

- web/concrete/composer.json
- web/concrete/composer.lock
- web/concrete/src/Gathering/DataSource/TwitterDataSource.php
> Remove extra twitter dependency

- web/concrete/js/build/vendor/redactor/redactor.js
The Title field in the image edit form modal was mislabelled.
> change input label from Title to Alt

- web/concrete/config/concrete.php
- web/concrete/src/Http/Response.php
> Add X-Frame-Options header option

- web/concrete/config/app.php
- web/concrete/controllers/dialog/file/bulk/storage.php
- web/concrete/elements/files/search.php
- web/concrete/views/dialogs/file/bulk/storage.php
Currently, there is no way to bulk change storage location of multiple files. This pull request add it.
> Feature: bulk update storage locations

- web/concrete/src/User/User.php
This improves my logged in load time by ~10% believe it or not. This actually removes 5,348 calls to `\Concrete\Core\Support\Facade::__callStatic` though it adds 1,376 `Application::make` calls. Luckily `Application::make` is much cheaper :)
I'm merging this if the tests pass.
> Remove facade references from `User` constructor

- tests/tests/Core/Routing/URLTest.php
- tests/tests/Core/Url/Resolver/PageUrlResolverTest.php
- tests/tests/Core/Url/Resolver/PathUrlResolverTest.php
- tests/tests/Core/Url/Resolver/RouteUrlResolverTest.php
- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
- web/concrete/src/Url/Resolver/PathUrlResolver.php
- web/concrete/src/User/User.php
This is showing another ~10% improvement for me! Down from 880ms to 750ms!
part of #3287
> Further speed improvements

- web/concrete/config/db.xml
- web/concrete/src/Permission/IPService.php
This should resolve issue #3185 though upgrading may still be problematic.
> Update default date to be compatible with more recent mysql versions

- web/concrete/src/Conversation/Message/Message.php
- web/concrete/src/Conversation/Message/MessageEvent.php
dispatches on_new_conversation_message event when a message is added.
> Feature: Add new Conversation Message event

- build/Gruntfile.js
- web/concrete/config/app.php
- web/concrete/controllers/panel/detail/page/seo.php
- web/concrete/controllers/single_page/dashboard/system/seo/bulk.php
- web/concrete/css/build/core/app/app.less
- web/concrete/css/build/core/app/panels/seo.less
- web/concrete/js/build/vendor/jquery-text-counter/textcounter.js
- web/concrete/single_pages/dashboard/system/seo/bulk.php
- web/concrete/views/panels/details/page/seo.php
Uses the jQuery Text Counter Plugin under MIT
https://github.com/ractoon/jQuery-Text-Counter
> Adds word counts to fields in bulk seo page and sidebar panel

- web/concrete/src/User/UserList.php
Just a tiny suggestion.
This is the simple but convenient addition to SortBy function.
I know I could achieve easily by
`$userList->sortBy('u.uDateAdded', 'desc');`
> UserList: sortByDateAdded()

- web/concrete/src/Routing/Router.php
- web/concrete/src/Routing/RouterInterface.php
> Improvement: Update the Router::register method to allow full symfony constructor params

- web/concrete/src/Application/Application.php
part of https://github.com/concrete5/concrete5/issues/3287
more information here https://github.com/concrete5/concrete5/pull/3323
> remove facades from Application

- web/concrete/blocks/image_slider/controller.php
Maybe some data is missing in elemental_full/content.xml ?
> Avoid accessing undefined array indexes during installation

- tests/tests/Core/Backup/ContentImporterValueInspectorTest.php
- web/concrete/src/Backup/ContentImporter/ValueInspector/InspectionRoutine/PictureRoutine.php
Will fix https://github.com/concrete5/concrete5/commit/de1b98a0d5394de61af2de05b30d991b36708358#commitcomment-14725279
> Fix regex of Picture Inspection Routine

- web/concrete/js/build/core/sitemap/sitemap.js
I got such a result: https://dl.dropboxusercontent.com/u/23236615/Easy%20Export%20Import.png
> Add hierarchical multiple select in sitemap.js

- web/concrete/blocks/youtube/view.php
> Fix related videos behaviour on youtube block

- web/concrete/elements/page_types/composer/form/layout_set/control.php
Change button text in Dashboard -> Page Types -> Edit Form -> Delete Control
> Change button text in Delete Control modal

- web/concrete/src/Authentication/Type/OAuth/ServiceProvider.php
> Use valid \InvalidArgumentException instead of invalid \InvalidParameterException

- web/concrete/src/Console/Command/ClearCacheCommand.php
- web/concrete/src/Console/Command/ConfigCommand.php
- web/concrete/src/Console/Command/GenerateIDESymbolsCommand.php
> CLI minor fixes

- web/concrete/src/Console/Command/JobCommand.php
The relevant commit is this: https://github.com/concrete5/concrete5/commit/c75bf31198b27f67673f36478c9e32fb8ef625af
> Fix running job sets with c5:job CLI command

- web/concrete/src/Editor/LinkAbstractor.php
> Fixes 3399

- web/concrete/src/Console/Command/InstallPackageCommand.php
- web/concrete/src/Console/Command/PackPackageCommand.php
- web/concrete/src/Console/Command/UninstallPackageCommand.php
- web/concrete/src/Console/Command/UpdatePackageCommand.php
> CLI minor fixes II

- web/concrete/src/Package/StartingPointPackage.php
Fix for a bug introduced in #3403
> Fix the fix to StartingPointPackage::getClass

- web/concrete/src/Page/Page.php
- web/concrete/src/User/User.php
Changed some database queries to prepared statements
> Use prepared statements in queries

- web/concrete/src/Console/Command/ResetCommand.php
- web/concrete/src/Console/Command/TranslatePackageCommand.php
Third and last episode of the *CLI minor fixes* saga.
> CLI minor fixes III

- web/concrete/controllers/search/files.php
Bug tracker:
http://www.concrete5.org/developers/bugs/5-7-5-5/file-manager-broken-after-deleting-a-file-set./
> Fix error when searching files in deleted set

- web/concrete/css/build/core/file-manager.less
- web/concrete/single_pages/dashboard/files/sets.php
Reverts concrete5/concrete5#3407
> Revert "remove max height from filemanager thumbnail"

- web/concrete/blocks/core_area_layout/templates/parallax/view.js
- web/concrete/js/build/core/frontend/parallax-image.js
This is a complete rewrite
* Works in every case I could test
* More performant
* Easier code to understand
* Better commented
* Easier configuration based on "speed"
@joe-meyer  / @MrKarlDilkington mind trying this out for me?
> Improve parallax js

- web/concrete/js/build/core/frontend/parallax-image.js
This also adds a nice fade in effect so that it doesn't feel so jagged when they load.
> Fix: Initial scaling in IE

- web/concrete/src/Application/Application.php
- web/concrete/src/Url/Resolver/CanonicalUrlResolver.php
- web/concrete/src/Url/Url.php
- web/concrete/src/Url/UrlImmutable.php
- web/concrete/src/Url/UrlInterface.php
This change alters how we generate the string instead of changing when the port is set.
> Better url port handling

- web/concrete/controllers/single_page/register.php
Cleanup in concrete/controllers/single_page/register.php
> Register controller cleanup

- web/concrete/src/Multilingual/Service/Extractor.php
Package translations wasn't fetched from .mo files
> Fix translating packages from .mo files

- web/concrete/attributes/text/controller.php
- web/concrete/attributes/textarea/controller.php
- web/concrete/attributes/topics/controller.php
https://github.com/concrete5/concrete5/pull/3386/
> remove length from attribute type index definition

- web/concrete/controllers/backend/page/arrange_blocks.php
> Fix ordering blocks in global areas

- web/concrete/controllers/panel/add.php
- web/concrete/src/Application/Service/Urls.php
- web/concrete/src/Block/BlockType/BlockType.php
- web/concrete/src/Block/BlockType/Set.php
- web/concrete/views/panels/add.php
Making the add panel `E_NOTICE` free and cleaning up the code a little bit
> Add panel cleanup 8.0.0

- web/concrete/blocks/autonav/nav_item.php
> Undefined property: Concrete\Block\Autonav\NavItem::$cPointerExternalLink 

- web/concrete/src/User/UserList.php
http://www.concrete5.org/index.php?cID=799144
> Add join criteria to left join query

- web/concrete/src/Updater/ApplicationUpdate.php
> Clear op-cache when saving new update core version

- web/concrete/controllers/single_page/login.php
1. Replaced Core::make with $this->app->make
2. Replaced Session::(..) with $session
3. Replaced Events::(..) with $this->app->make
4. Removed unused imports
> Cleanup login controller

- web/concrete/blocks/core_area_layout/templates/parallax/view.php
- web/concrete/src/Area/CustomStyle.php
- web/concrete/src/Block/CustomStyle.php
> Fix custom styling with additional file storage location types

- web/concrete/authentication/concrete/controller.php
- web/concrete/controllers/single_page/dashboard/system/mail/method/test.php
- web/concrete/controllers/single_page/dashboard/system/seo/bulk.php
- web/concrete/controllers/single_page/dashboard/users/search.php
- web/concrete/controllers/single_page/register.php
- web/concrete/elements/header_required.php
- web/concrete/single_pages/dashboard/system/seo/bulk.php
- web/concrete/single_pages/login_oauth.php
- web/concrete/src/Antispam/Service.php
- web/concrete/src/Multilingual/Service/Extractor.php
- web/concrete/src/Sharing/ShareThisPage/Service.php
- web/concrete/src/User/PrivateMessage/Limit.php
- web/concrete/src/User/User.php
- web/concrete/src/User/UserInfo.php
- web/concrete/src/Workflow/BasicWorkflow.php
Fixes #3479
I still have to work on the dashboard/system/seo page: the suggested page titles should be build starting from each page multilingual section. BTW, before doing that I'd prefer to know if the approach of this PR is fine for the core team and for other users.
> Allow site name localization

- web/concrete/src/Application/Application.php
- web/concrete/src/Localization/Localization.php
> Load site strings after package strings

- web/concrete/controllers/single_page/download_file.php
1. Replace Core::make with app->make
2. Add PHPDoc
3. Simplify $this->post as it retuns null by default
4. Use app->shutdown instead of exit
5. Fix incorrect comments
> Cleanup download_file controller

- web/concrete/src/Permission/Access/Entity/UserEntity.php
Fix for http://www.concrete5.org/developers/bugs/5-7-5-6/choose-user-not-working/
> Allow accepting core UserInfo class

- web/concrete/bootstrap/process.php
- web/concrete/composer.lock
- web/concrete/config/db.xml
- web/concrete/controllers/panel/page/check_in.php
- web/concrete/css/build/core/app/panels.less
- web/concrete/css/build/core/app/panels/check-in.less
- web/concrete/css/build/core/include/variables.less
- web/concrete/elements/page_controls_footer.php
- web/concrete/src/Form/Service/Widget/DateTime.php
- web/concrete/src/Page/Collection/Version/Version.php
- web/concrete/src/Page/Page.php
- web/concrete/src/Routing/DispatcherRouteCallback.php
- web/concrete/views/panels/page/check_in.php
This is the PR for the [Add Timed Release of Pages](https://github.com/concrete5/concrete5/issues/3339).
Notes:
* The timezone shown on the scheduling controls has been moved to a new line to be able to fit long timezones.
* Should we create a new event "**on_page_type_scheduled**"?
> Timed Release of Pages

- web/concrete/blocks/video/README
- web/concrete/blocks/video/README.md
only rename to README.md and review text, as #3497.
> review text of block/video README

- web/concrete/controllers/single_page/dashboard/system/backup/update.php
site.php is legacy config file name.
> Fix wrong message on update error

- web/concrete/blocks/image_slider/form_setup_html.php
> add light box shadow for easier reordering

- web/concrete/config/concrete.php
- web/concrete/elements/files/search.php
http://www.concrete5.org/community/forums/5-7-discussion/file-manager-change-default-10-images
> add config value to set file manager results per page

- web/concrete/elements/page_types/composer/form/layout_set/control.php
https://github.com/concrete5/concrete5/issues/3540
> add required label for required form controls

- web/concrete/blocks/core_stack_display/controller.php
Stack content was not indexed to search results. Fixes #1513
> Fix stack content search indexing

- web/concrete/src/Session/SessionFactory.php
Resubmitting pull request to develop branch instead of master (apologies).
Original PR here: https://github.com/concrete5/concrete5/pull/3546
> Bugfix: gc_max_lifetime should be gc_maxlifetime

- CONTRIBUTING.md
Added note about using the `develop` branch, plus a few other minor editing tweaks
> Some text improvements to CONTRIBUTING.md

- web/concrete/src/Editor/CkeditorEditor.php
https://github.com/ExchangeCore/Concrete5-CKEditor/issues/48
> prevent icon tags from being hidden in editor and code view

- web/concrete/js/build/core/translator.js
> Filter by translated/untranslated out of the drop down menu

- web/concrete/composer.json
- web/concrete/composer.lock
> Switch to forked ZendQueue

- web/concrete/js/build/core/app/ajax-request/base.js
- web/concrete/views/panels/details/page/composer.php
> Stop autosave routine on ajax request error

- web/concrete/src/Page/Page.php
Same issue as #3508
We can use "1" or "2" for page handle, but we can't use "0"
> Use strings validator to validate cHandle

- web/concrete/src/Editor/LinkAbstractor.php
This fixes the broken tests. We should make sure to not push up breaking changes, I think the best way to do that is to go through pull requests always and never commit directly.
> Fix broken tests

- web/concrete/views/dialogs/file/properties.php
> Fix namespace of UserInfo

- web/concrete/config/app.php
- web/concrete/controllers/dialog/area/layout/presets/manage.php
> Fix LSB problem in Controller\Dialog\Area\Layout\Presets\Manage

- web/concrete/src/Conversation/Message/Message.php
Bug tracker: https://www.concrete5.org/developers/bugs/5-7-5-6/error-on-conversation-with-deleted-users/
> Be sure to not use deleted users in conversations

- web/concrete/blocks/image/controller.php
updated some deprecated functions
> Cleanup deprecated- ../blocks/image/controller.php

- web/concrete/blocks/image/form.php
updated some deprecated functions
> Cleanup deprecated- ../blocks/image/form.php

- web/concrete/views/panels/details/page/versions.php
Let's initialize `$checked` and `$display`, fix closing of `<iframe>` element
> Fix versions panel

- web/concrete/src/File/Search/ColumnSet/Available.php
https://www.concrete5.org/community/forums/5-7-discussion/feature-request-add-filename-colum-option-to-file-manager/
> add filename column to file manager Available column set

- web/concrete/attributes/text/controller.php
- web/concrete/attributes/text/type_form.php
- web/concrete/src/Entity/Attribute/Key/Type/TextType.php
Add option to set placeholder to the text attribute
> Placeholder for text attribute

- web/concrete/blocks/image_slider/form_setup_html.php
- web/concrete/blocks/image_slider/view.php
Correction of typos in the form and view.
> Image Slider fixes

- web/concrete/src/Http/FlysystemFileResponse.php
Looks like someone forgot to change these in the update.
> v8: Fix the ability to download files

- web/concrete/src/File/StorageLocation/Type/Type.php
Otherwise they get installed, just not to the package, then nothing works :/
> v8: Make Storage Locations installable from packages

- web/concrete/blocks/form/controller.php
Added an event to the form submit action, so after each form submit a **on_form_submission event** is triggered that passes form data to the eventlistener.
> Updated core form block controller for event

- web/concrete/src/Captcha/Library.php
- get rid of deprecated methods
- add phpDoc
- define properties (it's faster to use explicitly declared properties)
- allow using package IDs in addition to Package instances
- fix a couple of "Accessing undefined array index" warnings
> Fix captcha library

- web/concrete/config/app.php
I think that part of #3682 has been lost...
> Fix ccm/system/dialogs/area/layout/presets/manage route

- web/concrete/authentication/google/controller.php
- web/concrete/src/Authentication/Type/Google/Factory/GoogleServiceFactory.php
- web/concrete/src/Authentication/Type/Google/ServiceProvider.php
> Fix: Google authentication type

- web/concrete/authentication/community/controller.php
- web/concrete/src/Authentication/Type/Community/Factory/CommunityServiceFactory.php
- web/concrete/src/Authentication/Type/Community/ServiceProvider.php
> Fix: Community authentication

- tests/tests/Core/File/Service/Fixtures/TestStorageLocation.php
- tests/tests/Core/File/Service/ImageTest.php
- tests/tests/Core/Localization/Adapter/Zend/Translation/Loader/Gettext/SiteTranslationLoaderTest.php
- tests/tests/bootstrap.php
- web/concrete/src/File/FileServiceProvider.php
- web/concrete/src/File/Image/BasicThumbnailer.php
- web/concrete/src/File/StorageLocation/Configuration/ConfigurationInterface.php
- web/concrete/src/File/StorageLocation/StorageLocation.php
- web/concrete/src/File/StorageLocation/StorageLocationInterface.php
Mnkras originally did all the work, I did a little bit of extra DI stuff and got the tests functioning
See #3746
> Use storage locations for thumbnails

- web/concrete/elements/express/form/association/select.php
- web/concrete/elements/express/form/association/select_multiple.php
For a better translation, I need to know what hasn't been found...
> Better translatable text: "None found"

- web/concrete/single_pages/dashboard/system/registration/global_password_reset.php
> Translate the Global Password Reset page

- web/concrete/src/User/UserInfo.php
- web/concrete/tools/users/bulk_deactivate.php
> Fix user activation/deactivation

- tests/tests/Core/Localization/Adapter/Zend/Translation/Loader/Gettext/CoreTranslationLoaderTest.php
- tests/tests/Core/Localization/Adapter/Zend/Translation/Loader/Gettext/SiteTranslationLoaderTest.php
- tests/tests/Core/Localization/LocalizationTest.php
- tests/tests/Localization/LocalizationTest.php
- tests/tests/Localization/LocalizationTestsBase.php
- tests/tests/bootstrap.php
> Fix localization tests

- web/concrete/src/Database/EntityManagerConfigFactory.php
- web/concrete/src/Package/Package.php
- web/concrete/src/Package/PackageService.php
Mapping Information is now stored with relative paths.
> v8: Fix - Safe mapping information with relative paths

- web/concrete/blocks/page_title/controller.php
- web/concrete/blocks/page_title/form_add_edit.php
https://github.com/concrete5/concrete5/pull/3713#issuecomment-217395881
> Page Title block formatting suggestions

- tests/tests/Core/Service/ApacheRulesTest.php
- web/concrete/config/app.php
- web/concrete/config/services.php
- web/concrete/controllers/single_page/dashboard/system/seo/urls.php
- web/concrete/single_pages/dashboard/system/seo/urls.php
- web/concrete/src/Console/Application.php
- web/concrete/src/Console/Command/ServiceCommand.php
- web/concrete/src/Service/Configuration/ConfiguratorInterface.php
- web/concrete/src/Service/Configuration/GeneratorInterface.php
- web/concrete/src/Service/Configuration/HTTP/ApacheConfigurator.php
- web/concrete/src/Service/Configuration/HTTP/ApacheGenerator.php
- web/concrete/src/Service/Configuration/HTTP/ApacheStorage.php
- web/concrete/src/Service/Configuration/HTTP/Generator.php
- web/concrete/src/Service/Configuration/HTTP/NginxConfigurator.php
- web/concrete/src/Service/Configuration/HTTP/NginxGenerator.php
- web/concrete/src/Service/Configuration/HTTP/NginxStorage.php
- web/concrete/src/Service/Configuration/StorageInterface.php
- web/concrete/src/Service/Detector/DetectorInterface.php
- web/concrete/src/Service/Detector/HTTP/ApacheDetector.php
- web/concrete/src/Service/Detector/HTTP/NginxDetector.php
- web/concrete/src/Service/HTTP/Apache.php
- web/concrete/src/Service/HTTP/Nginx.php
- web/concrete/src/Service/Manager/ManagerInterface.php
- web/concrete/src/Service/Manager/ServiceManager.php
- web/concrete/src/Service/Manager/ServiceManagerServiceProvider.php
- web/concrete/src/Service/Rule/ConfigurableRuleInterface.php
- web/concrete/src/Service/Rule/Option.php
- web/concrete/src/Service/Rule/Rule.php
- web/concrete/src/Service/Rule/RuleInterface.php
- web/concrete/src/Service/ServiceInterface.php
Last attempt to implement #3156 / #3123
I just hope that @KorvinSzanto @WouterSioen and @chasepeeler won't ask to add more classes to this PR: I introduced 12 classes, 5 interfaces and spent a total of about 15 hours on this subject - it seems enough to me to read/write 10 lines of data... :wink:
> Improve web server configuration handling

- web/concrete/blocks/page_list/controller.php
- web/concrete/blocks/page_list/db.xml
- web/concrete/blocks/page_list/page_list_form.php
> Add an option to list pages at the current level in Page List

- web/concrete/css/build/core/app/app.less
- web/concrete/css/build/core/app/panels/design.less
- web/concrete/css/build/core/app/search.less
- web/concrete/css/build/core/include/variables.less
- web/concrete/js/build/core/style-customizer/inline-toolbar.js
I found some random [no-break space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) characters in a few files.  I replaced them, assuming they're supposed to be normal [space](http://www.fileformat.info/info/unicode/char/0020/index.htm) characters.
They were sometimes preventing less from compiling (e.g. https://github.com/less/less.js/issues/2542).
Not sure how to prevent this in the future outside of forcing UTF-8 character encoding in the `.gitattributes` file.
> Replace NO-BREAK SPACE characters

- web/concrete/src/Entity/Block/BlockType/BlockType.php
> Fix: Add facade use statement to fix tests

- tests/tests/Core/Application/UserInterface/ContextMenu/ContextMenuTest.php
https://github.com/concrete5/concrete5/compare/c1d3b22acfa8...0e0b1affc608#diff-f0ebff3a2d92929d50a183cc1f685080L25 broke the tests, this pull fixes them
> Fix the tests after merge

- composer.json
People who want to be included in the author field should open pull requests. Once this is merged we should be able to work with packagist.
> Add composer meta data

- concrete/src/Entity/Package.php
- Update method comments
- DateTime import
- PSR
> Fix docblocks pkg

- web/concrete/blocks/image_slider/form_setup_html.php
> Fix: Image slider max width bug

- README.md
- build/README.md
- build/package.json
See commit messages.
Closes #3834
> Fix build and install instructions

- concrete/single_pages/dashboard/users/points/actions.php
- concrete/single_pages/dashboard/users/points/assign.php
- concrete/single_pages/dashboard/users/points/view.php
- Make point fields numerical
- Remove some unused vars
> Assign points numerical fields

- concrete/controllers/single_page/dashboard/users/points/assign.php
Should be fixed with h-helper:
> Escape assign point action

- concrete/views/image-editor/controls/position.php
> Bugfix: Fix broken layout of image editor

- web/concrete/src/Editor/LinkAbstractor.php
> [5.7.x] Do not add empty style attributes to picture elements

- web/concrete/src/Search/Pagination/View/ViewRenderer.php
This pull
* Moves the url resolving function creation out to the getter so that it doesn't run until we actually need it.
* Sanitizes the resulting url
https://hackerone.com/reports/139971
> Add sanitization to pagination url

- composer.json
- composer.lock
as discussed in #3825 update the zend dependencies to their latest stable versions.
> Update Zend dependencies

- concrete/controllers/single_page/dashboard/system/environment/info.php
- concrete/src/Console/Application.php
- concrete/src/Console/Command/InfoCommand.php
- concrete/src/System/Info.php
Same output as of /dashboard/system/environment/info page, with these additions:
- Installed? Yes/No
- Value of `DIR_BASE`
- Value of `DIR_BASE_CORE`
> Add c5:info cli command

- web/concrete/bootstrap/process.php
- web/concrete/controllers/dialog/block/edit.php
- web/concrete/controllers/dialog/page/add_block.php
- web/concrete/src/Block/Events/BlockAdd.php
- web/concrete/src/Block/Events/BlockDelete.php
- web/concrete/src/Block/Events/BlockEdit.php
- web/concrete/src/Block/Events/BlockEvent.php
Adds events for add, edit, and delete for blocks on a page
> Add block add / edit / delete events

- concrete/src/Entity/File/Version.php
Thumbnails from SVG need the Imagik extension. If it's not available, let's simply don't create thumbnails
> Add support to thumbnails for SVG

- concrete/blocks/image/controller.php
- concrete/src/Block/Block.php
Better than https://github.com/concrete5/concrete5/commit/ee233bdc207fddb96ce5f4a03202d0e01de9c9b7 IMHO
> Correct initialization of block type controllers

- concrete/single_pages/dashboard/system/express/entities/add.php
- concrete/single_pages/dashboard/system/express/entities/edit.php
Asterisks added to:
- index.php/dashboard/system/express/entities/add
- index.php/dashboard/system/express/entities/edit/
> Add asterisks to indicate fields are required

- concrete/elements/dashboard/express/detail_navigation.php
Per the discussion, change the text to make the ability to change the listing info more easily discoverable
Closes #3920
> Change Express Customize Search to also include Listing

- concrete/elements/page_types/form/base.php
Noticed this small typo by chance.
> Fix ptDefaultPageTemplateID label

- web/concrete/blocks/form/controller.php
- web/concrete/bootstrap/process.php
PS: I think we should focus on redoing this process script for v8.1
> Duplicate block instead of aliasing if the block is set to copy on propagate

- concrete/blocks/core_area_layout/controller.php
Fix for https://www.concrete5.org/community/forums/5-7-discussion/call-to-a-member-function-setblockobject-on-a-non-object/
> Check for AreaLayout object

- concrete/src/User/User.php
`php-cs-fixer --config-file==<webroot>/.php_cs fix <filename>`
> Seems to be a typo with function hashpassword instead of HashPassword

- web/concrete/src/Conversation/Message/Message.php
`php-cs-fixer --config-file==<webroot>/.php_cs fix <filename>`
> Set date on a Conversation Message

- composer.lock
See https://github.com/concrete5/doctrine-xml/issues/4
> Upgrade DoctrineXML to v1.0.1

- concrete/src/Entity/File/Version.php
Before: The setting of the thumbnail size is "400 x Automatic dimensions" but the real size of the thumbnail image is "Automatic dimensions x 400"
After: Fixed.
> Fix issue to generate thumbnail of vertical long image

- concrete/src/Database/EntityManagerConfigFactory.php
- tests/tests/Core/Database/ApplicationXmlMetadataDriverTest.php
- tests/tests/Core/Database/ApplicationYmlMetadataDriverTest.php
- tests/tests/Core/Database/EntityManagerConfigFactoryTest.php
V8: Ignore application + package mapping information with invalid folder paths
> V8: Ignore application + package mapping information with invalid folder paths

- web/concrete/src/Application/Application.php
This would be rather helpful for two projects we are working on. Something you want to or have to populate a few things. In our case we want to update a third party system with the latest information and don't want to do that using a cronjob running every minute. That would kill our server..
> on_cache_flush_end added

- concrete/blocks/image/view.php
https://github.com/concrete5/concrete5/issues/4001
> restore Image block classes

- web/concrete/src/Page/View/PageView.php
Okay next attempt to #3946.
The cache output file for pages with theme customizations was only written after saving the customizations. Once the Cache was cleared or if the page was copied, no caching was possible.
This PR serves an uncached version only if the Theme CSS cache has been deactived in the settings or if the current version isn't approved yet. In all other cases the cache output file gets written on request if needed.
> Fix theme customizations caching

- web/concrete/css/build/core/app/panels.less
- web/concrete/css/build/core/app/panels/add-block.less
- web/concrete/js/build/core/app/panels.js
This makes it so that accordions can be used in subpanels, not just in the blocks panel
> Add the ability to use accordions in subpanels

- web/concrete/src/Application/Application.php
Apply the change from #4020 to v7
> Apply the change from #4020 to v7

- web/concrete/src/Application/Application.php
Flips the conditional to make it work how we actually want it to work.
> Invert path traversal blocker conditional

- concrete/views/panels/add.php
https://github.com/concrete5/concrete5/issues/3985
> remove empty block sets and add check to marketplace button

- concrete/css/build/core/app/panels.less
> remove dashboard panel scrollbars

- concrete/elements/page_controls_footer.php
> Fixes minor HTML error

- .travis.yml
- tests/tests/Core/Page/PageListTopicTest.php
The first commit enables the MySQL strict mode.
Upcoming commits will fix errors.
> Enable strict MySQL mode for tests (and fix tests)

- concrete/src/Entity/File/File.php
> Check if an author is associated to a file before returning it's ID

- concrete/views/panels/details/page/caching.php
- concrete/views/panels/details/page/location.php
- concrete/views/panels/details/page/permissions/simple.php
Fixes #4048, fixes #4049 and fixes #4050.
A few small tweaks to the Location, Caching and Simple Permissions panels.
> Settings panels styling tweaks

- concrete/single_pages/dashboard/system/seo/excluded.php
> make Excluded URL Word List single page fieldless

- concrete/blocks/rss_displayer/controller.php
- concrete/blocks/rss_displayer/form_setup_html.php
...and fix the ID of the referenced element for standardDateFormat label in the edit interface
> Avoid accessing undefined array index in RssDisplayer controller 

- concrete/single_pages/dashboard/system/environment/proxy.php
This pull request removes the form's Bootstrap grid elements that were breaking the layout.
**Current**
**Changes**
> Proxy Server single page layout fix

- concrete/single_pages/dashboard/system/attributes/topics/add.php
> make Add Topic Tree input fieldless

- concrete/single_pages/dashboard/system/mail/method/test.php
> Test Mail Settings fieldless

- concrete/views/panels/details/page/attributes.php
> add missing cancel button to attribute panel

- concrete/single_pages/dashboard/users/add.php
> make Add User single page fieldless

- concrete/single_pages/dashboard/system/mail/importers.php
> make Email Importers single page fieldless

- concrete/single_pages/dashboard/users/group_sets.php
> make Group Sets single page fieldless

- concrete/tools/permissions/dialogs/access/entity/types/group_combination.php
> update Add Group Combination modal button classes

- concrete/src/Page/Page.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/PageTemplateCorePageProperty.php
- concrete/src/StyleCustomizer/Stylesheet.php
- concrete/src/Workflow/Progress/Progress.php
- concrete/src/Workflow/Request/Request.php
Let's fix some warnings. See every commit message for details.
> Fix some warnings

- concrete/src/Workflow/Progress/Progress.php
> Fix Workflow\Progress::$wrID default value

- concrete/blocks/date_navigation/controller.php
- concrete/blocks/search/controller.php
- concrete/elements/conversation/message.php
- concrete/src/Conversation/Message/Message.php
- concrete/src/Page/Page.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/DescriptionCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UrlSlugCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UserCorePageProperty.php
- concrete/tools/conversations/add_message.php
See every commit message for details.
> Fix some warnings - Part II

- composer.json
- composer.lock
I did some work on the zend queue repo to make sure tests build and submitted to packagist
This resolves #4206
> Use custom zend queue fork for 7.0 compatibility

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
If the canonical url and canonical ssl url are different host, you can't move site link because canonical url resolver doesn't use canonical ssl url. This request will fix this issue.
Before:
After:
> Fix for canonical ssl url

- concrete/bootstrap/configure.php
- concrete/bootstrap/paths.php
> Use const instead of define

- concrete/attributes/select/form.php
- concrete/blocks/desktop_latest_form/view.php
- concrete/blocks/page_title/controller.php
- concrete/blocks/rss_displayer/view.php
- concrete/blocks/search/controller.php
- concrete/elements/pages/search_header.php
- concrete/src/Application/Service/Dashboard/Sitemap.php
- concrete/src/Legacy/PageList.php
- concrete/src/Search/Field/Manager.php
> Fix some warnings - Part III

- concrete/src/File/Service/File.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Updater/Update.php
Both during the installation and after an upgrade
> Make concrete/bin/concrete5 executable

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
Some of my changes were missed when #4226 was applied, I think this gets them all.
> Reapply changes that were missed in the merge from #4226

- .travis.yml
- concrete/src/Page/PageList.php
- concrete/src/User/UserList.php
This may help detecting problems like the one fixed in https://github.com/concrete5/concrete5/pull/4168 (tests should be as restrictive as possible)
> Add ONLY_FULL_GROUP_BY to the MySQL test server

- concrete/src/User/Search/ColumnSet/DefaultSet.php
It's called statically and does not contain references to `$this`
> Make User\Search\ColumnSet\DefaultSet::getUserStatus static

- concrete/single_pages/dashboard/users/search.php
That constant is not defined anymore...
> Get rid of ENABLE_USER_TIMEZONE constant

- concrete/blocks/content/controller.php
- concrete/blocks/image/controller.php
- concrete/blocks/image_slider/controller.php
- concrete/config/app.php
- concrete/config/install/base/jobs.xml
- concrete/config/statistics.php
- concrete/controllers/dialog/file/Usage.php
- concrete/jobs/update_statistics.php
- concrete/src/Entity/Statistics/UsageTracker/FileUsageRecord.php
- concrete/src/Entity/Statistics/UsageTracker/FileUsageRepository.php
- concrete/src/File/Menu.php
- concrete/src/File/Tracker/FileTrackableInterface.php
- concrete/src/File/Tracker/UsageTracker.php
- concrete/src/Page/Collection/Collection.php
- concrete/src/Updater/Migrations/Migrations/Version20160819000000.php
- concrete/views/dialogs/file/usage.php
- tests/tests/Core/Statistics/UsageTracker/FileUsageTrackerTest.php
- tests/tests/Core/Statistics/UsageTracker/TrackableBlockController.php
This adds a new usage tracker for files as well as an interface to the file manager for viewing usage.
Blocks it has been added to:
* Content
* Image
* Image Slider
Resolves #2929
> Add a file usage tracker and a job for scanning usage

- concrete/src/Multilingual/Page/PageList.php
I **think** the resulting query is correct: this needs a review...
Fix #3667
> Fix multilingual report query

- concrete/single_pages/dashboard/system/files/image_uploading.php
> make Image Uploading single page fieldless 

- concrete/single_pages/dashboard/system/registration/profiles.php
> make Public Profiles single page fieldless 

- concrete/single_pages/dashboard/system/mail/method.php
> make SMTP single page fieldless 

- concrete/src/Http/DispatcherInterface.php
This replaces the typo in the interface. This doesn't change functionality at all.
> Update dispatcherInterface to have 'request' variable

- concrete/src/Entity/File/Version.php
- Update the author of a file version when it's duplicated
- Update the approver  of a file version when it's approved
Fix #4210
> Set author ID on duplicate, approved ID on approval of files

- tests/tests/BlockTypeTestCase.php
Let's implement a couple of tests previously marked as incomplete.
> Implement BlockType::refresh tests

- concrete/src/User/Group/Group.php
It's called statically and it does not contain any reference to `$this`
> Make Group::getAutomationControllers static

- concrete/src/Http/DefaultDispatcher.php
This should be the right fix for #4311
@KorvinSzanto am I right?
> Fix installation via web interface

- concrete/src/Entity/Attribute/Value/Value/NumberValue.php
- concrete/src/Utility/Service/Number.php
- phpunit.xml
- tests/tests/Attribute/FileAttributeTest.php
- tests/tests/AttributeValue/NumberValueTest.php
- tests/tests/Core/Utility/Service/NumberTest.php
> Numbers work

- concrete/src/Entity/Attribute/Value/Value/NumberValue.php
> Avoid Core facade calls in NumberValue

- concrete/single_pages/dashboard/extend/install.php
... and fix a [couple of HTML errors](https://github.com/concrete5/concrete5/commit/cbfcc5f60ddb97ea48f4f8d731b32ccc120ccbf5)
> Avoid accessing undefined vars in dashboard/extend/install

- concrete/elements/attribute/editable_attribute.php
`atHandle` property does not exist anymore
> Use getAttributeTypeHandle instead of atHandle in editable_attribute element

- concrete/single_pages/dashboard/system/multilingual/translate_interface.php
> Avoid full path disclosure in translate_interface page

- concrete/single_pages/dashboard/users/add_group.php
...and fix a bug (see https://github.com/concrete5/concrete5/commit/f2a96bcf66d5cb25b18f60fd8f09f793b6c0e153)
> Avoid accessing undefined vars and array indexes in group add page

- concrete/blocks/image_slider/form_setup_html.php
- concrete/blocks/image_slider/view.php
I've added getString to the tabs so that more than one block gets displayed in composer view.
Using the blocks ID ($bID) I've updated the the javascript to only target the current block.
Converted remaining inputs to use view->field
> Fix image slider composer view #4390

- concrete/src/Page/Template.php
I'm not sure why it happens, but I get the following fatal error:
``usort(): Array was modified by the user comparison function`` with php 5.5.38
> Fix Page\Template::sort

- concrete/controllers/backend/user_interface.php
I'm not sure if this is intentional or not. If it was intentional, is this the right way to handle errors?
> Remove code potentially left from develop

- web/concrete/src/View/View.php
Backport of https://github.com/concrete5/concrete5/pull/4382
> [5.7] Fallback to viewPkgHandle if file not found for themePkgHandle

- concrete/js/build/core/app/alert.js
PS: javascript assets needs rebuilding if this PR is accepted
> Remove dialog DIV when dialog is closed

- README.md
This adds links to slack, irc and the forums.
> Add community channels to the readme

- concrete/blocks/core_area_layout/view.php
- concrete/src/Area/Layout/ThemeGridColumn.php
> Minor grid fixes.

- concrete/src/Page/Stack/Stack.php
PHP 7.0 won't work without this
> Make Stack::getByPath compatible with Page::getByPath

- concrete/bootstrap/helpers.php
- concrete/src/Database/EntityManager/Provider/AbstractPackageProvider.php
- concrete/src/Database/EntityManager/Provider/DefaultPackageProvider.php
- concrete/src/Foundation/ClassLoader.php
- concrete/src/Package/Package.php
- tests/tests/Core/Package/fixtures/package_upgrades/test_metadatadriver_annotation_default/controller.php
- tests/tests/Core/Package/fixtures/packages/test_metadatadriver_additional_namespace/controller.php
- tests/tests/Core/Package/fixtures/packages/test_metadatadriver_annotation_default/controller.php
- tests/tests/Core/Package/fixtures/packages/test_metadatadriver_annotation_default_core_extension/controller.php
- tests/tests/Core/Package/fixtures/packages/test_metadatadriver_xml/controller.php
- tests/tests/Core/Package/fixtures/packages/test_metadatadriver_yaml/controller.php
- tests/tests/Core/Package/fixtures/packages/test_not_installed_package/controller.php
- tests/tests/Core/Package/fixtures/packages/test_package_with_no_entities/controller.php
This swaps naming for newly created methods based on discussion in #4404.
> Update Package and ClassLoader based on discussion in #4403

- concrete/src/Foundation/ClassLoader.php
We were calling the wrong method here.
> Fix classloader package call

- concrete/src/Http/ResponseFactory.php
- concrete/src/Routing/RoutingServiceProvider.php
This fixes an untested path of code when maintenance mode is enabled.
> Fix maintenance mode

- concrete/blocks/image_slider/form_setup_html.php
A var keyword was mistakenly left out.
> add missing var

- concrete/single_pages/dashboard/extend/install.php
I have this strange error in PHP 5.5
```
usort(): Array was modified by the user comparison function
```
This workaround solves it
> Fix "usort(): Array was modified by the user comparison function"

- concrete/src/Controller/AbstractController.php
- concrete/src/Controller/ApplicationAwareControllerResolver.php
- concrete/src/Database/EntityManagerConfigFactory.php
- concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
- concrete/src/Foundation/Runtime/DefaultRuntime.php
- concrete/src/Foundation/Runtime/Run/CLIRunner.php
- concrete/src/Foundation/Runtime/Run/DefaultRunner.php
- concrete/src/Statistics/UsageTracker/AggregateTracker.php
- concrete/src/Url/Resolver/PathUrlResolver.php
Let's avoid duplicated code...
> Use ApplicationAwareTrait in all ApplicationAwareInterface classes

- composer.lock
Fixes [this problem](https://www.concrete5.org/community/forums/internationalization/database-error-on-reload-strings-multilingual) when MySQL runs in strict mode
> Upgrade the Translation Library

- concrete/src/Page/CustomStyle.php
> [v8] Corrected page custom style property / variable name.

- web/concrete/src/Page/Page.php
> [5.7] Fix check in out bug see #4521

- concrete/src/Page/Page.php
Fix check in out bug see #4521.
> [v8] Fix check in out bug see #4521

- web/concrete/blocks/core_stack_display/controller.php
> [5.7] Fix block styles in stacks.

- concrete/controllers/backend/editor_data.php
- concrete/controllers/backend/page.php
- concrete/controllers/panel/sitemap.php
- tests/tests/Core/Routing/CheckRoutesTest.php
This helps avoiding invalid route destinations like the one fixed in #4533
> Check that all route destinations are callable

- concrete/elements/custom_style.php
https://github.com/concrete5/concrete5/issues/4087
> Design & Custom Template > Advanced > Custom Class - add custom classes

- concrete/elements/files/properties.php
Ran into this in testing, figured it might be nice to have and it was easy enough to implement.
> Add tracked url to properties dialog and add anchor tags to both urls

- concrete/controllers/install.php
> Show language names in their language during install

- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
- concrete/src/Page/Controller/PageController.php
- concrete/themes/dashboard/view.php
Fix #4473
Please remark that I've had to add an optional "message is already in HTML" parameter to the `flash` system in order to avoid h() calls
> Express entity readd

- concrete/config/db.xml
- concrete/elements/block_header_view.php
- concrete/elements/custom_style.php
- concrete/src/Block/CustomStyle.php
- concrete/src/Entity/StyleCustomizer/Inline/StyleSet.php
- concrete/src/StyleCustomizer/Inline/StyleSet.php
- tests/tests/Core/StyleCustomizer/InlineStyleSetTest.php
https://github.com/concrete5/concrete5/issues/4449
**Changes:**
> add custom ID to blocks and custom layouts

- web/concrete/src/Foundation/EnvironmentDetector.php
> [5.7] Fix installation and CONCRETE5_ENV

- web/concrete/blocks/share_this_page/controller.php
> Fix #4616 for 7.x

- concrete/js/ckeditor4/core/ckeditor.css
https://github.com/concrete5/concrete5/issues/4183#issuecomment-258598097
> add padding to the inline CKEditor

- concrete/elements/page_controls_footer.php
> Missing t function of “Publish Now” button

- concrete/single_pages/dashboard/files/sets.php
> add sort text color

- concrete/src/Mail/Service.php
Currently there's no way to determine if we were able to send an email or not.
Let's return true/false so signal success or failure
> [V8] 	Return true/false from Mail\Service::sendMail

- concrete/src/Entity/File/Version.php
Adjusts the way thumbnails are generated when the source image has the _same_ width as the thumbnail size. 
With this change, a thumbnail is generated when:
- The source image is _equal to_ or greater than the thumbnail width
- But if it's equal to the width and there's no thumbnail height or the thumbnail height is greater than the image height, don't create the thumbnail  (as it's either the same size or there is nothing to crop).
Previous to this change you could have images that were exactly matching the width of the thumbnail, but taller than thumbnail (i.e. it would be useful to apply cropping selection) not having a thumbnail generated. 
An example use case might be a 1920x300 banner area for a website header. It would be common place to have as resources 1920 wide images, but …
> Adjustment of thumbnail creation logic

- web/concrete/src/Sharing/ShareThisPage/Service.php
Consider controller method when sharing pages
> BugFix https://github.com/concrete5/concrete5/issues/4182

- concrete/controllers/install.php
- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Http/Middleware/ThumbnailMiddleware.php
#4625 breaks installation. Let's fix this.
PS: relevant changes are [only these](https://github.com/concrete5/concrete5/commit/c7a5a942c5f3f125eefade0259e27f9788b00375?w=1)
> Fix installation

- web/concrete/src/Block/BlockController.php
> [V5.7] Fix #4658

- concrete/src/Block/BlockController.php
FIx #4658 for `develop` branch
> [V8] Fix #4658

- web/concrete/blocks/share_this_page/controller.php
with this change we can have a different link for the very same block
https://github.com/concrete5/concrete5/pull/4648
> [5.7] disable caching of share block

- concrete/blocks/share_this_page/controller.php
with this change we can have a different link for the very same block
https://github.com/concrete5/concrete5/pull/4652
> [v8] disable caching of share block

- concrete/controllers/page_types/core_stack.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Page/Controller/PageController.php
resolves #4629
This also makes it possible to return responses from a page controller's on_start method.
> Fix the core_stack page type

- concrete/src/Http/ResponseFactory.php
- concrete/src/Page/Controller/AccountPageController.php
- concrete/src/Page/Controller/PageController.php
This is a reapplication of #4495 to the release/8.0 branch
> Fix controller->replace functionality

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/registration/open.php
- concrete/controllers/single_page/register.php
- concrete/single_pages/dashboard/system/registration/open.php
> Readd manual approve

- concrete/blocks/image_slider/form_setup_html.php
Add in the form third option for navigation Type. **Arrows & bullets**. Example (Default template)
http://www.siton-systems.co.il/slider
Change in `view.php`:
#4688
> Image slider form.php:: add option For arrow + bullets

- composer.lock
> Upgrade Punic to v1.6.4

- concrete/src/Url/Resolver/CanonicalUrlResolver.php
This change got applied to develop and not to the release branch.
> Use the request to resolve the canonical url again.

- concrete/controllers/install.php
> Switch to APP_INSTALL_LANGUAGE only if it's not empty

- concrete/src/Session/SessionFactory.php
> Fix typo gc_maxlifetime

- concrete/src/Multilingual/Service/Extractor.php
- concrete/src/Package/Package.php
> Add getTranslatableStrings method to package controllers

- concrete/elements/header_required.php
Implements #4561
I also took the opportunity to clean the code of `header_required`: see every commit.
> Add support to hreflang alternate link tags

- concrete/views/panels/page/versions.php
> Add a translation context and a comment for a "for" alone

- concrete/config/app.php
- concrete/src/Application/Application.php
- concrete/src/File/Service/File.php
- concrete/src/Http/Client/Adapter/Curl.php
- concrete/src/Http/Client/Adapter/Socket.php
- concrete/src/Http/Client/Client.php
- concrete/src/Http/Client/Factory.php
- concrete/src/Http/Curl.php
- concrete/src/Http/HttpServiceProvider.php
- concrete/src/Updater/ApplicationUpdate.php
- concrete/src/Updater/Update.php
- concrete/tools/files/importers/remote.php
- tests/tests/Core/Http/HttpClientTest.php
#4743 take two
**Please hold on, I still have to review this PR**
> Add HTTP Client

- concrete/themes/dashboard/view.php
> Avoid accessing an undefined array index in dashboard/view.php

- concrete/single_pages/dashboard/users/groups/bulkupdate.php
> Avoid accessing undefined vars and array indexes in user groups bulk update

- concrete/controllers/single_page/dashboard/reports/forms/legacy.php
> Avoid accessing undefined vars and array indexes in legacy forms view

- concrete/src/Area/Area.php
- concrete/src/Area/GlobalArea.php
So we can do strict comparison `if ($a->getTotalBlocksInArea($c) === 0)` in our templates.
> Return an integer in getTotalBlocksInArea methods

- concrete/src/Editor/CkeditorEditor.php
This will add some docblocks and attempts to improve overall readability.
> Cleanup ckeditor class

- concrete/views/panels/details/page/caching.php
> Fix display of custom cache lifetimes

- concrete/elements/page_types/composer/controls/core_page_property/url_slug.php
`php-cs-fixer --config-file==<webroot>/.php_cs fix <filename>`
> Fix #1663 - change event of slug-creation to input

- concrete/elements/dashboard/welcome.php
> make welcome background image cover full width and height

- concrete/blocks/faq/form_setup_html.php
https://github.com/concrete5/concrete5/issues/4859
This pull request uses the same approach used here: https://github.com/concrete5/concrete5/pull/4482
Each entry gets a unique ID and on delete that ID is used to destroy the entry.
> FAQ delete entry fix

- concrete/single_pages/dashboard/system/multilingual/setup.php
- concrete/single_pages/dashboard/system/optimization/clearcache.php
These classes "pull-left" do nothing and may screw up styling
> Removed unneeded pull-left classes

- concrete/single_pages/dashboard/system/basics/social.php
- concrete/views/panels/details/page/location.php
There is a "column" (col-md-8) which makes the table fairly small and it hasn't got a row either. This makes it float and breaks designs.
- Sorry for the 2 commits that do nothing here. Not sure what I can do about that though, something got broken here and I don't know what/why.
> "Social Links" column fix

- concrete/single_pages/dashboard/pages/types/view.php
> match Delete Page Type modal buttons to other modals

- concrete/elements/permission/lists/tree/node.php
> match topics tree node permissions buttons

- concrete/elements/permission/detail.php
> match permissions modal buttons

- concrete/single_pages/dashboard/system/attributes/sets.php
> Attribute Sets - wrap Add Set button in dashboard form actions wrapper and add button classes

- concrete/single_pages/dashboard/system/optimization/jobs.php
- adds input text classes and removes inline width
- removes empty th and expands Reset Jobs cell
- add jobs modal cancel button
**Current:**
**Changes:**
> Automated Jobs

- concrete/controllers/single_page/dashboard/reports.php
- concrete/controllers/single_page/dashboard/users.php
> Use redirect in view, not constructor

- concrete/single_pages/dashboard/extend/install.php
> Avoid accessing an undefined variable in extend/install.php

- concrete/controllers/dialog/page/add_block.php
- concrete/views/dialogs/page/add_block.php
> Avoid accessing undefined vars in add_block dialog

- concrete/src/Block/BlockController.php
> Avoid accessing undefined property in BlockController::getBlockTypeHelp

- concrete/src/Entity/File/Version.php
Docs for File Version
also removed unused code
> Docs for File Version

- composer.lock
Changelog: https://github.com/Seldaek/monolog/releases/tag/1.22.0
> Upgrade Monolog to v1.22.0

- concrete/src/Entity/File/Version.php
- concrete/src/File/Image/Thumbnail/Path/Resolver.php
- concrete/src/File/StorageLocation/Configuration/DeferredConfigurationInterface.php
- tests/tests/Core/File/ImporterTest.php
This should resolve #4942 and help demystify what's happening in this class.
> Fix thumbnailer using relative paths

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/basics/accessibility.php
- concrete/elements/account/menu.php
- concrete/elements/footer_required.php
- concrete/single_pages/dashboard/system/basics/accessibility.php
> Allow hiding account menu

- concrete/elements/footer_required.php
See https://github.com/concrete5/concrete5/pull/4974 and https://github.com/concrete5/concrete5/commit/8447b6fec98725c7ac6c6bdab20e3371607de247
> display_account_menu instead of display_user_menu in comment

- concrete/src/Entity/File/Version.php
- concrete/src/File/Image/BasicThumbnailer.php
- tests/tests/Core/File/ImporterTest.php
Changes to thumbnails to make stuff work betterish.
> Work on Thumbnails

- concrete/src/Foundation/Environment.php
> Remove languages from list of core overrides

- concrete/tools/dashboard/sitemap_drag_request.php
> Avoid accessing undefined array indexes in sitemap_drag_request

- concrete/src/Application/Application.php
This PR fixes the same problem described in #3680
Fixes http://www.concrete5.org/developers/bugs/8-1-0/package-translations-not-working/
> Fix package localization for v8

- concrete/single_pages/dashboard/system/basics/editor.php
> remove extra hr element on Rich Text Editor page

- concrete/blocks/survey/controller.php
- concrete/blocks/survey/edit.php
> update Survey block form

- concrete/single_pages/dashboard/reports/surveys.php
> update Surveys dashboard page

- .github/PULL_REQUEST_TEMPLATE.md
The php-cs-fixer syntax changed between v1 and v2: let's update the pull requests template
> Update pull request template for php-cs-fixer v2

- concrete/views/panels/details/page/caching.php
> Page Caching - make Custom minutes input wider, min of 1, and a number input

- concrete/attributes/number/controller.php
> make number attribute width 100%

- concrete/elements/files/search_header.php
- concrete/js/build/core/file-manager/search.js
* Make sure that the folder name input is cleared before the dialog is shown 
* Have the folder name focus after the dialog in shown
> Fix #4834 

- concrete/authentication/concrete/controller.php
- concrete/src/Permission/Event/BanIPEvent.php
- concrete/src/Permission/IPService.php
...and upgrade code to the v8 style
> Add on_ip_ban event

- concrete/config/install/base/single_pages/dashboard.xml
... so that default children are the first ones.
Fix #5039
> Sort dashboard pages

- concrete/themes/dashboard/elements/header.php
> Remember dashboard scroll position

- concrete/src/Console/Application.php
- concrete/src/Console/Command.php
- concrete/src/Console/Command/ClearCacheCommand.php
- concrete/src/Console/Command/CompareSchemaCommand.php
- concrete/src/Console/Command/ConfigCommand.php
- concrete/src/Console/Command/ExecCommand.php
- concrete/src/Console/Command/GenerateIDESymbolsCommand.php
- concrete/src/Console/Command/InfoCommand.php
- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Console/Command/InstallPackageCommand.php
- concrete/src/Console/Command/JobCommand.php
- concrete/src/Console/Command/PackPackageCommand.php
- concrete/src/Console/Command/ResetCommand.php
- concrete/src/Console/Command/ServiceCommand.php
- concrete/src/Console/Command/TranslatePackageCommand.php
- concrete/src/Console/Command/UninstallPackageCommand.php
- concrete/src/Console/Command/UpdateCommand.php
- concrete/src/Console/Command/UpdatePackageCommand.php
> Add concrete5 abstract command

- concrete/themes/dashboard/elements/footer.php
Once closed, the dashboard panel starts closed on subsequent calls.
Let's fix this...
> Fix dashboard panel visibility

- concrete/js/build/core/sitemap/search.js
Wrong field key. See: \Concrete\Core\Page\Search\Field\Field\ParentPageField::getKey
> Fix unable to search pages from full sitemap

- composer.lock
- concrete/authentication/facebook/type_form.php
- concrete/composer.json
- concrete/config/app.php
- concrete/src/Application/Application.php
- concrete/src/Authentication/Type/Facebook/Factory/FacebookServiceFactory.php
- concrete/src/Authentication/Type/Google/Factory/GoogleServiceFactory.php
- concrete/src/Authentication/Type/OAuth/HttpClient.php
- concrete/src/Authentication/Type/OAuth/ServiceProvider.php
- concrete/src/Authentication/Type/Twitter/Factory/TwitterServiceFactory.php
- concrete/src/File/Exception/RequestTimeoutException.php
- concrete/src/File/Service/File.php
- concrete/src/Http/Client/Client.php
- concrete/src/Http/Client/Factory.php
- concrete/src/Http/HttpServiceProvider.php
- concrete/src/Marketplace/Marketplace.php
- concrete/src/Updater/ApplicationUpdate.php
- concrete/src/Updater/Migrations/Migrations/Version20170131000000.php
- concrete/src/Updater/Update.php
- concrete/tools/files/importers/remote.php
- tests/tests/Core/Http/HttpClientTest.php
What about merging `feature/http-client-service` into develop?
> Merge `feature/http-client-service` branch into develop

- concrete/authentication/facebook/type_form.php
- fix a couple of html errors
- add hints about Valid OAuth redirect URIs
- make it so it looks like the Twitter type_form
> Improve Facebook type_form

- composer.lock
- concrete/composer.json
- concrete/src/Entity/File/StorageLocation/StorageLocation.php
See #3729
Does it work?
~~Sure...?~~ Yes!
Nothing broke... :D
Reduce my filemanager load time from 10s->3s
> Implement Caching for Flysystem

- concrete/single_pages/dashboard/users/groups/bulkupdate.php
> Move Multiple Groups - set labels and make search full width

- concrete/src/File/ImportProcessor/AutorotateImageProcessor.php
- concrete/src/File/Importer.php
Autorotate image on upload based on Exif Metadata
> Autorotate image

- concrete/src/Attribute/AttributeInterface.php
- concrete/src/Attribute/Controller.php
Building a custom attribute type still is puzzling for developers. The documentation is limited and the code is undocumented.
Can we add an interface that would make it easier for developers to implement on?
This is a starting point. Suggestions are welcome.
> Add AttributeInterface class

- concrete/src/Filesystem/FileLocator.php
> FileLocator fixes for Windows 

- concrete/src/User/Search/Field/Field/IsValidatedField.php
- concrete/src/User/Search/Field/Manager.php
- concrete/src/User/UserList.php
Added a new filter option to the advanced search. It works exactly the same as filter by isActive field. Now it is possible to see unvalidated users.
> Add possibility to see unvalidated users in the user search

- concrete/controllers/dialog/search/advanced_search.php
- concrete/elements/search/customize_results.php
- concrete/src/Entity/Search/Query.php
- concrete/src/File/FolderItemList.php
- concrete/src/Search/AbstractSearchProvider.php
This PR resolves ticket #5051.
> Add "Number of Results" dropdown to customize search results

- concrete/src/Http/ResponseFactory.php
Plus some other sugest for ResponseFactory class
> Fix unable to use mobile theme

- concrete/elements/search/customize_results.php
- concrete/src/Search/AbstractSearchProvider.php
This PR resolves ticket #5142.
> Editing Advanced Search doesn't show currently selected results number

- concrete/src/Console/Command/ExecCommand.php
In #5111 I added by mistake a call to a non existing method
> Fix CLI Exe command

- concrete/src/User/UserInfo.php
Use our nice new secure way to generate strings for reset passwords
https://hackerone.com/reports/209761
> Switch to generating more secure random passwords

- tests/README.md
I followed my instructions and nothing blew up.
> Update tests readme with how to run them.

- concrete/src/User/Group/Group.php
`getGroupDateTimeEntered` needs only the user ID, so what about letting it accept integers too?
> Let Group::getGroupDateTimeEntered accept user IDs

- concrete/src/Http/Middleware/CookieMiddleware.php
Fix for issue https://github.com/concrete5/concrete5/issues/5193
> Add directory to cookie clear/set in cookie middleware

- concrete/blocks/page_list/page_list_form.php
- concrete/single_pages/dashboard/users/search.php
> Added some missed t-functions

- concrete/authentication/concrete/controller.php
- concrete/authentication/concrete/required_password_upgrade.php
> Fix global password reset

- concrete/attributes/date_time/controller.php
Added placeholder for the DateTime Text input
Formatted as short date/time
> Added placeholder for the DateTime Text input

- concrete/src/User/UserList.php
Let's speed up the userlist a bit by avoiding facade calls
> Avoid facade calls in UserList

- build/Gruntfile.parameters-sample.js
- build/README.md
- build/tasks/build-release/translations.js
- build/tasks/translations.js
> Build script: switch from Transifex to Community Translation

- concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
We have a method to set the oauth binding code, but we currently can't know if a user is already bound with an oauth account: let's add it
> Add an option to get the oauth binding associated to a user

- concrete/attributes/date_time/type_form.php
> Fix saving date/time attribute type

- concrete/src/Service/Configuration/HTTP/NginxGenerator.php
As discussed in Slack with @KorvinSzanto
> Faster nginx rewrite rule

- concrete/src/Block/BlockController.php
An implementation of https://github.com/concrete5/concrete5/pull/5225 that does not break compatibility
> Block types: allow saving NULL values v2

- concrete/jobs/index_search_all.php
- concrete/src/Search/Index/DefaultManager.php
Fix some typos to make indexing work better
> Fix some minor typos to make indexing work

- concrete/src/User/UserInfo.php
This fixes a bug introduced in my badly resolved merge conflict of #5232
> Fix creation of default values in UserInfo

- concrete/src/Validation/CSRF/Token.php
See [here](https://github.com/concrete5/concrete5/pull/4855/#issuecomment-291008831) for an explanation (thanks @Mnkras for spotting this)
> Revert detection order of token value

- concrete/src/Block/View/BlockViewTemplate.php
> Fix typo in BlockViewTemplate::computeView

- concrete/controllers/backend/tree/node.php
> Avoid accessing undefined array indexes in tree node backend controller

- concrete/tools/sitemap_overlay.php
> Avoid accessing an undefined array index in sitemap_overlay tool

- concrete/src/Block/Block.php
> Avoid accessing a potentially undefined property in Block::getBlockID

- concrete/controllers/single_page/members/directory.php
> Avoid accessing an undefined array index in members directory controller

- concrete/src/Page/Desktop/DesktopList.php
> Avoid accessing an undefined index in DesktopList::getMyDesktop

- concrete/elements/dashboard/reports/forms/header.php
> Avoid accessing undefined vars in dashboard/reports/forms/header

- concrete/src/Page/View/PageView.php
- concrete/src/View/ErrorView.php
Using Travis to test because I don't have nightly locally :(
* LSP issue in not declaring a default value in an overridden method in a child class
> Get ahead of PHP 7.2 issues

- concrete/src/Attribute/StandardSetManager.php
See https://github.com/concrete5/concrete5/issues/5277 for details
@aembler can you verify this is the right solution?
> Fix https://github.com/concrete5/concrete5/issues/5277

- concrete/controllers/install.php
- concrete/controllers/single_page/dashboard/system/basics/multilingual/update.php
- concrete/src/Console/Command/InstallLanguageCommand.php
- concrete/src/Localization/Service/TranslationsChecker.php
- concrete/src/Localization/Service/TranslationsInstaller.php
As discussed with @KorvinSzanto on Slack
> Split TranslationsUpdater in TranslationsChecker and TranslationsInstaller

- concrete/config/concrete.php
> Use HTTP instead of HTTPS to install/update languages

- concrete/config/concrete.php
- concrete/src/Express/Entity/Listener.php
- concrete/src/Updater/Migrations/Migrations/Version20170406000000.php
Fixes #5305 including a migration
> Remove tables for deleted Entities

- build/tasks/build-release/clean.js
- concrete/src/Page/Collection/Collection.php
- concrete/src/Support/i18n.php
> Translate VERSION_INITIAL_COMMENT

- concrete/single_pages/dashboard/system/mail/method.php
- concrete/src/Form/Service/Form.php
As [suggested](https://github.com/concrete5/concrete5/pull/5243#issuecomment-293403392) by @KorvinSzanto 
I also noticed that in #5233 I left some code I used to test the autocompletion disabler
> Improve autocompletion

- concrete/single_pages/dashboard/system/registration/authentication.php
> Avoid accessing an undefined var in system/registration/authentication

- concrete/controllers/single_page/dashboard/system/permissions/site.php
> Avoid accessing undefined vars in system/permissions/site

- concrete/elements/date_time/duration.php
Tool tip for date_time/duration element
> adding tool tip to duration date time element

- concrete/config/concrete.php
- concrete/src/Cache/Driver/FileSystemStashDriver.php
See https://github.com/tedious/Stash/issues/350 for more info
Lines 51 through 59 are my own, the rest is straight from stash.
> Fix edge case where opcache in stash caused a fatal

- concrete/controllers/single_page/dashboard/pages/templates.php
- concrete/controllers/single_page/dashboard/pages/templates/add.php
https://hackerone.com/reports/221385
> Fix H1 221385

- concrete/blocks/express_entry_detail/controller.php
- concrete/blocks/express_entry_list/controller.php
- concrete/controllers/single_page/dashboard/system/express/entities.php
- concrete/elements/dashboard/express/detail_navigation.php
- concrete/elements/dashboard/express/entries/header.php
- concrete/elements/dashboard/express/menu.php
- concrete/single_pages/dashboard/express/entries.php
- concrete/single_pages/dashboard/express/entries/create.php
- concrete/single_pages/dashboard/express/entries/update.php
- concrete/single_pages/dashboard/express/entries/view_entry.php
- concrete/single_pages/dashboard/system/express/entities.php
- concrete/single_pages/dashboard/system/express/entities/associations/add.php
- concrete/single_pages/dashboard/system/express/entities/associations/view_association.php
- concrete/single_pages/dashboard/system/express/entities/view_details.php
- concrete/src/Entity/Express/Entity.php
- concrete/src/Express/Association/Formatter/AbstractFormatter.php
- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
https://hackerone.com/reports/221325
> Fixes for H1 #221325

- concrete/single_pages/dashboard/pages/feeds.php
- concrete/src/Entity/Page/Feed.php
https://hackerone.com/reports/221380
> Fix H1 221380

- concrete/controllers/dialog/block/cache.php
https://hackerone.com/reports/221323
> Fix H1 221323

- concrete/src/Updater/Migrations/AbstractMigration.php
> Regenerate all entities to keep foreign keys

- concrete/config/concrete.php
- concrete/config/site.php
- concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- concrete/single_pages/dashboard/system/multilingual/setup.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Multilingual/Service/Detector.php
> Fix multilingual home redirection

- concrete/src/File/Type/Type.php
Update based on the suggestions of @KorvinSzanto.
https://github.com/concrete5/concrete5/pull/5342#discussion_r112032077
> Update supportsThumbnails() method

- concrete/blocks/page_attribute_display/controller.php
Remove some debug code I mistakenly added to  #5368
> Remove debug code from page_attribute_display

- concrete/controllers/dialog/block/design.php
> Avoid accessing an undefined var in dialog/block/design controller

- concrete/controllers/panel/detail/page/permissions.php
> Avoid accessing undefined array indexes in page permissions panel

- concrete/src/Entity/File/StorageLocation/StorageLocation.php
- concrete/src/Filesystem/FlysystemCache.php
Not sure if this is how we want to fix it, but it works,
> Fix #5328 (maybe)

- concrete/src/File/Image/BasicThumbnailer.php
This should fix the coding style tests
> Fix BasicThumbnailer coding style

- concrete/src/Localization/Translator/Adapter/Zend/Translation/Loader/Gettext/PackagesTranslationLoader.php
- concrete/src/Package/PackageService.php
> Fix get available packages

- concrete/config/install/app.php
- concrete/controllers/install.php
- concrete/views/frontend/install.php
Let's update the Country list in the *Advanced Options* of the installation procedure if the selected language changes
> Installation: update Country list upon language change

- concrete/elements/form/composer.php
- concrete/elements/page_types/composer/controls/core_page_property/date_time.php
- concrete/elements/page_types/composer/controls/core_page_property/description.php
- concrete/elements/page_types/composer/controls/core_page_property/name.php
- concrete/elements/page_types/composer/controls/core_page_property/page_template.php
- concrete/elements/page_types/composer/controls/core_page_property/publish_target.php
- concrete/elements/page_types/composer/controls/core_page_property/url_slug.php
- concrete/elements/page_types/composer/controls/core_page_property/user.php
- concrete/src/Attribute/Context/ComposerContext.php
- concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php
- concrete/src/Page/Type/Composer/FormLayoutSetControl.php
This is user experience issue.
Let's add "Required" label if the composer form control is marked as "Required".
> Display "Required" labels on composer form

- concrete/controllers/backend/page.php
> Avoid accessing undefined variable in page backend controller

- concrete/attributes/topics/controller.php
> Avoid accessing undefined vars in Topics attribute view/controller

- concrete/blocks/switch_language/controller.php
- concrete/blocks/switch_language/templates/flags/view.php
- concrete/blocks/switch_language/templates/flags_set_default/view.php
- concrete/blocks/switch_language/view.php
> Switch language block with single pages

- web/concrete/js/build/vendor/redactor/redactor.js
> [5.7] Fix Redactor issue with Chrome 58

- concrete/tools/files/import.php
> Avoid accessing an undefined array index in tools/files/import

- concrete/blocks/topic_list/view.php
> Avoid accessing an undefined var in view of topic_list block

- concrete/src/Tree/Node/Type/Category.php
> Avoid accessing an undefined array index in Tree/Node/Type/Category::getTreeNodeJSON

- concrete/src/Search/Field/Field/KeywordsField.php
> Avoid accessing an undefined array index in KeywordsField

- concrete/blocks/video/form_setup_html.php
> Avoid accessing undefined vars in blocks/video/form_setup_html

- concrete/src/Search/AbstractSearchProvider.php
> Avoid accessing an undefined array index in AbstractSearchProvider

- concrete/elements/search/customize_results.php
> Fix html errors and PHP warnings in elements/search/customize_results

- concrete/blocks/video/controller.php
> Avoid accessing undefined variables and array indexes in block video controller/view

- concrete/src/Utility/Service/Validation/Numbers.php
- tests/tests/Core/Utility/Service/Validation/NumbersTest.php
This pull request lets users check if a number is within a range, as well as offering a function to determine if a variable is numeric (that is, integer or float).
> Improve number validation helper

- concrete/src/Permission/Access/ListItem/EditUserPropertiesUserListItem.php
> Avoid accessing undefined properties in EditUserPropertiesUserListItem

- concrete/src/Page/Collection/Version/Version.php
- tests/tests/Core/Page/PageTest.php
> Rescan collection paths only if the collection handle is updated

- concrete/single_pages/dashboard/system/permissions/antispam.php
> Spam Control - add missing form class

- concrete/src/Service/Detector/HTTP/ApacheDetector.php
Fix https://www.concrete5.org/developers/bugs/8-1-0/urls-and-redirection-and-apache-2.4.10/
> Improve detection of Apache server

- concrete/tools/permissions/dialogs/access/entity/types/group_combination.php
- concrete/tools/permissions/dialogs/access/entity/types/group_set.php
> replace Group Set and Group Combination PNG icons with Font Awesome

- concrete/single_pages/dashboard/system/multilingual/setup.php
> Multilingual Setup - add dashboard form actions wrapper for "Save Settings" button

- concrete/tools/files/permissions.php
> Protect with Password - make input full width

- concrete/attributes/topics/controller.php
- concrete/attributes/topics/form.php
- concrete/attributes/topics/type_form.php
- concrete/src/Entity/Attribute/Key/Settings/TopicsSettings.php
- concrete/src/Updater/Migrations/Migrations/Version20170425000000.php
I've created a new branch from recent develop branch and picked reviewed commits from #5386
> Re: Allow to choose single select mode for topic type attribute

- concrete/src/Foundation/Queue/DatabaseQueueAdapter.php
The DatabaseQueueAdapter returns `false` when it successfully creates a new queue: it should return `true`.
I took the opportunity to "modernized" the code.
> Fix queue adapter

- concrete/config/concrete.php
- concrete/src/Updater/Migrations/Migrations/Version20170513000000.php
Before we had the foreign key fix in place if you attempted to delete a file it left it in an in-consistent state, (shown as Unknown in the file manager) this cleans those up.
> Remove invalid (Unknown) files from the file manager

- concrete/src/Notification/View/NewPrivateMessageListView.php
https://hackerone.com/reports/238271
> Fix https://hackerone.com/reports/238271

- concrete/single_pages/dashboard/system/express/entities/forms/view_form.php
- concrete/src/Entity/Express/Control/TextControl.php
https://hackerone.com/reports/230278
> Fix https://hackerone.com/reports/230278

- concrete/src/Console/Command/InstallCommand.php
This makes it a little less painful to install via CLI
* If you enter invalid data, it will ask you to try again
* It validates database data as you enter it
* It validates passwords in a better way
* The final yes or no requires an actual answer
With these changes, you can enter your valid database details and just hold enter to be alerted to things that are required and don't have a default.
> Make install via cli better

- composer.lock
- concrete/composer.json
Currently composer.lock forces installing monolog 1.5.0 (it's 4 years old!)
> Update monolog in composer.lock

- composer.lock
The changes are:
```
Package operations: 0 installs, 17 updates, 0 removals
- Updating symfony/class-loader (v3.2.7 => v3.3.2): Loading from cache
- Updating symfony/routing (v3.2.7 => v3.3.2): Loading from cache
- Updating symfony/debug (v3.2.7 => v3.3.2): Loading from cache
- Updating symfony/polyfill-mbstring (v1.3.0 => v1.4.0): Loading from cache
- Updating symfony/http-foundation (v3.2.7 => v3.3.2): Loading from cache
- Updating symfony/event-dispatcher (v3.2.7 => v3.3.2): Loading from cache
- Updating symfony/http-kernel (v3.2.7 => v3.3.2): Loading from cache
- Updating league/flysystem (1.0.37 => 1.0.40): Loading from cache
- Updating symfony/serializer (v3.2.7 => v3.3.2): Loading from cache
- Updating filp/whoops (2.1.8 => 2.1.9): Loading from cache
- Updating …
```
> Update our composer dependencies

- concrete/config/concrete.php
- concrete/controllers/install.php
- concrete/controllers/single_page/dashboard/system/seo/urls.php
- concrete/single_pages/dashboard/system/seo/urls.php
- concrete/src/Application/Application.php
- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Entity/Site/Site.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Updater/Migrations/Migrations/Version20170614000000.php
- concrete/src/Url/Resolver/CanonicalUrlResolver.php
- concrete/views/frontend/install.php
- tests/tests/Core/Routing/URLTest.php
Fix #5556 
Let's rename *SSL Canonical URL* to *Alternative Canonical URL*
> Rename SSL Canonical URL to Alternative Canonical URL

- concrete/src/Updater/Migrations/Migrations/Version20170407000001.php
This may fix [this reported error](https://github.com/concrete5/concrete5/issues/5562#issuecomment-310436386).
> Disable foreign key checks in migration 20170407000001

- concrete/single_pages/dashboard/system/express/entities/edit.php
- concrete/single_pages/dashboard/system/express/entities/view_details.php
- concrete/src/Entity/Express/Entity.php
https://hackerone.com/reports/229401
> Fix H1 #229401

- concrete/css/build/core/account.less
- concrete/css/build/core/app/components.less
- concrete/css/build/core/app/search-v8.less
- concrete/css/build/core/app/search.less
- concrete/css/build/core/file-manager.less
- concrete/css/build/core/image-editor/image-editor.less
- concrete/css/build/themes/dashboard/welcome/rss-displayer.less
- concrete/css/build/vendor/selectize/plugins/remove_button.less
- concrete/elements/files/add_to_sets.php
- concrete/single_pages/dashboard/system/conversations/settings.php
- concrete/single_pages/dashboard/system/files/thumbnails.php
- concrete/views/panels/details/page/attributes.php
- concrete/views/panels/details/page/caching.php
- concrete/views/panels/details/page/location.php
This pull request makes minor changes to the dashboard UI.
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
**Current:**
**Changes:**
> Minor UI fixes

- concrete/elements/attribute/key/header.php
> Format translation of "Delete Attribute" for javascript

- concrete/attributes/express/controller.php
- concrete/attributes/express/form.php
- concrete/attributes/rating/controller.php
- concrete/attributes/rating/form.php
- concrete/attributes/telephone/controller.php
- concrete/attributes/telephone/form.php
This PR is for adding the missing form templates for attributes that allow user's to customise attribute output.
> added missing form templates for express customisation

- composer.lock
- concrete/controllers/single_page/dashboard/system/registration/authentication.php
- concrete/single_pages/dashboard/system/registration/authentication.php
- concrete/single_pages/login.php
- concrete/single_pages/login_oauth.php
- concrete/src/Authentication/AuthenticationType.php
- concrete/src/Package/ItemCategory/AuthenticationType.php
- concrete/src/Support/i18n.php
> Translate Authentication Type names

- concrete/elements/block_footer_edit.php
- concrete/elements/block_header_edit.php
> Avoid warnings in block edit header/footer

- concrete/bootstrap/configure.php
> Fix installation when no default time zone is defined

- concrete/js/build/core/app/search/base.js
- concrete/js/build/core/sitemap/sitemap.js
- concrete/src/Search/Pagination/View/ConcreteBootstrap3PagerTemplate.php
> Avoid loading URLs of disabled pagination links

- concrete/controllers/install.php
- concrete/controllers/single_page/dashboard/system/basics/timezone.php
- concrete/src/Console/Command/InstallCommand.php
- concrete/src/Database/Connection/Timezone.php
- concrete/src/Foundation/Runtime/Run/DefaultRunner.php
- concrete/src/Package/StartingPointPackage.php
- concrete/views/frontend/install.php
- tests/tests/Core/Foundation/Runtime/Run/DefaultRunnerTest.php
This is done both in the web and in the CLI install procedures.
> Ask and check the system time zone during install

- concrete/elements/pages/search.php
Page search could potentially show xss if a page name contained malicious code.
> Fix potential xss in page search

- concrete/controllers/single_page/login.php
> Fix URL after logout, avoid permanent redirects

- concrete/controllers/install.php
That's what #5648 should have been
> Simplify a translatable string, really

- concrete/blocks/express_entry_list/view.css
- concrete/blocks/express_entry_list/view.php
**Current:**
- If "Enable Search" is checked and at least one "Enable Searching by Attributes" attribute is checked, the form search fields are displayed, but without a way to submit the form.
- When a submit "Search" button is added, and a search does not return a result, the text 'No "X" entries can be found' and the "Search" button are displayed. A follow-up search cannot be done, requiring users to navigate back to the previous page.
**Changes:**
- A "Search" button is added. 
- When a search does not return a result, the form fields are displayed and additional searched can be made.
**Current:**
- When a keyword search returns a result, the "Advanced Search" fields can be toggled.
- If the keyword search does not return a result, the "Advanced Search" fields cannot be toggled. …
> Express Entry List block search

- concrete/controllers/install.php
This fixes a bug introduced in #5625 that prevented install via the web interface (!)
> Fix check of database time zone

- concrete/src/Page/Collection/Version/Version.php
- concrete/src/Page/Page.php
> Be sure to save integer values in Pages.cInheritPermissionsFromCID

- concrete/controllers/dialog/search/advanced_search.php
- concrete/src/Express/Search/SearchProvider.php
- concrete/src/File/Search/SearchProvider.php
- concrete/src/Page/Search/SearchProvider.php
- concrete/src/Search/ProviderInterface.php
- concrete/src/User/Search/SearchProvider.php
https://github.com/concrete5/concrete5/pull/5649/commits/8f16f3a5de387b5be8fb78a5cba414e3968c31fe
> Fix custom class in general code (save search preset) 

- concrete/src/Search/Column/Set.php
> Fix Column Set wakeup

- web/concrete/blocks/switch_language/controller.php
- web/concrete/blocks/switch_language/templates/flags/view.php
Port for the 5.7 series of #5630
> [5.7] SEO-friendly flags template for Switch Language block

- composer.lock
- concrete/composer.json
- concrete/src/Permission/IPService.php
- concrete/src/Session/SessionValidator.php
> Support IP zone ids

- concrete/blocks/next_previous/controller.php
This is quick request for Next and Previous block.
We had an occasion that we wanted to retrieve page objects so that we can get thumbnail attribute and etc. So it would be nice to pass page objects from controller to views.
Thanks.
> Next Previous: Passing page objects to view

- concrete/src/Search/Field/Group.php
- concrete/src/Search/Field/GroupInterface.php
- concrete/src/Search/Field/Manager.php
- concrete/src/Search/Field/ManagerInterface.php
See https://github.com/concrete5/concrete5/pull/5670#issuecomment-313708917
> Add some methods to search field interfaces

- concrete/controllers/single_page/dashboard/system/express/entities/forms.php
- concrete/single_pages/dashboard/system/express/entities/forms/view_form.php
> Disabling deletion of default express forms

- concrete/attributes/address/controller.php
- concrete/src/Attribute/ObjectTrait.php
> Fix address attribute in certain situations

- concrete/src/Conversation/Editor/Editor.php
Hi concrete5 Team,
This is my proposed solution for https://hackerone.com/reports/248523. 
Seems it resolves problem as issue is no longer reproducible. Let me know what you think.
Regards,
bl4de
> Proposed fix for H1 report 248523

- concrete/controllers/single_page/account/messages.php
Hi guys,
This is proposed fix for H1 report https://hackerone.com/reports/247517
The issue is no longer reproducible with this change.
Regards,
bl4de
> Fix for H1 247517 report

- concrete/src/User/Group/Group.php
Hi concrete5 Team,
This is my proposition of fix for https://hackerone.com/reports/247521
Regards,
bl4de
> Fix for H1 247521 report

- concrete/elements/express/form/form/form.php
- concrete/elements/express/form/view/form.php
Hi Guys,
This is fix for https://hackerone.com/reports/248506
Issue is no longer reproducible after this change
Regards,
bl4de
> Fix for H1 report 248506

- concrete/blocks/express_entry_detail/edit.php
- concrete/blocks/express_form/form.php
- concrete/single_pages/dashboard/system/express/entities/forms.php
- concrete/single_pages/dashboard/system/express/entities/forms/view_form.php
Hi Guys,
This is fix for https://hackerone.com/reports/248504 for both admin and website.
The issue is no longer reproducible.
Regards,
bl4de
> Fix for H1 report 248504

- concrete/single_pages/dashboard/pages/feeds.php
Hi Guys,
This is fix for https://hackerone.com/reports/248133.
The issue is no longer reproducible.
Regards,
bl4de
> Fix for H1 report 248133

- concrete/blocks/page_list/auto.js
- concrete/blocks/page_list/page_list_form.php
- concrete/blocks/page_list/tools/preview_pane.php
Added a pagelist.topictree.select event when a topic is selected.
Then update the auto.js to bind that event to reload the preview window
#5721
> Pagelist update so the topic tree choice affects the preview pane

- concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
> Use original handle if no mapping was specified

- concrete/src/Notification/View/Menu/WorkflowProgressListViewMenu.php
Since the `Archive` word alone has multiple meanings (verb, noun), it can have multiple translations. Let's state that it's a verb.
> Define 'Archive' as a verb in WorkflowProgressListViewMenu

- .appveyor.yml
- README.md
- tests/tests/Core/Block/BlockViewTemplateTest.php
- tests/tests/Core/Database/EntityManagerClassLoaderTest.php
- tests/tests/Core/Filesystem/FileLocatorTest.php
- tests/tests/Core/Filesystem/TemplateLocatorTest.php
- tests/tests/Core/Style/StyleTest.php
I know many people developing for concrete5 under Windows (myself for one :wink:).
So, what about running tests under Windows too?
This would also help fixing https://github.com/concrete5/concrete5/issues/5185 (if the core team wants to do that).
Here's a sample output of an AppVeyor build: https://ci.appveyor.com/project/mlocati/concrete5
> Test under Windows with AppVeyor

- concrete/src/Entity/Express/Entry/OneAssociation.php
- concrete/src/Express/Association/Applier.php
- concrete/src/Express/ObjectBuilder/FieldsetBuilder.php
- concrete/src/Express/ObjectBuilder/FieldsetBuilderAssociationControl.php
- tests/tests/Core/Express/AssociationApplierTest.php
Big rework of the express association applier to fix a number of bugs and orphaned data; Adding tests for this functionality.
> Fix #5363; Close #5674; Fix #5758; Add express association tests

- concrete/blocks/form/auto.js
Added missing semicolon (consistency) at the end of line 188
> Update concrete/blocks/form/auto.js:188 - Add missing semicolon
