concrete/src/Form/Service/Widget/DateTime.php
(supersedes #5017) Currently, the "date" widget isn't initialized with the current value: its initial value is always "today".
Credits to @manielsen2002 for pointing this out!
=> Fix date widget

concrete/blocks/page_attribute_display/controller.php
The controller currently ignores custom templates because of the type specific templates for date_time and boolean.  Change the code to see if there is a custom template and don't execute render() if there is allowing the base view() to do the job.
=> Update controller to not ignore Custom Templates

concrete/config/concrete.php, concrete/config/install/base/single_pages/dashboard.xml, concrete/controllers/single_page/dashboard/system/files/thumbnails/options.php, concrete/single_pages/dashboard/system/files/thumbnails.php, concrete/single_pages/dashboard/system/files/thumbnails/options.php, concrete/src/File/Image/BasicThumbnailer.php, concrete/src/File/Image/Thumbnail/ThumbnailerInterface.php, concrete/src/Updater/Migrations/Migrations/Version20170131000000.php, tests/tests/Core/File/Service/ImageTest.php
`BasicThumbnailer` always generated thumbnails in the JPEG format.
This PR fixes the following problems with that:
- the file extension of the thumbnails is always the same as the one of the original image (that could lead to some problems / misunderstandings)
- we loose the transparency, leading to problems like the one [described here](https://www.concrete5.org/developers/bugs/8-1-0/resizingconstraining-images-with-transparent-backgrounds-causes-/)
This pull requests fixes these problems by:
- allowing saving in JPEG or in PNG format (so that transparency is kept)
- the file extension of the thumbnails is `.jpg` for JPEG files and `.png` for PNG files
Currently, this PR doesn't change the behavior: thumbnails are always created in JEPG format. BTW, we can change that by setting the …
=> Thumbnail fixes

composer.json, composer.lock, concrete/composer.json, tests/tests/Core/FilesParseTest.php
This allows us to leave `concrete5/concrete5` a type "package" so that we can continue as we are and not be disrupted by any composer restructuring. By having a composer file in `/concrete`, we can automatically split out that directory into its own git repository with its own tags. By doing that, we can ALSO use the `composer/installers` effort that @Remo and @olsgreen and others were working on to great effect and move forward with concrete5 being fully composer installable.
I [opened a PR](https://github.com/composer/installers/pull/339) over with composer installers to add the `concrete5-core` type and set up [an example subtree split based on this branch](https://github.com/KorvinSzanto/concrete5-core).
Some surface level benefits of having this subtree split:
* We can include …
=> Separate composer.json into two files

composer.json, composer.lock
For users such as myself running PHP7+ composer update by default uses the currently running version to resolve dependencies. This wonderful setting sets it to use php 5.5.9 regardless of the running environment
=> Set Composer PHP version

concrete/src/Entity/File/Version.php
A user on the forum reported that using an SVG image caused errors when upgrading from 8.0.3 to 8.1.0.
"after upgrading my site from 8.0.3, where everything works fine, to 8.1.0 i got the following error on every page, including dashboard:
Call to a member function getSize() on boolean"
https://www.concrete5.org/community/forums/installation/error-after-upgrade-from-8.0.3-to-8.1.0/
I was able to reproduce the error when uploading SVG images through the file manager.
**Steps to reproduce:**
- upload an SVG image in the file manager
- this will trigger an "Upload Failed" error modal with the filename and `Call to a member function getSize() on boolean` error
- close the error modal
- refresh the page
- the SVG image is uploaded and listed, but has a size of 0.00 KB
When an SVG image is …
=> SVG images - do not generate thumbnail if getImagineImage() returns false

concrete/blocks/page_list/view.php
* Remove deprecated `Loader`
* Add html comment to show closing tag
* Fix indent lines
* Simplify using external links
* Get the page owner instead of the author of initial version
* Use second option of `getAttribute` (because most designer don't use `is_object()`)
* Remove example of image attribute (because default template use thumbnail attribute)
=> Refactor default template of page list block

concrete/src/Site/Service.php
=> Fix default site installed with wrong plural form

concrete/src/Localization/Translator/Adapter/Zend/Translation/Loader/Gettext/SiteTranslationLoader.php
Since v8, user can translate site interface by default. Why don't we enable loading site interface translation by default?
Note: Please merge this PR after merging #5073.
=> Load site interface translation by default

concrete/js/ckeditor4/core/concrete5styles/plugin.js
`PageTheme::getThemeEditorClasses` is backward compatible with Redactor, but CKEditor has more useful options. Let's make it enable to use them.
Ref: http://docs.ckeditor.com/#!/guide/dev_styles
=> Make it enable to define CKEditor style set from Page Theme

composer.lock
This fixes an edge case when concrete5 installation may break.
See https://github.com/punic/punic/releases/tag/1.6.5
=> Upgrade Punic to v1.6.5

.gitignore
These are project files generated by IntelliJ IDE, they should be ignored to avoid erroneous commits.
=> Ignore .iml files from IntelliJ IDE

concrete/blocks/tags/controller.php, concrete/blocks/tags/tag_form.php, concrete/blocks/tags/view.php, concrete/themes/elemental/css/build/blocks/tags.less
https://www.concrete5.org/community/forums/customizing_c5/get-selected-tag-on-tag-block-for-page-list-filtering/
The selected tag on tag filtered pages will receive the "ccm-block-tags-tag-selected" class. In the Elemental theme the selected tag has a change to its border color.
**Changes:**
_selected tag_
_selected tag and tag hover_
=> Tags block - add class to selected tag on tag filtered pages

concrete/blocks/share_this_page/view.php
https://www.concrete5.org/community/forums/usage/share-this-page-open-in-new-window/
Based on the behavior of the default widgets from Twitter, Facebook, and Google, share links should open in a new window.
=> Share This Page block - open links in new window

concrete/src/Console/Command.php, concrete/src/Console/Command/ClearCacheCommand.php, concrete/src/Console/Command/CompareSchemaCommand.php, concrete/src/Console/Command/ConfigCommand.php, concrete/src/Console/Command/ExecCommand.php, concrete/src/Console/Command/GenerateIDESymbolsCommand.php, concrete/src/Console/Command/InfoCommand.php, concrete/src/Console/Command/InstallCommand.php, concrete/src/Console/Command/InstallPackageCommand.php, concrete/src/Console/Command/JobCommand.php, concrete/src/Console/Command/PackPackageCommand.php, concrete/src/Console/Command/ResetCommand.php, concrete/src/Console/Command/ServiceCommand.php, concrete/src/Console/Command/TranslatePackageCommand.php, concrete/src/Console/Command/UninstallPackageCommand.php, concrete/src/Console/Command/UpdateCommand.php, concrete/src/Console/Command/UpdatePackageCommand.php
When running CLI commands it's often useful to see where an error occurred.
What about adding support to show the file where the exception occurred (`-v` option) and the stack trace (`-vv` option)?
=> Enable printing exception details in CLI commands

concrete/elements/files/properties.php, concrete/src/File/Type/Type.php
This pull request checks to see if the file has the mime type of image/svg+xml before getting thumbnails, displaying the Thumbnail form row and Rescan button, and displaying a thumbnail error. It is based on this pull request https://github.com/concrete5/concrete5/pull/5069 being merged first.
**Current:**
**Changes:**
=> SVG thumbnails and "Invalid file dimensions, please rescan this file." error

concrete/themes/concrete/background_image.php
The check in the elseif is correct (concrete.white_label.background_url), only the config item that is used (concrete.urls.background_url) is different. (line 82-84)
=> Show white_label background when needed

concrete/src/Antispam/Library.php
Our custom antispam library can't be saved in `/dashboard/system/permissions/antispam/saved`. In this class we are using `Facade`, but we aren't importing it.
=> import facade in antispam library

composer.lock
This fixes only an `E_NOTICE` warning thrown by the previous version of the Translation Library
=> Update Translation Library

concrete/src/Form/Service/Validation.php, tests/tests/Core/Form/Service/ValidationTest.php
ErrorList#containsField check does not works when check input data with form validation service.
=> Form Validation Service: add field name to errors

concrete/controllers/single_page/dashboard/users/search.php, concrete/single_pages/dashboard/users/search.php, concrete/tools/workflow/dialogs/user_details.php
Changed the way user attributes are displayed on the user page and in the workflow user review pop-up dialog. Now the order is the same as on the attribute page, and with attribute set headers.
=> Display user attributes in set order

concrete/controllers/dialog/search/advanced_search.php, concrete/controllers/search/file_folder.php
This PR adds to #5147 
Presets are saved on the session so the "Number of Results" dropdown already selects what was set on the preset.
=> Saving preset on session so items per page are shown on customised search

concrete/src/User/UserInfo.php
For example if you want to reset it to a random string and make it so that a user can actually type it in a reasonable amount of time...
=> Allow variable length when resetting user password

concrete/controllers/dialog/search/advanced_search.php, concrete/controllers/search/file_folder.php, concrete/js/build/core/app/search/base.js, concrete/src/Search/AbstractSearchProvider.php, concrete/src/Tree/Node/Node.php
* Hides "Reset Search" link when a preset is loaded.
* Populates "Number of Results" from preset or session, in this order. 
* Presets are not loaded into the session.
=> Fixes for File Search presets

concrete/src/Entity/File/StorageLocation/StorageLocation.php
Resolves an issue when moving files between locations and it thinking it already exists.
This will invalidate the old cache, oh well
=> Use a FSL ID as a cache key for flysystem

concrete/blocks/core_conversation/form.php
This string wasn't clear about what the code expects: an attribute with a Rating name or an attribute of type Rating.
Furthermore, avoid re-translating it: let's keep the current translation of the Rating attribute type.
=> Specify that the attribute to create is a Rating type

concrete/src/Backup/ContentImporter/Importer/Routine/ImportGroupsRoutine.php
If we import this XML:
```xml
<?xml version="1.0"?>
<concrete5-cif version="1.0">
<groups>
<group name="Test" />
</groups>
</concrete5-cif>
```
The group `Test` will always be created, even if it already exists.
=> Fix import of groups without path

composer.json
Composer automatically adds to the PATH variable the `concrete/vendor/bin` directory, so we can call the scripts in it without specifying the folder.
This also implies that we can avoid duplicating script definitions for posix and Windows.
I had to remove the `--colors` option in the `phpcs` script, because PHP on Windows doesn't support VT100 control codes (well, from PHP 7.2 it will, thanks to [this contribution of mine](https://github.com/php/php-src/pull/2103) :wink: )
=> Simplify composer scripts

concrete/src/Utility/Service/Text.php, tests/tests/Core/Utility/Service/TextTest.php
The html generated by the current `autolink` method always uses the http protocol, even if the source text is something like `https://example.com`.
Let's improve `autolink`:
1. if the source text contains a protocol, use it
2. if the source text does not contain a protocol, allow users to specify their preferred protocol (fallsback to http)
3. let's hide the protocol from the link text
=> Fix autolink text helper

concrete/src/User/Search/Field/Manager.php
In the advanced user search pop-up the user attributes were not sorted and displayed in the order of creation. This will sort the attributes by the sets also adding the set names to the list (Core properties, Set 1, Set 2, ..., Other Attributes).
Cleaned up version of PR.
=> Display attributes by sets in the advanced user search

concrete/src/Authentication/Type/OAuth/HttpClient.php
The HTTP Client introduced a bug that could prevent OAuth working.
=> Fix OAuth client

concrete/src/Updater/Migrations/Migrations/Version20170313000000.php
This should fix this strange error:
```
'update Pages set siteTreeID = 0 where ptID in (?, ?) or cFilename = ?'
with params ["core_stack_category", "core_stack", "\/!stacks\/view.php"]:
SQLSTATE[22007]: Invalid datetime format:
1292 Truncated incorrect DOUBLE value: 'core_stack_category'
```
=> Fix stacks migration

concrete/elements/header_required.php
After #4974 we can now disable the account menu.
BTW the `core/account` asset is still included in the output asset list, and we always call the `ccm_enableUserProfileMenu` javascript function.
Theme developers can inhibit the inclusion of `core/account` by calling `ResponseAssetGroup::get()->markAssetAsIncluded('core/account')`.
That causes that the `ccm_enableUserProfileMenu` javascript function may not be defined: so let's call it only if it's available.
=> Call ccm_enableUserProfileMenu only if it's defined

concrete/src/Application/Service/Dashboard.php
If the current view has the `dashboard` theme, `Dashboard::inDashboard` always returns true, even if it receives a path/page that's not in dashboard.
So, let's check first the passed parameters, and only after the current view/page.
This fixes for instance this problem:
1. in the authentication dashboard pages, we show OAuth callback URLs containing `index.php` since the current page is a dashboard page
2. when we build the callback URLs during the authentication process, they are without `index.php` since the current page is the login page
=> Fix detecting if a page is in dashboard

concrete/src/Application/Service/Dashboard.php
Currently, the "Quick Search" on the toolbar's right side provides results in the same language as the site is in. Instead, this should be in the system language (i.e. the language set to the logged in user account OR in case not set, system default).
=> Display quick search results in 'system' locale

concrete/controllers/frontend/assets_localization.php, concrete/src/Asset/Asset.php
I keep getting errors like
```
Refused to execute script from
'https://www.example.com/ccm/assets/localization/jquery/ui/js'
because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
Let's:
1. return Response instances from the `assets_localization.php` methods
2. greatly improve the performance of `assets_localization.php` by calling `json_encode` only on dictionaries instead of single strings
3. update the Asset method that retrieves the content of dynamic routes by:
3.1 taking in account the case when a route returns a Response instead of printing out some text directly
3.2 creating the route controller instead of performing static calls
=> Better localized assets responses

concrete/controllers/single_page/dashboard/system/express/entities.php
We cant clone null
```
199 $entity = Express::getObjectByHandle($handle); // returns null if the given handle is not exists
234 $previousEntity = clone $entity;
```
=> Fix enable to edit express entity handle

concrete/controllers/single_page/members/profile.php, concrete/src/Http/ResponseFactory.php, concrete/src/Page/Controller/PublicProfilePageController.php
https://github.com/concrete5/concrete5/pull/4495 only considers the case when the `replace` method is called in the `on_start` method. Let's allow calling it in controller tasks too.
An example of why this is needed: be sure to not be logged in and browse to https://translate.concrete5.org/members/profile
=> Fix replace not in on_start

concrete/src/Mail/Service.php
1. We may use SMTP, not only `mail()`: let's avoid writing references to `mail()`
2. Let's log if an email has been successfully sent or not
=> Better mail log message

concrete/attributes/boolean/controller.php, concrete/src/Attribute/Controller.php, concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php, concrete/src/User/UserInfo.php
In case users registered with OAuth, we don't have a way to set the default attribute values.
What about this approach?
Fix #5223
=> Create users with default attribute values when using authentication

concrete/authentication/community/controller.php, concrete/authentication/community/hook.php, concrete/authentication/community/hooked.php, concrete/single_pages/account/edit_profile.php, concrete/src/Authentication/AuthenticationType.php
In the user's profile, we always present a link to bind oauth accounts.
BTW, if a user is already bound to an account via oauth, I'd avoid it.
Here's for instance what changes for a user already bound to concrete5 account:
Before:
After:
=> Fix authentication type links in user's profile

concrete/controllers/single_page/dashboard/users/search.php, concrete/src/User/Search/SearchProvider.php
When listing users with the `SearchProvider` (not as `admin`), we currently build a query like this:
```sql
SELECT distinct (u.uID)
FROM Users u
LEFT JOIN UserSearchIndexAttributes ua ON u.uID = ua.uID
LEFT JOIN UserGroups ugRequired ON ugRequired.uID = u.uID
WHERE ((ugRequired.gID IN (-1, 3, 4, 5, 6, 7)) OR (ugRequired.gID IS NULL))
AND (u.uIsActive = 1)
AND (u.uIsValidated != 0)
ORDER BY u.uDateAdded
```
When MySQL runs in strict mode (`ONLY_FULL_GROUP_BY` flag), since the order by field is not in the selected results, we have this error:
```
Expression #1 of ORDER BY clause is not in SELECT list,
references column 'u.uDateAdded' which is not in SELECT list;
this is incompatible with DISTINCT
```
To fix this issue, we need to switch to a query like this:
```sql
SELECT u.uID
FROM Users u …
```
=> Fix users query when filtering accessible groups

concrete/src/Search/ItemList/Database/ItemList.php
If one tries to clone a PageList object, both instances will still reference to the same `$query` object. This PR will fix that problem.
=> Clone query object in ItemList class

concrete/controllers/single_page/dashboard/users/points/assign.php
When trying to assign community points to a user at `/dashboard/users/points/assign/` an Exception is thrown.
The controllers save() method calls an non existent UserInfo method: getByUserID()
=> Update dashboard/users/points/assign.php: The controllers save() method calls an non existent UserInfo method: getByUserID()

concrete/attributes/express/controller.php
concrete/attributes/express/controller.php was missing a searchForm function that led to a bug when searching for a user by an express object.
=> add searchForm method to express attributes ctrlr

web/concrete/controllers/search/users.php
This fixes a user list SQL query issue that was solved for v8 with this PR but left unsolved in 5.7x so far.:
https://github.com/concrete5/concrete5/pull/5245
It addresses a Issue with sorting and distinct, When MySQL runs in strict mode (ONLY_FULL_GROUP_BY flag), since the order by field was not in the selected results, we got this error when trying to view the User List as a non-Superuser:
`An exception occurred while executing 'SELECT distinct (u.uID) FROM Users u LEFT JOIN UserSearchIndexAttributes ua ON u.uID = ua.uID LEFT JOIN UserGroups ugRequired ON ugRequired.uID = u.uID WHERE (ugRequired.gID in (-1,3,4,6,31,32)) OR (ugRequired.gID is null) ORDER BY u.uDateAdded desc LIMIT 10 OFFSET 0': SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, …
=> fix users list query when filtering accessible groups

concrete/src/Http/RequestBase.php, concrete/src/Http/ResponseFactory.php, concrete/src/Http/Service/Ajax.php, concrete/src/Validation/CSRF/Token.php
When an ajax call fails, showing the message "Invalid form token. Please reload this form and submit again." doesn't make much sense, since 99.99% of ajax calls are not for form submissions.
So, what about detecting if the call was an ajax call and show a message like "Invalid token. Please reload the page and retry." in that case?
I also took the opportunity to:
1. fix the phpdocs of the Token class
2. avoid deprecated methods
3. centralize the detection of ajax calls in the Request instance
4. move the ccm_token string to a constant
=> Token helper: avoid deprecated methods and detect ajax calls

concrete/src/Localization/Localization.php
We currently wipe out all the expensive cache when we clear the Localization cache.
What about clearing only the [ZendCacheDriver](https://github.com/concrete5/concrete5/blob/589e3193e40766574b82f61947cde4bb4b1c4280/concrete/src/Cache/Adapter/ZendCacheDriver.php)-related files?
@ahukkanen Do you see any drawback?
=> Clear only the Zend cache when flushing the localization cache

concrete/jobs/index_search.php, concrete/jobs/index_search_all.php
Fixes #5264
also `index()` is a void function so changed the returns to breaks
The increments are obviously numbers, so use number formatting
=> Don’t clear the entire table when doing incremental updates

concrete/src/Localization/LocalizationServiceProvider.php
The current definition of localization-related services is quite odd (but other service providers have the same problem).
For instance, the output of this code:
```php
function checkSame($a, $b) {
echo "$a === $b ? ", Core::make($a) === Core::make($b) ? 'yes' : 'no', "\n";
}
checkSame('helper/localization/countries', 'helper/localization/countries');
checkSame('Concrete\Core\Localization\Service\CountryList', 'Concrete\Core\Localization\Service\CountryList');
checkSame('helper/localization/countries', 'localization/countries');
checkSame('helper/localization/countries', 'Concrete\Core\Localization\Service\CountryList');
checkSame('localization/countries', 'Concrete\Core\Localization\Service\CountryList');
```
is currently:
```
helper/localization/countries === …
```
=> Fix localization-related singletons

concrete/src/Utility/Service/Number.php
Let's avoid the warning `A non well formed numeric value encountered`
Ref: #4723
=> Avoid warnings in Number::getBytes()

concrete/bootstrap/process.php
The definition of $step has been removed in [this commit](https://github.com/concrete5/concrete5/commit/be61564211174434206cb5cbdcc1951001eb2911#diff-36329fa02654b9d4b96bc7ecc8a36269L12).
Ref: #4723
=> Remove references to undefined $step in bootstrap process.php

concrete/src/Tree/Node/Node.php
`$populateMissingChildren` is undefined: maybe `$loadMissingChildren` should be used instead?
=> Fix Tree\Node::selectChildrenNodesByID

concrete/src/Entity/Express/Entry.php, concrete/src/Entity/Express/Entry/Association.php, concrete/src/Express/Association/Applier.php
Express currently saves associations by finding the first one with a matching inverse property handle. This currently breaks things because we end up resolving the wrong association when property handles are not unique. This pull request instead uses the association instance to find the entry association object.
Now there are still issues in the core where we have behavior that is still based on unique property handles. I'm not sure how best to handle those. You can find them in the core by searching for `->getAssociation\([^\)]` in PHPStorm.
=> Make saving associations work when handles are not unique

concrete/single_pages/dashboard/system/registration/authentication.php, concrete/single_pages/dashboard/users/add.php, concrete/src/Form/Service/Form.php
Browsers automatically complete forms with usernames and password.
This is often handy, but sometimes may be problematic.
For instance, in the authentication type forms, we don't want that the browser insert the account username and password in AppID and AppSecret fields.
What about the approach of this PR?
[tested and working on Chrome, Firefox, Internet Explorer, Edge]
=> Disable autompletion

composer.lock, concrete/composer.json, concrete/src/Foundation/ClassLoader.php
Moving autoloading into composer allows us to offload the file IO intensive aspect of autoloading to the `composer install` command instead of searching the filesystem every request. Doing this [speeds up my user search page by ~20%](https://blackfire.io/profiles/compare/726936d0-9a44-4867-bf92-9623b3c7a58f/graph).
=> Use composer to autoload our PSR4 stuff

concrete/src/Multilingual/Service/Detector.php, concrete/src/Page/Controller/AccountPageController.php, concrete/src/Page/Controller/DashboardPageController.php, concrete/src/Page/Controller/PageController.php
User's account pages (those available at `/account/...` path) should use the user's language, not the site one.
What about adding a method to the page controllers to decide about that? This way, custom pages may control this behavior as well.
=> Let page controllers decide about page language

concrete/src/Page/Search/Field/Field/ParentPageField.php
Let's include system pages on page search when the parent id is in system page area.
=> Page Search: include system pages when parent id is also a system page

concrete/composer.json
Let's allow installing monolog versions greater that 1.5 (but still with it as per semver specs).
=> Fix minimum requirements for monolog

concrete/src/Http/Middleware/ThumbnailMiddleware.php
In concrete5 5.7, there was a bug that allowed for SVG images to be displayed using the Image block. The image would be displayed as a picture element with multiple duplicate srcset attributes. In concrete5 v8, using SVG images in the Image block triggers an error.
https://www.concrete5.org/community/forums/submitting-to-the-marketplace/svg-issue-notify-existing-stucco-users-or-hurry-up-to-fix-and-re/
**Errors:**
=> Prevent errors when SVG images are used with the Image block

concrete/src/File/Type/Type.php
I mistakenly left out GIF when creating the supportsThumbnails() method.
=> add GIF to supportsThumbnails()

concrete/blocks/page_attribute_display/controller.php
In the page_attribute_display block type, when we handle date/time attributes, we [currently get the display value](https://github.com/concrete5/concrete5/blob/c72a0fe3ae4d1839487606d81c47cdb07ea8d2f2/concrete/blocks/page_attribute_display/controller.php#L95), but we need the full representation of the DateTime value in order to correctly format it.
=> Fix display of date/time attributes

concrete/blocks/html/controller.php
Changing the needle regex as shown has decreased Stack loading time when editing pages by an order of magnitude: it was **~47 seconds** before (above the `max_execution_time` set in `php.ini`, causing server errors, HTTP code 500); after applying this fix the XHR completes in **~3 seconds**.
A web designer working on a site I support emailed me panicked that Stacks were not loading; after doing some investigation, I found that the server had started throwing server errors (`PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /example/path/to/website/concrete/blocks/html/controller.php on line 89`) when editing pages, specifically when GET-ting `/ccm/system/panels/add?cID=2468&tab=stacks` via XHR.
To give credit where credit is due, [Alan …
=> Increase regex performance in in HTML block controller method xml_highlight()

concrete/src/Entity/Attribute/Value/Value/AbstractValue.php, concrete/src/Entity/Attribute/Value/Value/ImageFileValue.php, concrete/src/Entity/Attribute/Value/Value/Value.php, concrete/src/Updater/Migrations/Migrations/Version20170407000001.php
This fixes a bunch of issues where people can't delete things because of foreign key constraints.
Basically (if you don't know what the cascade does) we tell the DB to delete any associated data.
This Fixes #5275
@KorvinSzanto This allows the deletion of attributes on entities that had values (the ID attribute)
=> Make it so that we can delete Entities and stuff related to entities

concrete/blocks/image/add.php, concrete/blocks/image/composer.php, concrete/blocks/image/controller.php, concrete/blocks/image/db.xml, concrete/blocks/image/edit.php, concrete/blocks/image/form.php, concrete/blocks/image/view.php, concrete/src/Updater/Migrations/Migrations/Version20170408000000.php
- limits the image hover effect to size constrained images
- adds optional image cropping to constrained images
When adding an image using the Image block, it will display as an `img` or `picture` depending on whether the image size has been constrained. Size constrained images display as img and unconstrained images display as picture. 
The type of image element displayed plays a role when selecting a second image to use for the image hover effect. The image hover effect only works with img elements and does not work with picture elements. This is due to picture elements having a fallback src attribute and multiple srcset attributes that are more involved to modify than img elements. To address this, image hover only works when an image has been size constrained.
To …
=> Image block - fix image hover and add image cropping

concrete/src/File/Image/BasicThumbnailer.php, concrete/src/File/Image/Thumbnail/Type/CustomThumbnail.php, concrete/src/Http/Middleware/ThumbnailMiddleware.php
Store thumbnail paths for files generated in /cache/
Does not work for files not in the filemanager, so those aren't stored, (there is an `@todo` in there)
tested by using the image block and setting different widths, rows were added and thumbnails generated.
@KorvinSzanto look good to you?
=> Use the resolver to track cache thumbnails

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/optimization/clearcache.php, concrete/single_pages/dashboard/system/optimization/clearcache.php, concrete/src/Application/Application.php, concrete/src/Cache/Cache.php, concrete/src/Cache/CacheClearer.php, concrete/src/Cache/CacheServiceProvider.php, concrete/src/Cache/FlushableInterface.php, concrete/src/Cache/Page/PageCache.php, concrete/src/File/Image/BasicThumbnailer.php
This moves cache flushing into its own service in a backwards compatible way and makes it possible to exclude thumbnails from being cleared when cache gets cleared.
=> Make thumbnail cache clearing optional

concrete/controllers/frontend/jobs.php, concrete/jobs/index_search_all.php, concrete/src/Job/QueueableJob.php
This makes it possible to track your jobs a little more closely, and makes it so that jobs running from the command line are able to resume.
This resolves #5272 
> output from a mostly fixed search_index job is always Indexed 0 Pages, 0 Users, 0 Files, and 1 Sites. (only when run via queue)
=> Improve queueable job functionality

concrete/blocks/desktop_waiting_for_me/view.php
Now we can't edit /account/welcome page with an error. This PR will fix it.
```
Error thrown with message "Call to undefined method Concrete\Core\Notification\View\UserSignupListView::showControls()"
Stacktrace:
#28 Error in /Users/hissy/Repositories/concrete5/concrete/elements/block_header_view.php:14
#27 include in /Users/hissy/Repositories/concrete5/concrete/src/Block/View/BlockView.php:268
#26 Concrete\Core\Block\View\BlockView:renderViewContents in /Users/hissy/Repositories/concrete5/concrete/src/View/AbstractView.php:151
#25 Concrete\Core\View\AbstractView:render in /Users/hissy/Repositories/concrete5/concrete/src/Area/Area.php:873
#24 Concrete\Core\Area\Area:display in /Users/hissy/Repositories/concrete5/concrete/single_pages/desktop.php:7
#23 include in …
```
=> Do not use $view in block template to avoid conflict with elements

concrete/jobs/index_search_all.php
I think 50 is a good size for this, any input?
This resolves #5272 
> We index 1 item in the queue at a time, we should probably increase this as the time to make the ajax call is significantly longer than it takes to process 1 item.
=> Add a queue batch size to the index_search_all job

concrete/single_pages/dashboard/blocks/stacks/view.php
Fixes #5196 by hiding the usage button on global areas (for now)
=> Hide the usage button on global areas (for now)

concrete/blocks/youtube/view.php
If the related videos checkbox is left unchecked, the REL argument is not used and Youtube assumes it to be set at 1 which defies the purpose.
This fixes that and ensures rel always got a value.
=> Youtube block not respecting the related video setting

concrete/src/Localization/Service/CountryList.php
We often need the list of Countries where a language is spoken (for instance during installation or when adding a new multilanguage section).
We currently list all the Countries where a language is spoken by someone, even if the language is not the official one for a Country (so, for instance, for English we also have Italy listed - because 34% of population can somehow understand and speak English).
Let's limit the list to the Countries where a language is the official (or de facto official) one.
=> Limit the Countries where a language is spoken

concrete/src/Cache/CacheClearer.php
This resolves the exception some get:
```php
FilesystemIterator::__construct(/Users/andrewembler/git/armymwr/web/application/files/cache): failed to open dir: No such file or directory
```
=> Catch exception when cache directory doesn't exist

CHANGELOG.md, concrete/src/Application/UserInterface/Menu/Item/Item.php
Ref: #4723
I guess it's too late to add protected properties, so we need to check them with `isset`...
=> Avoid accessing undefined properties in Menu Item

concrete/config/app.php, concrete/controllers/dialog/language/update/details.php, concrete/controllers/single_page/dashboard/system/basics/multilingual/update.php, concrete/single_pages/dashboard/system/basics/multilingual/update.php, concrete/src/Localization/Translation/Local/Stats.php, concrete/src/Localization/Translation/Remote/CommunityStoreTranslationProvider.php, concrete/src/Localization/Translation/Remote/Stats.php, concrete/views/dialogs/language/update/details.php
What about showing details of installed/available languages?
This PR adds a link to the language names:
If clicked, this dialog is shown:
This is useful to:
1. see the location of the language file
2. debug potential issues when determining the correct version of the language files
3. show the power of the new translation system :wink:
=> Show details of installed/available languages

concrete/src/Session/SessionValidator.php, concrete/src/User/User.php
When user agent or ip address of the user changed, session validator clears session storage. This is nice feature for prevent session fixation attack, but the message "This user is inactive." is wrong. The user is not changed to inactive. I think "Your session has expired." message is correct for this situation.
=> Fix wrong message when the session invalidated

concrete/elements/files/add_to_sets.php
When the fileset dialog is open in the file manager and we add a new fileset, clicking on the "-" button to remove it only removed the add-on that says "Public set".
This tiny fix removes the whole row as it should be
=> Filemanager fileset dialog fix

concrete/jobs/index_search.php, concrete/jobs/index_search_all.php
This resolves #5272 
>  if we fix the above, search_index does not remove items from the search index once they have the attribute applied
This deleted any indexed page where the following is true:
* The page is indexed
* The page is one of:
* The page is inactive (`cIsActive = 0`)
* The page has exclude from search set to true
=> Make it possible for the search indexer to remove pages from the index

concrete/controllers/panel/page/check_in.php, concrete/elements/dashboard/welcome.php
If the `concrete.misc.require_version_comments` is set to `true`, we require that page versions have comments.
If the user specifies an empty comment (or a comment with spaces only), we have a `Concrete\Controller\Panel\Page\Response` class does not exist exception. Let's fix this.
We also need to specify comments when saving the dashboard welcome page: let's add them.
=> Required comments fixes

concrete/views/panels/details/page/permissions/advanced.php
This fixes a Javascript issue where jQuery would close the wrong top element causing advanced permissions to no longer be changed after modifying 2 pages.
In reference to issue #3321
The javascript would close the top jQuery but when u change permissions several times it would cause the javascript to close the wrong top element and then jQuery would replace the wrong element. This element could never be submitted so it always failed.
=> fix for advanced permissions

concrete/src/File/Image/Thumbnail/Path/Resolver.php
There is a race condition when saving after generating a thumbnail the race is as follows:
Cache is cleared/page has never been visited
User 1 Visits site
User 2 Visits site
Resolver for user 1 sees no thumbnail in cache table
Resolver for user 2 sees no thumbnail in cache table
Generate thumbnail for user 1
Generate thumbnail for user 2
Insert into DB info for thumbnail generated by user 1
Insert into DB info for thumbnail generated by user 2
User 2 gets a duplicate key exception.
This fixes it by hiding the exception under the rug.
=> Catch the duplicate exception when generating thumbnail cache

concrete/blocks/search/form_setup_html.php
This pull request moves the "Beneath Another Page" page selector from out of the radio label.
**Current:**
**Changes:**
=> Search block form tweak

concrete/blocks/core_conversation/controller.php, concrete/blocks/core_conversation/form.php
- Saves the enableTopCommentReviews checkbox value. Currently the value is not saved.
- Capitalizes the "Aggregate Ratings by Attribute" label.
=> Conversation block - save enableTopCommentReviews checkbox value

concrete/src/File/Image/BasicThumbnailer.php
Thanks to @TimDix for bringing this up
We were fataling when trying to generate a thumbnail for non-file-manager thumbnails which is a regression
We also threw a warning if we tried to stat a remote file.
=> Fix generating thumbnails for non-file-manager files

concrete/src/Mail/Service.php
Currently we can only add `File` entities to the emails sent from concrete5.
What about implementing a way to add other kinds of attachments?
=> Add addRawAttachment method to mail service

concrete/src/User/Search/Field/Field/GroupSetField.php, concrete/src/User/UserList.php
Fix #5427
I had to add a way to look for users that belong to **at least one** of the groups in the set (calling the existing `filterByGroup` method would have required that users must belong to **all** the groups in the set).
For that reason, I added the new `filterByInAnyGroup` method.
=> Fix search users by group set

concrete/src/Permission/Access/NotifyInNotificationCenterNotificationAccess.php
Ref: #4723
`$db->GetRow` always returns an array (if no record found, it's an empty array): let's switch to `$db->fetchAssoc` (that returns false if no record is found)
=> Avoid accessing an undefined array index in NotifyInNotificationCenterNotificationAccess::getAccessListItems

concrete/config/concrete.php, concrete/config/db.xml, concrete/controllers/single_page/dashboard/blocks/stacks.php, concrete/src/Localization/Locale/Service.php, concrete/src/Page/Stack/Stack.php, concrete/src/Updater/Migrations/Migrations/Version20170505000000.php
- Fixes breadcrumb in dashboard when viewing global areas
- Fixes error when trying to add a localized stack
- Removes unused siteTreeID column from Stacks table in db.xml, adds migration.
- Fixes bug where no permissions were applied to new multilingual home page when creating new multilingual section.
This is orthogonal to #5075 but and #5035 but they are related and both are now resolved (though not specifically with this.)
=> Multilingual stack/setup fixes

concrete/src/Foundation/Runtime/Boot/DefaultBooter.php, concrete/src/Foundation/Runtime/Run/DefaultRunner.php
In version 7, we could override session handler like this:
https://github.com/hissy/scaling-concrete5/tree/master
However, we couldn't because core creates `User` instance before loading `bootstrap/app.php`.
If we move `setSystemLocale()` method from Booter to Runner, we can do it even in v8.
https://github.com/hissy/scaling-concrete5/tree/v8
However, I'm not sure the place of running `setSystemLocale` in Runner.
=> Make it enable to override session handler

concrete/blocks/image/controller.php, concrete/blocks/image/view.php, concrete/src/File/Type/Type.php
This pull request adds basic SVG support to the Image block.
- The SVG is displayed in an img element with the additional class of "ccm-svg".
- Size constraining and image hover are not supported.
Because of the variability in how SVG images are displayed in different browsers (and if the SVG has width/height attributes), custom sizing of the SVG should be handled using CSS. This would ideally be done by adding a custom class to the Image block (using Custom Class in Design & Custom Template) and then selecting the child img element. I will explain this and include an example in the Editors documentation.
Also, a minor change to the alt attribute was made. If an alt attribute is not set, then the file title is used.
=> add SVG support to the Image block

concrete/blocks/core_conversation/form.php
- Displays the Custom Date Format input field conditionally. It currently displays at all times.
- Adds formatting help text.
- Makes the input label more specific.
**Current:**
**Changes:**
=> Conversation block form - display the Custom Date Format input conditionally

concrete/blocks/image_slider/form_setup_html.php
When a slide has been reordered multiple times, it will pull to the left edge of the form modal. Adding position relative to the slide's parent fixes this.
**Current:**
**Changes:**
=> Image Slider sortable fix

concrete/src/View/View.php
A good way to replicate the issue that I faced is to create a singlepage that sets $view. Essentially the issue was that the first include could mess with scope variables before the second include fired.
=> Separate scopeitems into an isolated context so that they dont effect eachother

concrete/blocks/faq/LICENSE.TXT, concrete/blocks/faq/add.php, concrete/blocks/faq/controller.php, concrete/blocks/faq/db.xml, concrete/blocks/faq/edit.php, concrete/blocks/faq/form_setup_html.php, concrete/blocks/faq/view.php
This pull request updates the FAQ block:
- entries can be collapsed and dragged to reorder
- when an entry is collapsed, the Navigation Link Text becomes the entry label
- the missing LinkAbstractor translate methods were added
- Core:make() and Database::connection() were replaced with $app->make()
- the database methods were updated
- existing code was formatted and indented
In an attempt to keep a concise commit history, I mistakenly condensed too many changes into too few commits.
**Current:**
**Changes:**
=> FAQ block update

concrete/src/Entity/File/Version.php, concrete/src/File/Type/Inspector/ImageInspector.php
I tried to rescan a file with this simple script.
```php
Route::register('/test', function() {
$f = Concrete\Core\File\File::getByID(16); // sunset.jpg
$fv = $f->getApprovedVersion();
$resp = $fv->refreshAttributes();
});
```
This refreshed file is sunset.jpg in elemental_full starting point package. The size of this image is only 447.31 KB. Amazingly, this scripts will allocate 49.1MB memory!
This change will avoid loading same image on memory repeatedly, and reduce 19% memory usage on refreshing file versions.
https://blackfire.io/profiles/compare/6ff77e4a-d709-4687-8ac3-a1bb698e0094/graph
=> Reduce memory usage on rescan file version

concrete/src/Http/DefaultDispatcher.php
When concrete5 receives a request that satisfy one of the configured routes, but with a method that doesn't match the configured ones (eg if we receive a `POST` request but the route only allows `GET` requests), we have an unhandled exception.
Let's consider this case as if the route didn't match.
=> Handle invalid methods for valid routes

concrete/src/Tree/Node/Node.php
Installing concrete5 fails with the following error message:
`Call to a member function getRequestData() on null`
=> Fix Tree\Node populateDirectChildrenOnly when there's no tree

concrete/src/Entity/File/File.php
This is important for database integrity.
We currently have an issue where if anywhere in the file-deletion process, something throws an exception, then we end up with a database in an in-consistent state (for example, a file with no file-versions). Wrapping this code in a transaction solves this by rolling back if an exception is thrown. The roll back will NOT reverse the deletion of files on disk.
I tested this by throwing exceptions throughout the delete method and seeing that database entries still existed.
=> Wrap file deletion in a transaction

concrete/css/build/core/app/inline-toolbar.less, concrete/elements/block_area_header_view.php, concrete/elements/block_header_view.php, concrete/elements/custom_style.php, concrete/src/Area/CustomStyle.php, concrete/src/Block/CustomStyle.php, concrete/src/Entity/StyleCustomizer/Inline/StyleSet.php, concrete/src/StyleCustomizer/Inline/StyleSet.php, concrete/src/Updater/Migrations/Migrations/Version20170519000000.php, tests/tests/Core/StyleCustomizer/InlineStyleSetTest.php
- adds a free-form element attribute input to blocks, custom layouts, and areas
- adds the custom ID input to areas (currently it is only added to blocks and custom layouts)
A common use case for these changes will be for creating anchor links and adding data attributes.
As a working example, the following site uses the pull request code to add data attributes to blocks, custom layouts, and areas for controlling page animation.
http://cea.stellar.software/index.php.
The Custom Element Attribute input has basic validation. To prevent duplicate class and ID attributes from being added, it strips them before saving. If there are odd numbers of quotes (double or single), an error is thrown.
Notes on behavior:
- areas
- while in edit mode, Custom ID and Custom Element …
=> Custom Element Attribute and Custom ID

concrete/blocks/image/controller.php, concrete/blocks/image/db.xml, concrete/blocks/image/form.php
https://github.com/concrete5/concrete5/issues/5450
I believe this existing migration should handle the changes to the Image block table: https://github.com/concrete5/concrete5/blob/develop/concrete/src/Updater/Migrations/Migrations/Version20170421000000.php#L18
**Current:**
**Changes:**
I have tested the code changes, but would appreciate additional eyes to make sure I haven't overlooked something.
=> add Link to File option to the Image Block

concrete/tools/files/replace.php
**Current:**
**Changes:**
The approach used for spacing the input and buttons should allow for the button to accomodate more or less text and stay on one line.
**Example:**
=> File Manager Replace modal - make inputs and buttons use the full width available

concrete/single_pages/dashboard/system/seo/urls.php
https://github.com/concrete5/concrete5/issues/5499
- places the URL Redirection warning above the URL Redirection checkbox
- changes the Separate SSL URL text input placeholder text to "https://domain.com" from "http://domain.com"
**Current:**
**Changes:**
=> URLs and Redirection - warning and placeholder

concrete/src/Logging/LogEntry.php
There was a typo in the Font Awesome class used for critical and alert level icons.
**Current:**
**Changes:**
=> Logs - add icon to critical and alert levels

concrete/src/File/FileServiceProvider.php, concrete/src/File/Service/VolatileDirectory.php, tests/tests/Core/File/Service/VolatileDirectoryTest.php
What about a new helper class that automatically creates a new (empty) temporary directory and self-destroys it when it's no more used?
Example:
```php
// Create a new temp directory
$virtualDirectory = \Core::make(\Concrete\Core\File\Service\VolatileDirectory::class);
// Work on that directory
file_put_contents($virtualDirectory->getPath() . '/test.file', 'sample');
// Delete the temp directory
unset($virtualDirectory); // or simply exist the current function
```
=> Add VolatileDirectory

concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
Let's set to NULL the invalid file authors (otherwise the relationship between file authors and users is broken)
=> Fix migration of Files table from v5.7 to v8

concrete/authentication/concrete/controller.php, concrete/blocks/form/controller.php, concrete/config/concrete.php, concrete/config/db.xml, concrete/config/install/base/single_pages/dashboard.xml, concrete/controllers/single_page/dashboard/system/permissions/blacklist.php, concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/controllers/single_page/register.php, concrete/elements/dashboard/system/permissions/blacklist/menu.php, concrete/single_pages/dashboard/system/permissions/blacklist.php, concrete/single_pages/dashboard/system/permissions/blacklist/range.php, concrete/src/Package/StartingPointPackage.php, concrete/src/Permission/IPRange.php, concrete/src/Permission/IPRangesCsvWriter.php, concrete/src/Permission/IPService.php, concrete/src/Updater/Migrations/Migrations/Version20170412000000.php, concrete/src/User/UserBannedIp.php, tests/tests/ConcreteDatabaseTestCase.php, tests/tests/Core/Permission/IPServiceTest.php
Fix #3149
Fix #4100
Fix #5029
I also added support for whitelisted IP address ranges.
For instance, you can permanently ban (blacklist) all ip addresses, both IPv6 and IPv4 (`::/0` and `*.*.*.*`), and whitelist only selected IP addresses: that way, the login is only allowed from those selected addresses.
-----
-----
-----
=> Refactoring of the IP blacklist

concrete/src/Package/StartingPointPackage.php
1. Set Viewing Permissions to Members on Site Access page
2. Sign out
3. Access to some 404 page (e.g. `https://YOUR_SITE/favicon.ico`)
4. Sign In
5. Redirected to previous 404 page
1. `ResponseFactory::notFound` will pass `Page::getByPath('/page_not_found')` to `ResponseFactory::collection`
2. If the user is not able to access to `Page::getByPath('/page_not_found')`, `ResponseFactory::collection` will pass request uri (e.g. /favicon.ico or anything 404 uri) to `ResponseFactory::forbidden`
3. `ResponseFactory::forbidden` will save given request uri to session storage
=> Redirected to /favicon.ico after sign in on private website

concrete/src/Localization/Translation/Local/Factory.php
This fix is needed in order to install/update package translations from translate.concrete5.org
=> Fix updating package translations

concrete/src/Search/Column/Column.php
This does two things:
1. Declare properties
2. Provide a default value for search direction
The reason we need to make sure that we always declare properties is because if we don't our classes end up costing about 8x as much in terms of memory usage:
https://3v4l.org/h7nVV
=> Declare properties on search column class.

concrete/src/Events/EventsServiceProvider.php
Before, the following would all be false:
```php
dd(
$app['director'] === $app[EventDispatcher::class],
$app['director'] === $app[EventDispatcherInterface::class],
$app[EventDispatcher::class] === $app[EventDispatcherInterface::class]
);
```
After this pull request they all output true.
=> Make the dispatcher singleton work properly

concrete/jobs/index_search.php
This answers #5272 
> search_index never finishes indexing pages
> search_index indexes pages excluded from the search index - this may not be true, looks like we might filter this out at the last second
What @Mnkras meant to say was the search index updates job will always index pages. It never runs with 0 pages to reindex.
=> Make search index updates act as expected

concrete/controllers/single_page/dashboard/users/points.php, concrete/single_pages/dashboard/users/points/view.php, concrete/src/User/Point/EntryList.php
This PR fixes two problems:
1. When searching for a user, the dashboard page receives an user ID, but it thinks it's a user name. This results in a non functional search
2. The filterByUserID method of the datalist was broken
=> Fix searching Community Points for user

concrete/config/concrete.php, concrete/single_pages/dashboard/system/basics/multilingual/update.php
What about adding links to the `/dashboard/system/basics/multilingual/update` page pointing to the related page on translate.concrete5.org? Maybe that could encourage people to translate the packages...
Here's a screenshot (I added the two "more details" links, in this case pointing to [here](https://translate.concrete5.org/translate/package/concrete5) and [here](https://translate.concrete5.org/translate/package/customize_editing_interface)):
=> Add a link to the package translation pages

concrete/css/build/vendor/bootstrap/bootstrap.css
Currently to build app.css you need to rebuild bootstrap.css, as the minified version included does not include concrete5 adjustments. This cause incorrect css values to be displayed, for example button padding.
This PR replaces the minified non-adjusted bootstrap with the concrete5 adjusted version of bootstrap (non-minified). So that users who wish to rebuild the CSS can do so without having to go through the trouble of this https://github.com/concrete5/concrete5/blob/develop/build/Gruntfile.js#L422-L428
=> Updated bootstrap.css with a grunt build friendly version

concrete/src/Updater/Migrations/AbstractMigration.php, concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
About foreign keys: what about fixing the invalid data?
Here's what this PR does:
- delete records that *require* a parent record, but it's lost
- for the other records (where the parent record is not required), set the foreign field to NULL
In order to create this pull request, I installed concrete5 5.7.5.13 and concrete5 8.0 (the version that `Version20160725000000` migrates to), and inspected the foreign keys existing in 8.0 but not in 5.7.5.13.
=> Fix records containing invalid foreign keys

.travis.yml, composer.lock, concrete/src/Foundation/ClassLoader.php, tests/tests/Core/File/FileListTest.php, tests/tests/Core/Session/SessionFactoryTest.php, tests/tests/Core/Session/SessionValidatorTest.php
PHP 7.2 added some incompatibilities:
* `count` can no longer count things that aren't arrays or countables
* `each()` is now deprecated
This pull request fixes all of the issues blocking tests.
=> Support PHP 7.2

concrete/blocks/image_slider/form_setup_html.php
While working on the FAQ block, I realized that I wrote a redundant element selector in the Image Slider block. Since many people use the Image Slider block as a base for their own blocks, I wanted to remove this.
=> Image Slider block - remove redundant code

concrete/src/Permission/Access/Entity/Entity.php
There's no class named `PermissionAccessEntity` in \Permission\Access\Entity\Entity, so the PAE caching system doesn't work.
It's `self`, isn't it?
=> Fix reading cached permission access entities

concrete/attributes/date_time/controller.php, concrete/attributes/date_time/form.php, concrete/attributes/telephone/controller.php, concrete/attributes/telephone/form.php
There was a missing print/echo statement from the form.php template for telephone attribute. Also date_time didnt have a form template.
Fixed a case where composer is called by a context then form is called by context, causing duplicate entries.
=> Missing date_time form.php and added print statement in telephone attribute

concrete/src/Updater/Migrations/Migrations/Version20160725000000.php, concrete/src/Updater/Migrations/Migrations/Version20170202000000.php, concrete/src/Updater/Migrations/Migrations/Version20170404000000.php, concrete/src/Updater/Migrations/Migrations/Version20170420000000.php
more details here https://github.com/concrete5/concrete5/issues/5620#issuecomment-311342813
an attribute can always be deleted in concrete5, even if it's used by the core. Since this can happen I'd propose that we skip them in this context too to ensure that the update runs without any problems.
=> check if attribute exists before running migration script

concrete/src/Page/Page.php
I had used `$page->getCollectionDatePublicObject()->format('M j, Y')` some times, but this code will break a site if there's an scheduled page. So I'd like to add this phpdoc to avoid same mistakes.
=> Add phpDoc for \Concrete\Core\Page\Page::getCollectionDatePublicObject

concrete/src/Page/Type/Composer/FormLayoutSetControl.php
While debugging the migration of the setup that @patej gave me to solve #5631, I met a broken serialized object that aborted the execution (call of a method on a non object).
=> Intercept invalid serialized composer control objects

concrete/blocks/express_entry_list/edit.php
This is an ugly fix for the "Alternate Row Background Color" color picker being cut off. The modal is set to overflow hidden, so the color picker only partially displays.
**Current:**
**Changes:**
=> Express Entry List block - "Alternate Row Background Color" color picker cut off

concrete/controllers/search/pages.php
Fix #5637
It seems that when the search field is rendered, it already escapes the keywords, so we don't need to do it again.
=> Don't escape received keywords

concrete/views/frontend/install.php
Let's fix these problems:
- in the install page, checking `Set alternative canonical URL:` does not activate the related text box.
- rename `Set canonical URL for HTTP` to `Set main canonical URL`
- the html5 `pattern` attributes force users to specify `http:...` for the main canonical URL and `https:...` for the alternative canonical URL: let's allow `http:...` and `https:...` for both canonical URLs.
=> Fix enabling alternative canonical URL, fix canonical URL patterns

concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/single_pages/dashboard/system/permissions/blacklist/range.php
Changes included in this pull request:
1. in the whitelist page, show the current user's IP address:  
2. if you try to add to the blacklist an IP range that contains the current user's IP address, and if the current user's IP address is not in the whitelist, let's show this confirmation dialog:  
3. if you remove a whitelist range that contains the current user's IP address, and if after this removal the IP address is in a blacklist, show this warning:
=> Add confirmations about the risk of being locked out because of blacklisted IP

composer.lock
Just a minor change of the translation library to avoid errors when parsing empty XML CIF files (https://github.com/mlocati/concrete5-translation-library/releases/tag/1.5.9)
=> Update the translation library to v1.5.9

concrete/src/Foundation/Runtime/Run/CLIRunner.php
The [web runner](https://github.com/concrete5/concrete5/blob/6f01a4ec0e146000264e0225e53013633605143b/concrete/src/Foundation/Runtime/Run/DefaultRunner.php) initializes the time zone, but the [CLI runner](https://github.com/concrete5/concrete5/blob/6f01a4ec0e146000264e0225e53013633605143b/concrete/src/Foundation/Runtime/Run/CLIRunner.php) doesn't.
=> Initialize time zone in CLI commands

concrete/controllers/install.php
This fixes a bug introduced in #5564 that prevented specifying the canonical URLs during install (!)
I think I'm done with fixing the bugs I keep adding 🤣 I do really need a break :wink:
=> Fix specifying canonical URLs at install time

concrete/src/Support/Symbol/PhpDocGenerator.php
What about adding a PHPDoc generator?
For instance, in controllers we set the variables for the views, but in views we have to remember the variable types.
With this chunk of code:
```php
die('<pre>'.(new Concrete\Core\Support\Symbol\PhpDocGenerator())->describeVars(get_defined_vars()));
```
placed once at the top of a view, we'll have this kind of output:
```php
/* @var Concrete\Core\Area\Area $a */
/* @var Concrete\Core\Block\Block $b */
/* @var string $bID */
/* @var Concrete\Core\Entity\Block\BlockType\BlockType $bt */
/* @var Concrete\Core\Page\Page $c */
/* @var string[] $categories */
/* @var string $category */
/* @var Concrete\Package\MyPackage\Block\MyBlock\Controller $controller */
/* @var Concrete\Controller\Dialog\Block\Edit $dialogController */
/* @var …
```
=> Add helper class to generate PHPDoc

concrete/src/Search/Result/Item.php
In certain circumstances null values can enter a saved file search this has caused some issues when trying to run subsequent searches.
Once resolved I've not been able to replicate the issue, so believe it could be a legacy issue that's since been fixed?
But without this if a null value exists in the Users config then then the site search breaks with the exception listed in the bug tracker link below.
https://www.concrete5.org/developers/bugs/8-1-0/running-an-advanced-search-returns-an-exception/
=> Add a check to prevent null values from breaking the advanced file search

concrete/controllers/panel/page/design.php
When I'm trying to access Design & Types for pages like login or register, it generates an error. Because it's trying to get siteTreeObject which actually doesn't exists.
That's why I've applied a simple check and now it's working as the attached screenshot.
=> Error fix for null site tree object

concrete/controllers/single_page/account/messages.php
`Cancel` button doesn't have any event if the sender doesn't have public profile.
I've checked it from `Dashboard -> Members -> MemberName -> Send Private Message`.
**Applied javascript back to previous page, if the `getUserPublicProfileUrl` is null.**
=> Fix - Cancel button event, for who doesn't have public profile

concrete/src/User/User.php
Before the upgrade process starts, we may call the validateUser user method, which is referring to the Users.uIsPasswordReset database field that does not exist yet, since it's added by the upgrade.
Fixes http://www.concrete5.org/developers/bugs/8-1-0/upgrade-from-5.7.5.13-to.-8.1-error/
=> Avoid accessing non-existent Users.uIsPasswordReset field

concrete/src/User/PrivateMessage/Limit.php
This commit fixes the following issue.
=> Class not found error fix for PrivateMessage/Limit

concrete/src/Search/Pagination/PagerPagination.php
We can add some additional filtering on Page List block template, because PageList object is passed from block controller to view. It is useful to customize page list without override a block type controller. Here is an example code to do it.
```php
// application/blocks/page_list/templates/example.php
$list->filterByKeywords('Hello');
$pagination = $list->getPagination();
$pages = $pagination->getCurrentPageResults();
foreach ($pages as $page):
```
This code works expected on 8.1.0.
However, it doesn't works on 8.2.0RC2.
The new PagerPagination class modifies querybuilder object in page list. This is the why this code won't works. So, I've added simple `clone` call in the constructor.
=> Clone ItemList object in PagerPagination

concrete/blocks/express_entry_list/controller.php
When you save Express Entry List block without check any columns, you'll get the following error. This request will fix this.
Stack Trace:
```
Whoops\Exception\ErrorException: Invalid argument supplied for foreach() in file /path/to/concrete/blocks/express_entry_list/controller.php on line 208
Stack trace:
1. Whoops\Exception\ErrorException->() /path/to/concrete/blocks/express_entry_list/controller.php:208
2. Whoops\Run->handleError() /path/to/concrete/blocks/express_entry_list/controller.php:208
3. Concrete\Block\ExpressEntryList\Controller->save() /path/to/concrete/src/Block/Block.php:496
4. Concrete\Core\Block\Block->update() /path/to/concrete/controllers/Dialog/Block/Edit.php:54
5. Concrete\Controller\Dialog\Block\Edit->submit() …
```
=> Avoid Invalid argument supplied for foreach error

concrete/src/File/Image/BasicThumbnailer.php
The height was being passed along twice when using the new async thumbnail generation. This PR passes the width and height as expected
=> pass along the width and height

concrete/js/ckeditor4/core/concrete5link/plugin.js
In 5.7, there was a possibility to make a link to a page or an image open in a lightbox using Magnific pop-up.
Since all the code was still there, I modified concrete5link plugin.js to get the lightbox back in the editor.
The only difference is I didn't make it an option to switch on or off. It's just included.
=> Lightbox in CKeditor link plugin

concrete/src/Console/Command/InstallCommand.php
On CLI install, at the step of-
```
Starting point to use? [Default: elemental_blank]:
[0] elemental_full
[1] elemental_blank
```
has changed to-
```
Starting point to use? [Default: elemental_blank]:
[0] elemental_blank
[1] elemental_full
```
to make it more meaningful.
[0 for blank and 1 for full]
=> [Update] Starting point value swapped on cli install

concrete/src/File/Image/Thumbnail/AtomicThumbnailStream.php
Older versions of mysql would prevent async thumbnailing from working.
=> Use compatible date format for table lock

concrete/src/Utility/Service/Url.php
As an example, in the file concrete\src\Search\ItemList\ItemList.php, in the function getSortURL() you have an array of query parameters you send to the URL helper.
Since 8.2 you have added the parameter ccm_cursor with an empty value (it doesn't seem to be doing anything at the moment but it's there)
The function setVariable() in the URL helper is replacing existing parameters with their new value but is looking for parameters with a value already set (+? in regex looks for at least 1 match) so since we had ccm_cursor= with no value it was never replaced and on each iteration we added a new ccm_cursor= to the query string (?ccm_order_by=name&ccm_order_by_direction=asc&ccm_cursor=&ccm_cursor=&ccm_cursor=)
So by modifying the regex to use *? instead of +? we accept from 0 to many …
=> Regex is not taking into account empty query parameters

concrete/config/app.php, concrete/elements/files/view/audio.php, concrete/elements/files/view/text.php, concrete/elements/files/view/video.php
This pull request fixes the error on the view video element that is caused `<?=path()?>` . It also updates the other view elements in the file manager by replace Loader with Core::make and incorporating video/audio elements.
I have also updated filetypes in app.php to include mp4, ogg, webm etc in the view video element.
=> Fixing video view not working in file manager

concrete/single_pages/dashboard/files/sets.php
This PR fixes the file sets view icons being wrong for asc/desc order as mentioned in issue #5764
=> Fixing issue #5764 - wrong icons for asc/desc order

concrete/controllers/backend/file/thumbnailer.php, concrete/src/Entity/File/Version.php, concrete/src/File/Type/Inspector/ImageInspector.php, concrete/src/Http/Middleware/ThumbnailMiddleware.php
When building thumbnails, every File\Version instance loads the image.
Let's add a way to unload that image, otherwise we'll run out of memory when loading many images.
=> Release the Imagine instances once we're done with them

concrete/controllers/single_page/dashboard/system/express/entities.php, concrete/single_pages/dashboard/system/express/entities/add.php, concrete/single_pages/dashboard/system/express/entities/edit.php, concrete/src/Entity/Express/Entity.php, concrete/src/Express/Association/Formatter/AbstractFormatter.php, concrete/src/Express/Entry/Formatter/EntryFormatterInterface.php, concrete/src/Express/Entry/Formatter/LabelFormatter.php, concrete/src/Express/ExpressServiceProvider.php, concrete/src/Express/Formatter/FormatterInterface.php, concrete/src/Express/Formatter/LabelFormatter.php, concrete/src/Updater/Migrations/Migrations/Version20170731021618.php
This copies the name format that was given to associations and allows it to be used for entities as well. This replaces a lot of the association naming functionality.
=> Name formatting for entities

concrete/blocks/next_previous/controller.php
It was possible to get stuck in an infinite loop because some versions of mysql would return $date > $date possibly because of float logic? This PR adds a check that prevents that from happening to each sql query.
=> Prevent infinite loop in next/previous block

concrete/controllers/search/file_folder.php, concrete/src/Permission/Access/Entity/PageOwnerEntity.php
Beside #5820, PHP 7.2 is more strict about some warnings.
I'll add the relative fixes to this PR as I find the ones that prevents concrete5 running on PHP 7.2.
=> PHP 7.2 fixes

concrete/src/Express/Export/EntryList/CsvWriter.php
This adds `dateCreated` to the CSV export of entries.
=> Add date created to csv export for express entities

concrete/blocks/switch_language/controller.php
The `switch_language` block lists all the language sections, even those not accessible.
Let's show only the accessible language sections.
=> Show only accessible languages in switch_language blocks

concrete/controllers/single_page/dashboard/system/files/thumbnails/options.php, concrete/single_pages/dashboard/system/files/thumbnails/options.php
What about adding this new option to the `/dashboard/system/files/thumbnails/options` dashboard page?
=> Let users configure the thumbnail generation strategy via UI

concrete/controllers/single_page/dashboard/system/optimization/clearcache.php
When we save a new configuration option (`$config->save`), its value is persisted, but if we call `$config->get` without reloading the configuration file we still get the previous value.
In order to fix this, we need to call both `$config->set` and `$config->save`
=> Fix clearing cache settings

concrete/src/Cache/CacheClearer.php
The standard PHP library returns paths with the OS-specific DIRECTORY_SEPARATOR.
So, when we determine the files to be removed from the cache, we check if the path `C:/Path/To/application/files/cache\thumbnails` is contained in the array `['C:/Path/To/application/files/cache/thumbnails']`, which is always false.
That implies that the cache cleaner always remove the thumbnails cache directory.
=> Fix clearing cache but keep thumbnails on Windows

concrete/src/Console/Command/ClearCacheCommand.php
The `c5:clear-cache` CLI command clears or keeps the cached thumbnails depending on the `concrete.cache.clear.thumbnails` configuration key.
What about adding an option to the CLI command to explicitly delete/keep the thumbnails?
=> Add an option to the c5:clear-cache CLI command to keep thumbnails

concrete/config/concrete.php, concrete/src/Updater/Migrations/Migrations/Version20170818000000.php
I forgot to add a migration in #5865 (it's needed because of [this](https://github.com/concrete5/concrete5/pull/5865/files#diff-4b429fb8d545365541cec4e9a09ba8dcR87) and [this](https://github.com/concrete5/concrete5/pull/5865/files#diff-4b429fb8d545365541cec4e9a09ba8dcR107) changes of the setter methods).
=> Add migration to refresh Site\Locale entity

build/Gruntfile.parameters-sample.js, build/libraries/short-tags-remover.php, build/tasks/build-release/remove-short-tags.js, build/tasks/remove-short-tags.js
Since concrete5 requires PHP 5.5.9+, and the short echo tag `<?=` is always enabled since PHP 5.4.0, there's no more the need to replace `<?=` with `<?php echo` in concrete5 releases
=> Keep the short echo tags in built releases

concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/single_pages/dashboard/system/permissions/blacklist.php, concrete/single_pages/dashboard/system/permissions/blacklist/range.php, concrete/src/Console/Application.php, concrete/src/Console/Command/BlacklistClear.php, concrete/src/Permission/IPService.php
Fix #5357
This PR adds a new CLI command (`c5:blacklist-clear`) and a UI dialog to delete the logged failed login attempts and/or the automatic IP bans.
Here's a screenshot of the newly added dialog (the CLI command has similar options):
I also fixed the layout of the blacklist options page:
before:
after:
=> Allow clearing blacklist-related data

concrete/src/Http/Middleware/ThumbnailMiddleware.php
When ThumbnailMiddleware is done building a thumbnail, it [currently persist](https://github.com/concrete5/concrete5/blob/51bf047054a9bce7c76beb1ac4550711aacb9fe9/concrete/src/Http/Middleware/ThumbnailMiddleware.php#L263) that the thumbnail is done by passing all the columns of the database table.
BTW the Doctrine `update` methods builds a query like
```sql
UPDATE
FileImageThumbnailPaths
SET
isBuilt = 1
WHERE
fileID = 123
AND fileVersionID = 1
AND thumbnailTypeHandle = 'file_manager_listing'
AND storageLocationID = 1
AND path = '/thumbnails/file_manager_listing/1315/0160/3431/test.jpg'
AND isBuilt = 0
AND lockID = NULL
AND lockExpires = NULL
```
Since we compare fields with ` = NULL` instead of ` IS NULL`, no record is being updated, and the thumbnails gets rebuilt at every cycle (!). …
=> Fix saving "thumbnail is built" in ThumbnailMiddleware

concrete/blocks/image/controller.php, concrete/blocks/image/form.php
This pull request updates the checkbox formatting and prevents the "Open link in new window" value from always being true.
**Current:**
**Changes:**
=> Image block - "Open link in new window" checkbox

concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
When exporting Form Results (Dashboard > Reports > Form Results > Export to CSV) there is no filename, just the csv extension. This also had as consequence that the column `dateCreated` was inserted (on purpose?) and filled with HTML which corrupted the CSV-file. 
---
A further question is: Why the property `/concrete/src/Entity/Express/Entity.php->created_date` is never  part of the `/concrete5/concrete/src/Express/EntryList.php`, so never will be inserted when writing to csv file [CsvWriter.php#L44](https://github.com/concrete5/concrete5/blob/8.2.1/concrete/src/Express/Export/EntryList/CsvWriter.php#L44). Is that on purpose?
=> Fix csv-filename upon Form Results Export

concrete/js/ckeditor4/core/concrete5styles/plugin.js, concrete/src/Editor/CkeditorEditor.php
After you removed the async: false setting from the Ajax call, the snippets button couldn't be added to CKeditor's toolbar making snippets unusable.
This pull request gets all our snippets and custom classes while preparing all our editor's data and then sends it to the editor along with all the other config variables.
No more Ajax call and the editor loads way faster
=> Getting rid of an Ajax call in the core styles CKeditor plugin

concrete/src/Http/Middleware/CookieMiddleware.php
The [`setCookie` method of Symfony `ResponseHeaderBag`](https://github.com/symfony/http-foundation/blob/v3.3.2/ResponseHeaderBag.php#L182) accepts only one parameter (a `Cookie` instance), and not its path (the path is defined by the cookie instance itself).
Let's avoid passing an unused second parameter.
=> Removed unused parameter in CookieMiddleware

concrete/src/Support/Symbol/PhpDocGeneratorCaller.php
I use a lot the PhpDocGeneratorCaller introduced in #5669, but I always forget how to use it.
What about adding a file that, when included, calls it the right way?
It's enough to add this:
```php
include DIR_BASE_CORE . '/src/Support/Symbol/PhpDocGeneratorCaller.php';
```
=> Add PhpDocGeneratorCaller.php

concrete/src/Package/ItemCategory/GeolocatorLibrary.php
I forgot to add the procedure to automatically uninstall geolocation libraries when they are part of packages and when these packages are uninstalled.
=> Uninstall packaged geolocation libraries

concrete/controllers/single_page/dashboard/system/multilingual/setup.php, concrete/single_pages/dashboard/system/multilingual/setup.php
It's currently not possible to change the locale assigned to a specific multilingual section.
What about an *edit* icon for every multilingual section like this?
When clicked, this new dialog is shown:
=> Allow changing site locale

concrete/elements/header_required.php
@mlocati according to this we should display the current language too: https://moz.com/learn/seo/hreflang-tag
> The hreflang attribute on each page should include a reference to itself as well as to all the pages that serve as alternates for it.
=> show current language in hreflang too

concrete/blocks/page_list/controller.php, concrete/blocks/page_list/page_list_form.php, concrete/src/Page/PageList.php
- adds 2 new methods to the PageList class for sorting by date modified ascending and descending
- adds a "Most recently modified first" sorting option to the Page List block for sorting by date modified descending
These changes had been previously requested on the forum, but the need for a "Recently Updated" documentation sidebar page list was the driving factor for the pull request.
**Changes:**
=> PageList and Page List block - sort pages by date modified

concrete/controllers/single_page/dashboard/system/files/storage.php, concrete/single_pages/dashboard/system/files/storage.php, concrete/src/Entity/File/StorageLocation/StorageLocation.php, concrete/src/File/StorageLocation/StorageLocationFactory.php
When we adding a new Storage Location that's set as as the default one, we currently end up having two default storage locations in the database.
I also fixed an HTML error (an unclosed `<label>` tag) and some warnings about accessing undefined variables in the view of dashboard/system/files/storage
=> Fix creating new default storage location

concrete/src/Entity/File/File.php
When duplicating a file, two copies of it gets created (one copy by a call to `duplicateUnderlyingFile` and one copy by the lines removed in this PR).
=> Duplicate actual file just once

concrete/src/Entity/File/File.php
When a file is inside a folder and is duplicated and the copy duplicated again, the second copy doesn't appear anywhere.
This problem first appeared in #5875
It is sent to a non-existent folder. This fixes it.
=> Fixes duplicating a duplicated file in a folder

concrete/src/Entity/File/File.php, concrete/src/Entity/File/Version.php
When duplicating a file, thumbnails don't get duplicated and the file ends up with no thumb in the manager.
This takes care of that issue by copying the thumbnails as well (since we're duplicating, no need to recreate the thumbs, a simple copy should do it)
=> Copy thumbs on duplicate

composer.lock, concrete/composer.json, concrete/src/Config/FileLoader.php, concrete/src/Config/LoaderInterface.php, concrete/src/Config/Repository/Repository.php
This pull request updates from [4.2.x](https://github.com/illuminate/config/tree/4.2) to [5.2.x](https://github.com/illuminate/config/tree/5.2) which is actually a relatively big jump.
Considerations:
* This is technically a backwards incompatible change since it removes those classes from the illuminate namespace, but our layer is 100% compatible.
* This updates other dependencies that we use quite often too, illuminate/support and illuminate/filesystem. I'm not exactly sure what the full implications of that are yet.
* If we get this done, we will be compatible with [codeception](http://codeception.com/)
All I did was copy out the relevant stuff from the old 4.2 version into our wrapper layer.
=> Remove old config dependency and update to use the latest version

concrete/src/Page/Page.php
This should fix this error (see https://travis-ci.org/concrete5/concrete5/jobs/269569618):
```
PageTest::testSinglePagesPath
Whoops\Exception\ErrorException: Undefined property: Concrete\Core\Page\Page::$cPointerID
/home/travis/build/concrete5/concrete5/concrete/src/Page/Page.php:1451
/home/travis/build/concrete5/concrete5/concrete/src/Page/Page.php:2500
/home/travis/build/concrete5/concrete5/tests/tests/Core/Page/PageTest.php:86
```
=> Avoid accessing cPointerID property of Page object if it's not defined

concrete/config/site.php, concrete/src/Editor/CkeditorEditor.php
- adds CKEditor config and JavaScript configuration options
- allows toolbar button and group reordering and row creation
Currently, CKEditor configuration options are contained in CkeditorEditor.php and not easy accessible. This pull request allows for additional configuration options to be added through the site.php config.
I have created a sample site.php config gist that provides a few examples of what these configuration options allow you to do. Things like controlling what formatting tags are available, removing toolbar buttons, custom ordering of toolbar groups, and removing plugin dialog modal fields and full modal tabs.
https://gist.github.com/MrKarlDilkington/5a14cf2c8aca511c8c9d2026e07b297c
The code changes were tested, but I welcome additional eyes to look …
=> Add CKEditor configuration options

concrete/js/ckeditor4/core/concrete5link/plugin.js
**Steps to reproduce:**
- add a Content block to a page
- add some text
- create a link in the text
- edit the link
- when you edit the link, this creates a console error 
`Uncaught TypeError: Cannot read property 'name' of undefined`
I spoke to another developer about this error and they thought it was likely caused by a bug in the CKEditor Link plugin (not the concrete5link plugin that extends it). Instead of modifying a vendor file, it looks like checking the property type before using it fixes the issue.
=> Prevent uncaught type error when editing links in CKEditor

concrete/views/panels/page/versions.php
This commit improves the page version info display animation.
**Before**
**After**
=> [Update] Page version info animation

concrete/src/File/ImportProcessor/ConstrainImageProcessor.php
When Image Uploading "Automatically resize uploaded images" is enabled, uploading SVG files fail with an `An image could not be created from the given input` error.
Dashboard > System & Settings > Files > Image Uploading > Automatically resize uploaded images
=> Prevent image upload resizing of SVG files

concrete/src/File/Service/File.php
When using the getContents() function there is a $timeout parameter that is not used. It is most important for cURL uses.
As an example, it is set by the core when getting a package list from the marketplace but not actually used.
This tiny fix corrects that.
=> Use the timeout setting

concrete/composer.json
Update composer.json to have the concrete5 lessphp vendor name. Autoload wasn't working properly because it was looking for the original vendor, fixed here https://github.com/concrete5-forks/less.php/commit/eebead5849b7dd21f450905007cd65a385b894e3 but wasn't being applied.
=> Fix lessphp composer vendor (using 2.0.0)

concrete/src/Error/ErrorList/ErrorList.php
Concrete5 shows error messages together on the top of the form. But, sometimes we may need to show the messages underneath of the form field. This PR allows to print error messages for single field by following way-
```
if (is_object($error) && ($error->has())) {
echo $error->getMessage('uEmail');
}
```
=> [Feature] Display single error message by field

concrete/bootstrap/configure.php, concrete/dispatcher.php
The startup process checks the minimum PHP version in the `concrete/bootstrap/configure.php` file.
BTW that file contains PHP syntax not supported in old PHP versions (for example [this line](https://github.com/concrete5/concrete5/blob/5708633433d7eb2a743c252a62803fafd9f5b8de/concrete/bootstrap/configure.php#L21) and [this line](https://github.com/concrete5/concrete5/blob/5708633433d7eb2a743c252a62803fafd9f5b8de/concrete/bootstrap/configure.php#L84) require PHP 5.3.0).
What about checking the PHP version at the very beginning of dispatcher.php (it's the entry point for both web and CLI calls)?
=> Fix startup on unsupported PHP versions

concrete/src/Http/DefaultDispatcher.php
We currently resolve the routes twice, uselessly: let's resolve the route just once.
=> Look for routes only once

concrete/src/Page/EditResponse.php, concrete/src/Page/Page.php
Fixes #4633, where page selector replaces alias ID by original ID when selecting a page alias. Please review before accepting.
=> Return collection pointer ID for alias pages instead of the target ID

concrete/src/Block/BlockType/BlockTypeList.php
The block object isn't created the correct way. The error popped up when creating a new BlockType with additional constructor parameters.
To reproduce:
1. Copy autonav block to application folder and rewrite namespace as usual
2. rename folder name to `test_autonav` & adapt namespace
3. add the following `Connection $database` param to the constructor:
```
use Concrete\Core\Database\Connection\Connection;
//...
protected $database;
//...
class Controller extends BlockController
{
//...
public function __construct(Connection $database, $obj = null)
{
parent::__construct($obj);
$this->database = $database;
}
//...
}
```
4. head over to `/dashboard/blocks/types/install`
5. Install the new BlockType
Result:
> Exception: Argument 2 passed to …
=> Fix BlockTypeList: new Block object isn't created properly

concrete/controllers/backend/file.php
When rescanning images the first thing that happens is whether the setting to constraint image sizes is enabled. Normally this setting applies on upload but if it was set after some images were already uploaded, it didn't apply to those images. Hence the check on rescan.
The problem is, if constraints are enabled, the system doesn't check whether the image is already within constraints. It goes through the whole process of creating a new version and going through imagine which will eventually figure out the image doesn't need processing.
This modification checks the size of the image BEFORE doing all this so if it is already within constraint, we don't waste time.
I did a quick microtime() measuring on 6 images and, doing it this way, it gets between 3x to 5x faster processing one image …
=> Faster file rescan

concrete/src/Tree/Node/Type/FileFolder.php
Previously you'd get an error when viewing the file manager.
=> Fix filemanager when sortcolumn isn't found

concrete/jobs/generate_sitemap.php, concrete/src/Console/Command/InstallPackageCommand.php, concrete/src/Console/Command/JobCommand.php, concrete/src/Console/Command/UninstallPackageCommand.php, concrete/src/Console/Command/UpdatePackageCommand.php, concrete/src/Console/ConsoleAwareInterface.php, concrete/src/Console/ConsoleAwareTrait.php
This makes it easy for jobs and packages to output to the console when being manipulated via cli. As an example I added a progress bar to the generate_sitemap job.
=> Make jobs and packages aware of the console

concrete/attributes/rating/form.php
Fixed issue in form.php with incorrect variable being called. Previously, the ratings attribute was not being passed correctly into service.php when output method was called.
=> Fixed issue with existing ratings not being populated in edit mode - Update form.php

concrete/src/Tree/Node/Type/File.php
This prevents XSS in some places, namely when deleting a file. See h1 #243858
=> Sanitized display value for file nodes

concrete/src/Tree/Type/Topic.php
When importing topic trees we need a `name` attribute ([link](https://github.com/concrete5/concrete5/blob/d5658e0b592bdcd176ad1b342f0e5d5db346adaf/concrete/src/Tree/Type/Topic.php#L96)), but it's not set while exporting them ([link](https://github.com/concrete5/concrete5/blob/d5658e0b592bdcd176ad1b342f0e5d5db346adaf/concrete/src/Tree/Type/Topic.php#L82)).
Let's fix this issue.
=> Add "name" attribute to exported topic trees

concrete/src/File/Set/Set.php
After you delete a File Set, it only makes sense all relations in the "FileSetFiles" database table get deleted too. For some reason, this wasn't happening yet though. It already IS deleting entries from the "FileSetSavedSearches" database table though, so this should be a nice addition to keep the database clean.
=> Remove entries from 'FileSetFiles' database table too after deleting a File Set

concrete/src/Marketplace/RemoteItem.php, concrete/src/Package/Package.php
When updating a package, C5 first makes a backup in the trash directory and puts the backup directory's path in the package object's variable $this->backedUpFname.
Later, if updating fails, C5 attempts to restore the package from the backup.
The problem is $this->backedUpFname returns an empty value and the package is not restored breaking C5.
This fixes the restore system by returning the package after backup so we can access $this->backedUpFname
=> Fix package restore after failed update

concrete/src/Updater/Migrations/Migrations/Version20170926000000.php
In #5986 I changed the type of the `postTo_cID` field (`btSearch` table) from string to integer.
In order to avoid migration problems, I set to `null` all the `btSearch` fields that contain empty strings.
BTW, in case the `btSearch` column contain other values that can't be converted to integers, the migration will break. There shouldn't exist records with such invalid values, but it's safer to not assume anything :wink:
=> Safer migration of btSearch table

concrete/src/Backup/ContentImporter.php
We might want to consider doing this in each of the routines rather than forcing it as part of content import.
Using blackfire, this shows the installation going from 3:30s down to 1:48s!
=> Improve the contentimporter by clearing the entitymanager regularly

concrete/src/Search/Pagination/View/ConcreteBootstrap3PagerTemplate.php
This pull request adds a page number for non-superuser pagination. The goal is to add more feedback to how many pages are available and where you are within the results.
https://github.com/concrete5/concrete5/issues/5116#issuecomment-330837336
https://www.concrete5.org/community/forums/usage/why-diff.-pagination-for-diff.-admins/
=> Add pager pagination page number

concrete/controllers/backend/file.php
* Delete message if `unserialize` returns false.
* Remove `5` argument as `deleteQueue` does not take any
arguments
If there is bad data in the queue, for example, the string "7164",
the `unserialize` call with return false which make `file['fID']` `null`.
This causes the `getByID` call to fail with the error
`The identifier fID is missing for a query of Concrete\Core\Entity\File\File`
Then the offending queue message is never removed breaking
multiple file rescan until it is manually removed from the database.
This seems to happen after upgrade of sites with a lot of files
from version 5.7 to 8.
See this forum post for more report of the issue
https://www.concrete5.org/community/forums/installation/error-the-identifier-fid-is-missing-for-a-query-of-concretecoree/
=> Fix rescan multiple files error

concrete/src/Error/Provider/WhoopsServiceProvider.php
I don't know if it's already possible to add a custom error handler, but this PR would allow to add a custom error handler with
```php
$app->make(Whoops\Run::class)->pushHandler($myErrorHandler);
```
=> Add the Whoops\Run instance to Application

concrete/controllers/single_page/dashboard/extend/update.php, concrete/src/Console/Command/UpdatePackageCommand.php, concrete/src/Package/Dependency/DependencyChecker.php, concrete/src/Package/Dependency/DependencyException.php, concrete/src/Package/Dependency/IncompatiblePackagesException.php, concrete/src/Package/Dependency/MissingRequiredPackageException.php, concrete/src/Package/Dependency/RequiredPackageException.php, concrete/src/Package/Dependency/VersionMismatchException.php, concrete/src/Package/Package.php, tests/tests/Core/Package/DependencyCheckerTest.php
What about introducing package dependencies?
Package dependencies are described by a [`$packageDependencies ` property](https://github.com/concrete5/concrete5/blob/d1902925555ffe44b2d811d0fb2f152381d892c4/concrete/src/Package/Package.php#L206-L228), that's an array with:
- keys: the other package
- values: the dependency description from the other package.
The dependency description can be:
- `false` to say that the current package can't be installed in the other package is installed
- `true` to say that the current package requires that the other package must be installed (any version)
- a string to say that the current package requires that the other package must be installed (minimum version)
- an array with two strings to say that the current package requires that the other package …
=> Introduce package dependencies

concrete/src/Support/Symbol/ClassSymbol/ClassSymbol.php, concrete/src/Support/Symbol/SymbolGenerator.php
Currently, the `__IDE_SYMBOLS__.php` file generated by the `c5:ide-symbols` is invalid, since it contains the following code:
```php
<?php
namespace {
class Area extends \Concrete\Core\Area\Area
{
}
// [...]
class Concrete\Core\Foundation\Object extends Concrete\Core\Foundation\ConcreteObject
{
}
// [...]
}
```
which is invalid.
Let's generate the following code:
```php
<?php
namespace {
class Area extends \Concrete\Core\Area\Area
{
}
// [...]
}
namespace Concrete\Core\Foundation {
class Object extends \Concrete\Core\Foundation\ConcreteObject
{
}
// [...]
}
```
=> Fix the generation of __IDE_SYMBOLS__.php

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/registration/open.php, concrete/controllers/single_page/register.php, concrete/single_pages/dashboard/system/registration/open.php, concrete/single_pages/register.php
- In current version of concrete5, display username on registration form is configurable from config file. But can't do it from dashboard. This PR allows to do it.
- Additionally, it's very common for us, sometimes our clients want to remove confirm password field, as it can reset by forgot password. Let's control it also from dashboard.
- If we skip username on registration form, but we don't configure it to login with email, it may not work. I've added a dialog for it.
=> [Feature] Make username and confirm password display/hide configurable for registration form from dashboard

concrete/tools/conversations/view_ajax.php
This prevents users from viewing conversations they might not otherwise have access to. See h1 #265284
=> Tighten up conversations view

concrete/attributes/date_time/controller.php, concrete/attributes/date_time/form.php, concrete/attributes/date_time/type_form.php, concrete/config/concrete.php, concrete/src/Entity/Attribute/Key/Settings/DateTimeSettings.php, concrete/src/Updater/Migrations/Migrations/Version20171012000000.php
In order to allow custom formats for the date/time attributes, we need to know if we have to convert the timezone or to keep the user's time zone (for instance, a birth date shouldn't follow the time zone, but the date/time of a meeting should).
So, we need to add another type of `Text Input Field`, to know if the time zone should be converted or not.
To simplify its description, I split `Text Input Field` to `Text Input Field with Date` and `Text Input Field with Date and Time` (but I'm obviously open to comments about that :wink:).
Fix #6039
=> Allow custom date/time formats for date_time attributes

concrete/controllers/single_page/dashboard/system/environment/entities.php, concrete/single_pages/dashboard/system/environment/entities.php, concrete/src/Package/Event/PackageEntities.php, concrete/src/Package/PackageService.php
Supersedes #6037 with a much less invasive approach:
- add an event (`on_list_package_entities`) to list the entity drivers in the `/dashboard/system/environment/entities` dashboard page
- add an event (`on_refresh_package_entities`) to tell subscribers that the user wants to refresh the entity managers
=> Add support for custom entity managers v2

concrete/blocks/video/form_setup_html.php
fix #5957 An invalid form control with name='width' is not focusable.
This problem occurs when you want to edit the blok and 'Set Max Width' is not checked. The 'width' input is hidden and can not be focused because of this. 
The solution switches the type of the input.
=> fix #5957 An invalid form control with name='width' is not focusable.

concrete/src/Console/Command/InstallLanguageCommand.php, concrete/src/Console/Command/InstallPackageCommand.php, concrete/src/Console/Command/PackPackageCommand.php, concrete/src/Console/Command/TranslatePackageCommand.php, concrete/src/Console/Command/UninstallPackageCommand.php, concrete/src/Console/Command/UpdatePackageCommand.php
I think it makes more sense to type `c5:translate-package`, than to type `c5:package-translate`.
Because the commands are alphabatically sorted, I added the following aliases:
- `c5:install-language`
- `c5:install-package`
- `c5:pack-package`
- `c5:translate-package`
- `c5:uninstall-package`
- `c5:update-package`
=> Add console command aliases

concrete/src/Entity/File/StorageLocation/StorageLocation.php
When
- caching is enabled, and
- a file on the file system is modified (e.g. decreases in size)
The Rescan file doesn't update the file size correctly. 
This PR adds a method that would allow us to clear the Flysystem [cache](https://github.com/concrete5/concrete5/blob/develop/concrete/src/Entity/File/StorageLocation/StorageLocation.php#L135).
See also: https://github.com/concrete5/concrete5/issues/5933#issuecomment-333260534
=> Add method to clear the Flysystem cache

concrete/authentication/concrete/controller.php
Now, if someone try to access http://concrete5.dev/index.php/login/concrete/change_password (which is an invalid url) it shows some errors. Let's stop it with a simple check.
=> Stop change password page invalid access

concrete/src/Attribute/Category/SearchIndexer/StandardSearchIndexer.php
What about adding support to foreign keys creation in attribute index tables?
For instance, for the file attributes, we may have [here](https://github.com/concrete5/concrete5/blob/1388634e32b526b66f0ae0d74245c9cd40cca3dc/concrete/src/Attribute/Category/FileCategory.php#L27) a code like this:
```php
return [
'columns' => [
[
'name' => 'fID',
'type' => 'integer',
'options' => ['unsigned' => true, 'default' => 0, 'notnull' => true],
],
],
'primary' => array['fID'],
'foreignKeys' => [
[
'foreignTable' => 'Files',
'localColumns' => ['fID'],
'foreignColumns' => ['fID'],
'onUpdate' => 'CASCADE',
'onDelete' => 'CASCADE',
]
],
];
```
That way, when a record in the Files  table is deleted, we won't have records in the FileSearchIndexAttributes table anymore.
=> Add support to foreign keys in attribute index tables

concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
This should fix the migration problem reported here: http://www.concrete5.org/community/forums/internationalization/multilingual-site-error-after-upgrade-to-8.2
=> Prepare MultilingualPageRelations table for upgrading

concrete/controllers/single_page/account/edit_profile.php
File: concrete/controllers/single_page/account/edit_profile.php
Use
```
$message = call_user_func([$at->controller, $method]);
```
istead of 
```
$message = call_user_method($method, $at->controller);
```
=> Replace deprecated method call_user_method with call_user_func

concrete/blocks/document_library/controller.php
`Set Order` may stand for `Order of the set` or `Configure the order`.
Different meanings imply different translations. Let's add a translation context to define what it exactly means.
=> Define the meaning of `Set Order` with a context

concrete/controllers/single_page/members/profile.php
I'm working on a quick fix of Public Profile page.
Client deleted some users because they want to quit.
Then, when Google tried to crawl deleted users' public profile pages, it generated a bunch of exception errors which fired false alert.  (opps)
I think it would be nice to render 404 not as exception error page.
But my method won't send 404 response to browser.
Does anyone know a quick way to render a real 404 page from view() method of single_page?
=> Show 404 for deleted user public profile page

concrete/src/Url/SeoCanonical.php
On w3c Online Checker For HTML we get two errors on <meta rel="canonical" :
Error: Attribute rel not allowed on element meta at this point.
Error: Attribute href not allowed on element meta at this point.
It must be a link instead of meta : https://support.google.com/webmasters/answer/139066?hl=fr.
=> Fix W3C HTML Validator Error for Meta Canonical

concrete/src/Page/PageList.php, concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
This PR fixes issue https://github.com/concrete5/concrete5/issues/4907
```
$rb = $this->connection->executeQuery('select * from CollectionAttributeValues where akID = ?', [$row['akID']])
```
[This query](https://github.com/concrete5/concrete5/blob/develop/concrete/src/Updater/Migrations/Migrations/Version20160725000000.php#L370) was causing duplicate entries on `atSelectedTopics` table.
```
$rb = $this->connection->executeQuery("select * from CollectionAttributeValues where akID = ? group by avID", array($row['akID'])); 
```
or,
```
$rb = $this->connection->executeQuery("select distinct akID, avID, atID  from CollectionAttributeValues where akID = ? ", array($row['akID'])); 
```
As `atID` isn't available on most recent version, I think using `group by` is safer than `distinct`.
Have to …
=> [Fix#4907] Fix duplicated results of topic filter

concrete/blocks/express_form/controller.php
The form name isn't update properly.
* Create a form with the name "test"
* Edit the form block and change the name to "test 123"
* When you then edit the block, you'll see the new name, but when you check the reports in the backend, you'll still see the old name
This PR fixes this
=> update node name in addition to form entity name

concrete/src/Error/ErrorList/ErrorList.php, concrete/src/Error/ErrorList/Formatter/TextFormatter.php
We have a way to convert an ErrorList to JSON or to HTML: what about adding a way to get a plain text representation?
=> Allow converting an error list to plain text

concrete/blocks/express_form/controller.php
When creating new forms I often see people missing the `Add Question` button. It's not really surprising as you can't see the button and there's another `Add` button that can easily confuse users. The modals in concrete5 have a maximum height, even if a screen is smaller, the block will still work.
With this PR the button is at least visible to the majority of the users:
=> Increase form block height

concrete/elements/block_footer_edit.php, concrete/elements/block_header_edit.php
* Add a content block
* Put content block in clipboard
* Paste content block from clipboard
You'll see the save/cancel buttons for non-inline blocks. The reason for this is because the block type handle is pulled form the current block which is a the scrapbook display block and not the original block. This PR should fix this problem.
=> fix inline edit detection for blocks pasted from the clipboard

concrete/src/User/User.php
After reverting this https://github.com/concrete5/concrete5/issues/6093 I still wasn't able to install concrete5. The XML defines a default value of 0, but since we pass a null value into the replace function it tries to write an empty value.
=> set 0 as uID when writing config record without being logged in

concrete/src/File/Service/Zip.php
The `$destinationDirectory` variable is undefined here.
=> Fix variable name to sourceDirectory

concrete/blocks/express_form/auto.js
When you add a question in the form block the type is reset (1), but the form fields stay (2). Triggering the change event fixes this.
=> reset answer type form after adding question

concrete/src/Updater/Migrations/Configuration.php
I don't think a namespace should start with a backslash. I'm not 100% certain that this is only used when generating migrations though?
=> fix migration namespace

concrete/css/build/core/app/inline-toolbar.less, concrete/elements/block_area_footer.php, concrete/elements/custom_block_template.php, concrete/src/Block/Menu/Menu.php, concrete/src/Page/Collection/Collection.php, concrete/views/dialogs/block/design.php
As described here https://github.com/concrete5/concrete5/issues/6115
* This completely removes the area design menu item if `concrete.design.enable_custom` is set to false
* It changes the menu item text in the block menu from `Design & Custom Template`  to `Custom Template` if the design feature is disabled
* It shows the template list in the toolbar to save another click
I'd be happy to hear anyone's thoughts about this.
=> hide block and area design features if disabled

concrete/elements/system_errors.php
[It's possible to trigger some self-xss on the install screen](https://hackerone.com/reports/289330). Let's escape those strings to fix that.
=> Run errors through htmlspecialchars

composer.lock
Let's upgrade the Translation Library, so that the new CIF XML nodes `/concrete5-cif/permissionkeys/permissionkey/access/entity` doesn't break the execution
=> Update the Translation Library

concrete/src/Workflow/Request/ApproveCalendarEventRequest.php
There are two strings that aren't translatable in the new Calendar system (the translatable argument of `t()` functions must be a **literal** string).
=> Fix calendar event translatable strings

concrete/src/Multilingual/Page/Section/Section.php, phpunit.xml, tests/tests/Multilingual/SectionTest.php
I noticed the Multilingual option `multilingual.use_browser_detected_locale` is not working as expected with some browsers:
- When there is a full locale in the headers it works well (e.g. `Accept-Language: de-CH, en-US, en`).
- However, when it only includes the language it fails to redirect to the correct language section (e.g. `Accept-Language: de, en`).
Here's what happens behind the scenes:
- [`Detector::getPreferredSection`](https://github.com/concrete5/concrete5/blob/9a5bc417bf31f3a106b19ad36bede54cd5ed963a/concrete/src/Multilingual/Service/Detector.php#L65) tries to detect the language with the browser headers
- [`Section::getByLocaleOrLanguage`](https://github.com/concrete5/concrete5/blob/9a5bc417bf31f3a106b19ad36bede54cd5ed963a/concrete/src/Multilingual/Page/Section/Section.php#L …
=> Multilingual redirect based on browser locale not always working

concrete/src/Support/Symbol/MetadataGenerator.php
We have the great `c5:ide-symbols` that generates metadata files to help IDE resolving for instance the result of `$app->make('config')`.
What about also telling the IDE that the results of `$app->build(ClassName::class)` is an instance of the `ClassName` class?
=> Help build factory method

concrete/src/Page/Search/IndexedSearch.php
The foreach loop overwrote the passed in $arHandle variable whilst setting up the blacklisted areas. I have renamed the variable in the loop. This appears to now allow non blacklisted areas to be indexed.
=> Fix area blacklist in IndexedSearch.php

concrete/attributes/calendar_event/controller.php, concrete/src/Calendar/Event/Formatter/LinkFormatter.php
The link formatter for the details page was using versionOccurenceID as the url get parameter, but the calendar_event block was looking for occurenceID, so the links from a calendar to a detail page using the request method weren't working. 
This PR is a little unclean, though, I messed up and put some changes in the develop branch last night rather than doing a feature branch. Oops. So I'm not sure if that changes if this one can be merged or not, but it did seem like it should be a separate PR because it's unrelated to the attribute stuff that I did before. So I have an extra commit that removes those changes... 
Sorry about that, I don't contribute to the core very much, I'm a little rusty.
=> Bugfix calendar link formatting

concrete/attributes/calendar_event/controller.php
I was having issues with filtering by event in page lists, this seems to fix it for me. The first change was to actually return the value for the attribute to the search index table rather than just "1" so that there's actually a valid value to search against. The second was to use the actual form method for the attribute to use in advanced search, instead of the one inherited from the number attribute. Nobody's going to know the ID number for the event they want to use. 
I wasn't able to get the event ID to persist in the selector, though. I'm not sure how to do that, but this is a lot better overall so submitting. The calendar ID does persist, so I'm really not sure what's up. I figure anyone wanting to modify the search query is going to be picking another event, anyway, so it's kind …
=> Enabled searching by event

concrete/src/Application/Application.php, concrete/src/Support/Symbol/MetadataGenerator.php
Registered aliases that have not yet been evaluated aren't included in the `.phpstorm.meta.php` file generated by the `c5:ide-symbols` IDE command.
In order to include them, we need to get the list of registered aliases. Since there's no current method to do that, I've had to add it to our `Application` class.
This will let PHPStorm (and Eclipse+PDT+[concrete5 plugin](https://github.com/mlocati/concrete5-eclipse-plugin)) to autocomplete stuff like
```php
$app->make('date')->|
```
Here's the list of additional items recognized with this pull request:
```php
'captcha'
'date'
'helper/date'
'helper/lists/countries'
'helper/lists/states_provinces'
'helper/localization/countries'
'helper/localization/states_provinces'
'helper/validation/captcha'
'http/client'
'lists/countries' …
```
=> Add aliases too PHPStorm metadata file

concrete/src/Support/Symbol/MetadataGenerator.php
We can associate custom repositories to Doctrine entities (via the `@Doctrine\ORM\Mapping\Entity(repositoryClass="...")` annotation).
What about suggesting the IDE what's the exact result of `$em->getRepository(EntityClass::class)` for such cases?
For instance, because of the PHPDoc of the `EntityManagerInterface::getRepository`, the IDE thinks that the result of
```php
$em->getRepository('Concrete\Core\Entity\Attribute\Key\UserKey');
```
is an instance of `Doctrine\Common\Persistence\ObjectRepository`, but for concrete5 this is more specifically an instance of `Concrete\Core\Entity\User\AttributeRepository`.
PS: this will help developers using PHPStorm or Eclipse+[concrete5 plugin](https://mlocati.github.io/concrete5-eclipse-plugin/), provided that they run the `c5:ide-symbols` CLI …
=> Add custom entity repositories support to .phpstorm.meta.php

concrete/blocks/faq/form_setup_html.php
https://github.com/concrete5/concrete5/issues/6172
=> FAQ block - prevent quotes in Navigation Link Text and Title Text from breaking display

concrete/controllers/single_page/page_not_found.php
what about an event to hook into the 404 process? That way it would be easier to redirect old urls from a package.
=> raise event when page not found is shown

concrete/controllers/single_page/dashboard/system/files/thumbnails/options.php, concrete/src/File/Image/BasicThumbnailer.php, concrete/src/File/Image/Thumbnail/ThumbnailFormatService.php
Let's fix a format naming problem introduced in #5900: we sometimes called the JPEG format as `'jpg'` and sometimes as `'jpeg'`.
Let's always use the format constant to represent it (`'jpeg'`), and automatically convert the wrong representation.
=> Thumbnail fixes... fixed

concrete/src/Block/Block.php
Furthermore:
- add PHPDoc
- deprecated unused methods (block actions via URLs, `refreshCache`, `refreshCacheAll`)
- deprecated duplicated methods (`getController` === `getInstance`, `loadNewCollection` === `setBlockCollectionObject`, `delete` === `deleteBlock`)
Ref. #4723
=> Avoid accessing undefined vars in Block\Block

concrete/controllers/backend/page/multilingual.php
I currently can't create a new mapped page from the multilingual page report screen.
That happens because `r.pages` isn't available in this line https://github.com/concrete5/concrete5/blob/develop/concrete/single_pages/dashboard/system/multilingual/page_report.php#L261
=> Creating page from multilingual page report

concrete/controllers/single_page/dashboard/system/multilingual/page_report.php
Without this fix, the list of pages in the multilingual/page_report dashboard page was empty for me.
=> Fix the site tree filter of MultilingualPageList in multilingual/page_report

.travis.yml
Now that PHP 7.2 has been released, what about telling TravisCI that failing tests are not allowed?
PS: we should have a PHP 7.2 warning. That's caused by PHPUnit 4.8. [I tried](https://github.com/sebastianbergmann/phpunit/pull/2773) to fix this issue, but @sebastianbergmann [closed my pull request](https://github.com/sebastianbergmann/phpunit/pull/2773#issuecomment-331136709).
=> PHP 7.2 must not fail

concrete/src/Captcha/CaptchaInterface.php, concrete/src/Captcha/CaptchaWithPictureInterface.php, concrete/src/Captcha/ConfigurableCaptchaInterface.php, concrete/src/Captcha/Controller.php, concrete/src/Captcha/Library.php, concrete/src/Captcha/NoCaptchaController.php, concrete/src/Captcha/SecurimageController.php, concrete/src/Captcha/Service.php, concrete/src/Validation/ValidationServiceProvider.php
In #6036 I changed the signatures of the captcha controller.
Instead of doing that (it's a BC break), what about adding an interface that captcha libraries can implement?
=> Add specialized ConfigurableCaptchaInterface instead of changing captcha signatures

concrete/blocks/form/add.php, concrete/blocks/form/controller.php, concrete/blocks/form/form_setup_html.php, concrete/blocks/form/mini_survey.php, concrete/blocks/form/tools/services.php
Ref. #4723
In particular, [without this](https://github.com/concrete5/concrete5/compare/develop...mlocati:fixwarnings-legacy-form-block?expand=1#diff-5a255818ba8e8f58cbd838bf0d6758b6R361) we had a fatal error with PHP 7.2
=> Avoid accessing undefined vars in legacy form block

concrete/elements/custom_style.php, concrete/src/Area/CustomStyle.php, concrete/src/Block/CustomStyle.php, concrete/src/StyleCustomizer/Inline/StyleSet.php
The shadow styling for blocks and areas needed to be improved on. This adds several improvements:
1- Added the transparency option for the shadow color so now RGBA colors are possible instead of just RGB. It seems to me that a shadow without an alpha layer is missing something
2- The only thing a shadow MUST have is a color and then if a color is set at least one of the other variables (blur, spread, horizontal or vertical offset). The shadows were set so that they would only be saved if the horizontal offset was set which makes no sense. Shadows don't require a horizontal offset, it's only an option. So now it checks that a color is set and at least one of the other variables.
3- Shadow would only be applied if a spread value was set which makes no sense because as explained above, …
=> Better Block/Area shadow styling

concrete/attributes/select/controller.php
I have run into the occasion when adding a select attribute to express form and leaving a text attribute (that is required) blank that the function will receive the $value parameter as an array - the issue is that you can't call explode on an array of course as it fatally crashes.
=> Update select controller

concrete/controllers/backend/file/folder.php
This pull request stops users putting in null/empty folders in the file manager.
=> Do not allow folder names to be null in file manager

concrete/src/Page/Controller/DashboardAttributesPageController.php
User attribute can't update when the attribute belongs to any set.
This PR fixes the issue.
- Add custom attribute for members.
- Add a group set.
- Associate the attributes into the set.
- Now, try to edit the attribute.
- It'll show updated successfully, but not.
=> User attribute update issue fix

concrete/src/File/Type/Inspector/FlvInspector.php, concrete/src/File/Type/Inspector/ImageInspector.php, concrete/src/File/Type/Inspector/Inspector.php
- add PHPDoc to File inspectors
- get rid of reprecated methods
- don't die in case of errors (missing attributes, failure to inspect the image size, ...)
Bonus track: even if I don't think that someone still uses it, I fixed the FLV inspector (it gave me totally random values for the width/height/duration)
=>  File inspectors: improve, add PHPDoc, and get rid of deprecated methods 

concrete/blocks/desktop_app_status/view.php, concrete/src/Application/Service/UserInterface/Help/DashboardManager.php
The update pages has been moved from backup section of System and Settings of Dashboard to Updates. But some links URL was left unchanged, now some users are claiming that they're getting 404 error.
I've done quick search of
[concrete5]/index.php/dashboard/system/backup/update
and changed them to
[concrete5]/index.php/dashboard/system/update/update
=> Dashboard's Update pages has been moved, and now link is still unchanged and get 404

concrete/blocks/core_scrapbook_display/controller.php
Blocks that register assets break when pasted from the clipboard after reload. By calling registerViewAssets (if available) this is solved.
=> Register assets from copied block

concrete/src/Html/Image.php
As detailed in my bug report <http://www.concrete5.org/developers/bugs/8-3-1/exception-on-login-page-when-mobile-theme-switcher-is-active-and>, if mobile theme switching is enabled, and you visit the login page on a mobile device, an exception is raised, because in this case a theme object is returned and fed into an SQL query. Simple fix which extracts the theme handle and uses that instead.
=> Fix exception accessing /login with mobile theme switching enabled using a mobile device

concrete/src/Support/Symbol/MetadataGenerator.php
What about suggesting the IDE that the result of `$em->find(EntityClass::class)` is an instance of `EntityClass`?
PS: this will help developers using PHPStorm or Eclipse+[concrete5 plugin](https://mlocati.github.io/concrete5-eclipse-plugin/), provided that they run the `c5:ide-symbols` CLI command.
=> Add EntityManagerInterface::find support to .phpstorm.meta.php

concrete/src/File/FileServiceProvider.php, concrete/src/Support/Facade/Image.php
To retrieve the currently defined image library we currently have these options:
1. use the Image facade
2. manually check the `concrete.file_manager.images.manipulation_library` configuration key
What about simplifying our life simply by calling
```php
$app->make(\Imagine\Image\ImagineInterface::class);
```
(that would also allow us to use `ImagineInterface` with dependency iniection).
=> Allow using DI to get the configured Image library

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php, concrete/src/User/RegistrationService.php
OAuth authentication controllers contain code to determine a free username starting from user's details.
What about moving this code to a service class, so that other code may reuse this function?
=> Add RegistrationService::getNewUsernameFromUserDetails()

concrete/blocks/youtube/view.php
This small change just forces the parameter show info to be set to 0 when disabling show video information. Currently if you disable show video information, it will still show video information.
I also updated the loop parameter to work correctly according to the YouTube documents ( https://developers.google.com/youtube/player_parameters#loop ) regarding single videos.
=> Fixed Youtube block video issues with showinfo and loop.

concrete/bootstrap/configure.php, concrete/src/Multilingual/Service/Extractor.php
Some translation requirements could be in service code i.e. a form builder 
```php
application/src/Forms
$builder->add('input', InputType::Text, ['placeholder' => t('hello world')]);
```
Adding this scan would be a nice little enhancement
=> Scan the SRC directory within the application for translatable strings

concrete/src/Updater/Update.php
The current "check for updates" dashboard page doesn't report the latest version because of a bug in the cache reading/writing process: let's fix this.
=> Fix storing/reading cache item about last available version

concrete/src/Multilingual/Service/Extractor.php
=> Fix directory name in extract package strings

concrete/controllers/single_page/dashboard/pages/themes.php, concrete/single_pages/dashboard/pages/themes/view.php
Currently in concrete5 in the themes page in the dashboard it is possible to delete the active theme (or core themes) by just clicking on remove (works on chrome 63) even though it is shown as disabled it is not disabled. if a theme removal fails no error message is shown.
This pull requests removes the ability for users to be able to delete core themes and active site themes. This also fixes the issue with no error messages being shown on the theme page if an uninstall fails.
=> Fixed users being able to delete core and active themes.

concrete/src/Asset/Asset.php, concrete/src/Asset/AssetInterface.php
- Add PHPDoc to `AssetInterface`
- Add PHPDoc to `Asset`
- move `ASSET_POSITION_HEADER` and `ASSET_POSITION_FOOTER` from `Asset` to `AssetInterface`
- get rid of deprecated methods in `Asset`
- avoid accessing undefined array indexes in `Asset::register`
Ref. #4723
=> Asset refactoring

concrete/controllers/single_page/login.php, concrete/src/Http/ResponseFactory.php, concrete/src/User/PostLoginLocation.php
What about moving the handling of the post-login URL in a service class?
Why?
- we have a simple & single way to handle it
- to retrieve the post-login URL we currently have to call methods of the Login controller (which furthermore erases the values stored in the session, so it's a destructive approach)
- we sometimes set `rcID` and sometimes `rUri` to describe the destination. A mess.
- it's easier to override
BC breaks:
- packages that relies on the `rcID` / `rUri` session keys will break
=> Move the post-login URL management to a service class

concrete/config/database.php, concrete/src/Database/Connection/Connection.php, concrete/src/Package/StartingPointPackage.php, concrete/src/Updater/Update.php
Doctrine DBAL does not currently support creating indexes on TEXT fields (see https://github.com/doctrine/dbal/issues/1597, https://github.com/doctrine/dbal/pull/2412, https://github.com/doctrine/dbal/issues/2368), so we currently create them at install time (see [`StartingPointPackage::indexAdditionalDatabaseFields()`](https://github.com/concrete5/concrete5/blob/8.3.1/concrete/src/Package/StartingPointPackage.php#L386-L392).
What about being sure that those indexes are created even after upgrades?
In particular, the lack of the index on the `PagePaths`.`cPath` database field has a big performance impact...
=> Add indexes on text fields

concrete/src/Console/Command/CompareSchemaCommand.php, concrete/src/Updater/Migrations/Migrations/Version20180119000000.php
This is a continuation of #6311
I installed concrete5 7.5.12, and I migrated it to the `release/8.3.2`.
The only schema differences were 3 missing foreign keys in the `ExpressEntities` table: this pull request fixes this.
I also fixed the `c5:compare-schema` CLI command: it now "hides" only the difference about the indexes of TEXT fields.
With this PR here's the results after migration from 7.5.12 to 8.3.2:
```sh
$ ./concrete/bin/concrete5 c5:compare-schema
No differences found between schema and database.
```
=> Fix migrations - Part II

concrete/src/Page/PageList.php, concrete/src/Search/ItemList/Database/ItemList.php
In MySQL 5.7, the fields included in the `ORDER BY` list of `SELECT DISTINCT` queries must be present in the selected fields.
This causes, for instance, this error in the default content at the page `/blog/topic/32/humor`:
```
An exception occurred while executing '
SELECT distinct
p.cID,
p.cDisplayOrder
FROM
Pages p
LEFT JOIN PagePaths pp ON (p.cID = pp.cID and pp.ppIsCanonical = true)
LEFT JOIN PageSearchIndex psi ON p.cID = psi.cID
LEFT JOIN PageTypes pt ON p.ptID = pt.ptID
INNER JOIN Collections c ON p.cID = c.cID
INNER JOIN CollectionVersions cv ON p.cID = cv.cID
LEFT JOIN CollectionSearchIndexAttributes csi ON c.cID = csi.cID
INNER JOIN CollectionAttributeValues cavTopics ON cv.cID = cavTopics.cID and cv.cvID = cavTopics.cvID
INNER JOIN AttributeValues av ON cavTopics.avID = av.avID …
```
=> ItemList: fix order by fields not in selected fields

concrete/blocks/calendar/db.xml, concrete/blocks/document_library/db.xml, concrete/blocks/event_list/db.xml, concrete/blocks/express_entry_list/db.xml
What about getting rid of the old AXMLS for these db.xml files?
Please remark that [we had a couple of errors](https://github.com/concrete5/concrete5/commit/5867893d575d56db2f8f6d16f0d91e236026f56d)  in the db.xml file of the ExpressEntryList block type.
It's not clear if we wanted the fields `btExpressEntryList`.`linkedProperties` and `btExpressEntryList`.`searchProperties` as `TEXT` fileds or as `VARCHAR` fields. For now I just kept the currently definition we have in the generated schema (`VARCHAR(255)`): is this ok? Or should they be `TEXT`?
PS: to convert from AXMLS to DoctrineXML I used http://concrete5.github.io/doctrine-xml/
=> Convert db.xml files from AXMLS to DoctrineXML

concrete/src/Page/PageList.php
In #6318 we added to the selected fields the ones we sort by.
This causes prolems in the PageList::sortByRelevance method, which tries to sort by an undefined field.
=> PageList: add match score before sorting by it

concrete/src/Cache/CacheServiceProvider.php
We currently declare that cache *handles* (`'cache/request'`, `'cache/expensive'`, ...) are singletons.
BTW the actual classes (`Concrete\Core\Cache\Level\RequestCache`, `Concrete\Core\Cache\Level\ExpensiveCache`, ...) are not singletons.
That means that
```php
$app->make('cache/request')
```
always returns the same instance, but
```php
$app->make('Concrete\Core\Cache\Level\RequestCache')
```
always returns a new instance.
What about always using the same instance?
=> Be sure that caches are singletons

concrete/src/Attribute/Key/SearchIndexer/StandardSearchIndexer.php
=> Avoid accessing an undefined array index in StandardSearchIndexer::setTypeLength

concrete/src/Application/Application.php, concrete/src/Captcha/SecurimageController.php, concrete/src/Support/Symbol/MetadataGenerator.php
This allows IDEs that use `.phpstorm.meta.php` to resolve the followings:
- `$app->make('Concrete\Core\Captcha\CaptchaInterface')`
🠞 `Concrete\Core\Captcha\SecurimageController`
- `$app->make('Illuminate\Container\Container')`
🠞 `Concrete\Core\Application\Application`
- `$app->make('app')`
🠞 `Concrete\Core\Application\Application`
- `$app->make('console')`
🠞 `Concrete\Core\Console\Application`
=> Add to IDE Metadata the registered instances

concrete/src/Application/Service/UserInterface.php
`\Concrete\Core\Application\Service\UserInterface::renderError` renders error view with status code 200. That's why monitoring tool can't catch c5 site down. Let's return properly status code.
=> Send 500 code instead of 200 on creating an error response

concrete/src/Support/Facade/Url.php
`Router::route()` is not a static method: let's call in in a non-static way.
Ref: #4723
=> Url::route(): avoid accessing a non-static method statically

concrete/blocks/survey/controller.php
`$this->cID` is no longer declared in `action_form_save_vote()` because the `on_start()` method has been removed
=> Survey block - missing cID when voting

concrete/src/Session/SessionValidator.php, tests/helpers/TestHeadersTrait.php, tests/tests/Session/SessionFactoryTest.php, tests/tests/Session/SessionValidatorTest.php
Let's execute the tests that require that the headers are not sent.
This relealed a failing test: `SessionValidatorTest::testSetsOnFirstCheck()` sets a `Request` instance, but the `IPService` used by `SessionValidator` was using a different `Request` instance: let's fix that too.
=> Execute tests that require that headers are not sent

concrete/src/Legacy/Controller/ToolController.php
When requesting an invalid tool path (eg `/index.php/tools/required/foo/bar`), we currently return an empty 200 response.
Let's return a 404 response instead.
=> Return 404 when requesting an invalid tool

concrete/src/Routing/DispatcherRouteCallback.php
The `notFound` method of `ResponseFactoryInterface` requires at least one argument (the response content).
=> Fix the call to ResponseFactoryInterface::notFound() in DispatcherRouteCallback

concrete/controllers/single_page/page_forbidden.php, concrete/src/Page/Controller/PageController.php
The PageController::isValidControllerTask checks against the non-existing `Concrete\Controller\PageForbidden` class.
Furthermore, it doesn't support extending the (correct) `Concrete\Controller\SinglePage\PageForbidden` class: let's check with `instanceof` instead of matching the exact class name,
=> Fix handling of page_forbidden

concrete/controllers/single_page/dashboard/sitemap/explore.php, concrete/single_pages/dashboard/sitemap/explore.php
In the flat sitemap we output the sitemaplogic even if the users don't have access to the sitemap (leading to unnecessary assets loading and accessing undefined vars).
Ref #4723
=> Avoid deprecated methods in dashboard/sitemap/explore, fix logic

concrete/blocks/faq/view.php
I think that "<p>"tag in line 21 is unnecessary.
It is because the "<p>"tag is attached in the editor.
This is because if there is a "<p>"tag it gets doubly attached.
=> Correction of view of FAQ block

concrete/src/Updater/Migrations/Migrations/Version20171110032423.php
I saw a situation where the migration failed because of duplicated foreign key names.
I've been able to solve this by dropping the foreign keys of the calendar backup tables.
=> Drop foreign keys for Calendar backup tables

concrete/src/File/ImportProcessor/AutorotateImageProcessor.php
1. Don't load (and save) the image if it's not rotated
2. Use the configured JPEG quality compression when saving the rotated image
Point 1 requires loading the file once more, but it's fast since since we don't actually create an image, just read its metadata. Furthermore for a cleaner approach we'd require https://github.com/avalanche123/Imagine/pull/580 (but since Imagine is updated very infrequently I opted for the approach included in this PR).
=> Fix autorotate image processor

concrete/config/concrete.php, concrete/src/Entity/Site/Locale.php, concrete/src/Site/Locale/Listener.php, concrete/src/Updater/Migrations/Migrations/Version20180213000000.php
Since #5866 we have the possibility to change the locale of a site section.
I forgot to update the `mpLocale` and `mpLanguage` columns of the table `MultilingualPageRelations` for the affected pages.
=> Fix locale and language of MultilingualPageRelations when site locale changes

concrete/jobs/fill_thumbnails_table.php
I was translating the job and got confused.
So I would like to suggest the change of the name, description and return text.
When I was translating the new text string, I got confused which "table" this job is going to fill.
When I read the code and understood that it's repopulating the path in thumbnail path database table.
I think the beginner concrete5 user will confuse the name of the current job, description and return text.
But I don't want to change too much to change too much such as Class name, installation files and etc.
@biplobice, @deek87 and I had a short discussion and came to this sentences.
Thanks.
=> Revise fill thumbnail job name, description and return text

concrete/src/Calendar/Event/EventService.php
This fixes an issue wherein an upgraded site would be unable to edit existing events. By capturing the persisted value and using that instead of the original entity we are giving the entity manager a chance to do its magic.
=> Capture the persisted entity for association, make it possible to save events

concrete/src/Page/Page.php
This adds a DocBlock to the addBlock method in Concrete\Core\Page\Page class.
It was unclear what parameters needed to be passed to this method with the names given to the parameters. This adds a DocBlock for this method detailing what parameters are passed and what is returned.
=> Adds a DocBlock for the addBlock method in Concrete\Core\Page

concrete/controllers/dialog/express/search.php, concrete/controllers/element/dashboard/express/entries/header.php, concrete/elements/dashboard/express/entries/header.php, concrete/views/dialogs/express/entry/search.php
When selecting Express entries in page attributes, there was no way to filter them by search query. This PR adds the default search header to this selector. So now you can search through all entries to find the one you're looking for.
=> Adds search header to express entity selector

concrete/src/File/Set/Set.php
Due to theyr flexible nature filesets can be a very helpful tool to use in packages.
We use it in our gallery package to define Image Albums for Example.
However, that can lead to orphaned references when Filesets are deleted over the c5 Dashboard. Having a event dispatched enables package developers to hook into it and take apropriate cleanup reactions within their package controller whenever a FileSet is deleted.
=> dispatch a additional event when File Sets are deleted.

concrete/controllers/dialog/event/edit.php
The form passes a `0` if you unset the associated "More Details Link Destination" page. This would get lost in our controller, so I've updated the controller so that it handles it properly.
=> Allow unsetting the "More Details Link"

concrete/src/Editor/CkeditorEditor.php
When using CKEditor in dashboard single pages and non-pages, the Styles drop-down is blank. The `getEditorSnippetsAndClasses()` method expects CKEditor to be used on a non-dashboard page and to have a theme. 
This pull request gets the current site theme when a page has no theme or if CKEditor is used in an element or other non-page.
**Examples of blank CKEditor Styles drop-down:**
- The Add Event modal
Dashboard > Calendars & Events > View Calendar > Add Event button
concrete\elements\event\form.php
- Single pages using CKEditor 
Paste the following code into accessibility.php
concrete\single_pages\dashboard\system\basics\accessibility.php
```
<div class="form-group">
<label for="name" class="control-label">
<?= t('Test'); ?>
</label>
<?= …
```
=> Get theme editor classes when using CKEditor in dashboard single pages and non-pages

concrete/elements/attribute/editable_list.php
=> Avoid accessing an undefined variable in attribute/editable_list element

concrete/src/Foundation/Runtime/Run/DefaultRunner.php
To upgrade concrete5, we may want to do that via the CLI interface.
BTW, the core currently self-upgrades itself if needed when a web request is fulfilled.
Let's inhibit automatic upgrades via web when the website is in maintenance mode, so that site operators can upgrade it manually.
Ref. https://github.com/concrete5/concrete5/issues/6450#issuecomment-368321469
=> Do not automatically upgrade the core in maintenance mode

concrete/config/app.php, concrete/controllers/upgrade.php, concrete/src/Application/Application.php, concrete/src/Console/Command/UpdateCommand.php, concrete/src/System/Mutex/FileLockMutex.php, concrete/src/System/Mutex/InvalidMutexKeyException.php, concrete/src/System/Mutex/MutexBusyException.php, concrete/src/System/Mutex/MutexInterface.php, concrete/src/System/Mutex/MutexTrait.php, concrete/src/System/Mutex/SemaphoreMutex.php, concrete/src/System/SystemServiceProvider.php, concrete/src/Updater/Update.php, tests/assets/System/acquire-mutex.php, tests/tests/System/MutexTest.php
On high-traffic sites, we may have that `Update::updateToCurrentVersion()` is executed simultaneously more that one time, leading to unexpected results.
What about protecting us from that by using mutex?
I added two mutex implementations here: one based on PHP Semaphores (it requires that PHP is compiled with the ` --enable-sysvsem` option), and another one based on file locks.
I also included a test case to check that these mutex works. I don't think that TravisCI supports Semaphores by default, but I tested with a PHP 7.0 compiled with ` --enable-sysvsem` and test passes.
=> Inhibit concurrent execution of Update::updateToCurrentVersion()

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/extend/install.php, concrete/single_pages/dashboard/extend/connect.php, concrete/src/Console/Command/InstallPackageCommand.php, concrete/src/Localization/Service/TranslationsChecker.php, concrete/src/Localization/Service/TranslationsInstaller.php, concrete/src/Marketplace/Marketplace.php
What about automatically downloading language files when a package is installed?
When installing a package via the dashboard, this option is controlled by the new `concrete.i18n.auto_install_package_languages` configuration key.
When installing a package via the CLI command, users may specify if they want to download the language files or not with the new `--get-languages` option (if this option is not specified, we'll use the `concrete.i18n.auto_install_package_languages` configuration key).
The language files that will be downloaded are the ones used in the site (that is, the languages of the multilingual sections and the languages of the site interface).
=> Install language files when installing packages

concrete/src/Console/Application.php, concrete/src/Console/Command/IsInstalledCommand.php
What about adding a new `c5:is-installed` command?
This would allow for instance fancy stuff file adding this to `composer.json`:
```json
{
"scripts": {
"pre-update-cmd": "concrete5 c5:is-installed && concrete5 c5:set -g concrete.maintenance_mode true",
"post-update-cmd": "concrete5 c5:is-installed && concrete5 c5:update --no-interaction >/var/log/concrete5-upgrade.log 2>&1 && concrete5 c5:set -g concrete.maintenance_mode false",
}
}
```
(PS: the above json is totally untested, but it seems quite interesting)
=> Add c5:is-installed CLI command

concrete/src/Page/Collection/Version/Version.php
That way we can update concrete5 from previous versions.
Without this chamge, I have the following error while updating the core:
```
Refreshing schema for Concrete\Core\Entity\Calendar\CalendarEventVersion...
Refreshing schema for Concrete\Core\Entity\Express\Entity...
Refreshing schema for Concrete\Core\Entity\Express\Form...
Refreshing schema for Concrete\Core\Entity\Package...
Updating database tables found in doctrine xml...
Creating single page at /dashboard/system/mail/addresses...
An exception occurred while executing 'select cvID, cvIsApproved, cvIsNew, cvHandle, cvName, cvDescription, cvDateCreated, cvDatePublic, pTemplateID, cvAuthorUID, cvApproverUID, cvComments, pThemeID, cvPublishDate, cvPublishEndDate from CollectionVersions where cID = ? order by cvID desc' with params …
```
=> Avoid referencing cvPublishEndDate

concrete/config/app.php, concrete/src/System/Mutex/MutexTrait.php, concrete/src/Updater/Update.php
Having the list of registered mutex keys stored as a plain array makes 3rd party packages hard to use it.
Indeed, to add a new mutex key, we should (a) copy the entire `app.mutes` array the application config, or add a specific numeric key to the application config.
Switching to a key-value approach allows simply adding new keys to the mutex array.
=> Simpler mutex configuration

concrete/src/Entity/File/Version.php
When loading an image, we check if it is an SVG and, if so, we'll try to use Imagick instead of GD to load it (because GD can't load SVG images).
BTW, I've seen that the system may detect that SVG images have a `text/plain` content type. Let's consider this case.
=> Consider text/plain images as SVG images

concrete/src/Console/Command.php, concrete/src/Console/Command/ClearCacheCommand.php, concrete/src/Console/Command/ConfigCommand.php, concrete/src/Console/Command/GenerateIDESymbolsCommand.php, concrete/src/Console/Command/InstallCommand.php, concrete/src/Console/Command/InstallLanguageCommand.php, concrete/src/Console/Command/InstallPackageCommand.php, concrete/src/Console/Command/ResetCommand.php, concrete/src/Console/Command/TranslatePackageCommand.php, concrete/src/Console/Command/UninstallPackageCommand.php, concrete/src/Console/Command/UpdateCommand.php, concrete/src/Console/Command/UpdatePackageCommand.php, concrete/src/Foundation/Environment/User.php
Some commands shouldn't be executed as root.
What about discouraging it?
- add a new `--allow-as-root` option: if specified, we have the current behaviour (users may execute the commands as root)
- if the `--allow-as-root` option is not specified
- if the user is root and the `--no-interaction` option is specified: abort operation
- if the user is root and the `--no-interaction` option is not specified: ask users if they want to proceed
Examples:
=> Discourage running some CLI commands as root

.travis.yml
We install and use PHPUnit via composer: it's useless ([and may lead to problems](https://travis-ci.org/concrete5/concrete5/jobs/349332932#L332)) showing the version of the preinstalled PHPUnit
=> Don't show system-wide PHPUnit version

concrete/controllers/backend/user_interface.php, concrete/controllers/upgrade.php, concrete/src/Application/Application.php, concrete/src/Foundation/Runtime/Run/DefaultRunner.php, concrete/src/Updater/Migrations/LongRunningMigrationInterface.php, concrete/src/Updater/Migrations/MigrationIncompleteException.php, concrete/src/Updater/Migrations/Migrations/Version20150504000000.php, concrete/src/Updater/Migrations/Migrations/Version20160725000000.php, concrete/src/Updater/Migrations/Migrations/Version20170316000000.php, concrete/src/Updater/Migrations/Migrations/Version20170412000000.php, concrete/src/Updater/Migrations/Migrations/Version20171110032423.php, concrete/src/Updater/Update.php
The automatic upgrade process via web interface suffers the following problems:
1. if a visitor quits the browser while the upgrade is in progress, the PHP execution could halt.
2. the update process may require long time, because of many migrations need to be executed or because a migration requires long time to be executed, and the PHP execution may reach its maximum time limit.
To solve 1.  we can call [`ignore_user_abort`](http://php.net/manual/en/function.ignore-user-abort.php).
To solve 2:
- Let's try to increase the PHP execution time limit with `set_time_limit`
- If `set_time_limit` fails (or can't be executed), let's ask the client to reload the requested page when:
- we executed 10 migrations
- or we executed some migrations and the next migration to be executed will require …
=> Avoid breaking the update process

concrete/blocks/youtube/controller.php, concrete/blocks/youtube/db.xml, concrete/blocks/youtube/form_setup_html.php, concrete/blocks/youtube/view.php
Thought I'd try to help out while posting an issue of my own :) My IDE has made a few tabbing changes, hope that's ok.
YouTube block changes for https://github.com/concrete5/concrete5/issues/6452
The block will respect the t parameter in the url.
I've also added a way of doing this through the block settings, which will take priority over what's in the url. Works with formats `1:20:30` (`h:m:s`) and `1h20m30s` (or just `20m30s`, or `30s`)
=> youtube block start time options

concrete/controllers/dialog/event/edit.php
We were calling `$version->setPageObject(0)` when this method only accepts instances of `Page`. Instead let's call `$version->setPageID(0)` to unset.
=> Fix unsetting the selected page for an event version

concrete/src/Entity/Search/SavedSearch.php
Fix "Class PackageClass\Property\Search\Query does not exist" does not exist from custom SavedSearch
=> Fix Class "Query" does not exist

concrete/blocks/autonav/nav_item.php
This `use` statement is required [here](https://github.com/mlocati/concrete5/blob/8e91e60cd32a1a2333420428d0c34d53c80402bf/concrete/blocks/autonav/nav_item.php#L107)
=> Fix determination of homepage ID in getURL method of nav_item block controller

concrete/src/Console/Command/InstallCommand.php
99% of times, we use the same value for the `--language` and `--site-locale` options: so let's make the default value of `--site-locale` the same as `--language` when installing in an interactive way.
Furthermore, let's allow users to edit the options at the end of the cycle.
Sample session (note the default value of *The default site locale*, and the final two lines:
```
$ ./concrete5 c5:install -i
Checking required preconditions:
- PHP 5.5.9... passed (you are running PHP version 7.0.28-0ubuntu0.16.04.1).
- MySQL PDO Extension Enabled... passed.
- JSON Extension Enabled... passed.
- DOM Extension Enabled... passed.
- ASP Style Tags Disabled... passed.
- Fileinfo Extension Enabled... passed.
- Image Manipulation Available... passed.
- XML Support... passed.
- Writable Files and …
```
=> Improve CLI install

concrete/src/File/FolderItemList.php
I'm building a website that has 200+ editors. Each editor can upload files to the file manager, but they can search only files that uploaded by themselves. 2k+ files are already uploaded to the file manager.
Now, the file manager is extremely slow. The reason is new `PagerAdapter`. Let me clear the recent change of Pager class.
Before: Get 1k items, then check permission of each items, then slice
After: Get 10 items, then check permission of each items. If the number of result is less than 10 items, get more 10 items repeatedly.
The new style should improve performance in the case "The user can access almost all of files". However, it generate a lot of queries and decrease performance in the case "The user can't access almost all of files".
For example, if the current user can only 1 file …
=> Improve performance of file manager

concrete/src/Area/Layout/Preset/Formatter/ThemeFormatter.php
Some manual grids and grid systems control row column count using things like flexbox or nth-child selectors. Currently, layout presets always add a container element, this prevents these types of column control approaches.
An example is if you have multiple rows of 3 columns. At smaller screen widths your only option is going to 1 column and stacking vertically, if you switch to 2 columns the columns will be unevenly distributed. Without the container element, you could switch to 2 columns as a screen gets more narrow and then one.
In the below examples, the black line is the container element added in the layout preset and the red is the container element in your theme HTML.
**Example: 3 layout presets of 3 columns with container element**
**Example: 3 layout presets of 3 columns with …
=> Allow layout presets to optionally have no container element defined

concrete/config/concrete.php, concrete/controllers/backend/file/thumbnailer.php, concrete/controllers/single_page/dashboard/system/files/thumbnails.php, concrete/jobs/fill_thumbnails_table.php, concrete/single_pages/dashboard/system/files/thumbnails.php, concrete/src/Backup/ContentImporter/Importer/Routine/ImportFileImportantThumbnailTypesRoutine.php, concrete/src/Console/Application.php, concrete/src/Console/Command/FillThumbnailsTableCommand.php, concrete/src/Entity/File/File.php, concrete/src/Entity/File/Image/Thumbnail/Type/Type.php, concrete/src/Entity/File/Image/Thumbnail/Type/TypeFileSet.php, concrete/src/Entity/File/Version.php, concrete/src/File/Image/Thumbnail/Path/Resolver.php, concrete/src/File/Image/Thumbnail/Type/Type.php, concrete/src/File/Image/Thumbnail/Type/Version.php, concrete/src/File/Set/Set.php, concrete/src/Updater/Migrations/Migrations/Version20180215000000.php, concrete/src/Updater/Migrations/Migrations/Version20180302080830.php, concrete/views/dialogs/file/thumbnails.php
This PR allows us to specify that a specific thumbnail type is valid only for files in specific file sets (or for files that are not in specific file sets).
Here's a screenshot of the relevant part of the dashboard page:
Fix #3559
=> Implement Conditional thumbnails

concrete/src/User/UserInfo.php
Fix #6283
The target on the user column in the table **UserAttributeValues** is not the `UserInfo` class but the `Concrete\Core\Entity\User\User` entity, so we should use the `getEntityObject()` method to pass the correct object.
(Note: this method is also used in the `Concrete\Core\Export\Item\User` class to get all user attributes)
=> Use the user entity to delete all user attribute values

concrete/single_pages/dashboard/pages/types/output.php
I made an error in translating text in a previous pull request.
=> fix incorrect page template default text translation

concrete/blocks/social_links/view.php, concrete/src/Sharing/SocialNetwork/Service.php
https://github.com/concrete5/concrete5/issues/6565
This pull request makes the Social Links block links more accessible.
**link**
**icon**
**link**
**icon**
=> Add aria attributes and title to Social Links block links and icons

tests/README.md
Running all tests takes ages and it's not immediately clear how one could run a single test. This PR adds an example of how to run a single test.
```bash
composer test -- --filter testCoreBlockView
```
=> Add instructions to run a single test

concrete/js/build/core/app/remote-marketplace.js, concrete/single_pages/dashboard/extend/update.php
I noticed that the link "More Details" doesn't do anything. There is [no `max-height`](https://github.com/concrete5/concrete5/search?utf8=%E2%9C%93&q=ccm-marketplace-update-changelog&type=) set to the `ccm-marketplace-update-changelog` wrapping div.
This PR removes the links and the corresponding JavaScript.
---
The yellow link will be removed:
=> Remove 'More Details' link from package upgrade page

tests/README.md
Adding an additional user for the `::1` hostname, solved running the tests for me on Windows. This PR updates the instructions in the README.
```
$ composer test
> phpunit
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1045] Access denied for user 'travis'@'::1' (using password: NO) in file C:\dev\c5\concrete\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 47
```
=> Add IPv6 user to test instructions

tests/tests/Block/BlockViewTemplateTest.php
We can't use `$pkg = new Package();`, because the Application parameter is required. 
This PR uses mocks of the Package object instead.
=> Fix booting package object in test class

concrete/src/Editor/CkeditorEditor.php
In 8.3 @MrKarlDilkington  added some configuration options to the Ckeditor that allow us to customize it's behaviour.
However, the order in wich the options are merged prevents us from overriding options already set in
\concrete\src\Editor\CkeditorEditor.php - This PR changes merge order to enable us to override those settings in config.
The way "allowedContent" config options is set to true in the core completely disables all Advanced Content Filtering features of CKEditor.
We would like to make use of these features in order to filter content that is pasted from MS Word and other external sources.
This allows us to override the option in config and add more sophisticated content/ paste filtering.
=> Change merge order of CKEditor config options to enable overrides

concrete/src/Block/Events/BlockBeforeRender.php, concrete/src/Block/View/BlockView.php, tests/tests/Block/BlockViewTest.php
This will trigger an event when the block is about to be rendered*. Hooking into this event makes it possible to prevent it from displaying. 
```php
Events::addListener('on_block_before_render', function ($event) {
$event->preventRendering();
return $event;
});
```
---
*) for naming convention see also https://github.com/concrete5/concrete5/issues/6574
=> Add on_block_before_render event

concrete/config/app.php, concrete/src/System/Mutex/FileLockMutex.php, concrete/src/System/Mutex/InvalidMutexKeyException.php, concrete/src/System/Mutex/MutexTrait.php, concrete/src/System/Mutex/SemaphoreMutex.php, concrete/src/System/SystemServiceProvider.php, tests/tests/System/MutexTest.php
Having a fixed dictionary for mutex keys can limit what we can do with mutexes.
Let's avoid this limit.
=> Avoid the need of a fixed dictionary for the mutex system

concrete/src/Express/Search/Column/AssociationColumn.php
Please check `$this->association` is the object like `getColumnValue` method. It may be null when the class is wakeup
=> Check is object to avoid error on search express entities

concrete/single_pages/dashboard/system/update/update.php
It appears to be fairly common that users apply version updates on production sites without making a backup first. A warning may help remind them that backups should be done before all updates.
**Current:**
**Changes:**
=> Backup before update warning message

concrete/src/Updater/Migrations/Migrations/Version20180328215345.php
There's no problem if migration 20180328215345 is excuted more than once, so let's mark it as repeatable.
This is very important, otherwise the `--rerun` option of the `c5:update` command won't be able to execute this migration and all the migrations that precede it: `--rerun` will only let users execute migrations *after* this 20180328215345.
=> Mark migration 20180328215345 as repeatable

tests/tests/Update/RepeatableMigrationsTest.php
When we create a new migration, 99% of times it is repeatable, so let's add a test case to check this.
This new test case checks that all migrations are marked as repeatable, except the ones explicitly listed in the `$allowedNotRepeatableMigrations` property of this new  `RepeatableMigrationsTest` test.
This new test case helps a lot avoiding problems like these:
- #6382
- https://github.com/concrete5/concrete5/pull/6475#pullrequestreview-99785254
- https://github.com/concrete5/concrete5/pull/6539#pullrequestreview-108195062
- #6636
Marking migrations as repeatable is very important, because the `--rerun` option of the `c5:update` command can re-execute migrations only if they are repeatable, and all the next migrations are repeatable.
For instance, if we have migrations M1, M2, M3, M4, …
=> Test that migrations are marked as repeatable

concrete/src/Updater/Update.php
`migration->execute('up')` already marks a migrations as migrated, so our `markMigrated` call leads to the following error:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<MigrationVersion>' for key 'PRIMARY'
```
So, let's call `markMigrated` only if `migration->execute('up')` fails.
=> Fix rerunning migrations

concrete/src/Application/Service/FileManager.php
When trying to create a file selector for an element with a name containing special characters like `form[articles[0]]` the following error was thrown:
`Error: Syntax error, unrecognized expression: [data-file-selector=event_form[articles][0][image]]`
By escaping the name part in the jQuery selector this is fixed.
=> Escape element selector for adding file selector

concrete/blocks/document_library/controller.php, concrete/blocks/document_library/view.css
This pull request replaces code that references a package asset. The Document Library block requires Font Awesome, so the package folder.png image is replaced with a Font Awesome font icon.
**Current:**
**Changes:**
=> Add missing folder icon in Document Library block

concrete/js/build/core/file-manager/search.js, concrete/js/build/core/file-manager/selector.js
There are a couple JavaScript warnings: let's fix them.
BTW there's still a reference to an undefined variable at https://github.com/concrete5/concrete5/blob/18b605ddc1d69be461f3cdd0b85ed9f3ab826f58/concrete/js/build/core/layouts.js#L302
Should thst line be
```javascript
for (i = this.columns; i < $columns.length; i++) {
```
instead of
```javascript
for (i = columns; i < $columns.length; i++) {
```
?
=> Fix JavaScript warnings

concrete/src/File/Search/ColumnSet/Column/FileVersionDateAddedColumn.php
If a non super user is using the file manager with sorting by date modified and, the cursor, the file at the bottom of the list has multiple versions then currently concrete5 will get the original date added for the file not the latest date modified of the approved version.
This is because we get the file entity cursor object from the file list and then call getDateAdded() on it. This causes the cursor to be at a wrong place.
An example is if a file that has a date modified of 21st February 2018 and a date added of 1st January 2017 is at the bottom of the list or used as a cursor on 
`concrete5.site/ccm/system/search/files/basic?`
Then all the files on the next page will be older/newer (depending on sort) of 1st January 2017 not 21st February 2018. This can lead to loops ( since there is …
=> Fixes issue when a file with multiple versions is the cursor 

concrete/controllers/backend/user_interface/block.php
In order to avoid data disclosure, generic exceptions may not be shown to the site users (it depends on the `concrete.debug.display_errors` configuration key).
When we want that a specific error message is shown to the user, we should throw `Concrete\Core\Error\UserMessageException` exceptions (see [here](https://github.com/concrete5/concrete5/blob/650c92f5ed90543c7e991781185befc5a1fd43e4/concrete/src/Error/Handler/ErrorHandler.php#L28) for http errors and [here](https://github.com/concrete5/concrete5/blob/650c92f5ed90543c7e991781185befc5a1fd43e4/concrete/src/Error/Handler/JsonErrorHandler.php#L20) for json errors).
=> Use UserMessageException when there are problems in block backend

concrete/blocks/page_list/controller.php
See [this bug report](https://www.concrete5.org/developers/bugs/8-3-2/switching-template-in-design-in-php7.2-generates-count-error/)
=> Call count() only if array in page_list block controller

concrete/single_pages/dashboard/system/mail/addresses.php
https://github.com/concrete5/concrete5/issues/6663
=> Make System Email Addresses dashboard page labels more descriptive

concrete/src/Application/Service/FileManager.php, concrete/src/File/FileList.php, concrete/src/File/FolderItemList.php, concrete/src/File/Search/Field/FileFolderManager.php
It seems that the new `FileFolderManager` only supports filtering by file type: it's very useful if it supported filtering by file extension.
Furthermore, the use of filters in the FileManager is very little documented: let's improve its PHPDoc (and rename a few parameters... `$bf` doesn't tell me much :wink:)
=> Let FileFolderManager filter by file extensions, improve FileManager service

concrete/blocks/content/controller.php, concrete/blocks/image/controller.php, concrete/blocks/image_slider/controller.php
When someone extends a block type, the $tracker property may not be set if they override the controller constructor. This leads to this error:
```
Error thrown with message "Call to a member function track() on null"
```
Let's avoid this BC issue.
=> Tracker may be null in block types

concrete/config/concrete.php, concrete/src/Updater/Migrations/Migrations/Version20180524000000.php
Commit 01cada6eea10c9def51a09ae3e03bdbf77419b5f changed the schema of the `btContentImage` database table, but we didn't have a migration for it.
Thus, for upgraded concrete5 instances we may have:
```sh
$ ./concrete/bin/concrete5/c5:compare-schema
concrete5 found at C:\Dev\Web\concrete5\concrete5.git
1 query found
1: ALTER TABLE btContentImage CHANGE openLinkInNewWindow openLinkInNewWindow TINYINT(1) DEFAULT '0' NOT NULL
```
Let's fix this database difference.
=> Add a migration to refresh the image block type

concrete/src/Job/Job.php
=> Avoid accessing an undefined var in Job::executeJob

concrete/src/Entity/File/Version.php, concrete/src/File/Event/ThumbnailDelete.php, concrete/src/File/Event/ThumbnailGenerate.php
It'd be handy if an event is fired when thumbnails are deleted or regenerated. 
Related issue: https://github.com/concrete5/concrete5/issues/6695
---
When hooking into the events and logging the path:
(I added and removed a file)
=> Add Thumbnail Type events

concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
When migrating address attribute types from concrete5 5.7.x to 8, we currently have 2 problems:
- the list of allowed countries is malformed
- we have an SQL error because we are inserting a row without specifying the (required) value for the `akGeolocateCountry` field.
Let's fix them.
=> Fix migration of address attribute type settings

concrete/controllers/panel/add.php, concrete/src/Page/Stack/Pile/Pile.php
These methods are called statically ([example 1](https://github.com/concrete5/concrete5/blob/e4d73c2f758083d3fa5d40585fdef2a50055fad0/concrete/src/Page/Stack/Pile/PileContent.php#L110), [example 2](https://github.com/concrete5/concrete5/blob/e4d73c2f758083d3fa5d40585fdef2a50055fad0/concrete/tools/pile_manager.php#L47)), so let's mark them as static.
Sure, we should switch to a better approach (services, factories, entities, ...), but let's fix these warnings for the moment.
Ref. #4723
=> Mark static Pile methods as static

concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Since version 3.3.0, `Symfony\Component\HttpFoundation\Response::setTrustedProxies()` [**requires** two arguments](https://github.com/symfony/http-foundation/blob/v3.3.0/Request.php#L594) (merging the functionality of `setTrustedProxies` and `setTrustedHeaderName`).
Since concrete5 [requires 3.*](https://github.com/concrete5/concrete5/blob/24dbaca91cebf4c8ccd181cfeb1f23a6e0217e2c/concrete/composer.json#L34), we need to support both approaches (calling `setTrustedProxies` + `setTrustedHeaderName` vs calling `setTrustedProxies` alone).
PS: it's not the first time they don't follow semver, we have to be very careful when upgrading Symfony.
=> Fix setTrustedProxies for Symfony 3.3.0+

concrete/src/Block/Menu/Menu.php
=> Avoid accessing undefined var in Block/Menu constructor

concrete/src/File/Filesystem.php, concrete/src/Tree/Node/Node.php, concrete/src/Tree/Node/Type/Category.php, concrete/src/Tree/Node/Type/FileFolder.php, concrete/src/Tree/Type/FileManager.php, tests/tests/File/FilesystemTest.php
Here's what we discussed in #6672, with a handy addition: the ability to create folders if they don't exist (plus some phpdocs and [this](https://github.com/concrete5/concrete5/commit/1dcee2fe1cc162acfe13e3697bd020947d8fe285#diff-479422cef7f180fc48e597c997a644ecR564) and [this](https://github.com/concrete5/concrete5/commit/50e92a45043e3668f7eccab5c39cbc831e517764) bug fixes).
One question about [this line](https://github.com/concrete5/concrete5/commit/8c63a1d317d1703ffd63f4a4d1d14aad1f5f501a#diff-65eeada9ffd75ac1f9142813fa390018R112): it works, but is it ok or should we use the `addFolder` method of `Filesystem`?
PS: fix #6672
=> Add FileFolder::getChildFolderByName and FileFolder::getChildFolderByPath

concrete/src/Authentication/AuthenticationTypeController.php
In https://github.com/concrete5/concrete5/pull/6673 the signature of the Login controller method `finishAuthentication` changed.
Most calls were updated, but this call in `AuthenticationTypeController` was missed.
When login in with a third-party authentication type like Twitter the following message appears:
```
Too few arguments to function Concrete\Controller\SinglePage\Login::finishAuthentication(), 1 passed in /Users/fabian/Workspace/concrete5/concrete/src/Authentication/AuthenticationTypeController.php on line 39 and exactly 2 expected
```
The user is already passed to the `completeAuthentication` method, so we can simply forward that argument.
=> Pass user to finishAuthentication in AuthenticationTypeController completeAuthentication

concrete/src/Asset/JavascriptLocalizedAsset.php
If we register a JavascriptLocalizedAsset without specifying a leading `/` for the filename, the asset gets loaded when `concrete.cache.assets` is false, but it doesn't get loaded if its true.
That's because of an unnecessarily convoluted and buggy algorithm to resolve the assets (which furthermore may not work if pretty URLs are not enabled).
Let's simplify this approach, making it simpler and more robust.
=> Fix handling of JavascriptLocalizedAsset URL & path

concrete/controllers/dialog/editor/settings/preview.php
Fix a bug introduced in #6720 which prevents users from viewing the editor preview in the `/dashboard/system/basics/editor` page (it only worked for `admin`).
=> Fix CKEditor configuration preview

concrete/src/Multilingual/Service/Detector.php
When we detect the browser locale, we can for example resolve the `it` language code specified by the browser to the `it_IT` multilingual section.
In this case, we store in the `multilingual_default_locale` session key `it` instead of `it_IT`, which is wrong: we should store the actual multilingual section ID, otherwise [this line](https://github.com/concrete5/concrete5/blob/8.4.0/concrete/src/Multilingual/Service/Detector.php#L43) will fail.
=> Use correct locale ID in Multilingual/Service/Detector::getPreferredSection

concrete/elements/footer_required.php
Let's assume that I'm a user that specified English when I logged in, and that I'm viewing a page in Chinese.
I'd expect the concrete5 toolbar and the account menu to be in English (sadly I really can't understand Chinese).
BTW ATM the interface is in Chinese:
With this fix, the interface will be in English:
=> Use UI localization context in concrete5 toolbar & account menu

concrete/src/Package/BrokenPackage.php
1. `t()` is called
2. the localization system initialize itself:
1. it loads the core language files
2. it loads the package language files, which implies listing all the packages marked as installed in the database and creating an instance of package controller of each
3. If there's a problem instantiating a package controller, we create an instance of BrokenPackage
4. In the constructor of the BrokenPackage controller we currently have `t()` calls.
5. since the localization system is not yet loaded, go to point 2. until PHP runs out of memory.
Solution: don't call `t()` in BrokenPackage constructor
PS: this problem does not occur for `en_US`, since no language file is loaded for that locale.
=> Don't call t() in BrokenPackage constructor

concrete/src/Console/Command/InstallLanguageCommand.php
When runnint the `c5:language-install` command, concrete5 assumes (if neither `--core` nor `--packages` are specified) that the user wants to process both core and package languages.
BTW, when concrete5 is not installed, we can't obviously retrieve the list of installed packages, so let's avoid it.
=> Don't try to get package lists when concrete5 is not installed in language-install CLI command

concrete/src/Cache/Driver/FileSystemStashDriver.php
If two concurrent processes are running [these lines](https://github.com/concrete5/concrete5/blob/66a0c288b8b6b990a1a3f1030fd0999d370e48c3/concrete/src/Cache/Driver/FileSystemStashDriver.php#L31-L34), the first process will succeed, but the second one may return false because it tried to create the directory that has been already created by the other process.
So, let's try to see if the directory exists even if mkdir failed.
=> Reduce concurrency problems in FileSystemStashDriver::storeData

concrete/config/concrete.php, concrete/views/frontend/install.php
What about adding a link to the concrete5 Slack channels in the install screen?
=> Add a link to Slack in the install page

concrete/elements/help/dialog/introduction.php
As discussed in https://github.com/concrete5/concrete5/pull/6789#issuecomment-398547137, here's the new link to concrete5 Slack page in the introduction dialog:
We now have a vertical scrollbar... to remove it, we could have two columns of the same width (not included in this PR at the moment):
=> Add link to concrete5 Slack page and fix indentation of intro dialog

concrete/themes/dashboard/elements/footer.php
I noticed that sometimes `$showPrivacyPolicyNotice` is not defined...
Ref. #4723
=> Avoid accessing undefined var in footer element

concrete/src/Multilingual/Service/Extractor.php
In the multilingual Extractor, we extract translatable strings from configuration files.
BTW those strings are not added to the list of extracted strings.
=> Actually add translatable strings extracted from config files to Translations instance

concrete/src/Http/DefaultDispatcher.php
As discussed in #3336
TL;DR: We currently have ~300 registered routes in a bare concrete5 installation. For every request we compile all of them, and implementing a cache is very hard because routes may be dinamically added by packages. This PR strips out from the routes that won't match the request for sure.
=> Faster routes resolution

concrete/src/Mail/Service.php
When we instruct the mail service to throw exceptions on delivery failures, and when we pass `true` for the `$resetData` parameter of the `sendMail` method, exceptions are not thrown.
=> Throw email delivery exceptions even when $resetData is true

concrete/src/Marketplace/Marketplace.php
The main parts of this change are:
- Make this class aware of the application using the `ApplicationAwareInterface`, and to preserve BC, move constructor stuff into the `->setApplication` method
- Consolidate requests to c5.org into a single method that is actively dealing with timeouts
- Added a new constant to mark when a failure is due to timeout.
=> Make marketplace error handling more consolidated and handle timeouts

concrete/src/Block/Events/BlockOutput.php, concrete/src/Block/View/BlockView.php
Fire an event just before a block is outputted / echoed on a page. This allows custom code / add-ons to modify the block's contents on runtime.
---
```php
$dispatcher->addListener('on_block_output', function ($event) {
$event->setContents('Block ID:' . $event->getBlock()->getBlockID());
});
```
=> Add 'on_block_output' event

concrete/bootstrap/configure.php, concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/environment/debug.php, concrete/single_pages/dashboard/system/environment/debug.php, concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Now that concrete5 doesn't throw many warnings (see all the fixes addressing #4723), what about adding an option for developers to consider PHP warnings as errors?
Sure, they could add `error_reporting(-1);` to `/application/bootstrap/start.php`, but it's a manual operation that:
- developers may not think about it
- developers may not be aware of it
- it requires more time than checking an option
I really want this option, and I'd really prefer that any concrete5 core/package developer turns it on: that way we may grant a better and more stable product.
Example of a warning:
=> Add an option to consider warnings as errors

concrete/src/Captcha/SecurimageController.php
I have these warnings in my logs:
```
The $code parameter passed to Securimage::check() must be a string, NULL given
```
This is [caused by Securimage](https://github.com/dapphp/securimage/blob/3.6.7/securimage.php#L1278) when someone tries to do something harmful with the website. Let's avoid this warning.
=> Avoid warning in Securimage::check when no captcha token is received

concrete/blocks/form/controller.php, concrete/mail/block_express_form_submission.php, concrete/mail/block_form_submission.php, concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
I've added $subject variable to email template so that it'll be easier to customize the email template for both Legacy Form and Express Form blocks.
To support backward compatibility, I've added an extra step to insert subject if the email templates didn't set subject.
=> Add $subject to form email templates to make it easier to customize

concrete/src/Editor/CkeditorEditor.php
When building CKEditor options, we have up to 3 option sets:
- the default options, defined in the `getEditorInitJSFunction` method (let's call them `$defaultOptions`)
- dynamically-defined options, passed to the `getEditorInitJSFunction` as an argument (let's call them `$dynamicOptions`)
- custom options defined in the `editor.ckeditor4.toolbar_groups` configuration key (let's call them `$customOptions`)
At the moment, the final option list is built with a code this:
```php
$options = array_merge(
array_merge(
$dynamicOptions,
$defaultOptions,
),
$customConfigOptions
);
```
which can be written as
```php
$options = $customConfigOptions + $defaultOptions + $dynamicOptions;
```
that means that the precedence order (from hight to low) is
1. `$customConfigOptions`
1. `$defaultOptions`
1. …
=> Fix CKEditor options override

concrete/src/Config/Repository/Liaison.php, concrete/src/Config/Repository/Repository.php
I often need to temporarily set a configuration key and execute some code.
What about this implementation?
```php
$config->withKey($keyName, $temporaryValue, function() {
// here the configuration key $keyName will have a value of $temporaryValue
});
// here the configuration key $keyName will have its previous value
```
=> Add "withKey" feature to configuration

concrete/src/Block/Block.php
This PR adds method to the Block class to clear / refresh the block record cache of a block.
Usage:
```php
$block->refreshBlockRecordCache();
```
---
More information about block caching: https://documentation.concrete5.org/developers/working-with-blocks/creating-a-new-block-type/making-blocks-cacheable
=> Add refreshBlockRecordCache method to Block class

concrete/src/Page/Page.php
I grow tired of writing
```php
/** @var \Concrete\Core\Page\Page $page **/
$page = Page::getByID(1);
```
Can we use the FQN instead of the alias?
=> Update return type of Page::getBy* methods

concrete/themes/dashboard/elements/header.php
In the dashboard pages we can override the page title placed in the `<h1>` tag by using a `$pageTitle` variable.
BTW the `<title>` element doesn't reflect this setting: let's do that.
=> Forward $pageTitle to dashboard header element

concrete/config/concrete.php, concrete/config/site.php
Tracking codes has been moved from global configuration to site-specific configuration.
Let's reflect it in the default configuration files.
=> Fix default definition of tracking codes

concrete/src/Http/RequestBase.php
Symphony `Request` has a [more complete approach](https://github.com/symfony/http-foundation/blob/v3.4.8/Request.php#L1347-L1362) that [our `isPost`](https://github.com/concrete5/concrete5/blob/051ee246c4c27599a21ece098b16686835e12170/concrete/src/Http/RequestBase.php#L212) method: let's use it.
=> Use Symfony Request to determine the request method

concrete/controllers/single_page/dashboard/blocks/stacks.php
I'm getting crazy to check if a stack exists for a specific language:
With this edit, it's pretty clear which languages have a specific stack version:
=> Highlight existing localized stacks

concrete/controllers/backend/user_interface/block.php
This fixes the following error:
```
Call to a member function setBlockAreaObject() on a non-object
File: concrete/controllers/backend/user_interface/block.php
Line: 51
```
I don't know when it happens, maybe when a block is removed from a stack but in the concrete5 cache it's still there...
=> Avoid calling setBlockAreaObject on NULL in block backend userinterface controller

concrete/controllers/dialog/user/bulk/delete.php
#6840 is caused by double $ui objects in $this->users array in `concrete/controllers/dialog/user/bulk/delete.php:91`.
=> Fix for #6840

concrete/src/User/UserInfo.php
Related: https://github.com/concrete5/concrete5/issues/6676
=> GDPR - uID cleanup

concrete/blocks/next_previous/controller.php
Hardcoding a `next_previous` block in a template without specifying all the block properties causes PHP warnings.
Because it's not ideal to write
```php
$bt = BlockType::getByHandle('next_previous');
$bt->controller->loopSequence = 1;
$bt->controller->orderBy = 'display_asc';
$bt->controller->nextLabel = '';
$bt->controller->previousLabel = '';
$bt->controller->parentLabel = '';
$bt->render();
```
just to prevent some 'undefined variables' warnings, it's probably better to add these block properties to the controller. In that case they are always defined.
=> Add public properties to next_previous block controller

concrete/src/Updater/Migrations/Migrations/Version20180621222449.php
This should fix the following error:
```
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException
thrown with message
"An exception occurred while executing
'INSERT INTO atNumber (avID, value) VALUES (?, ?)'
with params ["462", "0"]:SQLSTATE[23000]:
Integrity constraint violation:
1452 Cannot add or update a child row:
a foreign key constraint fails (`c1c5minenu`.`atNumber`, CONSTRAINT `FK_41BA30B5A2A82A5D` FOREIGN KEY (`avID`) REFERENCES `AttributeValues` (`avID`) ON DELETE CASCADE)"
```
=> Fix migration of data in atPageSelector table

concrete/src/Asset/JavascriptLocalizedAsset.php
When concrete5 is installed in a subdirectory, in order to get the canonical route of a JavaScript asset we also need to remove the relative path, because routes are stored without it.
=> Fix JavascriptLocalizedAsset::getAssetContents when concrete5 is installed in subdirectory

concrete/single_pages/dashboard/blocks/types/view.php
This is a fix for the following error:
`Argument 1 passed to Concrete\Core\Url\Resolver\Manager\ResolverManager::resolve() must be of the type array, string given, called in B:\wamp64\www\dimger\concrete\single_pages\dashboard\blocks\types\view.php on line 95`
=> Fix for installing new blocks in 8.4.1

concrete/src/Http/ResponseFactory.php
Condition:
1. using Apache with [`.htaccess` set by concrete5](https://github.com/concrete5/concrete5/blob/8.4.1/concrete/src/Service/Configuration/HTTP/ApacheGenerator.php#L43-L50)
1. users visits an existing directory (eg `/concrete/images`)
Execution:
1. the browser visits `/concrete/images`
1. Apache sees that `/concrete/images` is not a file and it's not a folder containing `index.php`/`index.html`, and it sends the request to `index.php` but with `/concrete/images/` as request path  
Here's the mod_rewrite log:
```
strip per-dir prefix: /var/www/concrete/images -> concrete/images
applying pattern '.' to uri 'concrete/images'
RewriteCond: input='/var/www/concrete/images' pattern='!-f' => matched
RewriteCond: input='/var/www/concrete/images/index.html' pattern='!-f' => matched …
```
=> Fix infinite redirection visiting existing dirs when seo.trailing_slash is false

concrete/src/Editor/LinkAbstractor.php
content block converts all cID to link including drafts (`/!draft/*`) or deleted pages (`/!trash/*`) now.
I think we should ignore these pages.
=> [Bugfix] [or Proposal] Do not link to non active page in content block

concrete/src/Page/Sitemap/SitemapWriter.php
When we run  generate sitemap xml job getTemporaryDirectory() function return null value on first call (or if $result was null)
=> Fixing the error of generate sitemap xml job

concrete/composer.json, concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/controllers/single_page/dashboard/users/search.php, concrete/src/Csv/EscapeFormula.php, concrete/src/Csv/WriterFactory.php, concrete/src/Page/Controller/DashboardExpressEntriesPageController.php, tests/tests/Csv/InjectionPreventionTest.php
This PR has two ways you could add protection from CSVi:
1. If you're create your own write
* Apply an `EscapeFormula` object as a "Formatter" with `$writer->addFormatter(new EscapeFormula())`
2. If you're just using old `Writer::createFrom...` methods, we have a replacement factory
* Create a writer with `$writerFactory->createFrom(String|Stream|Path|FileObject)(...)
Either way you'll end up with a writer that has reasonable protection from common CSVi attacks.
=> Port league csv's injection protection

concrete/src/Cookie/CookieJar.php, concrete/src/Cookie/CookieServiceProvider.php, concrete/src/Cookie/ResponseCookieJar.php, concrete/src/Http/Middleware/CookieMiddleware.php, tests/tests/Cookie/CookieTest.php
#6864 was bad because CookieJar did too many things, having too many responsibilities.
Here's the (backward compatible) approach of this pull request:
- response cookies are handled by the new `ResponseCookieJar`
- we don't need a `RequestCookieJar`: it's already there in Symfony (see `$request->cookies`)
- `CookieJar` now is a simpler class that can be used for simple operations that involve both request and response cookies
For backward compatibility (we have to consider existing code that uses `$app->make('cookies')` or the `CookieJar` class with DI), I kept these methods (but I deprecated them) that work with response cookies:
- `set` ⇒ use `ResponseCookieJar::addCookie`
- `add` ⇒ use `ResponseCookieJar::addCookieObject`
- `clear` ⇒ use `ResponseCookieJar::clear`
- `getCookies` ⇒ use …
=> CookieJar refactoring v2

concrete/blocks/tags/view.php
This pull request fixes an issue with mixed case tag names and when the `ccm-block-tags-tag-selected` class is assigned to the current selected tag name. The tag name in the URL will always be lowercase and the selected tag name compared with it should also be lowercase.
The following is an example of the "Artist editions" tag name before and after the fix. In the changes screenshot, the `ccm-block-tags-tag-selected` class is applied to the current selected tag name.
**Current:**
**Changes:**
=> Tags block - support mixed case tag names when setting selected tag class

concrete/src/Database/DatabaseStructureManager.php
To support creating [multiple EntityManagers](https://documentation.concrete5.org/developers/packages/custom-database-tables-in-packages/doctrine-entities-in-a-custom-database) (e.g. via a child class) we should check for an interface instead of a concrete implementation.
This would then allow for
```php
$manager = new DatabaseStructureManager(new MyOwnEntityManager());
```
=> Enforce instance of EntityManagerInterface instead of EntityManager

concrete/src/Page/Page.php
When working with aliases, we have to use `cPointerOriginalID` instead of `cID` to build the display order.
=> Fix Page::movePageDisplayOrderToSibling() when working with aliases

concrete/src/Database/Connection/Connection.php
The Connection::Replace method is currently marked as deprecated. BTW a simple alternative to it does not exist.
So, what about making it NOT deprecated?
Furthermore, since all the new use camelCase instead of PascalCase, I renamed it from `Replace` to `replace` (which shouldn't have BC issues since method names are case insensitive).
=> Mark Connection::replace as NOT deprecated

concrete/blocks/express_entry_detail/controller.php
Error detail
file: "/path/to/concrete5/concrete/blocks/express_entry_detail/edit.php"
line: 36
message: "count(): Parameter must be an array or an object that implements Countable"
How to reproduce: Delete all "express" page attributes
=> Avoid errors in editing express entry detail block

concrete/elements/pages/search_header.php, concrete/src/Form/Service/Widget/SiteLocaleSelector.php, concrete/src/Page/PageList.php
We often need to search pages across all the language sections of the website.
So, what about these changes?
- let `PageList` filter by all the languages of a site, if pass to `setSiteTreeObject()` a `Site` object instead of a `SiteTree` object
- Add an option to `SiteLocaleSelector` to select "any locale"
- Add support to "any locale" to the `page_search` element
=> Add support to site-wide page searches

concrete/src/Utility/Service/Number.php
I grew tired of this warning:
This PR adds / fixes some docblocks in the [Number service](http://legacy-documentation.concrete5.org/tutorials/formatting-numbers).
Ref https://github.com/concrete5/concrete5/issues/4723
=> Fix docblocks in Number service

concrete/src/Routing/RouteGroupBuilder.php, concrete/src/Routing/SystemRouteList.php, tests/tests/Core/Routing/RouterTest.php, tests/tests/Routing/CheckRoutesTest.php
So I've fixed all of the tests and I've written a new test for checking the routes. (without the new test - https://travis-ci.org/deek87/concrete5/builds/424294629 )
As you can see there are a few classes missing. Im assuming @aembler may have forgot to merge them in when migrating the new routing system.
Ive also made the routeGroupBuilder ignore namespace if you use \ in front of a classname
The following classes don't exist in concrete5
```
/ccm/system/page/copy_all/ : Concrete\Controller\Backend\Page\CopyAll::fillQueue
/ccm/system/page/sitemap_delete_forever/ : Concrete\Controller\Backend\Page\SitemapDeleteForever::fillQueue
/ccm/system/dialogs/page/bulk/delete/ : Concrete\Controller\Dialog\Page\Bulk\Delete::view
/ccm/system/dialogs/page/bulk/delete/submit/ : …
```
=> Fixing tests 

concrete/blocks/express_form/controller.php, concrete/blocks/express_form/view.php
PR:
- Add phpdocs to help IDE with variables in the view.
- Make sure captcha object is injected via the controller instead of instantiated in the view.
- Fix indentation / newline issues.
- Do not `print` the renderer, as it always returns `void`.
Ref https://github.com/concrete5/concrete5/issues/4723
=> Improve Express Form block view

concrete/src/Database/Connection/ConnectionFactory.php, tests/tests/Database/DatabaseTest.php
Commit 34efff59e3fecd33dbea3e3e31a16d7b9e86fa9c implies that the connection is opened as soon as the connection instance is created.
Let's update the DatabaseTest::testInvalidConnection accordingly.
=> Fix DatabaseTest::testInvalidConnection

concrete/blocks/image_slider/controller.php
Reported in Slack #bug_team
https://concrete5.slack.com/archives/C6P2PL03A/p1535546677000100
The Image Slider block ResponsiveSlides.js assets were moved into app.php. 
https://github.com/concrete5/concrete5/blob/develop/concrete/config/app.php#L410-L412
https://github.com/concrete5/concrete5/blob/develop/concrete/config/app.php#L721-L726
=> Image Slider block - remove old CSS and JS assets code

concrete/src/Block/BlockController.php, concrete/src/Block/View/BlockView.php
If we call a custom block action (for example `action_my_custom_method`), the action of block controller is not `view` but `action_my_custom_method`.
Let's fix this issue.
=> Fix BlockController::getActionURL when a custom action is already executed

concrete/src/Block/Block.php
Before:
`getBlockID` returns `string` or `null`.
After:
`getBlockID` returns `int` or `null`.
=> Make sure getBlockID returns an integer

concrete/src/Console/Command/RefreshEntitiesCommand.php
`./concrete/bin/concrete5 c5:entities:refresh --help`
=> Fix typo in 'successfully'

concrete/src/Package/StartingPointPackage.php
The `$site_install` variable doesn't exist in this scope. 
https://github.com/concrete5/concrete5/blob/b404d9f54f4eb6b72990c8f0530bfdd8dd5a6a98/concrete/src/Package/StartingPointPackage.php#L485-L507
=> Fix alternative canonical URL in package StartingPoint

README.md
Reopening #7079 to test without waffle.io enabled
The signup link in the readme is wrong, let's update that to be a working link
=> Fix slack signup link

concrete/src/Error/Handler/JsonErrorHandler.php
Our JsonError handler only sends `application/json` content types if the browser explicity says it supports it, BTW some browser may say that it support *any* content type: let's consider this case.
=> Send JSON error responses when browser supports '*/*' content type

concrete/src/Page/Page.php
When we create an alias of the homepage, we need to create a handle for the page because home pages doesn't have any and the resulting alias URL will be the same as the one of its parent page:
=> Create collection handle when aliasing the homepage

concrete/elements/page_controls_footer.php
When we hit the "Force Exit Edit Mode" button, an empty dialog, users see an empty dialog (the Italian "dice" means "says"):
Let's avoid that.
=> Avoid displaying an empty message when forcing exit edit mode

concrete/attributes/boolean/controller.php
For example, in the registration page in Italian we currently have this:
> ![immagine](https://user-images.githubusercontent.com/928116/45961163-28bfa400-c01e-11e8-814e-c1c2bada5eef.png)
as you can see, there are mixed Italian (correct) and English (wrong) texts.
With this fix, we'll have:
> ![immagine](https://user-images.githubusercontent.com/928116/45961194-3ecd6480-c01e-11e8-9d9a-7a4aabba51c3.png)
=> Translate checkbox labels

concrete/src/Page/Page.php
- (5a57d38762b036d25f396a7919938049d7552f5b) in case of page aliases, let's just use the `$row` variable containing the alias data, there's no need to extract the wanted fields one by one
- (e5016043ac089a67ca187c96f45670abd2f61203) the result of `executeQuery` for select queries is always a `Statement` object, there's no need to check if it's not falsy (in case of errors, Doctrine throws exceptions, doesn't return falsy values)
- (e5016043ac089a67ca187c96f45670abd2f61203) we can use `fetchAssoc` instead of `executeQuery` + `fetchRow`, which returns `false` if no row is found
=> Simplify Page::populatePage

concrete/blocks/image/controller.php, concrete/blocks/image/view.php
In my opinion this option should not be excluded from image Block. Imagine a concrete5-template with a logo Area in which the user wants to add an SVG Logo with image Block. Why he can't have the option to resize this SVG image?
=> allow resizing for SVG images on image block.

concrete/views/dialogs/page/add_block_list.php
When adding new blocks to a stack, we are presented a full list of blocks, without the possibility to quickly filter it.
What about this?
PS: this `/views/dialogs/page/add_block_list.php` view is not the one used when adding blocks to pages, which is `/views/panels/add.php`
=> Allow filtering blocks in the add_block_list dialog used in Stacks

composer.lock, concrete/composer.json
There are some breaking changes in Imagine from 0.7.1 to 1.0.0.
These BC are only relevant if someone extends Imagine classes; which is BTW very unlikely since almost all Imagine classes are final. So, it should be safe to upgrade this library.
Fix #3999
=> Upgrade Imagine from 0.7.1 to 1.0.0

concrete/src/File/ImportProcessor/ConstrainImageProcessor.php
If concrete5 is set to automatically resize images that exceed a maximum height but not a maximum width, the resizing never happens.
=> Fix resizing images on import when only max height is set

concrete/src/File/ImportProcessor/ConstrainImageProcessor.php
This works only if Imagine is configured to use the Imagick driver (the GD driver does not support animated GIFs).
=> Keep animations when ConstrainImageProcessor resizes animated GIFs

concrete/src/Entity/OAuth/Scope.php
It's not possible to install concrete5 right now, because we have this error:
```
[Doctrine\DBAL\Exception\NotNullConstraintViolationException]                                                        
'INSERT INTO OAuth2Scope (identifier, description) VALUES (?, ?)'
with params  
["system", null]:                                                                                                   
```
Here's the relevant stack trace:
```
Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
at
concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
at
concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:177
Doctrine\DBAL\Statement->execute()
at …
```
=> Let OAuth Scopes always have strings in their description

concrete/src/Page/Sitemap/Event/SitemapXmlElementEvent.php, concrete/src/Page/Sitemap/SitemapWriter.php
This PR adds the `SitemapXmlElementEvent` class, which makes it easier to work with than a `GenericEvent` class. Because now we can add documentation blocks, for example.
Also, the former code:
```php
new GenericEvent(['sitemapPage' => $element])
```
causes the `$subject` to be an array, which is not very handy, because then you'd get this kind of code in a listener:
```
$subject = $event->getSubject();
/** @var \Concrete\Core\Page\Sitemap\Element\SitemapPage $element */
$element = $subject['sitemapPage'];
```
=> Add dedicated event class for 'on_sitemap_xml_element'

composer.lock
I found a minor bug in Imagine, where sizes calculation was sub-optimal.
This leads, for example, to having thumbnails one pixel narrower and/or lower.
So, I updated Imagine to consider this case.
=> Update Imagine to version 1.0.1

concrete/blocks/core_stack_display/view.php, concrete/controllers/page_types/core_stack.php, concrete/controllers/single_page/dashboard/blocks/stacks.php, concrete/single_pages/dashboard/blocks/stacks/view.php, concrete/src/Block/Menu/Menu.php, concrete/src/Permission/Assignment/AreaAssignment.php, concrete/src/Permission/Key/AddBlockBlockTypeKey.php, concrete/src/Permission/Response/PageResponse.php, concrete/src/Workflow/Request/DeletePageRequest.php, concrete/views/panels/details/page/permissions/advanced.php, concrete/views/panels/page/versions.php
This *pool* :wink: request is an alternative to #7029.
Here I'm trying to implement what @aembler [suggested](https://github.com/concrete5/concrete5/issues/7006#issuecomment-420037381).
*WARNING* it's not yet done, I'm currently facing a big issue, as described below.
Let's assume that we configure the stack with the following *page* permissions:  
- if we don't specify [these lines](https://github.com/concrete5/concrete5/commit/2b0e45c81a327b4a4b7fedb0c1b78afae4c3ffaa#diff-4d8968f8965dab8c74fe27f9b5a6bb39R18), the resulting area permissions are the following ones (the user can't add blocks to the stack):  
- if we specify [these lines](https://github.com/concrete5/concrete5/commit/2b0e45c81a327b4a4b7fedb0c1b78afae4c3ffaa#diff-4d8968f8965dab8c74fe27f9b5a6bb39R18), the resulting area …
=> Fix stack access with advanced permissions - Take 2

concrete/single_pages/dashboard/system/files/thumbnails.php
As [suggested](https://github.com/concrete5/concrete5/pull/7114#issuecomment-424817221) by @MrKarlDilkington, we should show a warning about memory & performance issues when a thumbnail is set to create animated GIF files.
With this change, we'll show this error message (if Imagine is configured to use ImageMagick):
If Imagine is configured to use GD, we still show this other warning:
=> Show a warning about memory & performance when using animated thumbnails

concrete/controllers/frontend/assets_localization.php
Resizing animated GIFs on the client implies that the image sent to the server will be no more animated. Let's avoid this.
=> Disable client-size resizing of GIF images

concrete/controllers/search/users.php
Using `getEntityManager` on the Connection object is deprecated, so I replaced that by booting an instance of the EntityManager instead.
=> Improve user search controller

concrete/src/Console/Command/InstallCommand.php
If running the CLI install command in an interactive way (`./concrete/bin/concrete5 c5:install -i`), and we enter invalid database connection parameters, the process aborts for an uncaught exception (`SQLSTATE[HY000] [2002] Connection refused`).
What about intercepting exceptions so that users can change the wrong connection parameters?
=> Catch exceptions in interactive CLI install

concrete/src/Install/Preconditions/EmptyDatabase.php
=> Show "Database should be empty" instead of "Database is empty"

.travis/rebuild-assets.sh
TravisCI checks out a commit before doing its tests thus we are in the so-called *detached HEAD state*).
We need to checkout the develop branch in order to actullly being able to update it.
=> Checkout branch before rebuilding the CSS/JS assets

concrete/src/File/Importer.php
one of the constants in Importer.php was missing the self:: in front of it which was causing an issue in PHP 7.2
=> fix const usage

concrete/src/Page/Sitemap/SitemapGenerator.php
Without overriding the **SitemapHeader** class it's not easy to change the XML's **namespaces**.
Overriding the class would be a lot easier if we resolve it via the container.
=> Resolve SitemapHeader via container, to allow overriding

.appveyor.yml
Let's use the [PhpManager](https://www.powershellgallery.com/packages/PhpManager) PowerShell package to install and configure PHP in AppVeyor.
=> Test concrete5 on Windows with the latest PHP 7.1

concrete/src/System/Info.php
Let's get rid of this error thrown with PHP 7.3:
```
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
=> Fix System\Info constructor for PHP 7.3

.appveyor.yml, .appveyor/configure.ps1
- move the AppVeyor configuration script to its own file
- let AppVeyor run tests for PHP 7.2 64-bit too
- configure PHP to correctly handle HTTPS connections
- use PhpManager to install composer
=> AppVeyor: move to own script, test PHP 7.2 x64, setup PHP CA certificates

concrete/src/Express/Association/Applier.php
Previously we were running `->getInverseAssociation()` for every item we were associating, even though it doesn't really change.
After this change we stop querying for that inverse association on every loop.
=> Only get inverse association when we need it

concrete/js/build/core/app/search/preset-selector.js
=> Close just the top dialog when selecting a search preset

concrete/src/Localization/Localization.php
We often have to temporarily switch the localization context.
What about adding a method to do that?
=> Add Localization::withContext() method

concrete/src/User/UserInfo.php
In addition to what @a3020 proposed in #7163, I also added the `UPDATE` on the ConversationMessageRatings table.
Fix #7163
=> Detach user from conversation messages and ratings when deleted

concrete/src/Permission/Key/Key.php
Fixes this error:
> Argument 2 passed to Doctrine\DBAL\Connection::executeQuery() must be of the type array, integer given, called in **\public\concrete\src\Permission\Key\Key.php on line 391
=> Make sure parameters are passed as array in getListByPackage

concrete/blocks/autonav/templates/responsive_header_navigation/view.js
fixes errors (and companion warning) in w3.org validator (and possibly non-standard browsers). These errors show as
>Error: Duplicate ID `_search_input`.
>From line 100, column 17; to line 100, column 130
>          `<input id="_search_input" class="ccm-search-block-text _search_input" value="" size="20" name="query" type="text">` 
>Warning: The first occurrence of ID `_search_input` was here.
>From line 71, column 17; to line 71, column 130
`<input id="_search_input" class="ccm-search-block-text _search_input" value="" size="20" name="query" type="text">`
replaces element in cloned region as `<input id="cloned-ccm-ro__search_input" class="ccm-search-block-text _search_input" value="" size="20" name="query" type="text">`
`php-cs-fixer fix …
=> fix duplicate IDs in cloned blocks

concrete/src/Localization/LocalizationEssentialServiceProvider.php, concrete/src/Localization/Translator/Adapter/Zend/TranslatorAdapterFactory.php, concrete/src/Localization/Translator/Loader/Gettext.php, concrete/src/Localization/Translator/TranslatorAdapterRepository.php, concrete/src/Localization/Translator/TranslatorAdapterRepositoryInterface.php
When the Zend I18N component loads language files with wrong or missing plural rules, concrete5 aborts with this `Zend\I18n\Exception\RuntimeException` exception:
```
Plural rule of merging text domain is not compatible with the current one
```
End users may have a very hard time debugging (and understanding) what's going on.
So, what about fixing automatically the number of plural rules if possible (or showing a better error message if an automatic fix is not possible)?
=> Add custom Gettext loader to fix plural rules

concrete/src/Page/Page.php
The `Page::isAlias()` method is really misleading: it's actual meaning is "is the page an alias or an external link?"
So, what about renaming `Page::isAlias()` to `Page::isAliasPageOrExternalLink()`, and adding a new `Page::isAliasPage()` to only check if a page is an alias?
=>  Add Page::isAliasPage(), rename Page::isAlias() to Page::isAliasPageOrExternalLink()

concrete/src/Install/Installer.php
If someone configures the preferred DB charset to be the same as the fallback one, we have an infinite loop in the install procedure.
Let's avoid that.
=> Avoid infinite loop is the configured charset is the same as the preferred one

concrete/src/Package/StartingPointPackage.php
When a database error occurs, we currently show only its numeric code (that's what returned by the deprecated `$db->ErrorMsg() `).
Let's display the actual error message instead.
=> Show the actual DB error message in StartingPointPackage

.travis.yml, .travis/composer-deps.sh
For some reason travis is complaining that xdebug isn't enabled. Let's try using the default dist rather than being explicit
=> Don't specify travis distribution

concrete/src/Console/Command/RescanFilesCommand.php, concrete/src/Console/ServiceProvider.php, tests/tests/Console/ServiceProviderTest.php
Example usage:
`concrete/bin/concrete5 c5:rescan-files`
Limit to 10
`concrete/bin/concrete5 c5:rescan-files --limit=5`
Limit to 50, rescanning after file ID 17:
`concrete/bin/concrete5 c5:rescan-files --after=17 --limit=50`
=> Add a console command to rescan files

concrete/tools/sitemap_overlay.php, concrete/tools/sitemap_search_selector.php
This PR fixes two bugs within the `sitemap_overlay` tool :
1. When selecting the **Full Sitemap** tab and switching to **Flat View**, there was an error in the console :
`Uncaught TypeError: Cannot read property 'indexOf' of undefined`
2. When selecting the **Flat View** tab, switching to **Full Sitemap** and switching back to **Flat View**, the sitemap overlay was displayed two times :
=> Fix in the sitemap_overlay tool

concrete/views/panels/page/versions.php
Informations about the approver could be empty on the first version, this PR adds a check on this.
Before :
After :
=> Check if there is an approve date and an approver on page versions

concrete/controllers/backend/user_interface/page.php
PS: to actually display the error message. we need #6975 (otherwise users will only see "Internal Server Error" message because jquery won't recognize the response as a JSON object).
=> Display a "page not found" instead of "access denied" message when a page is not found

concrete/config/db.xml, concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php, concrete/src/Entity/Attribute/Category.php, concrete/src/Entity/Attribute/Set.php, concrete/src/Entity/Attribute/Type.php, concrete/src/Entity/Express/Entity.php, concrete/src/Entity/File/Version.php, concrete/src/Entity/Geolocator.php, concrete/src/Entity/OAuth/Client.php, concrete/src/Entity/OAuth/Scope.php, concrete/src/Entity/Package.php, concrete/src/Entity/Page/PagePath.php, concrete/src/Entity/Site/Site.php, concrete/src/Entity/Site/Type.php, concrete/src/Entity/User/User.php, concrete/src/Updater/Migrations/Migrations/Version20181006212400.php
As described in #7216, indexed text fields with a length of more that 191 characters may not support `utf8mb4` (full unicode).
This is the case of old MySQL versions, or recent MySQL versions configured with `innodb_large_prefix` set to `OFF`.
The solution of this PR is to use `utf8mb4` except for selected fields that may not support it (that is, the indexed ones).
Fix #7216.
=> Don't use utf8mb4 for varchar(>191) indexed fields

.php_cs.dist
Symfony ruleset includes yoda style in later versions of PHP Cs fixer. 
This PR disables yoda style if you run php-cs-fixer
@mlocati can you test with older version of php-cs-fixer
For those wondering what Yoda style is like this
`if (1 === $variable) {` compared to Normal Style `if ($variable === 1) {`
=> Yoda Style, Disable We Must!

.scrutinizer.yml, .travis.yml, .travis/composer-deps.sh
What about enabling xdebug and collecting code coverage in just one of the TravisCI jobs? Otherwise tests take really a lot of time...
=> Run code coverage just once

concrete/src/Session/SessionFactory.php, tests/tests/Session/SessionFactoryTest.php
Prior to this PR we only supported two session handlers: `file` (default), and `database`. If you wanted to add a new session handler of any type, you'd need to extend `SessionFactory` and reimplement quite a few important meaty functions in order to properly add the ability to return a custom handler.
Now with this PR, we support three session handlers by default: `file` (default), `database`, and `memcached`. Also we now have the ability to simply add new handlers. For example, if I wanted to implement a custom `Foo` session handler with the handle `custom_foo`, all I would need to do is:
1. Create an extension of this class in my own namespace like `\PortlandLabs\Foo\Session\Factory`
2. Tell the application to use that class instead of the core by adding 
```php
$app->bind( …
```
=> Improve ability to configure and extend c5 session

concrete/single_pages/dashboard/system/registration/automated_logout.php
My proposal is **to prevent espace characters in t-strings**, because these text strings are often used to search in the code base. If a user would search for "Log users out if their browser\'s user agent changes", he wouldn't find any matches. If we were to use double quotes instead, the string would be found. 
Of course this is a minor change. But if the core team agrees that we should try to avoid escape characters in t-strings, we'd enforce that for future commits, which I think would be useful.
https://github.com/concrete5/concrete5/pull/7227#discussion_r229774805
=> Translation - Make it easier to search for a text string

concrete/authentication/facebook/controller.php
This prevents a duplication translation message.
'Successfully detached.' is used [elsewhere](https://github.com/concrete5/concrete5/search?q=%22Successfully+detached%22&unscoped_q=%22Successfully+detached%22).
=> Translation - Make detach message consistent with other auth types

concrete/src/Page/Collection/Collection.php
The `cID` class property in the Page/Collection class sometimes contains a string. Let's make sure it always returns an integer or null, when we call `getCollectionID`.
=> Make sure getCollectionID always returns int or null

concrete/blocks/autonav/controller.php
We can pass a custom collection to the autonav block by using the `$collection` property.
But the `$cID` property is always retrieved from the current page, this PR allows to use the collection ID of the `$collection` property.
=> Use the ID of the custom collection in the autonav block

composer.lock, concrete/composer.json
It seems that Wikimedia is going to take care of less.php: https://github.com/oyejorge/less.php/issues/329#issuecomment-430122809
=>  Switch from concrete5/less.php to wikimedia/less.php 

concrete/controllers/dialog/file/bulk/storage.php, concrete/elements/storage_location_types/local.php, concrete/routes/dialogs/files.php, concrete/single_pages/dashboard/system/files/storage.php, concrete/src/Entity/File/StorageLocation/StorageLocation.php, concrete/src/File/FileList.php, concrete/src/File/Menu.php, concrete/src/File/Search/Field/Field/StorageLocationField.php, concrete/src/File/Search/Field/Manager.php, concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php, concrete/views/dialogs/file/bulk/storage.php, tests/tests/File/SearchFieldManagerTest.php
This PR :
- Adds a storage location field to the advanced file search
- Adds a `hasFiles()` method to storage locations
- Prevents the deletion of a storage location if there are files in it
- Prevents changing the root path of a local storage location if it contains files
- Adds a progressive operation to change files storage location
- Adds the 'Storage Location' bulk menu item to files
**I didn't try it with a storage location other than the local one, if anyone is available to test that 👍** 
Fix #5517, fix #1611, fix #4107
=> Storage locations improvements

concrete/src/Form/Service/Widget/SiteLocaleSelector.php
This PR improves `SiteLocaleSelector::selectLocale()`: it can now optionally display the locale ID.
This is useful when working with locales with the same language name but different country.
For example, if we have two languages `zh_CN` and `zh_TW`, the language text for both is 'Chinese'.
`selectLocale` is now able to detect if there are two or more locales with the same name: if so, we'll display the language code too (so, `Chinese zh_CN` and `Chinese zh_TW`).
This behavior can be controlled by the new `displayLocaleCode` option.
This PR implements also a new `SiteLocaleSelector::selectLocaleMultiple()`, to let users specify multiple locales.
=> Improve SiteLocaleSelector

concrete/src/File/Set/Set.php
Restoring the sorted file set name that was lost in this commit: https://github.com/concrete5/concrete5/commit/ea0092092d57ad38a739977f35e0b520cc582824
=> Adding alpha sort to file set list

concrete/blocks/express_form/controller.php
PR:
- Remove unused imports, unused variables
- Improve a few if/else statements
- Use `app` container instead of Core facade
- Use Request object instead of e.g. `Page::getCurrentPage()`
- Use ::class to make FQNs resolve
- Remove unused (protected) entityManger property 
- Use Checker class import instead of the Permissions alias
- Add a few docblocks (where it makes sense to have them)
- Move the `view` method to the top, because that's where you'd expect it
I consider this as a first round of optimization / code clean up...
Ref https://github.com/concrete5/concrete5/issues/4723
=> Improve Express Form controller

concrete/src/Page/PageList.php, concrete/src/Page/Search/Field/Field/VersionStatusField.php
This PR adds the ability to search for pages that are scheduled to be published. Currently you can see scheduled pages only by selecting All on the version status. This adds the 'Scheduled' version status option.
There are some other issues related to scheduled pages I think should be covered separately (such as what to display in public date) So I opened an Issue for them #7244
=> [Feature] add scheduled as an option for page search

concrete/src/Page/Page.php
Because #7266 got merged, I had to add ab277ee3c988be8815cd49222922616025027a4a to #7207
Instead of reverting #7266 (I love it), what about doing the same for `Page::getCollectionParentID`?
=> Make sure getCollectionParentID always returns int or null

concrete/src/Routing/Router.php
For package developers it's extremely useful to have `since` tags. For example, `register` is deprecated since [8.5.0.a2](https://github.com/concrete5/concrete5/commit/742d6f936cdf4fa090cfd954759301a94286ca91#diff-14d1f498101c71b53b4fb69738a82c08), but the alternatives (the verb-like methods) are not available in earlier versions.
This PR adds a few docblocks, nothing fancy, but it saves us a lot of BC problems.
PS. @aembler the verb methods are not part of the RouterInterface, is this on purpose? I'm not sure I get the idea of a router interface, if the recommended way of adding new routes is via verb-methods. E.g. `$router->post('url', 'action');`.
=> Add docblocks to verb-route methods in Router

concrete/src/Attribute/Category/UserCategory.php
Currently if you add a User Attribute to a set you cant save any of the default settings
"Editable in profile" , etc
This is because we normally save to the database in the assignToSetFromRequest function 
https://github.com/concrete5/concrete5/blob/4ccf81248f2b7925e25568eb779acb2bed592d7f/concrete/src/Page/Controller/DashboardAttributesPageController.php#L138
We should save in the saveFromRequest() on the UserCategory (like the parent does)
I also noticed we weren't saving in import either, this could mean in attributes not having the correct settings if previously imported.
=> [FIX] #7280 Save the Default User Attribute Settings

concrete/src/Database/CharacterSetCollation/Exeption/LongKeysUnsupportedByCollation.php, concrete/src/Database/CharacterSetCollation/Resolver.php, concrete/src/Database/Connection/Connection.php
In order to fix #7216, I previously suggested #7221. BTW that PR would have required that every concrete5 developer should use (and know) that they'd have to force `utf8`instead of `utf8mb4` for string keys wider than 191 chars.
Another fix for #7216 is this PR: we always use the same charset: `utf8mb4` if available *and* usable in string keys with up to 255 chars, otherwise we use `utf8`.
PROs: concrete5 developers don't have to deal with charsets
CONs. users with old MySql versions (or with recent MySql versions with `innodb_large_prefix` turned off) won't have a full-unicode support
Here's a sample installation session when MySQL doesn't support utf8mb4 for 255-long key columns:
=> Use (only) utf8mb4 only if supported for keys

concrete/views/dialogs/page/delete_alias.php
When deleting an alias or an external link, we ask this confirmation:
What about showing a different message for the two cases?
| ![immagine](https://user-images.githubusercontent.com/928116/48251913-827c0200-e403-11e8-861d-fbf90755d386.png) | ![immagine](https://user-images.githubusercontent.com/928116/48251920-8576f280-e403-11e8-9d8f-a1dd4d65fdd6.png) |
|:-:|:-:|
=> Show different text for aliases and external links in removal confirmation

concrete/views/dialogs/page/drag_request.php
When we show the sitemap drag dialog, we sometimes pre-check the first option, sometimes we don't:
With this PR, we always check the first displayed option.
=> Sitemap drag: automatically check the first options

concrete/config/app.php, concrete/elements/files/view/image.php
What about considering the SVG images exactly like the other images?
| Before this PR | With this PR |
|:---:|:---:|
| ![immagine](https://user-images.githubusercontent.com/928116/48271814-7d3ba900-e43d-11e8-9182-817c26e9def2.png) | ![immagine](https://user-images.githubusercontent.com/928116/48271848-90e70f80-e43d-11e8-9060-4603b8936178.png) |
=> View SVG images like we already do with other image types

concrete/js/build/core/file-manager/search.js, concrete/src/Entity/File/Version.php
SVG images can be very big.
So, we may have very big previews:
With this change, the previews of SVG images have a size comparable to the one of the other images:
=> Limit the maximum width/height of previews of SVG images

concrete/src/File/Set/Set.php, tests/tests/File/FileListTest.php
Follow up of https://github.com/concrete5/concrete5/pull/7249#issuecomment-435215164
=> Refresh thumbnails when adding/removing files to sets only when needed

concrete/src/Multilingual/Service/Detector.php
The issue in #6908 appears to be caused by `$session->has('multilingual_default_locale')`.
I used @mlocati's method to check if we can set session values before using `$session->has()` and to replace the duplicate code. 
Co-Authored-By: mlocati <michele@locati.it>
Fix #6908
=> Check if we can set session values in Detector class

concrete/blocks/desktop_waiting_for_me/controller.php, concrete/blocks/desktop_waiting_for_me/view.php
We (sometimes) set the `$activeFilter` variable in the controller, and we use `$activeFilter` and `$filter` in the view.
Let's always use `$filter`.
Ref. #4723
=> Avoid accessing undefined var in desktop_waiting_for_me block

concrete/src/Page/Controller/PageController.php, concrete/src/Page/Page.php, concrete/src/Page/Search/IndexedSearch.php, tests/tests/Attribute/CollectionAttributeTest.php
I've had to add a check for `getPageTypeObject`. When I tested this change a received a lot of exception when calling `$c->getPageController()` due to a null object.
=> allow page controllers to return searchable content

concrete/controllers/dialog/page/drag_request.php, concrete/src/Page/Sitemap/DragRequestData.php
It turned out that the cause of #7287 was that in #6951 I passed the ID of the pages, not the ID of the aliases.
Fix #7287
=> Fix dragging aliases in sitemap

concrete/elements/pages/schedule.php, concrete/src/Form/Service/Widget/DateTime.php
This PR fixes the following issue-
Reason for using `autocomplete="nope"`
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
=> Turn off autocomplete for schedule datepicker input

concrete/src/Page/Page.php
This PR adds some improvements to the `Page` class :
- Use "(No Title)" instead of an empty value for the page name in the getJSONObject() method, this avoids having an empty page name in the page selector
- Avoid core aliases
- Avoid core facades
=> Avoid having an empty value as page name in page selector attribute

concrete/src/Error/Handler/JsonErrorHandler.php, concrete/src/Http/RequestMediaTypeParser.php, tests/tests/Http/RequestMediaTypeParserTest.php
Our `JsonErrorHandler` class is sending JSON responses for ajax requests that contain errors.
BTW, if the client is requesting HTML (for example), the `Accept` header (`$_SERVER['HTTP_ACCEPT']`) for PHP will be something like this (just tested with Chrome, Firefox, Edge, Internet Explorer):
```
Accept: text/html, */*; q=0.01
```
(which means: the browser would really like a `text/html` document, but it may also accept anything else - see the `*/*; q=0.01` chunk).
In the above case, we currently answer to ajax calls with the error in JSON format, but with a `text/plain` media type (so, the client won't interpret is as JSON).
The simple regex we [currently have](https://github.com/concrete5/concrete5/blob/230d6f72ec5ea77f8d4385f6b7741b6e59fe2e74/concrete/src/Error/Handler/JsonErrorHandler.ph …
=> Send a JSON error response only if the client is requesting a JSON response

concrete/src/Error/Provider/WhoopsServiceProvider.php
The reason why in #7326 we run out of memory is that `var_dump` runs out of memory because of nested loops of self-referencing instances.
What about using `var_dump_safe` instead of `var_dump`?
=> Use var_dump_safe instead of var_dump in Whoops PlainTextHandler

concrete/controllers/single_page/dashboard/system/registration/open.php
This PR prevents an error on the `implode(',', $registerNotificationEmails)` which sometimes could be unset.
=> Add missing checks in Public Registration page

concrete/src/Page/DisplayOrderUpdateEvent.php, concrete/src/Page/Page.php, tests/helpers/Page/PageTestCase.php, tests/tests/Page/PageTest.php
I hooked into the event in the bootstrap.php to verify if this event works as expected.
```php
Events::addListener('on_page_display_order_update', function($event) {
\Log::addInfo(
$event->getPageObject()->getCollectionName()
. '. Old order: ' . $event->getOldDisplayOrder()
. '. New order: ' . $event->getNewDisplayOrder()
);
});
```
https://github.com/concrete5/concrete5/issues/7254#issuecomment-434759474
=> Trigger event when the display order of a page changes

concrete/src/Updater/Migrations/Configuration.php
This PR makes sure the 'Version' prefix is removed from migration identifiers. Now you can just copy/paste a migration's class name in the CLI.
'Fixes' https://github.com/concrete5/concrete5/issues/7332
=> Remove 'Version' prefix from migration identifiers

concrete/src/Updater/Migrations/Migrations/Version20181006212400.php
#7333 fixed a nasty bug that could break sites.
What about fixing migration 20181006212400 so that it doesn't break the site when have `Throwable` exceptions (at least for PHP 7.0+)?
=> Make migration 20181006212400 safer

concrete/src/Page/Search/Field/Field/ParentPageField.php
This should fix the following issue:
```
Argument 1 passed to Concrete\Core\Page\PageList::setSiteTreeObject()
must implement interface Concrete\Core\Site\Tree\TreeInterface, null given,
called in concrete/src/Page/Search/Field/Field/ParentPageField.php on line 41
```
=> Fix ParentPageField search field when page is no (more) available

concrete/src/Page/Single.php
`Single::addGlobal` can create the same single page repeatedly.
=> Fix checking the global single page is already exists

concrete/controllers/single_page/account/edit_profile.php, concrete/controllers/single_page/register.php, concrete/single_pages/account/edit_profile.php, concrete/single_pages/register.php
This PR changes the user attributes display order on the **Edit Profile** and **Register** pages.
Now we use the same order as on the **View/Edit** page of a user and the list of user attributes.
PS : this PR also removes core aliases and facades.
Fixes #7268 and #7269.
=> Fix user attributes order on Edit Profile and Register pages

concrete/src/Page/Sitemap/Element/SitemapPage.php, concrete/src/Page/Sitemap/Element/SitemapPageAlternativeLanguage.php
Let's be less picky about the URLs used by the sitemap stuff.
We currently use `Concrete\Core\Url\UrlInterface`, but if we switch to its parent interface `League\Url\UrlInterface` we grant users more freedom about what they can do.
=> Use League\Url\UrlInterface instead of its child class Concrete\Core\Url\UrlInterface in sitemap

concrete/src/Database/DatabaseServiceProvider.php
The class doesn't have a `$connection` argument.
https://github.com/concrete5/concrete5/blob/a58b41ded8b74fd81cf371058a4512b565aa4985/concrete/src/Database/EntityManagerConfigFactory.php#L38-L42
=> DatabaseServiceProvider  - Remove incorrect 4th parameter

concrete/src/View/AbstractView.php
If `View::getInstance()` is called in Middleware, it currently returns `false`. This is a bug, and the why is explained in issue #7377. 
Three changes in this PR:
1. Instantiate a new instance in case the property is not a View instance. E.g. if it's `null` (initial value) or `false` (see issue #7377), see 815555c
2. Say the user already has a View instance and the property is set to `false` via `revertRequestInstance`, this might give problems. Therefore a fresh instance is retrieved in that method as well. See ebb8b98.
3. Add comments for (pkg) developers that may rely on this method and support older versions, see 63dcb49
=> Make sure View::getInstance always returns a View

.appveyor/configure.ps1
When running PHP on Windows, we need to manually configure the list of trusted Certification Authorities (CA) for HTTPS/SSL/TLS communications (php isn't able to retrieve them from the system on Windows).
Our AppVeyor job uses [PhpManager](https://github.com/mlocati/powershell-phpmanager) to do it.
At the moment, PhpManager is configured to use the CA certificates provided by https://curl.haxx.se/docs/caextract.html, but it's not the first time that they are misconfigured (when they update the CA certs, the certificates and their hash are not synchronized for some time because of the caching infrastructure they are using).
This leads to errors like this: https://ci.appveyor.com/project/concrete5/concrete5/builds/20781564/job/ojgppvtxrnjjpq9l
So, what about using the CA certificates …
=> AppVeyor: Use local machine trusted CA certs instead of using the cURL ones

concrete/src/Entity/File/Version.php, concrete/src/File/Image/Thumbnail/Type/Version.php
When deleting a file version, we currently (try to) delete its associated thumbnails, even if the file is not an image.
This may lead to an uncaught exception if a thumnbail type is set to generate animated gifs.
Let's fix this by:
1. deleting thumbnails only for image files
2. don't break the execution when determining the thumabail extension accordingly to its content.
=> Delete thumbnails only for images

concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Since `APP_CHARSET` is defined later than the registration of error handlers (see [here](https://github.com/concrete5/concrete5/blob/24c24624f05d04865b1f7e5b75373cd1df620b59/concrete/src/Foundation/Runtime/Boot/DefaultBooter.php#L97-L104) the calls to `initializeServiceProviders()` and `initializeLegacyDefinitions()`), if something wrong happens in `initializeServiceProviders()` we may be referencing an undefined `APP_CHARSET` constant in error handlers.
So, what about swapping the two calls?
=> Swap calls to initializeServiceProviders() and initializeLegacyDefinitions()

concrete/controllers/dialog/page/add_block.php
The cause of #7384 is #7308 and the way `EditResponse` is initialized when its constructor receives an `ErrorList` instance.
Indeed:
1. before #7308, the error object of `EditResponse` was set to the received instance if it's not empty
(see [here](https://github.com/concrete5/concrete5/blob/8.4.3/concrete/src/Application/EditResponse.php#L28))
1. after #7308, the error object of `EditResponse` is always set to that instance
(see [here](https://github.com/concrete5/concrete5/blob/24c24624f05d04865b1f7e5b75373cd1df620b59/concrete/src/Application/EditResponse.php#L75))
(And I do think it's a better approach since it's more predictable and consistent).
When adding a new block type, we [have this code](https://github.com/concrete5/concrete5/blob/24c24624f05d04865b1f7e5b75373cd1df620b59/concrete …
=> Fix the check token logic in add_block controller

concrete/authentication/external_concrete5/controller.php, concrete/config/concrete.php, concrete/src/Package/StartingPointPackage.php, concrete/src/Updater/Migrations/Migrations/Version20181212221911.php
Install the authentication type properly.
Install it in a migration.
Fix bug when editing it for the first time.
=> Bug fixes for external concrete5 authentication

concrete/single_pages/dashboard/system/environment/logging.php
- fix typo *simple* instead of *siple*
- use placeholders (`%1$s`, `%3$s`) instead of configuration keys (they must not be translated)
=> Fix typo in logging text, use placeholders for configuration key names

concrete/src/Logging/LoggerFactory.php, concrete/src/Logging/LoggingServiceProvider.php, tests/tests/Logging/LogTest.php
When installing concrete5, we have this error:
```
Call to undefined method
Psr\Log\NullLogger::createLogger()
in file
concrete/src/Application/Application.php on line 414
```
That's because `$app->make('log/factory')` should return a logger factory, not a logger.
=> Fix installation with new log stuff

concrete/controllers/single_page/dashboard/system/mail/method/test.php, concrete/elements/system_errors.php, concrete/js/build/core/app/ajax-request/base.js, concrete/js/build/core/app/dialog.js, concrete/src/Error/Error.php, concrete/src/Error/ErrorList/Error/AbstractError.php, concrete/src/Error/ErrorList/Error/ExceptionError.php, concrete/src/Error/ErrorList/Error/ThrowableError.php, concrete/src/Error/ErrorList/ErrorList.php, concrete/src/Error/ErrorList/Formatter/AbstractFormatter.php, concrete/src/Error/ErrorList/Formatter/FormatterInterface.php, concrete/src/Error/ErrorList/Formatter/JsonFormatter.php, concrete/src/Error/ErrorList/Formatter/StandardFormatter.php, concrete/src/Error/ErrorList/Formatter/TextFormatter.php, concrete/src/Error/UserMessageException.php
In #7395 we introduced a way to tell the system if an error is in HTML or in plain text.
In this new PR I add something that was missing in #7395:
1. the `system_errors` element html-escapes all the errors, regardless if they are already in HTML or not. Let's fix this (see commit 3a12fba87598b46c1a34da81becc9079995afa19)
1. the plain-text error formatter should remove HTML stuff when rendering errors in HTML format (see commit cbf6f8bcb17e94b00ae0665df6caffb79ae2067e)
1. adding a simple error string in HTML format to an ErrorList instance is a bit too comples (we need to create an instance of an Error class, set its `messageContainsHtml` flag and add it to the error list). What about adding a new `addHtml()` method in addition to `add()`? See commit …
=> Fix handling of html/text in error messages

concrete/controllers/dialog/block/edit.php, concrete/src/Block/BlockController.php
In concrete5 on older blocks they would return true when validate() is called. 
This means that an error of true is added to the blockedit response object.
This PR fixes the issue if validate returns true and also updates the default block controller to return an error list rather than just true
=> Fixing issue with block editing/adding

concrete/controllers/single_page/dashboard/system/api/integrations.php, concrete/single_pages/dashboard/system/api/integrations/add.php, concrete/single_pages/dashboard/system/api/integrations/edit.php
When creating/editing an API integration, let's add client-side validation of the integration name (it's required), and the integration redirect (it's a required URL).
=> API Integrations: make redirect field an URL input, mark name and redirect as required

concrete/src/Form/Service/Widget/PageSelector.php
When a page is permanently deleted there may be (custom) blocks that still refer to the page. The page selector widget, in edit mode, blocks editing of that field for anyone without superadmin priviledges. By checking if the page actually exists permissions are not checked and the widget becomes editable.
=> Fix editing blocks that refer to deleted pages for non-admins

concrete/src/Page/Search/Field/Field/ParentPageField.php
This fixes the following error when you do an advanced page search and select the trash page or a system page as a parent page.
```
Argument 1 passed to Concrete\Core\Page\PageList::setSiteTreeObject() must implement interface Concrete\Core\Site\Tree\TreeInterface, null given,
```
=> Fix an error when selecting trash or system pages as the parent page on page search

concrete/src/Search/Pagination/Adapter/PagerAdapter.php, tests/tests/File/FileListTest.php
PagerAdapter::getSlice() may return more results than expected.
Tests should have revealed this issue, but because a test file is not imported (it doesn't have an allowed file extension), the tests state is not the expected one.
First, let's fix the file import: I'll add the fix when TravisCI tests finish (they should fail).
=> Fix too many results in PagerAdapter::getSlice()

concrete/blocks/next_previous/controller.php, concrete/src/Page/Page.php
Fixes some errors with MySQL queries being incorrect (extra and statements) on Page and prev_next block.
@mlocati
=> Fixing SQL errors with next_previous block and getFirstChild

concrete/src/File/Image/BitmapFormat.php
When we save an Imagine image, we call `getFormatImagineSaveOptions` to get the save options for a specific format.
BTW, we don't store in the built options the format of the image. In this case Imagine infers it from the file extension, but we may be working without files (for instance sending the image directly to the client) or with files with weird file extensions.
So, what about explicitly set the wanted image format?
=> Set the image format so that it's not inferred from the file extension when saving

concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php
Before, the ip addresses weren't saved. ('why do we need code reviews again?')
After PR:
=> Trusted Proxies - Fix saving the list of ip addresses/ranges

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/registration/automated_logout.php, concrete/single_pages/dashboard/system/registration/automated_logout.php
First step for automatically logout inactive users (issue #7260). This PR only saves the values to the configuration file. The actual logout functionality is still pending per @aembler request.
=> Adds New Feature - Logout Inactive users 

concrete/src/Page/Collection/Version/Version.php, concrete/src/Page/PageList.php
Currently in version 8.5.0a3 and below the current PAGE_VERSION_RECENT_UNAPPROVED will return the Active version object rather than the most recent unapproved CollectionVersion
In CollectionVersion we dont have a way to load recent_unapproved versions and on the page list we just get the active version if you select PAGE_VERSION_RECENT_UNAPPROVED as the page version to retrieve.
This PR adds the ability for the CollectionVersion to load RECENT_UNAPPROVED versions and the page list will load them.
I have also removed Future Scheduled pages from the Recent_unapproved page list as it makes no sense to have it. ( We have the ability to filter by scheduled) These pages have been approved for publishing on a set date and as such they are not unapproved version ( this bug was introduced recently …
=> Fixing PAGE_VERSION_RECENT_UNAPPROVED

concrete/src/Permission/Access/Entity/GroupEntity.php
If the group already deleted, an exception occurred when using a group entity of the deleted group.
```
Exception Occurred: /Users/hissy/Repositories/concrete5/concrete/src/Permission/Access/Entity/GroupEntity.php:21 Call to a member function getGroupMembers() on boolean (0)
```
Steps to reproduce:
1. Create a group
2. Create a Workflow then set a notification to the group
3. Apply the workflow from full sitemap page
4. Delete the group
5. Create a workflow request with approving a page
=> Avoid error on getting users of group permission access entity

concrete/blocks/core_area_layout/controller.php, concrete/blocks/core_stack_display/controller.php
If some block in the layout overrides their parent area's permission, and the block cannot be viewable, we shouldn't create a whole area cache.
Steps to reproduce the issue:
1. Create a layout on a page.
2. Add a block in the layout (Content block type is the best).
3. Set Schedule Guest Access for the block.
4. Open the "View as User" panel (c5 will create a layout cache even if the block is not viewable).
5. Change "Date / Time" to future. The scheduled block is still not viewable.
=> Fix layout cache issue

concrete/js/build/core/app/edit-mode/editmode.js
The issue of custom block templates set on the area not working for the Content block has been reported in #6069.
The location of the problem has been correctly identified in 
https://github.com/concrete5/concrete5/issues/6069#issuecomment-340458978 - there is a typo (I assume) in editmode.js - I could find any reference to `arCustomTemplate` anywhere, `arCustomTemplates` seems to be correct.
I confirmed the fix locally by editing app.js as well, but it needs to be compiled again after the merge. I left if away to avoid merge conflicts.
=> Fix arCustomTemplates in editmode.js

concrete/src/Block/Block.php, concrete/src/Block/BlockController.php
This allows the block setting "Block Container Class" with the values "Disable Grid Container" or "Enable Grid Container" to be exported. It also adds support to use it in the `concrete5-cif` format for packages or starting points.
=> Add support for custom container settings in import/export

concrete/src/Localization/Service/Date.php
`Misc::join` is deprecated in recent Punic library, but we have to keep using this method for old environment.
=> Fix failing test when added --prefer-lowest option

concrete/src/Validator/PasswordValidatorServiceProvider.php
It's very minor thing.
Some languages, such as Japanese, don't need to prepare special strings for plural.
In translation screen, we will type one translated strings.
In these 2 strings, singular string didn't contain %d character which could confuses some translators.
I recommend to keep using %d for singular string as well.
=> Make sure to use %d for singular string for better support some languages

concrete/composer.json
Older versions of this dependency can have issues with trusting IIS headers. We're already set to use `3.4.17` in composer.lock, let's just set composer.json to match
=> Codify the current symfony/http-foundation version

build/package.json
laravel-mix is managing these dependencies for us now. I believe I added these explicit version requirements because there was trouble with grunt integration, but I didn't have any trouble this time.
=> Remove explicit webpack version requirements

concrete/src/Page/View/PageView.php
Before this fix rendering the integrations single pages in the dashboard showed chrome less pages.
=> Fix error rendering the API integrations dashboard pages and other pages

concrete/authentication/concrete/controller.php, concrete/src/Application/Application.php, concrete/src/Logging/Entry/EntryInterface.php, concrete/src/Logging/Entry/User/LoginAttempt.php, concrete/src/Logging/LoggerAwareTrait.php, concrete/src/Logging/Processor/ServerInfoProcessor.php, concrete/src/Session/SessionFactory.php, concrete/src/Session/Storage/LoggedStorage.php, concrete/src/User/Login/LoginService.php, tests/tests/Logging/Entry/User/LoginAttemptTest.php, tests/tests/User/Login/LoginServiceTest.php
This PR:
- Adds a monolog processor that gives the ability to attach `$_SERVER` information to all log entry contexts
- Adds login logging on the authentication channel, both successes and failures
- Wraps the session storage object to log relevant session modifications
I've also added an interface that defines how to delegate the responsibility of building the log message and context to another class. The [LoginAttempt](https://github.com/concrete5/concrete5/compare/develop...KorvinSzanto:feature/comprehensive-logging?expand=1#diff-f0e64195698bbdd3afb0a80bdc22e0d7) class is a good example of this.
--- 
Here's my testing configuration:
```
'log' => [
'configuration' => [
'advanced' => [
'configuration' => [
'handlers' => [
'syslog' => [
'class' => SyslogHandler::class,
'ident' => 'FOO', …
```
=> Add logging to the login / logout flow and to sessions

concrete/src/Database/DatabaseServiceProvider.php
A shortcut for calling database connection
`
$db = $app->make('database/connection');
`
=> What about making an Alias for Database Connection

concrete/src/Permission/Key/Key.php
Now, we can't create a [custom task permission](https://documentation.concrete5.org/developers/permissions-access-security/creating-custom-permissions) with custom class without creating a new category.
This PR allows to create custom task permissions to existing category with custom class from a package.
=> Allow custom class loading from the package for a custom permission key

concrete/src/Database/CharacterSetCollation/Resolver.php
`getSupportedCollations()` returns: [array keys: collation (always lower case); array values: associated character set (always lower case)](https://github.com/concrete5/concrete5/blob/738690996281c45d1d193c120a27c047dc013850/concrete/src/Database/Connection/Connection.php#L457), so `$characterSet !== $collations[$characterSet]` will never evaluate correctly.
=> fix: charsets are values in $collations array, not keys

composer.lock, concrete/authentication/external_concrete5/controller.php, concrete/authentication/external_concrete5/type_form.php, concrete/composer.json, concrete/config/app.php, concrete/controllers/single_page/dashboard/system/api/integrations.php, concrete/single_pages/dashboard/system/api/integrations/edit.php, concrete/single_pages/dashboard/system/api/integrations/view_client.php, concrete/src/Api/ApiServiceProvider.php, concrete/src/Api/OAuth/Controller.php, concrete/src/Api/OAuth/Server/ClaimsSetFactory.php, concrete/src/Api/OAuth/Server/IdTokenResponse.php, concrete/src/Authentication/Type/ExternalConcrete5/ExternalConcrete5Service.php, concrete/src/Authentication/Type/ExternalConcrete5/Extractor.php, concrete/src/Authentication/Type/ExternalConcrete5/ServiceFactory.php, concrete/src/Authentication/Type/OAuth/OAuth2/GenericOauth2TypeController.php, concrete/src/Entity/OAuth/AccessToken.php, concrete/src/Entity/OAuth/Client.php, concrete/src/Entity/OAuth/RefreshToken.php, concrete/src/Updater/Migrations/Migrations/Version20190110194848.php, concrete/src/Updater/Migrations/Migrations/Version20190110231015.php, concrete/src/Updater/Migrations/Migrations/Version20190111181236.php, concrete/views/oauth/authorize.php, concrete/views/oauth/consent/simple.php
Our oAuth2 server previously only provided authorization for our API server, luckily we had an API endpoint that would give us information about the user's account so we were able to use this for authentication as well. OIDC adds an 'id_token' when the `openid` scope is requested which contains everything we need for authentication so that we don't even need to use the API (other than oauth endpoints) to authenticate anymore.
Also I've put a little more thought into how the scope consent flow should work:
* Instead of showing an arbitrary list of requested scope keywords, let's give all default scopes a description and show that in a list instead (openid is hidden)
* Instead of giving the user a checkbox to allow or deny access, just give them a single button. They can "deny" by not …
=> Add OIDC id tokens and add consent levels to integrations

concrete/controllers/backend/file.php
The download button in the View Image dialog in the Dashboard currently throws an error. Let's fix it by removing the deprecated FilePermissions call (which has a missing class) and instead just performing the permissions check in getRequestFiles.
=> Fix broken download file button when viewing an image in the file manager

concrete/src/Permission/Response/AreaResponse.php
Issue: can't add page type composer control output block on page type default, if you're signed in as a non-admin user, even if you have a right permission to edit page type defaults.
My fix works and fixes the issue, but I'm worrying this is the right way to fix this issue.
=> Make it enable to adding page type composer control block

concrete/blocks/express_form/controller.php, concrete/blocks/topic_list/controller.php
`\Concrete\Core\Multilingual\Page\Section\Processor\ReplaceBlockPageRelationsTask::execute` doesn't affect for topic_list block. I found the reason, `$btExportPageColumns` is missing.
Question: Is it possible to add `internalLinkCID` column in `btImageSliderEntries` table? This value will not replaced too.
=> Add missing $btExportPageColumns

concrete/blocks/express_form/controller.php
How to reproduce:
1. Add an express form block(includes a file field with HTML input mode).
2. Select a file from your local then submit the form.
3. Check the file manager. You'll see two files.
=> Fix: Express form uploads the same file at twice

concrete/src/Application/Service/Urls.php
=> Fix Urls::getBlockTypeAssetsURL() when the asset is not a JS/CSS asset

concrete/src/API/API.php
Now that scopes are requested rather than defined when setting up integrations, let's make it so that the built in API client can have its scopes configured.
In order to configure this one would have to implement `APIProviderInterface`
=> Make API client have configurable scopes

concrete/src/Page/Type/Composer/Control/BlockControl.php
=> Avoid accessing undefined var in BlockControl::validate()

concrete/src/Page/Template.php
It's called statically [here](https://github.com/concrete5/concrete5/blob/0182666c9a818f135d3de006bbaa1f9e3a88458d/concrete/controllers/single_page/dashboard/pages/templates/add.php#L13) and [here](https://github.com/concrete5/concrete5/blob/0182666c9a818f135d3de006bbaa1f9e3a88458d/concrete/controllers/single_page/dashboard/pages/templates.php#L50).
=> Make Template::getIcons() static

concrete/src/Package/Package.php
We currently read package changelogs from files named `CHANGELOG`.
What about reading also from `CHANGELOG.txt` and from `CHANGELOG.md`?
=> Read package changelog from txt and md files too

concrete/views/dialogs/user/search.php
Currently when using a userSelector if you search for a user or load a new page and try to use the dropdown to select user(s). The option will disappear.
This PR changes the event from onLoad to onUpdateResults so the choose users option is not lost.
To reproduce on a clean install. 
Go to /dashboard/system/conversations/settings then click on the + icon under ‘Users To Receive Conversation Notifications‘ then search for ‘admin‘ if you click on the checkbox then the drop down. The drop down will be missing the choose users option
=> Fix User Selector when searching/loading new pages

concrete/composer.json
This is similar to #7533 but with the symfony/console dependency. This doesn't change anything for general releases, but allows composer based concrete5 to install newer versions.
=> Allow newer versions of symfony/console as well

concrete/config/concrete.php, concrete/src/System/Mutex/SemaphoreMutex.php, concrete/src/System/SystemServiceProvider.php, tests/tests/System/MutexTest.php
We have some reports of users whose installaion/upgrade fails because of this error:
```
sem_get(): failed for key 0x1234abcd: No space left on device
```
(the `0x1234abcd` part may vary).
This error may occur when PHP is configured to enable semaphores, and concrete5 uses them with the `sem_get()` PHP function.
This `sem_get()` PHP function [calls the `semget()` system function](https://github.com/php/php-src/blob/php-7.3.1/ext/sysvsem/sysvsem.c#L216) which, in case there are no more available semaphores, [returns the `ENOSPC` error identifier](http://man7.org/linux/man-pages/man2/semget.2.html#ERRORS).
The system description of this `ENOSPC` is [`No space left on device`](https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html#index-ENOSPC).
So, a more correct description of …
=> Improve mutex

tests/config/database.php
I don't know why, but using `localhost` prevents from running tests in Windows Subsystem for Linux (the `bash` shell that's integrated in recent Windows 10 versions).
Using `127.0.0.1` works fine.
=> Use 127.0.0.1 instead of localhost in test DB connection

composer.json, composer.lock
See https://github.com/concrete5/dependency-patches/releases/tag/1.2.0
Fix  #7481
=> Update dependency patches to apply zend-http security fix

concrete/src/Http/ResponseFactory.php, concrete/src/Page/Collection/Version/Version.php
This PR fixes all three issues described in #7540
We now check to see if the active page has an end date and deny.
We now display 404 error with content like other pages do rather than redirect - this also fixes issues with browsers not respecting the header no-cache
=> Fixing issue #7540

concrete/src/Console/Parser.php
This fixes the following error:
TypeError: Argument 4 passed to Symfony\Component\Console\Input\InputOption::__construct() must be of the type string, null given, called in concrete/src/Console/Parser.php on line 134 in file vendor/symfony/console/Input/InputOption.php on line 44
=> CLI options: assume empty description instead of NULL

concrete/single_pages/account/edit_profile.php
This fixes the following issue:
`Call to a member function getTimezones() on null`
(that's because we have to use `$date` instead of `$helper_date`)
=> Use $date instead of $helper_date in edit_profile view

concrete/src/Logging/Configuration/ConfigurationFactory.php, concrete/src/Logging/Configuration/SimpleConfiguration.php, concrete/src/Logging/Processor/Concrete5UserProcessor.php, tests/tests/Logging/LogTest.php, tests/tests/Logging/Processor/Concrete5UserProcessorTest.php
This PR:
* Inverts dependencies for `Concrete5UserProcessor` making it possible to test it without connecting to the database
* Inverts dependencies for the factories in the chain that create the processors so that they can pass in dependencies in an inverted way
* Adds full unit test coverage of the `Concrete5UserProcessor` class without connecting to the database or having any other coupled dependencies tested what-so-ever
=> Invert dependencies for simple logging processors

concrete/blocks/page_list/controller.php
An unexpected value will be stored when editing page list block on a master collection
```php
$cPID = 0;
$cParentIDs = [
"0", // Everywhere
"195", // Beneath this page
"OTHER", // Beneath another page
];
// Expected:
// bool(true)
// bool(false)
// bool(false)
// Same as current controller
foreach ($cParentIDs as $cParentID) {
var_dump(($cParentID == $cPID));
}
// bool(true)
// bool(false)
// bool(true)
// How about changing == to === ?
foreach ($cParentIDs as $cParentID) {
var_dump(($cParentID === $cPID));
}
// bool(false)
// bool(false)
// bool(false)
// How about using intval function if the valud is numeric?
foreach ($cParentIDs as $cParentID) {
if (is_numeric($cParentID)) {
$cParentID = intval($cParentID);
}
var_dump($cParentID == $cPID);
}
// bool(true)
// bool(false)
// bool(true) …
```
=> Improve sanitization in page list controller

.travis/rebuild-assets.sh
The current TravisCI job that automatically rebuilds CSS/JS assets is configured to only do that on the `develop` branch.
Since concrete5 has multiple branches, we have to do that on any branch, not only on `develop`.
So, with this pull request, assets are rebuilt when all the following conditions are met:
- it's not a pull request
- it's not a build triggered by a tag
=> (Re)build CSS/JS assets on any branch

concrete/controllers/single_page/dashboard/users/search.php
This fix these warnings
```
Undefined property: Concrete\Controller\SinglePage\Dashboard\Users\Search::$canEditAvatar
Undefined property: Concrete\Controller\SinglePage\Dashboard\Users\Search::$canEditUserName
...
Undefined property: Concrete\Controller\SinglePage\Dashboard\Users\Search::$canAddGroup
```
Ref. #4723
=> Always define accessibility properties when editing a user

concrete/src/Http/Client/Client.php
This fixes the following `E_STRICT` warning:
```
Concrete\Core\Http\Client\Client
and
Concrete\Core\Logging\LoggerAwareTrait
define the same property ($logger) in the composition of
Concrete\Core\Http\Client\Client
This might be incompatible, to improve maintainability consider using accessor methods
in traits instead.
Class was composed
```
@aembler What about turning on the `Consider warnings as errors` flag in the `dashboard/system/environment/debug` dashboard page? This is very helpful to spot problems while developing :wink:
=> Http Client: avoid double definition of $logger

concrete/controllers/single_page/account/messages.php
The `Concrete\Core\Helper\Validation\Error` class does not exist: we should use `Concrete\Core\Error\ErrorList\ErrorList`
=> Correctly detect if sendPrivateMessage returned an error

concrete/src/User/PrivateMessage/Limit.php
These two methods are [called statically](https://github.com/concrete5/concrete5/blob/6a204e60a10050e5589aebc1ec72f29b997712cd/concrete/src/User/UserInfo.php#L349-L351).
Ref. #4723
=> Define PrivateMessage\Limit methods as static

concrete/css/build/core/app/panels.less, concrete/js/build/core/app/edit-mode/editmode.js, concrete/views/panels/add.php
About the "Add Stack" panel:
1. let user drag the stack name, not just the icon
2. add an arrow to expand the stack content
2. collapse the stack content if the arrow is clicked again.
This should fix everything in #7526 except point 3 (I haven't take a look at that specific issue yet).
=> Add Stack panel: draggable name, toggle expansion

concrete/src/Page/Controller/DashboardPageController.php
The names of the dashboard pages are translated everywhere, except in the html `<title>` tag: let's fix this.
=> Translate dashboard page titles

concrete/controllers/single_page/dashboard/users/search.php
We turned an array into a boolean by not properly checking what was going on in a particular block of code, leading to attributes being unable to be edited on a user detail page in the Dashboard. This should fix that.
=> Fix broken user attribute editing introduced in #7562

concrete/src/Http/Client/Client.php
The `getBody` method of the Response object may throw Exceptions.
This leads to a broken execution.
PS: before the logging stuff was refactored, this wasn't a big problem since the Http Client logger was set only if configured so.
=> Ignore errors when logging HTTP requests

concrete/config/concrete.php
Client who is very picky about grammar point out missing `and` in the error message.
So sending a PR for it.
=> Add mission "and" to password restriction error message

concrete/views/dialogs/page/add/compose.php
This PR fixes a small issue with the **Add Page** dialog `btn-group` :
Before :
After :
=> Fixing compose btn group

concrete/src/Form/Service/Widget/DateTime.php
The most recent version of google chrome isn't supporting the value `nope` for autocompletion which was implemented on https://github.com/concrete5/concrete5/pull/7234.
The Mozilla documentation also has removed this from their [documentation](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion). 
[Edit History](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion$history)
=> Change datepicker autocomplete value from `nope` to `off`

concrete/blocks/page_list/controller.php, concrete/blocks/page_title/controller.php
How to reproduce
Access to page list with invalid year & month like:
http://concrete5.test/index.php/blog/10000/13
You'll get this error: `Can't convert '10000-13-01 00:00:00' to a \DateTime`
=> Validate given year & month value to avoid error

concrete/src/Http/DefaultDispatcher.php, concrete/src/Session/SessionValidator.php
Fixes issue #6699.
The ccmAuthUserhash cookie was only evaluated when a session existed, which usually does not since the GDPR changes, so now it gets evaluated if there is no session or no uID set in the session.
SessionValidator needed to be changed because with the above changes we have a started session but haven't set the session cookie in $app['cookies'].
=> Fix issue #6699, 'Stay signed in for two weeks' not working

concrete/config/concrete.php, concrete/src/Page/Cloner.php, concrete/src/Page/Stack/Stack.php, concrete/src/Updater/Migrations/Migrations/Version20190301133300.php
When we create a localized version of a Stack, we (mistakenly) added two rows in the `Stacks` database table ([here](https://github.com/concrete5/concrete5/blob/0dab0af0d9ed1a235357a5201e23a01fa33e1371/concrete/src/Page/Cloner.php#L159-L164) and [here](https://github.com/concrete5/concrete5/blob/0dab0af0d9ed1a235357a5201e23a01fa33e1371/concrete/src/Page/Stack/Stack.php#L463-L471)).
Let's just add one row.
I also included a migration that fixes those duplicated rows.
Fix #7615
=> Fix creation of localized stacks/global areas

concrete/src/User/UserList.php, tests/tests/User/GroupTest.php
This PR fixes an issue with PathNames not being correctly sanitised.
It also fixes an issue with ->filterByInAnyGroup($groups, false) - not always correctly filtering if the user is in multiple groups. 
It also cleans up the code a bit better and Ive also added tests for filterByInAnyGroup.
=> Fixing User List Group Filters

concrete/src/Console/Command.php
| Before | After |
|:---:|:---:|
| ![immagine](https://user-images.githubusercontent.com/928116/53580582-3b657880-3b7c-11e9-8b8b-08574d49b485.png) | ![immagine](https://user-images.githubusercontent.com/928116/53580593-43251d00-3b7c-11e9-9519-263d2aa04e3b.png) |
=> Don't override CLI commands description if already set

concrete/blocks/survey/view.php
See https://www.concrete5.org/developers/bugs/8-4-3/survey-bug-count-parameter-must-be-an-array-or-an-object-that-im/
=> Fix counting non countable in Survey block view

.travis.yml, .travis/composer-deps.sh, .travis/rebuild-assets.sh
The current TravisCI configuration report leads to a quite cryptic name/variable list:
https://travis-ci.org/concrete5/concrete5/builds/490430820
What about switching to a wonderful list with beautiful job names?
https://travis-ci.org/mlocati/concrete5/builds/490466416
Furthermore, moving the code-coverage job to the first position may help saving some time.
PS: in order to avoid merge conflicts, I included #7558 in this PR.
=> TravisCI: sort jobs and give them a name

concrete/src/Page/Page.php
In case we have malformed data in the Pages table (that is, cID === cParentID), the rescanCollectionPath method runs forever.
Let's avoid that.
=> Avoid infinite recursion in Page::rescanCollectionPath()

concrete/src/File/Image/Thumbnail/Type/CustomThumbnail.php
When [we added upscaling as a configurable part of thumbnail types](https://github.com/concrete5/concrete5/commit/fb5176710cad83d679480d7935c92b928bc2f176), we inadvertently changed `CustomThumbnail` instances to fail to generate thumbnails larger than their source image. That's not necessarily a bad thing but it's a break in backwards compatibility that's better suited for 9.0 and some documentation.
=> Make sure custom thumbnails have upscaling enabled

concrete/controllers/dialog/page/sitemap_selector.php, concrete/js/build/core/sitemap/search.js, concrete/js/build/vendor/redactor/redactor.js, concrete/js/ckeditor4/core/concrete5link/plugin.js, concrete/routes/dialogs/pages.php, concrete/views/dialogs/page/drag_request.php, concrete/views/dialogs/page/sitemap_selector.php
This PR fixes the issue with #7572 and also moves sitemap_search_selector to the CCM route system
I have kept the old sitemap_search_selector in tools incase of any packages using it (unlikely but don't want to BC break)
=> Fix #7572 and Moving sitemap_search_selector from tools to new route

concrete/elements/page_controls_footer.php
How to reproduce:
1. Edit a page and set schedule
2. Add a new user
3. Change the permission of the page. Give "View Versions" permission only to the user
4. Sign in as the user then access to the page
5. You can see the "Publish Now" button but you can't publish because you can't approve versions
=> Hide "Publish Now" button from a user who can’t approve versions

concrete/controllers/single_page/dashboard/extend/install.php
On package uninstallation if you select `Yes, remove the package's directory from the installation directory.` It shows the following error. This PR fixes the error.
```
Object of class Concrete\Package\MyPackage\Controller could not be converted to string
```
=> Fix error on package uninstall while remove the package directory is checked

concrete/src/Session/SessionValidator.php
When getting a value from the Session, we have to:
1. get the `SessionValidator` instance
2. check if `SessionValidator::hasActiveSession()`
3. get the session instance if it returns `true`
What about simplifying it a bit, by adding `SessionValidator::getActiveSession()`?
=> Add SessionValidator::getActiveSession()

concrete/src/Support/Symbol/PhpDocGenerator.php
The `output_vars` function generates PHPDoc describing the defined variables.
This PR changes its output, so that it generates phpdoc comments instead of normal comments.
=> output_vars: change "/* @var" to "/** @var"

concrete/src/Localization/Service/Date.php
the Config class is called in various places within the Concrete\Core\Localization\Service\Date Class but it wasn't imported yet which leads to Class not found exceptions when certain methods are used.
=> import Config class for usage

concrete/blocks/search/controller.php, concrete/blocks/search/db.xml, concrete/blocks/search/form_setup_html.php, concrete/src/Updater/Migrations/Migrations/Version20190416224702.php
The Everywhere option in the Search block is limited only to the current site and not to across all sites. 
This update adds a new Search All option that be available if the project has more than one site.
=> Add Search All Sites functionality to the Search Block

concrete/src/Form/Service/Form.php
When there's no currently selected country, we display a blank option.
What about allowing developers to display a custom text for this case?
=> Add 'noCountryText' option to Form::selectCountry()

concrete/src/Page/Stack/Stack.php
https://github.com/concrete5/concrete5/blob/0c349867acc59458f2a6df8a98c485e6720440b2/concrete/src/Page/Stack/Stack.php#L78
This actually returns `Stack|false|null`.
This PR fixes some warnings, adds new phpdoc blocks including the above fix.
=> Update phpdoc and fix some warnings of Stack class

concrete/src/File/Image/Svg/Sanitizer.php
There are some LIBXML constants that may not be defined.
Accordingly to the [PHP docs](https://www.php.net/manual/en/libxml.constants.php), those constants should be defined for PHP 5.5+, but a concrete5 user reported that they are not defined (his PHP version is compiled with libxml 2.7.6 even if PHP is 7.1.28).
So, we have to check if these variables are defined.
=> Check that LIBXML constants are defined

concrete/src/Marketplace/Marketplace.php
When concrete5 is executed by a reverse proxy (Cloudflare, Apache behind Nginx. ...), `$_SERVER['HTTPS']` may return an invalid value: we have to rely on the scheme property of the Request instance (which already correctly handles proxy-related stuff).
=> Fix detection of HTTP/HTTPS in Marketplace

concrete/js/build/core/app/dialog.js
I often use jQueryUI dialogs like this:
```html
<div id="my-dialog">
Contents
</div>
<script>
var $dialog = $('#my-dialog').dialog({my:options});
</script>
```
BTW, with this approach, there's no easy way to render the dialog buttons in the concrete5 default style.
So, what about supporting a syntax like this?
```html
<div id="my-dialog">
Contents
<div class="dialog-buttons">
<button class="btn btn-default pull-left">Cancel</button>
<button class="btn btn-primary">Save</button>
</div>
</div>
```
This is the same approach syntax used by the core when creating dialogs with `$('#my-dialog').dialog();`
=> Render jQueryUI dialog buttons in concrete5 style

concrete/src/Page/Collection/Collection.php
Calling `Version::getAttributeValue($ak)`  is exactly the same as calling `Version::getAttributeValueObject($ak, false)` (see [here](https://github.com/concrete5/concrete5/blob/b5648881c19529753a5f81e15fece3313374931e/concrete/src/Attribute/ObjectTrait.php#L38)).
In order to correctly forward the value of the `$createIfNotExists` parameter, we should call `Version::getAttributeValueObject($ak, $createIfNotExists)`.
=> Fix Collection::getAttributeValueObject call

concrete/src/Entity/Calendar/CalendarEventOccurrence.php
The assumpition that allDay Events have a diff of 0 is wrong. All Day Events are saved with a Duration from 00:00:00 to 23:59:59 which would be a int value of 86399
=> Fix AllDay determination of Event Occurrences

concrete/src/Editor/CkeditorEditor.php
It'd be very useful to be able to fine tune the Rich Text editor.
Since every editor has its own specific options, we can't add a method to the `EditorInterface` interface (options for `CkeditorEditor` may not be applicable to `RedactorEditor`, and vice versa), so I added here a `outputEditorWithOptions` method only to the `CkeditorEditor` class.
=> Add CkeditorEditor::outputEditorWithOptions()

concrete/blocks/calendar/view.php
This PR fixes the following two issues of the calendar block related to [fullcalendar](https://fullcalendar.io).
- Doesn't show the last date of the events which end time is before 9 am. Because full calendar has `default: "09:00:00" (9am)` [threshold](https://fullcalendar.io/docs/nextDayThreshold).
- Doesn't show the last date of an all-day event. It's because `The exclusive date/time an event ends`. Check [here](https://fullcalendar.io/docs/event-object)
Noted that, it doesn't reflect on the dashboard page because of PHP validation.
There is a discussion regarding this issue on full calendar git and it's still open!
https://github.com/fullcalendar/fullcalendar/issues/2985
=> Fix calendar block issues with all-day events

concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
The user would be able to specify in config an individual from email simply by using the form handle name. (e.g concrete.email.form_block.my_super_contact_form.address).
=> Add the ability for each Express Form block to have its own from address.

concrete/controllers/single_page/dashboard/system/environment/info.php, concrete/src/Console/Command/InfoCommand.php, concrete/src/System/Info.php
What about adding this information to the `/dashboard/system/environment/info` dashboard page and to the `c5:info` CLI command?
Sample output of the `c5:info` CLI command (notice the new `# Database Information` section):
```
Installed - Yes
Core Version - 8.5.2a1
Version Installed - 8.5.1
Database Version - 20190301133300
Version - 5.7.24
SQL Mode - NO_ENGINE_SUBSTITUTION
Web root - /path/to/concrete5
[...]
```
=> Add MySQL version and SQL_MODE to environment information

concrete/src/Http/DefaultDispatcher.php
The use of the `$callDispatcher` variable is useless: let's remove it.
=> Simplify DefaultDispatcher::handleDispatch()

concrete/controllers/single_page/dashboard/users/groups/message.php
The send message to group page was not displaying the correct qualified label.
=> Changed group name to the correct qualified label

concrete/src/Entity/File/File.php
In case the `uID` field of the `Files` table points to a deleted user, we have an uncaught `EntityNotFoundException` exception: let's intercept this issue.
PS: Let's also add the `getUser()` method (the author is already an instance of the User entity)
=> Check that the File author was not removed

concrete/src/Console/Command/Express/ExportCommand.php, concrete/src/Console/ServiceProvider.php, tests/tests/Console/ServiceProviderTest.php
This command takes a single argument `entity` which matches the handle of the entity we export.
=> Add a simple command to export express entries

composer.lock
[Changelog](https://github.com/punic/punic/releases/tag/3.4.0)
=> Update Punic from 3.3.1 to 3.4.0

concrete/src/Localization/Service/CountryList.php
This is not a BC break. the result is the same. The only difference is that PHP won't raise a warning in case a country code is not valid.
Ref. #4723
=> Avoid accessing undefined array index in CountryList::getCountryName()

concrete/blocks/document_library/controller.php
This commit fixes also the false navigate URL that comes when you click on a folder
(e.g /ccm/system/block/action/edit/1846/Main/490/navigate/1401)
=> Replace deprecated function action() with getActionURL() in Document Library Block

concrete/src/Multilingual/Service/Detector.php
`isEnabled()` & `getPreferredSection()` has been called dynamically in everywhere.
Should we remove the `static` keyword then?
https://github.com/concrete5/concrete5/blob/0c349867acc59458f2a6df8a98c485e6720440b2/concrete/src/Multilingual/Service/Detector.php#L24
https://github.com/concrete5/concrete5/blob/0c349867acc59458f2a6df8a98c485e6720440b2/concrete/src/Multilingual/Service/Detector.php#L154
=> Remove 'static' keyword from isEnabled() and getPreferredSection()

concrete/blocks/express_form/controller.php
If the form redirects to a thank you page, pass the entry id so that the page can interact with the entry if desired.
=> Entry ID to thanks page

concrete/bootstrap/helpers.php, concrete/src/Support/Symbol/PhpDocGenerator.php
Followup of https://github.com/concrete5/concrete5/pull/7790#discussion_r285199509
For example, the output of `output_vars(get_defined_vars(), $this);` when placed in `/concrete/single_pages/login.php` changes from
```php
/** @var array $authTypeParams */
/** @var Concrete\Core\Page\Page $c */
/** @var Concrete\Controller\SinglePage\Login $controller */
/** @var Concrete\Core\Form\Service\Form $form */
/** @var Concrete\Core\Html\Service\Html $html */
/** @var string[] $locales */
/** @var array $scopeItems */
/** @var Concrete\Theme\Concrete\PageTheme $theme */
/** @var Concrete\Core\Page\View\PageView $this */
/** @var string $uNameLabel */
/** @var Concrete\Core\Validation\CSRF\Token $valt */
/** @var Concrete\Core\Page\View\PageView $view */
```
to
```php
/**
* @var array …
```
=> Let output_vars() generate just one docblock

concrete/controllers/install.php, concrete/views/frontend/install.php
Install errors/warnings contains a title and an error message.
We currently display them on the same line, which may result in a bit odd sentences:
What about separating titles and messages?
=> Format install errors

concrete/blocks/image/view.php
- rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
- rel="noreferrer" attribute has the same effect, but also prevents the Referer header from being sent to the new page.
As the following link describes 
https://developers.google.com/web/tools/lighthouse/audits/noopener
=> Add rel="noopener noreferrer" to external link in image block

concrete/blocks/social_links/view.php
- rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
- rel="noreferrer" attribute has the same effect, but also prevents the Referer header from being sent to the new page.
As the following link describes
https://developers.google.com/web/tools/lighthouse/audits/noopener
=> Add rel="noopener noreferrer" to external link in social_links block

concrete/blocks/share_this_page/view.php
- rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
- rel="noreferrer" attribute has the same effect, but also prevents the Referer header from being sent to the new page.
As the following link describes
https://developers.google.com/web/tools/lighthouse/audits/noopener
=> Add rel="noopener noreferrer" to external link in share_this_page block
