- concrete/src/Job/Job.php
- concrete/src/Site/Service.php
- concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
See every comment result.
Fix #5743
This need some more testing, but it should already be much better than what we currently have.
> Fix migration of locale-related stuff from 5.7 to 8.x

- concrete/js/ckeditor4/core/concrete5link/plugin.js
this fixes #5797
I left a long comment at line 25 explaining the problem that was throwing a JS error. It might have something to do with how C5 loads the editor
> takes care of #5797

- concrete/src/File/File.php
> Define undefined FileUploaderPermissionAccessEntity in File

- .travis.yml
- tests/tests/CreateClassMockTrait.php
If travis passes and is faster after rerunning, we'll merge this.
> Remove `--prefer-source` and only cache the composer cache

- concrete/tools/dashboard/sitemap_drag_request.php
> Avoid accessing undefined array index in sitemap_drag_request tool

- concrete/controllers/panel/detail/page/attributes.php
> Avoid accessing undefined array indexes in page attribute panel controller

- concrete/blocks/feature/form.php
> Feature block: increase the preview icon size

- concrete/blocks/external_form/add.php
- concrete/blocks/external_form/controller.php
- concrete/blocks/external_form/edit.php
- concrete/blocks/external_form/form.php
- concrete/config/concrete.php
- concrete/src/Updater/Migrations/Migrations/Version20170808000000.php
This pull requests makes a few small text changes and updates some of the code.
**Current:**
**Changes:**
> External Form block update

- concrete/src/Page/Stack/Pile/PileContent.php
It's called statically
Ref #4723
> Define PileContent::get as static

- concrete/src/File/Importer.php
This method is called statically: let's make it static.
Ref #4723
> Make File\Importer::getErrorMessage() static

- concrete/single_pages/download_file.php
> Avoid accessing undefined variable $rc in download_file view

- concrete/src/Filesystem/FileLocator/ThemeLocation.php
- tests/tests/Core/Filesystem/FileLocatorTest.php
> Fix packaged theme block template location url

- composer.lock
Adds support to localization of geolocation library names and descriptions in CIF files
> Update the translation-library

- concrete/src/Application/UserInterface/Sitemap/FlatSitemapProvider.php
> Avoid accessing undefined var in FlatSitemapProvider

- tests/tests/Core/Localization/LocalizationTest.php
- tests/tests/Localization/LocalizationTest.php
This PR should fix the failing tests related to localization (see for instance https://travis-ci.org/concrete5/concrete5/jobs/274506588 )
> Fix the localization tests

- concrete/controllers/dialog/type/update_from_type.php
`$this->app(Service::class)::method` is not valid for PHP 5.x
> Make update_from_type dialog controller compatible with PHP 5.x

- concrete/authentication/concrete/invalid_token.php
This PR updates the invalid token message of concrete authentication.
> [Fix] Invalid token message

- concrete/config/concrete.php
- concrete/src/Workflow/BasicWorkflow.php
I want to make the basic workflow notification from address and name to be configurablevia config file.
Plus, I don't think from email process should be inside of the foreach.
> Make Basic Workflow Notification From Address and Name configurable

- concrete/controllers/single_page/dashboard/express/entries.php
- concrete/src/Page/Controller/DashboardExpressEntityPageController.php
parent method https://github.com/concrete5/concrete5/blob/439de21f61c2862fc3c8111ea9e3fc078762eda7/concrete/src/Page/Controller/DashboardExpressEntriesPageController.php#L113
> Fix declaration error on php 7

- concrete/elements/dashboard/pages/types/header.php
> Avoid accessing undefined vars in dashboard/pages/types/header element

- concrete/elements/dashboard/system/permissions/blacklist/menu.php
> Fix position of dropdown menu in blacklist dashboard page

- concrete/authentication/concrete/controller.php
- concrete/src/User/ValidationHash.php
This PR fixes the issue #5938 
It checks the password validation hash lifetime based on different types.
> [Fix #5938] Validation hash lifetime check

- concrete/src/User/UserInfo.php
What about adding a n `on_user_deleted` event like we did in https://github.com/concrete5/concrete5-legacy/pull/1769 ?
> Add on_user_deleted event

- concrete/attributes/text/form.php
This fixes self-XSS in the dashboard pages where this text is modified.
> Fix XSS in created attribute H1 244046

- concrete/tools/files/importers/remote.php
> Show generic error for connect failures, disallow downloading from localhost

- concrete/single_pages/dashboard/users/groups.php
Prevent XSS in group badge description, see H1 #247520
> Prevent XSS in group badge description

- concrete/attributes/textarea/form.php
- concrete/single_pages/dashboard/system/seo/bulk.php
This prevents XSS in the sitemap dialog and in the bulk seo dashboard page. See H1 247529
> Prevent XSS in textarea attribute form

- concrete/tools/files/importers/remote.php
> Sanitize content type before outputting in remote file updater

- concrete/views/frontend/install.php
This PR adds an arrow on `Advanced Options` panel.
> Improve setup page UI

- concrete/src/Http/ResponseFactory.php
allows the app to override which object User points to.
closes #6025
> change the use statement for ResponseFactory

- concrete/src/Install/Preconditions/Cookies.php
- concrete/src/Install/Preconditions/DomExtension.php
- concrete/src/Install/Preconditions/FileinfoExtension.php
- concrete/src/Install/Preconditions/ImageManipulation.php
- concrete/src/Install/Preconditions/InternationalizationSupport.php
- concrete/src/Install/Preconditions/Javascript.php
- concrete/src/Install/Preconditions/JsonExtension.php
- concrete/src/Install/Preconditions/MemoryLimit.php
- concrete/src/Install/Preconditions/NoAspStyleTags.php
- concrete/src/Install/Preconditions/PdoMysqlExtension.php
- concrete/src/Install/Preconditions/PhpCommentsPreserved.php
- concrete/src/Install/Preconditions/PhpVersion.php
- concrete/src/Install/Preconditions/RemoteFileImporting.php
- concrete/src/Install/Preconditions/RequestUrls.php
- concrete/src/Install/Preconditions/TokenizerExtension.php
- concrete/src/Install/Preconditions/WritableDirectories.php
- concrete/src/Install/Preconditions/XmlSupport.php
- concrete/src/Install/Preconditions/ZipSupport.php
> Don't translate install precondition identifiers

- concrete/single_pages/dashboard/reports/logs.php
This pull request adds a confirmation prompt before clearing a specific channel log or all channel logs.
https://github.com/concrete5/concrete5/issues/6034
> Require confirmation before clearing logs

- concrete/src/Backup/ContentImporter/Importer/Routine/ImportAttributeCategoriesRoutine.php
- concrete/src/Backup/ContentImporter/Importer/Routine/ImportAttributeTypesRoutine.php
> Allow associating attribute categories to existing attribute types

- concrete/src/Install/Preconditions/WritableDirectories.php
Fix grammatical error in the plural sentence.
> Fix grammatical error

- concrete/src/Entity/File/File.php
I'm really missing this :wink:
> Add PHPDoc to File::getApprovedVersion

- concrete/authentication/concrete/controller.php
- concrete/authentication/concrete/password_sent.php
Fix https://github.com/concrete5/concrete5/issues/6081
> [Fix#6081] Global password reset issue with email registration

- concrete/src/Attribute/Category/AbstractCategory.php
- concrete/src/Attribute/Category/CategoryInterface.php
- concrete/src/Attribute/Category/SearchIndexer/StandardSearchIndexerInterface.php
...and fix some minor coding style (see each commit)
> Attributes: add PHPDoc to AbstractCategory and StandardSearchIndexerInterface

- concrete/src/User/User.php
Reverts concrete5/concrete5#6094
> Revert "set 0 as uID when writing config record without being logged in"

- concrete/src/Csv/Import/AbstractImporter.php
- concrete/src/Csv/Import/CsvSchema.php
- concrete/src/Csv/Import/ImportResult.php
Let's let the CSV importer collect (part of) the imported data.
> Improve CSV importer

- concrete/src/Utility/Service/Url.php
> avoid E_NOTICE in case query string isn't set

- concrete/elements/header_required.php
What about letting javascripts know what's the code of the current locale?
> Let JavaScripts know the current locale

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/files/thumbnails/options.php
- concrete/single_pages/dashboard/system/files/thumbnails/options.php
- concrete/src/File/Image/Thumbnail/Type/Type.php
should take care of this https://github.com/concrete5/concrete5/issues/2633
> option to disable retina thumbnails added

- concrete/attributes/select/controller.php
- concrete/attributes/select/form.php
- concrete/attributes/select/type_form.php
- concrete/src/Entity/Attribute/Key/Settings/SelectSettings.php
- concrete/src/Updater/Migrations/Migrations/Version20171109065758.php
This should take care of this issue https://github.com/concrete5/concrete5/issues/5976
> allow hiding of none in select attribute

- concrete/src/Conversation/Editor/Editor.php
[Fix for hackerone report](https://hackerone.com/reports/277479)
> Sanitize conversation messages

- concrete/attributes/rating/controller.php
The current string is a bit hard to understand and translate. Change it to be more easy to understand.
> Change string content to be more understandable

- concrete/controllers/dialog/type/update_from_type.php
> Fix Queue Service calls

- concrete/src/Calendar/Event/EventService.php
> Fix calendar event publishing.

- concrete/config/concrete.php
- concrete/config/db.xml
- concrete/src/Page/Page.php
- concrete/src/Page/Type/Type.php
- concrete/src/Updater/Migrations/AbstractMigration.php
- concrete/src/Updater/Migrations/Migrations/Version20171117173822.php
Faster $page->isPageDraft() call.
> Faster page drafts

- concrete/config/install/packages/elemental_full/content.xml
> Update global search block Elemental full install default

- concrete/src/Express/Entry/Formatter/LabelFormatter.php
For example an entry mask could be "Boat #%id%" and the result would be "Boat #5"
> Make it possible to include the ID in the name mask

- concrete/src/Url/SeoCanonical.php
> Fix resolution of canonical URL for alias pages

- concrete/src/Updater/Migrations/Migrations/Version20170926000000.php
> Fix migration of btSearch table

- concrete/src/Area/GlobalArea.php
- concrete/src/Cache/CacheClearer.php
- tests/tests/Core/Routing/URLTest.php
This is an approach to delete empty global areas on cache clear as described here https://github.com/concrete5/concrete5/issues/6182
> delete empty global areas on cache clear

- concrete/attributes/calendar_event/controller.php
- concrete/attributes/calendar_event/search.php
There was a bug in the last two pull requests I did, where the second one rolled back the changes that I had made in the first. Also, on further testing, I found that I needed a search.php file in order to get the calendar picker to display in advanced search.
> Calendar event attribute fixes

- concrete/src/Page/Collection/Collection.php
> Add PHPDoc to the Collection class

- concrete/elements/workflow/notifications.php
This is a request from my client. I can do it by override, but I think this change is useful for every users. So I made this pull request.
> Add more information on workflow notification popup window

- concrete/single_pages/dashboard/system/registration/open.php
> Simplified the public registration settings form

- concrete/src/Entity/File/Image/Thumbnail/Type/Type.php
... and get rid of deprecated methods.
> Add PHPDoc to Thumbnail\Type entity

- concrete/src/File/Image/Thumbnail/Type/Type.php
... and get rid of deprecated methods.
> Add PHPDoc to Thumbnail\Type service

- concrete/src/Tree/Node/Node.php
Currently in concrete5 when a node is added/moved or delete it's parent is not updated.
This is quite annoying when you have folders to manage files and the have dates from months ago even though new files have been added.
I mirrored the same behaviour that Mac OS has when moving add/deleting files. Only the direct parent is updated when adding or deleting. With moving both destination and source folders are updated.
This also adds a function to the base node class that allows users to update the dateModified more easily.
> Updating Parent Node's Date Modified when children are moved/deleted/added

- concrete/src/Install/Preconditions/RequestUrls.php
> Avoid using an undefined var in RequestUrls install precondition

- concrete/src/Install/Preconditions/MemoryLimit.php
> Avoid using an undefined var in MemoryLimit install precondition

- concrete/blocks/search/controller.php
> Avoid accessing an undefined array index in search block controller

- concrete/src/Block/BlockType/Set.php
> Fix listing file sets

- concrete/src/Form/Service/Widget/UserSelector.php
FIx #4696 
Last pull request of the year :wink:
> Let UserSelector::selectMultipleUsers accept square brackets

- concrete/src/User/RegistrationService.php
> Fix RegistrationService::getNewUsernameFromUserDetails

- concrete/blocks/topic_list/view.php
There's an extra </li> in the toplic_list template.
> Removed stray </li> tag

- concrete/src/Job/Job.php
> Avoid accessing undefined array index in Job

- concrete/blocks/survey/controller.php
> Avoid accessing undefined indexes in Survey block controller

- concrete/blocks/tags/controller.php
> Avoid accessing undefined indexes in Tags block controller

- concrete/src/Page/PageList.php
Fix bug reported here : [issue 6296](https://github.com/concrete5/concrete5/issues/6296)
> Fix [Bug] filterByTopic / MySQL 5.7 compatibility

- concrete/jobs/generate_sitemap.php
Same as https://github.com/concrete5/concrete5-legacy/pull/1831
> Ignore master collections from sitemap.xml

- concrete/config/install/base/single_pages/dashboard.xml
- concrete/controllers/single_page/dashboard/system/mail/addresses.php
- concrete/single_pages/dashboard/system/mail/addresses.php
- concrete/src/Updater/Migrations/Migrations/Version20180120000000.php
https://github.com/concrete5/concrete5/issues/6298
> add System Email Addresses dashboard page

- concrete/src/Updater/Migrations/ManagedSchemaChangerInterface.php
In #6311 I committed a wrong interface declaration: this is the correct one.
> Fix declaration of ManagedSchemaChangerInterface

- concrete/src/User/PostLoginLocation.php
@mlocati I think this was a typo :)
> Fix post login redirect

- concrete/src/User/Avatar/AnonymousAvatar.php
- concrete/src/User/Avatar/StandardAvatar.php
> escape avatar name

- concrete/elements/files/properties.php
> escape folder name in file properties

- concrete/single_pages/account/messages.php
> Apply nowrap white space on private message box status column

- concrete/config/concrete.php
- concrete/config/db.xml
- concrete/src/Updater/Migrations/Migrations/Version20150619000000.php
- concrete/src/Updater/Migrations/Migrations/Version20180126000000.php
> Delete records in AreaLayoutsUsingPresets when deleting AreaLayouts

- concrete/src/Updater/Migrations/Migrations/Version20160725000000.php
I fixed the migration Version20160725000000: it was breaking upgrades when the `MultilingualPageRelations` database table contained invalid records.
Bonus track: I fixed a bug in the migration of multilingual Stacks.
> Fix migration when MultilingualPageRelations contains invalid data

- concrete/src/Search/Pagination/View/ConcreteBootstrap3PagerTemplate.php
> Avoid accessing undefined array indexes in ConcreteBootstrap3PagerTemplate::current

- composer.lock
- concrete/composer.json
See [changelog](https://github.com/avalanche123/Imagine/blob/develop/CHANGELOG.md)
> Upgrade Imagine to 0.7.1

- concrete/src/Page/View/PageView.php
> Avoid accessing the undefined pTemplatePkgHandle property in PageView

- tests/tests/File/ImporterTest.php
In [this Travis build](https://travis-ci.org/concrete5/concrete5/builds/338881796) there's [this error](https://travis-ci.org/concrete5/concrete5/jobs/338881799#L360): let's try to describe what's going wrong.
> Describe why Importer::import fails in ImporterTest test case

- concrete/elements/calendar/block/data_source.php
> Use Selectize for Data Source element select multiple inputs

- concrete/controllers/single_page/page_forbidden.php
> Avoid permanent redirect in page_forbidden

- concrete/views/dialogs/file/properties.php
> Avoid accessing undefined var in dialogs/file/properties view

- concrete/tools/files/replace.php
> Avoid accessing an undefined array index in files/replace tool

- concrete/controllers/frontend/jobs.php
> Avoid accessing undefined array indexes in jobs frontend controller

- concrete/tools/dashboard/sitemap_copy_all.php
> Avoid accessing undefined array indexes in dashboard/sitemap_copy_all tool

- concrete/controllers/single_page/dashboard/system/multilingual/page_report.php
> Avoid accessing undefined array indexes in multilingual/page_report page controller

- concrete/blocks/form/mini_survey.php
> Avoid accessing undefined var in form/mini_survey

- concrete/single_pages/dashboard/files/sets.php
> Avoid accessing an undefined array index in file sets dashboard page

- concrete/config/concrete.php
- concrete/config/db.xml
- concrete/controllers/dialog/page/add/compose.php
- concrete/controllers/panel/detail/page/composer.php
- concrete/controllers/panel/page/check_in.php
- concrete/elements/page_types/composer/form/output/buttons.php
- concrete/elements/pages/schedule.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Page/Collection/Version/EditResponse.php
- concrete/src/Page/Collection/Version/Version.php
- concrete/src/Page/Type/Type.php
- concrete/src/Updater/Migrations/Migrations/Version20180227035239.php
- concrete/src/Workflow/Request/ApprovePageRequest.php
- concrete/views/dialogs/page/add/compose.php
We currently have the ability to specify a date to start publishing a page – let's add the ability to specify an end date for publishing.
This is a first pass – there may be issues with this.
> Add publish end date functionality

- concrete/src/Http/ResponseFactory.php
>  Use the site context in ResponseFactory::controller 

- concrete/blocks/date_navigation/controller.php
> Avoid accessing undefined array indexes in date_navigation block controller

- concrete/blocks/image/controller.php
> Avoid accessing undefined array indexes in image block controller

- concrete/src/Foundation/Runtime/Run/DefaultRunner.php
While concrete5 is updating itself, let's show the "Site is in maintenance" page.
> Automatically set maintenance mode during core updates

- concrete/views/dialogs/page/add/compose.php
> Remove "schedule-page" dialog when scheduling page or on cancel

- concrete/controllers/dialog/block/delete.php
https://www.concrete5.org/community/forums/customizing_c5/suggestion-delete-box/
**Current:**
**Changes:**
> Add block type name to delete block modal message

- .appveyor.yml
- .travis.yml
- concrete/src/User/UserList.php
- tests/config/database.php
Let's see if it works (and let's hope that Trusty is more stable than Precise)
> TravisCI: switch from Precise to Trusty

- concrete/controllers/single_page/dashboard/reports/logs.php
- concrete/single_pages/dashboard/reports/logs.php
- concrete/src/Logging/LogEntry.php
Feature requested here : #6451
> Added the ability to delete individual Log entries

- concrete/single_pages/dashboard/pages/types/output.php
https://github.com/concrete5/concrete5/issues/6509
**Current:**
**Changes:**
>  Add text label and table row styling for default page templates 

- concrete/blocks/core_area_layout/controller.php
- concrete/src/Area/Layout/Column.php
Attempting to add cache checking to core area layout block.
> Add cache to core area layout block; Fix #2825

- concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- concrete/src/Localization/Locale/Service.php
These events (on_locale_added, on_locale_removed, on_locale_changed) could be really useful in concepts with multilingual Doctrine Entities or Express objects.
> Adding application events for changes in multilingual setup

- concrete/blocks/image_slider/form_setup_html.php
- concrete/blocks/image_slider/view.php
>  Allow image slider navigation option set to none

- concrete/src/File/Type/Type.php
Updated translation based on advice from @mlocati.
> Improve generic thumbnail icon alt attribute translation

- concrete/src/Tree/Type/Group.php
- concrete/src/User/Group/Group.php
- concrete/src/User/Group/GroupList.php
- concrete/src/User/Point/Action/ActionList.php
- concrete/src/User/Point/EntryList.php
- concrete/src/User/User.php
- concrete/src/User/UserInfo.php
- concrete/src/User/UserList.php
- tests/config/database.php
- tests/helpers/Database/ConcreteDatabaseTestCase.php
It's a reserved word in MySQL 8.
This addresses #6156, but in order to run concrete5 with MySQL 8 we require that DBAL gets updated with https://github.com/doctrine/dbal/pull/3128
> Quote "Groups" in MySQL queries

- concrete/src/Package/Package.php
When package dependencies are not satisfied, we have an $error array that contains both error identifiers and exception instances.
Decoding these exception instances with the getErrorText method of the Package class throws a PHP error, since we are trying to access an hash table item using the exception as the item key.
> Fix handling of package dependency errors

- concrete/js/build/core/layouts.js
Let's fix the remaining JavaScript error
> Fix js error in layouts.js

- concrete/src/Block/CacheSettings.php
> Avoid accessing an undefined array index in CacheSettings::get

- concrete/src/File/Importer.php
What about adding a method to the file importer to import uploaded files?
That way, we could import an uploaded file simply with:
```php
$importer = $app->make(Importer::class);
$fv = $importer->importUploadedFile($request->files->get('field_name'));
if (is_int($fv)) {
$errorToShow = $importer->getErrorMessage($fv);
}
```
> Add File\Importer::importUploadedFile

- concrete/src/Permission/Access/EditUserPropertiesUserAccess.php
> Avoid accessing undefined var in EditUserPropertiesUserAccess::getAccessListItems

- concrete/src/Application/Service/FileManager.php
> Fix bug in FileManager::file

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/files/thumbnails.php
- concrete/single_pages/dashboard/system/files/thumbnails.php
- concrete/src/Backup/ContentImporter/Importer/Routine/ImportFileImportantThumbnailTypesRoutine.php
- concrete/src/Entity/File/Image/Thumbnail/Type/Type.php
- concrete/src/Entity/File/Version.php
- concrete/src/File/Image/Thumbnail/Type/Type.php
- concrete/src/File/Image/Thumbnail/Type/Version.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Updater/Migrations/Migrations/Version20180531000000.php
- tests/tests/File/Image/Thumbnail/ThumbnailTypeTest.php
> Add "upscalingEnabled" field to thumbnail types

- concrete/elements/page_types/target_types/all.php
> Avoid accessing undefined vars in page_types/target_types/all

- concrete/elements/page_types/target_types/page_type.php
> Avoid accessing undefined vars in page_types/target_types/page_type

- concrete/elements/page_types/target_types/parent_page.php
> Avoid accessing undefined var in page_types/target_types/parent_page

- concrete/elements/page_types/form/base.php
> Avoid accessing undefined var in page_types/form/base

- concrete/controllers/backend/user_interface/page.php
> Avoid accessing an undefined var in user_interface/page backend controller

- concrete/controllers/backend/user_interface.php
> Throw a UserMessageException in UserInterface backend controller on access denied

- concrete/config/concrete.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Updater/Migrations/Migrations/Version20180604000000.php
> Allow upscaling of file_manager_listing thumbnail type

- concrete/config/app.php
- concrete/controllers/dialog/editor/settings/preview.php
- concrete/single_pages/dashboard/system/basics/editor.php
- concrete/src/Editor/EditorServiceProvider.php
- concrete/src/Editor/Plugin.php
- concrete/views/dialogs/editor/settings/preview.php
This is the implementation of what I [showcased in #6717](https://github.com/concrete5/concrete5/pull/6717#issuecomment-394358227).
> Add editor plugin descriptions and configuration preview

- concrete/elements/permission/detail.php
> Avoid accessing undefined array index in permission/detail element

- concrete/tools/permissions/access_entity.php
> Avoid accessing undefined array indexes in permissions/access_entity tool

- concrete/blocks/desktop_featured_theme/view.php
> Avoid accessing undefined var in desktop_featured_theme view

- concrete/blocks/desktop_featured_theme/controller.php
> Avoid accessing undefined array index in desktop_featured_theme controller

- concrete/blocks/desktop_featured_addon/view.php
> Avoid accessing undefined var in desktop_featured_addon view

- concrete/blocks/desktop_featured_addon/controller.php
> Avoid accessing undefined array index in desktop_featured_addon controller

- concrete/blocks/page_list/controller.php
- concrete/src/Search/ItemList/ItemList.php
> Bring back the setNameSpace() method in ItemList

- concrete/blocks/page_list/controller.php
> Avoid accessing undefined array index if page_list block controller

- concrete/controllers/single_page/dashboard/system/multilingual/copy.php
> Avoid accessing undefined array index in multilingual/copy dashboard page controller

- concrete/src/Multilingual/Page/Section/Processor/ReplaceBlockPageRelationsTask.php
> Avoid accessing undefined values in ReplaceBlockPageRelationsTask::execute

- concrete/views/dialogs/page/design.php
> Avoid accessing undefined var in page/design dialog controller

- concrete/attributes/page_selector/controller.php
- concrete/attributes/page_selector/form.php
- concrete/config/concrete.php
- concrete/config/install/base/attributes.xml
- concrete/src/Updater/Migrations/Migrations/Version20180609000000.php
@aembler I'm not sure for the migration, can you tell me if that would be good ?
Fix #5806
> Add a page selector attribute

- concrete/src/Form/Service/Validation.php
> Avoid accessing undefined array indexes in Validation form service

- concrete/src/Legacy/TaskPermission.php
> Mark TaskPermission::getByHandle static

- concrete/blocks/next_previous/controller.php
Equivalent date page get skipped as well as pages before/after an  inaccessible page.
> 6755: next_previous block skips pages

- concrete/authentication/concrete/controller.php
- concrete/config/concrete.php
- concrete/config/install/base/jobs.xml
- concrete/config/install/base/single_pages/dashboard.xml
- concrete/controllers/single_page/dashboard/system/registration/deactivation.php
- concrete/controllers/single_page/login.php
- concrete/jobs/deactivate_users.php
- concrete/single_pages/dashboard/system/registration/deactivation.php
- concrete/src/Updater/Migrations/Migrations/Version20180622192332.php
Add automatic user expiration: add dashboard page, add ability to custom inactive user messaging; add job that deactivates users based on login
> Automatic User Expiration

- concrete/jobs/generate_sitemap.php
- concrete/src/Console/Application.php
- concrete/src/Console/Command/GenerateSitemapCommand.php
- concrete/src/Page/Sitemap/DeprecatedPageListGenerator.php
- concrete/src/Page/Sitemap/Element/SitemapElement.php
- concrete/src/Page/Sitemap/Element/SitemapFooter.php
- concrete/src/Page/Sitemap/Element/SitemapHeader.php
- concrete/src/Page/Sitemap/Element/SitemapPage.php
- concrete/src/Page/Sitemap/Element/SitemapPageAlternativeLanguage.php
- concrete/src/Page/Sitemap/PageListGenerator.php
- concrete/src/Page/Sitemap/SitemapGenerator.php
- concrete/src/Page/Sitemap/SitemapWriter.php
The current generation of the sitemap.xml file is all done inside the `generate_sitemap` authomated job.
This has a few drawbacks:
1. it's not possible to specify the website URL if it's launched via CLI (with the `c5:job` command) and if the site does not have a canonical URL
2. the whole sitemap is always generated in memory and then written to a file (this is a problem for huge websites)
3. to specify a specific location of the generated file we have to change the concrete configuration (it would be nice to be able to do it easily via a CLI command)
4. the listeners of the events that allow customizing the sitemap have a hard life, since they have to work with a SimpleXml instance, so they have to process it to extract the relevant data
5. in future concrete5 will support multiple …
> Rewrite XML Sitemap generation

- concrete/elements/help/dialog/introduction.php
> Columns in introduction dialog with the same width

- concrete/single_pages/dashboard/system/registration/postlogin.php
> Update radio's labels with new descriptions in Login Destination page. #4098

- concrete/single_pages/dashboard/system/conversations/settings.php
> Modified the formatting of the attachments checkbox in the conversation settings page #4095

- concrete/config/site.php
- concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- concrete/single_pages/dashboard/system/multilingual/setup.php
- concrete/src/Http/ResponseFactory.php
- concrete/src/Multilingual/Service/Detector.php
> Add option to not create session cookies in multilingual sites

- concrete/elements/workflow/notifications.php
> Avoid accessing undefined var in workflow/notifications element

- concrete/src/Area/Layout/Column.php
> Avoid accessing undefined array indexes in Area\Layout\Column

- concrete/blocks/core_area_layout/form.php
> Avoid accessing undefined vars in core_area_layout/form

- concrete/views/image-editor/editor.php
> Avoid accessing undefined var in image-editor/editor

- concrete/controllers/backend/file.php
> Fix deleting file version

- concrete/controllers/single_page/dashboard/users/attributes.php
> Don't use an undefined var in users/attributes dashboard page controller

- concrete/elements/attribute/categories/user.php
> Avoid accessing undefined vars in attribute/categories/user element

- concrete/elements/attribute/key/form.php
> Avoid accessing undefined vars in attribute/key/form element

- concrete/single_pages/dashboard/system/permissions/maintenance.php
> Adding a label to the Maintenance Mode page  - #4102

- concrete/tools/pile_manager.php
> Avoid accessing undefined vars in pile_manager tool

- concrete/config/concrete.php
- concrete/controllers/dialog/page/add_block_list.php
- concrete/controllers/dialog/page/clipboard.php
- concrete/controllers/panel/add.php
- concrete/controllers/single_page/dashboard/blocks/types.php
- concrete/single_pages/dashboard/blocks/types/view.php
- concrete/src/Block/BlockType/BlockType.php
- concrete/src/Block/BlockType/Set.php
- concrete/src/Entity/Block/BlockType/BlockType.php
- concrete/views/dialogs/page/add_block_list.php
- concrete/views/panels/add.php
Fix #6438
(PS: the sort order is saved on the fly)
> Sort block types

- concrete/src/Sharing/SocialNetwork/ServiceList.php
Add ability to change defined social network icon in Core. Use array union instead of array merge.
With this change we can change social-icon from config file.
Example: facebook -> facebook-square.
> Add ability to change SocialNetwork icon

- concrete/src/Database/Connection/Connection.php
Even if #6779 greatly reduced the issue reported in #5440, I still have some exceptions in my logs (maybe because of concurrent sessions with different connections open).
This approach should actually fix #5440.
> Fix #5440 (again)

- concrete/blocks/google_map/controller.php
- concrete/blocks/google_map/form_setup_html.php
> Avoid long timeouts when checking the Google API Key

- concrete/controllers/backend/file.php
[From an idea](https://github.com/concrete5/concrete5/commit/23ce0690588992de6406791701251c7a380fa3c4#commitcomment-29667486) of @JeRoNZ
> Delete unused filesystem files and thumbnauls when a file version is removed

- concrete/src/Application/Application.php
- concrete/src/Url/Resolver/CanonicalUrlResolver.php
- tests/helpers/Url/Resolver/ResolverTestCase.php
- tests/tests/Routing/URLTest.php
> Use just one seo.trailing_slash configuration key

- .travis.yml
For some reason travis is failing to install dependencies with npm, and so I'm throwing a hail mary here and seeing if just switching to yarn is enough to fix tests.
> Try using yarn instead of npm to install our project dependencies to fix tests

- concrete/blocks/calendar/controller.php
- concrete/blocks/calendar_event/view.php
- concrete/blocks/event_list/view.php
- concrete/single_pages/dashboard/calendar/event_list.php
- concrete/src/Calendar/Event/Formatter/LinkFormatter.php
- concrete/src/Workflow/Request/UnapproveCalendarEventRequest.php
- concrete/views/dialogs/event/delete.php
- concrete/views/dialogs/event/duplicate.php
- concrete/views/dialogs/event/view.php
This makes it impossible to store XSS in the event name.
> Sanitize calendar event names

- concrete/src/File/Image/Thumbnail/Type/Version.php
> Thumbnail\Type\Version::shouldExistFor should always return a boolean

- concrete/controllers/single_page/dashboard/express/entries.php
- concrete/single_pages/dashboard/system/express/entities/attributes.php
- concrete/src/Page/Controller/DashboardExpressEntityPageController.php
- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
See screenshots
* ![view_cast_entries](https://user-images.githubusercontent.com/514294/44002700-eeda7ec6-9e81-11e8-8c1b-5d9b799cf332.png)
* ![add_cast](https://user-images.githubusercontent.com/514294/44002701-f2efb648-9e81-11e8-80cf-8777a4d1514a.png)
* ![edit_cast_entry](https://user-images.githubusercontent.com/514294/44002702-f4f7433e-9e81-11e8-8969-53b34df91ad7.png)
* ![attributes](https://user-images.githubusercontent.com/514294/44002703-f61fa68e-9e81-11e8-922f-fefd9ca07763.png)
> UI improvement: Show express entity name

- concrete/src/File/Service/File.php
See: https://github.com/concrete5/concrete5/issues/6986
> Silence tempnam to prevent Notice in Windows

- concrete/blocks/document_library/controller.php
- concrete/blocks/document_library/edit.php
- concrete/blocks/document_library/view.php
> Avoid accessing undefined vars & array indexes in document_library block

- concrete/blocks/express_entry_list/controller.php
Let's require pagination asset same as page list block
> Require pagination asset from express entry list block

- application/bootstrap/app.php
- concrete/src/Routing/Router.php
> Add back setThemeByRoute to Router

- concrete/src/Routing/Router.php
I just started to take a look at the new rooting system, and it seems to me that we still need what we did in #6823, otherwise all the routes get compiled again for every request.
> Faster routes resolution - Again

- concrete/blocks/express_entry_detail/controller.php
Let's avoid duplicate content penalties
> Add the label of current express entry as title segment

- concrete/single_pages/dashboard/conversations/messages.php
- concrete/tools/conversations/flag_message.php
Also added the token on flag message action
> Fixed inability to delete conversation messages from dashboard

- concrete/src/Express/Form/Renderer.php
PR:
- Remove unused import.
- Improve docblocks / code style.
Ref https://github.com/concrete5/concrete5/issues/4723
> Improve Express Form Renderer

- concrete/single_pages/dashboard/system/calendar/colors.php
count(): Parameter must be an array or an object that implements Countable
> Fix PHP 7.2 count error

- concrete/src/Page/Collection/Version/Version.php
> Fixing #6963 - scheduled drafts becoming live when new version scheduled

- concrete/src/Asset/Asset.php
- concrete/src/Routing/Router.php
- concrete/src/Routing/RouterInterface.php
- tests/tests/Block/BlockActionTest.php
We need to resolve routes both when resolving the current request and when retrieving the contents of dynamic assets.
What about adding a common method for a fast resolution of routes?
> Add getRouteByPath method to Router

- concrete/config/concrete.php
- concrete/config/install/base/single_pages/dashboard.xml
- concrete/controllers/single_page/dashboard/system/permissions/security.php
- concrete/single_pages/dashboard/system/permissions/security.php
- concrete/src/Updater/Migrations/Migrations/Version20180907091500.php
> Add dashboard page to control forced user logouts

- concrete/config/app.php
- concrete/routes/api/oauth2.php
- concrete/src/Api/ApiRouteList.php
- concrete/src/Api/ApiServiceProvider.php
- concrete/src/Api/Controller/V1/Site.php
- concrete/src/Api/Controller/V1/System.php
- concrete/src/Api/OAuth/Controller.php
- concrete/src/Api/OAuth/Validator/DefaultValidator.php
- concrete/src/Api/Transformer/System/InfoTransformer.php
Based on this discussion: https://github.com/concrete5/concrete5/pull/6946#issuecomment-413425284
> Rename API namespace to Api

- concrete/single_pages/dashboard/system/permissions/security.php
> missed t-function

- concrete/src/Page/Collection/Version/Version.php
> Add PHPDoc to Collection\Version

- concrete/src/Page/Collection/Collection.php
> Fix Page\Collection PHPDoc

- concrete/jobs/deactivate_users.php
> fix in t2-function

- concrete/single_pages/dashboard/reports/logs.php
> Moving Delete all channels button to header to remove ambiguity

- concrete/src/Page/Page.php
> Add PHPDoc to Page

- concrete/src/Api/OAuth/Controller.php
One less string to be translated ;)
> Use the standard token error message in OAuth controller

- concrete/src/Entity/Page/Feed.php
> Let RSS Feeds correctly handle site trees

- concrete/src/Cache/Page/PageCache.php
I added to this PR atomic commits, so that they can be reviewed one by one.
If it's not ok, I can close this PR and submit separated pull requests.
> Modernize PageCache abstract class

- concrete/blocks/social_links/controller.php
- concrete/blocks/social_links/form.php
- concrete/blocks/social_links/view.php
- concrete/single_pages/dashboard/system/basics/social.php
- concrete/src/Sharing/SocialNetwork/ServiceList.php
Allows for both appending to list and overriding existing items.
Adds additional checks to social links block and dashboard page to prevent block/page errors when a custom link type is removed from config while an entry still exists for it.
Run of php-cs-fixer against edited files.
> Corrects merging of built-in social links with custom defined list.

- composer.lock
- concrete/composer.json
- concrete/config/db.xml
- concrete/src/Database/Schema/Parser/DoctrineXml05.php
- concrete/src/Database/Schema/Parser/XmlParser.php
Tested with MySQL 5.7.20 and MariaDB 10.1.19.
Fix #6537
> Force MYISAM for PageSearchIndex only if required

- concrete/elements/dashboard/welcome.php
This PR hides the "Customize" button if the user does not have permission to edit the page content.
> Check for permissions on welcome page

- concrete/src/Editor/EditorServiceProvider.php
> Fix typo in list of CKEditor plugins ('applying')

- concrete/tools/page_types/composer/form/add_control.php
> Avoid accessing undefined array index in page_types/composer/form/add_control

- concrete/tools/files/importers/remote.php
> Check uploading remote file

- concrete/controllers/dialog/file/bulk/sets.php
> Release image resources when adding multiple files to sets

- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
Fixes #7219 
See further details from the issue.
> Fix express editing form validation issues

- concrete/src/Page/Search/IndexedSearch.php
> Fix an oversight in the page search indexing

- concrete/src/Html/Image.php
On Slack there was some confusion about what this class actually returns, and how it works. This PR should take away some of that confusion for future developers.
> Improve html image

- concrete/controllers/single_page/dashboard/system/registration/automated_logout.php
- concrete/single_pages/dashboard/system/registration/automated_logout.php
See https://github.com/concrete5/concrete5/pull/7227#discussion_r230656241
> Translate the "invalidate" confirmation string in automated logout page

- concrete/src/Sharing/SocialNetwork/ServiceList.php
Added social network 'vkontakte' or shortly 'vk'  (https;//vk.com).
In font awesome vk service has already has the icon: https://fontawesome.com/icons?d=gallery&q=vk
> Added one more popular social network: vk

- concrete/js/build/core/app/edit-mode/editmode.js
> Disable block proxy when editing inline blocks

- concrete/js/build/core/sitemap/sitemap.js
- concrete/src/Application/Service/Dashboard/Sitemap.php
- concrete/src/Application/UserInterface/Sitemap/StandardSitemapProvider.php
- concrete/tools/sitemap_overlay.php
- concrete/tools/sitemap_search_selector.php
> Fix sitemap selector overlay with pagination

- concrete/src/Updater/Migrations/Migrations/Version20181112211702.php
This should fix the failing tests
> Mark migration 20181112211702 as repeatable

- .travis.yml
- .travis/composer-deps.sh
- composer.json
- concrete/src/Application/Application.php
- concrete/src/Captcha/SecurimageController.php
- tests/tests/System/MutexTest.php
Let's see if phpdbg if faster than Xdebug...
> Switch from Xdebug to phpdbg for code coverage

- composer.json
- composer.lock
> Require concrete5/dependency-patches

- concrete/src/Attribute/Category/UserCategory.php
This is simple fix. See code changed.
> Add missing package parameter

- concrete/src/Database/DatabaseManagerORM.php
I also removed some imports, because they were unused.
> Docblocks and cleanup DatabaseManagerORM class

- concrete/controllers/single_page/dashboard/pages/types/add.php
And get rid of deprecated methods.
Ref. #4723
> Avoid accessing undefined array indexes in page/types/add::submit()

- concrete/src/Page/Cloner.php
> Fix creation of block aliases

- concrete/config/concrete.php
- concrete/config/install/base/single_pages/dashboard.xml
- concrete/controllers/single_page/dashboard/system/files/export_options.php
- concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php
- concrete/controllers/single_page/dashboard/users/search.php
- concrete/single_pages/dashboard/system/files/export_options.php
- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
- concrete/src/Updater/Migrations/Migrations/Version20181207085100.php
> Add an option to include the BOM in exported CSV

- concrete/src/Csv/WriterFactory.php
There's a missing `use SplFileObject` in `Csv\WriterFactory`.
And let's add some PHPDoc to it.
> Fix Csv\WriterFactory::createFromFileObject(), add PHPDoc

- concrete/src/Error/ErrorList/Error/AbstractError.php
- concrete/src/Error/ErrorList/Error/Error.php
- concrete/src/Error/ErrorList/Error/ErrorInterface.php
- concrete/src/Error/ErrorList/Error/ExceptionError.php
- concrete/src/Error/ErrorList/Error/FieldNotPresentError.php
- concrete/src/Error/ErrorList/Error/HtmlAwareErrorInterface.php
- concrete/src/Error/ErrorList/Formatter/StandardFormatter.php
- concrete/src/Package/Dependency/DependencyException.php
- concrete/src/Package/Dependency/IncompatiblePackagesException.php
- concrete/src/Package/Dependency/MissingRequiredPackageException.php
- concrete/src/Package/Dependency/RequiredPackageException.php
- concrete/src/Package/Dependency/VersionMismatchException.php
- tests/tests/Error/ErrorTest.php
- tests/tests/Form/Service/ValidationTest.php
> [8.4] HTML-escape error messages

- concrete/src/Cache/Page/RedisPageCache.php
Fixes this error:
> ReflectionException thrown with message "Class facade does not exist"
@deek87 ping ;)
> Redis - Page Cache, fix initialization with config values

- concrete/authentication/google/controller.php
- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/controllers/single_page/dashboard/system/environment/proxy.php
- concrete/controllers/single_page/login.php
- concrete/single_pages/dashboard/system/environment/logging.php
- concrete/src/Antispam/Service.php
- concrete/src/Application/Application.php
- concrete/src/Authentication/AuthenticationTypeController.php
- concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
- concrete/src/Authentication/Type/OAuth/OAuth2/GenericOauth2TypeController.php
- concrete/src/Authentication/Type/OAuth/ServiceProvider.php
- concrete/src/Logging/Channels.php
- concrete/src/Logging/Configuration/ConfigurationFactory.php
- concrete/src/Logging/Configuration/SimpleConfiguration.php
- concrete/src/Logging/Configuration/SimpleDatabaseConfiguration.php
- concrete/src/Logging/Configuration/SimpleFileConfiguration.php
- concrete/src/Logging/LoggerAwareInterface.php
- concrete/src/Logging/LoggerAwareTrait.php
- concrete/src/Logging/LoggingServiceProvider.php
- concrete/src/Page/Page.php
- concrete/src/User/Point/Action/Action.php
- concrete/src/User/PrivateMessage/Limit.php
- concrete/src/Validation/CSRF/Token.php
- tests/tests/Logging/LogTest.php
* Refactoring all log statements in the core
* adding a couple new log statements
* adding ability to log files in the simple configuration model
> Logging Improvements v2.0

- concrete/blocks/express_form/controller.php
- concrete/blocks/express_form/db.xml
- concrete/blocks/express_form/form.php
- concrete/blocks/express_form/view.php
- concrete/mail/block_express_form_submission.php
- concrete/src/Attribute/Controller.php
- concrete/src/Express/Entry/EntryManagerInterface.php
- concrete/src/Express/Entry/Formatter/LabelFormatter.php
- concrete/src/Express/Entry/Listener.php
- concrete/src/Express/Entry/Manager.php
- concrete/src/Express/Entry/Notifier/AbstractNotifier.php
- concrete/src/Express/Entry/Notifier/Notification/AbstractFormBlockSubmissionNotification.php
- concrete/src/Express/Entry/Notifier/Notification/EntrySubject.php
- concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
- concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionNotification.php
- concrete/src/Express/Entry/Notifier/NotificationInterface.php
- concrete/src/Express/Entry/Notifier/NotificationList.php
- concrete/src/Express/Entry/Notifier/NotificationListInterface.php
- concrete/src/Express/Entry/Notifier/NotificationProviderInterface.php
- concrete/src/Express/Entry/Notifier/NotifierInterface.php
- concrete/src/Express/Entry/Notifier/StandardNotifier.php
- concrete/src/Express/Entry/Search/Result/Item.php
- concrete/src/Express/Entry/Search/Result/Result.php
- concrete/src/Express/Form/Control/Type/AssociationType.php
- concrete/src/Updater/Migrations/Migrations/Version20181204170355.php
Express Forms - Make storing submissions optional
> Express Forms - Make storing submissions optional

- concrete/elements/page_types/target_types/form/page_type.php
This PR fixes issue #6962 - if you have draft pages from 5.7 then try to update to 8.4.x and it throws an error if you try to edit these pages. More info in #6962
> Fixes issue #6962

- concrete/bootstrap/start.php
This pull request make the app variable comment block consistent.
> Consistent comment block

- concrete/blocks/youtube/controller.php
- concrete/blocks/youtube/db.xml
- concrete/blocks/youtube/form_setup_html.php
- concrete/blocks/youtube/view.php
- concrete/src/Updater/Migrations/Migrations/Version20181213000000.php
As there isn't any news from the author of this [PR](https://github.com/concrete5/concrete5/pull/7328) 
we intented to complete the work to get faster approve.
> Youtube 'nocookie' feature

- concrete/src/Page/Type/Composer/Control/BlockControl.php
- concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php
- concrete/src/Page/Type/Validator/StandardValidator.php
Validate all controls on submission; ignore field not present errors if the field itself is not required.
> Fix #6191; supersdes #7300

- concrete/src/Logging/Channels.php
- concrete/src/Logging/Handler/DatabaseHandler.php
- concrete/src/Logging/Logger.php
> Backward compatibility work in Logger

- tests/tests/Localization/Service/DateTest.php
This is a new test case for date helper.
This test will fail due to the bug #7446
> Add a test for date helper

- concrete/controllers/single_page/dashboard/system/basics/multilingual.php
- concrete/controllers/single_page/dashboard/system/multilingual/setup.php
- concrete/single_pages/dashboard/system/basics/multilingual/view.php
- concrete/single_pages/dashboard/system/multilingual/setup.php
> Link "Languages" and "Multilingual Setup" dashboard pages

- concrete/routes/actions/blocks.php
- concrete/routes/actions/pages.php
- concrete/routes/actions/users.php
- concrete/routes/assets_localization.php
- concrete/routes/dialogs/areas.php
- concrete/routes/dialogs/blocks.php
- concrete/routes/dialogs/conversations.php
- concrete/routes/dialogs/groups.php
- concrete/routes/dialogs/page_types.php
- concrete/routes/dialogs/pages.php
- concrete/routes/dialogs/users.php
- concrete/routes/panels.php
> Improve comments in the routes directory

- concrete/src/Page/Collection/Version/Version.php
> Fix error in Collection\Version::isApprovedNow()

- concrete/blocks/express_form/form.php
- concrete/src/Application/Service/Urls.php
Fix error in edit mode with new asset updates; fix duplicate submit button label in express form
> Hotfix fix asset error and submit label

- concrete/views/dialogs/page/add_block.php
Fix bug introduced in https://github.com/concrete5/concrete5/pull/7479
> Fix broken add block interface

- concrete/single_pages/dashboard/pages/templates/view.php
> Avoid accessing undefined $template in templates view

- concrete/elements/attribute/editable_set_list.php
> Avoid accessing undefined $permissionsArguments in editable_set_list element

- concrete/elements/attribute/editable_attribute.php
> Avoid accessing undefined $permissionsArguments in editable_attribute element

- concrete/src/Page/Exporter.php
Found a very minor misspelling getCollectionPUblic(); :)
> Fix misspell getCollectionPUblic()

- concrete/single_pages/account/messages.php
> Avoid accessing undefined when composing a private message

- concrete/src/Form/Service/Validation.php
> Avoid accessing undefined property in Form\Service\Validation::test

- concrete/src/Page/Page.php
> Avoid accessing undefined array index in Page::update()

- concrete/views/oauth/consent/simple.php
> Improve translation of oauth request authorization

- concrete/attributes/text/type_form.php
> Avoid accessing undefined var in attributes/text/type_form

- concrete/src/User/Search/ColumnSet/ColumnSet.php
> Fix deserializing deleted attribute key

- concrete/src/Page/Collection/Version/Version.php
> Fix case mismatch of getCollectionID on Collection Version class

- concrete/controllers/single_page/dashboard/users/search.php
- concrete/src/Session/SessionValidator.php
- concrete/src/Session/Storage/LoggedStorage.php
- tests/tests/Session/SessionValidatorTest.php
Up the value of certain log writes (they are more interesting than debug); log sudo actions.
> Logging Tweaks

- concrete/src/Form/Service/Form.php
This just fixes the issue #7591 and adds a h to another option
> Fix PR #7591 and H() to option fields

- concrete/js/build/core/app/dialog.js
> Add Block to Stack: hide menu when adding contents

- concrete/src/Page/Stack/Stack.php
This is [required by page cloner](https://github.com/concrete5/concrete5/blob/b5648881c19529753a5f81e15fece3313374931e/concrete/src/Page/Cloner.php#L163).
> Make Stack::getMultilingualSectionID() public

- concrete/src/Updater/Migrations/Migrations/Version20190225184524.php
> Fix updating OAuth\AccessToken entity

- concrete/src/Express/Form/Control/SaveHandler/ManyAssociationSaveHandler.php
This line shouldn't be there, should it?
> Remvove debug code in ManyAssociationSaveHandler

- concrete/single_pages/dashboard/system/basics/social.php
> Avoid accessing undefined var in social dashboard page

- concrete/config/concrete.php
What about adding some docs about how users can add new Social links?
> Add some comments about how to add/customize Social links

- concrete/src/User/User.php
This PR fixes issue #7635 and also correctly gets groups for custom request users.
> #7635 - Fixing issue with custom request user not having any groups

- concrete/src/Database/CharacterSetCollation/Manager.php
> Fix Exception already used in CharsetCollation\Manager

- concrete/elements/page_types/composer/controls/core_page_property/publish_target.php
> Avoid accessing undefined var in publish_target

- concrete/controllers/single_page/dashboard/reports/logs.php
- concrete/single_pages/dashboard/reports/logs.php
- concrete/src/Logging/LogList.php
Follow up https://github.com/concrete5/concrete5/pull/5984
This PR allows to filter log by date from and date to.
> [Feature] Filtering log with date from and to

- concrete/bootstrap/process.php
> Avoid accessing undefined vars/array keys in process::add_stack

- concrete/js/build/core/app/progressive-operations.js
- concrete/js/build/core/sitemap/sitemap.js
Reported at https://concrete5.slack.com/archives/C2H7N3DC4/p1553067271015900
> Fix resuming copy language tree operation

- concrete/src/Package/StartingPointPackage.php
- concrete/src/Page/Page.php
- concrete/src/Site/Service.php
> Fix installation with HOME_CID not 1

- concrete/src/Install/Preconditions/DatabaseCharsetCollation.php
> Simplify the warning when the database does not fully support utf8mb4

- README.md
[Waffle.io is going away](https://waffle.io/closing-its-doors) :(
> Remove waffle.io throughput activity chart from readme

- concrete/src/User/Login/LoginService.php
This change addresses the login issues discussed in #7686.  The credit goes to @debaugh for isolating the spot for the fix.
> Fix Login Failure After Manual 8.5.1 Migration

- .appveyor/configure.ps1
This will hopefully fix this AppVeyor error message:
```
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.
Please try again later.
```
> Update PowerShellGet PowerShell module

- concrete/js/build/core/app/search/base.js
> Use CTRL to toggle selection in search list

- concrete/controllers/install.php
> Installation: display only error message when connection fails

- concrete/elements/page_controls_footer.php
version 8.5.0 & 8.5.1
1. Open [ Page Settings (Page panel) > Versions ]
2. Click Live Version
3. Click Unapproved in the menu
Result... 404 Not Found.
> Add Unapproved Routing

- concrete/blocks/document_library/controller.php
This might be helpful for Databases that have ONLY_FULL_GROUP_BY activated.
> Fix for #7311 and #7683

- concrete/config/app.php
- concrete/src/Form/Service/Widget/GroupSelector.php
- concrete/src/Permission/Access/Entity/GroupEntity.php
- concrete/src/User/Group/Command/AddGroupCommand.php
- concrete/src/User/Group/Command/AddGroupCommandHandler.php
- concrete/src/User/Group/Command/AddGroupCommandValidator.php
- concrete/src/User/Group/Command/DeleteGroupCommand.php
- concrete/src/User/Group/Command/DeleteGroupCommandHandler.php
- concrete/src/User/Group/Command/Traits/ExistingGroupTrait.php
- concrete/src/User/Group/Command/Traits/GroupDetailsTrait.php
- concrete/src/User/Group/Group.php
- concrete/src/User/Group/GroupRepository.php
> Refactor groups somewhat; add commands for group operations

- concrete/blocks/survey/controller.php
- concrete/blocks/survey/db.xml
- concrete/blocks/survey/edit.php
- concrete/blocks/survey/view.php
- concrete/config/concrete.php
- concrete/src/Updater/Migrations/Migrations/Version20190513164028.php
Adding show/hide results and custom thank you message in the block settings.
> Implementing show/hide survey results with custom message

- concrete/src/Permission/Response/PageResponse.php
See https://github.com/concrete5/concrete5/pull/7809/files#diff-d9b83c4570b958642a9357197827af40R146
> Define $app in PageResponse::canViewToolbar()

- concrete/attributes/select/type_form.php
> Avoid accessing undefined var in attributes/select/type_form

- concrete/js/build/core/file-manager/menu.js
- concrete/js/build/core/file-manager/selector.js
- concrete/src/File/Menu.php
This addresses the issue described in #6955 (but not https://github.com/concrete5/concrete5/issues/6955#issuecomment-428983124).
Screenshot:
> Add "Choose New File" to file picker menu item

- concrete/src/Updater/Migrations/Migrations/Version20181006212300.php
This completes the changes in #3301
Fix #7774
> Fix default date/time values of DB fields

- concrete/js/build/core/file-manager/search.js
> Hide popover when selecting images

- concrete/tools/page_types/composer/form/add_control.php
https://github.com/concrete5/concrete5/issues/7688
> Search attributes on compose form

- concrete/controllers/single_page/dashboard/reports/logs.php
- concrete/single_pages/dashboard/reports/logs.php
What about adding a link to `/dashboard/system/environment/logging` in the `/dashboard/reports/logs` page?
Previews:
---
> Add link to log settings page in the log viewer page

- concrete/js/build/core/app/search/base.js
- concrete/js/build/core/app/search/preset-selector.js
Currently in the core no search presets can be selected at all. Express/User Search/etc
This is because we try to call ajaxUpdate on the wrong object, Ive switched over the event system to better handle this.
> Fixing search presets not actually being submitted.

- concrete/attributes/user_selector/controller.php
UserInfo does not have a getByUserID() method, it should be getByID when using UserInfo.
Not sure how this was missed...
> User selector display value is broken, because UserInfo does not have getByUserID method

- concrete/src/Url/Resolver/CallableUrlResolver.php
- concrete/src/Url/Resolver/CanonicalUrlResolver.php
- concrete/src/Url/Resolver/Manager/ResolverManager.php
- concrete/src/Url/Resolver/Manager/ResolverManagerInterface.php
- concrete/src/Url/Resolver/PageUrlResolver.php
- concrete/src/Url/Resolver/PathUrlResolver.php
- concrete/src/Url/Resolver/RouteUrlResolver.php
- concrete/src/Url/Resolver/RouterUrlResolver.php
- concrete/src/Url/Resolver/UrlResolverInterface.php
- concrete/src/Url/Resolver/UserInfoUrlResolver.php
See every commit for a detailed list of changes.
The actual code changes are b4303ae4116a6797defc1ddaf496eef85cf9535a, 2f8abc36ebc652854a910b78c4fbe23328ef8c71, a7b253689014fb7f6c5fbb9be49c26ef0f40e17b, and ee7dad9a71129a111ddd3c244b7622b5856430be
> Fix URL resolving stuff

- concrete/js/build/core/file-manager/menu.js
- concrete/js/build/core/file-manager/search.js
- concrete/js/components/avatar.bundle.js
- concrete/js/vue.js
- concrete/src/File/Menu.php
Fixes #7828 
Fixes error where Choose File is showing up all the time.
Fixes download file not working in the bulk-style dropdown menu.
> Fix #7828; Fix misc. funky behavior in file manager

- concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
> Avoid Yoda Style on condition

- concrete/src/Attribute/Controller.php
> Avoid accessing an undefined array index in Attribute\Controller

- concrete/src/Workflow/Type.php
> Fix Workflow\Type::getByHandle()

- concrete/src/Workflow/Type.php
- concrete/src/Workflow/Workflow.php
- tests/tests/Workflow/WorkflowTest.php
- tests/tests/Workflow/WorkflowTypeTest.php
We have an error similar to the one fixed by #7928 in Workflow\Type::getListByPackage().
Let's fix it, and let's add/fix phpdoc and reorder the methods.
> Workflow\Type: fix getListByPackage, fix phpdoc, reorder methods

- concrete/blocks/core_area_layout/form.php
> Avoid accessing undefined var in core_area_layout/form.php

- .travis/check-php-coding-style.sh
This bash line is wrong (it always return true)
> Fix checking TRAVIS_PULL_REQUEST environment variable

- concrete/js/build/core/app/edit-mode/block.js
- concrete/js/build/core/app/edit-mode/editmode.js
This completes the "third issue" described at #7879
> Allow reverting block moves when arrangement fails

- concrete/controllers/frontend/assets_localization.php
- concrete/single_pages/dashboard/system/seo/bulk.php
Small Spelling change Occured to Occurred.
> Spelling Change Occured to Occurred

- concrete/js/build/core/app/in-context-menu.js
Delegated event handler approach.
> Fix for #7920

- concrete/js/build/core/app/in-context-menu.js
> Fully reverting #7960

- concrete/blocks/youtube/view.php
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> Fix autoplay not starting

- concrete/src/Cache/Page/PageCache.php
- tests/tests/Cache/Page/PageCacheTest.php
> Fix full page cache collisions

- build/tasks/git-skipper.js
We can't tell git to assume as changed/unchanged files that are not tracked: we need to filter them out.
This PR fixes [this TravisCI errors](https://travis-ci.org/concrete5/concrete5/jobs/557526264#L718) that prevented the automatic generation of the JS/CSS assets.
> Fix the gitskip grunt tasks

- concrete/css/build/vendor/jquery-ui/jquery-ui.less
Upgrading JQuery-UI to 1.12.1
#7812
> Upgrading JqueryUI to 1.12.1

- concrete/bootstrap/helpers.php
Makes it easier tot get the application instance and resolves types. 
This is also done by Laravel.
[Laravel documentation](https://laravel.com/docs/5.8/helpers#method-app).
[Source code](https://github.com/laravel-zero/foundation/blob/5.8/src/Illuminate/Foundation/helpers.php#L107-L123)
> A helper function to get the application instance

- concrete/bootstrap/helpers.php
> add array type hint for $parameters in the app function

- concrete/src/Multilingual/Page/Section/Section.php
This pull request should fix the issue #8013
> Fix multilingual page relation on copy

- concrete/src/Cache/Driver/RedisStashDriver.php
Password set in config is not sent Redis connection process
> Redis password should be kept in server data

- concrete/src/Block/Block.php
Fix this warning when running concrete5 on PHP 7.4
> Block: Fix "Trying to access array offset on value of type bool"

- concrete/controllers/single_page/dashboard/blocks/stacks.php
- tests/tests/System/NameAlreadyInUseTest.php
This is very useful to avoid problems like the one fixed in #7673
> Test class name already in use

- concrete/src/Application/UserInterface/Menu/Item/Controller.php
This is an alternative to https://github.com/concrete5/concrete5/pull/8038 (here I implemented 1. described there).
Ref. #4723
> Fix initialization of menu item controllers v2

- concrete/blocks/form/form_setup_html.php
- concrete/blocks/page_list/page_list_form.php
- concrete/elements/pages/schedule.php
The correct case of `Loader` is `Loader`, not `loader`
> Fix casing of Loader

- build/package.json
This *should* fix [this issue](https://travis-ci.org/concrete5/concrete5/jobs/573893511#L728).
> Fix building of JS/CSS assets

- tests/tests/Routing/URLTest.php
- tests/tests/Url/Resolver/CanonicalUrlResolverTest.php
What about fixing those tests, which are marked as incomplete since 5eb45e11b186a7399da01f8589a3ef7a063e24f6 (that is, 3 years ago :wink:)
> Fix the canonical URL tests

- .appveyor/configure.ps1
- .travis/composer-deps.sh
This should speedup fetching composer packages
> Add hirak/prestissimo composer global package

- concrete/single_pages/dashboard/system/multilingual/page_report.php
> Fix the layout of the search fields in "Page Report" page

- concrete/elements/attribute/editable_attribute.php
> Open attribute editing popup to bottom instead of top

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/pages/feeds.php
- concrete/single_pages/dashboard/pages/feeds.php
- concrete/src/Entity/Page/Feed.php
- concrete/src/Updater/Migrations/Migrations/Version20190817000000.php
> Make it configurable whether or not to ignore page permissions for RSS feeds

- concrete/authentication/community/controller.php
- concrete/authentication/external_concrete5/controller.php
- concrete/authentication/facebook/controller.php
- concrete/authentication/google/controller.php
- concrete/authentication/twitter/controller.php
> Remove Guest from "Group to enter on registration" options

- concrete/src/File/StorageLocation/StorageLocationFactory.php
> StorageLocationFactory::fetchByName should return an instance

- concrete/single_pages/dashboard/blocks/stacks/view.php
- concrete/src/Permission/Assignment/AreaAssignment.php
- concrete/src/Permission/Assignment/StackAssignment.php
- concrete/src/Permission/Key/AddBlockToAreaAreaKey.php
This is an alternative to #7989 accordingly to https://github.com/concrete5/concrete5/pull/7989#pullrequestreview-267894968
Fix #7929
> Fix permission checks of global areas v2

- concrete/blocks/youtube/controller.php
- concrete/blocks/youtube/db.xml
- concrete/blocks/youtube/form_setup_html.php
- concrete/blocks/youtube/view.php
- concrete/src/Updater/Migrations/Migrations/Version20190826000000.php
This option forces the captions to be shown by default for the YouTube iframe embed.
More info:
https://developers.google.com/youtube/player_parameters#cc_load_policy
https://developers.google.com/youtube/player_parameters#cc_lang_pref
> Possibility to show captions by default for the YouTube block

- .appveyor/configure.ps1
Let's fix [this ugly AppVeyor warning](https://ci.appveyor.com/project/concrete5/concrete5/builds/27549764/job/add2b3h3ew6ry1cf#L16).
> Fix AppVeyor warning

- composer.lock
See https://github.com/mlocati/ip-lib/releases
> Update IPLib from version 1.6.0 to version 1.9.0

- concrete/blocks/event_list/form.php
https://github.com/concrete5/concrete5/issues/8104
> Added translations and tidied up the template a bit

- concrete/controllers/dialog/block/aliasing.php
> SetupOnChild: Fix showing empty error message when a problem occur

- concrete/src/Console/Command/InstallThemeCommand.php
- concrete/src/Console/ServiceProvider.php
- tests/tests/Console/ServiceProviderTest.php
This adds the command ```c5:install-theme <theme-handle> (optional -a flag)``` to the CLI commands.
The -a will activate the theme as well.
> CLI install Theme command

- build/tasks/build-release/download.js
- concrete/config/concrete.php
> Update develop to 8.5.2 as its version number.

- concrete/src/Cache/Driver/RedisStashDriver.php
- concrete/src/Session/SessionFactory.php
This PR allows us to send a password to Redis Arrays correctly (on both session and cache)
https://github.com/concrete5/concrete5/compare/develop...deek87:hotfix/redis-password?expand=1#diff-90f4c72074b5cfab443abfcc624329ffR129-R131 - RedisArray only accepts one password
Removes unused code from #8017
Fix ttl not being used in RedisArray correctly
> Fixing not sending password to RedisArray in session and cache drivers

- concrete/blocks/core_area_layout/templates/parallax/view.php
- concrete/blocks/core_area_layout/view.php
- concrete/src/Area/Layout/Preset/Formatter/ThemeFormatter.php
This fixes #6799 by allowing the container to be nested elements in area layouts.
> Allow nested containers in area layout

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/single_pages/dashboard/system/environment/logging.php
- concrete/src/Api/ApiRouteList.php
- concrete/src/Http/Middleware/ApiLoggerMiddleware.php
- concrete/src/Routing/RouteGroupBuilder.php
Add an ApiLoggerMiddleware. Can be enabled/disabled in the config file or over the "Logging Settings" page. Middleware is only logging, if the "Core Logging Level"
is set to "Debug"
Related #8225
> Add ApiLoggerMiddleware

- concrete/tools/conversations/update_message.php
check for an array before counting
fixes #8233
> php 7.2 fix for updating a conversation message

- concrete/src/Editor/CkeditorEditor.php
This helps fixing HTML problems because of manual input.
Fix #8276
> CKEditor: turn off 'Edit Source' before submit

- composer.lock
- concrete/composer.json
[Changelog](https://github.com/concrete5-community/translation-library/compare/1.5.12...1.5.13)
> Update concrete5 Translation Library

- concrete/blocks/search/controller.php
> Avoid accessing undefined array index allowUserOptions in Search block controller

- concrete/src/Html/Image.php
> Avoid accessing undefined var in Html\Image constructor

- concrete/src/Permission/Access/AddBlockBlockTypeAccess.php
> Avoid accessing undefined array indexes in AddBlockBlockTypeAccess::save()

- concrete/controllers/install.php
> Fix suggested values for canonical URLs

- concrete/src/Editor/LinkAbstractor.php
> Fix rendering picture tag with numeric attributes

- concrete/src/User/User.php
This PR modifies the `User::recordLogin` to add a log entry every time a user logs in.
> Add a log entry when users successfully log in

- concrete/authentication/facebook/controller.php
- concrete/authentication/google/controller.php
- concrete/authentication/twitter/controller.php
- concrete/src/Authentication/Type/OAuth/BindingService.php
- concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
- tests/tests/Authentication/OAuth/BindingServiceTest.php
Instead of having controllers access this table directly let's have a service manage interactions and add logging to that service.
> Add oauth binding service that manages logging when bindings change

- concrete/attributes/user_group/controller.php
Not every user is a customer :wink:
> Use "user" instead of "customer" in user_group attribute

- concrete/src/Page/Page.php
What about adding a unique class to each page via `getPageWrapperClass()` method?
> add a unique class to each page

- concrete/config/install/base/single_pages/dashboard.xml
- concrete/src/Updater/Migrations/Migrations/Version20141024000000.php
Some leftovers after https://github.com/concrete5/concrete5/pull/7397/commits/80506962a2f2793b6562b741381c6cce37758516
> Remove query_log leftovers

- concrete/blocks/core_conversation/form.php
- concrete/config/concrete.php
- concrete/config/conversations.php
- concrete/controllers/single_page/dashboard/system/conversations/settings.php
- concrete/controllers/single_page/dashboard/system/files/filetypes.php
- concrete/single_pages/dashboard/system/conversations/settings.php
- concrete/single_pages/dashboard/system/files/filetypes.php
- concrete/src/File/Service/Application.php
- concrete/src/File/ValidationService.php
- concrete/tools/conversations/add_file.php
> Introduce a black list of file extensions

- concrete/controllers/frontend/assets_localization.php
This PR fixes the issue described in #8308.
> Fix #8308 - Chunked file uploads generate multiple files in the backend

- concrete/src/User/User.php
> Fixing issue #7222

- .travis.yml
- phpunit.xml
- tests/assets/Docker/run-install.sh
- tests/assets/Docker/run-update.sh
- tests/helpers/DockerTrait.php
- tests/tests/File/ExecutableFilesTest.php
- tests/tests/Update/InstallUpdateTest.php
What about adding a couple of tests to check that concrete5 can actually install and update a previously installed concrete5?
> Test installing/updating concrete5

- composer.lock
See the [changelog](https://github.com/punic/punic/blob/master/CHANGELOG.md).
> Update Punic from version 3.4.0 to version 3.5.1

- concrete/elements/attribute/key/form.php
This is the same as #8419 just with try/catch specific error handling.
> Catch and handle file doesn't exist error for category elements

- concrete/src/Block/Block.php
previously blocks would be added to all pages of the PageType
This PR would close #8417
> only queue blocks for PageType / PageTemplate combo

- concrete/src/Updater/Update.php
During the update process, in order to avoid timeout problems (mainly when updating via web), in #6482 we introduced the concept of "long running" migrations (that is, migrations that may take a lot of time).
If a migration is marked as "long running" (that is, it implements the `LongRunningMigrationInterface` interface), we try to increase the PHP execution time (with `set_time_limit`), or ask the web client to reload the page (so that the upgrade process will start over, from the next migration).
But in #6482 I did a mistake: the result of `getMigrationsToExecute` is an array of `Doctrine\DBAL\Migrations\Version` instances, whereas the actual migrations are sub-classes of `Doctrine\DBAL\Migrations\AbstractMigration`.
So, we have to check that the actual migrations implements …
> Fix handling of Migrations vs Migration Versions

- concrete/src/Backup/ContentImporter/Importer/Routine/ImportExpressEntitiesRoutine.php
> Correctly set express entity package reference during import.

- .travis/rebuild-assets.sh
- .travis/setup-build.sh
This *should* fix rebuilding assets in the v9 branch.
> Automatically rebuild assets for v9

- concrete/controllers/frontend/assets_localization.php
> [v9] Fix #8308 non-chunked file uploads directly dropped to dropzones

- concrete/controllers/element/navigation/dashboard_menu.php
- concrete/controllers/element/navigation/dashboard_mobile_menu.php
> Show aliased pages in the dashboard navigation

- concrete/src/Database/ForeignKeyFixer.php
> Fix invalid string placeholders in ForeignKeyFixer

- concrete/src/Console/Command/PhpCodingStyleCommand.php
Pretty straight forward change
> Fix misspelling of unable

- concrete/src/Page/View/PageView.php
https://github.com/concrete5/concrete5/issues/8111
> Added an exception in case there's no template file to render

- concrete/src/Entity/Board/DataSource/DataSource.php
- concrete/src/Entity/Board/SlotTemplate.php
- concrete/src/Entity/Board/Template.php
- concrete/src/Entity/Page/Container.php
- concrete/src/Entity/Summary/Category.php
- concrete/src/Entity/Summary/Field.php
- concrete/src/Entity/Summary/Template.php
Related pull request for the translation library: https://github.com/concrete5-community/translation-library/pull/7
> [v9] Add localization support for new entities

- concrete/js/build/core/country-data-link.js
This fixes the first issue reported at https://github.com/concrete5/concrete5/pull/8539
> [v8] Fix initializing country/province link

- concrete/src/Database/Schema/Parser/Axmls.php
Our db.xml doesn't support all of what's available in Doctrine, let's add JSON.
> Add support for json columns in db.xml

- build/assets/themes/dashboard/scss/main.scss
See https://github.com/concrete5/concrete5/issues/8564#issuecomment-620882456
> Let ccm-dashboard-form-actions-wrapper elements have a white background

- concrete/controllers/single_page/dashboard/system/optimization.php
- concrete/controllers/single_page/dashboard/system/optimization/cache.php
- concrete/controllers/single_page/dashboard/system/optimization/clearcache.php
- concrete/controllers/single_page/dashboard/system/optimization/jobs.php
- concrete/single_pages/dashboard/system/optimization/cache.php
- concrete/single_pages/dashboard/system/optimization/clearcache.php
- concrete/single_pages/dashboard/system/optimization/jobs.php
- concrete/single_pages/dashboard/system/optimization/view.php
Fix https://github.com/concrete5/concrete5/issues/8564
I also fixed a few things vs version 8, see https://youtu.be/o_Bzq10iztQ for a short (Real Spaghetti English™️) description.
> Clean up Dashboard > System and Settings > Optimization section

- concrete/blocks/express_form/controller.php
Adds an additional check before entity deletion as described here:
https://github.com/concrete5/concrete5/issues/8588#issuecomment-621486936
> Fix for #8588

- concrete/controllers/panel/detail/page/location.php
> Additional check before clearPagePaths()

- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/src/Controller/AbstractController.php
Saving logging settings was a little bit jumbled and had a few edge cases that were hard to see at a glance. This PR reorganizes stuff to have default values and validate in more cases.
Fixes H1-841947
> Reorganize logging settings saving routine

- concrete/controllers/backend/file/thumbnailer.php
> Avoid accessing undefined array index in thumbnailer::generate()

- concrete/elements/page_controls_footer.php
> Avoid accessing undefined var in page_controls_footer

- concrete/src/Page/Sitemap/SitemapGenerator.php
Similar to #8457 but for version 8
> [V8] Fix issue with sitemap generation in multilingual sites

- concrete/single_pages/login.php
> Avoid accessing undefined var in login single page

- concrete/blocks/desktop_latest_form/controller.php
> Avoid accessing element of non array variable

- concrete/src/Search/Column/Column.php
Let's make sure we have a valid sort direction in our Search Column class
This PR resolves H1 #876800
> Fix error caused by invalid sort direction

- concrete/blocks/youtube/view.php
Before this PR we were building urls in a funky way. Let's use the League url wrapper to manage building the youtube embed url instead.
This resolves H1 #8651 869752
> Build youtube embed url with the league url class

- concrete/controllers/single_page/dashboard/system/environment/database_charset.php
- concrete/controllers/single_page/dashboard/system/environment/debug.php
- concrete/controllers/single_page/dashboard/system/environment/entities.php
- concrete/controllers/single_page/dashboard/system/environment/geolocation.php
- concrete/controllers/single_page/dashboard/system/environment/info.php
- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/controllers/single_page/dashboard/system/environment/proxy.php
- concrete/geolocation/geoplugin/configure.php
- concrete/single_pages/dashboard/system/environment/database_charset.php
- concrete/single_pages/dashboard/system/environment/debug.php
- concrete/single_pages/dashboard/system/environment/entities.php
- concrete/single_pages/dashboard/system/environment/geolocation.php
- concrete/single_pages/dashboard/system/environment/info.php
- concrete/single_pages/dashboard/system/environment/logging.php
- concrete/single_pages/dashboard/system/environment/proxy.php
- concrete/single_pages/dashboard/system/environment/view.php
This PR addresses https://github.com/concrete5/concrete5/issues/8572
> Clean up Dashboard > System and Settings > Environment section

- build/assets/themes/dashboard/scss/_update.scss
- concrete/controllers/single_page/dashboard/system/update.php
- concrete/controllers/single_page/dashboard/system/update/update.php
- concrete/single_pages/dashboard/system/update/update.php
- concrete/single_pages/dashboard/system/update/update/local_available_update.php
- concrete/single_pages/dashboard/system/update/update/no_access.php
- concrete/single_pages/dashboard/system/update/view.php
- concrete/src/Updater/UpdateArchive.php
Fix #8573
In this PR I've split the big view file in multiple sub-views, so that managing each step is much easier.
> Clean up Dashboard > System and Settings > Update concrete5 section

- concrete/single_pages/dashboard/system/optimization/cache.php
- concrete/single_pages/dashboard/system/optimization/clearcache.php
- concrete/single_pages/dashboard/system/optimization/jobs.php
This should have been included in #8598
> Fix checkboxes and radios in System and Settings > Optimization

- concrete/config/concrete.php
- concrete/src/Cookie/ResponseCookieJar.php
- concrete/src/User/PersistentAuthentication/CookieService.php
> Added raw and samesite options to cookie

- concrete/src/Board/Command/PopulateBoardInstanceDataPoolCommandHandler.php
I missed a placeholder in #8671
> Improve translatable log string in PopulateBoardInstanceDataPoolCommandHandler

- concrete/controllers/single_page/dashboard/express/entries.php
Sanitize entity name on entry list
See H1 #873474
> Sanitize entity name on entry list page

- concrete/views/dialogs/search/advanced_search.php
> Sanitize preset name in advanced search dialog

- concrete/elements/express/form/form/form.php
Any downside on this?
PS: fix #8704
> Express form: don't output CSFR token if page is in edit mode

- concrete/blocks/image_slider/view.php
Resolves h1#865416
This PR sanitized the slider slide title to prevent rendering issues.
> Sanitize image slider slide title

- concrete/attributes/user_group/controller.php
- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/multisite/settings.php
- concrete/single_pages/dashboard/system/multisite/settings.php
- concrete/src/Updater/Migrations/Migrations/Version20200609145307.php
* Fixes error when adding user group attribute
* Fix #8735
> Fix 8.5.3 issues

- concrete/controllers/frontend/assets_localization.php
- concrete/elements/page_controls_footer.php
- concrete/elements/workflow/notifications.php
- concrete/src/Application/Service/UserInterface.php
This PR addresses issue #8580
requires a companion Bedrock PR https://github.com/concrete5/bedrock/pull/77
> Page notification update

- concrete/elements/date_time/duration.php
When adding "Repeat Event" options, there are a couple of visual inconsistencies, this PR addresses these styling issues.
> Fixing event repetition styling

- concrete/blocks/gallery/controller.php
- concrete/blocks/gallery/view.css
- concrete/blocks/gallery/view.php
- concrete/src/Feature/UsesFeatureInterface.php
This view includes lightbox functionality for the images in the gallery, and the ability to set some images as full width.
> Update gallery to have a nice default view

- concrete/controllers/dialog/page/advanced_search.php
- concrete/controllers/dialog/user/advanced_search.php
- concrete/controllers/element/pages/search/menu.php
- concrete/controllers/element/pages/search/search.php
- concrete/controllers/element/users/search/menu.php
- concrete/controllers/element/users/search/search.php
- concrete/controllers/single_page/dashboard/sitemap/search.php
- concrete/controllers/single_page/dashboard/users/add.php
- concrete/controllers/single_page/dashboard/users/search.php
- concrete/elements/pages/search/menu.php
- concrete/elements/pages/search/search.php
- concrete/elements/users/search/menu.php
- concrete/elements/users/search/search.php
- concrete/single_pages/dashboard/sitemap/search.php
- concrete/single_pages/dashboard/users/search.php
- concrete/single_pages/dashboard/users/search/edit.php
- concrete/src/Navigation/Breadcrumb/Dashboard/DashboardUserBreadcrumbFactory.php
- concrete/src/Page/Menu.php
- concrete/src/Page/Search/Menu/MenuFactory.php
- concrete/src/User/Menu.php
- concrete/src/User/Search/Menu/MenuFactory.php
This commit contains the refactored versions of page and user search.
Associated tasks: #8752 and #8753 .
Everything is tested and working fine on my development environment.
**Comments:**
While refactoring this i have found two general issues that should be fixed in the future:
1. "$(...).concreteEditableFieldContainer is not a function" on some bulk actions and on user detail page (and on all other places where in-page-editing is used)
2. the dashboard breadcrumb style is not visible for non-super-admin-users (permission problem?)
> Feature/dashboard page + user search

- concrete/src/File/Import/ImportOptions.php
> use the selected folder's storage location when uploading a file

- concrete/src/Tree/Node/Type/File.php
> when moving a file, use the folder's storage location

- concrete/src/Multilingual/Page/Section/Processor/MultilingualProcessorTarget.php
Fix #8791
Is the base branch `8.5.x` correct for this pull request? Or should I use `8.6.x-dev`? Or... ?
> [v8] Fix Rescan Multilingual Locale does not work

- build/webpack.mix.js
- concrete/blocks/html/add.php
- concrete/blocks/html/composer.php
- concrete/blocks/html/controller.php
- concrete/blocks/html/edit.php
- concrete/blocks/html/form_setup_html.php
- concrete/blocks/html/view.php
- concrete/config/app.php
This Pull Request addresses issue: #8833
Requires an update of the Bedrock repository (https://github.com/concrete5/bedrock/pull/94).
We have updated Ace library to the latest version and tested if there are some breaking changes.
> Fix HTML block for version 9

- concrete/controllers/single_page/dashboard/pages/containers.php
- concrete/controllers/single_page/dashboard/pages/containers/add.php
- concrete/controllers/single_page/dashboard/pages/single.php
- concrete/controllers/single_page/dashboard/pages/templates.php
- concrete/controllers/single_page/dashboard/pages/templates/add.php
- concrete/single_pages/dashboard/pages/containers/add.php
- concrete/single_pages/dashboard/pages/containers/form.php
- concrete/single_pages/dashboard/pages/containers/view.php
- concrete/single_pages/dashboard/pages/single.php
- concrete/single_pages/dashboard/pages/templates/add.php
- concrete/single_pages/dashboard/pages/templates/view.php
This pull request adresses: #8888
Additionally we have cleaned up some php points in views/controllers and replaced deprecated code
> Dashboard > Page and Themes > Page Templates, Containers and Single Pages cleanup

- concrete/controllers/single_page/dashboard/users/add.php
- concrete/single_pages/dashboard/users/add.php
This pull request adresses: #8873
Additionally we have cleaned up some php points in views/controllers and replaced deprecated code
> Dashboard > Users > Add User Cleanup

- concrete/blocks/file/add.php
- concrete/blocks/file/composer.php
- concrete/blocks/file/controller.php
- concrete/blocks/file/edit.php
- concrete/blocks/file/view.php
- concrete/blocks/form/add.php
- concrete/blocks/form/controller.php
- concrete/blocks/form/edit.php
- concrete/blocks/form/form_setup_html.php
- concrete/blocks/form/mini_survey.php
- concrete/blocks/form/statistics.php
- concrete/blocks/form/styles_include.php
- concrete/blocks/form/tools/services.php
- concrete/blocks/form/view.php
- concrete/blocks/google_map/add.php
- concrete/blocks/google_map/controller.php
- concrete/blocks/google_map/edit.php
- concrete/blocks/google_map/form_setup_html.php
- concrete/blocks/google_map/scrapbook.php
- concrete/blocks/google_map/view.php
- concrete/src/Application/Service/UserInterface.php
This pull request adresses:
- File Block https://github.com/concrete5/concrete5/issues/8842
- Legacy Form Block https://github.com/concrete5/concrete5/issues/8843
- Google Map Block https://github.com/concrete5/concrete5/issues/8844
Additionally we have cleaned up some php points in views/controllers and replaced deprecated code
> Fix file/form/google maps blocks

- concrete/controllers/single_page/dashboard/pages/themes.php
- concrete/controllers/single_page/dashboard/pages/themes/inspect.php
- concrete/single_pages/dashboard/pages/themes/inspect.php
- concrete/single_pages/dashboard/pages/themes/view.php
This pull request adresses: #8886
Additionally we have cleaned up some php points in views/controllers and replaced deprecated code
> Cleanup dashboard page themes

- concrete/src/Updater/Migrations/Migrations/Version20190509205043.php
Apply #8781 to the 8.5.x branch.
> Fix ExpressEntityEntries.publicIdentifier migration

- concrete/controllers/single_page/dashboard/blocks/permissions.php
- concrete/controllers/single_page/dashboard/blocks/stacks.php
- concrete/elements/permission/detail.php
- concrete/elements/permission/details/block_type.php
- concrete/elements/permission/keys/add_block.php
- concrete/single_pages/dashboard/blocks/permissions.php
- concrete/single_pages/dashboard/blocks/stacks/detail.php
- concrete/single_pages/dashboard/blocks/stacks/list/view.php
- concrete/single_pages/dashboard/blocks/stacks/view.php
- concrete/single_pages/dashboard/blocks/types/view.php
- concrete/single_pages/dashboard/blocks/view.php
- concrete/src/Block/BlockType/BlockTypeList.php
- concrete/tools/permissions/access_entity.php
- concrete/views/dialogs/page/add_block_list.php
This Pull Request addresses issue: #8891
> Cleanup Stacks and Blocks section

- concrete/controllers/single_page/dashboard/users/points.php
- concrete/controllers/single_page/dashboard/users/points/actions.php
- concrete/controllers/single_page/dashboard/users/points/assign.php
- concrete/single_pages/dashboard/users/points/actions.php
- concrete/single_pages/dashboard/users/points/assign.php
- concrete/single_pages/dashboard/users/points/view.php
- concrete/src/User/Point/Action/Action.php
- concrete/src/User/Point/Action/ActionList.php
- concrete/src/User/Point/EntryList.php
This pull request adresses #8879 
I've replaced `Concrete\Core\Legacy\DatabaseItemList` by `Concrete\Core\Search\ItemList\Database\ItemList` for `Concrete\Core\User\Point\Action\ActionList` and `Concrete\Core\User\Point\EntryList` to fix pagination design issue and get rid of legacy code
> Cleanup  Dashboard > Users > Community Points

- composer.json
- composer.lock
This fixes some PHP-CS-Fixer bugs
> Update PHP-CS-Fixer from 2.16.1 to 2.16.4

- concrete/src/Application/Service/UserInterface.php
This PR updates the UserInterface Notification PopUp styling.
> Update UserInterface popup styling

- concrete/src/Database/Driver/PDOStatement.php
> [v8] Fix doctrine dbal incompatibility

- concrete/src/Block/Block.php
> [v8] Avoid editing non-editable aliased blocks

- concrete/config/concrete.php
- concrete/elements/header_required.php
- concrete/src/Block/Block.php
- concrete/src/Multilingual/Service/Detector.php
- concrete/src/StyleCustomizer/Style/TypeStyle.php
(broken style selector when using 'type'-type with missing color preset). I think @bitterdev fixed this in develop but we'll need it in 8.5.
> Fix issue #8787 

- concrete/src/Page/Theme/Theme.php
Currently, we're getting the same PageTheme instance from the database so many times on a single request!
Let's avoid it by using the request cache.
Before: 245 statements were executed, 114 of which were duplicates, 131 unique
After: 227 statements were executed, 96 of which were duplicates, 131 unique
> Avoid getting same PageTheme instance from database repeatedly

- concrete/src/Page/Collection/Version/Version.php
Let's avoid getting the same collection version from the database multiple times!
Before: 245 statements were executed, 114 of which were duplicates, 131 unique
After: 236 statements were executed, 98 of which were duplicates, 138 unique
> Avoid to get the same Collection Version from the database repeatedly

- concrete/src/Tree/Node/NodeType.php
- concrete/src/Tree/Tree.php
It's amazing, but we're getting Tree and NodeType object a lot of times in a single request, even if we're using one Tree in most cases. Let's store it in the request cache.
Before: 339 statements were executed, 145 of which were duplicates, 194 unique
After: 333 statements were executed, 135 of which were duplicates, 198 unique
> Avoid getting same Tree and Tree Node Type from database repeatedly

- concrete/src/Block/BlockType/BlockType.php
Currently, we're getting BlockType object 47 times, even if there're 9 block types on the Home page of Elemental Full demo site. That means, we're loading block type controller 47 times, calling `Concrete\Core\Filesystem\FileLocator::getRecord` 78 times, calling `$app->make()` 156 times. We can reduce it to 9 times if we use request cache.
Before
After
> Avoid getting same BlockType object repeatedly

- concrete/src/Session/Storage/LoggedStorage.php
> [v9] Fix regenerate method of LoggedStorage Session Storage

- concrete/src/Session/Storage/LoggedStorage.php
> [v8] Fix regenerate method of LoggedStorage Session Storage

- concrete/config/app.php
- concrete/src/Page/HandleGenerator.php
- concrete/src/Page/Page.php
- concrete/src/Page/PageServiceProvider.php
This PR fixes #9013 
Now developers can override how to generate a collection handle like alphanumeric only, YYYYMMDD, etc.
> Make it enable to customize the process of generating collection handle

- concrete/src/Http/DefaultDispatcher.php
V8 version of https://github.com/concrete5/concrete5/pull/9080
> [V8] Use UserMessageException when invalid path traversal is detected

- concrete/blocks/board/controller.php
This PR does a few things to the board block controller:
1. Adds a validator method that makes sure we are provided a valid block instance if we're not regenerating
2. Declares the `blockInstanceId` property
3. Ensures the blockInstanceId is not null before searching with doctrine
> Validate board block save

- concrete/single_pages/dashboard/boards/add.php
> Fixed wrong value of for attribute

- concrete/src/Editor/CkeditorEditor.php
> [V8] Prevent CKEditor from initializing an already initialized editor

- concrete/src/Session/SessionFactory.php
> [V8] Fix Redis prefix for session cookies

- concrete/src/Session/SessionFactory.php
> [V9] Fix Redis prefix for session cookies

- concrete/views/dialogs/tree/node/category/delete_express.php
This pr fixes https://github.com/concrete5/concrete5/issues/8167
But please make sure it doesn't break anything else. I couldn't find anything though.
> [Fix]Error when deleting custom entry locations #8167

- concrete/src/Routing/RouteActionFactory.php
See https://github.com/concrete5/concrete5/pull/8485#issuecomment-715440533
> Avoid potential issue in RouteActionFactory::createAction()

- concrete/elements/dashboard/navigation/nav.php
- concrete/elements/panels/dashboard.php
- concrete/src/Application/UserInterface/Dashboard/Navigation/AbstractNavigationCache.php
- concrete/src/Application/UserInterface/Dashboard/Navigation/FavoritesNavigationCache.php
- concrete/src/Application/UserInterface/Dashboard/Navigation/NavigationCache.php
- concrete/src/Navigation/Item/PageItem.php
The contents of the dashboard panel is not localized: let's translate its content.
> Translate contents of dashboard panel

- concrete/src/Console/Command/ConfigCommand.php
ConfigCommand load only application config after splitting FileLoader in two loaders ( See https://github.com/concrete5/concrete5/commit/2514f1ac195ad62fff240f4cd8aa948a8faab7c8 )
> [V9] BugFix: ConfigCommand load only from application config

- build/assets/themes/dashboard/js/file-manager/file-manager.js
- build/assets/themes/dashboard/scss/_tables.scss
- concrete/config/concrete.php
- concrete/controllers/backend/file.php
- concrete/elements/files/search/menu.php
- concrete/routes/actions/files.php
- concrete/single_pages/dashboard/files/search.php
- concrete/src/Entity/File/Folder/FavoriteFolder.php
- concrete/src/File/Component/Chooser/DefaultConfiguration.php
- concrete/src/File/Component/Chooser/Option/FolderBookmarkOption.php
- concrete/src/File/Search/Result/Item.php
- concrete/src/Updater/Migrations/Migrations/Version20201022000000.php
You need to update bedrock (https://github.com/concrete5/bedrock/pull/122)
> Add favorite folders support for file manager.

- composer.lock
- concrete/composer.json
- concrete/controllers/backend/file.php
- concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php
- concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php
- concrete/src/Permission/IPService.php
- concrete/src/Permission/PermissionServiceProvider.php
- tests/tests/Session/SessionValidatorTest.php
> [V8] Correctly parse non decimal ip addresses

- concrete/src/Routing/Router.php
- tests/tests/Core/Routing/RouterTest.php
- tests/tests/Routing/CheckRoutesTest.php
This is a backport of #9056 to v8
> [V8] Fix routes with optional arguments

- concrete/elements/permission/lists/file.php
I missed this change in e22d87e6998da05c47d4c465d333e4d6e8aa7e92 (#9036)
> Fix wrong route in  permission/lists/file element

- concrete/controllers/backend/block/process.php
- concrete/routes/actions/blocks.php
- concrete/views/panels/add.php
>  Migrate top level tools scripts into the routing/controller/view system - Part 2

- .appveyor/configure.ps1
- .travis/composer-deps.sh
Let's keep using composer version 1 for the time being
> Stay with composer version 1

- .appveyor/configure.ps1
- .travis/composer-deps.sh
Same as #9161 but for concrete5 8
> [V8] Stay with composer version 1

- concrete/src/Application/Service/Dashboard/Sitemap.php
> [V8] Store the "include system pages" sitemap option in session instead of cookie

- concrete/views/dialogs/page/sitemap_selector.php
> Fix height of sitemap_selector dialog contents

- concrete/controllers/backend/file.php
- concrete/controllers/backend/file/chooser.php
- concrete/src/File/ExternalFileProvider/Configuration/ConfigurationInterface.php
- concrete/src/File/ExternalFileProvider/ExternalFileList.php
- concrete/src/File/ExternalFileProvider/ExternalSearchRequest.php
This is related to the following ticket:
https://github.com/concrete5/brand_central/issues/51
> Performace tweak for file folder dropdown.

- concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
This pull request should fix issue 9162.
> #9162 make sure the csv writer config values are used

- concrete/controllers/backend/file.php
Remove the SQL optimized fetch directories query because of missing permission checks and revert back to the previous one.
> Revert back changes

- composer.lock
- concrete/composer.json
- concrete/controllers/backend/file.php
- concrete/controllers/single_page/download_file.php
- concrete/src/Entity/File/File.php
- Let's reduce the Composer dependencies, by using `symfony/polyfill-uuid` instead of `ramsey/uuid`
- Let's use the ready-to-use `uuid_is_valid` function to check UUIDs
- Let's add an index to the File.fUUID database field
- Let's make the File.fUUID database field unique (we don't want two files with the same UUID, don't we?)
- Let's avoid adding public properties (we should use getters/setters instead)
> Some UUID-related fixes

- concrete/views/dialogs/file/search.php
> [V8] Avoid accessing an undefined variable in dialogs/file/search view

- concrete/src/Filesystem/FileLocator.php
- concrete/src/Filesystem/FileLocator/CoreLocation.php
> Minor fixes for FileLocator

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/extend/update.php
- concrete/src/Application/Application.php
- concrete/src/Console/Command/FixThemeValuesCommand.php
- concrete/src/Console/Command/UpdatePackageCommand.php
- concrete/src/Package/Package.php
- concrete/src/Page/Theme/AvailableVariablesUpdater.php
- concrete/src/Page/Theme/AvailableVariablesUpdater/Result.php
- concrete/src/Updater/Migrations/Migrations/Version20201116182100.php
- fix listing installed themes
- look for variable values in all presets
- fix phpdoc
Supersedes #9249
> Fix AvailableVariablesUpdater

- concrete/config/app.php
- concrete/elements/files/edit/image_editor/toast.php
This PR should fix the issue reported here: https://github.com/concrete5/concrete5/pull/9255#issuecomment-732265448
> Be sure that the Image Editor CSS is loaded before creating it

- concrete/blocks/event_list/controller.php
- concrete/blocks/event_list/db.xml
- concrete/blocks/event_list/form.php
- concrete/blocks/event_list/view.php
- concrete/blocks/express_entry_list/controller.php
- concrete/blocks/express_entry_list/db.xml
- concrete/blocks/express_entry_list/edit.php
- concrete/blocks/express_entry_list/view.php
Adds a title format option to the Event List block as discussed in #8282 and initial PR #8405
> block-title-format for Event List block #8282

- concrete/blocks/feature/controller.php
- concrete/blocks/feature/db.xml
- concrete/blocks/feature/form.php
- concrete/blocks/feature/view.php
Adds a title format option to the Feature block as discussed in #8282 and initial PR #8405
> block-title-format for Feature block #8282

- concrete/blocks/page_list/controller.php
- concrete/blocks/page_list/db.xml
- concrete/blocks/page_list/page_list_form.php
- concrete/blocks/page_list/view.php
Adds a title format option to the Page List block as discussed in #8282 and initial PR #8405
>  block-title-format for Page List block #8282

- concrete/blocks/tags/controller.php
- concrete/blocks/tags/db.xml
- concrete/blocks/tags/tag_form.php
- concrete/blocks/tags/view.php
Adds a title format option to the Tags block as discussed in #8282 and initial PR #8405
> block-title-format for Tags block #8282

- concrete/blocks/topic_list/controller.php
- concrete/blocks/topic_list/db.xml
- concrete/blocks/topic_list/form.php
- concrete/blocks/topic_list/view.php
Adds a title format option to the Topic List block as discussed in #8282 and initial PR #8405
> block-title-format for Topic List block #8282

- concrete/attributes/topics/controller.php
Issue
https://www.youtube.com/watch?v=kReUfVc8Ado
Fixed
https://www.youtube.com/watch?v=TIZX5NELXTY
> [V8] Fixes filtering by multiple topic attributes.

- concrete/src/Workflow/Type.php
> [V8] Fix: Workflow\Type::getListByPackage always return Basic Workflows

- concrete/attributes/topics/controller.php
> [V9] Fixes filtering by multiple topic attributes.

- concrete/config/app.php
> [V8] Fix config value of generic file type for html file

- concrete/config/app.php
> [V9] Fix config value of generic file type for html file

- concrete/attributes/textarea/controller.php
> [V9] Do not remove picture elements on rendering textarea attribute value

- concrete/blocks/survey/controller.php
- concrete/blocks/survey/edit.php
- concrete/blocks/survey/view.php
- concrete/controllers/single_page/dashboard/reports/surveys.php
- concrete/single_pages/dashboard/reports/surveys.php
[9.0] Fix h1 report 1065577
also ran php-cs on the files edited.
> [9.0] Fix h1 report 1065577

- concrete/blocks/survey/controller.php
- concrete/blocks/survey/view.php
- concrete/controllers/single_page/dashboard/reports/surveys.php
- concrete/single_pages/dashboard/reports/surveys.php
Fix H1 report 1065577
also ran php-cs on the files edited.
> [8.5] Fix H1 report 106557

- tests/tests/Workflow/WorkflowTypeTest.php
WorkflowTypeTest introduced by @mlocati on #7931, but it couldn't catch the bug #8943
I've updated the test to catch if the bug happens again in the future.
> Update test to catch getListByPackage bug

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/extend/install.php
- concrete/single_pages/dashboard/extend/install.php
> [v9][Feature] add delete button to package #5204

- concrete/attributes/duration/controller.php
- concrete/attributes/duration/form.php
- concrete/attributes/duration/type_form.php
- concrete/config/concrete.php
- concrete/config/db.xml
- concrete/config/install/base/attributes.xml
- concrete/config/install/base/jobs.xml
- concrete/jobs/remove_old_file_attachments.php
- concrete/src/Entity/Attribute/Key/Settings/DurationSettings.php
- concrete/src/Entity/Attribute/Value/Value/DurationValue.php
- concrete/src/Updater/Migrations/Migrations/Version20201229143500.php
- concrete/src/Updater/Migrations/Migrations/Version20201231153200.php
- concrete/src/User/PrivateMessage/PrivateMessage.php
- concrete/src/User/UserInfo.php
Merging @bitterdev 's work via cherry-picking.
> Duration attribute type private message attachments

- concrete/blocks/document_library/controller.php
- concrete/blocks/document_library/db.xml
- concrete/blocks/document_library/edit.php
- concrete/src/Updater/Migrations/Migrations/Version20210128224608.php
This PR applies changes that were made to the 8.6.x-branch in:
- #9338 
- #9345 
with necessary changes for v9
> Document library fixes from 8.6.x-dev branch

- concrete/src/Http/Client/Client.php
This PR adds a log entry any time a client fails to send a request.
> Add better logging for failed network requests

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/mail/method.php
- concrete/controllers/single_page/dashboard/system/mail/method/test.php
- concrete/single_pages/dashboard/system/mail/method.php
- concrete/src/Mail/Transport/Factory.php
Companion of https://github.com/concrete5/concrete5/pull/9375
> [V9] Let user specify the SMTP HELO/EHLO domain

- concrete/src/Search/ItemList/ItemList.php
Drops into 8.5.4 as well!  @jbender0 thx for solving my initial problem 💯 
https://github.com/concrete5/concrete5/commit/ac03a44454094f289a825a7b818f2e8498bfa51b
> Legacy Paging String 8.5.x

- concrete/controllers/dialog/groups/search.php
- concrete/routes/dialogs/groups.php
- concrete/src/Permission/Access/Entity/GroupEntity.php
- concrete/views/dialogs/permissions/access/entity/types/group_combination.php
This PR is bringing back the group search for access entities. (was removed by the group type feature)
> Important fix

- concrete/src/Search/Result/ResultFactory.php
> fix to result factory

- concrete/blocks/survey/auto.js
- concrete/views/dialogs/event/choose.php
Issues
https://user-images.githubusercontent.com/514294/115765351-9c4a0d80-a3e1-11eb-9e92-ceda4cdb968d.mov
https://user-images.githubusercontent.com/514294/115765400-ab30c000-a3e1-11eb-92ad-026f4fe34ab7.mov
Fixed
https://user-images.githubusercontent.com/514294/115765444-ba177280-a3e1-11eb-8dcc-55428d463fe7.mov
https://user-images.githubusercontent.com/514294/115765476-c4d20780-a3e1-11eb-900d-567c893e3faa.mov
> Fix disappearing dialog in some cases

- concrete/authentication/concrete/controller.php
This is a fix for https://github.com/concrete5/concrete5/issues/9434. I was looking at login speed when logging in via the auth cookie on one of our sites, and found some odd behaviour in the verifyHash() function that was affecting performance:
1) The function would fetch all rows from the `authTypeConcreteCookieMap` table for the user, even expired rows
2) The delete functionality would only delete the one row that matches the cookie hash. This caused quite a few expired entries to build up in the database.
3) The `checkPassword()` function would run against the expired entries, but then later in the function that entry would be rejected because it is expired. `checkPassword()` can be slow and this was noticeably slowing down the login as it was checking all expired entries
4) I've …
> Improved cookie login speed

- concrete/config/app.php
> Fixes #9471

- concrete/src/Mail/Service.php
Same as #9483 but for concrete 9
> [V9] Ignore errors when closing the mail transport

- .github/workflows/phpunit.yml
- README.md
- concrete/composer.json
This PR does less than @mlocati's earlier attempt but it's fully working for the following:
- PHP 7.4 using locked dependencies
- PHP 7.3 using locked dependencies
- PHP 7.2 using locked dependencies
- PHP 7.4 using highest dependencies
It does not yet work for:
- PHP 8.0 using any dependencies
- PHP 7.4 using lowest dependencies
> Add simple github action for phpunit tests

- concrete/elements/page_controls_footer.php
- concrete/src/Application/Service/UserInterface.php
> [v9] Fix Page Alias notification error

- concrete/src/Validator/PasswordValidatorServiceProvider.php
This PR fixes issue #9449  when set 0 (no limit) for maximum characters of password
> Fix issue #9449

- concrete/elements/express/form/form/form.php
- concrete/src/Entity/Express/FieldSet.php
needs this to be merged
https://github.com/concrete5-community/translation-library/pull/9
> [V8] Localization support for express form field sets

- concrete/controllers/panel/detail/page/seo.php
> [v9] Fix update url slug

- concrete/src/Mail/MailServiceProvider.php
Same as #9499 but for concrete5 version 8.
> [V8] Don't make the mail transport a singleton

- concrete/controllers/panel/sitemap.php
- concrete/src/Permission/Access/Access.php
This PR fixes #9481 and needs to make some PR to the develop branch also.
* demo (Administratos group)
* author1 (Authors group)
* author2 (Authors group)
Add Pages of This Type by "Administrators" and "Authors" group
Edit Page Type Drafts by "Administrators" group and "Page Owner"
Add Pages of This Type by "Administrators" and "Authors" group
Edit Page Type Drafts by "Page Owner" only
Add Pages of This Type by "Authors" group
Edit Page Type Drafts by "Administrators" group
> [V8] Fix to show page drafts created by the current user

- composer.lock
- concrete/composer.json
- concrete/src/Updater/Migrations/Migrations/Version20210616131513.php
- tests/tests/Localization/Address/FormatterTest.php
Includes:
adding repeatable migration
the fixes from #9517
and updating the minimum requirement for commerceguys/address
> [v9] Fix all the tests

- concrete/single_pages/account/edit_profile.php
All thanks to @bitterdev in the develop branch:
https://github.com/concrete5/concrete5/pull/9514/commits/ee67a94cca2743accdada3f1d9edae3242ae44fa
> 8.5.x - Profile > Edit Username

- concrete/config/concrete.php
- concrete/config/install/base/single_pages/dashboard.xml
- concrete/controllers/single_page/dashboard/system/registration/session_options.php
- concrete/single_pages/dashboard/system/registration/session_options.php
- concrete/src/Updater/Migrations/Migrations/Version20210622145600.php
- concrete/src/User/User.php
- Adds a single page to edit session cookie settings
- Forces generating a new session when logging in
> Add session options

- concrete/controllers/backend/file.php
- tests/tests/Controller/Backend/FileTest.php
See #9547 for the 8.5.x version of this and discussion
> Prevent importing from hexadecimal/octal/long ips

- concrete/controllers/element/dashboard/express/menu.php
- concrete/controllers/single_page/dashboard/system/express/entities.php
> [V9] Fix display order of express entities in dashboard

- concrete/src/Permission/Access/Entity/GroupEntity.php
V8 version of #9038
Before
After
> [V8]Avoid to get same Permission Access Entity from database repeatedly

- concrete/elements/express/form/form/form.php
- concrete/src/Entity/Express/FieldSet.php
> [V9] Localization support for express form field sets

- concrete/controllers/backend/file.php
This is the v9 version of #9549
> Don't follow redirects on import

- concrete/config/install/base/single_pages/dashboard.xml
- concrete/config/install/base/single_pages/global.xml
- concrete/config/install/base/single_pages/root.xml
> [V9] Fix icons class for pages trash & Drafts & Dashboard & Stacks in Sitemap

- concrete/jobs/index_search.php
> "Index Search Engine - Updates" job should not re-index all entries.

- concrete/blocks/core_container/view.php
- concrete/views/panels/add.php
> make container's name translatable  (In add panel & core_container view)

- concrete/views/panels/details/page/composer.php
Fix #7692 for V8
https://user-images.githubusercontent.com/514294/117095689-fc599000-ada1-11eb-982e-81a52772961d.mov
> [V8] Fix 7692

- concrete/views/panels/details/page/composer.php
V9 version of #9474
https://user-images.githubusercontent.com/514294/126633393-5fbb1348-4db3-483e-9f00-882e2610694d.mov
> [V9] Fix 7692

- concrete/config/install/base/single_pages/global.xml
> [V9] Add noindex meta tag to login page

- concrete/config/install/base/single_pages/global.xml
> [V8] Add noindex meta tag to login page

- concrete/src/User/PrivateMessage/Limit.php
> [V9] Private messages max limit fix

- concrete/src/Http/ResponseFactory.php
- concrete/src/Multilingual/Service/Detector.php
- concrete/themes/concrete/elements/header.php
- concrete/themes/core/error.php
- concrete/themes/dashboard/elements/header.php
V9 version of #9468 but also included #9026 that not yet merged to develop branch.
> [V9] Render single pages like 404, 403, login, register in default site locale

- concrete/src/Page/Controller/PageController.php
V9 version of #9068 but it also fixes #9383
> Fix #5578 for v9

- concrete/src/Express/ObjectBuilder.php
* Make it enables to set searchable, indexed. Fixes #8978
* Avoid creating an attribute key with an already existing handle. Fixes #5284
> Improve Express\ObjectBuilder::addAttribute

- concrete/elements/page_types/composer/controls/core_page_property/version_comment.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/VersionCommentCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/Type/CorePagePropertyType.php
> [Feature] Add version comment field to Composer form

- concrete/elements/attribute/categories/user.php
Fixes #6064
https://user-images.githubusercontent.com/514294/126768309-d6de8a21-a403-4452-80d0-e88892469ca2.mov
> Show warning message when admin trying to make a user attribute to public

- concrete/attributes/calendar_event/controller.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UrlSlugCorePageProperty.php
- concrete/src/Page/Type/Composer/Control/CorePageProperty/UserCorePageProperty.php
> Fix some font awesome icons

- concrete/blocks/share_this_page/controller.php
V8 version of #9598
Fixes #9120
> [V8] Revert "disable caching of share block"

- concrete/blocks/share_this_page/controller.php
Let's turn on the cache for share this page block again. #9120
> [V9] Revert "disable caching of share block"

- concrete/src/Tree/Node/Type/FileFolder.php
> fix issue :  #9561

- concrete/config/site.php
V8 version of #9603 to fix #8259
> [V8] Add more excluded query parameters for canonical tag

- concrete/blocks/page_attribute_display/controller.php
- concrete/blocks/page_attribute_display/form.php
This handles the Page Attribute Display Block issues in 8.5.x branch as well...
> Page Attribute Display updates 8.5.x

- concrete/bootstrap/start.php
- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php
> [v8] fix H1 1063039

- concrete/bootstrap/start.php
- concrete/controllers/single_page/dashboard/system/environment/logging.php
- concrete/src/File/StorageLocation/Configuration/LocalConfiguration.php
> [v9] fix H1 1063039

- concrete/controllers/single_page/dashboard/pages/types/output.php
fixes #9582
Same as #9610 but for version 9
> [v9] fix #9582 - Fix session set not working correctly on redirect in redis/memcached/slow filesystem 

- concrete/themes/elemental/elements/footer.php
Update ccm branding anchor text and url.
modernize login link bootstrap float class.
> [v9] Elemental Footer Updates

- composer.lock
- concrete/composer.json
- concrete/controllers/backend/file.php
- concrete/controllers/single_page/dashboard/system/environment/geolocation.php
- concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php
- concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php
- concrete/src/Entity/Permission/IpAccessControlEvent.php
- concrete/src/Entity/Permission/IpAccessControlRange.php
- concrete/src/Permission/IPRange.php
- concrete/src/Permission/IPService.php
- concrete/src/Permission/IpAccessControlService.php
- concrete/src/Permission/PermissionServiceProvider.php
- tests/tests/Permission/IPServiceTest.php
- tests/tests/Session/SessionValidatorTest.php
- tests/tests/User/Login/LoginServiceTest.php
> [V9] Upgrade IPLib to version 1.17.0

- concrete/single_pages/dashboard/extend/connect.php
Same as #9557 + #9558 but for V8
> [V8] Fix marketplace texts

- concrete/blocks/express_entry_list/controller.php
- concrete/controllers/backend/express/entry.php
- concrete/controllers/backend/file/chooser.php
- concrete/controllers/single_page/dashboard/extend/install.php
- concrete/controllers/single_page/dashboard/pages/themes.php
- concrete/controllers/single_page/dashboard/system/express/entities/customize_search.php
- concrete/controllers/single_page/dashboard/system/express/entities/order_entries.php
- concrete/src/Api/ApiServiceProvider.php
- concrete/src/Api/OAuth/Client/ClientFactory.php
- concrete/src/Config/ConfigServiceProvider.php
- concrete/src/Config/Driver/Redis/RedisConfigServiceProvider.php
- concrete/src/Console/Command/PackPackageCommand.php
- concrete/src/Controller/Traits/DashboardExpressEntryListTrait.php
- concrete/src/Http/DefaultServer.php
- concrete/src/Package/Package.php
- concrete/src/Page/Relation/Menu/Item/RelationListItem.php
- concrete/src/Page/Stack/Folder/FolderService.php
- concrete/src/Session/SessionFactory.php
- concrete/src/Site/Menu/Item/SiteListItem.php
- tests/tests/Api/OAuth/Client/ClientFactoryTest.php
If I'm not wrong, we need to call `$app->make()`  using a keyed array for the parameters.
If this is true, I checked the whole ConcreteCMS source code with a regular expression, and I found these places that are using the old positional array alternative.
> Use keyed array for params of app->make()

- concrete/tools/conversations/add_message.php
> Improve validation

- concrete/controllers/single_page/dashboard/users/add_group.php
- concrete/src/User/Group/FolderItemList.php
- concrete/src/User/Group/Group.php
> Fixing bugs in groups

- composer.json
- composer.lock
- concrete/composer.json
- concrete/controllers/backend/file.php
- concrete/controllers/backend/tree/node/duplicate.php
- concrete/controllers/single_page/download_file.php
- concrete/js/build/core/file-manager/menu.js
- concrete/js/build/core/image-editor/image-editor.js
- concrete/js/build/core/tree.js
- concrete/src/Conversation/Message/Message.php
- concrete/src/File/Image/Svg/Sanitizer.php
- concrete/tools/conversations/delete_file.php
- tests/tests/File/Image/Svg/SanitizerTest.php
- tests/tests/File/Import/FileProcessorsTest.php
> Minor security fixes

- concrete/src/Console/CommandRegistry.php
Same as #9720 but against 9.0rc
> Enable the is-installed CLI command

- build/tasks/build-release/clean.js
- build/tasks/build-release/download.js
- composer.lock
- concrete/composer.json
- concrete/src/Encryption/PasswordHasher.php
- concrete/src/User/PasswordHash.php
- concrete/src/User/User.php
- concrete/src/Utility/Service/Identifier.php
This PR removes the gone hautelook/phpass library in favor of a local forked copy. 
See #9807
> Remove hautelook passwordhash; Fix #9807

- concrete/src/Entity/Attribute/Value/Value/TopicsValue.php
This pull request will fix #5000
Maybe we need to fix this also on develop branch
> [V8] Fix: Page type default topic attribute values are not set on the newly created page

- concrete/blocks/document_library/controller.php
This fixes #9759 and also cleans up some of the use of super globals and depreciated code.
> [9.0rc3]fixes #9759 - Document library

- concrete/src/Page/Controller/PageController.php
> [v8] Fix issue with case-sensitive urls

- concrete/src/Page/Controller/PageController.php
> Fix issue with case-sensitive urls

- concrete/src/Http/ResponseFactory.php
> [V8] Return 503 when maintenance mode enabled

- concrete/controllers/backend/file.php
Same fix like https://github.com/concrete5/concrete5/pull/9887 but for version 8.
> Add security fix for importing remote urls.

- concrete/config/concrete.php
- concrete/src/Updater/Migrations/Migrations/Version20210623000000.php
> Set default site type ID for page types created before 8.0

- concrete/src/User/User.php
> Re: Re: Avoid getting Permission Access Entities repeatedly for the same user

- concrete/config/concrete.php
- concrete/config/db.xml
- concrete/controllers/dialog/page/add/compose.php
- concrete/controllers/panel/detail/page/composer.php
- concrete/controllers/panel/page/check_in.php
- concrete/controllers/panel/page/versions.php
- concrete/elements/pages/schedule.php
- concrete/src/Attribute/Category/PageCategory.php
- concrete/src/Attribute/Key/SearchIndexer/StandardSearchIndexer.php
- concrete/src/Page/Collection/Version/EditResponse.php
- concrete/src/Page/Collection/Version/Version.php
- concrete/src/Page/PageList.php
- concrete/src/Page/Type/Type.php
- concrete/src/Updater/Migrations/Migrations/Version20211028142609.php
- concrete/src/Workflow/Request/ApprovePageRequest.php
- concrete/views/panels/page/versions.php
- tests/tests/Page/Collection/Version/ApproveTest.php
> Re: Fix scheduling page feature

- concrete/blocks/gallery/controller.php
- concrete/blocks/gallery/edit.php
- concrete/controllers/panel/detail/theme/preview_page_legacy.php
- concrete/controllers/panel/detail/theme/preview_skin.php
- concrete/controllers/panel/theme/customize_legacy.php
- concrete/controllers/panel/theme/customize_preset.php
- concrete/controllers/single_page/dashboard/files/details.php
- concrete/elements/header_required.php
- concrete/elements/panels/dashboard.php
- concrete/routes/panels.php
- concrete/routes/panels/details.php
- concrete/single_pages/dashboard/extend/install.php
- concrete/src/Block/View/BlockView.php
- concrete/src/Entity/File/File.php
- concrete/src/Form/Service/Form.php
- concrete/src/Page/CustomStyle.php
- concrete/src/StyleCustomizer/Customizations/LegacyCustomizationsManager.php
- concrete/src/StyleCustomizer/Preset/PresetInterface.php
- concrete/src/StyleCustomizer/Preview/LegacyStylesheetPreviewHandler.php
- concrete/src/StyleCustomizer/Traits/CustomizeControllerTrait.php
- concrete/views/panels/details/theme/preview_page_legacy.php
- concrete/views/panels/theme/customize.php
- concrete/views/panels/theme/skins.php
- tests/tests/Form/Service/FormTest.php
Miscellaneous fixes (see individual commits)
> Miscellaneous Fixes 11/11

- concrete/jobs/index_search_all.php
Properly reindexes files, users and sites when running the Index Search All job.
> 8.5.x: Fix #10077

- concrete/src/Sharing/ShareThisPage/ServiceList.php
Maybe @aembler forgot to update this file when he fixed #10043
https://github.com/concrete5/concrete5/commit/41a9deb85c2337ed66d24448ea28a0a8d01446b6
> Fix icon class of share this page services

- concrete/elements/permission/access/entity/types/user.php
> Fix set permission per user issue #10098

- concrete/config/concrete.php
- concrete/config/install/packages/atomik_full/content.xml
- concrete/elements/dashboard/pages/types/header.php
- concrete/src/Updater/Migrations/Migrations/Version20211208145933.php
- concrete/themes/atomik/documentation/containers.xml
- concrete/themes/atomik/documentation/support/containers.xml
* Rename light two column / light stripe to highlight two column / highlight stripe
> Misc fixes 1208

- concrete/src/Attribute/Exception/InvalidAttributeException.php
- concrete/src/Search/ItemList/Database/AttributedItemList.php
Followed by https://github.com/concrete5/concrete5/pull/10156
> [v9] Throw InvalidAttributeException when attribute is not found

- concrete/src/Config/Repository/Liaison.php
Same as https://github.com/concrete5/concrete5/pull/10170 but for concrete5 v8
> [v8] Fix Site config withKey

- composer.lock
This upgrades the localization stuff to Unicode CLDR v40
> Upgrade gettext/languages and punic/punic

- concrete/blocks/core_area_layout/controller.php
- concrete/src/Area/Layout/CustomLayout.php
- concrete/src/Area/Layout/Layout.php
- concrete/src/Area/Layout/Preset/Provider/ActiveThemeProvider.php
- concrete/src/Area/Layout/Preset/Provider/Manager.php
- concrete/src/Area/Layout/Preset/Provider/ManagerServiceProvider.php
- concrete/src/Area/Layout/Preset/Provider/ThemeProvider.php
- concrete/src/Area/Layout/PresetLayout.php
- concrete/src/Area/Layout/ThemeGridLayout.php
- concrete/src/Block/BlockController.php
- tests/helpers/Block/BlockTypeTestCase.php
- tests/tests/Area/AreaLayoutPresetTest.php
- tests/tests/Area/AreaLayoutTest.php
> Fix importing theme-defined area layouts

- concrete/src/Application/UserInterface/Sitemap/StandardSitemapProvider.php
- concrete/src/User/User.php
Fix issue where sitemap is inaccessible to users if the user doesn't have access to view the default locale in the sitemap. 
Fix #10152
> Fix #10152

- concrete/src/Marketplace/Marketplace.php
Fixed errors, and also modernized the legacy Marketplace class
Error detail:
```
Whoops\Exception\ErrorException thrown with message "Undefined variable $ms"
Stacktrace:
#32 Whoops\Exception\ErrorException in /path/to/concrete/src/Marketplace/Marketplace.php:88
#31 Whoops\Run:handleError in /path/to/concrete/src/Marketplace/Marketplace.php:88
#30 Concrete\Core\Marketplace\Marketplace:isConnected in /path/to/concrete/src/Marketplace/Marketplace.php:59
```
> Fix connecting to the marketplace on php8

- concrete/src/Console/Command/RefreshEntitiesCommand.php
> Fix c5:entities:refresh CLI command

- concrete/single_pages/dashboard/calendar/add.php
- concrete/single_pages/dashboard/system/attributes/topics/add.php
- concrete/single_pages/dashboard/users/group_sets.php
- concrete/single_pages/dashboard/users/groups/message.php
Fixed some undefined variable and array to string conversion error on php@8.0.
I'll make another pull request when I find same error on another pages
> Fix undefined variable error on php@8.0

- concrete/themes/atomik/page_theme.php
Description '2021' is already dated. Re-word for the future.
> Improve description which was already dated.

- concrete/attributes/express/controller.php
- concrete/attributes/page_selector/controller.php
- concrete/attributes/user_selector/controller.php
> [V9] Add not implemented validateValue/validateForm methods for some attribute types

- concrete/src/Config/Driver/Redis/RedisSaver.php
Same as #8986, but for 8.5 branch
> Update RedisSaver.php for #10260

- concrete/blocks/express_form/controller.php
Relevant changes added from https://github.com/aembler/concrete5/commit/d74fb2b4ad35d6625c2c1700ee7b12c37feb3138 and tested by our team.
> Fix concrete5#8501 for c5-8

- concrete/blocks/core_area_layout/controller.php
- concrete/config/app.php
- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/optimization/cache.php
- concrete/single_pages/dashboard/system/optimization/cache.php
- concrete/src/Asset/Asset.php
- concrete/src/Asset/AssetInterface.php
- concrete/src/Asset/CssAsset.php
- concrete/src/Asset/CssInlineAsset.php
- concrete/src/Asset/CssLocalizedAsset.php
- concrete/src/Asset/JavascriptAsset.php
- concrete/src/Asset/JavascriptConditionalAsset.php
- concrete/src/Asset/JavascriptInlineAsset.php
- concrete/src/Asset/JavascriptLocalizedAsset.php
- concrete/src/View/DialogView.php
- concrete/src/View/View.php
- Reinstates asset caching setting per the request in #10181 
- Updates cache settings page to better group functionality and better explain functionality.
New cache settings page layout:
> Fix #10181

- concrete/blocks/accordion/add.php
- concrete/blocks/accordion/controller.php
- concrete/blocks/accordion/edit.php
- concrete/blocks/accordion/view.php
- concrete/blocks/autonav/add.php
- concrete/blocks/autonav/controller.php
- concrete/blocks/autonav/edit.php
- concrete/blocks/autonav/form_setup_html.php
- concrete/blocks/autonav/nav_item.php
- concrete/blocks/autonav/templates/breadcrumb.php
- concrete/blocks/autonav/templates/responsive_header_navigation/view.php
- concrete/blocks/autonav/view.php
- concrete/blocks/board/add.php
- concrete/blocks/board/controller.php
- concrete/blocks/board/edit.php
- concrete/blocks/board/view.php
- concrete/blocks/breadcrumbs/controller.php
- concrete/blocks/breadcrumbs/form.php
- concrete/blocks/breadcrumbs/view.php
- concrete/src/Form/Service/Form.php
- concrete/src/Navigation/Breadcrumb/PageBreadcrumb.php
This pr is split from In regards to #10300 to make it easer to review
This PR fixes some issues in php8 when adding/editing the accordion,autonav or board block
It also updates the php-doc for these blocks and updates/removes dead code comments
we also run php-cs-fixer against all these files and phpstan level 6
> PHP8 Compatibility/PHP Doc Block Update for Accordian, Auto-Nav, Boards and breadcrumbs

- concrete/src/Application/Service/Dashboard.php
- concrete/src/Application/Service/Dashboard/Sitemap.php
> [V9] [Performance improvement] Cache response from application services

- concrete/src/Controller/ApplicationAwareControllerResolver.php
- concrete/src/Controller/FunctionController.php
> Fix building route callbacks

- concrete/src/Permission/Response/PageResponse.php
`$cp->canViewToolbar()` is the often used permission check and also it should return the same value on each request.
So let's cache it! It'll be two times faster than before.
Before
After
If you look nice, I'll make another PR for V9.
> [V8] Cache response of $cp->canViewToolbar()

- concrete/controllers/panel/detail/page/attributes.php
- concrete/src/Attribute/ObjectTrait.php
- concrete/src/Page/Collection/Collection.php
See #10051
I've just cherrypicked these commits from develop branch history.
> [V8] Fix #10051

- concrete/elements/permission/details/block/timed_guest_access.php
- concrete/src/Block/Menu/Menu.php
> [v9] Fix 10385

- concrete/src/Support/CodingStyle/PhpFixerRuleResolver.php
See https://mlocati.github.io/php-cs-fixer-configurator/#version:2.19|fixer:list_syntax
> Fix list_syntax rule of PHP-CS-Fixer

- CONTRIBUTING.md
- INSTALL.md
A couple typo fixes for repo docs.
> Fixing some typos in repo documentation

- .github/workflows/update.yml
Let's be sure that we can upgrade from 8.5.7
> Test updating from 8.5.7

- .github/workflows/install.yml
- .github/workflows/update.yml
We use [docker5](https://github.com/concrete5-community/docker5) to test if the current develop branch can install and update previous versions.
docker5 also comes with a web server: so, what about testing if the installed/updated website actually works?
> Test that the website works after install/upgrade

- concrete/src/Permission/IpAccessControlService.php
> [v8] Fix IpAccessControlService check against specific access control category

- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/optimization/clearcache.php
- concrete/src/Asset/Asset.php
- concrete/src/Console/Command/ClearCacheCommand.php
Does the same for v8 as https://github.com/concrete5/concrete5/pull/10484 for v9
https://github.com/concrete5/concrete5/issues/10483
> [v8] Implement #10483 - add cache clear timestamp

- composer.lock
Version 1.3.1 is affected by a PHP bug: see https://github.com/php-imagine/Imagine/releases/tag/1.3.2
> Upgrade Imagine to v1.3.2

- concrete/single_pages/dashboard/blocks/stacks/view.php
Sanitize sort URLs to prevent issues in legacy browsers.
> Sanitize sort urls on stacks page

- concrete/controllers/single_page/dashboard/system/seo/bulk.php
refs #10505 
This appears to work with pages both from the default and alternate languages selected but I'm not sure if there would be a different approach that would be preferred.
> Filter bulk seo PageList by site when filtering by all levels

- concrete/elements/files/bulk/move_to_folder.php
> Remove unused, undefined variable

- concrete/themes/elemental/blocks/page_list/templates/thumbnail_grid/view.php
> null coalesce optional variable

- concrete/src/Page/Page.php
> Do not set full page cache lifetime longer than upcoming publish date

- concrete/controllers/backend/file.php
This PR sanitizes dropzone input.
> Make sure we have good input from dropzone

- concrete/src/Block/Block.php
Before
After
Reduced 22 duplicated SQL queries before this fix
> Performance Improvement: Fix wrong usage of request cache in Block::getByID

- concrete/src/File/Image/Thumbnail/Type/Type.php
Before
After
Reduced 26 duplicated SQL queries
> Performance Improvement: Avoid getting thumbnail type list multiple times

- concrete/elements/dashboard/reports/logs/search/menu.php
- concrete/single_pages/dashboard/reports/logs.php
Prevent potential XSS in legacy browsers
> Prevent potential XSS in legacy browsers

- concrete/src/Updater/Migrations/Migrations/Version20181116072400.php
This pull request fixes #9788
Before run the migration
cID | cvID | cvIsApproved | cvPublishDate       | cvPublishEndDate    |
----|------|--------------|---------------------|---------------------|
224 | 1    | 1            | NULL                | NULL                |
224 | 2    | 1            | 2021-09-27 18:25:00 | NULL                |
225 | 1    | 1            | NULL                | 2021-09-30 18:39:00 |
225 | 2    | 1            | 2021-09-28 18:39:00 | 2021-09-29 18:39:00 |
After run the migration
cID | cvID | cvIsApproved | cvPublishDate       | cvPublishEndDate    |
----|------|--------------|---------------------|---------------------|
224 | 1    | 1            | NULL                | 2021-09-27 18:24:59 |
224 | 2    | 1            | 2021-09-27 18:25:00 | NULL                | …
> [V8] Fix migration bug on fix overlapping start end dates

- concrete/blocks/accordion/view.php
- concrete/blocks/core_area_layout/templates/parallax/js/parallax-image.js
- concrete/blocks/core_area_layout/templates/parallax/view.js
- concrete/controllers/backend/file.php
- concrete/themes/elemental/blocks/accordion/view.php
- tests/tests/Statistics/UsageTracker/FileUsageTrackerTest.php
- tests/tests/User/Password/PasswordUsageTrackerTest.php
> Misc fixes 0420

- composer.lock
- concrete/blocks/document_library/controller.php
- concrete/blocks/document_library/view_header.php
- concrete/composer.json
- concrete/src/Database/DatabaseStructureManager.php
- concrete/src/Localization/Locale/Service.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Page/Page.php
- concrete/src/Updater/Update.php
> Misc fixes 0425

- concrete/controllers/backend/tree.php
- concrete/js/build/core/tree.js
Same fix as for c5-9 but for c5-8
> Fix #7731 on c5-8

- concrete/src/Block/Block.php
> Fix #10616

- concrete/controllers/backend/file.php
> update permission key for duplicating a file

- concrete/single_pages/dashboard/system/permissions/captcha.php
> Misc fixes 6/2

- concrete/elements/custom_block_template.php
- concrete/elements/custom_style.php
- concrete/src/StyleCustomizer/Style/ColorStyle.php
- concrete/views/dialogs/area/design.php
- concrete/views/dialogs/block/design.php
> Misc Fixes 06/13

- concrete/single_pages/dashboard/extend/update.php
> define $mi for php8.x

- concrete/blocks/core_area_layout/form.php
- concrete/blocks/document_library/controller.php
- concrete/controllers/panel/page/versions.php
- concrete/src/Page/Collection/Version/EditResponse.php
- concrete/src/User/Group/Group.php
- concrete/views/panels/page/versions.php
See individual commits.
Also fix #9401
> Misc. Fixes 06/14

- concrete/single_pages/dashboard/extend/update.php
> [v9] Make the version history nicer

- concrete/single_pages/dashboard/extend/update.php
Followed by https://github.com/concretecms/concretecms/pull/10697
> [v8] Make the version history nicer

- concrete/src/Attribute/ObjectTrait.php
- concrete/src/Page/Collection/Collection.php
It was my mistake, I cherrypicked a commit that has a scalar type hint on #10378
> [V8] Fix to work with PHP 5.6

- concrete/elements/custom_style.php
closes #10708
Essentially we were sending false/true to the server it wants 0/1
> [v9] fix #10708 saving hideOnDevices

- concrete/src/Page/Page.php
> Misc fixes 06/22

- concrete/controllers/single_page/dashboard/system/notification/events.php
- concrete/single_pages/dashboard/system/notification/events.php
- concrete/src/Notification/Events/MercureService.php
Mercure is now working in the develop branch but there were some limitations in how it was configured. This should help address more advanced configuration use cases.
> Mercure updates

- concrete/src/Page/Page.php
Adds an 'on_get_page_wrapper_class' event to provide an opportunity for altering the CSS classes in the page wrapper.
Implement enhancement  https://github.com/concretecms/concretecms/issues/10731
> Add 'on_get_page_wrapper_class' event

- concrete/src/Page/Page.php
See https://github.com/concretecms/concretecms/pull/10765
> Add 'on_get_page_wrapper_class' event for 8.5.x

- concrete/src/Application/Service/UserInterface.php
full-width tabs are not always desirable.
> ability to pass class to `tabs` method

- concrete/single_pages/dashboard/reports/page_changes.php
- concrete/single_pages/dashboard/system/calendar/colors.php
- concrete/single_pages/dashboard/system/multilingual/page_report.php
> Fix/minor UI fixes

- concrete/bedrock/documentation/components.xml
- concrete/composer.json
- concrete/config/install/packages/atomik_full/content.xml
- concrete/src/Page/Theme/Documentation/Installer.php
Bug fixes with theme documentation in packaged themes
Sample content fixes in theme documentation
Fixed bug with BC and commerceguys/addressing by locking onto a particular version
> Misc fixes 0808

- concrete/src/Cache/Adapter/ZendCacheDriver.php
- tests/tests/Cache/Driver/ZendCacheDriverTest.php
fixes #10792
I'll make an another PR for v9 soon
> [V8] Fix ZendCacheDriver does not set life time properly

- concrete/src/Cache/Adapter/LaminasCacheDriver.php
- tests/tests/Cache/Driver/LaminasCacheDriverTest.php
> [V9] Fix LaminasCacheDriver does not set TTL properly

- concrete/blocks/event_list/controller.php
- concrete/blocks/event_list/form.php
- concrete/src/StyleCustomizer/Style/ColorStyle.php
> Misc Fixes 08/16

- concrete/elements/dashboard/express/detail_navigation.php
needs this [PR](https://github.com/concretecms/bedrock/pull/246) to be merged first.
> adding `nav-sidebar` class to express page

- concrete/single_pages/dashboard/system/permissions/workflows.php
- concrete/src/Editor/LinkAbstractor.php
- concrete/src/Workflow/BasicWorkflow.php
> Misc Fixes 09/07

- build/assets/themes/dashboard/js/file-manager/file-manager.js
- concrete/config/concrete.php
- concrete/controllers/backend/file.php
- concrete/controllers/frontend/assets_localization.php
- concrete/elements/files/search/menu.php
- concrete/single_pages/dashboard/files/search.php
- concrete/src/File/Upload/Dropzone.php
- concrete/views/dialogs/file/import.php
- concrete/views/dialogs/file/search.php
Fix #10500
Please let me know if this approach is ok: in this case I'll also add a dashboard page to configure dropzone stuff.
> Restore chunked upload

- concrete/attributes/page_selector/controller.php
This solves the issue outlined [here ](https://github.com/concretecms/concretecms/issues/10836) in v9
> Add missing search features to the page_selector attribute

- concrete/controllers/single_page/download_file.php
Fixes #10869
If this PR is accepted, I'll create same PR for v8 branch too.
> [V9] Fix #10869

- concrete/controllers/single_page/download_file.php
> [V8] Fix #10869

- concrete/src/File/Import/ImportOptions.php
This is the same fix which was applied to v9 in #8815 but against the 8.5.x branch
> fixes #8814 for 8.5.x

- concrete/controllers/single_page/dashboard/users/search.php
- concrete/elements/dashboard/users/header.php
- concrete/single_pages/dashboard/users/search.php
> Add "Password Reset" button to the user details page

- concrete/controllers/frontend/assets_localization.php
In Italian (and many other languages too), adjectives change depending on the subject they are referring to.
For example:
| English | Italian | French |
|---|---|---|
| Alice is beautiful | Alice è bella | Alice est belle |
| Bob is beautiful | Bob è bello | Bob est beau |
So, when we have to translate adjectives alone, we need to know the context where they are used.
> Add subject to password strength adjectives

- concrete/blocks/gallery/view.php
Check if the image is null (the file is deleted) and skip it if so. Otherwise a page with a gallery with a single deleted image throws an irreparable exception.
> Handle deleted file

- concrete/controllers/dialog/user/search.php
- concrete/views/dialogs/user/search.php
Companion of https://github.com/concretecms/bedrock/pull/253
> Add an option to the user picker to hide usernames

- concrete/src/Tree/Node/Type/Group.php
- concrete/src/User/Group/Group.php
I'm going to implement a Group selector (like the User selector), and I'd need this PR (as well as #10963)
> Add more group details to the data we send to clients

- concrete/src/File/FileServiceProvider.php
At the moment it's not possible to resolve to an instance of a class implementing ThumbnailerInterface with DI.
Let's fix it.
> Make it possible to use DI to get an instance of ThumbnailerInterface

- concrete/elements/header_required.php
This PR prevents XSS in the microsoft application tile color.
> Sanitize microsoft application tile color

- concrete/elements/dashboard/navigation/breadcrumb.php
This PR fixes the formatting in the breadcrumbs element and adds output sanitization for item names and urls.
> Clean up dashboard breadcrumbs element

- concrete/controllers/single_page/dashboard/system/files/image_uploading.php
- concrete/controllers/single_page/dashboard/system/multilingual/page_report.php
- concrete/single_pages/dashboard/system/basics/icons.php
This PR fixes a few instances of unsanitized output in the dashboard
> Sanitize output in dashboard pages

- build/assets/themes/concrete/js/main.js
- build/assets/themes/dashboard/js/main.js
Same as https://github.com/concretecms/bedrock/pull/259
Fix https://github.com/concretecms/concretecms/issues/10944
> Avoid double tooltip initialization

- composer.json
- composer.lock
- concrete/composer.json
- concrete/controllers/single_page/dashboard/system/api/settings.php
- concrete/single_pages/dashboard/system/api/integrations/form.php
And other miscellaneous API fixes in PHP 8.
> Putting openapi zircote library in the right place

- concrete/blocks/form/controller.php
> Fix #11001

- concrete/authentication/concrete/controller.php
- concrete/src/Authentication/Type/ExternalConcrete5/ExternalConcrete5Service.php
- concrete/src/Error/Handler/ErrorHandler.php
Version 8.5.11 is still broken on PHP 5.5/5.6.
> [V8] Fix PHP 5 compatibility

- concrete/single_pages/dashboard/files/details.php
This commit fixes the XSS on Tags which was occurred due to insufficient sanitization on user input Tag.
> Fix XSS on Tags H1 #1767949

- concrete/blocks/form/mini_survey.php
- concrete/single_pages/dashboard/reports/forms/legacy.php
It's being called statically in concrete/controllers/single_page/dashboard/reports/forms/legacy.php
Fix #11019
> Make MiniSurvey::loadQuestions() static

- concrete/single_pages/dashboard/system/basics/multilingual/update.php
| Before | After |
|---|---|
| ![before](https://user-images.githubusercontent.com/928116/197860651-722887af-93be-4ebe-8a94-626acbf1a1a0.png) |  ![after](https://user-images.githubusercontent.com/928116/197860684-3437ddde-25d8-4481-a062-bc9f9bc42020.png) |
> Fix UI of "Update Languages" dashboard page

- concrete/attributes/select/controller.php
> Fix issue under PHP8 when saving select/option attributes with no selected values

- concrete/elements/workflow/edit_type_form_required.php
> wrong params order in the call of View::element(), under elements\workflow

- concrete/controllers/panel/add.php
> Fix #10985

- concrete/src/Express/Form/Control/Validator/AssociationControlValidator.php
https://github.com/concretecms/concretecms/issues/11058
[*Check these before submitting new pull requests*
- [ x ] I read the __guidelines for contributing__ linked above. My pull request conforms to the coding style guidelines described within.
> express forms association validation when required

- concrete/controllers/panel/page/design.php
> Fix #11100

- concrete/src/Database/Connection/Connection.php
> Fix installing using MariaDB 10.10+

- concrete/blocks/document_library/controller.php
This is a fix for #11120  to make sure the Document Library block orders files by File Set, if selected in the settings. 
If multiple file sets are used the list is ordered by file set ID first then by file order.
This works pretty well when displaying files belonging to any file set.
Obviously when displaying files belonging to all file sets, results may vary as the file set order will probably be of only one of the file sets.
> [V9][Bug] Order by FileSet not working in Document Library Block

- concrete/src/Job/Job.php
This issue was discussed in H1 #1772230
> Use triple equals to validate job token

- concrete/authentication/concrete/controller.php
- concrete/blocks/form/controller.php
- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/users/search.php
- concrete/controllers/single_page/register.php
- concrete/single_pages/dashboard/system/mail/addresses.php
- concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
- concrete/src/Mail/MailServiceProvider.php
- concrete/src/Mail/SenderConfiguration/Entry.php
- concrete/src/Package/StartingPointPackage.php
- concrete/src/Updater/Migrations/Migrations/Version20221219220600.php
- concrete/src/Workflow/BasicWorkflow.php
- concrete/src/Workflow/Request/ActivateUserRequest.php
> Default sender address: switch from admin's email to concrete.email.default.address

- concrete/src/Navigation/Breadcrumb/PageBreadcrumbFactory.php
> Support replace_link_with_first_in_nav attribute in breadcrumb

- concrete/elements/express/search/menu.php
#11156 as the title already says ;)
> fixed issue#11156: exception cause of lower permission

- concrete/elements/conversation/message/pending.php
- concrete/single_pages/dashboard/users/search/edit.php
- concrete/src/Block/BlockController.php
- concrete/src/Conversation/Command/AbstractConversationMessageCommand.php
- concrete/src/Conversation/Command/HandleNewConversationMessageCommand.php
- concrete/src/Conversation/Command/HandleNewConversationMessageCommandHandler.php
- concrete/src/Conversation/Command/SendEmailsToConversationMessageSubscribersCommand.php
- concrete/src/Conversation/Command/SendEmailsToConversationMessageSubscribersCommandHandler.php
- concrete/src/Conversation/Message/Message.php
- concrete/src/Entity/Express/Control/TextControl.php
- concrete/src/Entity/Notification/NewConversationMessageNotification.php
- concrete/src/Notification/ContextMenu/Item/ArchiveItem.php
- concrete/src/Notification/View/NewConversationMessageListView.php
- concrete/src/Notification/View/NewFormSubmissionListView.php
- concrete/src/Notification/View/StandardListView.php
> Misc Fixes 01/14

- concrete/src/Attribute/Category/AbstractCategory.php
Just adding a missing cache lock.
> add cache lock to fix potential race condition

- concrete/mail/user_register.php
Adding some missing echoes in `concrete/mail/user_register.php`
> add missing echoes

- concrete/src/Localization/Locale/Service.php
Flush happens on line 102/103.
> remove unnecessary flush

- concrete/src/Permission/Access/Entity/GroupEntity.php
- concrete/src/Permission/Access/Entity/GroupSetEntity.php
There can be instances where a user has not been put in groups, so this just checks that there are actually groups before getting permissions.
> check in case user hasn't been put into any groups

- concrete/authentication/community/controller.php
> [V8] Fix member profile URL

- concrete/single_pages/dashboard/pages/containers/view.php
This commit fixes XSS on container name.
> Fixed: XSS on container name [H1: 1866111]

- concrete/blocks/core_page_type_composer_control_output/view.php
- concrete/blocks/horizontal_rule/view.php
- concrete/src/Attribute/Key/Component/KeySelector/ControllerTrait.php
- concrete/src/Page/Type/Composer/OutputControl.php
- concrete/src/Updater/Migrations/Migrations/Version20210725000000.php
> Misc fixes 0209

- concrete/config/concrete.php
- concrete/src/Entity/Attribute/Key/Key.php
- concrete/src/Entity/Attribute/Value/Value/AddressValue.php
- concrete/src/Entity/Page/PagePath.php
- concrete/src/Updater/Migrations/Migrations/Version20230127095217.php
We've found that these additional indexes have helped out query performance.
> Additional indexes

- concrete/src/Attribute/Category/AbstractCategory.php
- concrete/src/Attribute/Category/AbstractStandardCategory.php
- concrete/src/Attribute/Category/EventCategory.php
- concrete/src/Attribute/Category/ExpressCategory.php
- concrete/src/Attribute/Category/FileCategory.php
- concrete/src/Attribute/Category/PageCategory.php
- concrete/src/Attribute/Category/SiteCategory.php
- concrete/src/Attribute/Category/SiteTypeCategory.php
- concrete/src/Attribute/Category/UserCategory.php
- concrete/src/Attribute/ObjectTrait.php
Before
After
Reduced 40 duplicated SQL queries
> Performance Improvement: Avoid getting same attribute values multiple times

- concrete/single_pages/dashboard/boards/boards.php
- concrete/single_pages/dashboard/boards/designer.php
- concrete/single_pages/dashboard/users/group_types.php
run a few outputs through the sanitization method
> Santitize display

- concrete/blocks/core_container/controller.php
Fixes #11238
The codes I added are picked from core area layout block
> Make containers enable to cache its output

- concrete/blocks/event_list/view.php
Ref. https://github.com/concretecms/concretecms/issues/11263#issuecomment-1459712426
> Cleanup view of event_list block type

- composer.json
- composer.lock
- concrete/composer.json
See https://github.com/concretecms/dependency-patches/commit/850c21a1ab5925900bc4be9b764600967a41380b
> Fix name of dependency-patches composer package

- concrete/controllers/single_page/dashboard/users/search.php
- concrete/elements/dashboard/users/header.php
Minor wording change to not assume the user's gender when resetting their password
> wording update

- concrete/blocks/file/controller.php
> Fix saving "Force Download" in File block

- concrete/src/Page/Page.php
> Misc. Fixes 04/17

- concrete/blocks/tags/controller.php
> Always define $items in Tags block controller

- concrete/controllers/single_page/dashboard/blocks/types.php
- concrete/src/Search/ProviderInterface.php
- concrete/src/Search/Query/QueryFactory.php
Fix #11371
...but please remark that I've never used this search query stuff: is there a method to build the querystring parameters from a Query instance? I couldn't find it...
> Fix View pages using a specific block type

- concrete/blocks/social_links/view.php
Added "list-inline-item" class to the li on social links so they float inline on Bootstrap 5 themes
Closes #11415
> Added "list-inline-item" class to social links

- concrete/blocks/feature/controller.php
- concrete/blocks/feature/db.xml
- concrete/blocks/feature/form.php
- concrete/blocks/feature/view.php
- concrete/blocks/feature_link/controller.php
- concrete/blocks/feature_link/db.xml
- concrete/blocks/feature_link/edit.php
- concrete/blocks/feature_link/view.php
- concrete/config/concrete.php
- concrete/src/Updater/Migrations/Migrations/Version20230503095900.php
This PR will allow users to add images to the Feature and Feature Link blocks.
> Update Feature and Feature Link Blocks to add images

- concrete/src/Search/Column/Set.php
- tests/tests/Search/Column/SetTest.php
This PR allows adding a column at a specific position (before or after a key) of a column set.
> Add ability to column at a specific position

- concrete/controllers/panel/add.php
This addresses parts of #11235 
This PR allows ordering blocks per sets alphabetically in the block add panel.
This solution doesn't touch the DB calls as they would become overly complicated. It simply re-orders the block types arrays as needed. It's also very fast.
The code expects a `concrete.block_add_panel_order.alpha` config key.
If any is found, its value can be either **boolean True or an array of Block Sets' handles.**
If true all sets will be ordered. Otherwise only the listed sets will be ordered.
**Order only the Multimedia, Navigation, and Form Reform block sets alphabetically.**
```
return [
'block_add_panel_order' => [
'alpha' => [
'multimedia',
'form_reform',
'navigation',
],
],
];
```
**Order all block sets alphabetically.**
```
return [
'block_add_panel_order' => [ …
```
> Add alphabetical ordering to blocks in the add panel

- concrete/attributes/topics/controller.php
Update regex in topics attribute controller so that multiple values are correctly imported.
Fix issue https://github.com/concretecms/concretecms/issues/11480
> Fix Topics Attribute https://github.com/concretecms/concretecms/issues/11480

- concrete/controllers/single_page/dashboard/reports/health.php
- concrete/controllers/single_page/dashboard/welcome/health.php
- concrete/single_pages/dashboard/reports/health.php
- concrete/single_pages/dashboard/welcome/health.php
...otherwise they'll always be in English
> Use the Date service to output site health report dates

- concrete/elements/files/edit/image_editor/toast.php
Here's a sample session, where you can clearly see that editing at full screen is much much easier
https://github.com/concretecms/concretecms/assets/928116/c4fc3460-e767-4e91-9a16-95bed6ed5a1a
> Add full screen to image editor

- concrete/src/Command/Task/Runner/Context/ContextFactory.php
See for example https://3v4l.org/ZF82M
> Fix building NullOutput when running tasks

- concrete/single_pages/dashboard/system/environment/geolocation.php
|: Before :|: After :|
|---|---|
| ![immagine](https://github.com/concretecms/concretecms/assets/928116/0734f982-45c5-44da-aaa9-86fef96ea62e) | ![immagine](https://github.com/concretecms/concretecms/assets/928116/cc678e1a-0065-48a5-943b-7db91a8defa5) |
> Fix highlighting currently active geolocation library

- concrete/blocks/feature_link/controller.php
- concrete/blocks/hero_image/controller.php
- concrete/blocks/top_navigation_bar/controller.php
- concrete/blocks/top_navigation_bar/edit.php
- concrete/config/install/packages/atomik_full/content.xml
> Misc. Fixes 06/23

- concrete/blocks/image_slider/controller.php
- concrete/src/Block/BlockController.php
Adding support for content replacement/rich text content columns on import; Only running columns through the importer replacement if they should be
> Content Import Tweaks

- composer.lock
Just a minor update to improve PHP 8.2 compatibility (see the [changelog](https://github.com/PrimalPHP/Color/compare/1.0.1...1.0.2)).
> Upgrade primal/color

- concrete/src/Area/Layout/PresetLayout.php
Possible fix for https://github.com/concretecms/concretecms/issues/11528
> Fix https://github.com/concretecms/concretecms/issues/11528

- concrete/src/Foundation/EnvironmentDetector.php
PR intended to resolve this [issue](https://github.com/concretecms/concretecms/issues/11423)
> Fixes #11423

- build/package-lock.json
Affected of this project `concretecms/concretecms` are vulnerable to Improper Input Validation due to the improper handling of URLs by the url.parse() function. When new URL() throws an error, it can be manipulated to misinterpret the hostname. An attacker could exploit this weakness to redirect traffic to a malicious site, potentially leading to information disclosure, phishing attacks, or other security breaches.
**PoC**
```js
let url = 'http://[localhost]/admin';
try{
new URL(url); // ERROR : Invalid URL
}catch{
url.parse(url); // -> http://localhost/admin
}
let url = 'http://attacker.domain*.allowed.domain:a';
try{
new URL(url); // ERROR : Invalid URL
}catch{
url.parse(url); // -> http://attacker.domain/*.allowed.domain:a
}
```
Below is part of follow-redirects's index.js code.
``` …
```
> Update and Fixed Improper Input Validation Follow Redirects improperly handles URLs in the url.parse() function
