concretecms/concretecms

concrete/src/Editor/CkeditorEditor.php, concrete/src/Editor/EditorServiceProvider.php
The current version of the `EditorServiceProvider` has two issues that are resolved by this pr:
1. When using multisite the dashboard page to edit plugins doesn't actually save for the site you're editing
2. When no custom plugins have been selected for a site other than default, no default plugins are selected.
=> Fix editor plugins when using multisite

concrete/controllers/single_page/dashboard/users/groups/message.php, concrete/src/User/PrivateMessage/Limit.php, concrete/src/User/UserInfoRepository.php
This PR adds two new methods to the `UserInfoRepository` class to facilitate getting all users:
- `->all()` Get all user info objects
- `->getByUserEntity()` Get the UserInfo object from an entity
And one static method to the `Limit` class to allow disabling limit checks:
- `::setEnabled(false)`
=> Add the ability to private message all groups at once

concrete/src/Entity/Express/Entry.php, concrete/src/Express/Export/EntryList/CsvWriter.php, tests/tests/Express/Export/EntryList/CsvWriterTest.php
We can add an author to the Express entries since 8.5.0, but it is not included in the exported CSV file.
https://github.com/concrete5/concrete5/pull/7023
Let's add the author column on CSV export.
=> Add the author column on express entries CSV export.

concrete/src/Site/Service.php, concrete/src/User/PostLoginLocation.php, tests/tests/User/PostLoginLocationTest.php
Before this PR logging into a multisite site other than the default site caused you to be redirected to the default site. With this change, the fallback redirect is determined using the active site rather than the active page.
=> Make sure we are resolving the homepage from the active site rather than the active page

concrete/config/concrete.php, concrete/config/install/base/single_pages/dashboard.xml, concrete/src/Updater/Migrations/Migrations/Version20190405171430.php
When you tried clean install concrete5 8.5.0 & 8.5.1, Password Requirement page doesn't get installed.
You forgot to add installation xml page.
Adding additional migration script for 8.5.0 & 8.5.1 fresh-installed site.
I didn't bother to add downgradeSchema(). Which is also set in `Version20181222183445.php`.
=> Password Requirements dashboard page was not installed via 8.5.0 & 8.5.1 fresh install

concrete/controllers/single_page/download_file.php
Hi guys,
After many evaluations that we made  for our websites with some SEO Tools i saw that they complain about those 302 file redirects. As i researched this thema i am convinced that in this case of redirect we should use 303 instead of 302. 
Any input is welcome here.
=> set 303 as standard redirect status code for download_file url

concrete/views/oauth/consent/simple.php
Before, when using an external concrete5 auth type and being redirected to the user portal:
After:
=> Add openID scope to listing of scopes

concrete/src/Install/Preconditions/DatabaseCharsetCollation.php
As discussed in https://github.com/concrete5/concrete5/pull/7674#issuecomment-502803377
> The database does **not** have a complete support for all the Unicode characters.
=> Installation precheck - Fix typo in charset collation exception

concrete/src/Session/SessionValidator.php
Since #7679, we can use the `getActiveSession` method of `SessionValidator` to get the session if it's already started.
This is very handy when we have to read a value from the session, without starting the session if it's not already started. Here's a sample code:
```php
function getValueFromSession()
{
$session = $this->sessionValidator->getActiveSession();
return $session === null ? null : $session->get('key');
}
```
When writing the session, we always need the session instance, and start it. This implies that service classes currently need the `Application` dependency, because we have to write some code like this:
```php
function getValueFromSession()
{
$session = $this->sessionValidator->getActiveSession();
return $session === null ? null : $session->get('key');
}
function …
```
=> Let SessionValidator::getActiveSession() start the session

concrete/src/Page/Controller/DashboardCalendarPageController.php
array_filter doesn't change keys so $calendars[0] can be null.
For example if a user doesn't have permissions on the first calendar, $calendar[0] is null and a null pointer exception is thrown.
=> Bugfix: Null pointer exception calendar dashboard

concrete/views/panels/details/page/composer.php
Previously the autosave could still launch once after the "publish" button has been clicked from the composer view.
This prevents that from happening.
This caused occasionally an extra page version to be created which is visible to the user because the "page is pending for approval" popup appears straight after the page has been published.
=> Disable the autosaver completely when publishing through composer

composer.json, composer.lock
When sending emails with the `intl` PHP extension enabled, we have these deprecation warnings:
- `idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated`
- `idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated`
I've updated the dependency patches package to fix this issue: see https://github.com/concrete5/dependency-patches/releases/tag/1.3.0
=> Fix "INTL_IDNA_VARIANT_2003 is deprecated" warning

concrete/blocks/desktop_app_status/controller.php, concrete/blocks/desktop_app_status/view.php, concrete/config/concrete.php, concrete/src/Marketplace/Marketplace.php, concrete/src/Updater/Update.php
There are cases when we'd like to disable upgrading the core and/or packages from within the dashboard (for example, as discussed in [C5 Dev Round Up #1](http://www.youtube.com/watch?v=GLH0RFCAIc0&t=30m37s), upgrading via the dashboard should be avoided when using composer).
=> Inhibit dashboard updates

concrete/src/Mail/Service.php
When sending text/html emails, we currently use the "8-bit" transfer encoding.
This works 99% of times, but sometimes (when there are long lines), a new line is automatically inserted in a quite random place. And that may break HTML code (for example, a newline may occur in the middle of an `href` attribute).
So, what about using the quoted-printable transfer encoding?
=> Set quoted-printable encoding for outgoing emails

concrete/blocks/page_attribute_display/controller.php
this change has the page attribute block search the templates directory to see if there is a template that matches the selected attribute's handle. If so, this template will be used automatically.
Note: this currently does not work with template in a folder.
Example:
selected attribute handle: `my_attribute`
works:
`/application/blocks/page_attribute_display/templates/my_attribute.php`
does not work:
`/application/blocks/page_attribute_display/templates/my_attribute/view.php`
There have been quite a few times where I have had to create a template for a specific attribute and then select it each time an instance of the block is needed. In my opinion, it would be handy (and reasonably logical) to have a template that matches the selected attribute handle automatically applied if no custom …
=> allow page attribute block to use template for attribute

concrete/src/Updater/Migrations/Migrations/Version20150515000000.php, concrete/src/Updater/Migrations/Migrations/Version20170118000000.php
- Migration 20150515000000 may call `deleteBlock`, which may require an updated `PageTypeComposerOutputBlocks` table structure (otherwise we may have an `Unknown column 'cvID' in 'where clause'` when running the `delete from PageTypeComposerOutputBlocks where cID = ? and cvID = ?` query)
- Migration 20170118000000 should update the `PageTypeComposerOutputBlocks..cvID` field only once (since that migration is marked as repeatable, users may run it more than once
=> Fix migrations 20150515000000 and 20170118000000

concrete/config/app.php, concrete/elements/footer_required.php, concrete/elements/header_required.php
A couple of fixes here:
- the account menu requires jQuery: let's add it to the `core/account` asset group
- we include the `core/account` asset group if (1) the user is registered  
but
we enable when (1) the user is registered, (2) the theme or the configuration doesn't disable it, and (3) we are not in the dashboard
We should include the `core/account` asset group only if use it.
EDIT: fix #4588
=> Account menu fixes

concrete/src/Site/ServiceProvider.php, tests/tests/Site/SiteTest.php
The site service provider defines `'site'` and `'site/type'` as singletons.
BTW, the `Concrete\Core\Site\Service` and `Concrete\Core\Site\Type\Service` mapped classes are not singletons (which is bad when we use dependency injection).
So, what about making the classes as singletons, and `'site'`/`'site/type'` as aliases to them? That way, everything will be a singleton.
=> Site services: let the classes be singletons

concrete/attributes/image_file/controller.php, concrete/attributes/image_file/form.php
When using a File/Image attribute configured to use an HTML file input, we have the issue described in #4678 and #5599: when we edit an existing entity, we don't have a way to keep the previously selected file.
What about asking users what they want to do in this case?
Fix #4678
Fix #5599
=> Keep existing file attribute value when using HTML file input

concrete/src/Page/Page.php
This PR allows Page::getSiteHomePageID to use the default site and return its home page id.
Currently when upgrading from 5.7 the migrations will fail as it tries to get the locale home page id as they don't exist when trying to install the new version 8 Pages. They are installed after, since getSiteHomePageID should generally return something, its best to return the default site HomePageID rather than HOME_CID/1
=> Allow Page::getSiteHomePageID to use default site (fixes upgrade from 5.7)

concrete/routes/api/file.php
Since @aembler removed this function this route no longer exists. So it should be removed but...
...I'll try to find time to add back List Files in with proper functionality, rather than the half baked list before.
=> Remove unused route in Files API

.travis.yml
*nightly* now points to PHP 8.
So, in order to run TravisCI tests against PHP 7.4 we have to explicitly declare it.
=> Test with PHP 7.4

concrete/src/Form/Context/Registry/ControlRegistry.php, tests/assets/Express/Form/Control/View/TestView.php, tests/tests/Form/Context/Registry/ControlRegistryTest.php
When overriding the first form control in the registry, it does not currently work because of the check that does not consider that the index can have a zero value (.
This fixes that issue and adds some tests to ensure this bug does not reappear.
Example code to replicate this bug:
```php
$app = \Concrete\Core\Support\Facade\Facade::getFacadeApplication();
$registry = $app->make(\Concrete\Core\Form\Context\Registry\ControlRegistry::class);
$registry->register(
new \Concrete\Core\Express\Form\Context\FormContext(),
'express_control_attribute_key',
\Application\Express\Form\Control\View\AttributeKeyFormView::class
);
```
In order to get the example code working, you obviously need to define the `AttributeKeyFormView` class. The test included in this PR provides a more concrete example which …
=> Fix form context registry override

concrete/src/Block/View/BlockView.php, tests/assets/Block/weird_template.php, tests/tests/Block/BlockRenderTest.php
Some custom templates may change the block view's local scope variables as they are unaware what is happening "above" them. Changing the `$b` variable in particular inside the block templates is problematic as it will break the rendering of the block's edit controls (coming from the header/footer templates).
This happened to me personally when working with a custom template for the stacks block in which I was iterating through an array of blocks and storing them one-by-one in the `$b` variable. In this case, it was very hard to track down the bug as the edit view worked properly but just the edit controls pointed to the wrong block ID. Furthermore, this broke the "edit block" link which caused an error stating "Invalid Area" coming from here: …
=> Fix block templates that edit the scope variables within the block view

concrete/src/Form/Service/Form.php
The `select` method of the form service accepts arrays of arrays, building `<optgroup>` HTML elements.
What about extending this feature to the `selectMultiple` method?
=> Let selectMultiple accept arrays of arrays, building optgroup elements

concrete/attributes/number/controller.php, concrete/src/Entity/Attribute/Value/Value/NumberValue.php
Number attributes may contain `NULL` values, which is very different from `0`.
So:
1. we should let the system create `NULL` values (see 4345d33dc3f8942ff80bec0ecb65caa5e154f938)
1. we should display an empty value instead of `0` when the value is `NULL` (see 2728459aab9a00e4029d933eda79da448e518724)
=> Handling of NULL values for Number attributes

concrete/config/install/base/single_pages/dashboard.xml, concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php, concrete/single_pages/dashboard/system/permissions/trusted_proxies.php, concrete/src/Application/Service/UserInterface/Help/DashboardManager.php, concrete/src/Updater/Migrations/Migrations/Version20180920000000.php
We have a nice page to configure the trusted proxies, but we lacks a GUI to configure which headers should be trusted (so, that page is actually useless: you still have to manually set the `'concrete.security.trusted_proxies.headers` configuration key).
The result  of this PR will be:
- when using a proxy:  
- when NOT using a proxy:
=> Add GUI to configure trusted headers received by a proxy

concrete/config/app.php, concrete/config/concrete.php, concrete/src/Updater/Migrations/Migrations/Version20190507177700.php, concrete/src/Workflow/Type.php, concrete/src/Workflow/Workflow.php
This PR fixes the following issues with Workflow Types
Workflow's belong to a type that Belongs to a package, are not correctly added to that package. It means
When deleting Workflow Types it will not remove existing workflows, it instead just hides them. This means if you have any existing workflow progresses submitted. It will break the site. The order of the package get items was wrong for workflows (removed workflow types before workflows, would cause errors).
I've also removed legacy code from workflow/type.php
Change-log Text:
Fixed Issues when removing Custom Workflow Types
Fixed Issues when adding Workflows that have custom workflow types.
Refactored Workflow Types Class to use newer code.
=> Fixing issues when deleting Workflow Types

concrete/src/Package/Package.php
When a package installs attribute keys and attribute key sets, the sets will be empty.
That's because:
1. before the attribute keys, the code calls the "get attribute by handle" method, which stores in the request cache that there's no attribute with this handle
2. the attribute key is created
3. the attribute set is created
4. the code calls the "get attribute by handle" method to see if there's such attribute to be associated to the set. Since at point 1 we stored in the cache that the key doesn't exist, the attribute appears as non existing, so it's not added to the set
So, what about disabling the request cache when importing XML files?
=> Disable request cache when installing package XML contents

concrete/src/Backup/ContentImporter/Importer/Routine/ImportAttributeSetsRoutine.php
When we assign the attribute keys to the attribute sets via the dashboard, we are not allowed to add the same key to multiple sets.
What about forcing this in the "import from xml" procedure too?
=> Force attribute keys to be in one set only during import

concrete/config/concrete.php, concrete/config/install/base/single_pages/dashboard.xml, concrete/controllers/single_page/dashboard/system/environment/database_charset.php, concrete/single_pages/dashboard/system/environment/database_charset.php, concrete/src/Updater/Migrations/Migrations/Version20190520070000.php
At install time, concrete5 detects if we can use the `utf8mb4` character set (if not, we fall back to `utf8`).
This works great, but there are a couple of issues:
1. if at install time `utf8mb4` is not supported, but after MySQL is updated, `utf8mb4` may become usable
1. an SQL dump exported from a server that supports `utf8mb4` can be imported to a server that doesn't support it
In these cases, users may want/need to change the character set.
We already have the `c5:database:charset:set` CLI command, but not everybody can (or knows how to) use SSH.
So, what about adding a dashboard page to change the character set / collation?
=> Add dashboard page to change database character set / collation

concrete/src/Page/Page.php
I think it makes more sense than setting the linkname as url slug.
=> Set Name as URL-Slug for External Link

concrete/src/User/Search/Field/Manager.php
When using attributes grouped in sets, and filtering by one of these attributes, we may result in duplicated fields searched.
The reason of this is that the Search Field Manager adds the same attribute to more than one group, resulting in the same field detected as being filtered twice in the `getFieldsFromRequest` method.
=> Fix search with attributes in sets

concrete/blocks/form/controller.php
This pull request trims leading and trailing whitespace and commas from the "Send form submissions to email addresses" Legacy Form block form input.
When the "Send form submissions to email addresses" checkbox is checked in the Legacy Form block form, any leading or trailing commas will cause Zend Mail to throw an exception. Trailing commas are particularly hard to debug if you don't know what to look for.
**Email Address Input**
`test@test.com,`
**Error**
```
Zend \ Mail \ Exception \ InvalidArgumentException
Invalid address format
```
Zend\Mail\Exception\InvalidArgumentException 
…\vendor\zendframework\zend-mail\src\AddressList.php:94
**Email Address Input**
`,test@test.com`
**Error**
```
Zend \ Mail \ Exception \ InvalidArgumentException
',test' can not be matched against dot-atom …
```
=> Prevent leading/trailing commas from triggering errors in Legacy Form block 

concrete/src/Editor/LinkAbstractor.php, tests/tests/Editor/LinkAbstractorTest.php
The export method of the link abstractor has been broken by 06dcbdece84d087479db6e9730298525cc45164f.
This fixes that and adds some tests to assure this won't happen again.
=> Fix link abstractor export functionality

concrete/composer.json
Update composer.json to add PDO ext as dependency for project.
The purpose of this commit is to explicitly inform developers of any php ext dependencies.
=> Update composer.json to add PDO ext

concrete/controllers/backend/page/arrange_blocks.php, concrete/src/Permission/Key/AddBlockToAreaAreaKey.php, concrete/src/Permission/Response/AreaResponse.php
Consider this situation:
- enable advanced permissions
- login as a user that can edit pages and stacks, but not as the super user ID
- create a new stack
- add that stack to an area of the page
- move the stack to another area of the page
You'll see have the error message "You may not add Stack Display to area Main.", but the stack is shown as moved to the new area.
If you move the stack to another area again, you'll see the error message "Call to a member function getBlockTypeObject() on null".
There are three bugs here:
1. the user *is* authorized to move the stack
1. when the code detects an unauthorized access, it still moves the block if the source and/or the destination area is global
1. in the case the arrange operation fails, the UI doesn't reflect the actual arrangement saved in …
=> Fix arranging stacks in pages

concrete/js/build/core/app/search/base.js, concrete/js/build/core/app/search/preset-selector.js, concrete/js/build/core/file-manager/search.js
This pull request fixes the following issues:
Javascript console errors present when trying to submit, save or delete search presets.
Delete saved preset not actually reseting the search preset.
File search preset results being returned twice when created. (once with the response from created, then the result is submitted again).
It also adds the ability of other search presets (other than the file manager) to actually use the `SearchPresetCreated` event and update the results with the data received from the search preset saved
=> Fix Search Preset Console errors and Fix Reloading

concrete/blocks/page_list/controller.php, concrete/src/Routing/SystemRouteList.php
Currently the validation on save of the Page List block forces the slug for an RSS URL to be alphanumeric with underscores, not hyphens. This is at odds with the typical generated URLs used throughout the rest of Concrete5.
There may be a better way of checking the string then `alphanum($string, false, true)` (perhaps by validating the entire URL?) but this was a function from the same helper and seemed appropriate.
=> Updates the format of Page List RSS URL to alphanumeric with hyphens

concrete/config/coding_style.php
These files may contain literally everything, including invalid PHP files
=> Exclude test assets from the coding style

concrete/src/Page/PageList.php
filterByPageTypeID() comment had the wrong parameter `$cParentID`.
It was a bit confusing :)
=> PageList Class: very minor comment fix

concrete/src/Asset/Asset.php
Assets are burst out of Concrete5's own cache based on changing the version number.
The same should be true for the browser's cache. Relying solely on the package's version number is not enough. As an example, in my package Buttons Factory, I generate a CSS file and the asset version number is set dynamically.
This adds the version number, if any, to the string before obfuscating it so the asset will burst out of browser's cache if its version number changes.
=> Add asset version number to cache bursting query string

concrete/blocks/content/controller.php
Adds record to file usage for files that are linked in the content block from the file manager
https://github.com/concrete5/concrete5/issues/6867
=> Handle linked download files in update statistics in content block

concrete/attributes/textarea/controller.php
This is a fix for a really interesting issue that causes broken file links in textareas attributes when a page is edited.
**Steps to reproduce:**
1. Add a textarea attribute as richtext.
2. Add a link to file in this attribute
3. Save  page. (At this point you will have in your frontend a link like "{URL}/download_file/3/12")
4. Go again to edit mode and republish the page (no need to change anything).
5. At this point you will have a broken link like "{URL}/download_file/3/12/12"
This is because the LinkAbstractor keeps adding the current page id to the file link.
@aembler i think this is a really important issue that needs more eyes. Maybe it would be also useful a script that detects these broken links and fixes them. (If you think that this is necessary i can build an automated job …
=> Fixes issue with broken links to files in textarea(richtext) attribute

concrete/blocks/express_entry_list/controller.php
Default Express Entry List search functionality does not allow for searching for multiple fields simultaneously.  This was occurring even when first_name and last_name attributes were added to the search index.
Example: Searching for 'John Doe' does not return a result, while searching for either 'John' or 'Doe' does return results.
This fix is simply trimming the search parameters, exploding on white space, and using a loop to search for each keyword.
=> fix for #7971

.travis/rebuild-assets.sh
We already call `git add` when we detect changes in CSS/JS assets: that later call is useless.
=> rebuild-assets TravisCI job: don't call "git add --all ." more than necessary

concrete/blocks/express_form/controller.php
I'd be lieing if I said I fully understood what this was doing but it does seem to fix the issue. There might be a better way to use those values and ordering them ahead of this without having to go back to the manager but I'm not sure.
Fixes #7875
=> correcting ordering of question emailed

concrete/src/Error/ErrorList/Formatter/TextFormatter.php
When serializing errors represented by `UserMessageException` instances, we should keep just the message, not the whole stack trace of the error.
=> Show only the message when we have in case of UserMessageException

build/Gruntfile.js, concrete/config/app.php, concrete/controllers/backend/file.php, concrete/controllers/dialog/file/import.php, concrete/controllers/frontend/assets_localization.php, concrete/js/build/core/app/file-uploader.js, concrete/js/build/core/file-manager/search.js, concrete/views/dialogs/file/import.php
This is a fix for #7916 alternative to #7921
We basically have a new JavaScript global object (`ccm_fileUploader`) that we can use to upload files via Dropzone.
When we have the file manager, we tell `ccm_fileUploader` to use the whole page as a drop zone, without a place where upload progress should be reported (we'll use only NProgress).
When we open the `Add Files` dialog, we (re)initialize the Dropzone, so that upload progress is reported in that dialog (but the drop zone is still the whole page).
When we close the  `Add Files` dialog, we (re)initialize the Dropzone as it was before opening the dialog.
=> Refactoring of the way dropzone works

concrete/src/Backup/ContentImporter/Importer/Routine/ImportSinglePageStructureRoutine.php
Essentially this is what I was doing in #7912 but I broke the tests, so re-worked it and then it didnt work on the 5.7 upgrade at a different part.
So now when importing single pages it will use the site default if it cant get the relevant site tree from the page object.
Also removed the unused category declaration
=> 5.7 Upgrade FIX: Use default site object when importing single pages

concrete/js/build/core/app/file-uploader.js
This fixes the issue reported at https://github.com/concrete5/concrete5/pull/7985#issuecomment-510644456
PS: #7990 is required to actually update the repository with this new built asset.
=> Fix uploading multiple files via drag-and-drop

concrete/blocks/calendar/controller.php
Proposal to fix #7993 
When creating long events (multiple days) that begin in one month and end in another, they are only displayed on the month of the beginning day.
Solution : the events have to _end after_ the end of the period, instead of _starting after_ the beginning of the period.
=> FIX long events were not properly fetched

concrete/css/build/vendor/font-awesome/path.less
We are experiencing issues with old versions of IE and FontAwesome, looks like the problem is the query string in the path.
=> Removing query string from FontAwesome font paths, this fixes IE issues

concrete/blocks/express_entry_detail/controller.php, concrete/blocks/page_list/controller.php, concrete/src/Url/SeoCanonical.php, concrete/src/Url/UrlServiceProvider.php
This pull request includes:
* Mark SeoCanonical helper as a singleton
* Make it enable to append path arguments to canonical URL
* Append block action parameters to canonical URL from some block types
See also #7740
=> Prevent Express entry detail pages are ignored from search engines

composer.json, composer.lock
Changelog:
- [1.3.0 → 1.4.0](https://github.com/concrete5/dependency-patches/releases/tag/1.4.0)
- [1.4.0 → 1.5.0](https://github.com/concrete5/dependency-patches/releases/tag/1.5.0)
=> Upgrade dependency patches to version 1.5.0

concrete/views/dialogs/file/import.php
Fix #8010
We need to manually add the message because now the drop zone is the whole page and not just the area in the "Add Files" dialog (so [this check](https://github.com/enyo/dropzone/blob/v5.3.0/dist/dropzone.js#L1190) now fails because `this.element` is `body` and not the dropzone `form`).
=> Add back "Drop files here or click to upload." to drop zone

concrete/src/Editor/CkeditorEditor.php, concrete/src/Editor/EditorServiceProvider.php
This PR fixes some issues with #7871. Instead of trying to track the `selected_hidden` values separately, let's just store them in the `selected` array when you configure them in the dashboard.
=> Remove selected_hidden juggling, just merge them into selected plugins

concrete/src/Localization/Service/AddressFormat.php, tests/tests/Localization/Service/AddressFormatTest.php
As reported at https://github.com/concrete5/concrete5/issues/7943#issuecomment-516224778, the Japanese address formats differently which means the address object also needs to know its locale.
This fixes the linked issue reported by @hissy.
=> Fix Japanese address formatting

concrete/src/Form/Service/DestinationPicker/EmailPicker.php
We have a pretty nice email validator class: what about using it instead of the vendor one?
This will simplify upgrading the vendor email validator when we'll switch to concrete5 version 9.
=> Use the core email validator instead of the vendor one

concrete/controllers/dialog/block/aliasing.php, concrete/src/Block/Block.php, concrete/views/dialogs/block/aliasing.php
There are some cases where we don't want to update old blocks and we need only to add new ones.
=> PageTypeDefaults::SetupOnChildPages: Make Update forked blocks optional

concrete/elements/pages/search.php, concrete/src/Page/Search/Field/Field/IncludePageAliasesField.php, concrete/src/Page/Search/Field/Manager.php, concrete/src/Page/Search/Result/Item.php, concrete/src/Page/Search/SearchProvider.php
It's important to include page aliases within search result, otherwise we can't choose page aliases from page selector espacially for Big sites where isn't possible to find the page from Regular Sitemap
=> Include page aliases in page search result

concrete/elements/attribute/editable_attribute.php, concrete/js/build/core/editable-field/container.js, concrete/src/Attribute/CustomNoValueTextAttributeInterface.php
When we render attributes without a value, we always display `None`.
What about letting attribute controllers provide a different text?
Demo:
=> Let attribute controllers define the "no value" text

concrete/src/Console/Command/PhpCodingStyleCommand.php, concrete/src/Support/CodingStyle/PhpFixerOptions.php, concrete/src/Support/CodingStyle/PhpFixerRuleResolver.php, concrete/src/Support/CodingStyle/PhpFixerRunner.php
What about letting users to specify the minimum PHP version that the code should support?
For example, this would be useful when checking/fixing code of packages that are compatible with concrete5 version 5.7 (that supported PHP 5.3), where we can't use short echo tags, __DIR__ constant, short array syntax, ...
=> Allow specify the PHP version for coding style

concrete/src/Support/Symbol/MetadataGenerator.php
#8011 introduced the really handy `app()` global function: what about adding it to the `.phpstorm.meta.php` file generated by the `c5:ide-symbols` CLI command?
=> Add app() to PHPStorm metadata file

concrete/routes/rss.php
The name of the parameter passed to
Concrete\Controller\CalendarFeed::view is `calendar_id`, so `identifier`
is not being passed. Additionally, passing a non-numeric value throws
an exceptions, so adding `setRequirements` back will validate the
input. It was taken out when this was refactored in [20eb23ca339](https://github.com/concrete5/concrete5/commit/20eb23ca33948bda4b49f8a063b627c12fc0f17c#diff-85b456d955834f4fda0553a19acaa95aR658) (line 658).
=> Fix: calendar feed parameter and validation

phpunit.xml, tests/tests/Http/HttpClientTest.php
We have some tests that performs remote URL calls, and are marked as skipped unless we define a `CONCRETE5TESTS_TEST_REMOTE_URI` environment variable.
This makes the output of phpunit more verbose than necessary, since it displays a few tests marked as skipped (because the above variable is not set).
So, what about excluding those tests by default?
=>  Exclude "online" tests by default

concrete/controllers/single_page/dashboard/system/mail/method.php, concrete/single_pages/dashboard/system/mail/method.php
How about allowing users to enable/disable email sending from the dashboard?
**Before**
**After**
=> Allow email sending enable/disable from the dashboard

concrete/src/User/UserInfo.php
This pull request fixes below error when deleting a user who is an owner of express entries.
Error message:
```
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException thrown with message "An exception occurred while executing 'DELETE FROM Users WHERE uID = ?' with params [4]:
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`concrete5`.`expressentityentries`, CONSTRAINT `FK_B8AE3531FD71026C` FOREIGN KEY (`uID`) REFERENCES `Users` (`uID`))"
Stacktrace:
#42 Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException in /path/to/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
#41 Doctrine\DBAL\Driver\AbstractMySQLDriver:convertException in …
```
=> Fix error on delete user who has express enties

concrete/attributes/select/option.php
I think these recommended alternatives are correct. Not sure what to recommend for `exportTranslations`
=> Add alternative hints for deprecated methods

concrete/blocks/feature/form.php
1. Cleaner icon selector UI.
2. Changes in jQuery code let developers use this template in their own blocks. And in case there were multiple instances of icon selector in a form, the js code doesn't need to be duplicated.
=> Cleaner icon selector UI/jQuery code for Feature block form

build/Gruntfile.js, concrete/blocks/desktop_draft_list/controller.php, concrete/blocks/desktop_draft_list/view.php, concrete/config/app.php, concrete/js/build/core/blocks/draft-list.js, concrete/js/build/core/blocks/draft_list.js
This pull request fixes The issue related to the redirection to home page after the delete of a draft page in desktop draft list block
**Before fix**
**After fix**
=> fix delete draft desktop draft list block

concrete/src/Page/Page.php
at 984 line the variable reassigned
=> unnecessary line

concrete/config/app.php, tests/tests/Config/ValuesTest.php
`Cookie` is present in the configuration both [as an alias](https://github.com/concrete5/concrete5/blob/7deb96e2ce02b172427b5123bd2143779bb38293/concrete/config/app.php#L36) and [as a facade](https://github.com/concrete5/concrete5/blob/7deb96e2ce02b172427b5123bd2143779bb38293/concrete/config/app.php#L165).
What we need is the facade, the alias is never loaded (because the facade is initialized first, the class alias autoloader will never use that value). Indeed, running this code
```php
echo get_class(new \Cookie());
```
outputs
```
Concrete\Core\Support\Facade\Cookie
```
I also added a test so that we won't have an issue like this anymore.
=> Cookie is not an alias

concrete/src/Foundation/Runtime/Boot/DefaultBooter.php
Let's assume we have this code
```php
function foo(\Area $bar) {}
foo(new \Concrete\Core\Area\Area());
```
In the [configuration](https://github.com/concrete5/concrete5/blob/0a610c77e472c8439acbd48a445d1548d965e6b4/concrete/config/app.php#L14), `\Area` is an alias of `\Concrete\Core\Area\Area`.
The problem is that, if `\Area` has not already been autoloaded, PHP throws the following error:
```
Uncaught TypeError: Argument 1 passed to foo() must be an instance of Area,
instance of Concrete\Core\Area\Area given
```
(This is the reason of #8060).
In #8068 we remove all the alias usage from the core, but 3rd party code would still be affected by this issue.
So, IMHO the solution is to always load class aliases...
=> Always register class aliases

concrete/authentication/concrete/controller.php, concrete/authentication/concrete/db.xml, concrete/config/concrete.php, concrete/controllers/install.php, concrete/src/Authentication/AuthenticationTypeController.php, concrete/src/Console/Command/InstallCommand.php, concrete/src/Encryption/PasswordHasher.php, concrete/src/Package/StartingPointPackage.php, concrete/src/Session/SessionValidator.php, concrete/src/Updater/Migrations/Migrations/Version20190822160700.php, concrete/src/User/PersistentAuthentication/CookieService.php, concrete/src/User/PersistentAuthentication/CookieValue.php, concrete/src/User/RegistrationService.php, concrete/src/User/User.php, concrete/src/User/UserInfo.php
1. fixes #8056 by hashing the token used to login (we need to have a larger `authTypeConcreteCookieMap`.`token` field)
2. introduces a couple of classes (in the `Concrete\Core\User\PersistentAuthentication` namespace) to make it easier and safer to get/set/delete the persistent login cookie
3. fixes a bug where *all* the stored records have increased `validThrough` when a user logs in via the persistent cookie ([here's the buggy line](https://github.com/concrete5/concrete5/blob/9fb82b3ee65c0863027dc0772a43ea54831b0b3e/concrete/authentication/concrete/controller.php#L64)) (!).
4. uses the `concrete.session.remember_me.lifetime` configuration key instead of the hard-coded `2 weeks` (see [here](https://github.com/concrete5/concrete5/blob/9fb82b3ee65c0863027dc0772a43ea54831b …
=> Improve persistent login cookie

concrete/src/Html/Image.php, concrete/src/Html/Object/ImageNoScriptFallback.php, concrete/src/Html/Object/JavaScriptLazyImage.php, concrete/src/Html/Object/Picture.php
Native image lazy loading is due to be available in Chrome 75 (around the first week of June 2019 for Chrome and in the near future for other Chromium based browsers). This draft pull request updates the "html/image" service to add native lazy loading and JavaScript lazy loading support. This is a draft pull request because native lazy loading is only available in Chrome stable behind flags and lazy loading feature detection does not work. I tested this pull request using the latest Chrome stable and Chrome Canary with flags enabled and disabled.
**For more information on native lazy loading and lazy loading:**
https://addyosmani.com/blog/lazy-loading
https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video …
=> Add native lazy loading and JavaScript lazy loading support to the "html/image" service

concrete/config/site.php, concrete/controllers/single_page/dashboard/system/multilingual/setup.php, concrete/single_pages/dashboard/system/multilingual/setup.php, concrete/src/Localization/Service/LanguageList.php
Issue: You can not set "Simplified Chinese" or "Traditional Chinese" for multilingual section.
Chinese people living in mainland China uses Simplified Chinese, and people living in outside of the mainland (e.g. Hong-kong, Taiwan, Macau) uses Traditional Chinese. It's a very important difference. So, let's make it enable to choose these type of locale. I tested the multilingual sections with "Simplified Chinese" and "Traditional Chinese", and there's no problem.
Q. Why script-specific languages originally excluded?
A. There was no reason. See:
https://github.com/concrete5/concrete5/commit/a66e1507d4784d9f777cfac031ff74dd8efe246c#commitcomment-35135337
=> Add a config key to support script-specific locales

concrete/src/Foundation/Runtime/Run/DefaultRunner.php
This PR fixes the same issue as #8109, but in a more general way (we may also have the same issue with Blocks and any other aliased class).
=> Preload class aliases also when concrete5 is not installed

concrete/src/Site/Service.php
After the migration from version 5.7.5.9, a site became broken.
The browser stops with this error:
> [E_WARNING] Creating default object from empty value
At this line of Page::getFromRequest():
> $c->cPathFetchIsCanonical = true;
If force PHP to ignore this E_WARNING, the execution stops anyway with this error:
```
Argument 1 passed to
Concrete\Core\Http\ResponseFactory::collection()
must be an instance of
Concrete\Core\Page\Collection\Collection, instance of stdClass given,
called in src/Http/DefaultDispatcher.php on line 130
```
Inspecting the cause of this, I found that the change in this PR fixes the migration.
=> Fix migration from 5.7 when there's no multilingual section

concrete/config/site.php, concrete/controllers/single_page/dashboard/system/multilingual/setup.php, concrete/single_pages/dashboard/system/multilingual/setup.php, concrete/src/Localization/Service/LanguageList.php
This reverts #8128 – unfortunately it completely broke installation and will have to be reworked.
=> Revert "Add a config key to support script-specific locales"

concrete/composer.json
The only change between version 1.7.2 and 1.8.1 is a class alias (introduced in 1.8.1) and a `trigger_error` (that breaks sites where E_DEPRECATED is not accepted) (see [here](https://github.com/doctrine/migrations/compare/v1.7.1...v1.8.1)).
So, what about limiting the maximum version to 1.7.x?
=> Avoid DBAL Migrations 1.8

concrete/src/Workflow/Request/MovePageRequest.php, concrete/views/dialogs/page/drag_request.php
When moving an external URL in the sitemap, we are currently asked if we want to preserve the old page path.
This doesn't make sense, since external URLs don't have page paths.
=> Don't ask to preserve old page path of external URLs

concrete/blocks/page_list/view.php
One of our client's project we got the following error-
```
Error thrown with message "Call to a member function isEditMode() on null"
```
Let's add the `is_object($c)` to avoid this error.
=> Add is_object($c) check on page list block

concrete/src/Express/Entry/Notifier/Notification/FormBlockSubmissionEmailNotification.php
An issue occurs if:
- An Express Form is added
- With email notifications
- With an image_file attribute that's not required
- and it's submitted without a file
Fix: check for valid object, before trying to add it as an attachment.
=> Express Form - Email notification, check file object

concrete/src/Backup/ContentImporter/ValueInspector/InspectionRoutine/ImageRoutine.php
Image imports are not matched up correctly due to prefix not being parsed in getItem method.
https://github.com/concrete5/addon_migration_tool/issues/78
- [x ] I read the __guidelines for contributing__ linked above  
- [ x] PHP-only files follow our coding style; in order to do that use php-cs-fixer - http://cs.sensiolabs.org/ - as follows:
=> Fix for importing images

concrete/blocks/youtube/controller.php, concrete/blocks/youtube/db.xml, concrete/blocks/youtube/form_setup_html.php, concrete/blocks/youtube/view.php, concrete/config/concrete.php, concrete/src/Updater/Migrations/Migrations/Version20191002000000.php
I deleted showinfo setting because youtube IFrame Player API got it deprecated.
https://developers.google.com/youtube/player_parameters#showinfo
Also, I've changed setting's option name because each parameter function has been changed.
https://developers.google.com/youtube/player_parameters#rel
Fixes #8158
=> Delete 'show video infomation' option and change option name of showing related videos

concrete/controllers/dialog/block/edit.php
When we save a block, we call the outputJSON method of EditResponse.
This works, but normal request &rarr; response flow is broken (for example, middlewares are not executed).
What about switching to the standard way (that is, returning a Response instance)?
=> Return a Response instead of dying when saving a block

concrete/controllers/single_page/dashboard/blocks/stacks.php, concrete/src/Page/Cloner.php, concrete/src/Page/Stack/Stack.php
This PR fixes #8182 
The problem is in #7207. Page\Cloner is a nice solution, but we should omit old code that written before we introduced the neutral/localized stacks in #3529.
=> Do not copy stacks repeatedly when adding a localized stack

concrete/controllers/search/file_folder.php
This issue https://github.com/concrete5/concrete5/issues/7316 actually isn't being fixed.
The following code block always returns the value from the session and doesn't read the config value.
https://github.com/concrete5/concrete5/blob/1e62ebe56250c1ffc5bc552aae44526ce91a4c56/concrete/src/File/Search/SearchProvider.php#L119-L127
=> Fix file manager issue with number of items per page

concrete/src/Entity/File/Version.php
1. Currently, `getThumbnailURL()` returns incorrect URL (see attachment image) if the image is in the private storage location. Let's return `/download_file/view_inline/fID` URL instead.
2. We don't have to generate thumbnails if the image is in the private storage location. No one can access to these thumbnails, it's just wasting disk space.
=> Images in a private storage location

concrete/authentication/google/hooked.php
detach was written as deattach  - Don't know why I wrote it as deattach maybe I was half dead when re-writing that part. Or it was those logs saying deattach 🤷‍♂ 
This fixes #8175
=> Fixing #8175 - Correctly attach the detachment string to the detachment

concrete/authentication/google/controller.php, concrete/authentication/google/type_form.php, concrete/controllers/single_page/dashboard/system/registration/authentication.php, concrete/src/Utility/Service/Validation/Strings.php, tests/tests/Utility/Service/Validation/StringsTest.php
If users insert invalid regular expressions in the configuration of the Google authentication type, concrete5 accepts this invalid configuration but, upon login via Google, site visitors see an ugly error message (for example: `preg_match(): Delimiter must not be alphanumeric or backslash`).
So, what about adding some checks to the configuration?
=> Check the regular expressions in the Google authentication type

concrete/elements/attribute/key/form.php, concrete/src/Attribute/Category/SearchIndexer/ExpressSearchIndexer.php, concrete/src/Attribute/Category/SearchIndexer/LegacySearchIndexer.php, concrete/src/Attribute/Category/SearchIndexer/SearchIndexerInterface.php, concrete/src/Attribute/Category/SearchIndexer/StandardSearchIndexer.php, concrete/src/Attribute/Key/Listener.php, concrete/src/Attribute/Key/SearchIndexer/SearchIndexerInterface.php, concrete/src/Attribute/Key/SearchIndexer/StandardSearchIndexer.php, concrete/src/Updater/Migrations/Migrations/Version20170316000000.php
Included in this pull request:
- added some PHPDoc
- deprecate the `refreshSearchIndexKeyColumns()` method of the attribute key `StandardSearchIndexer`: it's not part of `SearchIndexerInterface`, what it does has been integrated into the `updateSearchIndexKeyColumns()` method
- deprecate the `refreshRepositoryColumns()` method of the category `StandardSearchIndexer`: it's not part of `SearchIndexerInterface`, what it does has been integrated into the `updateRepositoryColumns()` method
- fix the logic of `updateSearchIndexKeyColumns`:
- fix #5552
- fix #6562
- fix #7859
To be noted: with this PR, when users uncheck the `Field available in advanced search` option, the columns in the index table are dropped. The reasons for this are:
- we avoid having useless columns (see for example #8001) …
=> Fix indexing stuff

concrete/blocks/core_conversation/controller.php, concrete/blocks/core_conversation/view.php, concrete/js/build/core/conversations/conversations.js
On set a message as spam, token error is issued, because the form does not send a token.
=> Fix token error on flag_conversation_message

concrete/src/Page/Search/ColumnSet/ColumnSet.php
Let's use- 
```
return $provider->getDefaultColumnSet();
```
instead of 
```
return new DefaultSet();
```
Override of the  `SearchProvider` & `DefaultSet` class doesn't work properly because of this `return new DefaultSet();`. It requires one more class override only because of this line.
https://github.com/concrete5/concrete5/blob/80dfd7d8fc9bfa305a703c1aa1e71f6fd2694c5b/concrete/src/Page/Search/ColumnSet/ColumnSet.php#L21-L36
=> Minor fix - return default column set using the provider

build/components/avatar/Cropper.js, build/components/avatar/Cropper.vue, concrete/controllers/single_page/account/avatar.php
This PR fixes (#8218) the save_avatar not using the ccm_token supplied in the query string.
Essentially /ccm/assets/localization/dropzone/js adds ccm_token to the parameters by default and this causes issues with the validation
I've also added error handling and logging if anything goes wrong with the avatar upload. It will now display an error message if the token is invalid or something goes wrong during upload and will also reset the visuals to the previous source.
I've updated the controller a bit but i'm not sure if we need save_thumb anymore but i've kept it for bc (if people are using a custom pages)
=> Fix #8218 - save_avatar uses the incorrect ccm_token

concrete/blocks/document_library/controller.php
Document library block returns`Call to undefined method` error when the `$file` tree node type is other than `File` or `FileFolder`.
In my case, it was `\Concrete\Core\Tree\Node\Type\SearchPreset`.
https://github.com/concrete5/concrete5/blob/f8424aeeb7514c2e63ec746b6ea175e2b85e64f1/concrete/blocks/document_library/controller.php#L547-L551
This PR fixes the issue.
=> Fix document library block error when file node type is other than File or FileFolder

concrete/src/Sharing/SocialNetwork/ServiceList.php
Phone URLs should start with `tel:`, email URLs should start with `mailto:`
=> Add phone and email to social links

concrete/src/Api/OAuth/Controller.php
This updates the OAuth login controller to use concrete5's PasswordHasher class to check the password, instead of the native password_verify function. This ensures that the same password hashing types that are supported via the standard concrete5 login are also supported for external/API logins.
=> Update OAuth password check to use PasswordHasher class

concrete/controllers/backend/user.php, concrete/controllers/dialog/user/bulk/group.php, concrete/src/User/User.php, tests/tests/User/GroupTest.php
This pr fixes parent groups not being able to be added after a child has been added due to their path names being the same. #8150
It also adds a new inExactGroup() function for this behaviour. This means that the previous behaviour of inGroup(), which returns true if in the user is in the group or any child groups, are not affected by this change.
This pr also fixes the issue where Groups with similar names return true for inGroup() #8206. For example
A user in group named ("Paying members 1") would return true for being a member of ("Paying members 100")
This PR also adds some new tests to address the issues above, such as testing for similar named groups, testing for inExactGroup vs inGroup
=> Fixing #8206 and #8150 : Issues with userGroups and inGroup()

concrete/src/Api/ApiServiceProvider.php
When initializing the ResourceServer class, we pass the actual public key (in RSA format, that is a string that starts with `-----BEGIN PUBLIC KEY-----`).
In this case, the `league/oauth2-server` component saves this public key to file, and sets its file permissions to 0600 (see [here](https://github.com/thephpleague/oauth2-server/blob/5.1.6/src/ResourceServer.php#L50), [here](https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L40) and [here](https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L93)).
Under Windows, it all works, but reading back the configured permissions always return 0666, so [this check](https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L58) always fail.
The solution is to create the `CryptKey` …
=> Don't check POSIX permissions of API public key on Windows

concrete/src/Conversation/Message/Author.php
this allows something such as the following to work in app.php
Core::bind(\Concrete\Core\Conversation\Message\AuthorFormatter::class, function($app, $params) {
return new \Application\MySite\Conversation\Message\AuthorFormatter($params[0]);
});
the use-case in this circumstance was to allow a custom User attribute to be used as the display name for members who have posted on the site
addresses #8231
=> Allow the AuthorFormatter class to be overriden

concrete/src/Entity/OAuth/Scope.php
Fixes invalid orm schema check.
> ./concrete/bin/concrete5 -- 'orm:validate-schema'
[Mapping]  FAIL - The entity-class 'Concrete\Core\Entity\OAuth\Scope' mapping is invalid:
* The association Concrete\Core\Entity\OAuth\Scope#codes refers to the owning side field Concrete\Core\Entity\OAuth\AuthCode#scopes which is not defined as association, but as field.
* The association Concrete\Core\Entity\OAuth\Scope#codes refers to the owning side field Concrete\Core\Entity\OAuth\AuthCode#scopes which does not exist.
* The association Concrete\Core\Entity\OAuth\Scope#tokens refers to the owning side field Concrete\Core\Entity\OAuth\AccessToken#scopes which is not defined as association, but as field.
* The association Concrete\Core\Entity\OAuth\Scope#tokens refers to the owning side field …
=> Fix failing orm:validate-schema check. Invalid orm schema in Oauth2\Scope

concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
It's currently impossible to overwrite the CsvWriter in a fashionable manner. If we boot the CsvWriter via the app container, like in this PR, we can rebind it in custom code.
=> Use container to create CsvWriter instance

concrete/src/Routing/ClosureRouteAction.php
In the [application/bootstrap/app.php](https://github.com/concrete5/concrete5/blob/8.5.2/application/bootstrap/app.php#L40) file we have an example where routes can send their output by simply calling `echo`.
BTW this currently doesn't work: we have this error:
```
Error thrown with message "Call to a member function has() on null"
Stacktrace:
#11 Error in concrete/src/Http/Middleware/FrameOptionsMiddleware.php:41
...
```
that's because middlewares expect a Response object, but we currently return `null`.
What about actually supporting the `echo` approach?
EDIT: fix #7750 (thanks @hissy)
=> Make it so routes can echo their output

concrete/src/Editor/CkeditorEditor.php
#8118 is caused by this issue:
Here's the situation:
1. [we create a `<div contenteditable="true">`](https://github.com/concrete5/concrete5/blob/8.5.2/concrete/src/Editor/CkeditorEditor.php#L207)
2. [we manually create the CKEditor instance](https://github.com/concrete5/concrete5/blob/8.5.2/concrete/src/Editor/CkeditorEditor.php#L466)
3. [when the DOM is loaded, if `CKEDITOR.disableAutoInline` is true, CKEditor automatically starts the CKEditor instances of all the elements with `contenteditable` set to true](https://github.com/ckeditor/ckeditor4/blob/4.12.0/core/creators/inline.js#L143)
Since we don't set the `disableAutoInline` properly, CKEditor tries to initialize twice an editor for the same HTML element, so it throws [this error](https://github.com/ckeditor/ckeditor4/blob/4.12.0/core …
=> Fix initializing CKEditor

concrete/controllers/dialog/tree/node/category/add.php, concrete/controllers/dialog/tree/node/category/edit.php, concrete/src/Tree/Node/Type/Category.php
This PR contains the following-
- [Fix] The folder name is null when you create it with name '0'
- Allow add/edit tree node category/folder name to '0'
Now it doesn't show up the folder name if you save it with `0`.
I was wondering should we allow to add the folders with the name `0` or not. 
But as (@hissy suggested) we're allowing the page names with `0`, we should allow the folder name as well. 
https://github.com/concrete5/concrete5/pull/3856
=> [Bugfix] The folder name is null when you create it with name '0'

concrete/src/Mail/Service.php
In the `\Concrete\Core\Mail\Service::load()` method, the emails subject is set again, with for the most cases, a not defined variable. 
If the subject of a mail was set like the example below, the `load()` method will override the value of the subject again. The `$subject` may or may not be set with the `extract` function  shown [here](https://github.com/concrete5/concrete5/blob/f8424aeeb7514c2e63ec746b6ea175e2b85e64f1/concrete/src/Mail/Service.php#L296).
If the Mail\Service class has a proper setter for the Subject, which it does, it should be the only way in setting the emails subject.
```php
$mailHelper = $app->make('helper/mail')
$mailHelper->to('some@person.io);
// Set Subject
$mailHelper->setSubject('Some Title');
// Subject would be overridden under certain circumstances …
```
=> Fix setting the emails subject a second time with an undefined variable

concrete/attributes/textarea/controller.php, concrete/elements/attribute/editable_attribute.php, concrete/src/Attribute/XEditableConfigurableAttributeInterface.php
When editing a Rich Text attribute, the CKEditor instance is created inside an X-editable container.
When CKEditor opens a dialog (for example: add/edit link), and users click on it, X-editable tries to close the editor. This fails because of https://github.com/ckeditor/ckeditor4/issues/3686, but it shouldn't occur.
To solve this, we need to tell X-editable to not close the editor when users clicks outside the X-editable element.
Fix #8271.
=> Fix editing Rich Text attributes

concrete/elements/attribute/key/form.php
"User Attribute Options" section is not displayed now because of the wrong class import made by @mlocati  at #8198 . Let's fix it.
=> Fix to show User Attribute Options

concrete/src/Page/Controller/PageController.php
Since #8268 got merged, it's no more possible to edit pages.
Why?
We often access pages with `/index.php?cID=...` (that is, with an empty request path - like for example when we edit a page): in these cases `$request->getPath()` returns an empty string (which has a length lower than than the page path).
So, we shouldn't check the request path length if it's empty and we retrieved the page given its ID.
=> Allow empty request path

concrete/controllers/dialog/block/edit.php
Potential fix for https://github.com/concrete5/concrete5/issues/8261, essentially I've moved `$b = $this->getBlockToEdit();` to after the block passes validation, as that function creates a new version of the block, and I can't think of a reason why we would want a new version until we've successfully validated and can save the block. If I'm wrong please let me know. 😃
=> Fix block edit Access Denied issue #8261

concrete/js/build/core/file-manager/search.js
Fixes #7215
This PR fixes permission window breaks if the drag-able area is located over the folder #7215
Essentially if a draggable ui element was over a folder node in the file manager (such as permission windows) then when dropped it would drop into both areas and cause a javascript error and break the permissions
=> Fix #7215 - Fixing draggable zone on filemanager to only accept file/folder nodes 

concrete/config/concrete.php, concrete/src/Session/SessionFactory.php
Expired sessions are cleaned up in the so-called *garbage collection* (*GC* for short).
GC is called automatically at the startup of sessions (see [this PHP manual page](https://www.php.net/manual/en/sessionhandlerinterface.gc.php)), and it may or may not be performed accordingly to the value of the `session.gc_probability` and `session.gc_divisor` INI values.
At the moment, concrete5 doesn't handle these values, so PHP will use the ones configured in every system `php.ini` file.
If the system is misconfigured, we risk that GC never occurs, which leads to huge directories (or `Sessions` database tables if users use the database session handler).
So, what about adding explicit support to GC?
PS: in this PR we configure a default 1% GC probability (the PHP default one), but users can change …
=> Let concrete5 handle the session garbage collection

concrete/js/ckeditor4/core/concrete5uploadimage/plugin.js
After the refactoring of the file import in 8.5.0.
You are unable to drag and drop or paste images into content blocks.
This is due to the response no longer returning an array but an object that contains the array of files.
This PR fixes that issue
=> Fix #8265 - failing to add url upon drag/drop/paste

concrete/views/dialogs/page/drag_request.php
Breaks when moving multiple pages at once due to no check for `$singleOriginalPage` which is null in this case.
=> Fix: check singleOriginalPage object

concrete/controllers/backend/file.php
Currently in version 8.5.x sites that have been upgraded from 5.7 sites, you can no longer replace files.
This is due to two reasons, the first (and the one this PR seeks to resolve) is that after @mlocati 's refactoring of the backend file handler we check for the folder of replacing files.
The second issue is that 5.7 files don't have a folder under the folderTreeNodeID column (they have their own fileNodeID)... in the migration it states that this was for some permissions issue.
https://github.com/concrete5/concrete5/blob/develop/concrete/src/Updater/Migrations/Migrations/Version20161203000000.php#L37-L51
Rather than modify existing databases and replacing the folderTreeNodeID with an actual folder.
Instead I went with the method of checking if the replacing file getFileFolderObject() …
=> Fix replacing old 5.7 files

concrete/src/Routing/RouteActionFactory.php, tests/tests/Routing/RouteActionFactoryTest.php
In the current concrete5 release the only way to use a completely custom route action for a given route is to override the `RouteActionFactory` class completely. Luckily it's not a huge job to override, but it'd be nice if we simply allowed instances of RouteActionInterface to be set as route actions and to pass through cleanly.
This PR makes that happen and adds a couple tests for it.
=> Allow passing route actions through routes

concrete/src/Permission/Access/Entity/UserEntity.php
This is a similar problem with #7440
```
Exception Occurred: /path/to/concrete5/concrete/src/Workflow/BasicWorkflow.php:99 Call to a member function getUserID() on null (0)
```
Steps to reproduce:
1. Create a user
2. Create a Workflow then set a notification to the user
3. Apply the workflow from the full sitemap page
4. Delete the user
5. Create a workflow request with approving a page
=> Fix error on submitting workflow request to a deleted user

concrete/src/Tree/Menu/Item/EditPermissionsItem.php, tests/tests/Application/UserInterface/ContextMenu/ContextMenuTest.php
Since edit folder permissions is a tree node item it doesnt have a width or height set on the dialog.
This PR adds a Height and Width to the edit folder permission dialog.
Fixes issue described in PR #8303
=> Fix height/width of edit folder permissions dialog

concrete/blocks/core_area_layout/controller.php
By moving this from the view function the CSS will always be added, even when the view function doesn't run because of existing block cache.
Related to #2825 and #6477
=> Add layout assets to output via registerViewAssets

concrete/views/dialogs/user/search.php
This PR fixes an issue when searching in a user selector popup will fire the UserSearchDialogSelectUser and UserSearchDialogSelectUser.core events more than once. Causing popups to be closed multiple times.
For example on the Sitemap click on attributes then clear the author of a page and click choose user. When the user search shows up, search in the box in the right for any user (admin) then select a user (admin). Both the search dialog and attributes pop-up is closed.
=> Fix user-selector events firing more than once

concrete/src/Error/UserMessageException.php
Exceptions of type `UserMessageException` are meant to show errors to the users, without any system details.
BTW, the `system_errors` element may display the place where these exception were created and their stack trace, which is out of scope (see [here](https://github.com/concrete5/concrete5/blob/8.5.2/concrete/elements/system_errors.php#L36)).
So, what about displaying only the error message?
=> Display only the message of UserMessageException

concrete/src/Validator/String/EmailValidator.php, tests/tests/Attribute/ValidationTest.php
The EmailValidator validator class outputs the email address if it is valid. Let's output a generic message instead.
=> Don't output email when it's invalid

concrete/authentication/community/form.php, concrete/authentication/external_concrete5/form.php, concrete/authentication/facebook/form.php, concrete/authentication/google/form.php, concrete/authentication/twitter/form.php, concrete/controllers/single_page/login.php, concrete/single_pages/login.php
[](url)
We used to show the user buttons that allowed them to hook external accounts to their concrete5 account, instead let's just leave that a part of the user profile pages and show a logout view.
One important note is that we use the login page to manage filling required attributes, this PR takes care to ensure that the required attributes form can be shown and completed during the login process.
=> Show a logout view to logged in users on the login page

concrete/config/install/base/permissions.xml, concrete/controllers/frontend/assets_localization.php, concrete/elements/custom_style.php, concrete/src/Block/Menu/Menu.php
This PR addresses #7789 
- Moves the custom block template selector from the advanced tab to be at the start of the Design & Custom Template buttons
- Renames instances of 'Custom Template' to 'Block Template'
- Relabels 'Design & Custom Template' to 'Design & Block Template' in block context menu
- Renames '(None selected)' to 'Default', which makes more sense in the context of the 'Block Template' label
=> Moves the custom block template selector from the advanced tab to buttons

concrete/controllers/single_page/dashboard/blocks/stacks.php, concrete/src/Permission/Key/AddBlockToAreaAreaKey.php
Another pass to remove `new User()` calls
=> Use Concrete\Core\User\User singleton instead of creating new User instances

concrete/src/Controller/AbstractController.php
Fix #8361
1. Is it ok to have `function buildRedirect(array $args)` instead of `function buildRedirect() { $args = func_get_args()` ?
2. Can I add a commit to this PR that replaces all the occurrences of `$this->redirect()` with `return $this->buildRedirect()`?
=> Add AbstractController::buildRedirect()

build/foundation/js/cms/sitemap/search.js, concrete/config/concrete.php, concrete/controllers/dialog/page/edit_alias.php, concrete/controllers/frontend/assets_localization.php, concrete/routes/dialogs/pages.php, concrete/src/Page/Page.php, concrete/src/Updater/Migrations/Migrations/Version20200116115000.php, concrete/views/dialogs/page/edit_alias.php
When we create page aliases, it's not possible to change neither their name nor their URL slug.
(It's maybe the first issue I submitted to @aembler something like 9/10 years ago, IIRC via an email message - and he agreed it's something that should be fixed).
With this PR, users will be (finally :wink:) able to edit page aliases:
=> Edit page aliases

concrete/src/Database/Connection/Connection.php
This *could* fix #8338 (I'm not sure, for me everything works just fine)
=> Fix "Database is not empty" installing v9

concrete/blocks/calendar/view.php
I added " contentHeight: 'auto' " so that when you put the calendar block into narrow width area, scroll bar will not show up. If it's wide width area, there's no scroll bar.
I think it's better not showing scroll bar as initial setting.
=> Set calendar's contentHeight to 'auto'

.gitattributes
If `/concrete/bin/concrete5` uses the Windows line endings (`\r\n`), we'll have this error if we run it under POSIX (tested under Ubuntu 18.04):
```
/usr/bin/env: 'php\r': No such file or directory
```
So, let's ask git to use the standard POSIX line endings (`\n`) for that file.
The opposite may occur for the Windows batch file `/concrete/bin/concrete5.bat`.
=> Ensure line endings of files in /concrete/bin

concrete/controllers/single_page/dashboard/system/registration/profiles.php
When I change gravatar settings from `dashboard/system/registration/profiles` it shows `Public profiles have been enabled/disalbed` which is confusing.
Let's show `Public profiles settings have been updated.` when public profile option isn't changed.
=> Show different message when public profile option isn't changed

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/api/settings.php, concrete/src/Api/ApiServiceProvider.php, concrete/src/Entity/OAuth/RefreshToken.php, concrete/src/Updater/Migrations/Migrations/Version20200203000000.php
I worked for refresh_token. To enable it, the following three files need to be modified. It was straight forward.
- concrete/config/concrete.php
- concrete/controllers/single_page/dashboard/system/api/settings.php
- concrete/src/Api/ApiServiceProvider.php
However, this code has a Database integrity issue, because of the following code. In the code, an access token is removed at first, and then, its corresponding refresh token is removed.
```
// vendor/league/oauth2-server/src/Grant/RefreshTokenGrant.php
// Expire old tokens
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
$this->refreshTokenRepository->revokeRefreshToken($oldRefreshToken['refresh_token_id']);
```
Concrete5 database has a foreign key constraint, so that the above code is erroneous.
(DB …
=> Enable refresh_token grant

concrete/blocks/page_list/controller.php
1. Check custom topic
2. Doesn't select any topic nodes
3. Save
You'll get SQL error
```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `concrete5`.`btpagelist`.`customTopicTreeNodeID` at row 1
```
=> Avoid error on save page list block options with empty custom topic node

concrete/config/concrete.php, concrete/src/Express/Export/EntryList/CsvWriter.php, concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
ATOM format is hard to use for normal user in Japan.
=> Use local date time format in CSV

concrete/bootstrap/configure.php, concrete/src/Config/CompositeLoader.php, concrete/src/Config/ConfigServiceProvider.php, concrete/src/Config/CoreFileLoader.php, concrete/src/Config/Driver/Redis/RedisConfigServiceProvider.php, concrete/src/Config/Driver/Redis/RedisLoader.php, concrete/src/Config/Driver/Redis/RedisPaginatedTrait.php, concrete/src/Config/Driver/Redis/RedisSaver.php, concrete/src/Config/FileLoader.php, tests/tests/Config/CompositeLoaderTest.php, tests/tests/Config/Driver/Redis/Fixtures/Redis.php, tests/tests/Config/Driver/Redis/Fixtures/RedisPaginatedTraitFixture.php, tests/tests/Config/Driver/Redis/Fixtures/RedisPaginatedTraitValuesFixture.php, tests/tests/Config/Driver/Redis/RedisPaginatedTraitTest.php, tests/tests/Config/Driver/Redis/RedisSaverTest.php
This PR does two main things:
1. Split `FileLoader` into two loaders, one for application and one for core and add a `CompositeLoader` with both loaders registered so that functionality is the same. We needed to do this because we need drivers to override the core, but not the manual file overrides.
2. Implement a simple `RedisSaver` and `RedisLoader` for storing and reading config overrides to redis.
**Why?**
Config ends up being the major sticking point when running concrete5 in a distributed way. Today moving config to redis would be an extremely manual process and would overriding the application and many aspects of the runtime.
Redis was a good option as a first driver, database was the initial choice but it became obvious that race conditions with connecting to the database and with …
=> Add the ability to easily inject custom Config drivers (loaders/saves) and implement Redis drivers

concrete/attributes/express/form.php
This PR fixes the following error-
```
TypeError thrown with message "Argument 1 passed to Concrete\Core\Form\Service\Widget\ExpressEntrySelector::selectEntry() must be an instance of Concrete\Core\Entity\Express\Entity, null given, called in concrete\attributes\express\form.php on line 3"
```
To reproduce visit Page Types `/dashboard/pages/types/` and click the "Attribute" button of the page with having an invalid express page attribute.
- Create an express entity `/dashboard/system/express/entities/add`.
- Create a custom attribute with the entity `/dashboard/pages/attributes`.
- Add the attribute to the page type form `/dashboard/pages/types/form/{id}`.
- Delete the entity from `/dashboard/system/express/entities`.
- Visit the page types attributes page …
=> Avoid exception on express attribute form

concrete/elements/attribute/key/form.php
Error suppression was removed with this commit: https://github.com/concrete5/concrete5/commit/98412449f86614b78748dbbf2637fc7ffbc760b2
which caused attribute editing to break for categories that didn't have a custom element. Unfortunately since we support PHP 5.5 and since changing these to be thrown exceptions would be a BC break, our best bet is to add back error suppression and revisit in v9 or v10.
=> Add error supression back to category form element loading

concrete/elements/attribute/key/form.php
This is exactly the same as #8419 just cherry-picked into this branch
=> Add error supression back to category form element loading 8.6 branch version

concrete/src/Search/AbstractSearchProvider.php
This PR fixes the following error when the sortBy column isn't exists on the advanced search result
```
Call to a member function setColumnSortDirection() on null
```
- Create an express object
- Add some entries
- Do the advanced search
- Uncheck `Date Added` from `Choose Columns` section
- Keep the `Sort By Column` as it is `Date Added`
- Click on pagination
- You'll get the error
=> [Fix] Error when the sortBy column isn't exists on the advanced search result

concrete/src/Form/FormServiceProvider.php
How about adding `helper/form/group_selector` to  FormServiceProvider as singleton.
This PR allows to use the `GroupSelector` as follows-
```
$gsfh = Core::make('helper/form/group_selector');
echo $gsfh->selectGroup('group', $group);
```
=> [Feature] Make GroupSelector helper singleton

concrete/src/Form/Service/Validation.php
`\Concrete\Core\Form\Service\Validation::test()` method has return type `int` on the phpdoc, whereas it returns `bool`.
=> Fix phpdoc of the \Concrete\Core\Form\Service\Validation::test()

concrete/src/Database/DatabaseStructureManager.php, concrete/src/Updater/Migrations/Migrations/Version20160725000000.php, concrete/src/Updater/Migrations/Migrations/Version20190708000000.php
This is an alternative approach to #8428
Here we basically delay the creation of foreign keys until the migration is completed, so that we can skip setting `foreign_key_checks` to 0 (which seems to somehow break the database in selected MySQL/MariaDB versions).
=> Fix upgrading from concrete5 5.7 - v2

concrete/src/Console/Command/FixDatabaseForeignKeys.php, concrete/src/Console/ServiceProvider.php, concrete/src/Database/ForeignKeyFixer.php
If a concrete5 instance is upgraded from a previous version, foreign keys may be malformed (see [here](https://github.com/concrete5/concrete5/pull/8428#issuecomment-588875454) for a detailed description).
What about adding a CLI command that fixes these foreign keys?
=> Add ForeignKeyFixer and c5:database:foreignkey:fix CLI command

concrete/src/Page/Type/Composer/Control/CorePageProperty/DateTimeCorePageProperty.php
When creating a new page where you have set the attribute for Public Date Time to required, it doesn't validate the submitted data and tries to obtain this information from the page itself.
During testing I found that this did not behave in the same way `concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php` where it would actually get the information from the request if it was present.
Adding the above snippet in this PR seems to resolve the issue.
=> Public Date/Time Composer Error

concrete/attributes/select/controller.php
When creating a Page List query filtering on a select attribute it can potentially return incorrect results.
Example.
I'm filtering on some pages of type X that has been tagged with multiple tags.
Title = Page 1; Tags (select multiple) [Tag 1, Tag 2]
Title = Page 2; Tags (select multiple) No tags applied.
```php
$pl = new PageList();
$pl->filterByAttribute('tags', 'fish');
$results = $pl->getResults();
```
The above actually outputs all pages when it should output none.
The fix in this PR corrects that
=> select filterByAttribute can return all results

concrete/controllers/element/navigation/menu.php, concrete/src/Permission/Access/Access.php
Although the `implode` method accept parameters in either order, this order is deprecated.
https://www.php.net/manual/en/function.implode.php : `Note` section
=> fix order of parameters in implode method

concrete/src/Attribute/View.php, tests/tests/View/AttributeViewTest.php
Calling the `action` method of a `Concrete\Core\Attribute\View` instance causes one of these two errors (depending on the PHP version):
```
array_unshift() expects at least 2 parameters, 1 given
```
or
```
Only variables should be passed by reference
```
Before I add a test that shows the error, then I'll add a fix for it.
=> Fix Attribute\View::action()

concrete/src/Console/Command/ConfigCommand.php
The config command with the `environment` option doesn't work now as written on the doc.
It can't read or write the proper values. Please check the comments-
https://documentation.concrete5.org/developers-guide/appendix/cli-commands#c5-config
This PR allows you to set the config values with `--env=ENVIRONMENT` option.
I'll update the documentation once it got merged or after release.
=> [Fix] Config command with env option

concrete/src/Permission/Assignment/AreaAssignment.php, concrete/src/Permission/Key/AddBlockToAreaAreaKey.php, concrete/src/Permission/Key/AreaKey.php
Issue #8244 is a bit nasty... Here's a description of the issue.
When we open the *Add Block* panel, the list of blocks is built by the [`buildSetsAndBlockTypes()`](https://github.com/concrete5/concrete5/blob/8.5.2/concrete/controllers/panel/add.php#L82) method of the `panel/add.php` controller.
This method iterate all the non internal block types and basically calls this code to determine the list of allowed block types:
```php
$checker = new Concrete\Core\Permission\Checker($currentPage);
if ($checker->canAddBlockType($blockType)) {
$allowedBlockTypes[] = $blockType;
}
```
What `canAddBlockType()` does? It forwards the request to the [`canAddBlockType()`](https://github.com/concrete5/concrete5/blob/8.5.2/concrete/src/Permission/Response/PageResponse.php#L108) method of the …
=> Fix checking blocks than can be added to Stacks/Global Areas

tests/tests/Console/ServiceProviderTest.php
This PR does a few extra things:
1. Fixes service provider test by adding the missing `FixDatabaseForeignKeys` command
2. Makes the `app->extend` mock a little more robust so that it might catch more failures
3. Aliases different types of command namespaces to make it easier to see what's what at a glance
4. Modifies the assert so that the discrepancies are reported rather than just the whole subset being outputted
=> Fix console service provider test by adding

build/webpack.mix.js
This allows developing npm modules (like @concretecms/bedrock) wyth a simple `npm link`
Here's my setup:
1. clone the concrete5 repository (I cloned in to `C:\Dev\Projects\concrete5\concrete5`)
2. install the NPM dependencies:
```
cd build
npm install
```
3. clone the bedrock repository (I cloned in to `C:\Dev\Projects\concrete5\bedrock`)
4. From inside the `build` directory of concrete5, run this command:
```
npm link ..\..\bedrock
```
With the change in this pull request, running `npm run prod` seems to correctly generate the assets, without resolution-related issues.
=> [v9] Ask webpack to not resolve symlinks

build/assets/themes/concrete/js/main.js
On case-sensitive operating systems, we have this error:
```
ERROR in ./assets/themes/concrete/js/main.js
Module not found: Error: Can't resolve 'NProgress'
```
Let's fix this
=> Fix importing NProgress

tests/tests/Multilingual/SectionTest.php
Added a new unit test for #8014
This test failed before #8014 merged, because a new `mpRelationID` is not generated when the page copied in the same language tree.
```
$ composer test -- --filter testRegisterDuplicate
> phpunit '--filter' 'testRegisterDuplicate'
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
Runtime:        PHP 7.2.20
Configuration:  /path/to/concrete5/phpunit.xml
F
Time: 16.43 seconds, Memory: 38.25MB
There was 1 failure:
1) Concrete\Tests\Multilingual\SectionTest::testRegisterDuplicate
A page duplicated in the same locale, but did not created new mpRelationID.
Failed asserting that '1' is not equal to <string:1>.
/path/to/concrete5/tests/tests/Multilingual/SectionTest.php:78
FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
Script phpunit handling the test event …
```
=> Add test for Section::registerDuplicate

concrete/blocks/faq/controller.php, concrete/blocks/image_slider/controller.php
What about using just one query to duplicate the data in the `btImageSliderEntries` (Image Slider) and  `btFaqEntries` (FAQ) database tables?
This approach:
1. is faster (just one query for all the sub-records)
2. is safer (data won't be converted from MySQL to PHP and then back to MySQL)
3. is easier to be maintained (if you add/remove/rename a field, simply update the `$copyFields` variable)
=> Faster and safer duplication of FAQ/Image Slider blocks

concrete/src/Page/Sitemap/SitemapGenerator.php
In my opinion the OR check in populateLanguageAlternatives() function must change to an AND check in order to respect "exclude_sitemapxml" attribute of related pages (Or better say the whole canIncludePageInSitemap() function). Otherwise it seems that the system allows every related page to be in the sitemap just because it exists without checking if canIncludePageInSitemap functions retrurns true.
=> Fix issue with sitemap generation in multilingual sites

concrete/src/Multilingual/Service/Extractor.php
Now, concrete5 doesn't translate the files in the `application/authentication` directory. 
How about adding this directory to `multilingual/extractor`?
=> Add the authentication directory to the multilingual extractor

concrete/blocks/youtube/controller.php
If a url is passed with no params then ```parse_str($url['query'], $query)``` will throw an exception message as isset is not called before hand. This PR fixes that but also cleans up the code to remove duplication and stricter standards.
=> Potential YouTube block expection

concrete/controllers/frontend/assets_localization.php
Related to #8309 
Original issue #8308 
This fixes a bug caused by #8309 with non-chunked file uploads that are directly dropped to the dropzones.
The issue is further explained in this comment in the original pull request:
https://github.com/concrete5/concrete5/pull/8309#issuecomment-594708442
=> [v8] Fix #8308 non-chunked file uploads directly dropped to dropzones

concrete/src/Console/Command/UninstallPackageCommand.php
`Concrete\Core\Package\Package::backup()` always returns an object - see https://github.com/concrete5/concrete5/blob/develop/concrete/src/Package/Package.php#L852. Thus, issuing the CLI command to uninstall a package with the `--trash` flag set results in an exception being output to the screen even when everything worked just great. This small change fixes that.
=> make `c5:package:uninstall --trash` not throw exception if there wasn't a problem

concrete/authentication/concrete/controller.php
I faced a problem that login & logout are very slow (taking 6-7 seconds for each). The root cause was the use of deprecated logout() function instead of do_logout(), and too many hashed authcookie data remained in the database. Each hashed data needs 200ms for examination, in my environment.
The straight-forward solution is to clean up authTypeConcreteCookieMap table and to use  do_logout(), but many free theme in concrete5.org still don't use do_logout. I believe this trouble should be handled in other ways.
I suggest to check the stored hash in the descending order, so that the newer hash is examined earlier. In my case, the login time became from 7sec to 200ms, because there were needless 34 data.
=> Speedup Login

concrete/controllers/event/permissions.php, concrete/elements/permission/details/calendar.php, concrete/elements/permission/details/calendar_admin.php, concrete/views/dialogs/permissions/calendar.php
We were checking the 'access task permissions' permission, instead let's check whether you can edit permissions for the specific calendar.
Fixes #8412
=> Check the right permission when change calendar perms

concrete/elements/files/search_header.php
DOM and JS was changed in #7658 but this attribute name was not changed with the rest (from `data-launch-dialog` to `data-dialog`). Consequentially, the new folder modal doesn't work.
This change corrects the attribute name to match the selector in the JS
=> Fix: new folder modal

composer.lock, concrete/composer.json
This is required so that the translation library can parse the CIF elements introduced in concrete5 version 9.
See the [changelog](https://github.com/concrete5-community/translation-library/releases/tag/1.6.0).
=> [v9] Update translation library

concrete/src/Permission/Response/PageResponse.php
Even If you allow a user/group to add some specific type of blocks, the user can add all block types to the page.
This PR fixes the issue.
=> [Fix] User can add blocks to the page other than the permitted one

concrete/js/build/core/file-manager/search.js
the file-manager class names for results are no longer working on the helper function. Im going to assume it was something else was changed or browser behaviour between #8275 being created/merged and now. Because it worked when it was created
This changes the class finder so we don't rely on the helper classes and instead allow the actual element to be passed
=> Fix file-manager drag and drop not working anymore

concrete/src/Job/Set.php
If we schedule a Job Set to be executed after web visits, and we disable it, we have this exception: 
```
'UPDATE JobSets SET isScheduled = ?, scheduledInterval = ?, scheduledValue = ? WHERE jsID = ?'
with params
[false, "weeks", "1", "7"]
SQLSTATE[22007]
Invalid datetime format: 1366 Incorrect integer value: '' for column `JobSets`.`isScheduled` at row 1
```
I think it's because I have `NO_ENGINE_SUBSTITUTION` in the `sql_mode` of my MySQL installation (which is the default for recent MySQL/MariaDB versons).
This change fixes this issie.
=> Fix disabling Job Set scheduling

concrete/src/Form/Service/Form.php
We may need to output a form element (`<input />` or `<textarea />`), just for displaying a value. Thus, we should be able to skip specifying element names/ids.
=> Allow textarea and input elements without id or name

concrete/controllers/element/navigation/application_menu.php
This fixes the following warning:
```
implode(): Passing glue string after array is deprecated. Swap the parameters
```
PS: detected by turning on the *Consider warnings as errors* option in the System & Settings > Environment > Debug Settings dashboard page
=> Avoid deprecated order if implode() arguments

.travis.yml, tests/assets/Docker/run-install.sh, tests/assets/Docker/run-update.sh, tests/helpers/DockerTrait.php
Before https://github.com/concrete5-community/docker5/pull/12, the `docker5` docker images contained only one PHP version (which was 5.5 for concrete5 5.7 images and 7.2 for concrete5 8+ images).
This was a problem: since concrete5 9 requires PHP 7.2, we couldn't test upgrading a concrete5 5.7 installation because its docker image uses PHP 5.5.
Now, the `docker5` docker images contain multiple PHP versions: 5.6, 7.2 and 7.4 (you can switch the currently active one by using the new `switch-php` command). There's no PHP 5.5 (which could be useful to test concrete5 5.7) because the used PPA ([`ppa:ondrej/php`](https://launchpad.net/~ondrej/+archive/ubuntu/php)) doesn't offer it.
This change lets us test upgrading a concrete5 5.7 docker image to concrete5 9.
=> [v9] Fix Docker tests

concrete/src/Page/Controller/PageController.php
Before this change the `->getSets()` function would check for a session flashbag value for `page_message` each time it was called, and if there were messages would add those messages to the output by effectively merging them into the result of `parent::getSets()`
The problem with this is the flashbag contents get deleted when they get read, so setting them only in the output means that only the first call to `->getSets()` will include the stuff from the flashbag. To combat that, I've done a few things:
1. Memoize the fact that we've checked the flashbag, this prevents us from checking session every time we need to get the set values and also stops us from resetting the messages over and over
2. Changed from merging the values into the result to setting the values with `$this->set()` so …
=> Fix automatic flashbag sets

concrete/src/Site/Type/Controller/ControllerInterface.php, concrete/src/Site/Type/Controller/Manager.php, concrete/src/Site/Type/Controller/StandardController.php, concrete/src/Site/Type/Formatter/AbstractFormatter.php, concrete/src/Site/Type/Formatter/DefaultFormatter.php, concrete/src/Site/Type/Formatter/FormatterInterface.php, concrete/src/Site/Type/Service.php
PHP type hinting is a real life saver: programmers are sure about the returned values from functions, and functions are sure about what they receive.
We can't of course change stuff that has already been released (otherwise overriding classes and methods would break the LSP).
What about adding it for new classes, like the ones included in this PR?
=> Add type hinting to Site Type stuff

concrete/src/Form/Service/Form.php, tests/tests/Form/Service/FormTest.php
The current Form service creates HTML elements with the same value for the `name` and the `id` attribute.
This can be problematic when we have multiple forms in the same page, with fields with the name name: we'd have multiple elements with the same ID (which is wrong).
So, what about letting users specify a custom value for the `id` and/or the `name` element of HTML attributes?
We can also remove one of those attributes (simply specify an empty value for it).
=> Allow specifying custom ID or NAME attributes for form elements

concrete/src/Authentication/Type/OAuth/BindingService.php, tests/tests/Authentication/OAuth/BindingServiceTest.php
Looks like ->execute will return an int and not a statement in this situation, let's handle that properly.
=> Fix bindingservice, handle either a statement or an int being returned from ->execute()

concrete/blocks/express_form/controller.php
This asset group doesn't exist anymore so requiring it here throws errors. Getting rid of those errors unfortunately exposes a broken block edit interface but let's let that be a separate issue.
=> Remove core/tree requirement from express_form edit

concrete/single_pages/dashboard/boards/instances/details.php
We don't want translators to translate "Refresh Pool" as "Refresh Swimming Pool", don't we? :wink:
=> Use "Data Pool" instead of "Pool" to help translators

concrete/controllers/single_page/dashboard/express/entries.php
(Most) translators don't read the PHP code around strings when they translate: the only see translatable strings out of context.
So, when they see `%s Entries`, they don't know if `%s` is a number (for example: `3 Entries`), or something else (like the entity name associated to the entities, for example `Boat Entries`, that is `Entries of the Boat entity`).
So, since `%s Entries` can have two different meanings, its translations can be different for every meaning.
Solution:
- add a comment (`/*i18n: %s is an entity name*/`) to tell translators that `%s` is the name of an entity
- add a context (`tc('EntriesOfEntityName', '...')`), so that the translations table can have two translatable strings (for example, we can have `tc('NumberOfEntries', '%s Entries')` and `tc('EntriesOfEntityName', …
=> Improve translatable string in Express entries

concrete/src/Logging/LogEntry.php
Reading the log can be difficult if looking for specific severities. This pull adjusts the icons so that each severity has a distinct icon. The colours are also adjusted slightly. Errors now have the 'danger' red and notices are 'success' green.
=> Improve distinction between log severity icons

concrete/config/concrete.php
Some webservers could be configured to process these files types. Let's disallow them by default.
Resolves H1 #880621
=> Add more extensions to the blacklist

concrete/tools/files/permissions.php
File passwords aren't the most secure way to protect files. It's really meant to be a simple way of sharing insecure files without having them indexed by search engines. Let's add some info around that and what to use instead for serious security
Resolves h1#459380
=> Add information about what file passwords are used for

concrete/src/Support/Symbol/MetadataGenerator.php
This only fixes some wrong comments in the `.phpstorm.meta.php` file generated by the `c5:ide-symbols` CLI command:
```patch
--- a/.phpstorm.meta.php
+++ b/.phpstorm.meta.php
-// $em->getRepository(EntityClass::class)->find()
+// $em->getRepository(EntityClass::class)->findAll()
override(\Concrete\Core\Entity\User\AttributeRepository::findAll(0), map([
'' => 'Concrete\Core\Entity\Attribute\Key\UserKey[]',
]));
-// $em->getRepository(EntityClass::class)->find()
+// $em->getRepository(EntityClass::class)->findBy()
override(\Concrete\Core\Entity\User\AttributeRepository::findBy(0), map([
'' => 'Concrete\Core\Entity\Attribute\Key\UserKey[]',
]));
-// $em->getRepository(EntityClass::class)->find()
+// $em->getRepository(EntityClass::class)->matching() …
```
=> Fix comments in generated .phpstorm.meta.php file

concrete/config/concrete.php, concrete/config/db.xml, concrete/src/Entity/File/DownloadStatistics.php, concrete/src/Entity/File/File.php, concrete/src/Updater/Migrations/Migrations/Version20200610162600.php, concrete/src/User/UserInfo.php
I kept the table definition as is (except for the `fvID` table field which changes from unsigned to signed, because the `FileVersions`.`fvID` table field is signed).
Just one question: should we keep the `TIMESTAMP` type of the `timestamp` field, or should we switch to `DATETIME`?
- `TIMESTAMP` fields can't save values smaller than `1970-01-01` or greater than `2038-01-19`
- `DATETIME` fields require one more byte (6∼8 bytes instead of 5∼7 - that's a 15%∼20% more disk space)
=> Introduce the DownloadStatistics entity

concrete/src/Application/UserInterface/Dashboard/Navigation/Navigation.php, concrete/src/Navigation/Breadcrumb/BreadcrumbInterface.php, concrete/src/Navigation/Breadcrumb/Dashboard/DashboardBreadcrumb.php, concrete/src/Navigation/Navigation.php, concrete/src/Navigation/NavigationInterface.php
We may need to alter the items previously added to a `NavigationInterface` instance: what about adding a new `setItems()` method to it?
I also added some PHPDoc, as well as return types so that we can use method chaining (eg `$breadcrumb->add($a)->add($b);`)
=> Add setItems() to NavigationInterface

concrete/config/concrete.php, concrete/src/Updater/Migrations/Migrations/Version20200625191946.php
Our latest addition of the gallery block didn't include a migration to install it on existing sites.
=> adding migration for new gallery block

concrete/src/Job/Job.php
Currently if you run a single job (non queue-able job) when it is finished it will fire the on_job_execute event twice.
It is called in markCompleted and executeJob.
The call in executeJob is redundant as the job status hasn't been updated yet and if we try to get the status of a job it will return the previous run, not the current one.
=> Dont call on_job_execute event twice in executeJob

tests/tests/Config/CompositeLoaderTest.php, tests/tests/Utility/Service/TextTest.php
Let's fix [those two](https://travis-ci.org/github/concrete5/concrete5/jobs/699351172#L542-L551) warnings raised by phpunit.
=> Fix test warnings

concrete/src/Job/Job.php
same as #8798 but for version 8.5 as well
=> [v8] don't fire event execute_job twice

concrete/src/Entity/Page/Container.php, concrete/views/panels/add.php
This addresses #8478 
It (kind of) requires a bedrock companion draft pull request https://github.com/concrete5/bedrock/pull/87
The search works and I didn't have to modify liveupdate.js
The reason it's only a draft is that the screenshot on the issue page presents a design that is totally different from what was done for the Add block panel.
I added styling in bedrock to look like the screenshot but for now, it is commented out.
For now, I styled the containers list like the add block panel but without the grid view.
If the design should be as it is on the screenshot then I will uncomment the styling I added in bedrock and make a few other modifications.
It will make things difficult for the liveupdate.js part and the styling of the element when clicked before dragging but it's doable. …
=> New Add Container Experience

concrete/controllers/single_page/dashboard/system/environment/logging.php
The log channels were compared strictly to 1, but looking at the request data,
it was sent as a string ("1"), this made the comparision fail and always put 0.
which made it impossible to save the logging channels.
Since it is a checkbox and not present in the request if it remains unchecked,
we can just check if the checkbox name is present in the request, the value does not matter.
Page: /dashboard/system/environment/logging
=> Fixing save channel logging

concrete/attributes/page_selector/controller.php
It seems that the page selector attribute is not included in CollectionSearchIndexAttributes table because it is missing the $searchIndexFieldDefinition
=> [V9] make page_selector attribute searchable

concrete/attributes/page_selector/controller.php
It seems that the page selector attribute is not included in CollectionSearchIndexAttributes table because it is missing the $searchIndexFieldDefinition
=> [V8] make page_selector attribute searchable

concrete/blocks/express_form/controller.php
If a form redirects to an external page that includes a query parameter, the result is a malformed URL. This fixes that issue.
=> Fix malformed URL on form redirect

concrete/src/Updater/Migrations/Migrations/Version20190509205043.php
This is a repeatable migration, so we should be sure we don't wipe out previous data.
See https://github.com/concrete5/concrete5/pull/7822#discussion_r441125632
=> Fix ExpressEntityEntries.publicIdentifier migration

build/README.md
The readme instructions would install Gulp instead of Grunt. I've replaced the gulp install command for the equivalent in Grunt.
=> Fix readm to install grunt instead of gulp

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/mail/addresses.php, concrete/controllers/single_page/dashboard/users/search.php, concrete/controllers/single_page/register.php, concrete/single_pages/dashboard/system/mail/addresses.php, concrete/src/Workflow/Request/ActivateUserRequest.php
We're working on a project with user registration.
It's kinda troublesome that we cannot configure from name of register notification email.
This adds the config value or register notification FROM NAME.
I've also added the text input field system email setting page.
=> User Registration: Adding "concrete.email.register_notification.name"

concrete/elements/custom_style.php, concrete/elements/slider.php, concrete/src/Page/Theme/GridFramework/GridFramework.php
Requires an update of the bedrock repository (https://github.com/concrete5/bedrock/pull/93).
I have completely refactored the toolbar code within this task.
If you prefer that all input fields should have a dark gray background color i can change this. But i really like this style with the mixed background colors.
Issues:
1. Bootstrap is loaded 2 times currently in the frontend. Therefore you need to click two times on the bootstrap select components to get them open. I have sent andrew more details about that issue on slack.
=> Block and area design toolbar ui fixes.

concrete/blocks/autonav/controller.php, concrete/blocks/autonav/form_setup_html.php
This takes care of #8834 and does **not** have a companion bedrock pull request
- Fixed the checkbox to use BS4 class names
- Fixed input group to use BS4 class names
- Fixed the tabs with proper BS4 class names
- Removed all obsolete control-label class names
- Styled the preview in the preview tab
- Positioned the "cover" element properly on top of the preview
- Fixed the inline CSS that was using the wrong class name
- Fixed an issue with the preview when "Begin auto nav" was set to "beneath a particular page" and none was selected. The preview was displaying the whole sitemap including system pages.
Concerning the last point, the way I fixed it was to set the selected page to the home page for the preview if none was selected.
Here are a couple of screenshots and below the …
=> FIx Auto-Nav block add/edit form for BS4 #8834

concrete/views/dialogs/event/versions.php
At the moment in the Dialog Versions, the trash or delete icon is not being shown because is using `fa fa-trash-o` instead of simply `fa fa-trash` this update fixes this issue. 
Before:
With the correct icon:
=> Dialog Versions - FontAwesome icon typo

concrete/controllers/single_page/dashboard/calendar/events.php, concrete/single_pages/dashboard/calendar/events.php
This change makes it possible to link to the edit dialog of a calendar event using the `edit` GET parameter:
For example: `/dashboard/calendar/events?edit=111222`
This PR makes no attempt to check permissions or anything, the dialog's validation and permission checking should be plenty.
=> Add the ability to edit calendar events using a fixed link

concrete/single_pages/dashboard/calendar/events.php
I missed this in testing, sometimes the dialog code is not loaded in synchronously. I'm not sure what exactly causes this but it ends up being later in the async queue than this code so our defer is not enough. Instead let's just repeatedly poll every 50ms until the dialog functionality is loaded.
=> Avoid race condition with the dialog functionality by polling

concrete/controllers/backend/user/chooser.php, concrete/controllers/dialog/user/search.php, concrete/routes/actions/users.php, concrete/src/Form/Service/Widget/UserSelector.php, concrete/src/User/UserTransformer.php, concrete/views/dialogs/user/search.php
This PR adresses issue #8757
Requires companion bedrock PR https://github.com/concrete5/bedrock/pull/96
This is how it looks now:
* Initial input state
* User Selected
* Dialog Initial State
* When searching
For dialog, we can have single or multiple selection
* Single
* Multiple 
Note for developers:
To enable multiple selection for dialog, you need to pass `'multipleSelection'` arguments to dialog launcher
```javascript
ConcreteUserManager.launchDialog(myCallback, {multipleSelection: true})
```
=> Updating in-page user picker

concrete/src/Page/Type/Type.php
If `<pagetype>` has `internal` attribute, it will be installed as internal page type even if the value is "0".
=> Fix can't install page type properly from cif format

concrete/blocks/core_container/view.php
Viewing with [whitespace changes disabled](https://github.com/concrete5/concrete5/pull/8940/files?w=1) is the best way to go
=> Prevent error from container not being set

concrete/views/dialogs/page/drag_request.php
#8291 is not enough to check `$singleOriginalPage` is null or not.
=> Avoid "Call to a member function on null" on page drag request

concrete/controllers/dialog/event/edit.php
Currently saving after editing an occurrence redirects you to the calendar date on the event rather than the date on the edited occurrence. By trying to resolve the "local" occurrence from the request we can redirect to the proper date.
=> Redirect to the /occurrence/ date and time when editing an occurrence

build/webpack.mix.js
Edge 18 (before the chromium switch version <44) had issues with some syntax in dependencies we use. In order to fix this I've overridden the default js rule that comes from laravel mix and replaced it with the same thing except without the node_modules exclusion.
This seems to work well for me but absolutely has the potential to cause trouble with some dependencies. If we run into an issue like that we can either:
A. Update the exclude on a case by case basis and exclude only problematic stuff
B. Create a dist folder and make dist releases for bedrock with the compatibility compiled in
=> Fix panels in edge 18

concrete/single_pages/dashboard/calendar/events.php
This PR updates the calendar icon to the correct version. 
In version 4 the calendar uses `fa fa-calendar-o` in version 5 the icon should be change to `far fa-calendar`
This is the expected result:
=> Fixing FontAwesome missing calendar icon

concrete/controllers/backend/board/instance.php, concrete/controllers/single_page/dashboard/boards/scheduler.php, concrete/src/Logging/Channels.php
Everytime a user pins a board or schedule one we need to log that activity. 
This PR adds the new Channel Board "Board" to the Logging in order to log when users pin a board like this:
Or Schedule one from the Dashboard/Boards/Schedule:
The following is a screenshot of both events logged:
=> Adding new Channel Board to Logging and logs when users pin or schedule boards

build/webpack.mix.js
v-calendar was having trouble with the babel polyfills / transforms we have, let's exclude it
=> Exclude v-calendar from our babel transforms

concrete/blocks/calendar_event/controller.php, concrete/blocks/calendar_event/db.xml, concrete/blocks/calendar_event/form.php, concrete/blocks/calendar_event/view.php, concrete/config/concrete.php, concrete/controllers/dialog/event/export.php, concrete/routes/calendar.php, concrete/src/Calendar/Event/Menu/EventOccurrenceMenu.php, concrete/src/Updater/Migrations/Migrations/Version20201596544868.php
This pull request contains the export feature.
Furthermore i have changed the version number from the last migration class (thanks to @hissy for bringing this up in https://github.com/concrete5/concrete5/pull/8932#issuecomment-671151142)
After renaming i have extended the same migration class with an block update statement for this feature. 
@aembler If you have already executed the migration with the old-named migration class you need to manually run the refresh of the block type within the dashboard page Block types. Even better you should run the following SQL query: `DELETE FROM SystemDatabaseMigrations  WHERE version = '20201596544868';` to rollback the corrupted timestamp.
=> Implement task #8945

composer.lock, concrete/composer.json, concrete/config/concrete.php, concrete/routes/actions/pages.php, concrete/src/Calendar/Event/EventRepetitionService.php, concrete/src/Updater/Migrations/Migrations/Version20200810000000.php, concrete/src/Updater/Migrations/Migrations/Version20200814143401.php
#8963 broke some tests because the class was misnamed compared to the filename. Additionally, the migration really should be split out to a separate migration because it added functionality (rather than forcing people to have to run migrations again with --rerun.) I've added a separate migration for it.
=> Fixing migrations, adding new migration for separate functionality

concrete/src/Express/Export/EntryList/CsvWriter.php, concrete/src/Site/Service.php, concrete/src/Tree/Node/Type/ExpressEntrySiteResults.php, tests/tests/Express/Export/EntryList/CsvWriterTest.php
* **Support MultiColumnText interface**. We have some attributes that are able to output multiple text columns instead of just a single key => value pair. This change supports those text columns by prepending them with the attribute name and a hyphen. So for example if an attribute with the display name 'Bar' has 'foo' as a multi column text header we'd output `Bar - foo` as the header.
* **Fix `DATE_ATOM` output**. We were attempting to output ATOM format for date_created but the way things flow through the calendar date tool we were converting the *string* `ATOM` to a date format rather than actually using the `DATE_ATOM` format.
* **Add 'site' handle to export**. This PR adds a header 'site' and outputs the site handle value for each entry.
=> Improve express CSV export

concrete/src/Config/Driver/Redis/RedisSaver.php
I was setting this up today and realized that there was a bug in the saver that would cause a fatal error if trying to save a primitive value. That's not great so I added a conditional to handle those cases specifically
=> Handle primitive values in the Redis ConfigSaver

concrete/blocks/core_board_slot/controller.php, concrete/blocks/core_board_slot/view.php
Somehow core_board_slot blocks can be added with a null "slotTemplateID", this change makes it to that the site isn't borked if that happens.
=> Make core_board_slot more resistant to misconfiguration

concrete/src/Express/Export/EntryList/CsvWriter.php, tests/tests/Express/Export/EntryList/CsvWriterTest.php
The CSV export included dateCreated but not the last modified date. This PR adds dateModified next to dateCreated and populates it with a date string the same as dateCreated.
=> Add date modified to csv export

concrete/bootstrap/helpers.php
Replaced call_user_func_array with argument unpacking in bootstrap\helpers.php and cleaned it up 
We have prepared another branch that includes  `concrete/src/Localization/Translator/TranslatorAdapterInterface.php` and its implementations if you are okay with these changes, i can update this PR or create another one.
You can check what it's done [here](https://github.com/Xanweb/concrete5/commit/bafad092991a0b7082b74a82189e5c1660a6b07a)
=> Cleanup bootstrap\helpers.php

concrete/single_pages/dashboard/blocks/stacks/view.php
Whenever you save a change on a stack the publish button was not showing. JQuery was unable to find the element because had the wrong id name. This PR fixes this issue and moves the nav-item to the class attribute.
=> Fix publish button display when updating stack

concrete/src/User/UserServiceProvider.php
@mlocati tried to use `$app->make(User::class)` instead of `new User()` to improve performance on #7433 .
That pull request was already merged, but @aembler deleted registering singleton when merging https://github.com/concrete5/concrete5/commit/fdeb56230f12ca8e28d53d49cd5a20b4e4319a8a
I believe it was an accident, so let's get registering singleton back.
Before
After
=> Re: Make the User instance as a singleton

concrete/src/Multilingual/Service/Detector.php
This pull request contains improvements listed below, and fixes #8824
* Avoid to get preferred section twice
* Avoid to store Locale object in the session
* Check locale is a string and not empty before storing it in the session (for safety)
* Avoid to use request cache (we don't need it, this instance should be a singleton)
* Add some comments
* Use some interfaces
The main issue of #8824 is a bug in the Multilingual Detector class.
@Ruud-Zuiderlicht asked a question on that issue. I agree with him.
We should always store a locale key (e.g. en_US or ja_JP) instead of a Locale instance.
This bug was introduced on #5287 . @mlocati mistakenly changed to store Locale object, but I think it was not expected behavior for him.
I've changed to get locale key from Locale object before storing it …
=> Refactoring Multilingual Detector

concrete/blocks/core_conversation/form.php
Avoid implode(): Invalid arguments passed on `core_conversation` block.
=> Avoid implode(): Invalid arguments passed

concrete/src/Block/Block.php
=> [v9] Avoid editing non-editable aliased blocks

concrete/jobs/index_search_all.php
For large sites the Job never starts and always leads to 500 Error even with performant server, 6Gb of php memory_limit and 600s of max_execution_time.
With this transactions wrap, the job starts in about 15seconds
=> Fix Search Index Job

concrete/src/Editor/LinkAbstractor.php
We're getting all snippets from the database on viewing content block every time, even if there are no snippets in the content.
It's just wasting resources, let's reduce unnecessary database queries.
This PR includes some refactoring for the view of performance improvement.
Before: 655 statements were executed, 408 of which were duplicates, 247 unique (block cache disabled)
After: 607 statements were executed, 360 of which were duplicates, 247 unique (block cache disabled)
=> Load snippets from database only if any snippets used in the content

concrete/src/Area/Layout/Layout.php
Currently, we’re getting the same area layout from the database twice per layout object.
Let's avoid calling the same SQL query multiple times!
Before: 245 statements were executed, 114 of which were duplicates, 131 unique
After: 239 statements were executed, 102 of which were duplicates, 137 unique
=> Avoid to get the same Area Layout from the database repeatedly

concrete/src/Permission/Access/Entity/GroupEntity.php
Currently, we're getting the same Permission Access Entity from the database so many times on a single request!
Let's avoid it by using the request cache.
Before: 253 statements were executed, 122 of which were duplicates, 131 unique
After: 201 statements were executed, 70 of which were duplicates, 131 unique
=> Avoid to get same Permission Access Entity from database repeatedly

concrete/src/Area/Layout/CustomColumn.php, concrete/src/Area/Layout/PresetColumn.php, concrete/src/Area/Layout/ThemeGridColumn.php
Almost same as #9040
Let's use request cache to improve performance.
Before: 261 statements were executed, 136 of which were duplicates, 125 unique
After: 257 statements were executed, 128 of which were duplicates, 129 unique
=> Avoid getting same Column object from database repeatedly

concrete/src/Entity/Express/Entry.php
We don't have indexes on date created or date modified for express entries so when we try to get a list ordered by one of these values we end up with really expensive queries.
This PR adds basic indexes for date create and for date modified.
=> Add date indexes to express entry database table

concrete/blocks/document_library/controller.php
Fix #9053 
By returning an empty FileFolder object, the page will still render, and the now missing folder will no longer be associated with the block. This conditional block is only called in three methods: `action_upload`, `formatBreadcrumbs` and `setupFolderFileFolderFilter`. The other methods call this method with `$realRoot = true`, thus bypassing this block. 
All three of these methods fail gracefully with this change. If the page is already loaded, then someone deletes the folder before another user uploads a file, the page reloads and the block shows no files found. `formatBreadcrmbs` and `setupFolderFileFolderFildter` similarly fail gracefully. 
It may be better to add a warning that a document library block depends on a folder when deleting it, but this at least doesn't cause …
=> fix #9053 by not killing the whole page

concrete/src/Routing/Router.php, tests/tests/Core/Routing/RouterTest.php, tests/tests/Routing/CheckRoutesTest.php
Routes can have optional arguments, which are defined by specifying their default values.
For example, if we have:
```php
$route = $router->register('/foo/bar/{baz}'), $callback);
$route->setDefaults(['baz' => 'default-baz']);
```
The route should handle requests like `http://www.example.com/foo/bar/sample` and `http://www.example.com/foo/bar`.
In the first case, `$callback` receives a value of `sample` for the `$baz` argument, in the second case it should receive `default-baz`.
BTW, our current routing system doesn't work well with default arguments.
In this PR I first add a test for this (it should fail), after I'll add a fix.
=> Fix routes with optional arguments

concrete/src/Session/Storage/Handler/NativeFileSessionHandler.php
concrete5 v8 requires [`"symfony/http-foundation": "^3.4.17"`](https://github.com/concrete5/concrete5/blob/8.5.4/concrete/composer.json#L35), and since version 3.4 [we should use](https://github.com/symfony/http-foundation/blob/v3.4.17/Session/Storage/Handler/NativeSessionHandler.php#L22) `\SessionHandler` instead of `ymfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler`.
=> [v8] Don't use Symfony NativeSessionHandler

concrete/src/Session/Storage/Handler/NativeFileSessionHandler.php
concrete5 v9 requires [`"symfony/http-foundation": "^3.4.17"`](https://github.com/concrete5/concrete5/blob/f22f8a6b78ee357dd07cf7d4963e6d0185e5e312/concrete/composer.json#L35), and since version 3.4 [we should use](https://github.com/symfony/http-foundation/blob/v3.4.17/Session/Storage/Handler/NativeSessionHandler.php#L22) `\SessionHandler` instead of `ymfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler`.
=> [v9] Don't use Symfony NativeSessionHandler

concrete/src/Page/Controller/PageController.php
Original issue #5578 is already closed, but #8268 is not enough to fix the issue.
For example, if there're some multilingual sections like `/en` and `/ja` in your site, still you'll get the home page in some cases.
/f -> Not found ( #8268 fixes this case only, because only this request path is shorter than `/en` )
/fo -> Show default home page
/foo -> Show default home page
/fooo -> Not found
After merging this pull request, you'll get Page Not Found on all paths above.
=> Fix #5578 some of non-existing collection path shows home page on multilingual site

concrete/src/Validation/BannedWord/BannedWord.php, concrete/src/Validation/BannedWord/BannedWordList.php, concrete/src/Validation/BannedWord/Service.php, tests/tests/Validation/BannedWordTest.php
This PR fixes #8202 but also I added `@deprecated` to unused, old-school functions.
This class was written by Tony, and never updated since 5.4.
https://github.com/concrete5/concrete5-legacy/blob/5.4.2/web/concrete/helpers/validation/banned_words.php
I'd like to rewrite BannedWord class as Doctrine entity for version 9. Can I?
=> Make it enable to add multibyte banned words

concrete/controllers/single_page/login.php, concrete/src/User/User.php, tests/tests/Block/BlockRenderTest.php
The current way we store the User singleton works when logging in via web.
Let's make it work if we log in via code too.
=> Fix User singleton when logging in via code

concrete/src/Http/DefaultDispatcher.php
When we detect an invalid path traversal, we currently throw a RuntimeException.
This is not correct IMHO: such exceptions aren't displayed to the users by default, and this may ring all sort of alarm bells for system admins.
What about throwing an UserMessageException instead?
=> [V9] Use UserMessageException when invalid path traversal is detected

concrete/composer.json, concrete/src/Database/Driver/PDOStatement.php
Because the PHP bug https://bugs.php.net/bug.php?id=52098 has not been fixed for all the PHP versions that concrete5 v8 currently supports, we can't fix #9050 with #9052 (for the supported PHP versions see [this example](https://3v4l.org/tTYgg)).
So, the only viable solution for v8 is to require a version of DBAL lower than 2.11.
=> [v8] Fix doctrine dbal incompatibility - Take 2

concrete/elements/header_required.php
Everything needed is already added by the [`footer_required` element](https://github.com/concrete5/concrete5/blob/8.5.4/concrete/elements/footer_required.php#L37-L58).
=> [V8] Remove Account Menu stuff from header_required element

concrete/blocks/express_entry_detail/controller.php
Don't know how, but one of our clients was able to add an `express entry detail` block without the express form ID.
And then she couldn't fix it as the exception was thrown.
Let's avoid this exception.
=> Avoid an exception on express_entry_detail block when the express form ID is not exists

concrete/src/Tree/Node/NodeType.php
We should fix this typo in a subsequent pull request. (Note/Node)
_Originally posted by @aembler in https://github.com/concrete5/concrete5/pull/9042#discussion_r505024288_
=> Fix Typo in concrete/src/Tree/Node/NodeType.php

concrete/src/Routing/RouteActionFactory.php
What about supporting single action controllers?
```
Route::register('/testpath', 'Application\Fruit');
// OR:
use Application\Fruit;
Route::register('/testpath', Fruit::class);
```
https://laravel.com/docs/5.7/controllers#single-action-controllers
=> supporting single action controllers

concrete/src/Permission/Registry/Multisite/Object/AuthorObjectRegistry.php
`concrete/src/Permission/Registry/Multisite/Object/AuthorObjectRegistry.php` should have `Concrete\Core\Permission\Registry\Multisite\Object` as namespace.
=> Fix class namespace

composer.lock, concrete/composer.json, concrete/controllers/backend/file.php, concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php, concrete/src/Permission/IPService.php, concrete/src/Permission/PermissionServiceProvider.php, tests/tests/Session/SessionValidatorTest.php
IPv4 addresses are usually expresses in decimal notation, for example `127.0.0.1`.
By the way, for historical reasons, widely used libraries (and browsers) accept IPv4 addresses with numbers in octal and/or hexadecimal format.
For example, by opening the URL [`http://0177.0.0.0x1`](http://0177.0.0.0x1), your browser will actually open `http://127.0.0.1`.
We have to take care of this.
PS: this is a fix for v8: I'll submit soon a separate fix for v9
PPS: fix H1 863221
=> [V8] Correctly parse non decimal ip addresses

concrete/src/Database/CharacterSetCollation/Manager.php, concrete/src/Updater/Migrations/Migrations/Version20190509000000.php
I just experienced #8981 while trying to upgrade one of our websites from 8.5.2 to 8.5.4.
It turned out that we had mixed collations for the database tables. This prevents the creation of foreign keys (because the linked columns must all use the same collation).
I don't know how this may happen. BTW, to fix this issue, it's enough to reset the collation of all the database tables to the configured values.
For this reason I added a `reapply` method to the `Concrete\Core\Database\CharacterSetCollation\Manager` class, and a migration that calls it.
Closes #8981
=> [V8] Let's be sure that all the db tables use the configured charset

concrete/src/Database/CharacterSetCollation/Manager.php, concrete/src/Updater/Migrations/Migrations/Version20190509000000.php
Same as https://github.com/concrete5/concrete5/pull/9113 but for v9
=> [V9] Let's be sure that all the db tables use the configured charset

concrete/src/Block/Block.php
Stack proxy block shouldn't prevent full page cache, but it must not create an output cache for entire stack content.
This PR fixes #5717 for 8.5.x only, we should pick this commit for version 9 also.
=> Fix stack content never updated in some cases

concrete/controllers/panel/sitemap.php
I made this pull request for issue (#8868 ).
This PR is repaired to show page type according to the permission inside the draft list.
=> page type draft with permission

concrete/src/Form/Service/Form.php
Adds a magic method to the form helper so that it can adapt to current and future capabilities of html input types.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
The __call() renders any previously unspecified input field type. Allows for adaptive update to any new HTML input types that are not covered by explicit methods. Browsers will either handle the specific input type or fallback to a text input.
Th @docblock is adapted from other methods and describes what the __call() actually does, not its declared parameters.
=> Allow Form helper to handle new HTML input types.

concrete/src/View/DialogView.php
Sometimes composer form cached on browsers due to lack of `cache-control: no-cache, private` header.
This pull request fixes #3697 (already closed but not yet fixed), #3696, #6781
=> Do not print assets directly on dialog view to avoid cache problem

concrete/src/Console/Command/ConfigCommand.php
ConfigCommand load only application config after splitting FileLoader in two loaders ( See https://github.com/concrete5/concrete5/commit/2514f1ac195ad62fff240f4cd8aa948a8faab7c8 )
=> [V8] BugFix: ConfigCommand load only from application config

build/.npmrc, build/libraries/fs.js, build/libraries/git-skip.js, build/package.json, build/webpack.mix.js
When writing the source javascript/css assets, we often need to build the compiled assets.
When we commit the changes, we may want to commit only the changed source files, not the compiled files.
This is a bit of a mess at the moment.
What about adding an easy way to tell git to ignore the compiled assets?
- add two new `npm` commands:
- `npm run-script git-skip` tells git to ignore the compiled assets
- `npm run-script git-unskip` tells git to consider the compiled assets
- for convenience, we also call:
- `git-skip` when building the assets for development (eg `npm run-script dev`)
- `git-unskip` when building the assets for production (eg `npm run-script prod`)
=> Easily tell git to ignore built assets

concrete/routes/misc.php, concrete/single_pages/dashboard/system/optimization/jobs.php
Let's remove these routes: they were introduced in #1806 just for backward compatibility (their "standard" route alternatives are available since concrete5 5.7.4)
=> Remove job routes that use tools

concrete/elements/page_types/composer/controls/core_page_property/url_slug.php
This fixes a typo of 58e7b613773ffb0198693edbda0a8b3761168e08 (#9049)
=> Fix bug in  page_types/composer/controls/core_page_property/url_slug element

concrete/src/Application/Service/Dashboard/Sitemap.php
=> [V9] Store the "include system pages" sitemap option in session instead of cookie

README.md
We migrated from travis-ci.org to travis-ci.com.
Let's make the only change required.
=> [V9] Switch from travis-ci.org to travis-ci.com

README.md
Same as #9180 but for concrete5 version 8
=>  [V8] Switch from travis-ci.org to travis-ci.com

concrete/controllers/dialog/page/sitemap_selector.php, concrete/controllers/element/dashboard/sitemap/sitemap_overlay.php, concrete/controllers/single_page/dashboard/sitemap/explore.php, concrete/controllers/single_page/dashboard/sitemap/full.php, concrete/elements/dashboard/sitemap/sitemap_overlay.php, concrete/single_pages/dashboard/sitemap/explore.php, concrete/single_pages/dashboard/sitemap/full.php, concrete/src/Application/Service/Dashboard/Sitemap.php, concrete/src/Application/UserInterface/Sitemap/StandardSitemapProvider.php, concrete/src/Form/Service/Widget/PageSelector.php, concrete/views/dialogs/page/sitemap_selector.php
We currently store in a cookie if the sitemap browsers should include system pages.
This cookie is set in the `/dashboard/sitemap/full` dashboard page (*Include System Pages in Sitemap* option), but it's used everywhere we display a sitemap (eg in the `/dashboard/sitemap/explore` dashboard page and in the page selector widget).
IMHO it's a very sub-optimal behavior: for example, in order to pick a system page in the `/dashboard/system/registration/postlogin` dashboard page, we need to go to `/dashboard/sitemap/full`, check that flag, and go back to the postlogin page.
What:
- removing the cookie that stores the *Include System Pages in Sitemap* setting
- persist its value only for the `/dashboard/sitemap/full` & `/dashboard/sitemap/explore` dashboard pages (in the session)
- allow the …
=> Sitemap views:  allow setting includeSystemPages on an instance basis 

concrete/src/Page/Page.php
Its parent `__destruct` method is already called automatically ([example](https://3v4l.org/VE3Wt).
=> Remove useless Page::__destruct

tests/tests/Api/OAuth/ScopeRegistryTest.php, tests/tests/Cookie/CookieTest.php, tests/tests/Foundation/Queue/BatchTest.php, tests/tests/Foundation/Queue/DatabaseQueueAdapterTest.php, tests/tests/Localization/Translator/Translation/TranslationLoaderRepositoryTest.php, tests/tests/Localization/Translator/TranslatorAdapterRepositoryTest.php, tests/tests/Summary/Template/FiltererTest.php, tests/tests/System/MutexTest.php, tests/tests/System/NameAlreadyInUseTest.php
When have a few class names that are not PSR-4 compliant.
Indeed, by running `composer install --optimize-autoloader` we have these warnings:
```
Deprecation Notice: Class Concrete\Tests\Api\OAuth\Client\ScopeRegistryTest located in tests/tests/Api/OAuth/ScopeRegistryTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.
Deprecation Notice: Class Concrete\Tests\Error\CookieTest located in tests/tests/Cookie/CookieTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.
Deprecation Notice: Class Concrete\Tests\Foundation\BatchTest located in tests/tests/Foundation/Queue/BatchTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.
Deprecation …
```
=> [V9] Fix wrong class namespaces

concrete/src/Search/ItemList/ItemList.php
Added support again for using the config value "concrete.seo.paging_string" for pagination, rather than hardcoding the variable.
=> Update ItemList.php add features from old legacy

concrete/attributes/textarea/form.php
To replicate issue:
- add a form block to a page with two fields; a simple text field and a textarea field set to 'Rich Text'
- set the first text field to be a required field
- enter content into the rich text field, but leave the required text field blank, then submit the form
- when the page reloads and displays the validation error message, the rich text field will be missing the originally entered content
This change fixes this issue.
=> Fix issue where a rich text field on a form block doesn't re-populate contents after submit

concrete/attributes/textarea/form.php
To replicate issue:
- add a form block to a page with two fields; a simple text field and a textarea field set to 'Rich Text'
- set the first text field to be a required field
- enter content into the rich text field, but leave the required text field blank, then submit the form
- when the page reloads and displays the validation error message, the rich text field will be missing the originally entered content
This change fixes this issue.
=> Fix issue where a rich text field on a form block doesn't re-populate contents after submit 

concrete/blocks/google_map/form_setup_html.php
I wasted a few hours why c5 says my google API key is invalid.
I enabled Places API, but not enabled billing information.
This change will help someone who can't understand why their API key is not valid.
=> Improve error message for invalid google maps api key

concrete/config/concrete.php, concrete/src/Console/Command/FixThemeValuesCommand.php, concrete/src/Console/ServiceProvider.php, concrete/src/Page/Theme/AvailableVariablesUpdater.php, concrete/src/StyleCustomizer/Style/ColorStyle.php, concrete/src/Updater/Migrations/Migrations/Version20201116182100.php, tests/tests/Console/ServiceProviderTest.php
This PR supersedes #9230
We had 2 problems. In addition to the one fixed by #9230 (included here in the first commit), a user reported a strange issue:
when editing a Type style, he got an empty dialog:
I *think* the reason of this is that the theme has been upgraded from previous a version, and that caused the Type style to be rendered with all its components disabled (`-1`).
So, what about adding a tool to fix this kind of problems?
In this PR at the moment that updated is executed in a migration, but I included also a CLI command.
What about calling it whenever a theme is updated? Or maybe we could add a button somewhere to call this tool?
Fix #8787
=> Fix Style Customizer

concrete/src/Console/Command.php
The command class has a constant named `RETURN_CODE_ON_FAILURE`.
How about adding the `RETURN_CODE_ON_SUCCESS` too?
FYI, Symfony 5.1 has the constants  `Command::SUCCESS` and `Command::FAILURE`.
=> Add a new constant RETURN_CODE_ON_SUCCESS to the Command class

concrete/dispatcher.php, concrete/src/Install/Preconditions/PhpVersion.php
As stated [here](https://github.com/concrete5/concrete5/blob/5c3af8a6a21f980ae76676865495ebd742fa96a3/concrete/dispatcher.php#L3), the minimum PHP version for concrete5 9 will be 7.2.9 and not 7.2.0.
=> Fix displayed minimum PHP version

concrete/js/build/core/style-customizer/typography.js
When a typography value has disabled the Font Family sub-field, we still have a leftover in the UI.
See for example the palette of a typography with all its values disabled:
After the fix of this PR:
=> Fix visual glitch when disabling font family in typography

concrete/blocks/express_entry_list/controller.php, concrete/blocks/express_entry_list/db.xml, concrete/blocks/express_entry_list/edit.php, concrete/blocks/express_entry_list/view.php
Adds a title format option to the Express Entry List block as discussed in #8282 and initial PR #8405
Also changes the nested description in view template so the description can be displayed even when the title is not set.
=> block-title-format for Express Entry List block #8282

concrete/blocks/google_map/controller.php, concrete/blocks/google_map/db.xml, concrete/blocks/google_map/form_setup_html.php, concrete/blocks/google_map/view.php
Adds a title format option to the Google Map block as discussed in #8282 and initial PR #8405
=> block-title-format for Google Map block #8282

concrete/blocks/rss_displayer/controller.php, concrete/blocks/rss_displayer/db.xml, concrete/blocks/rss_displayer/form_setup_html.php, concrete/blocks/rss_displayer/view.php
Adds a title format option to the RSS Displayer block as discussed in #8282 and initial PR #8405
=> block-title-format for RSS Displayer block #8282

concrete/attributes/textarea/controller.php
Fixes #8964
Problematic output
```
<p>&lt;!--[if IE 9]&gt;&lt;![endif]--&gt;&lt;!--[if IE 9]&gt;&lt;![endif]--&gt;<img src="/application/files/thumbnails/small/2716/0629/5769/houses.jpg" alt="houses.jpg"></p>
```
Fixed output
```
<p><picture><img src="/application/files/thumbnails/small/2716/0629/5769/houses.jpg" alt="houses.jpg"></picture></p>
```
We need to fix it for V9 also
=> [V8] Do not remove picture elements on rendering textarea attribute value

concrete/css/build/core/app/panels/design.less
When we save the custom styles, we have this confirmation dialog:
In Italian the dialog width is not enough:
What about making it a bit wider?
In English this would still look ok:
but in Italian it's much better:
=> [V8] Wider "Apply Style" confirmation dialog

concrete/src/Area/SubArea.php, concrete/src/Permission/Assignment/AreaAssignment.php
I don't know why, but visiting a a rather complex page we have this error:
```
Call to a member function overrideCollectionPermissions() on a non-object
in concrete/src/Permission/Assignment/AreaAssignment.php
Line: 94
```
=> [V8] Fix "call to a member function overrideCollectionPermissions() on a non-object" in AreaAssignment

concrete/src/Package/Package.php
Update getByHandle() method docblocks to corresponding method instead of copy/paste from other method.
=> Small docblock fix in deprecated method

concrete/src/Multilingual/Service/Detector.php
When the site locale detector falls to the site default locale detection, this can cause the whole PHP process to jam (until its timeout is reached).
On this line, look the whole locale object is passed to the result array's first element:
https://github.com/concrete5/concrete5/blob/203eea555989997558bf4431cf19b405b06c80a6/concrete/src/Multilingual/Service/Detector.php#L86
It is fetched here from the site entity object:
https://github.com/concrete5/concrete5/blob/203eea555989997558bf4431cf19b405b06c80a6/concrete/src/Multilingual/Service/Detector.php#L83
And as you can see here it returns an instance of a `Concrete\Core\Entity\Site\Locale` when available:
https://github.com/concrete5/concrete5/blob/203eea555989997558bf4431cf19b405b06c80a6/concrete/src/Entity/Site/Site.php#L280
OK no …
=> Fix site default locale detection

concrete/src/Foundation/Repetition/Comparator.php
Added missing return statement in Repetition Comparator which prevented users from adding event repeat days after event creation. `if` statement was empty so Comparator would improperly return `true` even if the RepeatPeriodWeekDays did not match.
PHP's not equals operator take key/value combination into consideration when comparing so `[1,3] == [3,1]` will be false. The test in `RepetitionComparatorTest.php` suggests that the array keys are not important so I corrected the Comparator to use `array_diff` rather than update the test.
Fixes #9227
=> Correct missing return statement in Comparator

concrete/src/Form/Service/Widget/DateTime.php
When adding a datetime form element, if the time resolution is set to hours (e.g. 3600) and the time format is set to display 12-hour format with AM/PM indicator, the AM/PM selector is not added to the form.
e.g. 
```
$date =Core::make('helper/form/date_time');
echo $date->datetime('startDate', $entity->getStartDateTime(), false, true, null, 3600);
```
The form shows a date picker, then a drop-down hour selector with numbers 1-12. No AM/PM selector is added to the form.
The code changes look a little weird, but all I've done is move the `if ($timeFormat === 12)` and `if ($stepSeconds !== 0)` out of the `if ($stepMinutes !== 0)` block.
=> Show am/pm selector when time format is 12-hour but time resolution is set to hours

concrete/src/Config/Driver/Redis/RedisLoader.php
We were passing a Generator instance into `\Redis::del` which lead to a fatal error on package uninstall.
=> Fix redisdriver clearNamespace method

concrete/src/Validation/BannedWord/Service.php, tests/tests/Validation/BannedWordTest.php
I'd fixed `hasBannedWords` function to support multibyte characters in #9070, but I broke backward compatibility.
As suggested by @jaromirdalecky , it should ban string has whole banned words, instead of a part of the words.
It's not best for agglutinative languages like Japanese, because we don't use white spaces in sentences, but I'll try to support wildcard like `*ban*` in version 9.
On 8.5.5, I think we should just keep backward compatibility.
=> Fix hasBannedWords to keep backward compatibility

concrete/blocks/core_conversation/form.php
Followed by https://github.com/concrete5/concrete5/pull/9028#issuecomment-743151032
=> [8.5.x]Avoid implode(): Invalid arguments passed on core conversation block

concrete/attributes/select/controller.php, concrete/attributes/select/form.php, concrete/blocks/tags/controller.php, concrete/blocks/tags/view.php
Select option values are translatable on the "Translate Site Interface" page.
However, option values are not displayed as localized labels when you use tags block.
Also, `.ccm-block-tags-tag-selected` class is not applied to the selected tag, because the option value in the filtered URL is translated, but compared in view.php with untranslated option value.
Option values are not displayed as a localized string on the composer window.
It's not a serious issue, but it should be translated.
=> [V8] Fix some issues when using tags on multilingual site

concrete/src/Permission/IpAccessControlService.php
The ban duration of `IpAccessControlCategory` is in seconds, not minutes (see [here](https://github.com/concrete5/concrete5/blob/ab9be4e74ec460fa6c823f97e0b6705714c8c7c9/concrete/src/Entity/Permission/IpAccessControlCategory.php#L308)).
=> [V8] Fix duration of IP bans

concrete/src/Permission/IpAccessControlService.php
The ban duration of `IpAccessControlCategory` is in seconds, not minutes (see [here](https://github.com/concrete5/concrete5/blob/ab9be4e74ec460fa6c823f97e0b6705714c8c7c9/concrete/src/Entity/Permission/IpAccessControlCategory.php#L308)).
=> [V9] Fix duration of IP bans

build/libraries/built-assets.js, build/package.json
The `build/package.json` file currently defines these scripts:
- `npm run git-skip`: tell git to ignore the built assets
- `npm run git-unskip`: tell git to stop ignoring the built assets
Those scripts are useful while working with the built assets: we don't want to see them as to be committed while we build them for development.
BTW we still miss an easy, fast, and safe way to revert those built assets to the version committed in the repository (which is very useful when we perform a git pull or rebase).
So, what about adding a `npm run git-revert` script?
=> Add git-revert script to revert built assets

concrete/src/Mail/Service.php
=> [V8] Fix: make email log readable by decode quoted printable text

concrete/controllers/single_page/dashboard/users/groups/message.php
#7877 doesn't work correctly by a typo. I believe this bug exists since 8.5.3
=> [V8] Fix: enable to send private message to all groups at once

concrete/controllers/single_page/dashboard/extend/install.php, concrete/single_pages/dashboard/extend/install.php
I found these when I worked on https://github.com/concrete5/concrete5/pull/9332.
But making another pull request to keep things separated.
=> Remove some deprecated & duplicate codes from package install page

concrete/blocks/express_form/controller.php, concrete/src/Express/Attribute/AttributeKeyHandleGenerator.php, tests/tests/Express/AttributeKeyHandleGeneratorTest.php
When adding Express Form with multibyte only fields, it generates the same attribute handle 'attribute_key' for those attribute keys.
https://user-images.githubusercontent.com/514294/105643220-e2223300-5ed1-11eb-94d6-634fe15cb19f.mov
https://user-images.githubusercontent.com/514294/105643226-e77f7d80-5ed1-11eb-80d8-a9cfa9d4e167.mov
It causes because the information that missing existing attribute keys also stored in the request cache.
Let's store already generated handles in the instance of the generator to avoid the request cache effect.
We need to pick this fix for V9 also.
=> [V8] Fix bug: Express Form can generate same attribute keys for multiple attribute keys

concrete/blocks/document_library/controller.php, concrete/blocks/document_library/db.xml, concrete/blocks/document_library/edit.php, concrete/src/Updater/Migrations/Migrations/Version20210128214511.php
This PR:
- Fixes the 'in all sets' filter, it didn't work because it was attempting to check multiple rows in a join which as far as I'm aware is not possible. Instead we use a subselect that selects a count of the selected sets and match against the count we expect.
- Adds a "Show Folders" option that defaults to checked for new and existing blocks that hides folders and their contents. One caveat is if there is no selected folder, we will search all folders and show results from everywhere instead of just at the top level.
=> Fix document library 'in all sets' filter and add a folder hiding option

concrete/elements/block_area_footer.php, concrete/src/Area/Layout/Preset/Provider/Manager.php, tests/tests/Area/AreaLayoutPresetTest.php
This makes it so that sites are no longer bricked if a theme preset is re-saved as a user layout preset.
The layouts themselves that have been applied may look strange – I tried to make them actually apply the styles of the theme preset but that required a lot of recursive code and it was just too much potential error for too little gain. Instead, just use the theme presets and don't re-save them as user presets. There's no gain to resaving them as user presets. 
Additionally I've made it so you cannot re-save theme presets as user presets in the UI.
=> Fix #8819 (v9)

concrete/blocks/express_form/controller.php, concrete/src/Express/Attribute/AttributeKeyHandleGenerator.php, tests/tests/Express/AttributeKeyHandleGeneratorTest.php
Refs #9342
How to reproduce
https://user-images.githubusercontent.com/514294/105901513-d44ee800-6060-11eb-9d3e-a44489b1cff7.mov
=> [V9] Fix bug: Express Form can generate same attribute keys for multiple attribute keys

concrete/elements/block_area_footer.php
Looks like the "disabled" class was added twice, but it created invalid HTML due to the extra quotation mark
=> Fix: invalid HTML

concrete/elements/express/form/form/author.php
Adds an additional check to ensure `getUserID()` isn't run on `null` when an author isn't set for an Express entry.
Fixes error when editing an Express entry without an author in Dashboard -> Express, in the form view.
=> Checks author isn't null before getting ID

concrete/src/Express/Form/Control/SaveHandler/AuthorSaveHandler.php
If an author is set on an Express Entry, you cannot unset that user.
Added an `else` to the `if` condition to unset the current user.
=> Unsets author in Entry when it's cleared in Express form

concrete/src/Page/Search/IndexedSearch.php
This PR does the same thing as #9365, see the discussion there and in the related issue for more info
=> Fix page search index block order in 8.6

concrete/src/Page/Search/IndexedSearch.php, tests/tests/Page/Search/IndexedSearchTest.php
This PR prevents raw javascript added to blocks from being indexed in the page index.
Imagine a situation where a page has an html block with a large inline <script> tag. Today, the search indexer will strip the *tags* but will leave the *contents* of that script tag to be indexed. With this change, an extra step happens before stripping tags that normalizes the HTML and then removes script tags and their contents.
This isn't exactly a full solution, it still has edge cases that slip past. For example if a block has contents like:
```html
<script>
//</script>
alert('foo');
</script>
```
`alert('foo')` will be included in the search content. Most script content in blocks will be well formed though so I'd argue this is an adequate solution for now until we find a reason to use a DOM parser …
=> Strip script tag contents from the page search index

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/mail/method.php, concrete/controllers/single_page/dashboard/system/mail/method/test.php, concrete/single_pages/dashboard/system/mail/method.php, concrete/src/Mail/Transport/Factory.php
At the moment, ~~concrete5~~ ConcreteCMS always use `localhost` ([the default value](https://github.com/zendframework/zend-mail/blob/release-2.7.3/src/Transport/SmtpOptions.php#L20)) in the `HELO`/`EHLO` step of the SMTP connection procedure.
Some SMTP delivery services *require* a registered domain to be used instead of `localhost`.
Tested with the [SMTP relay service of Google Workspace](https://support.google.com/a/answer/176600?hl=en), and already in production for us.
=> [V8] Let user specify the SMTP HELO/EHLO domain

concrete/blocks/core_conversation/form.php
This is a more complete fix for https://github.com/concrete5/concrete5/commit/5b8a2a1f66cd3c93913605c7652ca9bb14456a19
As noted in the comment to that commit, the problem is that `$fileAccessFileTypesBlacklist` is only being set for the add task. Lines 35--39 need to be taken out of the conditional beginning on line 7, or otherwise refactored to make the form work when editing the block.
=> Avoid implode() invalid arguments when editing block

concrete/src/Routing/ClosureRouteAction.php
Gotten multiple reports like #9366 – basically any fractal response returned from our API was broken. OAuth2 fully broken in the develop branch.
This was broken in https://github.com/concrete5/concrete5/pull/8289
This should fix the issue.
=> fix broken API

concrete/blocks/document_library/controller.php
New "show folders" option only worked when a file set was also selected. However, it's not clear from the label that these two settings go together. It would be more self-explanatory if the "show folders" option worked independently of other settings. This change simply conditionally modifies the query in the view method based on `$this->hideFolders`.
=> Bugfix: make "show folders" option work without filesets

concrete/blocks/file/controller.php, concrete/blocks/html/controller.php, concrete/controllers/dialog/page/delete.php, concrete/src/Attribute/Controller.php, concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
These are fixes for errors/warning occurring with PHP 7.3 and 7.4 when "Consider warnings as errors" is set.
Also, all fixes have already been validated by @aembler in PRs against branch 8.5.x and this PR is being submitted on his suggestion.
=> Fix/php7.3 and 7.4 errors

concrete/controllers/dialog/page/delete.php, concrete/views/dialogs/page/delete.php
This PR fixes the following error/warning that occurs with PHP 7.3 And 7.4 when "Consider warnings as errors" is set and the user goes to Page Settings and then clicks on Delete Page:
Undefined variable: sitemap
/Applications/MAMP/htdocs/c855/concrete/views/dialogs/page/delete.php(21): Whoops\Exception\ErrorException->null	
/Applications/MAMP/htdocs/c855/concrete/views/dialogs/page/delete.php(21): Whoops\Run->handleError	
We've initialized $sitemap to fix it.
=> Fixing Page Settings -> Delete Page

concrete/views/panels/details/page/location.php
This PR fixes the following error/warning that occurs with PHP 7.3 And 7.4 when "Consider warnings as errors" is set and the user goes to Page Settings and then clicks on Location:
Exception Occurred: /Applications/MAMP/htdocs/c855/concrete/views/panels/details/page/location.php:9 Undefined variable: sitemap (8)
We've initialized $sitemap to fix it.
=> Fixing Page Settings -> Location

concrete/blocks/desktop_latest_form/controller.php
This PR fixes the following error/warning that occurs with PHP 7.4 when "Consider warnings as errors" is set and the user logs back in to c5:
Whoops\Exception\ErrorException thrown with message "Trying to access array offset on value of type bool"
Stacktrace:
#38 Whoops\Exception\ErrorException in /Applications/MAMP/htdocs/c855/concrete/blocks/desktop_latest_form/controller.php:27
#37 Whoops\Run:handleError in /Applications/MAMP/htdocs/c855/concrete/blocks/desktop_latest_form/controller.php:27
We've added some checks and initialized $legacyDateCreated to fix it.
=> Fixing Welcome Back Page (Desktop Latest Form Block Type)

concrete/src/Attribute/Controller.php, concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php
This PR fixes the following error/warning that occurs with PHP 7.3 And 7.4 when "Consider warnings as errors" is set and the user tries to save/delete/publish a page changes (edit mode -> save/delete/publish):
Exception Occurred: /Applications/MAMP/htdocs/c855/concrete/src/Page/Type/Composer/Control/CorePageProperty/NameCorePageProperty.php:71 Trying to access array offset on value of type null (8) 
We've added some checks to fix it.
=> Fixing page edit mode

concrete/blocks/html/controller.php, concrete/blocks/html/form_setup_html.php
This PR fixes the following error/warning that occurs with PHP 7.3 And 7.4 when "Consider warnings as errors" is set and HTML block is dragged and dropped on a page:
Undefined variable: content
/Applications/MAMP/htdocs/c855/concrete/blocks/html/form_setup_html.php(3): Whoops\Exception\ErrorException->null
=> Warning/error on HTML block drag and drop

concrete/js/build/core/app/dialog.js
From CKEditor 4.13, it adds `overflow:hidden` to `<body>` element when it opens its dialog by adding `.cke_dialog_open` class. However, it conflicts with concrete5 core dialog.js (jQuery UI dialog) because it does the same thing by adding `style="overflow: hidden"`.
Do not add `style="overflow: hidden"` attribute if overflow of `<body>` element is already hidden.
Since Concrete 8.5.5 (Oct 14, 2020, on GitHub). 8.5.4 still uses CKEditor 4.12.
=> Fixes #9419

concrete/single_pages/dashboard/blocks/types/view.php
The variable is not supposed to be $num but $numActive.
Since it's going to be 0 either way, it's better to simply echo 0.
Please refer to this slack.
https://concrete5.slack.com/archives/C2N3FLUBW/p1617266646210300
=> Fix dashboard's block types view. Return 0 when $numActive is less than 0.

concrete/src/Form/Service/Form.php
This pull request fixes #7391 
I simply used t() function to escape values passed on to $form->select() function.
=> Form service / select doesn't escape by default: fixed

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
This PR fixes the exception which is thrown when a user tries to attach his facebook account on concrete5 8.5.5.
The bug was introduced from this commit https://github.com/concrete5/concrete5/commit/4123eab28d33cf19d85f9bc3b148695eb3f0c91e.
Though Scrutinizer / Inspection recognized this, seems it was ignored.
```
An exception occurred while executing 'SELECT binding FROM OauthUserMap WHERE (namespace = ?) AND (user_id = ?)' with params ["facebook", {"uID":"47","uName":"c5j_biplob","uGroups":{"2":"2","3":"3","1":"1"},"superUser":false,"uTimezone":null,"error":""}]: Object of class Concrete\Core\User\User could not be converted to string
```
=> [Fix] Can't attach a facebook account

concrete/blocks/switch_language/controller.php
This PR fixes the following exception on switching language using switch_language block
See https://github.com/concrete5/concrete5/pull/9446
=> [v9][Fix] Error on switching language using switch_language block

concrete/blocks/switch_language/controller.php
This PR fixes the following exception on switching language using switch_language block
=> [v8][Fix] Error on switching language using switch_language block

concrete/src/Cache/Page/RedisPageCache.php
fix where cache item can be null.
This relates to issue https://github.com/concrete5/concrete5/issues/9457
=> Cache item can return null

concrete/controllers/single_page/dashboard/system/environment/logging.php
This PR fixes issue  #9445  with Channel Logging settings that cannot be changed on Logging Settings dashboard page.
=> Channel Logging settings can't change

concrete/attributes/text/form.php, concrete/src/Attribute/Key/Factory.php
Enbale translation for text attributes' placeholders. Useful when adding express forms on the frontend. [V9]
=> [V9] Localization support for text attr placeholders

concrete/attributes/text/form.php, concrete/src/Attribute/Key/Factory.php
Enbale translation for text attributes' placeholders. Useful when adding express forms on the frontend.
=> Localization support for text attr placeholders

concrete/src/Mail/Service.php
We need this because, in case of connection errors (eg wrong login), the SMTP transport may throw an exception when it gets destructed, hiding the actual connection problem.
(See https://github.com/concrete5/concrete5/pull/9375#issuecomment-835565053 for example).
=> [V8] Ignore errors when closing the mail transport

concrete/authentication/twitter/controller.php
Keys copied from the Twitter developer portal may contain whitepace. This causes Twitter logins to silently fail. Fix is a pair of trim's before saving the keys.
=> Twitter login fails

tests/tests/Utility/Service/TextTest.php
Japanese text in test means "Japanese person" but the sentence is
clearly referring to "Japanese language". Change the character to mean
"language".
=> Fix: Japanese text in test

concrete/single_pages/dashboard/system/api/integrations/edit.php, concrete/single_pages/dashboard/system/api/integrations/view_client.php, concrete/src/Entity/OAuth/Client.php
This PR gives users the ability to specify multiple valid redirect urls for a given oauth2 client. Before this change we could only ever have one client per domain if we wanted to maintain proper oauth2 security.
=> Use | characters to provide multiple valid redirect urls for an oauth2 client

concrete/config/concrete.php, concrete/src/Error/Handler/ErrorHandler.php
This is largely inspired by [laravel's implementation](https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Exceptions/WhoopsHandler.php#L61) which leverages whoops' built in hide support. We go a small step further and allow the ability to hide config items as well.
The way this is used is you specify the superglobal key or config item you want to hide in the appropriate superglobal or config array. So for example if you're using composer based concrete5 and you want to hide the password and hostname environment variables for the database you might have:
```php
return [
'debug' => [
'hide_keys' => [
'_ENV' => ['DB_PASSWORD', 'DB_HOSTNAME'],
]
]
];
```
This same thing works for all superglobals for example if you want to hide a …
=> Add the ability to hide specified superglobal or config keys when rendering whoops error pages

concrete/attributes/boolean/form.php, concrete/src/Attribute/Key/Factory.php
Enbaling translation for checkbox attributes' labels. Useful when adding express forms on the frontend.
=> [V9] localization support for checkbox attr label

concrete/js/build/core/file-manager/search.js
If you try to use the context menu to select a single file it will not work.
This fixes an issue when using the multi-file selector in version 8
Its only applicable to v8 since version 9 file selector is different
=> [v8] fix select on single file in multi-file selector

concrete/src/Mail/MailServiceProvider.php
#9484 (for V9) and #9483 (for V8) aren't enough: since the mail transport is a singleton, its instance is released only when the application life-cycle ends (that is, at the end of the request &rarr; response process).
Having the mail transport being a singleton may be problematic when the SMTP connection is closed prematurely by the SMTP server (for example because of wrong authentication): in this case, with the current implementation of the SMTP client, the state is undetermined, and we shouldn't re-use the client (for example, we see a "connection already closed" error instead of "wrong login/password").
It's much safer to create a new transport client when we need it.
=> [V9] Don't make the mail transport a singleton

concrete/src/Localization/Address/Formatter.php, tests/tests/Localization/Address/FormatterTest.php
This should fix issue pointed out in #9316 with previous fix attempt at #8539.
The problem is because concrete5 stores its own lists of states/provinces:
https://github.com/concrete5/concrete5/blob/f3ff41f3b92074b160aad96f0de6438cb9308807/concrete/src/Localization/Service/StatesProvincesList.php#L19
The state/province codes do not match what is expected for `commerceguys/addressing`, e.g. for Tokyo, Japan the correct "code" would be "Tokyo" or "JA-xx" where `xx` is the concrete5 code:
https://github.com/commerceguys/addressing/blob/311040bd78ea2ea82105dd1f17205c449ac8de47/resources/subdivision/JP.json#L65-L69
In addition, c5 provides states/provinces for some countries that `commerceguys/addressing` does not know as far as my observations went. An example of such country is Ireland: …
=> Fix "unknown" state/province formatting in addresses

concrete/src/Install/Preconditions/RequestUrls.php
Give a specific error message for when ajax request fails which could be reasons different to this check. For example, if the server responds with a status code of 500, it's unlikely related to this check, but many forum posts ([one example here](https://www.concrete5.org/community/forums/installation/installation-c5-ver.8.5.2-fail-during-checking-required-items-su)) show that people get stuck on this thinking the problem has to do with PATH_INFO. This new error message will at least point people in the right direction.
=> Improve error messages

concrete/config/app.php
Fixes #9507
Before, token included in the asset cache file, so concrete5 generates these caches forever
After, token never included in the asset cache file
=> [V8] Do not combine dropzone js

concrete/src/Page/Collection/Collection.php
I've just created this pull request for moving the discussion of #9126 to forward. It's still a work in progress. At least, I'd like to replace all insert queries in this class at this pull request.
=> [V9] Avoid to use Connection::executeQuery for insert queries in Collection class

composer.lock, concrete/controllers/backend/file.php, tests/tests/Controller/Backend/FileTest.php
The tests should make it clear how this behaves differently now, basically we disallow any hostnames that are either integers or hexadecimal values.
We use [ip-lib](https://github.com/mlocati/ip-lib/) to deal with the complex parts of parsing and classifying IP addresses, in this case the actual issue is we're parsing the plain text version of the url while curl (or whatever the http client here is) is actually parsing the hostname from a hexadecimal number or octal or integer into an IP address before sending the request. With that in mind it'd be much better if we just did that same conversion ourselves before sending the IP to ip-lib either on our own or maybe with some tooling ip-lib provides but that's not something that exists yet and I'm not sure I fully understand the problem well …
=> Block ip variants from importing

.github/workflows/phpunit.yml
Scrutinizer needs at least 2 commits to identify pulls so without 2 it ends up hanging for 10 minutes.
=> Use fetchdepth 2 to fix scrutinizer

concrete/config/concrete.php
This PR follows up #9506 with some default values as recommended in the comments.
One caveat to adding entries here as opposed to adding them to `application/config/concrete.php` is there's no way to reenable some of these things without doing something like setting these config values in code.
=> Set default hide keys for environment variables config and cookies

concrete/src/Permission/Access/ListItem/EditPagePropertiesPageListItem.php, concrete/src/Permission/Access/ListItem/EditUserPropertiesUserListItem.php, concrete/src/Permission/Access/ListItem/ViewUserAttributesUserListItem.php
Error message
```
Whoops\Exception\ErrorException thrown with message "count(): Parameter must be an array or an object that implements Countable"
Stacktrace:
#36 Whoops\Exception\ErrorException in /path/to/concrete/src/Permission/Key/EditPagePropertiesPageKey.php:145
#35 count in /path/to/concrete/src/Permission/Key/EditPagePropertiesPageKey.php:145
#34 Concrete\Core\Permission\Key\EditPagePropertiesPageKey:validate in /path/to/concrete/src/Permission/Response/PageResponse.php:133
#33 Concrete\Core\Permission\Response\PageResponse:canEditPageProperties in /path/to/concrete/src/Permission/Checker.php:52
#32 Concrete\Core\Permission\Checker:__call in /path/to/concrete/elements/page_controls_footer.php:114
#31 include in /path/to/concrete/src/View/View.php:476
#30 …
```
=> Fix "count() Parameter must be an array" if the current use doesn't have allowed property

concrete/src/Multilingual/Page/Section/Section.php
We currently use the miltilingual feature on our website and we've notice quite a heavy amount of calls to the Section::getLocaleFromHomePageID to the database. Adding the above the request cache like it does for pages already has reduced this dramatically.
Before
After
=> Multilingual Page Calls Expensive DB calls

concrete/controllers/backend/file.php, concrete/src/Http/Client/Client.php
This PR adds a method to the c5 zend based client that allows sending requests without following any redirects. Additionally I've updated the file download call to use this new method.
=> Add http client method to send request without following redirects

concrete/single_pages/dashboard/extend/connect.php
Since the subject is "token and client ID" I think we should use plural
=> Fix typo in "wrong marketplace credentials" error string

concrete/controllers/element/dashboard/express/menu.php, concrete/controllers/single_page/dashboard/system/express/entities.php
`\Doctrine\ORM\EntityRepository::findAll()` doesn't accept any parameters.
IMO this is just a typo.
Issue
Fixed
=> [V8] Fix display order of express entities in dashboard

concrete/src/Controller/Traits/DashboardExpressEntryListTrait.php
This is the version 9 fix of this #9162
also removed $datetime_format from `$writer->insertEntryList($entryList,$datetime_format)`; as it only accepts 1 parameter
=> [v9] use the config for datetime_format for csv export

concrete/config/concrete.php, concrete/src/Express/Export/EntryList/CsvWriter.php, concrete/src/Page/Controller/DashboardExpressEntriesPageController.php
This fixes the default formatting of exports in the express export csv writer
Currently it uses the text 'ATOM' which produces weird output like `AMEDT-0400Jul`
This changes brings the defaults in line with version 9 and uses the `DATE_ATOM `constant
I also removed $datetime_format from `$writer->insertEntryList($entryList,$datetime_format);` as it only expects one parameter
=> [v8]Fix default formatting of datetime exports in express export csv

concrete/src/User/PrivateMessage/Limit.php
Can't send a notification email when you hit the maximum limit of private messages.
```
Error thrown with message "Class 'Concrete\Core\User\PrivateMessage\Facade' not found"
Stacktrace:
#26 Error in /path/to/concrete5/concrete/src/User/PrivateMessage/Limit.php:68
#25 Concrete\Core\User\PrivateMessage\Limit:notifyAdmin in /path/to/concrete5/concrete/src/User/PrivateMessage/Limit.php:43
#24 Concrete\Core\User\PrivateMessage\Limit:isOverLimit in /path/to/concrete5/concrete/src/User/UserInfo.php:362
#23 Concrete\Core\User\UserInfo:sendPrivateMessage in /path/to/concrete5/concrete/controllers/single_page/dashboard/users/groups/message.php:112
#22 Concrete\Controller\SinglePage\Dashboard\Users\Groups\Message:sendMessage in /path/to/concrete5/concrete/controllers/single_page/dashboard/users/grou …
```
=> [V8] Private messages max limit fix

concrete/src/Entity/Attribute/Value/Value/TopicsValue.php
=> [V9] Fix: Page type default topic attribute values are not set on the newly created page type

concrete/blocks/page_attribute_display/controller.php
Fixing issues referenced here: https://github.com/concrete5/concrete5/issues/9568
9.0.0a3
The block is currently not adding default values to inputs when adding a new block. It is also declaring $dateFormat twice, once in the controller and then again in the controller add() method (to a second format, overwriting the first it is set to.) The lack of default values for the thumbnail inputs is then causing error when saving.
I'm setting the variables in the add() method to get default values to the view correctly.  I removed the colon from the dateFormat string for better display and all is working well.
Couple questions for @aembler or @tylerryan ...  as you can see I left one line commented out.  Do we want to keep the $dateFormat string like it's declared in the controller, or do we …
=> Page Attribute Display - Fix thumbnail w/h & dateFormat issues #2

concrete/config/site.php
Let's remove query parameters like `query` or `utm_source` from canonical tag to improve SEO.
Issue: #8259
=> [V9] Add more excluded query parameters for canonical tag

concrete/controllers/single_page/dashboard/pages/types/output.php
This fixes the bug when a user who can edit page type is given access denied when clicking edit on the page type outputs.
This happens when the session cache system is set to any system with a delay in read/writes such as redis/memcahced or a slow filesystem.
Using the Session::set() and Redirect::url(\URL::to($c))->send(); together means that the variable isn't actually saved before the redirect happens.
Updating the methods always results in the session actually being set
Though we should remove Session::set/Session::get facades from the core as we advise not to use them..
This PR also cleans up some of the methods, removes facades and adds extra documentation
=> [v8] fix #9582 - Fix session set not working correctly on redirect in redis/memcached/slow filesystem

composer.lock, concrete/composer.json, concrete/controllers/backend/file.php, concrete/controllers/single_page/dashboard/system/environment/geolocation.php, concrete/controllers/single_page/dashboard/system/permissions/blacklist/range.php, concrete/controllers/single_page/dashboard/system/permissions/trusted_proxies.php, concrete/src/Entity/Permission/IpAccessControlEvent.php, concrete/src/Entity/Permission/IpAccessControlRange.php, concrete/src/Permission/IPRange.php, concrete/src/Permission/IPService.php, concrete/src/Permission/IpAccessControlService.php, concrete/src/Permission/PermissionServiceProvider.php, tests/tests/Permission/IPServiceTest.php, tests/tests/Session/SessionValidatorTest.php, tests/tests/User/Login/LoginServiceTest.php
Since [version 1.17.0](https://github.com/mlocati/ip-lib/releases/tag/1.17.0), IPLib is able to parse addresses in non-quad-dotted format.
For example, `0xff.010` is an acceptable IP address for many `inet_aton` and `inet_addr` implementations, and it's like writing `255.0.0.8`:
For safety reasons, it's better to be able to parse such addresses.
PS: I'll also submit a PR for v9 asap
=> [V8] Upgrade IPLib to version 1.17.0

concrete/src/Updater/Migrations/Migrations/Version20210729191135.php
This fixes a misspelling in the latest migration on the 9.0rc branch which causes c5:update to fail
=> [9.0rc] fix migration misspelling

concrete/src/Workflow/Request/ApprovePageRequest.php
This update should allow page workflow requests to disclose the scheduled publishing dates of page versions that have been submitted for approval. This could be useful for showing messages to the approver about when a pending page version is scheduled.
=> Allow publish dates to be accessible for page workflow requests

concrete/src/Console/Command.php
With older versions of Symfony Console the result of the execute method of CLI commands may be anything.
BTW recent versions are much stricter: `execute()` must return an integer.
So, what about making developers life easier when they use the `handle` method?
=> Accept non-integer results from the handle() method of CLI commands

concrete/src/Application/UserInterface/Menu/Item/Controller.php
Allows menu items to set icons with full FontAwesome icon spec string such as fas and far.
Defaults to prior behaviour of prefixing "fa fa-" if full  FontAwesome icon string is not specified.
=> Make menu item icons fully compatible with latest FontAwesome

.github/workflows/phpunit.yml, composer.lock, concrete/composer.json, concrete/src/Encryption/PasswordHasher.php, concrete/src/User/User.php, concrete/src/Utility/Service/Identifier.php, tests/config/concrete.php
This resolves #4777
We have a high enough minimum PHP version that we can just drop this dependency without needing another to replace it. Hautelook passwords do verify with php's built in password tools as far as I've been able to test so I think we're solid there, we just need to start rehashing passwords when `password_needs_rehash()` says it needs to be rehashed.
=> Remove hautelook in favor of using the php stdlib password_hash functionality

concrete/js/build/core/app/search/base.js
fixes #9800 by moving the click handler to the thead element rather than the div so the event propagation finds the sortable columns after they are loaded/changed
=> [v8] fix #9800

concrete/src/Logging/Search/ColumnSet/Column/MessageColumn.php, concrete/src/Logging/Search/ColumnSet/DefaultSet.php, concrete/src/Mail/Service.php
fixes #9760 
Re-adds `makenice` to logs
Also re-adds the quoted printable decode if the email has that encoding enabled. (was in v8)
=> [9.0rc3]fixes #9760 - Make Logs nicely formatted again

concrete/js/captcha/recaptchav3.js
Issue 9780
When a form using reCAPTCHA V3 is loaded a time-out timer starts running. After 2 minutes the code expires and every form submission after this 2 minutes is not accepted and an error is given.
All we have to do is call grecaptcha.ready again a few seconds before it times out.
=> Prevent ReCAPTCHA timeout

concrete/controllers/single_page/dashboard/system/seo/urls.php
When checking the checkbox on "Remove index.php from URLs" and saving the changes, the response Success message, which contains the .htaccess changes has improper styling.
These minor changes fix that issue.
=> Minor styling on /dashboard/system/seo/urls page.

concrete/controllers/panel/sitemap.php, concrete/src/Permission/Access/Access.php
Same as #9489 but for version 9
Fixes #9481 and #8868
I want to run PHP CS Fix for old-style files, but couldn't due to #9830
| Username | Group |
| ---- | ---- |
| demo | Administrators |
| author1 | Authors |
| author2 | Authors |
=> [V9] Fix to show page drafts created by the current user

concrete/src/Page/Type/Composer/Control/CorePageProperty/UrlSlugCorePageProperty.php
Since it is sanitized in UrlSlugCorePageProperty::getRequestValue() and the undefined is replaced with blank strings, the
Change it to sanitize only if it is defined.
[Behaviors that are considered to be expected]
Composer's URL Slug will not send fields if they are not updated.
The null is set in UrlSlugCorePageProperty::publishToPage(), and the current handle is used in HandleGenerator::generate() in Page::update().
=> [V9 RC] Fix #9834

concrete/attributes/topics/controller.php
Same as #9492 but for Concrete5 version 8
cherry picked from commit 786252c6bee5501edb63d39e3a57a8cdce0efa26
=> [V8] tweaks to topics search index value

.github/workflows/phpunit.yml
This PR adds testing for 8.1 and allows it fail
It also removes the unnecessary composer install before composer update in highest dependencies
Due to continue-on-error still marking builds as failed I had to add it in a few more steps.
See : https://github.com/actions/toolkit/issues/399
This means that if the 8.1 builds fail it doesn't show up as a red X until GitHub introduce actual allowed failures
=> [v9rc4] Add php 8.1 testing (allow failures)

build/assets/cms.scss, concrete/blocks/feature/controller.php, concrete/blocks/feature/form.php, concrete/blocks/feature/view.php, concrete/src/Attribute/FontAwesomeIconFormatter.php, concrete/src/Html/Service/FontAwesomeIcon.php, concrete/themes/atomik/blocks/feature/templates/stacked.php, concrete/themes/atomik/blocks/feature/templates/stacked_primary.php, concrete/themes/elemental/blocks/feature/templates/hover_description/view.php, tests/tests/Html/Service/FontAwesomeIconTest.php
The feature block in version8 stores icon names without prefixes like `fa fa-`.
It already fixed to stores full icon class names like `fas fa-address` to support FontAwesome 5.
However, it is a backward compatibility issue. When you update Concrete from version 8 to 9, all feature block instances can't render icons correctly.
So I added a simple helper class to make it enable to create  Font Awesome`<i>` element objective way.
It can accepts old class names and convert it to compatible ones.
Additionally, I changed the icon picker to a new Vue component, so it also fix #9691 .
**IMPORTANT: Do not merge this pull request before https://github.com/concrete5/bedrock/pull/164 merged**
=> [V9RC] Improvement of backward compatibility, usability for font awesome icons in feature block

concrete/src/Application/UserInterface/Menu/Item/Controller.php
The first pull missed some prefixes. This allows the whole group, free and pro.
Thoughts triggered by discussion in https://github.com/concrete5/concrete5/pull/9835, so original fix will now be out of date.
=> Fix some missing prefixes

concrete/src/Http/HttpServiceProvider.php
Disabling core middlewares can only be done by creating "passthru" middlewares (as very well [described here](https://documentation.concrete5.org/tutorials/how-to-add-replace-or-remove-middleware)).
What about letting users to disable a middleware (for example `core_xframeoptions`) simply by writing this to the `application/config/app.php` file?
```php
return [
'middleware' => [
'core_xframeoptions' => false,
],
];
```
=> Make it so users can disable core middlewares

concrete/controllers/single_page/dashboard/system/express/entities/order_entries.php
One of our clients deleted an express entry just before reordering the entries and got this exception!
=> [v8] Avoid Call to a member function setEntryDisplayOrder() on null

concrete/controllers/single_page/dashboard/system/express/entities/order_entries.php
One of our clients deleted an express entry just before reordering the entries and got this exception!
=> [v9] Avoid Call to a member function setEntryDisplayOrder() on null

concrete/src/Package/Package.php
Fixes #10069 – something about the new auto commit detection breaks block reinstallation if the block database table already exists in the table and there are no queries to run. The way to fix this I think is to only start a transaction and commit it if there are actual queries to run.
=> Fix #10069

concrete/config/concrete.php, concrete/src/Api/OAuth/Controller.php, concrete/src/Encryption/PasswordHasher.php, concrete/src/Entity/User/User.php, concrete/src/User/User.php, tests/tests/Encryption/PasswordHasherTest.php
PHP has functionality to determine if a password hash matches expected hash settings, this gives us the ability to detect when hashes should be "upgraded" during the login procedure which makes it so users are always kept on the latest secure hash.
We did something similar in the past to support upgrading from legacy passwords to bcrypt passwords, this change takes it the full distance by upgrading bcrypt passwords as needed.
Some extra notes
- Cost makes sense still as long as you're sticking with bcrypt. However if you decide to use argon cost is no longer a logarithmic integer, it's a memory value or a time value. For this reason I've replaced the "hash_cost_log2" config item with a "hash_options" array that gets provided during password hashing / rehash checking. I made sure to keep …
=> Rehash passwords when needed

composer.lock, concrete/composer.json
See https://github.com/concrete5/concrete5/issues/9769#issuecomment-974084108 and https://github.com/concrete5-community/translation-library/commit/877e645dafa8c488385cfdd7c48418d98b335547
=> Upgrade translation-library from 1.7.0 to 1.7.1

concrete/config/install/base/single_pages/dashboard.xml
They are useless, and translators may see odd translatable strings, like for example this one:
=> Don't add spaces in meta_keywords attribute values

concrete/themes/atomik/elements/footer.php
I guess we should have `title` instead of `class` here, right?
=> Fix title of footer link to concretecms.org

concrete/views/dialogs/language/update/details.php
=> Fix position of caption in Language Details dialog

concrete/src/Console/Command/RunSchedulerInForegroundCommand.php
1. none of the CLI command is translated at the moment
2. CLI commands are almost only for people with a technical knowledge (and techy people can often understand English)
=> Don't translate strings in concrete:scheduler:run-dev CLI command

concrete/src/Updater/Migrations/Migrations/Version20211102171600.php
What about simplifying translators' life by saving them a few strings to be translated?
=> Avoid duplicated translatable strings with untranslatable chunks

concrete/blocks/core_conversation/form.php
When using PHP 8+, we can't add Conversation block types to pages because of "Undefined variable" errors.
Let's fix it.
=> Fix "variable is undefined" errors when adding Conversation blocks

concrete/controllers/single_page/dashboard/system/seo/codes.php, concrete/single_pages/dashboard/system/seo/codes.php
**What this does**
This change is for the Tracking Codes dashboard page at /dashboard/system/seo/codes.
On submit, the browser base 64 encodes both the header and footer data and submits those values, instead of the original scripts pasted in. To avoid showing the base 64 encoded values, the values are copied into hidden fields and the original input fields are disabled (so they won't be sent).
Server side, `base64_decode` is called on the submitted values, so that they are saved to the config as originally submitted. 
**Why is it needed**
This is needed to prevent Mod Security, installed on most cPanel systems, from being triggered when tracking codes are POSTed to the server. When Mod Security rules are triggered it will create a 403 forbidden response, and this is what is seen after …
=> Use base64 encoding and decoding on submitted tracking codes

concrete/controllers/dialog/block/aliasing.php
How to reproduce
https://user-images.githubusercontent.com/514294/144747991-87eeaecd-8bd2-42ac-a725-585c979385c8.mp4
How it fixed
https://user-images.githubusercontent.com/514294/144748000-7ca8d80f-833b-499f-9fb8-efa945b5beb4.mp4
=> [V8] Bugfix: conversation blocks are synced if these added from master collection

concrete/src/Block/Command/AddAliasDefaultsBlockCommandHandler.php
Same fix for V8: #10150
How to reproduce
https://user-images.githubusercontent.com/514294/144749482-04dddcc3-617d-4437-b558-6702d0a757bb.mp4
Fixed
https://user-images.githubusercontent.com/514294/144749493-d0bb8bed-d4df-4bc8-a199-cb8dbea2f5ac.mp4
=> [V9] Bugfix: conversation blocks are synced if these added from master collection

concrete/src/Block/Block.php
Fix #9354
* Avoid using raw sql query in Block::duplicate 
* Keep block cache settings on duplicate a block
=> Keep block cache settings on duplicate a block

concrete/src/Attribute/Exception/InvalidAttributeException.php, concrete/src/Search/ItemList/Database/AttributedItemList.php
Yesterday we faced an issue we added filtering with a new collection attribute which was supposed to be created on package update.
But we got lots of exceptions in between the code deploy and the package update due to not having the actual attribute which should be filtered by. 
**Let's throw `InvalidAttributeException` instead of a plain`Exception`.** 
So that, we can customize the behavior by catching this type of exception.
=> [v8] Throw InvalidAttributeException when attribute is not found

concrete/src/Config/Repository/Liaison.php
The Site configuration is managed by an instance of `Concrete\Core\Config\Repository\Liaison`.
This class is essentially a wrapper of `Concrete\Core\Config\Repository\Repository`. The only difference is that the keys must be transformed with the `transformKey` method.
Every method already calls `transformKey`, except `withKey`: this makes the method pretty useless (it temporarily sets the wrong key).
=> Fix Site config withKey

concrete/controllers/dialog/block/aliasing.php, concrete/src/Block/Block.php, concrete/src/Block/Command/AddAliasDefaultsBlockCommandHandler.php, concrete/src/Block/Command/DefaultsBlockCommand.php, concrete/src/Block/Command/ForceDefaultDisplayOrderBlockCommand.php, concrete/src/Block/Command/ForceDefaultDisplayOrderBlockCommandHandler.php, concrete/src/Block/Command/UpdateForkedAliasDefaultsBlockCommandHandler.php, concrete/src/Page/Cloner.php, concrete/src/Page/Collection/Collection.php, concrete/views/dialogs/block/aliasing.php
This pull request plans to implement the proposal listed in #10172
It adds the following features,
allow users/developers to set a displayOrder when using alias and clone commands
adds a new function that rescans an area display order using a block as a truth point, so if you set that block to position 4 and rescan it will scan everything from position 4, or the optional starting point, and onwards,  and skip over position 4 as that belongs to the block passed
add new force display order option on the setup on child pages on the pageType defaults.
https://user-images.githubusercontent.com/23059797/146513015-ebdc93c4-fe1a-4d9c-86df-466ae0a0759e.mov
=> [v9] Implement #10172 - Force Display Order from page types

concrete/blocks/testimonial/controller.php, concrete/blocks/testimonial/form.php
Testimonial block doesn't work on php8. Let's fix it
Error:
```
Whoops\Exception\ErrorException thrown with message "Undefined variable $awardImage"
Stacktrace:
#39 Whoops\Exception\ErrorException in /path/to/concrete/blocks/testimonial/view.php:46
#38 Whoops\Run:handleError in /path/to/concrete/blocks/testimonial/view.php:46
```
=> Make Testimonial block works on php8

concrete/src/Navigation/Item/PageItem.php
We currently have a (minor) issue with favorite pages:
1. the user logs in using language A
2. a new page is added to the favorites
3. the user logs out
4. the user logs in using language B
5. the displayed names of the favorite pages are in language A, whereas they should in language B
The problem is that in point 2 we save the page name using the current language, and in point 5 we reuse that value as is.
This PR fixes this issue by always saving the page names in English, and displaying them using the current language.
=> Translate favorite pages on the fly

concrete/src/Express/ExpressServiceProvider.php
The express service provider defines a few singletons (also via the deprecated `bindShared()` method, which [is an alias](https://github.com/concrete5/concrete5/blob/9.0.1/concrete/src/Application/Application.php#L505-L514) of the `singleton()` method):
- `express/builder/association`: resolves to `Concrete\Core\Express\ObjectAssociationBuilder`
- `express/control/type/manager`: resolves to `Concrete\Core\Express\Form\Control\Type\Manager`
- `express`: resolves to `Concrete\Core\Express\ObjectManager`
- `Concrete\Core\Express\Association\Applier`
- `Concrete\Core\Express\Controller\Manager`
For DI, it'd be useful to define as singletons the destination classes to (that is, for example `Concrete\Core\Express\ObjectAssociationBuilder`).
=> Simplify express bindings

composer.json
When using Composer 2.2 we have these warnings/requests:
```
composer/package-versions-deprecated
contains a Composer plugin which is currently not in your allow-plugins config.
See https://getcomposer.org/allow-plugins
Do you trust "composer/package-versions-deprecated" to execute code and wish to enable it now?
mlocati/composer-patcher
contains a Composer plugin which is currently not in your allow-plugins config.
See https://getcomposer.org/allow-plugins
Do you trust "mlocati/composer-patcher" to execute code and wish to enable it now?
wikimedia/composer-merge-plugin
contains a Composer plugin which is currently not in your allow-plugins config.
See https://getcomposer.org/allow-plugins
Do you trust "wikimedia/composer-merge-plugin" to execute code and wish to enable it now?
```
Let's …
=> List dependencies that can provide and execute Composer plugins

concrete/single_pages/dashboard/pages/themes/view.php
As explained in #10217 the list of themes ready to install is broken.
2 closing </div> tags are inside the foreach loop generating the list when they should be outside of it.
What's more, once that is fixed some design issues appear:
- Absence of vertical spacing between cards
- Misaligned "install" buttons
After fixing everything the list is not broken anymore and the design of the cards is improved
=> Fix broken themes list

concrete/controllers/element/dashboard/reports/forms/header.php, concrete/controllers/single_page/dashboard/reports/forms.php
As stated in #10213 the button to access legacy form reports is nowhere to be seen.
The single \dashboard\reports\forms single page is not using the correct header elements\dashboard\reports\forms\header.php
The page's controller use the DashboardSelectableExpressEntryListTrait trait which uses the DashboardExpressEntryListTrait trait.
That trait contains a getheaderMenu() method which is sending back the express/search/menu element.
As a result, we can't add a getheaderMenu() method to the controller of the forms single page otherwise it throws an error when trying to display Express forms results.
So I added the code to the view() method instead which works.
As far as I could tell everything related to Express in elements\dashboard\reports\forms\header.php and its controller is actually …
=> Fix broken reports page header

concrete/single_pages/dashboard/system/environment/geolocation.php
Ensures busy state is cancelled before opening the test dialog.
=> Prevent test of geolocator getting stuck in the busy state

concrete/src/Area/Layout/Preset/Provider/ActiveThemeProvider.php
I don't know why it may happen, but I've noticed this error:
```
Return value of
Concrete\Core\Area\Layout\Preset\Provider\ActiveThemeProvider::getThemeHandle()
must be of the type string, null returned
```
Let's fix it.
=> Fix return value of ActiveThemeProvider::getThemeHandle()

concrete/attributes/express/controller.php, concrete/attributes/page_selector/controller.php, concrete/attributes/user_selector/controller.php
The required option for composer form controls doesn't work for some attribute types.
I think it's just because the core team forgot to implement validateValue/validateForm method for them.
So let's add them. I'll add another pull request for V9 later.
=> [V8] Add not implemented validateValue/validateForm methods for some attribute types

concrete/single_pages/dashboard/system/files/image_uploading.php
As explained in #10250 there is a JS error stopping the checks for GD and ImageMagick libraries to run on page /dashboard/system/files/image_uploading.
It's a simple matter of replacing `$(window).load()` with `$(window).on('load'`
This PR fixes the issue.
here's a screenshot with the fix in place.
=> [9.0.1] Fixed image libraries check not running in Image Options single page

concrete/composer.json
add doctrine/annotations as required dependency
see doctrine/persistence#197
and doctrine/orm#8787
Essentially doctrine no longer requires annotations however we do require it for our packages/entities so we need to require it.
No changes to composer.lock since we already have it but in the future if we upgrade it may be removed, also currently composer based installs are currently not installing this causing the error in #10238
=> [v9] Fix #10238 - Add doctrine/annotations as a dependency

concrete/elements/block_area_footer.php
As explained in #10257 the area edit menu is broken when advanced permissions are enabled and the areas are wrapped in a list and list items <li>
When advanced permissions are enabled the permissions item appears in the area edit menu. That's the culprit so without advanced permissions we can't see the problem.
The divider just before the permissions item in the menu is wrapped in a left-over <li></li> that doesn't belong to any <ul></ul> so when it ends up inside a list it breaks it.
Removing the extra <li></li> fixes the problem. Screenshots below. The third one shows the menu fixed.
=> [9.0.1] Fix for broken area edit menu

concrete/blocks/feature_link/view.php
If by any chance `$buttonColor` is unset, the `class` tag of the `<div>`  is never closed.
=> fix(feature_link): fix the incorrect placement of the double quote on the block view

concrete/blocks/content/controller.php, concrete/src/File/Tracker/UsageTracker.php
Fix to the issue discussed in #10267 
What happens is the Usage Tracker expects an integer file ID but in the content block images are identified by their UUID.
What's more the block's controller incorrectly typecast the ID as an integer turning the alphanumeric UUID into an integer.
Often it doesn't throw any error although it saves the wrong values in the Usage Tracker table.
In this case, the resulting ID ((42000000000) was too big for the table.
One thing I can't explain is the same UUID turned into 42000000000 on a live server but to a much smaller integer on my local environment. I'm not sure what PHP setting would do that.
This fix does 2 things:
- it makes sure the block's controller doesn't convert the file ID to an integer
- it adds a check in the Usage Tracker class to verify …
=> [9.0.1] Fix file tracker usage issue with content block

concrete/blocks/express_entry_detail/edit.php
When editing an express block it shows `Call to undefined method DoctrineProxies\__CG__\Concrete\Core\Entity\Express\Form::label()`. The declared `$form` is being overwritten in the foreach, which was probably incorrect. Before this might have gone right, but now `$form` became an Entity this way. This commit fixes that.
=> Fix error in Edit Express Entry Detail popup

concrete/config/install/packages/elemental_full/content.xml
Install fails without this attribute due to https://github.com/concrete5/concrete5/commit/7cb423b4932bb2cbb594ffaf52fd31c6f110fa5a#diff-445ecf24f09c4efc84dfef13d9859a6df2880607d4dd91e331da47063294967bR928
Fixes #10293
=> Add titleFormat attribute to feature blocks (fixes #10293)

concrete/single_pages/dashboard/system/automation/tasks.php
This PR aims to resolve the issue pointed out in #10297
It does this by moving the options to a new dialog and clearly showing when tasks have an option or not.
See attached video for example
https://user-images.githubusercontent.com/23059797/152899598-059ed147-466c-4c28-b539-4d7497b843af.mov
=> [v9] Feature: Add a modal dialog for task options

concrete/jobs/remove_old_page_versions.php
When clearing  old page versions on a site with multiple page trees we've noticed that pages in all page trees other that ID 1 are skipped. This commit fixes that by specifically including all site trees.
=> Clear old page versions in all site trees

concrete/src/Page/Page.php
When an external link page is aliased, that page become undeletable in the trashcan. It also blocks all other pages from being deleted as soon as it is the first in the queue. This commit fixes that by adding the external link check before entering an infinite loop between `$this->delete()` and `$this->removeThisAlias()`.
=> Fix deletion of external links in the trashcan

composer.lock
`htmlawed/htmlawed` is a github repo that mirrors the real htmLawed releases and makes them available through composer. It had lagged behind in the past few years due to composer pain and so we weren't actually getting updates which left us without support for things like html5!  Things are sorted out over there now so let's update.
This PR updates htmlLawed to the current release which is `1.2.6`
=> Update htmlawed to latest version

concrete/blocks/page_list/view.php
The anchor target attribute will only be set correctly for the first page in the list because in the check to set it to "_self" (the default), `$target` has to be null. But it's only null on the first iteration. I changed this so that it's "_self" be default and then only changes if certain conditions are met.
=> Bugfix: anchor target attribute can be incorrect

concrete/src/Form/Service/Widget/FileFolderSelector.php, concrete/src/User/Search/Field/Field/GroupSetField.php, concrete/src/User/Search/Field/Field/HomeFolderField.php, concrete/src/User/Search/Field/Field/IsActiveField.php, concrete/src/User/Search/Field/Field/IsValidatedField.php
As explained in #10328 several field types in advanced user search don't retain their selected value when reloading the advanced search form.
These fields are:
- Group Set
- Home Folder
- Active
- Validated
Also, the file selector widget was always ignoring the $folder parameter, also impacting the user search.
This PR fixes the 4 field types and the file selector widget
=> [9.0.2] Fix several user search fields not retaining their selected values

concrete/src/Entity/File/Version.php
Fix to issue #10342 probably also #9867
When using an alternate storage location, especially a remote one like Amazon S3 for instance, the getThumbnailURL() method returns the wrong URL.
The custom storage location is ignored and the website's canonical URL is added at the beginning of the remote file's URL (e.g. https://www.website-canonical-url.com/https://actual-file-remote-url/xxx/xxx/thumbnail_type_handle/file-name.jpg)
This PR fixes it.
=> [9.0.2] getThumbnailURL() method ignores alternate storage location

concrete/src/Application/Application.php, concrete/src/Config/ConfigServiceProvider.php
We currently have that `config` is a singleton, and `Concrete\Core\Config\Repository\Repository` is bound to that singleton.
What about switching the logic, making `Concrete\Core\Config\Repository\Repository` a singleton and `config` an alias of it? This makes resolving `Concrete\Core\Config\Repository\Repository` faster.
=> Make the config repository a singleton

concrete/elements/header_required.php
I sometimes need to know the ID of the currently logged-in user via JavaScript (I don't think there are security problems doing that).
What about adding it to the global JavaScript variables that we already set in the `header_required.php` element?
PS: I also updated the code, so that PHP strings are sent to JavaScript via `json_encode` instead of a plain `echo`.
=> Add CCM_UID to global javascript variables

concrete/config/app.php
javascript-localized must be loaded after JavaScript, since the former references the ccmTranslator global object
=> Fix order of translator assets

concrete/src/Permission/IpAccessControlService.php
We need to include the category handle when we look for recorder IP events
=> Fix IpAccessControlService check against specific access control category

concrete/controllers/single_page/dashboard/system/permissions/denylist.php
Let's fix the display order of IP Access Control Categories in the `/dashboard/system/permissions/denylist` dashboard page.
=> IP Access Control: fix sorting categories in the dashboard page

concrete/controllers/single_page/dashboard/system/permissions/denylist.php, concrete/controllers/single_page/dashboard/system/permissions/denylist/configure.php, concrete/single_pages/dashboard/system/permissions/denylist.php, concrete/single_pages/dashboard/system/permissions/denylist/configure.php, concrete/src/Entity/Permission/IpAccessControlCategory.php
What about adding a helper method that describes the time window of IpAccessControlCategory?
Here's an example of its output (as displayed in the `dashboard/system/permissions/denylist` dashboard page when there is more than one IpAccessControlCategory):
=> IP Access Control: add IpAccessControlCategory::describeTimeWindow()

concrete/src/Permission/IpAccessControlService.php, tests/tests/Permission/IPServiceTest.php
When there's no time window, we currently ban IP addresses forever, even if we configure Concrete to only ban for X seconds.
For example, if we configure Concrete to ban IPs for 600 seconds if they try to login with a wrong password 3 times (in total, not "in the last 300 seconds"), the ban currently lasts forever.
In order to fix it, when there's no time window and if we already reached the event limits (for example, 3 wrong passwords) we need to check if the last event occurred more than the seconds of the ban duration (600 seconds): in that case it means that the ban already expired, and we need to delete the recorded events (so that the event count restarts from 0).
=> IP Access Control: fix ban duration when there's no time window

concrete/src/Http/Client/Client.php
This fixes the following issue:
```
Error: Call to a member function toArray() on array in concrete/src/Http/Client/Client.php:75
```
=> HTTP Client: fix error thrown when log is enabled

concrete/blocks/top_navigation_bar/controller.php, concrete/blocks/top_navigation_bar/view.php
also adds bootstrap's active class in the template
this addresses #9906 
I'm not sure if there would be a more preferred way to loading the ancestors as it appears the `NavigationService->getTrailToCollection($c)` loads the entire page objects. If needed for performance considerations I could add a `getIDTrailToCollection($c)` to only returns the collection ids since that's all we need here anyway
=> set isActive and isActiveParent for top_navigation_bar block

concrete/attributes/calendar_event/form.php, concrete/blocks/calendar/add.php, concrete/blocks/calendar/controller.php, concrete/blocks/calendar/edit.php, concrete/blocks/calendar/form.php, concrete/blocks/calendar/view.php, concrete/blocks/calendar_event/add.php, concrete/blocks/calendar_event/controller.php, concrete/blocks/calendar_event/edit.php, concrete/blocks/calendar_event/form.php, concrete/blocks/calendar_event/view.php, concrete/controllers/dialog/choose_event.php, concrete/controllers/dialog/event/edit.php, concrete/elements/event/form.php, concrete/src/Attribute/AttributeInterface.php, concrete/views/dialogs/event/choose.php
This PR is split from In regards to https://github.com/concrete5/concrete5/pull/10300 to make it easer to review
This PR fixes some issues in php8 when adding/editing the calendar and calendar event blocks
It also updates the php-doc for these blocks and updates/removes dead code comments
We also run php-cs-fixer against all these block files and phpstan level 6
This PR also fixes adding events, adding attribute events on php8
=> PHP8 Compatibility/PHP Doc Block Update for calendar and calendar event blocks

concrete/blocks/image/view.php
'image' in the handler function ends up referring the last element of the 'images' array. So if you have several image blocks on a single page, when hoving in and out of an image, it only changes the last element.
=> Fix a bug with having multiple image blocks with on-hover attribute set on the page

concrete/src/Application/Service/Dashboard.php, concrete/src/Application/Service/Dashboard/Sitemap.php
Let's cache response from `$app->make('helper/concrete/dashboard/sitemap')->canViewSitemapPanel()` or `$app->make('helper/concrete/dashboard/sitemap')->canRead()` because these methods are called several times per a request but should return same value.
I'm currently working on developing an intranet website for hundreds of employees with version 8, but if you think this PR is fine, I'll make another PR for V9.
=> [V8] [Performance improvement] Cache response from application services

concrete/src/Mail/Importer/MailImporter.php
Go to Dashboard > Extend and see the details of an installed package: you'll have this error:
```
Call to undefined method Doctrine\DBAL\ForwardCompatibility\Result::FetchRow()
```
Let's fix it.
=> Fix listing installed MailImporters

concrete/blocks/calendar_event/controller.php, concrete/blocks/page_list/controller.php, concrete/config/site.php, concrete/src/Block/View/BlockView.php, concrete/src/Page/Controller/PageController.php, concrete/src/Url/SeoCanonical.php
As we discussed on #10155 before, we decided to change the strategy of query parameter in the canonical link tag to allowlist instead of denylist. However, we don't allow any parameters now, so let's add them.
Google recommends pagination parameter should be included in the canonical link. See: https://developers.google.com/search/docs/advanced/ecommerce/pagination-and-incremental-page-loading#use-urls-correctly
Also event occurrence ID should be included in the canonical URL to avoid disappearing events from the search engine index.
I found another problem on working this issue. Block controller's `on_start` method is called too late to modify canonical URL. I think we should call it as earlier as possible, at least before rendering the `header_required` element. Additionally, we were …
=> Add some query parameters to the canonical link tag

concrete/controllers/panel/page/versions.php
Prior to #10374 page responses returned a json object but they are now returning a json string. 
This means the current version panel is broken and while requests are successful the javascript no longer works. This is because of using `getJSON` instead of `getJSONObject`. JSON responses json_encode whatever is passed to it so getJSON (a string) is encoded as such.
While fixing this I also did the following
added basic PHP Doc blocks
removed some dead code 
return json responses always (no reason not to)
validate page version before attempting to copy it/creating a new page from it
add some calls to helper/security to validate cvIDs
tightened up some types
=> [v9] Fix version panel responses

concrete/blocks/core_conversation/add.php, concrete/blocks/core_conversation/controller.php, concrete/blocks/core_conversation/edit.php, concrete/blocks/core_conversation/form.php, concrete/blocks/core_conversation/view.php, concrete/controllers/frontend/conversations/add_message.php, concrete/controllers/frontend/conversations/message_page.php, concrete/controllers/frontend/conversations/update_message.php, concrete/controllers/single_page/dashboard/conversations/messages.php, concrete/elements/conversation/message.php, concrete/elements/conversation/message/review.php, concrete/single_pages/dashboard/conversations/messages.php, concrete/src/Antispam/Service.php, concrete/src/Conversation/FlagType/FlagType.php, concrete/src/Conversation/Message/Author.php, concrete/src/Form/Service/Form.php, concrete/views/frontend/conversations/message_page.php
This PR is split from In regards to https://github.com/concrete5/concrete5/pull/10300 to make it easer to review
This PR fixes some issues in php8 when adding/editing conversation blocks, it also fixes issues with the conversation dashboard pages, the conversation block not displaying correct usernames.
It also updates the FlagType::getByHandle being incorrectly named 
was `getByhandle` now `getByHandle` as everywhere it was used it was `getByHandle`
It also adds phpdoc blocks to the core_conversation block and these files now pass phpstan level 6
It also adds some phpdoc blocks the conversation/messages controller, and updates some depreciated code along with returning json responses from the methods
=> PHP8 Compatibility/PHP Doc Block Update for Conversations

concrete/src/Application/Application.php
The function `setupPackages` loops over each package to run auto-update if that is enabled. But only checks if auto_update is enabled inside the packages loop, but takes no action when disabled. This commit fixes this behavior by checking once and start looping if enabled.
If it is intended to allow packages to disable auto_updates mid-update then this commit would break that. However, I don't think config is meant to be used as a runtime semaphore.
=> Check enable_auto_update_packages once at setupPackages

concrete/authentication/concrete/controller.php
We have to check if the threshold has been reached before registering the event.
Why?
For example, think at the case when we only allow 1 event every minute.
If we register the event and then we check if in the last minute we've had an event, that would always be true.
=> Forgot Password: fix rate limit logic

concrete/src/Permission/IpAccessControlService.php
Since PHP 5.6 constants are a bit smarter: we can define their value in a more flexible way ([example](https://3v4l.org/jdkl9)).
Furthermore, since PHP 7.1 we may declare the visibility of constants ([example](https://3v4l.org/d0mNC)).
=> Simplify constants of IpAccessControlService

concrete/blocks/feature_link/controller.php
I have this error when installing the latest develop branch with PHP 8.1:
```
In controller.php line 171:
[Whoops\Exception\ErrorException (2)]
Undefined array key "icon"
Exception trace:
at .../concrete/blocks/feature_link/controller.php:171
```
=> Fix accessing undefined array index

concrete/blocks/top_navigation_bar/controller.php
addresses #10415
are there any situations where where `Section::getBySectionOfSite(Page::getCurrentPage())` could be null and pose other issues (ie site tree not loading at all) or is the PR a reasonable way to approach this?
edit: I think I answered my own question and have added a new commit to address this. 
It would be good to consider if this will work on multi-site installs or if this needs to be tweaked to handle those scenarios
=> load the home page based off the currently active site section

concrete/src/Console/Command/ExecCommand.php
The return code of the c5:exec CLI command is defined by the script, so we shouldn't describe it in the command description.
Furthermore, let's allow the included script define the return value simply by using a `return` statement instead of defining a "magic" `$rc` variable.
=> Simplify c5:exec return code

concrete/controllers/backend/file.php, concrete/js/ckeditor4/core/concrete5uploadimage/plugin.js
Make a user belongs to some group
The user can access the File Manager but can not upload files
You'll get "File successfully uploaded." message, but the file upload failed due to the permission settings.
https://user-images.githubusercontent.com/514294/126082127-bf609f1d-25fe-4f61-9dc1-d6a14dbc44a9.mov
You'll get an error message when you don't have permission to upload a file.
https://user-images.githubusercontent.com/514294/126082160-1c094e6f-1557-438d-bd27-e0eb9a65ab96.mov
=> [V8] Fix: error message doesn't display when upload file failed via drag & drop

concrete/src/Http/ResponseFactory.php, concrete/src/Multilingual/Service/Detector.php, concrete/themes/concrete/elements/header.php, concrete/themes/core/error.php, concrete/themes/dashboard/elements/header.php
This PR fixes #7909, #6500 (already closed), #6228 (already closed), #5775 (already closed), #3345 (already closed).
This PR doesn't cover all pages described on #3350 but it's a related topic.
Single pages rendered in English, it's fine.
Users in the site will use English because this is an English site, but administrators use Japanese. In this case, /register page should be rendered in English, but it did in Japanese. The login page is a difficult issue because if the site is not registerable, only admin users use /login page, and they'll want to use it in Japanese.
404 and 403 pages should be displayed in Japanese because this is a Japanese site.
404 and 403 pages should be displayed in Japanese because this is a Japanese site.
Nothing changed
I believe these pages should be rendered …
=> [V8] Render single pages like 404, 403, login, register in default site locale

concrete/src/Marketplace/RemoteItem.php
#10014 describes a whoops arising from flawed code in the error handling for errors when connecting to the marketplace
This change is untested because testing would require the initial error condition. It adds checks to avoid class::method error inside the exception handling for marketplace update.
As a fix, I don't know if the calling code to which the Error or ErrorList object is returned can handle an ErrorList (line 230)
This is a messy fix. Better would be to restructure this method to avoid variant object type for $pkg. (line 243)
This is a #10435 for v8
=> Avoid class::method error in marketplace update

concrete/blocks/desktop_app_status/controller.php, concrete/blocks/desktop_concrete_latest/add.php, concrete/blocks/desktop_concrete_latest/controller.php, concrete/blocks/desktop_concrete_latest/edit.php, concrete/blocks/desktop_concrete_latest/view.php, concrete/blocks/desktop_draft_list/add.php, concrete/blocks/desktop_draft_list/controller.php, concrete/blocks/desktop_draft_list/edit.php, concrete/blocks/desktop_draft_list/form.php, concrete/blocks/desktop_draft_list/view.php, concrete/blocks/desktop_featured_addon/controller.php, concrete/blocks/desktop_featured_addon/view.php, concrete/blocks/desktop_featured_theme/controller.php, concrete/blocks/desktop_featured_theme/view.php, concrete/blocks/desktop_latest_form/controller.php, concrete/blocks/desktop_latest_form/view.php, concrete/blocks/desktop_site_activity/add.php, concrete/blocks/desktop_site_activity/controller.php, concrete/blocks/desktop_site_activity/edit.php, concrete/blocks/desktop_site_activity/form.php, concrete/blocks/desktop_site_activity/view.php, concrete/blocks/desktop_waiting_for_me/controller.php, concrete/blocks/desktop_waiting_for_me/view.php
This PR is split from In regards to https://github.com/concrete5/concrete5/pull/10300 to make it easer to review
This PR adds PHP doc blocks to all desktop_* blocks
desktop_app_status
desktop_concrete_latest
desktop_draft_list
desktop_featured_addon
desktop_featured_theme
desktop_latest_form
desktop_site_activity
desktop_waiting_for_me
It also passes phpstan level 6
remove some depreciated methods, use the app helper function over facades
ran php-cs-fixer on all the files
=> PHP Doc Block Update for desktop_* blocks

concrete/blocks/page_attribute_display/form.php
The core attribute display block defaults to no delimiter. But once you have set a delimiter, there was no option to clear it again!
This pull fixes that missing option.
(The option still exists on 8.5.x, but was lost when the code was refactored to use $form->select)
=> Fix missing none option in attribute display block

composer.json, composer.lock, concrete/composer.json
That way the package will be included in composer-based installations
=> Move concrete5/dependency-patches to the core composer.json

concrete/elements/form/composer.php, concrete/elements/form/grouped/composer.php, concrete/elements/page_types/composer/controls/core_page_property/date_time.php, concrete/elements/page_types/composer/controls/core_page_property/description.php, concrete/elements/page_types/composer/controls/core_page_property/name.php, concrete/elements/page_types/composer/controls/core_page_property/page_template.php, concrete/elements/page_types/composer/controls/core_page_property/publish_target.php, concrete/elements/page_types/composer/controls/core_page_property/url_slug.php, concrete/elements/page_types/composer/controls/core_page_property/user.php, concrete/elements/page_types/composer/controls/core_page_property/version_comment.php
refs #10462
This also wraps the output for the tooltips with the h() security helper
=> Switch to using Bootstrap 5 style tooltips for composer controls

concrete/src/Page/Cloner.php, tests/tests/Multilingual/SectionTest.php, tests/tests/Page/PageTest.php
Same as #10467 , fix #7781 for version 9
```
% composer test -- --filter testDuplicateAliasMultilingual
> phpunit '--filter' 'testDuplicateAliasMultilingual'
PHPUnit 8.5.24 #StandWithUkraine
Runtime:       PHP 7.4.27
Configuration: /path/to/phpunit.xml
E                                                                   1 / 1 (100%)
Time: 3.84 seconds, Memory: 52.50 MB
There was 1 error:
1) Concrete\Tests\Multilingual\SectionTest::testDuplicateAliasMultilingual
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'insert into MultilingualPageRelations (mpRelationID, cID, mpLocale, mpLanguage) values (?, ?, ?, ?)' with params ["2", 4, "de_CH", "de"]:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-4' for key 'PRIMARY' …
```
=> [V9] Fix SQL error on duplicate alias between multilingual sections

concrete/src/Page/Cloner.php, tests/tests/Multilingual/SectionTest.php, tests/tests/Page/PageTest.php
I've added a test to reproduce #7781 and also added a fix for it.
```
% composer test -- --filter testDuplicateAliasMultilingual
> phpunit '--filter' 'testDuplicateAliasMultilingual'
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
Runtime:        PHP 7.4.27
Configuration:  /path/to/phpunit.xml
E
Time: 2.95 seconds, Memory: 40.50MB
There was 1 error:
1) Concrete\Tests\Multilingual\SectionTest::testDuplicateAliasMultilingual
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'insert into MultilingualPageRelations (mpRelationID, cID, mpLocale, mpLanguage) values (?, ?, ?, ?)' with params ["2", 4, "de_CH", "de"]:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-4' for key 'PRIMARY' …
```
=> [V8] Fix SQL error on duplicate alias between multilingual sections

concrete/controllers/single_page/dashboard/extend/connect.php, concrete/src/Marketplace/Marketplace.php, concrete/src/Marketplace/RemoteItem.php, concrete/src/Marketplace/RemoteItemList.php
Basically all of the communication with the marketplace happens from server to server rather than in browser these days, the only exceptions being images loaded in the browser directly from marketplace. This PR starts using `concrete_secure` for this communication leaving only the usage in `Marketplace::getMarketplaceFrame()` since this method is not actually used anywhere and secure is already used any time the site is loaded via HTTPS.
=> Use `concrete_secure` over `concrete` wherever possible

concrete/src/File/Image/Thumbnail/ThumbnailPlaceholderService.php
This PR avoids a Exception by falling back to rendering a rectangular placeholder in case there is no height given for the thumbnail type.
=> Avoid exception when rendering thumbnail placeholders

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/optimization/clearcache.php, concrete/src/Asset/Asset.php, concrete/src/Cache/Command/ClearCacheCommandHandler.php, concrete/src/Console/Command/ClearCacheCommand.php
This pull requests implements the feature suggested in #10483 which adds a `concrete.cache.last_cleared` timestamp to the ccm_nocache hash.
This should help in cases where developers edit things like block overrides css etc and clear cache but the css is still cached on users browsers due to the ccm_nocache value not changing
=> [v9] Implement #10483 - add cache clear timestamp

concrete/config/install/base/attributes.xml, concrete/config/install/packages/elemental_full/content.xml
Two attributes used by concrete's core are installed through the `elemental_full` install package. These are handles "exclude_subpages_from_nav" and "thumbnail". This seems like an oversight because if Elemental would no longer be shipped with the core that would break some core functionality. 
This PR moves the attributes out of Elemental into `concrete/config/install/base/attributes.xml`.
edit: I tried installing `elemental_blank` and in that case the two attributes are also missing.
=> Move core attributes from elemental into base attribute install cif

concrete/src/Page/Theme/Theme.php
Concrete loads the current theme from database same number of times as images if the current theme supports responsive image. Let's use request cache to avoid it.
=> Performance Improvement: Reduce getting theme from database

build/assets/cms.scss
This is reported by @hdk0016.
Andrew recently tried to fix the directly level of CSS images for Concrete site under sub directory
https://github.com/concrete5/concrete5/commit/e5b8e6ed9f857695830dd3d57a286d891b5548c1
I think you confused over the final destination.
When he tried in sub-diretory, the icons below disappeared.
I think you put the path level wrong.
When he adjust the level like this..., it was fine.
Thx
=> Fix relative path level for CSS background images installed in the subdirectory

concrete/src/Page/Stack/StackList.php
Retrieve all stacks, not just those with an approved version
=> Fix #10578

concrete/blocks/form/auto.js
Originally reported via forum
https://forums.concretecms.org/t/9-0-2/2724/
- you add a legacy form block
- you add a email address field
- you set an option `reply to this email address`
- save a block
- come back and re-edit the email address field
- The checked state of `reply to this email address` was not properly passed and the checkbox WAS NOT CHECKED.
I only tested with Chrome on develop branch thought.. this PR should fix it.
Thx
=> Legacy form's "reply to this email address" checked state was not properly passed

concrete/blocks/hero_image/controller.php
Andrew said he can't reproduce #10595 but I believe it should still happen on 9.1.0RC4.
Here's the video I've tried to install with the recent develop branch on PHP8.0
https://www.youtube.com/watch?v=V-_jNtheSzo
=> Fix #10595

concrete/src/File/ExternalFileProvider/ExternalFileEntry.php
`ExternalFileEntry` class doesn't contain all properties in the [Files](https://github.com/concrete5/bedrock/blob/master/assets/cms/components/file-manager/Chooser/Files.vue) component.
Let's add them to show external file search interface works correctly.
Before
After
=> Add missing properties in the vue file component

concrete/blocks/accordion/view.php, concrete/themes/elemental/blocks/accordion/view.php
compares the class that is being determined a few lines up so that the logic follows the same as the 'show' class for the collapse item.
closes #10610
=> output correct class for collapsed accordion items

concrete/src/Form/Service/Widget/Color.php
The upgrade to spectrum2 had the side effect of changing the color picker widget layout. This fixes back compatibility.
=> Fix #10628

concrete/views/dialogs/page/seo.php, concrete/views/panels/details/page/attributes.php, concrete/views/panels/details/page/seo.php
Hi,
The content creators from the agency I work for noticed some changes in comparison to concrete5 V8.
When working with nested sitemap pages, its very annoying to edit attributes or seo info from multiple pages.
After the page reload the whole sitemap is collapsed again which makes it quite annoying to work with.
This is because there is a page refresh after saving the attributes and seo information, caused by a attribute in the form tag.
I removed the tags and everything worked as expected, couldn't find any reason why it was there so I removed it.
If this is not the proper solution and this feature is required for some reason, please let me know. I also build a different solution where you are able to disable the automatic page reload which can be toggled in the dropdown above the …
=> [v9.0.2] Remove javascript page reload attribute from seo and attributes panels

concrete/controllers/upgrade.php, concrete/views/frontend/upgrade.php
As described, this will allow clean install of core upgrades without php8 errors.  Fixed/adjusted button classes.  Moved "rerun script" button inline with "back to home". Cleaned up code.  Happy Upgrading!! :)
=> Make ccm Upgrades work on php8 without error, plus visual enhancement

concrete/blocks/top_navigation_bar/controller.php, concrete/blocks/top_navigation_bar/view.php
I recently released a nav_target page attribute package to the marketplace.  In review @JohntheFish pointed out the top nav bar wasn't respecting the nav_target attribute and could use fixing.  I later found it wasn't respecting the external link target either.  This should be problem solved...
=> Make Top Nav Bar Block Respect nav_target Page Attribute & External Link Targets

concrete/controllers/backend/page/preview_version.php, concrete/controllers/panel/detail/theme/preview_skin.php, concrete/controllers/panel/page/design.php, concrete/controllers/panel/page/devices.php, concrete/controllers/panel/page/preview_as_user.php, concrete/elements/header_required.php, concrete/elements/page_controls_footer.php, concrete/src/Area/Area.php, concrete/src/Form/Service/Widget/UserSelector.php, concrete/src/Page/Controller/PageController.php, concrete/src/Page/View/PageView.php, concrete/views/panels/page/preview_as/form.php, concrete/views/panels/page/preview_as/frame.php
* Fix #10702 
* Fix #6502
* Fix #6428
Additionally, improves the display, functionality and resilience in the View as User panel by using native browser controls and fixing some display bugs.
=> Improvements and bug fixes to previewing pages and versions as users

concrete/controllers/single_page/dashboard/files/sets.php
Removing unused parameter $fsOverrideGlobalPermissions.
update() method requires $setName only.
=> Fix $fileset->update() php8 undefined error

concrete/attributes/select/controller.php
Recently, I was developing a package that extends the select attribute controller. I had to override some of the methods as the properties are private and there are not enough getters and setters.
Let's change the visibility to `protected` from `private`.
=> [v9] Make the select attribute controller properties private to protected

concrete/src/Page/Stack/UsageTracker.php, concrete/src/Summary/Data/Field/DatetimeDataFieldData.php
If you have a page/page object without a public date, i.e. in the trash or waiting to be published. The re-index job will fail due to trying to call ->getTimeStamp() on null.
Since we allow for the DateTime to be null, we should check for that. While investigating this I also found on php8 there is an error on the $controller check (we should also reset the controller, just incase)
=> [v9] Fix/error in reindex contents task with Page Objects

concrete/single_pages/dashboard/users/add.php, concrete/single_pages/dashboard/users/search/edit.php
Using the new `PasswordInput` Vue component for password visibility toggle.
companion pull request in the bedrock: https://github.com/concretecms/bedrock/pull/236
=> using new PasswordInput component

concrete/controllers/single_page/dashboard/system/files/export_options.php, concrete/single_pages/dashboard/system/files/export_options.php
Let's make it enable to change `concrete.export.csv.datetime_format` value on dashboard
=> Add a pull down menu to set datetime format for exporter

concrete/blocks/hero_image/controller.php
Currently you can add a Hero Image Block without a Image since the Validation Code in place doesn't seem to be working as expected.
However: removing a Image from a existing Block [produces a Exception](https://github.com/concretecms/concretecms/issues/10744).
This PR makes it so the Hero Block can be saved without Issues whether or not a Image is selected.
The default Block template already makes sure the Block only is rendered when a Image is given. - But this gives the freedom to theme/ template developers to create templates that render nicely with or without images. (for example by using CSS implemented flat colors, gradients etc. to fill the space instead)
=> Allow for saving Hero Image Blocks without Image while avoiding the current datatype Exception

concrete/src/Form/Service/Form.php
Implements the __call magic method for misc form input types as per v9,  https://github.com/concretecms/concretecms/pull/10761
=> v8.5.x Implement __call for misc input types in Form

concrete/src/Form/Service/Form.php
$miscFields was incorrectly created by slicing the tail of the $args array. This left it as an array[0][miscFields] rather than array[miscFields]
Take 2 on this. Better tested than my now deleted https://github.com/concretecms/concretecms/pull/10759
=> Fix Forms miscFields in __call()

concrete/src/Attribute/StandardValidator.php
The Information passed in the ErrorList used by the Form Block in case of failed validation is not sufficient to achieve a modern UI Look& Feel because there is no proper way of matching errors to form fields.
This PR makes it so the field object passed to the error list includes the form field name as it's used in the form block.
Error Object before this change:
Error Object after this change:
=> [improvement] add form field name information to attribute validation error object

concrete/src/Search/ItemList/Database/ItemList.php
Steps to reproduce the error:
1. Go to `/dashboard/reports/logs` page and click the pagination link
2. Change the URL parameter `ccm_order_by_direction=desc` to `ccm_order_by_direction[]=desc`
3. You'll got `strtolower() expects parameter 1 to be string, array given` error
You'll get the same error if you develop an item list class that extends `\Concrete\Core\Search\ItemList\Database\ItemList` abstract class.
=> Sanitize pagination direction parameter value

concrete/src/Entity/File/Version.php
In English we say "JPG Image", but for example in Italian we say "Immagine JPG".
So, how about letting translators to swap the order of the file extension and the file type?
=> Let translators swap file extension and file type

concrete/controllers/single_page/dashboard/system/environment/info.php, concrete/src/Console/Command/InfoCommand.php, concrete/src/System/Info.php
This adds the Hostname and detected Environment to the start of the environment text, as well as to the output of the info command.
I was recently referring to https://documentation.concretecms.org/tutorials/loading-configuration-based-host-and-environment, to set up an environment based config file, and realised that there wasn't an easy way to work out what Concrete was actually detecting. 
In my case, I run valet locally, and didn't realise that the Concrete driver sets the environment for you (https://github.com/laravel/valet/blob/master/cli/drivers/Concrete5ValetDriver.php#L27)
It was a bit confusing why my environment detection wasn't working, I had to add code to output the detected environment name. 
So this code simply makes it easier to view what is actually being set.
=> Add environment name

concrete/src/Navigation/Breadcrumb/PageBreadcrumbFactory.php
You'll get `Argument 2 passed to Concrete\Core\Navigation\Item\Item::__construct() must be of the type string, null given` error when you unapproved all versions of a parent page. Let's avoid this error
=> Avoid type error on breadcrumbs navigation

concrete/views/dialogs/file/import.php
When swapping a file, the tab pane inside the "Swap File" dialog is empty: see
Let's fix it.
Fix https://github.com/concretecms/concretecms/issues/10729
=> Fix content of swap file initially empty

concrete/src/Form/Service/Form.php
For example, to output a [`datetime-local`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) input type, we can now call
```php
$form->datetime_local(...)
```
=> Allow users to write input types containing dashes

concrete/bootstrap/helpers.php
Every time we call the `h()` global function, a new instance of the `Concrete\Core\Utility\Service\Text` class is created and then destroyed.
Let's avoid that: it's useless.
=> Create a Text instance just once when calling h()

concrete/src/Cache/Command/ClearCacheCommandHandler.php
Hi, we discovered a "bug" in the clear-cache task.
To optimize our website we added the redis cache to the fullpagecache with the concrete.cache.page config. But when we tried to clear the cache it didn't seemed to clear correctly.
When checking the code we saw that the FlushableInterface was missing in the ClearCacheCommandHandler. 
When added the use it works all fine.
Currently we fixed it with a psr4 namespace in composer
```json
"autoload": {
"psr-4": {
"Concrete\\Core\\Cache\\Command\\": "./public/application/src/Concrete/Cache/Command"
},
},
```
Our config to reproduce :
```php
<?php
// a custom class store our credentials (for compatibility between dev and prod)
$config = new Config();
$redisConfig = $config->credentials('redis');
return [
'updates' => [
// Skip the automatic …
```
=> Add the FlushableInterface import in the ClearCacheCommandHandler.php

concrete/src/Entity/Search/Query.php, concrete/src/Search/Column/Set.php
Fix wrong column being selected on advanced search dialog open; adding direction to query normalize/denormalize so it shows up in advanced search dialog properly
=> Misc. Search Fixes

concrete/src/Updater/Migrations/Migrations/Version20220911000000.php
It's useless, and by using %s, the string "Importing %s" may be reused without requiring translators to translate it every time.
=> Skip translating a file name in migration 20220911000000

concrete/src/Command/Task/Controller/PageCacheReportController.php
We are checking "settings", which is plural, isn't it?
=> Fix typo in PageCacheReportController description

concrete/controllers/single_page/dashboard/users/groups.php
```
Whoops\Exception\ErrorException thrown with message "Undefined array key "gIsBadge""
Stacktrace:
#27 Whoops\Exception\ErrorException in /path/to/concrete/controllers/single_page/dashboard/users/groups.php:323
```
Badge is now deprecated, so we can remove these lines.
=> Fix: Enable to edit a Group on PHP8

concrete/src/File/FolderItemList.php
If we sort by `fv.fvTitle` we currently have this query:
```sql
SELECT distinct
n.treeNodeID,
if(nt.treeNodeTypeHandle='file', fv.fvTitle, n.treeNodeName) as name,
if(nt.treeNodeTypeHandle='file', fv.fvDateAdded, n.dateModified) as dateModified,
case when nt.treeNodeTypeHandle='file_folder' then 1 else (10 + fvType) end as type,
fv.fvSize as size
FROM
TreeNodes n
INNER JOIN TreeNodeTypes nt ON nt.treeNodeTypeID = n.treeNodeTypeID
LEFT JOIN TreeFileNodes tf ON tf.treeNodeID = n.treeNodeID
LEFT JOIN FileVersions fv ON tf.fID = fv.fID and fv.fvIsApproved = 1
LEFT JOIN Files f ON fv.fID = f.fID
LEFT JOIN Users u ON f.uID = u.uID
LEFT JOIN FileSearchIndexAttributes fsi ON f.fID = fsi.fID
WHERE
n.treeNodeParentID = ?
ORDER BY
fv.fvTitle desc
LIMIT 20
```
As you can see, in the `SELECT` part we …
=> Fix sorting results of FolderItemList by file title

concrete/src/Entity/User/User.php
\UserInfo is an alias of \Concrete\Core\User\UserInfoRepository whereas getUserInfoObject() actually returns a
\Concrete\Core\User\UserInfo instance
=> Fix PHPDoc of getUserInfoObject() method of user entity

concrete/src/Http/ResponseFactory.php
I don't know if it's a bug, but it's pretty weird.
We have a controller to display news fetched from algolia.
Our controller is a PageTypeController and have a public method to fetch data in json with a JsonResponse.
The method is named getEvents and does the exact same thing as the view method (return list of news by params).
News have a date and we use the helper/date to format the date to 'd M'.
When we use the view method our date display in french (the local we use), but if we use the getEvents method it display in english (seems to be the fallback locale).
After investigation i discovered that the ResponseFactory doesn't call the Detector to setup the local on controller call.
In the pr i added some line of code, it instanciate the multilingual detector, get the current page, and if …
=> Add the setupSiteInterfaceLocalization in the controller method in ResponseFactory.php

concrete/config/concrete.php, concrete/config/db.xml, concrete/controllers/single_page/dashboard/pages/types/form.php, concrete/elements/page_types/composer/form/output/form.php, concrete/single_pages/dashboard/pages/types/form.php, concrete/src/Page/Type/Composer/FormLayoutSet.php, concrete/src/Page/Type/Type.php, concrete/src/Updater/Migrations/Migrations/Version20220919000000.php
This feature is in response to the discussion at:
https://forums.concretecms.org/t/a-quick-way-to-make-composer-forms-more-condensed/3813/4
This makes the composer form set legend text triggers for showing and collapsing the set of attributes below it.
And when clicked:
When configuring a set of composer fields, there is an option to either set the set to be open by default, collapsed by default, or not able to be collapsed. 
This can help to make a long composer form with many attributes more manageable, by hiding lesser used set of attributes by default. 
The default behaviour is to add showing/collapsing to sets, but to remain visible, meaning already existing composer forms aren't changed in terms of field visibility.
A few minor spacing adjustments have also been made to the composer …
=> Adds ability to configure Composer form sets to be collapsable

concrete/src/Logging/Entry/Group/AddGroup.php, concrete/src/Logging/Entry/Group/DeleteGroup.php, concrete/src/Logging/Entry/Group/EnterGroup.php, concrete/src/Logging/Entry/Group/ExitGroup.php, concrete/src/Logging/Entry/Group/Group.php, concrete/src/Logging/Entry/Group/UpdateGroup.php, concrete/src/User/Group/Command/AddGroupCommandHandler.php, tests/tests/User/GroupLoggingTest.php
We may have user groups with the same name, but available at different paths.
For example, if we have this structure
```
/
├── Project1
│   |
│   └── Admins
|
└── Project2
|
└── Admins
```
In the logs we have entries like these:
What about logging the full path of the groups instead?
We'd have something like this:
=> Log the full group paths

concrete/src/Page/Collection/Version/Version.php
The user params was missing and we were only able to get the user with :
```php
use Concrete\Core\User\User;
use Symfony\Component\HttpFoundation\Session\Session;
/** @var Session $session */
$session = $this->app->make('session');
dd(User::getByUserID($session->get('uID')));
```
=> Add the missing user param on page_version_approve event

concrete/blocks/top_navigation_bar/edit.php
PHP 8+ no longer treats undefined variables as null and instead throws an exception. This fixes such a set of exceptions if logos are not set and you later attempt to edit the nav bar.
=> Fix PHP 8+ on null variables

concrete/src/Entity/Notification/GroupCreateNotification.php, concrete/src/Entity/Notification/GroupRoleChangeNotification.php, concrete/src/Entity/Notification/GroupSignupNotification.php, concrete/src/Entity/Notification/GroupSignupRequestAcceptNotification.php, concrete/src/Entity/Notification/GroupSignupRequestDeclineNotification.php, concrete/src/Entity/Notification/GroupSignupRequestNotification.php, concrete/src/Entity/Notification/NewConversationMessageNotification.php, concrete/src/Entity/Notification/NewFormSubmissionNotification.php, concrete/src/Entity/Notification/NewPrivateMessageNotification.php, concrete/src/Entity/Notification/Notification.php, concrete/src/Entity/Notification/NotificationAlert.php, concrete/src/Entity/Notification/NotificationAlertRepository.php, concrete/src/Entity/Notification/UserDeactivatedNotification.php, concrete/src/Entity/Notification/UserSignupNotification.php, concrete/src/Entity/Notification/WorkflowProgressNotification.php, concrete/src/Entity/User/GroupCreate.php, concrete/src/Entity/User/GroupRoleChange.php, concrete/src/Entity/User/GroupSignup.php, concrete/src/Entity/User/GroupSignupRequest.php, concrete/src/Entity/User/GroupSignupRequestAccept.php, concrete/src/Entity/User/GroupSignupRequestDecline.php, concrete/src/Entity/User/User.php, concrete/src/Entity/User/UserSignup.php, concrete/src/Notification/Notifier/StandardNotifier.php, concrete/src/User/Group/Command/AddGroupCommandHandler.php, concrete/src/User/Group/Group.php, concrete/src/User/Group/GroupJoinRequest.php, concrete/src/User/RegistrationService.php, concrete/src/User/User.php
Consider this code:
```php
$app = app();
$command = (new Concrete\Core\User\Group\Command\AddGroupCommand())->setName('Test');
$group = $app->executeCommand($command);
echo "Group: {$group->getGroupPath()} (ID={$group->getGroupID()})\n";
$user = Concrete\Core\User\User::getByUserID(USER_SUPER_ID);
$user->enterGroup($group);
echo $user->inGroup($group) ? "User correctly entered group.\n" : "User didn't enter the group!\n";
$command = new Concrete\Core\User\Group\Command\DeleteGroupCommand($group->getGroupID());
$deleted = $app->executeCommand($command);
echo $deleted === false ? "Not deleted.\n" : "Deleted\n";
```
At the moment it fails with the following output:
```sh
Group: /Test (ID=4)
User correctly entered group.
In HandleMessageMiddleware.php line 128:
Handling …
```
=> Fix notifications relations

concrete/src/User/Group/Command/DeleteGroupCommandHandler.php
Consider the case that, in the same request, we have some code that:
1. delete the group X
2. delete the group Y which is the parent of X
In this case, when we delete Y, in the request cache we have that it still has the child group X.
So, we may have problems like the one I reported at #10948.
By clearing the request cache related to tree nodes the problem is solved.
=> Clear tree/node request cache when deleting a group

concrete/controllers/single_page/dashboard/system/environment/debug.php
Since PHP 8.0, accessing undefined object properties has been promoted from `E_NOTICE` to `E_WARNING`, so it's no more a valid example for `E_NOTICE` messages.
Let's introduce another way to raise an `E_NOTICE` that would silently be ignored if we don't set the "Consider warnings as errors" option.
=> Update the sample code for "warnings as errors"

concrete/blocks/page_list/page_list_form.php
The Page List Block currently allows for saving negative numbers that always revert to zero.  This is senseless and solved by adding min to the input
=> Add min to Page List num input

concrete/src/Package/StartingPointPackage.php, concrete/src/User/Group/Command/AddGroupCommand.php, concrete/src/User/Group/Command/AddGroupCommandHandler.php
Since 310117283d0a142d1b0e33ab546e7bf1f83dbcba we've lost support for creating the core groups with the required IDs.
That means that, depending on server setup, the IDs of the admin/guest/registered users groups may not be the one that Concrete requires.
Let's restore it.
=> Let's be sure we create the core groups with correct IDs

concrete/controllers/backend/account.php, concrete/controllers/calendar_feed.php, concrete/controllers/dialog/file/statistics.php, concrete/controllers/single_page/dashboard/blocks/stacks.php, concrete/controllers/single_page/dashboard/extend/install.php, concrete/controllers/single_page/dashboard/reports/page_changes.php, concrete/controllers/single_page/dashboard/system/permissions/denylist/range.php, concrete/controllers/single_page/dashboard/users/search.php, concrete/src/Application/Service/UserInterface.php, concrete/src/Controller/Traits/DashboardExpressEntryListTrait.php, concrete/src/Foundation/Runtime/Run/DefaultRunner.php, concrete/src/Http/ResponseFactory.php
The `*Response::create()` methods are [deprecated since Symfony 5.1](https://github.com/symfony/http-foundation/commit/bfe9753cf60ed93b11b6bbb8f680db17d1f72878) (and Concrete [requires at least version 5.2](https://github.com/concretecms/concretecms/blob/9.0.0/concrete/composer.json#L40)).
=> Avoid deprecated methods when creating responses

concrete/src/User/Group/Group.php
Just a minor change: we don't have to invoke `trim` when we don't include HTML in `Group::getGroupDisplayName()`.
Before (please remark the missing space after the last `/`):
After;
=> Fix formatting separator in Group::getGroupDisplayName()

concrete/src/Calendar/Event/EventService.php
As [reported in the forums](https://forums.concretecms.org/t/error-deleting-calendar-event/4105), there's an issue when deleting a calendar event in PHP 8.
That's not about simply referring to an undefined object property: that `E_WARNING` highlights that the code is buggy.
Indeed the `CalendarEvent` event doesn't have a `cID` property, and we'd like to use the `cID` property of the event version (but `CalendarEvent` doesn't implement the `__get` magic method, only `__call`).
=> Fix handling of page removal when deleting a calendar event

concrete/src/Http/ResponseFactory.php, concrete/src/Http/Service/Ajax.php, concrete/src/Validation/CSRF/Token.php
The Symfony Request class already offers this feature.
=> Deprecate Ajax::isAjaxRequest()

concrete/controllers/single_page/dashboard/system/mail/addresses.php, concrete/single_pages/dashboard/system/mail/addresses.php, concrete/src/Mail/MailServiceProvider.php, concrete/src/Mail/SenderConfiguration.php, concrete/src/Mail/SenderConfiguration/Entry.php
We currently have 7 email addresses that can be configured in the `System & Settings` > `Email` > `System Email Addresses` dashboard page.
At the moment, they are configured in a one-by-one way.
What adding some logic to it?
Furthermore, with the approach of this PR, even 3rd party packages can add their own configurable email address, with some code like this in the `on_start()` method of the package `controller.php` file:
```php
use Concrete\Core\Mail\SenderConfiguration;
class Controller extends Package
{
// ...
public function on_start()
{
$this->app->extend(
SenderConfiguration::class,
static function(SenderConfiguration $configuration): SenderConfiguration {
return $configuration->addEntry(
(new SenderConfiguration\Entry(t('Name of the option'), 'email.configuration.key')) …
```
=> Allow extending system email addresses configuration

concrete/config/concrete.php, concrete/src/Error/Handler/ErrorHandler.php, concrete/src/Error/Provider/WhoopsServiceProvider.php
This PR does the following:
- Collapses config into a single expandable item and adds `app` config. Instead of flatting our config this PR leaves it in its original hierarchical form which allows Whoops to show only the top level items with a control to expand
- Include PHP extensions name and version in the PHP output
- Hides all `_ENV` `_SERVER` and `_COOKIE` superglobal values by default. This can be overridden by extending the whoops service provider and adding your own custom `getDisallowedKeys` method.
Test this by navigating to `/dashboard/system/environment/debug/debug_example`, here's an example of the output I get with my test site: https://gist.github.com/KorvinSzanto/c2362c5f966ca9eb527a58631e2e61b3
=> Improve whoops error output

concrete/authentication/concrete/controller.php
See #10933 for the originating issue
This PR does the following:
1. Update "forever" cookie creation to also truncate down to 10 entries and prune any expired cookies
2. Include the token ID in the cookie value
3. Update "forever" cookie validation to extract the token ID and select the matching hash that way rather than trying to validate against all possible tokens
=> Make 14 day cookie more performant

concrete/blocks/express_entry_list/controller.php
Issue posted here: #10980 
The query modifiers were running first and then setColumns(). 
setColumns() was overriding what the query modifiers had done.
As a result, parameters like ccm_order_by and ccm_order_by_direction had no effect on the block.
I checked that this modification doesn't affect pagination.
=> Order query parameters are ignored by the express_entry_list block

concrete/src/Navigation/Item/PageItem.php
Fix PageItem class external link targets.  This allows for anchor links as nav targets in the top navigation bar block, that properly render, similar to autonav block.
=> Fix PageItem class urls

concrete/controllers/single_page/dashboard/system/permissions/users.php, concrete/single_pages/dashboard/system/permissions/users.php
This pull request modifies the user permissions dashboard single page to include some JS that alerts the administrator to the risk  of assigning either the `sudo` or the `edit_group_folder` permission. 
This dialog will only show if either the `sudo` or the `edit_group_folder` permissions are modified.
=> Warn admins when they are potentially giving more access than they expect

concrete/controllers/frontend/assets_localization.php, concrete/src/Form/Service/Widget/GroupSelector.php
The current Group selector is rather basic, and it's quite hard to use it when we have many groups.
In addition, it displays the breadcrumb HTML code.
What about refactoring it?
Current group selector (as of `develop` branch):
https://user-images.githubusercontent.com/928116/192971916-d36108c2-7637-422b-bc5b-6a297527dbb1.mp4
Group selector with this PR:
https://user-images.githubusercontent.com/928116/192972084-471b4142-7453-41a9-a2b7-bd2114181579.mp4
PS: this PR requires:
- #10963
- #10964
- https://github.com/concretecms/bedrock/pull/255
=> Add group selector

concrete/src/Authentication/Type/ExternalConcrete/ExternalConcreteService.php, concrete/src/Authentication/Type/OAuth/OAuth2/GenericOauth2TypeController.php
This pull request also makes it easier to enable state in custom services as well, before you needed to override the `handle_authentication_callback()` which I did like this in the past:
```php
public function handle_attach_callback()
{
$this->getService()->assertStateValid($this->app->make(Request::class)->get('state'));
return parent::handle_authentication_callback();
}
```
and a method on my service:
```php
/**
* Validate the given state
* @throws \OAuth\OAuth2\Service\Exception\InvalidAuthorizationStateException
*/
public function assertStateValid(string $state): void
{
$this->validateAuthorizationState($state);
}
```
Now all you need to do to support this in custom oauth2 services is override the `needsStateParameterInAuthUrl` and return true like the `ExternalConcreteService` does.
=> Add state parameter to external concrete authentication service

concrete/src/File/Image/Svg/Sanitizer.php
This PR disables entity expansion when loading SVGs into domdocument. There aren't any expansions that I could get working but disabling this anyway is good.
=> Prevent entity expansion when sanitizing SVGs

concrete/single_pages/dashboard/system/express/entities/associations/add.php
This PR sanitizes both the plural entity handle and the singular entity handle on the association add page. This prevents any sort of stored XSS when switching between association modes.
=> Sanitize plural entity handle on the association add page

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
This PR "migrate"s the session when a user logs in using an authentication type that relies on this generic oauth controller. The value of migrating the session is we end up with a new session ID which can make it more difficult for someone to guess or steal a session ID.
=> Migrate session when logging in with OAuth

concrete/blocks/express_entry_list/view.php, concrete/elements/express/search/menu.php, concrete/elements/files/search/menu.php, concrete/elements/groups/search/menu.php, concrete/elements/pages/search/menu.php, concrete/elements/users/search/menu.php, concrete/single_pages/dashboard/express/entries/entries.php, concrete/single_pages/dashboard/files/search.php, concrete/single_pages/dashboard/sitemap/search.php, concrete/single_pages/dashboard/users/groups.php, concrete/single_pages/dashboard/users/search.php
Search pages were vulnerable to reflected XSS for users using old browsers. This change sanitizes all the URLs on output and prevents XSS.
=> Prevent browser blocked reflected XSS in dashboard search pages

concrete/src/User/User.php
This PR makes the legacy salt functionality easier to read and changes the `==` check to an `===` check.
=> Make the legacy_salt functionality easier to read and use strict comparison

concrete/src/Mail/MailServiceProvider.php
Binding a big closure requires that PHP keeps it in memory.
The alternative approach of this PR saves 752 bytes of memory (320 instead of 1072).
=> Optimize configuration of system email addresses

concrete/single_pages/dashboard/users/groups/tree.php
This PR adds a warning interstitial when moving groups. Instead of updating bedrock to handle this in the `ConcreteTree` class I've opted to overriding the `dragRequest` method in order to make this change easy to backport.
=> Add warning interstitial when moving groups

concrete/single_pages/dashboard/system/api/integrations.php, concrete/single_pages/dashboard/system/api/integrations/view_client.php
This fixes XSS which was due to getName() function lacked sanitization on two places. This commit fixes this issue.
=> Fix XSS on API Integrations H1 1753684

concrete/themes/elemental/elements/footer.php
When installing Concrete with the elemental_blank starting point package, we have a footer referring to the good old concrete5.
Let's update it.
=> Update name and link of Concrete website in elemental theme footer

.github/workflows/phpunit.yml, composer.json, composer.lock, concrete/authentication/concrete/controller.php, concrete/controllers/backend/file.php, concrete/controllers/backend/tree.php, concrete/controllers/element/search/search_field_selector.php, concrete/controllers/panel/sitemap.php, concrete/src/Authentication/Type/ExternalConcrete5/ExternalConcrete5Service.php, concrete/src/Error/Handler/ErrorHandler.php, tests/tests/Cache/Driver/ZendCacheDriverTest.php, tests/tests/Controller/Backend/FileTest.php, tests/tests/FilesParseTest.php
This PR does a few things:
1. Backports the develop phpunit action to work with v8 tests using php 5.5 - 7.3 (7.4 tests fail due to errors thrown in third party code)
2. Adds `nikic/php-parser` to parse every php file in the project with php5 support and guarantee there aren't any scalar type hints in use
3. Fixes all issues that were identified by the new testing
=> Add github action for phpunit to v8 and test for PHP 5 support

concrete/attributes/select/form.php
This simply adds a 'for' attribute to each label alongside a checkbox, in an option list attribute.
- It means you can click the label to select the checkbox, instead of having to click the checkbox control itself. (and it now matches the behaviour of the individual checkbox attribute)
- Better accessibility.
=> Add missing for attribute to checkbox label of option list attribute

concrete/controllers/single_page/dashboard/system/mail/method.php, concrete/single_pages/dashboard/system/mail/method.php
In the `System & Settings` > `Email` > `SMTP Method` dashboard page we have this section:
The password is sent to the client, and it's rather easy to get it.
Since it's not necessary, what about this approach instead?
1. When users load the page, they see the following:
3. If they want to set a new password, they simply have to check the "Change" checkbox:
It's not possible to adopt a "leave blank to keep the current password" approach, since the SMTP password may be empty.
=> SMTP config page: don't send the SMTP password to the clients

concrete/bootstrap/configure.php, concrete/controllers/frontend/heartbeat.php, concrete/src/Application/Service/User.php, concrete/src/User/User.php
The route `/ccm/system/heartbeat` is [called every 30 seconds](https://github.com/concretecms/bedrock/blob/e9042c2e279e58c4ae58efe8799145589ad2d3bf/assets/cms/js/edit-mode/heartbeat.js#L6) when there's [some user activity](https://github.com/concretecms/bedrock/blob/e9042c2e279e58c4ae58efe8799145589ad2d3bf/assets/cms/js/edit-mode/heartbeat.js#L8) on the client side.
What about updating the value of the `uLastOnline` user field and the `uOnlineCheck` session key accordingly?
That way, the session validator won't think that users have been away too much whereas they are actually working on the client side (and so avoiding session invalidation if `concrete.security.session.invalidate_inactive_users.enabled` is set to `true`).
Also, we have the `ONLINE_NOW_TIMEOUT` global constant, which has …
=> Make it so heartbeat updates uLastOnline

concrete/blocks/express_form/controller.php
PR to fix #11031 
Express forms were not properly indexing their attributes leading to errors when trying to edit submitted data.
This affected Forms built from the block.
=> [v9][Bug] Express Forms data can't be edited

concrete/single_pages/dashboard/users/search/edit.php, concrete/src/User/UserInfo.php
| Before | After |
|---|---|
| ![Before](https://user-images.githubusercontent.com/928116/198406341-290d66fb-f2db-4ce5-add8-cdb56bbb7f46.png) | ![After](https://user-images.githubusercontent.com/928116/198406385-292068f3-2bf8-4bbc-b9ae-178bad9d6d4c.png) |
New details added:
- Last Password Change
- Last Seen Online
- \# Logins (this is already displayed in the users list page: any reason to not display it in the user details page?)
=> Add more info in user details dashboard page

concrete/src/Updater/Migrations/Migrations/Version20211023155414.php
Fix upgradeColorValue function : legacy value for alpha channel can now be equal to 0. It was changed to 1 if it was equal to 0.
=> [v9][Bug] Fix legacy alpha channel in upgradeColorValue function

concrete/src/Attribute/Key/Component/KeySelector/ControllerTrait.php
Hi all,
I found a bug regarding bulk updating page attributes.
When select multiple pages only the first one is updated.
This was due to a return statement which was executed in the foreach loop.
Therefor the other objects where never updates.
I moved the return statement and added a return type for PHP 8.
Kind Regards,
Laurens van Strijland
=> Bugfix: Bulk update for page attributes only saves first selected page

concrete/src/Express/Export/EntryList/CsvWriter.php
Fix undefined array key when exporting Express entries on PHP 8
=> Fix undefined array key

concrete/src/Antispam/Library.php
A fix for PHP 8: checking an array key exists before using it. Nothing to it. Explained in #11080
=> Antispam getByHandle broken with PHP 8

concrete/src/Localization/Address/Formatter.php
In commerceguys/addressing 1.4.0 they [introduced a breaking change](https://github.com/commerceguys/addressing/pull/167).
For ConcreteCMS v9 we can be adopt the fix of this PR (since inherited methods can have a return type that's stricter than the overriden methods).
For concrete5 v8 I don't see any other solution than the one I suggested in #11087
=> Add support for commerceguys/addressing v1.4+

concrete/composer.json
With commerceguys/addressing 1.4+ we have this error:
```
Declaration of
Concrete\Core\Localization\Address\Formatter::buildView(...)
must be compatible with
CommerceGuys\Addressing\Formatter\DefaultFormatter::buildView(...): array
```
See https://github.com/commerceguys/addressing/pull/167#issuecomment-1326323236
=> [v8] Avoid installing commerceguys/addressing 1.4+

concrete/src/Express/Export/EntryList/CsvWriter.php
A null results node id will cause `->getSiteByExpressResultsNodeID(...)` to throw an exception causing csv export to fail. Instead we should treat a null result node id as if the site is null and continue as usual.
=> Handle null results node ID in csv writer

concrete/src/Page/Collection/Collection.php
As explained in issue #11035 Any time a page loads, it loads blocks from all Global Areas in the site regardless of whether the area belongs to the current page or not. As a result, it also triggers the on_block_load event for blocks that are not on the page which leads to issues if listening to that event.
This PR does 3 things:
1. It fixes the method getGlobalBlocks() to only fetch global blocks for the current page
2. It adds a public getGlobalBlockIDs() method to mirror the get BlockIDs() method
3. It adds a protected getGlobalStacksForCollection() method used by the 2 other methods
Modifying getGlobalBlocks() to return only the blocks on the current page instead of all the blocks from all the global areas is possible because this method is only used twice in the core and both time in …
=> [v9][Bug][Perf. Improv.] All global areas' blocks loaded on every page load

concrete/elements/files/bulk/add_to_sets.php
Issue explained in #11122 
When trying to add files to file sets from the file manager, any file sets already selected is checked in the dialog but the hidden input representing each file set gets a value of 0. So when saving, those file sets get deselected.
This fixes it
=> [v9][Bug] "select fileset" dialog in file manager doesn't retain file set values

concrete/src/Page/Type/Composer/Control/Control.php
I get errors in PHP 8.2 due to this property not being declared.
=> Declare ::$page class property that's in use

concrete/src/Entity/Health/Report/Finding.php, concrete/src/Entity/User/GroupRoleChange.php, concrete/src/Entity/User/GroupSignupRequest.php
```
biplob@Biplobs-MacBook-Pro concretecms % c5 orm:validate-schema
Mapping
-------
[FAIL] The entity-class Concrete\Core\Entity\Notification\GroupSignupRequestNotification mapping is invalid:
* The mappings Concrete\Core\Entity\Notification\GroupSignupRequestNotification#signupRequest and Concrete\Core\Entity\User\GroupSignupRequest#notifications are inconsistent with each other.
[FAIL] The entity-class Concrete\Core\Entity\Notification\GroupRoleChangeNotification mapping is invalid:
* The mappings Concrete\Core\Entity\Notification\GroupRoleChangeNotification#groupRoleChange and Concrete\Core\Entity\User\GroupRoleChange#notifications are inconsistent with each other.
[FAIL] The entity-class Concrete\Core\Entity\Health\Report\SearchResult mapping is invalid:
* The field …
```
=> Fix entity mappings

concrete/blocks/html/composer.php
Fixes #11160
Maybe we can remove `$description` and `$class`.
There's no way to set them from editor interface.
=> Fix: HTML block breaks composer interface on PHP 8.1

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/registration/automated_logout.php, concrete/controllers/single_page/dashboard/users/search.php, concrete/single_pages/dashboard/system/registration/automated_logout.php, concrete/single_pages/dashboard/users/search/edit.php, concrete/src/Entity/User/User.php, concrete/src/Session/SessionValidator.php, concrete/src/Updater/Migrations/Migrations/Version20230107185800.php, concrete/src/User/UserInfo.php, tests/tests/Session/SessionValidatorTest.php
Close #10656
Here's the UI changes:
| Before | After |
|---|---|
| ![immagine](https://user-images.githubusercontent.com/928116/211175332-84d45788-6033-4e07-a53c-af0f1dfa64c5.png) | ![immagine](https://user-images.githubusercontent.com/928116/211175338-1057a29b-d096-428e-a76e-b369e7c43271.png) |
| ![immagine](https://user-images.githubusercontent.com/928116/211175501-65f2f572-da35-4dfc-8768-2913c6dd8ba9.png) | ![immagine](https://user-images.githubusercontent.com/928116/211175505-7dd63508-8218-4eca-84b6-aa031a8d98e7.png) |
| ![immagine](https://user-images.githubusercontent.com/928116/211175541-759a9d58-b6a7-4055-9e17-ec9738ebbd0d.png) | ![immagine](https://user-images.githubusercontent.com/928116/211175547-4021bd40-df30-4b19-aa38-b68ae3a53270.png) |
I think that this feature is rather …
=> Allow IP changes inside specific IP ranges

composer.lock, concrete/composer.json, concrete/src/Database/EntityManagerConfigFactory.php
Doctrine 2.14.1 comes with [this breaking change](https://github.com/doctrine/orm/pull/10321).
This causes Concrete to break with an `E_COMPILE_ERROR` error:
```
Doctrine\Common\Annotations\AnnotationRegistry::registerFile():
Failed opening required 'doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php'
```
If this was the reason of 18b82169a87cd6821d19402e0cca48cf84a27aa5 (its description isn't descriptive that much :wink:), we can fix the issue by simply avoiding the `registerFile()` call (it's useless since `doctrine/annotations` 1.10, and we require `^1.13.2`).
=> Support doctrine/orm 2.14+

concrete/src/Job/QueueableJob.php
Minor fix to an incorrect annotation param typehint in `concrete/src/Job/QueueableJob.php`
=> fix incorrect typehint in queueable job class

concrete/src/Config/FileSaver.php
Make changes to config files atomic, as discussed by https://github.com/concretecms/concretecms/issues/11170. A put() to file has been replaced with a replace(). See concrete/vendor/illuminate/filesystem/Filesystem.php 
https://github.com/illuminate/filesystem/blob/6ca65f4f24d3277e22b8e8e7c62557c118209d0f/Filesystem.php#L188 https://github.com/illuminate/filesystem/blob/6ca65f4f24d3277e22b8e8e7c62557c118209d0f/Filesystem.php#L200
The illuminate replace() method does not have an actual return flag as the put() method does, however, the !==false test will return true and allow the following OpCache::clear() to be called.
=> Make changes to config files atomic

concrete/blocks/image_slider/form_setup_html.php
Today I had a message from a customer that he can't see the entries of his image_slider block. In the console there was a javascript error saying 
```
Uncaught SyntaxError: '' string literal contains an unescaped line break
```
So I looked in the Database and found a line break in the URL field of one entry.
I think it's not necessary to show the field as a textarea, at least it's a URL. So I changed this in the form of the block to prevent this kind of error.
=> change image_slider URL field to input

concrete/authentication/community/controller.php
The URL of the Concrete community memers changed from
`https://community.concretecms.com/profile/-/view/<UserID>/`
to
`https://community.concretecms.com/profile/<UserID>`
For example, [this doesn't work](https://community.concretecms.com/profile/-/view/35655/), but [this does](https://community.concretecms.com/members/profile/35655).
=> Fix member profile url

concrete/blocks/top_navigation_bar/edit.php
I could never find a combination of steps and settings to reproduce the error reported (reported in #11234, [here](https://forums.concretecms.org/t/changing-logo-in-atomik-causes-errors/5028), and [here](https://forums.concretecms.org/t/topnavigationbar-raises-error-undefined-variable-brandingtext/4627)), but this null coalescing operator should help
=> Fix #11234 Add check for $brandingText

concrete/blocks/breadcrumbs/controller.php
When I developed the breadcrumb block type, I set the cache lifetime as the same value as autonav.
Now I think it's nonsense because the feature of breadcrumb block type is almost similar with page title. 5 minutes is too short.
Let's change the lifetime to forever (same value as page title).
Related Issues: #9600, #11240, #11245, #2786
=> Change cache lifetime of breadcrumb blocks to forever

concrete/controllers/single_page/download_file.php, concrete/src/Entity/File/Version.php
Fixes #11217
Rather than defaulting to forced downloads for all files that don't have a public URL, assume that the request really did want to use the `download` method rather than the `force_download` method.
=> Add support for displaying files in browser when outside webroot

concrete/blocks/gallery/controller.php, concrete/blocks/next_previous/controller.php, concrete/blocks/switch_language/controller.php, concrete/blocks/topic_list/controller.php
Some block types are disabled output cache, but I think there's no reason to keep them off.
I think we can enable block cache for gallery block because image or image_slider block supports output cache.
Also, I wonder why `$btCacheBlockRecord` is `false` .
I think we can enable block cache for next previous and switch language because autonav supports output cache. 
Lifetime 300 is same as autonav block.
I guess we can enable block cache for topic list when it just show the list of topics and doesn't update the view.
It means we should disable block cache for search result pages.
#2786, #11238
=> Improve block cache support

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/optimization/cache.php, concrete/single_pages/dashboard/system/optimization/cache.php, concrete/src/Page/Page.php
fixes #11244
This is a test page that contains a page list block.
before: max-age is 6 hours (global settings)
after: max-age is 5 minutes (comes from page list block controller)
=> Cache lifetime should respect lifetime of each block on the pages

concrete/src/Page/Type/Type.php
I got the `Undefined array key "name"` error on changing the order of page types.
This PR fixes the the undefined array key errors.
```
/path/to/concrete/src/Page/Type/Type.php(890): Whoops\Exception\ErrorException->null
/path/to/concrete/src/Page/Type/Type.php(890): Whoops\Run->handleError
/path/to/concrete/controllers/single_page/dashboard/pages/types/organize.php(33): Concrete\Core\Page\Type\Type->update
/path/to/concrete/src/Controller/AbstractController.php(318): Concrete\Controller\SinglePage\Dashboard\Pages\Types\Organize->submit
/path/to/concrete/src/Controller/AbstractController.php(318): null->call_user_func_array
/path/to/concrete/src/Http/ResponseFactory.php(193): Concrete\Core\Controller\AbstractController->runAction
/path/to/concrete/src/Http/ResponseFactory.php(372): …
```
=> Fix: enable to change the order of page types

concrete/single_pages/dashboard/system/environment/proxy.php, concrete/single_pages/dashboard/system/multisite/sites/form.php, concrete/src/Mail/SenderConfiguration.php
Domains for multisite hosting and proxies accept anything. We should accept just URLs (addresses #11106). Same for proxy port.
And fixed a typo.
=> Fix: limit fields to specific types

concrete/elements/page_controls_footer.php
This is a feature request from my client. There's no notification message when you visit the page that was already closed. Let's add it like publigh pending message.
=> Add notification message for closed page.

composer.json, composer.lock, concrete/composer.json
What about adding the `dependency-patches` composer package to the core?
Also, let's rename it from `concrete5/dependency-patches` to `concretecms/dependency-patches`, accordingly to https://github.com/concretecms/dependency-patches/commit/850c21a1ab5925900bc4be9b764600967a41380b
=> [v8] Require Concrete dependency patches in the core

concrete/src/Antispam/Service.php
The submission type is an important piece of information when judging how to check for Spam. It should be included in the data sent over to the antispam service.
All the core blocks using the antispam service set a type to differentiate them.
That information doesn't reach the active antispam library. This PR fixes this.
=> Sending over the submission type to the active Antispam service

concrete/blocks/express_form/controller.php
When using the antispam, the Express form block and the legacy form block both use the same handle 'form_block'.
They are very different and when checking their submission for spam, it is important to be able to tell them apart.
This PR changes the Express Form block antispam handle to 'express_form_block'
=> Modify the Express Form block antispam handle

concrete/config/concrete.php, concrete/controllers/single_page/dashboard/system/files/uploads.php, concrete/single_pages/dashboard/system/files/uploads.php, concrete/src/File/Service/File.php
Please include this PR in the 9.2 release!
Before version 9, multibyte characters were removed from the file name on sanitization.
However, version 9 generates weird file names for Japanese users because it happening to start using asciify on sanitizing file names (It looks like a mix of Chinese words and Japanese words). 
Please accept adding a config option to sanitize file names without asciify as same as before.
Related issue: #10183
Related PR: #11083
=> Add a config option to disable asciify for uploaded files

concrete/src/Page/Collection/Collection.php
This fixes a functionality that was incorrectly refactored, causing a key to be missing from the `$row` array in the function `Collection::getByHandle`, see 8c4bdbd. This error wasn't apparent until run via PHP 8 which will complain about the missing array key a few lines down.
=> Add missing column alias in Collection::getByHandle

concrete/src/Support/CodingStyle/Fixer/InlineTagFixer.php, concrete/src/Support/CodingStyle/PhpFixerRuleResolver.php
With these changes, the `c5:phpcs` CLI command can change this code;
```php
<?php    echo     $form->label('id', 'text')  ; ?>
```
to
```php
<?= $form->label('id', 'text') ?>
```
=> Add inline_tag PHP CS Fixer, use echo_tag_syntax PHP CS Fixer

concrete/src/Health/Report/Test/Test/CheckConfigUrlSettingsForProductionTest.php
`League\Url\Url::getScheme()` returns an instance of `League\Url\Components\ComponentInterface` and not a `string`, so this strict equality check always fails.
Let's fix it.
=> Site Health: fix checking HTTPS canonical URL

concrete/blocks/tags/controller.php, concrete/controllers/dialog/event/edit.php, concrete/controllers/panel/detail/page/attributes.php, concrete/controllers/panel/detail/page/seo.php, concrete/controllers/single_page/dashboard/system/basics/name.php, concrete/src/Attribute/AttributeInterface.php, concrete/src/Attribute/Command/SaveAttributesCommandHandler.php, concrete/src/Attribute/Controller.php, concrete/src/Express/Form/Control/SaveHandler/AttributeKeySaveHandler.php, concrete/src/Page/Type/Composer/Control/CollectionAttributeControl.php, concrete/src/User/UserInfo.php
When we render the attributes, [we pass the attribute owner to attribute controllers](https://github.com/concretecms/concretecms/blob/9.1.3/concrete/src/Attribute/View.php#L157).
What about doing the same when creating attribute values from request?
=> Pass the attribute owner to attribute controllers when creating values from request

concrete/controllers/single_page/dashboard/system/permissions/antispam.php, concrete/src/Antispam/Service.php
It is incorrectly spelled in two file, I have changed it.
closes issue : #11352
In antispam.php :
from
$this->set('allowlistGroup', Config::get('concrete.spam.allowist_group', Config::get('concrete.spam.whitelist_group')));
to
$this->set('allowlistGroup', Config::get('concrete.spam.allowlist_group', Config::get('concrete.spam.whitelist_group')));
In service.php : 
from
return Group::getByID(Config::get('concrete.spam.allowist_group', Config::get('concrete.spam.whitelist_group')));
to
return Group::getByID(Config::get('concrete.spam.allowlist_group', Config::get('concrete.spam.whitelist_group')));
=> Replaced allowist to allowlist in all files, Now it is consistent.

concrete/blocks/express_form/controller.php
=> use the Express Entry's publicIdentifier after submitting a public form

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
The $extractor property may be null if we don't call getExtractor()
=> OAuth: Use getExtractor() method instead of accessing $extractor property

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
The actual fix is in the first commit (we had a *Class "RedirectResponse" not found* error).
=> Fix FQ class name of RedirectResponse in GenericOauthTypeController

concrete/src/Authentication/Type/OAuth/OAuth1a/GenericOauth1aTypeController.php, concrete/src/Authentication/Type/OAuth/OAuth2/GenericOauth2TypeController.php, concrete/src/User/User.php
The `User::isLoggedIn()` static method [is just a wrapper](https://github.com/concretecms/concretecms/blob/9.1.3/concrete/src/User/User.php#L87-L96) around `User->isRegistered()` instance method.
=> Use User->isRegistered() instead of User->isLoggedIn()

concrete/authentication/facebook/controller.php, concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
This PR includes 2 fixes:
- [`BindingService::clearBinding()`](https://github.com/concretecms/concretecms/blob/39d22c688fa7df8831404a61194b391a33c6486e/concrete/src/Authentication/Type/OAuth/BindingService.php#L38) accepts these parameters:
- `$userId`
- `$binding`
- `$namespace`
In `GenericOauthTypeController` the order of `$binding` and `$namespace` was inversed (thus, the affected record in `OauthUserMap` was not deleted).
In the facebook controller I *think* the order of `$userId` and `$binding` was inversed (but I'm not sure about that).
- `handle_detach_attempt()` also [tries to invalidate the token](https://github.com/concretecms/concretecms/blob/39d22c688fa7df8831404a61194b391a33c6486e/concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php#L561): in case the token …
=> Fix oauth detaching

composer.lock
[Changelog](https://github.com/concrete5-community/translation-library/compare/1.7.1...1.7.2).
Close https://github.com/concretecms/concretecms/issues/11252
=> Update translation-library from v1.7.1 to v1.7.2

concrete/src/Search/Pagination/PermissionablePagination.php
The PermissionablePagination class was missing its parent constructor call. The Pagerfanta constructor is still called in the Pagination constructor.
=> add missing parent constructor call

concrete/src/Permission/Access/WorkflowAccess.php
Simple fix to avoid undefined property error
=> Fix Undefined property error on PHP 8 in WorkflowAccess class

concrete/src/User/Group/Search/ColumnSet/Available.php
They are called statically and they don't contain any reference to $this
Fix #11412
=> Make ColumnSet\Available methods static

concrete/src/Updater/Migrations/Migrations/Version20220909000000.php, concrete/src/Updater/Migrations/Migrations/Version20220909100000.php
In #11401 we renamed the file name but not the class name of a couple of migrations
=> Fix a couple of wrong migration names

concrete/src/User/User.php
At the moment, we are throwing the `on_user_logout` event in the middle of the "logout" process: we should call it at the end of the process.
=> Move the on_user_logout event at the end of the logout

concrete/src/Navigation/Item/PageItem.php
This only addresses one of the items mentioned in #10556. The PageItem::getURL() method appears to be used in more places than just the Top Navigation Bar block so this will also impact other parts of Concrete CMS. This may or may not be desired.
=> make PageItem respect replace_link_with_first_in_nav attribute

concrete/controllers/single_page/login.php, concrete/src/User/Event/Logout.php, concrete/src/User/User.php
This PR:
- introduces a new `on_before_user_logout` event
- pass an instance of `Concrete\Core\User\Event\Logout` to the `on_before_user_logout`/`on_user_logout` events
- let people hook one of those two events to define the URL to be called after the current user has been logged out
=> Add on_before_user_logout, enable customization of post-logout URL

concrete/src/Mail/Service.php
Just something we noticed consulting the documentation https://documentation.concretecms.org/api/9.1.3/Concrete/Core/Mail/Service.html
=> Fix $bcc member variable description

concrete/src/Cache/Driver/RedisStashDriver.php, concrete/src/Session/SessionFactory.php
This fixes the following error:
```
Undefined array key "scheme"
in concrete/src/Cache/Driver/RedisStashDriver.php:132
```
=> Fix Undefined array key "scheme" in redis drivers

concrete/attributes/select/controller.php, concrete/src/Entity/Attribute/Value/Value/SelectValue.php
Let's avoid calling `getValue()` twice, and add some phpdoc
=> Optimize getSelectedOptions() method of select attribute

concrete/src/Http/Client/Factory.php
At the moment, it's not possible to create an HTTP client adding some some custom options to the default one.
For example, let's say we'd like to use the default options, but specifying a custom User Agent: we can't.
Indeed, at the moment, to create a client we can only:
- [use the default options](https://github.com/concretecms/concretecms/blob/9.2.0/concrete/src/Http/Client/Factory.php#L75), without the possibility to use custom ones
- [use custom options](https://github.com/concretecms/concretecms/blob/9.2.0/concrete/src/Http/Client/Factory.php#L90), without the possibility to use the default ones
In theory, we could make the [`getOptions()` method](https://github.com/concretecms/concretecms/blob/9.2.0/concrete/src/Http/Client/Factory.php#LL39C24-L39C34) public, but that would break …
=> Add getDefaultOptions() to HTTP client factory

concrete/src/Logging/Search/ColumnSet/DefaultSet.php
This PR fixes these two warnings:
```
call_user_func() expects parameter 1 to be a valid callback, non-static method
Concrete\Core\Logging\Search\ColumnSet\DefaultSet::getCollectionLevel()
should not be called statically
```
```
call_user_func() expects parameter 1 to be a valid callback, non-static method
Concrete\Core\Logging\Search\ColumnSet\DefaultSet::getFormattedMessage()
should not be called statically
```
=> Fix warnings when viewing /dashboard/reports/logs

concrete/src/Authentication/Type/OAuth/GenericOauthTypeController.php
`!` has a higher precedence than `&&`
=> Fix check in createUser of Oauth controller

concrete/elements/page_types/composer/form/output/buttons.php
Attempting to revert a page to draft doesn't work. JS Console shows an error about an unrecognised expression. This is due to a missing "]". See #11460
=> Fix #11460

concrete/blocks/feature/controller.php
Using the feature block, if the icon is not selected, an exception occurs with PHP 8.x due to an undefined array index. This happened to me when I installed a marketplace theme that swapped content, that used invalid icon names.
=> Fix exception when icon is not set in PHP 8.x

concrete/controllers/dialog/block/design.php
I see this error in the logs:
concrete/controllers/dialog/block/design.php:73: Undefined array key "bFilename"
Let's fix this issue.
=> Fix accessing undefined array index in dialog/block/design.php

concrete/controllers/frontend/assets_localization.php
Declare width, height and size in ccmi18n_filemanager object is used in ConcreteFileChooser component
See this file https://github.com/concretecms/bedrock/blob/master/assets/cms/components/file-manager/Chooser/Files.vue
=> Declare width and height ccmi18n_filemanager property that's in use

concrete/elements/files/edit/image_editor/toast.php
See these sample sessions to see why this is needed
https://github.com/concretecms/concretecms/assets/928116/ef9ac302-70e6-4593-944f-1d2145eabe7c
https://github.com/concretecms/concretecms/assets/928116/8eced0e0-fb29-431c-9988-e183a1e29690
=> Reload page when image editor creates a new image version

concrete/views/dialogs/file/versions.php
When we change the currently approved file version, we have to change the version details page, otherwise we still see the previously approved file version.
See for example:
https://github.com/concretecms/concretecms/assets/928116/31379bda-03d9-45cd-9007-af4e9f73ab03
https://github.com/concretecms/concretecms/assets/928116/744df598-29ea-4394-bf63-f0e9f5b19cb1
=> Reload current page if currently approved file version changes

concrete/src/Authentication/Type/OAuth/ServiceProvider.php, tests/tests/Authentication/OAuth/ServiceProviderTest.php
When we have a problem with the oauth authentication, people will see an empty page.
That's because the `ccm/system/authentication/oauth2/...` route callback simply returns nothing.
What about handling errors the standard Concrete way (display the error details if the system is configured so, or the generic "An error occurred" message otherwise)?
In addition:
- let's use static closures whenever possible (they require less memory)
- let's use app->singleton() instead of the deprecated app->bindShared()
- let's avoid aliases and closures
=> OAuth service provider: avoid deprecated methods, display errors

concrete/src/Application/Application.php, concrete/src/Foundation/Runtime/Run/CLIRunner.php, concrete/src/Foundation/Runtime/Run/DefaultRunner.php
We used to use the `C5_ENVIRONMENT_ONLY` php constant to setup the Concrete environment, without doing anything.
At the moment, this is only partially supported: we use `C5_ENVIRONMENT_ONLY` to determine [if we are running via CLI](https://github.com/concretecms/concretecms/blob/9.2.0/concrete/src/Application/Application.php#L305), but we don't actually respect this setting later on.
For example, we could use some code like this:
```php
const C5_ENVIRONMENT_ONLY = true;
const DIR_APPLICATION = '/path/to/project/root';
$app = require_once DIR_BASE . '/concrete/dispatcher.php';
echo "Here we are!\n";
echo '$app is an instance of ', get_class($app), "\n";
```
At the moment, Concrete thinks we are in a normal CLI environment, doesn't see the command to be executed, and quits showing the list …
=> Fix support for C5_ENVIRONMENT_ONLY env variable

concrete/src/Package/Offline/PackageInfo.php, concrete/src/Package/Offline/Parser.php, concrete/src/Package/Offline/Parser/FiveSeven.php, concrete/src/Package/Offline/Parser/Legacy.php, concrete/src/Package/Package.php, tests/helpers/Package/PackageForTestingPHPVersion.php, tests/tests/Package/MinimumPHPVersionTest.php
Package developers may require that users have a PHP version greater than the minimum PHP version required by the core (think for example about packages developed for concrete5 v8 that require PHP 7.4 instead of PHP 5.5).
So, what about adding a way to let packages declare the minimum PHP version they are meant to be used with?
=> Let packages declare their minimum supported PHP version

concrete/controllers/dialog/logs/delete_all.php
When we clear the logs in the /dashboard/reports/logs dashboard page, we see a nice message telling us that the log has been cleared successfully, but we still see all the logs in the page.
What about reloading the page? That way users will see that the logs have been actually deleted.
=> Reload the logs page when the log registry is emptied

concrete/src/Package/PackageService.php
What about preventing the core from breaking in case PHP throws `Error`s (which are not `Exception`s but, like `Exception`s, are `Throwable`s)  when trying to load a package `controller.php` file?
=> Catch Throwable instead of Exception in PackageService::getClass()

concrete/single_pages/dashboard/extend/install.php, concrete/src/Package/BrokenPackage.php, concrete/src/Package/Package.php, concrete/src/Package/PackageService.php
Examples:
1. When a package `controller.php` file does exist, or does not define the correct class name (`Controller`) in the correct namespace (`Concrete\Package\PascalCasePackageHandle`):   
2. When the package controller does not extend `Concrete\Core\Package\Package`:   
3. When PHP can't correctly parse the package controller:
=> Check that package controllers extend Package, show why a package is broken

concrete/src/Command/Task/Output/MemoryOutput.php
I'm playing with tasks, and I'm missing a way to have a list of task messages.
We currently have output implementations that send messages to the console and to a Mercure instance: what about adding an output that simply stores the messages in memory?
=> Add MemoryOutput for tasks

concrete/src/Search/Pagination/Pagination.php, concrete/src/Search/Pagination/PermissionablePagination.php
It's already been fixed in 9.x. Let's fix it in 8.x as well.
Please let me know if I should open the PR aginst `8.6.x-dev` branch.
=> Fix pagination constructor: __construct cannot return a value

concrete/controllers/single_page/dashboard/calendar/events.php, concrete/single_pages/dashboard/calendar/events.php, concrete/src/Page/Controller/DashboardCalendarPageController.php
In the /dashboard/calendar/events dashboard page, weeks always start on Sundays.
That's not the case everywhere.
So, let's show the first weekday accordingly to the current locale.
=> First weekday in dashboard calendar as defined by current locale

.github/workflows/build-assets.yml, build/libraries/built-assets.js, build/webpack.mix.js
This PR a brand new GitHub Action that:
- checks that building the assets works
- checks that git-skip and git-revert work (they weren't working: I've added a fix for this - see a877e407188ebc57d6feef8dc125fa10b8bf08e7)
- if the built assets are changed, they are committed back to the repository (that way, in order to publish new built assets we only need to fix their source code and/or the dependencies in `build/package-lock.json`)
In addition, I've updated the build process: now the built assets only use Unix line endings (`\n`) instead of a mix of `\r\n` and `\n`.
=> Test build system, automatically commit built assets
